### ISSUE TITLE
Text is duplicated with TextAreaRow

### ISSUE THREAD

**Issue by Dean151** [xmartlabs/Eureka#1]
I've found a graphic bug that occurs with TextAreaRow ;

I want to use that row to display non editable disclaimer text.
But when I do using the value property, a label is present with a duplicated version of the text.

I tried to force to an empty string the title and the placeholder with the same result.
Here is a screenshot of what happens. I've scrolled a little to be sure that the text is visible. It doesn't scroll and stay at the center.

![simulator screen shot 30 sept 2015 11 58 59](https://cloud.githubusercontent.com/assets/8696821/10200794/67952e7e-6776-11e5-860d-be69e3431d8c.png)

Here is the code I use for this particular row : 

    <<< TextAreaRow("disclaimer") {
                $0.value = NSLocalizedString("DISCLAIMER", comment: "")
                $0.disabled = true
            }

**Comment by Dean151** [comment]
This problem does not occurs if I set my text in placeholder instead of value, but this row does not allow to change the placeholderColor, so it results with the disabled state with a very bright gray.

**Comment by xinwo** [comment]
any solution?

**Comment by mtnbarreto** [comment]
@Dean151 It was a small issue in my end.
Now it should work.
Thanks
