### ISSUE TITLE
Data binding?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#100]
Does Eureka contain any automatic data binding between the storage object and the form fields?

For example if you use [Couchbase-Lite](http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/model/index.html) or [Realm](https://realm.io/) the form field tags should automatically be mapped to the object property names.

Absolutely awesome would be a "two-way-data-binding" between object and form, similar to the one AngularJS contains - is there anything like this already present in Eureka or planned?

**Comment by mats-claassen** [comment]
Hi, we are not planning to integrate Data binding because we think it is outside of Eureka's scope.
You can obviously create a plugin to integrate Eureka with Realm or Couchbase-Lite yourself.

**Comment by marbetschar** [comment]
Hi @mats-claassen 
I understand your decision and appreciate all the work you've already put into Eureka!
So for me, digging a bit further into a possible plugin: Is there already any documentation available on how to build such a plugin best?
