### ISSUE TITLE
Question on the event triggered when reordering rows in multivalued sections 

### ISSUE THREAD

**Issue by jasonho215** [xmartlabs/Eureka#1004]
As said, is there any event triggered when reordering the rows in multivalued section? 

The order is important to me but I found that the form.values returns a dictionary which is not according to the order of rows in current view. Provided that there is only one section in the form.

Thanks for all your attention

- Environment: Eureka -> master branch(up to date) , Xcode ->8.3.1,  iOS -> 10.3

**Comment by Carpemeid** [comment]
I've just saved the sections I'm interested in in some ivars and then the section itself represents the collection of rows in the correct order.
