### ISSUE TITLE
IOS : Add cancel bar button in popover selector options (Mobile view).

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [xmartlabs/Eureka#1006]
Hi there,

 How can i add cancel bar button in popover selector option menu, while creating "Eureka Forms" in mobile view. One way to close the popover option menu is to select a value, but i need to close without it. Refer the below image, 

<img width="417" alt="eureka-popoverselector" src="https://cloud.githubusercontent.com/assets/17313049/25116439/6b439dae-242a-11e7-8f88-30a413da2e04.png">

Thanks.

**Comment by santiagofm** [comment]
hey @ThiyagarajanShivSankaran ! Could you achieve this ?
Cheers

**Comment by ThiyagarajanShivSankaran** [comment]
@santiagofm yeah buddy. Actually, I am adding a custom row  while presenting popover with dismiss button. While clicking on that popover will be dismissed.

**Comment by santiagofm** [comment]
@ThiyagarajanShivSankaran Awesome ! I'm closing this issue then.
If you don't mind please post how you did it for future reference !
Cheers
