### ISSUE TITLE
InsertAnimation for rows doesn't work

### ISSUE THREAD

**Issue by alexsanderkhitev** [xmartlabs/Eureka#1009]
Animation for the section works, but for row does not. How can I fix it? Thanks.

My code 

```swift
    override func insertAnimation(forSections sections: [Section]) -> UITableViewRowAnimation {
        if isGetUpdatedCard {
            debugPrint("section auto")
            return .automatic
        } else {
            return .none
        }
    }
    
    override func insertAnimation(forRows rows: [BaseRow]) -> UITableViewRowAnimation {
        if isGetUpdatedCard {
            debugPrint("row auto")
            return .automatic
        } else {
            debugPrint("row none")
            return .none
        }
    }
```

**Comment by mats-claassen** [comment]
What do you mean by `does not work`? Is there no animation?
Did you try with different `UITableViewRowAnimation`?

**Comment by alexsanderkhitev** [comment]
@mats-claassen hello!
I did not have the code to turn off the animation for row (although it was called), but the animation still occurred, but it only happened on the simulator. On a real device, everything is fine, I'm sorry that I did not close the issue. Thank you.
