### ISSUE TITLE
Type Form doesn't conform to protocol MutableCollection

### ISSUE THREAD

**Issue by mamdouhweb** [xmartlabs/Eureka#1011]
<img width="1146" alt="screen shot 2017-04-21 at 5 47 31 pm" src="https://cloud.githubusercontent.com/assets/1148114/25297266/a2d83a80-26ba-11e7-8bac-a9af4b8a3ad8.png">

- Environment: Eureka 3.0.0, XCode 8.3, IOS 10.2

I'm trying to run the basic example, however, XCode is throwing 3 errors on build. 

1- Type Form doesn't conform to protocol MutableCollection
2- Type Form doesn't conform to protocol RangeReplicableCollection
3- Type Form doesn't conform to protocol _MutableIndexable

**Comment by mtnbarreto** [comment]
@mamdouhweb have you solved the issue?

**Comment by mamdouhweb** [comment]
It's not a Eureka issue, I just updated my XCode to latest and it worked
