### ISSUE TITLE
Code Samples and Tutorials for Custom Rows in Swift 3.1 ?

### ISSUE THREAD

**Issue by allanrojas** [xmartlabs/Eureka#1012]
Hi,

So, the sample code and the tutorials on the xmartlabs blog don't work with Swift 3.1... any plans for updating those? I'm interested in porting my app from Swift 2.3 to Swift 3.1, but it has plenty of custom rows and my first attempt was a total disaster...

**Comment by jacobo360** [comment]
same issue here..!

**Comment by mats-claassen** [comment]
Hey @allanrojas @jacobo360 We are working on bringing the blogs up to date. Thanks for pointing this out.

**Comment by mats-claassen** [comment]
The [Eureka custom row tutorial](https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/) has been updated to work with the latest version.

**Comment by m-revetria** [comment]
Closing this
