### ISSUE TITLE
Get Values from Multivalued sections

### ISSUE THREAD

**Issue by sasquatchgit** [xmartlabs/Eureka#1015]
+++ MultivaluedSection(multivaluedOptions: [.Reorder, .Insert, .Delete],
        header: "Options",
        footer: "footer") {
                            $0.addButtonProvider = { section in
                                return ButtonRow(){
                                    $0.title = "Add New Option"
                                }
                            }
                            $0.multivaluedRowToInsertAt = { index in
                                print(self.form.values())
                                return NameRow() {
                                    $0.placeholder = "Your option"
                                }
                            }
                            $0 <<< NameRow() {
                                $0.placeholder = "Your option"
                            }
    }
Now I want to extract all the values in NameRows at the end. There can be any number of rows(based on user input). This is what I tried:

self.form.values() but it results in [ : ].

How do I get all the values?

**Comment by sasquatchgit** [comment]
For anyone with similar issue:
http://stackoverflow.com/questions/43576317/get-form-values-from-multivalued-sections-of-eureka-form

**Comment by mtnbarreto** [comment]
@sasquatchgit  Thanks for answering yourself.. 
Notice that this approach is not totally perfect, you might duplicate tags causing some issues, in particular when the user reorder and delete rows in addition to insert new ones.

Lets say you add 2 rows with tag_1 and tag_2 as tags respectively and then reorder them moving tag_2 row to the top the the section, then remove the second row   (tag_1 row) and add a new one. In this case you will generate another row having tag_2 as id and the app will crash.

**Comment by sasquatchgit** [comment]
@mtnbarreto Thanks a lot for the insight. Any other approach to avoid this? Share if you have any idea, I'll implement and let you know if that works.

**Comment by Sweeper777** [comment]
@sasquatchgit I think you should just get all the values from all the rows in a multivalued section, put them all in an `[Any]`, and use the section's `tag` as the key and the `[Any]` as value to put it as an entry in the dictionary returned by `values()`.

**Comment by klwoon** [comment]
@Sweeper777 Could you show some example codes how to do it? I can't figure it out, thanks.
