### ISSUE TITLE
How do you customize from a nib file in 3.0.0?

### ISSUE THREAD

**Issue by fortybillion** [xmartlabs/Eureka#1016]
The Eureka 3.0.0 release notes say "Most cells can now be customized with nib files."

What's the correct way to accomplish this?

**Comment by m-revetria** [comment]
Hi @fortybillion, you need to create a xib with a `UITableViewCell` and make it inherit from one of the form cells. Then you will be able to connect the outlet to the appropriate views, like the `UITextField` in the `TextCell`.

You can follow one of the example in [CustomDesign](https://github.com/xmartlabs/Eureka/tree/master/Example/Example/CustomDesign). 

Cheers

**Comment by m-revetria** [comment]
Closing this
