### ISSUE TITLE
For MultiValuedSection, how to make a buttonRow with customized UI?

### ISSUE THREAD

**Issue by fans3210** [xmartlabs/Eureka#1017]
I want to make a custom cell & row used for inserting rows in multivaluedsection as shown below:
<img width="363" alt="screenshot 2017-04-25 14 58 17" src="https://cloud.githubusercontent.com/assets/6023208/25372364/a91177da-29c7-11e7-860c-243ba72457d1.png">
The cell is almost the same as apple's default inserting cell. The only difference is in the button color

What I found is that multivaluedsection's addbuttonprovider is a type of (MultivaluedSection) -> ButtonRow which makes it impossible to use a normal row as the inserting row.

So I subclassed _ButtonRowOf which accepts my custom cell
`final class NCCustomInsertRow: _ButtonRowOf\<NCCustomInsertCell\>, RowType`

Then I want to override

:
` public func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCellEditingStyle`

in my vc and make such change:

```
        if section.multivaluedOptions.contains(.Insert) && indexPath.row == section.count - 1 {
            return .none
        }
```

 the but I failed since this func is not open and allowed to be overridden. 

So how can I make a custom inserting row?

**Comment by santiagofm** [comment]
Hey @fans3210 ! Are you still having this issue ?

**Comment by fans3210** [comment]
@santiagofm . Yes I still have such issue since I didnt't update the library yet. Do you have any suggestion?

**Comment by fans3210** [comment]
If the func: public func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCellEditingStyle is overridable in _ButtonRowOf class. Then I would define a custom row with the inserting feature with my custom blue add buttons

**Comment by m-revetria** [comment]
Hi @fans3210 recently we merged into master a fix that makes that function open to be overridden. You can check the changed in PR #1113.

Regards

**Comment by mohammdsss1** [comment]
@fans3210  hey man,
How did you changed that plus button icon?

**Comment by jacktiong92** [comment]
@fans3210 Hi! Have you managed to customise the add button?

**Comment by fans3210** [comment]
@jacktiong92 , I just used a custom add button, nothing special

**Comment by jacktiong92** [comment]
@fans3210 Can you please kindly show me the way to do it?
I have actually created an issue here: [https://github.com/xmartlabs/Eureka/issues/1832](url)

**Comment by fans3210** [comment]
@jacktiong92 I don't quite remember since is long time ago and I haven't been using it for a while. So my solution might be outdated already. But if I remember correctly. The difficult part is not customise the cell since u can customize the cell based  on what u like. The difficult part is to make a custom row which warps that cell and behave like a 'insert row". 
Have to check on this library's source code. They used buttonRow as an insert row in their multiValuedSection. The trick is in this function from their sourcecode:
`public func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCellEditingStyle`
They made their insert row in this function. We have to override it to suit our needs. The details I already mentioned in my questions.
