### ISSUE TITLE
How to set the presentation style of a custom selector row?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#1018]
I made a custom row like this:

```swift
final class MyRow: SelectorRow<PushSelectorCell<SomeType>, SomeVC> {
    required init(tag: String?, _ initializer: ((MyRow) -> ())) {
        super.init(tag: tag)
        initializer(self)
        presentationMode = PresentationMode.presentModally(controllerProvider: ControllerProvider.storyBoard(storyboardId: "SomeVC", storyboardName: "Main", bundle: nil), onDismiss: {
            _ in
        })
    }
    required convenience init(tag: String?) {
        self.init(tag: tag)
    }
}
```

I want this row to present a new VC modally when pressed. That is why I used `PresentationMode.presentModally`. However, I want the VC to be presented in a form sheet, not covering the whole screen. Normally, I can just do this by setting the VC's `modalPresentationStyle`, but I have no access to the VC instance here. How can I do this?

**Comment by m-revetria** [comment]
Hi @Sweeper777, you should be able to set `modalPresentationStyle` in the storyboard or in the view controller's init method. Is that a solution for your case?

**Comment by Sweeper777** [comment]
Thanks! I didn't know that you can set it in the storyboard!
