### ISSUE TITLE
Get value from PickerInputRow

### ISSUE THREAD

**Issue by abdymm** [xmartlabs/Eureka#1019]
How can i get PickerInputRow , when i try to convert to baseRow (the way to getvalue like this https://github.com/xmartlabs/Eureka#getting-row-values) i got an error `cannot convert ...` like in picture 
<img width="682" alt="screen shot 2017-04-27 at 2 33 20 am" src="https://cloud.githubusercontent.com/assets/1695466/25453178/420e2c50-2af2-11e7-9256-f75b769e3919.png">

**Comment by abdymm** [comment]
@SpencerC @mtnbarreto please answer

**Comment by frederic-cerco** [comment]
I'm not sure but shouldn't you add the object of your PickerRow.

For instance: 

`let data: PickerInputRow<Person>? = formPersonal.rowBy(tag: "data");`

**Comment by santiagofm** [comment]
@frederic-cerco's answer is correct, you need to specify the type of the value associated to the row.
Please let me know if you have any other issue

**Comment by abdymm** [comment]
so specify the type of the value associated, i dont see it in documentation, i just implement like a TextInputRow etc. Thanks @frederic-cerco @santiagofm !!
