### ISSUE TITLE
Subclassing GenericMultipleSelectorRow and using a custom cell

### ISSUE THREAD

**Issue by joshherkness** [xmartlabs/Eureka#102]
Im having a bit of trouble with subclassing `GenericMultipleSelectorRow` in order to use my own custom cell.  The goal is to create a user select similar to the image below.

![screen shot 2015-11-25 at 11 04 27 pm](https://cloud.githubusercontent.com/assets/5797470/11414886/163623ba-93c9-11e5-9e71-a306e7efab62.png)

I'm able to subclass just fine, but when I attempt to set the `cellProvider`, I'm unable to.  My custom cell is subclassing `pushSelectorCell<Set<PFUser>>`.  My code can be seen below:

```swift
import Foundation
import UIKit
import Eureka
import Parse

public class PFUserMultipleSelectorCell: PushSelectorCell<Set<PFUser>> {
    
    required public init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }

    public override func setup() { 
        super.setup() 
    }

    public override func update() {
        super.update()

    }
}

public class PFUserMultipleSelectorRow: GenericMultipleSelectorRow<PFUser, MultipleSelectorViewController<PFUser>> {
    
    public required init(tag: String?) {
        super.init(tag: tag)
        self.displayValueFor = {
            if let t = $0 {
                return t.map({ String($0) }).joinWithSeparator(", ")
            }
            return nil
        }
    }
}
```

If I attempt to set the `cellProvider` for my custom row class, I receive the following error:

```
Cannot assign value of type 'CellProvider<PFUserMultipleSelectorCell>' to type 'CellProvider<PushSelectorCell<Set<PFUser>>>'
```

Please let me know if there is an easy way to use a custom cell for a `GenericMultipleSelectorRow, or if i'm on the complete wrong path.

Thank you!

**Comment by havocked** [comment]
Any update on this one ?

**Comment by mtnbarreto** [comment]
@jasonnam By definition `GenericMultipleSelectorRow<T, ....>` expects a  PushSelectorCell<Set<T> as a cell type. In your particular case you need a custom row similar to it but it should work with your custom cell.

```swift
// GenericMultipleSelectorRow type definition
public class GenericMultipleSelectorRow<T: Hashable, VCType: TypedRowControllerType where 
VCType: UIViewController,  VCType.RowValue == Set<T>>: Row<Set<T>, PushSelectorCell<Set<T>>>, PresenterRowType 
```

Being said that I recommend you to create a new custom row by taking ideas and following `GenericMultipleSelectorRow` implementation. For additional info read: https://github.com/xmartlabs/Eureka#extensibility

Ideally this new row should work with any type capable of provide an UIImage (having a constraint to force the type to conforms to UIImageProvider for instance) and not only with `PFUser `.

Please add it to Example project and make a pull request in case you implement it.
