### ISSUE TITLE
Open PushRow after creating Fom

### ISSUE THREAD

**Issue by frederic-cerco** [xmartlabs/Eureka#1022]
I have created a Form with some elements in it. 

element is a PushRow<>. 

```

        form +++ Section()
            <<< elementRow!
            <<< dateRow!

        //Add code so the PushRow is automatically opened after the creation of the form because its the first thing the user must do

```

I want to open the PushRow of elementRow because the selection of an element is the first thing the user has to do. I can not figure out how to make this work.

Thanks in advance.

**Comment by santiagofm** [comment]
You should give the row a tag and then In your vc's `viewDidAppear:animated` you could call the `customDidSelect` function of the row :
```swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)

    (form.rowBy(tag: rowtag) as? PushRow<Element>)?.customDidSelect()
}
```

Let me know if this works for you

**Comment by frederic-cerco** [comment]
Thanks, this works! :)
