### ISSUE TITLE
.cellSetup not getting called on a custom Cell(created using a NIB file)

### ISSUE THREAD

**Issue by kumaresansv** [xmartlabs/Eureka#1023]
- Environment: Eureka, Xcode and iOS version you are using.
  Eureka -> Latest stable 3.0 version
  Xcode -> 8.2.1
 iOS -> 9.0

The custom cell files are attached. Here is the code where I am using it. The code never reaches the .cellSetup.

                form +++ SelectableSection<ItemOptionRow>() { section in
                }
                form.last! <<< ItemOptionRow() { optionRow in
                    optionRow.selectableValue = Option(name: "Test", price: 9.99)
                    optionRow.cell.optionName.text = "Test"
                    
                    optionRow.value = nil
                    }.cellSetup { cell, _ in
                        cell.trueImage = #imageLiteral(resourceName: "selectedRadioBox")
                        cell.falseImage = #imageLiteral(resourceName: "unselectedRadioBox")
                }

[ItemOptionCell.zip](https://github.com/xmartlabs/Eureka/files/962049/ItemOptionCell.zip)

**Comment by mohammdsss1** [comment]
Same

**Comment by kumaresansv** [comment]
Any updated or suggestions?

**Comment by santiagofm** [comment]
Hey guys !

The issue is that you are accessing the cell in the _constructor_ callback(let's call it this) and thus the `cellSetup` callback gets called before even being set, [here](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Row.swift#L128-L144), and never again.
What you want to do is move every cell config to the `cellSetup` callback and just leave row configs in the constructor callback, like so:

```swift
form +++ SelectableSection<ItemOptionRow>()
    form.last! <<< ItemOptionRow() { optionRow in
        optionRow.selectableValue = Option(name: "Test", price: 9.99)
        optionRow.value = nil
    }
    .cellSetup { cell, _ in
        cell.optionName.text = "Test"
        cell.trueImage = #imageLiteral(resourceName: "selectedRadioBox")
        cell.falseImage = #imageLiteral(resourceName: "unselectedRadioBox")
    }
```

Cheers

**Comment by m-revetria** [comment]
Closing due to lack of response
