### ISSUE TITLE
Section index, Row indexPath not set properly unless sections are "appended"

### ISSUE THREAD

**Issue by eliburke** [xmartlabs/Eureka#1024]
Environment: current Eureka, Xcode 8.3.2, iOS 10

FWIW, I have solved this problem, but I stumbled into what is either a bug or a very important documentation caveat. BaseCell.reload() and Section.reload() do not work unless Sections are  appended using +++ or form.append().

I have been developing my forms in sections, with sections added and replaced using `form[index] = section`. This **appears** to work properly, but does not call Form.append() under the hood, which means Section.wasAddedTo() and Row.wasAddedTo() are never called, so the internal values for index and indexPath are never set. 

I can't say for sure when I started using form[0] and section[0]-- I think I encountered it in sample code posted here. But it is clearly wrong, at least without some additional operator overloading.

**Comment by m-revetria** [comment]
Hi @eliburke, thanks for your report, we are working on a fix for this bug.

You can see the proposed changes in PR #1028

**Comment by eliburke** [comment]
Awesome thanks @m-revetria now I'm wishing I hadn't refactored my code to use the other method 😄
