### ISSUE TITLE
How to change the style of a PushSelectorCell to "Subtitle"?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#1029]
I have this custom row that presents another controller. The row inherits from `SelectorRow<PushSelectorCell<SomeType>, MyVC>`.  The row's style appears to be "Right Detail". How can I make it so that the row is "Subtitle"? Like this:

<img width="377" alt="2017-05-01 9 15 56" src="https://cloud.githubusercontent.com/assets/13585047/25575390/d3470d86-2e4e-11e7-820e-2a49b6bb80a9.png">

**Comment by jmprice18** [comment]
I was able to do it like this: 
            ```let projectRow = MultipleSelectorRow<Item>("MyRow") {
                $0.cellStyle = UITableViewCellStyle.subtitle
             }```

**Comment by mats-claassen** [comment]
Yes you should use the `cellStyle` variable for that.
