### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by abdymm** [xmartlabs/Eureka#1030]
Can i set loading indicator before load form ?

**Comment by santiagofm** [comment]
Hey @abdymm ! You mean a loading indicator while the form is being populated ? If this is the case then you can't. 

Cheers

**Comment by abdymm** [comment]
Hey @santiagofm , yes that's exactly what i mean, how if i use spinner UIAlertController  (progress dialog) ?

**Comment by santiagofm** [comment]
The actual form population is quick and you shouldn't need a loading indicator for that.
Are you waiting for some network request to finish or something like that ? In that case this question is unrelated to Eureka and you should be asking it in stackoverflow :) 

I'm closing this issue, open a new one if you think i'm wrong please.
Cheers
