### ISSUE TITLE
Collapsible section

### ISSUE THREAD

**Issue by nvprokofiev** [xmartlabs/Eureka#1031]
Hi,

I'm trying to achieve the same behavior as Inline Row but for Section. There is a button on section by tapping on it section has to be collapsed and the next tap will expand this section. 

This is my form example 
```
        +++ Section(){ section in
            var header = HeaderFooterView<customView>(HeaderFooterProvider.nibFile(name: "customView", bundle: nil))
            header.onSetupView = { view, section in
                view.sec = section
            }
            section.header = header
        }
        <<< TextRow()
        <<< SwitchRow()
```

this is my customView class

```
    var isCollapsed: Bool = false
    var sec: Section!

    @IBAction func hideTapped(_ sender: Any) {
        if isCollapsed {
            print("sec \(sec.count)")
        } else {
            for row in sec.reversed() {
                row.hidden = true
                row.evaluateHidden()
            }
        }
    }
```

Hidding works perfect,  but **print("sec \(sec.count)")** gives me **sec 0**.
How to get rows that were hidden?
Thanks

**Comment by jmprice18** [comment]
I believe this is because the `row.hidden` attribute will actually remove the row from the form when you call `evaluateHidden()`, so afterwards, the section has no rows.  What I did was to keep a reference to the rows by looping sec.reversed when I stored my section property in my custom header view.  Here I was able to re-add those rows back to the section when I wanted expand the section again.

**Comment by nvprokofiev** [comment]
Thanks @jmprice18 for the help

At the end I decided to remove all rows in the section when the user taps because when I hided it with `row.hidden = true row.evaluateHidden()` I was getting the error 

`assertion failed: Duplicate tag oo: file/Users/nikolai_irina/Desktop/ee/Pods/Eureka/Source/Core/BaseRow.swift, line 172`

This means that rows were not removed from the form and there were references to them. If I'm wrong please correct me.

I didn't find any difference between `sec.removeAll()` and `sec.removeLast()`. I thought the animation had to be smoother but it looks the same.

This is my solution.

```
import Foundation
import UIKit
import Eureka

class customView: UITableViewHeaderFooterView {
    
    @IBOutlet weak var lab: UILabel!
    var isCollapsed: Bool = false
    var rows: [BaseRow]!
    var sec: Section!
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    @IBAction func hideTapped(_ sender: Any) {
        
        if !isCollapsed {
            rows = []
            for row in sec.reversed() {
                rows.append(row)
            }
            sec.removeAll()
        } else {
            for row in rows.reversed() {
                sec <<< row
            }
        }
        isCollapsed = !isCollapsed
        lab.backgroundColor = isCollapsed ? UIColor.orange : UIColor.cyan
    }
}
```

And the result is

![collapsible section](https://cloud.githubusercontent.com/assets/16692711/25883025/5a2abd9e-3515-11e7-9f12-5de159ae0761.gif)

**Comment by m-revetria** [comment]
Hi @nvprokofiev, looks like you found a solution. I'm closing the issue, if you need further assistance please add a new comment.

Cheers

**Comment by Ziqi-Li** [comment]
Thanks for the solution, I was able to replicate your method to get expandable section done. However, I experience flashing animation when I hide/expand, do you have this issue?

**Comment by seamusapple** [comment]
Thanks for you solution, it's really helpful.
BTW, how to hide the rows in the section by default, and then tap to expand and collapse?

**Comment by m3t8d1tr** [comment]
> Found out the problem is due to the footer. When hiding and expanding, the footer of the section will move from top to bot or bot to top, which causes the blinking.

Did you find a solution?

**Comment by Tectailor** [comment]
how to hide the rows in the section by default, and then tap to expand and collapse?

**Comment by Tectailor** [comment]
I am able collapse the rows in a section by click of a button in header section

**Comment by Tectailor** [comment]
but i want to hide the rows in section by default,Please let me know how to achieve it

**Comment by SpajicM** [comment]
@Tectailor  Facing the same problem, did you figure out how to do it?

**Comment by reenaphilip** [comment]
> @Tectailor @m3t8d1tr @seamusapple Same thing, I want rows hidden by default, and then expended, did you figure out how to do it?
> 
> EDIT:
> Got it, trickier than expected:
> 
> Doing `for row in sec` with hidden rows returns 0, so when creating the row, on setup I've hidden them, and added them to header's global rows[] variable, then on button click hidden = true/false from rows array.
@SpajicM Can you show the code for this ?  I tried hiding the rows in the header.SetUp and make visible in button click. But it didnt work for me

**Comment by SpajicM** [comment]
@reenaphilip 

```
 section <<< TextRow {
            $0.value = attribute.Answer
            $0.title = attribute.Question
            $0.hidden = true
            let header = section.header?.viewForSection(section, type: .header) as! AttributesHeaderView
            header.rows.append($0)
```

Header XIB code:
```

import Foundation
import UIKit
import Eureka

class AttributesHeaderView: UIView {
    
    @IBOutlet weak var headerButton: UIButton!
    @IBOutlet weak var headerImage: UIImageView!
    
    var isCollapsed: Bool = false
    var sec: Section!
    var rows: [BaseRow]!
    
    override func awakeFromNib() {
        headerImage.image = headerImage.image!.withRenderingMode(.alwaysTemplate)
        headerImage.tintColor = UIColor.white
        headerImage.transform = CGAffineTransform(rotationAngle: .pi)
        
        //toggle()
    }
    
    func toggle() {
        if !isCollapsed {
            headerImage.transform = CGAffineTransform(rotationAngle: .pi * 2)
            rows = []
            for row in sec.reversed() {
                rows.append(row)
            }
            sec.removeAll()
        } else {
            headerImage.transform = CGAffineTransform(rotationAngle: .pi)
            for row in rows.reversed() {
                sec <<< row
            }
        }
        isCollapsed = !isCollapsed
    }
    
    @IBAction func headerButtonClick(_ sender: Any) {
        toggle()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}

```

**Comment by GitMAM** [comment]
`class AttributesHeaderView: UIView {
    
  let headerButton: UIButton = {
    let btn = UIButton()
    btn.setTitle("Hello", for: .normal)
    btn.setTitleColor(.black, for: .normal)
    btn.addTarget(self, action: #selector(toggle), for: .touchUpInside)
    return btn
  }()
    
    var isCollapsed: Bool = false
  
  var sec: Section! {
    didSet {
      rows = sec.allRows
    }
  }
    var rows: [BaseRow]!
  
  override init(frame: CGRect) {
    super.init(frame: frame)
    
    addSubview(headerButton)
    headerButton.snp.makeConstraints { make in
      make.width.height.leading.trailing.top.bottom.equalToSuperview()
    }
  }
  
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }

  @objc func toggle() {
        if !isCollapsed {
          rows.forEach { row in
            row.hidden = true
            row.evaluateHidden()
          }
        } else {
          rows.forEach { row in
            
            row.hidden = false
            row.evaluateHidden()
          }
        }
        isCollapsed = !isCollapsed
    }
}
  
  override public func viewDidLoad() {
    super.viewDidLoad()
    
    tableView.contentInset = UIEdgeInsets(top: 100, left: 0, bottom: 0, right: 0)
    
    form
    +++ Section("Sign off") {
      var header = HeaderFooterView<AttributesHeaderView>(.class)
      
      header.onSetupView = { view, section in
        view.sec = section
        header.title = "oiiiii"
        header.height = {250}
      }

      $0.header = header
    }
    
    <<< TextRow {
      $0.value = "attribute.Answer 1"
      $0.title = "attribute.Question"
      $0.hidden = true
    }
    
    <<< TextRow {
      $0.value = "attribute.Answer 2"
      $0.title = "attribute.Question"
      $0.hidden = true
    }
    <<< TextRow {
      $0.value = "attribute.Answer 3"
      $0.title = "attribute.Question"
      $0.hidden = true
    }
    <<< TextRow {
      $0.value = "attribute.Answer 4"
      $0.title = "attribute.Question"
      $0.hidden = true
    }}
`
