### ISSUE TITLE
Validate before performing segue

### ISSUE THREAD

**Issue by ControlAdad** [xmartlabs/Eureka#1032]
How can I validate before performing a segue?
Thanks

**Comment by santiagofm** [comment]
Hey @ControlAdad !

For each row you want to validate you should set the `validationOptions` property to `.validatesOnDemand` and then before performing the segue tell the form to validate the rows, `form.validate()`. Don't forget you can retrieve all validation errors via the `validationErrors` property.
https://github.com/xmartlabs/Eureka#validations

Cheers

**Comment by m-revetria** [comment]
Closing due to lack of response
