### ISSUE TITLE
how to remove the extra space (in green rectangle) in the form

### ISSUE THREAD

**Issue by timxi** [xmartlabs/Eureka#1036]
![image](https://cloud.githubusercontent.com/assets/1224075/25832348/0e48c548-3438-11e7-92c4-0bdfd3c03d2c.png)

I want to know how to move the table view up to the navigation bar bottom.

**Comment by nvprokofiev** [comment]
You need to set section height to 0.
Here there are more details https://github.com/xmartlabs/Eureka/issues/80

**Comment by timxi** [comment]
Thanks @nvprokofiev !
