### ISSUE TITLE
How To Change Layout of elements to support RTL Languages (Persian,Arabic)?

### ISSUE THREAD

**Issue by razava** [xmartlabs/Eureka#1039]
Hi! i'm new in swift and Eureka. i want to use Eureka to develope Persian app. but elements designed Left to Right. how to change all or certain elements such as TextRow right to left direction?( label in right and input left). Please guide me by example...

**Comment by ybeapps** [comment]
I need the same thing..
I have a partially working workaround..

In your FormViewController add the last line

```
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        **tableView?.semanticContentAttribute = .forceRightToLeft**
```

**Comment by mtnbarreto** [comment]
I think you just need to change to change device language in iOS settings.

**Comment by ybeapps** [comment]
Not working. I wrote the workaround.. you can understand the problem from there

**Comment by ybeapps** [comment]
When the semanticContentAttribute set to Unspecified. It should use the direction of the device language.

I don’t think you need to set it
I think you need to understand why you’re overriding the default behavior 

It could be an Apple bug too
