### ISSUE TITLE
"AddressRow" planned?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#104]
Is there anything like an "AddressRow" planned to build into Eureka?
I'm thinking of a row like in the iOS contact app, a row containing the following fields:

    [ Street       ]
    [ Suffix       ]
    [ Zip | City   ]
    [ Country      ]

**Comment by mtnbarreto** [comment]
just in case someone is looking for this row. it's already implemented and merged:  #187

**Comment by connersimmons** [comment]
Has the PostalAddressRow been added the the Podfile? I installed the 1.3.1 pod and I don't see the PostalAddressRow in any of the files.
