### ISSUE TITLE
Form inside a View instead ViewController

### ISSUE THREAD

**Issue by timxi** [xmartlabs/Eureka#1040]
How can I create a form inside a UIView instead of FormViewController programmatically? Because I need some graphics on the top, just before of the Form.

Can someone provide a working example?

**Comment by santiagofm** [comment]
Hey @timxi !

If you are using a storyboard then you can adjust the `tableView`s positioning from there, just add a `UITableView` to your `UIViewController` and connect to the `FormViewController`'s `tableView` outlet. You can take a look to the `HomeViewController` in the Example project to see how it was done.

If you are using the framework programmatically you should still be able to change the `tableView`s positioning in your `viewDidLoad` by editing it's `frame`. The `tableView` is laid out to [match the `view`s bounds if the outlet is not connected](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Core.swift#L460-L466).
Or you could init the `tableView` before the super call and set it's `frame` or add constraints however you want.

Cheers

**Comment by timxi** [comment]
Thanks, @santiagofm !
