### ISSUE TITLE
TextAreaRow with a large text has a bug.

### ISSUE THREAD

**Issue by alexanderkhitev** [xmartlabs/Eureka#1041]
I found a UI bug (and a very strong slowdown) when I edit a large text in TextAreaRow.  How can I fix it?

I deleted all my custom code (for example fonts and sizes) but the bug remained.
```swift
   fileprivate func noteRow() -> TextAreaRow {
        let placeholder = "example."
        let row = TextAreaRow() { [weak self] in
            $0.placeholder = placeholder
            $0.textAreaHeight = .dynamic(initialTextViewHeight: 38)
            guard self != nil else { return }
            $0.value = ""
        }
        row.cellUpdate { [weak self] (cell, row) in

        }
        return row
    }
```
I got it in logs but I do not use the MetalKit.

```
2017-05-11 08:51:11.424709+0400 example[5363:1263562] Nil drawable for layer <MetalLayer: 0x170484880>
2017-05-11 08:51:12.723664+0400 example[5363:1263562] Nil drawable for layer <MetalLayer: 0x170484880>
```

![img_1076](https://cloud.githubusercontent.com/assets/12511909/25932789/853f37c0-3624-11e7-8e9e-8d896ae1de95.JPG)

**Comment by mats-claassen** [comment]
Did this issue happen on a real device or just the simulator?
If it wa just the simulator, could you try if you can reproduce it on a device as well?

**Comment by alexsanderkhitev** [comment]
@mats-claassen hello!
It was on a real device. It was the iPhone 7. The problem with the keyboard and FormViewController starts to work slowly. When the FormViewController is deinit, the performance becomes normal.

**Comment by santiagofm** [comment]
Hey @alexsanderkhitev !
Are you able to reproduce this issue with the Example project ? Tested on an iphone 6 with iOS 10.3.1 and everything works fine
Cheers

**Comment by mcousillas6** [comment]
Closing this due to lack of response
