### ISSUE TITLE
When adding a view with code inside a View, that is in a StackView, the sizing gets quirked.

### ISSUE THREAD

**Issue by chefren** [xmartlabs/Eureka#1044]
Hi, thank you for creating this cool library. I encountered this issue, but am unsure if I'm misreading some documentation or it's a weird condition for this scenario.

# Steps to reproduce
- Create a View Controller with a Stack View
- (optional) Add some element to the stack view (eg: text field) to make the issue more visible
- Add a View to the Stack View
- Add an outlet for the View in the ViewController
- Create a class for the FromController
eg
```swift
class FormVC : FormViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        form +++ Section("test")
            <<< SwitchRow("some switch") { row in
                row.title = "Select me"}
    }
}

```
- In the `ViewController.viewDidLoad` create the instance of the FormVC and add it to the stack view
```swift
    @IBOutlet weak var formView: UIView!
    
    var taskFormCtrl : FormVC!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Create instance for forms
        taskFormCtrl = FormVC()
        formView.addSubview(taskFormCtrl.view)

    }

```

The selector switch gets clipped out of the screen
<img width="379" alt="screen shot 2017-05-15 at 2 29 10 pm" src="https://cloud.githubusercontent.com/assets/2918150/26042741/0594451a-397b-11e7-985a-5d010b09b478.png">

## Environment
- Eureka: 3.0.0
- Xcode : 8.3.2 
- iOS: 10

**Comment by m-revetria** [comment]
Hi @chefren this seems to be related to #1045. I just answered there.

The short story, you should not embed a FormViewController's view in other view just like that, you should add the FormViewController as a child of your view controller.

Regards

**Comment by chefren** [comment]
Thank you Miguel, I tried it and commented here: https://stackoverflow.com/q/43994002/1736679. Will add it as proper answer and close this now :)
