### ISSUE TITLE
SliderRow doesn't respect imageView on the cell

### ISSUE THREAD

**Issue by AAverin** [xmartlabs/Eureka#1047]
SliderRow should respect imageView that can be set on the UITableViewCell and change it's constraints accordingly

<img width="118" alt="screen shot 2017-05-16 at 20 46 21" src="https://cloud.githubusercontent.com/assets/1481332/26122727/c1e15ba6-3a78-11e7-8006-62151acddbdf.png">

**Comment by AAverin** [comment]
And this looks even more broken
<img width="157" alt="screen shot 2017-05-16 at 21 22 08" src="https://cloud.githubusercontent.com/assets/1481332/26124164/cffcc57c-3a7d-11e7-9fef-3b66ac142397.png">

**Comment by santiagofm** [comment]
Hey @AAverin !
Would you like to submit a PR that fixes this issue ?

Cheers

**Comment by AAverin** [comment]
@santiagofm unfortunately I will probably screw things up =) It's my first week of iOS development.
So far I have worked around by building a custom slider row because functionality I need differs a lot.

**Comment by mtnbarreto** [comment]
fixed!
