### ISSUE TITLE
Change height of UIImageView in TextRow

### ISSUE THREAD

**Issue by zsefvlol** [xmartlabs/Eureka#1049]
Working on a captcha row in register form by Eureka with Swift. I inserted a `TextRow` and assign the captcha image to `cell.imageView`, but the image is slightly taller that covered the row line. How can I change the height of that image?
Tried `cell.imageView?.frame`, not working.
Codes below. Many thanks.
```swift
<<< TextRow(){ row in
    row.title = ""
    row.tag = "Captcha"
    }.cellSetup { cell, row in
        cell.imageView?.image = UIImage(data:imgData!, scale:1)
        //this line is not working
        cell.imageView?.frame = CGRect(x: 0, y: 0, width: 98, height: 28)
    }
```
Also asked on [stackoverflow](http://stackoverflow.com/questions/43932333/change-height-of-uiimageview-in-eureka-textrow), with a image to show what happened.

**Comment by santiagofm** [comment]
Hey @zsefvlol ! Have you found a solution for this ?
Cheers

**Comment by zsefvlol** [comment]
@santiagofm Nope.

**Comment by aksswami** [comment]
@zsefvlol Maybe you can change the height of cell itself.
```
<<< TextRow(){ row in
    row.title = ""
    row.tag = "Captcha"
}
.cellSetup { cell, row in
                    cell.height = {
                        return 100
                    }
                }
```

**Comment by mtnbarreto** [comment]
Closing since it's not directly related with Eureka.
