### ISSUE TITLE
I still don't get how do I get the value?

### ISSUE THREAD

**Issue by kaka21garuda** [xmartlabs/Eureka#1050]
when I declared: in the viewDidLoad

```swift
+++ Section("Where can customer contact you?")
            <<< TextRow(){ row in
                row.title = "Email"
                row.placeholder = "Enter your email here"
            }
            <<< PhoneRow(){
                $0.title = "Phone Row"
                $0.placeholder = "And numbers here"
            }

```
how do I get the reference value? should each row has its own tag? and how do I get the value in `SelectableSection`

**Comment by santiagofm** [comment]
Hey @kaka21garuda ! 
Yes, each row should have it's own tag and then to obtain the values you can use any of the ways described in the readme, [here](https://github.com/xmartlabs/Eureka#getting-row-values).
To get the `SelectableSection` value you could use the above methods, if you assign a tag to each option, but maybe the best way would be the one used in the Example project, [here](https://github.com/xmartlabs/Eureka/blob/master/Example/Example/ViewController.swift#L1092-L1134).
Let me know if this works for you!
Cheers

**Comment by kaka21garuda** [comment]
Yes I've looked at the example but still do not get it. so I declared the code above shown in the viewdidload, and should I assign tag to each row or should make the row like this.
```swift
let titleRow: TextRow? = form.rowBy(tag: "titleRow")
```

If you guys have real example that I can check, it would be appreciate. I've been trying to figure this out for ours and still no idea on how to get the value.

**Comment by daaavid** [comment]
Hi @kaka21garuda!

So, let's say we used this code to make a row:

```
<<< TextRow() {  row in
  row.tag = "email"
  row.title = "Email"
  row.placeholder = "Enter your email here"
}
```

Note that we set the **tag**.

We can very easily grab the value of that particular row like this:

```
let emailRow: TextRow? = form.rowBy(tag: "email")
let email: String? = emailRow?.value
```

Better yet, let's conditionally unwrap both of those, since they're both optional:

```
if let emailRow: TextRow = form.rowBy(tag: "email"), let value = emailRow.value {
  let email = value
}
```

You can also grab all values of the form as a `[String: Any?]` dictionary, where the row tags are the keys, and the row values are the values. Like so:

```
let allValues = form.values()
```

Hope this helped!

**Comment by kaka21garuda** [comment]
Yes, that's work! but is there any row for images like shown in the example. In the example, you guys have this row when you clicked it you'll get directed to image library?

**Comment by santiagofm** [comment]
Thanks @daaavid !
Yes @kaka21garuda, i think you want something like [imageRow](https://github.com/EurekaCommunity/ImageRow).
Let me know if theres anything else i can help you with!

Cheers
