### ISSUE TITLE
Custom Cells and the Next Arrow

### ISSUE THREAD

**Issue by calebmanley** [xmartlabs/Eureka#1054]
I have a custom cell that contains a custom text field that I would like to be able to include in the arrow keys on the form. When a cell above it is selected I can use the arrow keys above the keyboard to move up and down to the other cells fine, but it skips my custom text field cell.
Is there a simple way to include this?

Thanks.

**Comment by calebmanley** [comment]
Turns out the required code is the first responder stuff. Works great, thanks.

**Comment by duongel** [comment]
@calebmanley could you explain how you solved this? I have the same problem.
