### ISSUE TITLE
while archiving a "no such module 'Eureka'" error

### ISSUE THREAD

**Issue by jameseraynor** [xmartlabs/Eureka#1060]
hi, I am trying to archive my project but I get the error  that it cannot import eureka module
I saw that there is an error similar to mine 'Carthage build fails with Xcode 8.2.1 #1021' i am also using 
Eureka version: 3.0.0
Xcode version: 8.2.1

but I am using cocoapods, I added the libraries, to the 'linked frameworks and libraries' and in 'framework and search paths'  so I am out of ideas of what it is.

here is my pod file just in case

```ruby
 # Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Mercy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mercy
  pod 'Firebase/Core'
  pod 'Firebase/Core'	
  pod 'Firebase/AdMob'	
  pod 'Firebase/Messaging'	
  pod 'Firebase/Database'	
  pod 'Firebase/Invites'	
  pod 'Firebase/DynamicLinks'	
  pod 'Firebase/Crash'	
  pod 'Firebase/RemoteConfig'	
  pod 'Firebase/Auth'	
  pod 'Firebase/Storage'

pod 'Eureka'

  target 'MercyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MercyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end
```

**Comment by jameseraynor** [comment]
after I looked a little bit more into the problem it seems the real issue is in it can't find a 'Eureka-Swift.h' in the module.modulemap

```
framework module Eureka {
  umbrella header "Eureka-umbrella.h"

  export *
  module * { export * }
}

module Eureka.Swift {
    header "Eureka-Swift.h"
}
```

and truly I can't find this file

**Comment by santiagofm** [comment]
Hey @jameseraynor !
When you say *I added the libraries, to the 'linked frameworks and libraries'*, you mean you linked your target with the Pods_***.framework generated by cocoapods, right ? Or are you adding each framework ?
Cheers

**Comment by jameseraynor** [comment]
the first time I tried it was with the cocoapods generated file, I saw on the internet that the module not found could be fixed by adding it directly, I tried most of the solutions.

**Comment by santiagofm** [comment]
Yeah, the .framework created with cocoapods should be enough & it should be automatically linked to your target also.
Go to your target's *build settings* and check that the path to where the Eureka framework is(somewhere in the Pods dir) is set *Framework Search Paths*

**Comment by jameseraynor** [comment]
I am afraid the issue persist, I created a separate project and tried to archived using only the cocoapods the errors I get are: 

`error: cannot parse the debug map for "/Users/javierjaramillo/Library/Developer/Xcode/DerivedData/testcocoaeureka-elddhrntmbfauigvevojmckhlhti/Build/Intermediates/ArchiveIntermediates/testcocoaeureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Eureka": No such file or directory`
and 
`error: cannot parse the debug map for "/Users/javierjaramillo/Library/Developer/Xcode/DerivedData/testcocoaeureka-elddhrntmbfauigvevojmckhlhti/Build/Intermediates/ArchiveIntermediates/testcocoaeureka/InstallationBuildProductsLocation/Applications/testcocoaeureka.app/testcocoaeureka": No such file or directory`

I checked the folders and there is an eureka.bundle for the first error and a testcocoaeureka file for the second. also in the build path I have the following "$PODS_CONFIGURATION_BUILD_DIR/Eureka"

**Comment by santiagofm** [comment]
@jameseraynor Would you mind uploading that test project so i can take a look ?

**Comment by jameseraynor** [comment]
sure, here is the code

https://github.com/jameseraynor/testcocoaeureka

**Comment by santiagofm** [comment]
@jameseraynor It's working fine for me 😕 . 
Have you tried clean and build ? Or deleting DerivedData ? I just cloned the repo, opened the workspace and run and it all went ok.

**Comment by jameseraynor** [comment]
I think there is a misunderstanding, the project and the test run fine when on the simulators, the problem arises when I tried product - archive, does this work as well? cuz I tried again, clean and build, deleted derived data and still cannot archive.

**Comment by santiagofm** [comment]
Yup, i understood you couldn't run the project. Anyway, archiving works ok also.
Which error are you getting ? In the report navigator you can see/export a full report of the archive that fails.

**Comment by jameseraynor** [comment]
sure, uploaded the file 
https://github.com/jameseraynor/testcocoaeureka/blob/master/Archive%20testcocoaeureka_2017-05-26T09-46-14.rtf

**Comment by santiagofm** [comment]
@jameseraynor Can you try building with Xcode 8.3.2 ? I think you *need* the swift 3.1 toolchain to build and we should update the README then

**Comment by jameseraynor** [comment]
nope, I have a 2010 mac so I can't upgrade :(

**Comment by santiagofm** [comment]
Oh 😕 . I think you won't be able to build the library then.. you'll need to use an older version

**Comment by santiagofm** [comment]
Same as #1070

**Comment by kiraninfogird** [comment]
> While archive Xcode project on simulator [Xcode Version 9.0 (9A235)  and Swift  version 4.0 ]


it gave me below error;

**/Users/iipl5/Documents/iOS Projects/iOS_Projects/HRGirdAdmin/hrgirdadmin_iosapp/HRGirdAdmin/FrontEndController/Controller/Need To Review/Reimbursement/ReviewedReimbursementViewController.swift:10:8: error: no such module 'Alamofire'
import Alamofire**

but I already did everything i.e. when I was run or build the project I will work fine.
Please help me to solve it?

**Comment by zungx** [comment]
I have same issues when archive with xcode 9.0, swift 4.0. How can i fix it? Thks
