### ISSUE TITLE
How to enable highlight on custom design TextRow?

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#1062]
I customised a TexRow, works fine by linking it up with `FieldCell`.
 ```swift
<<< TextRow() {
    $0.cellProvider = CellProvider<TextCell>(nibName: "RegisterTextCell", bundle: Bundle.main)
    $0.cell.height = { 50 }   
  }
```
How how can i make changes to the selection behaviour? i.e change the tint color from blue to another color

**Comment by santiagofm** [comment]
Hey @kohdesmond !
I think you can do that the same way you do with a regular `TextRow`, via the `cellSetup` callback:
```swift
<<< TextRow() {
    $0.cellProvider = CellProvider<TextCell>(nibName: "RegisterTextCell", bundle: Bundle.main)
    $0.cell.height = { 50 }   
 }.cellSetup { cell, row in
    cell.titleLabel?.tintColor = .red
}
```

Cheers

**Comment by kohdesmond** [comment]
thanks @santiagofm
