### ISSUE TITLE
"Typed" Row?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#107]
How to define a "Typed" row in Eureka? For example if you have a phone input which also have a choosable type like "Private", "iPhone" or "Business"?

    PHONE
    [ Private | 45678 ]
    [ iPhone  |       ]

**Comment by marbetschar** [comment]
Maybe this can be achieved by simply allowing two columns?

**Comment by marbetschar** [comment]
@mtnbarreto does the label `custom row` mean this would definitely be a feature not going into core?

Apart from that: Do you have any idea on how this can be built best? I'm a bit lost here, since I would love to reuse the existing core and custom cells.

So adding this feature would allow me to use a `LabeledValue` as follows:

```
TextRow(){
  $0.labelFormatter = LabelFormatter()
  $0.formatter = ValueFormatter()

  if let labeledValue = $0.value as? LabeledValue{
    print(labeledValue.label) //The label as regular String - should be formattable as you can see from above
    print(labeleldValue.value) //The actual value
  }.onChange {
    //would be fired if the label or the value changes...
  }
}
```

**Comment by mtnbarreto** [comment]
@marbetschar  Thanks for the contribution, and my apologies for the late response. 
I think is not a good idea to add this to Eureka core. It could be a custom row and it would be great if you publish it on this github organization (https://github.com/EurekaCommunity) that aims to provide Eureka components and plug-ins.
