### ISSUE TITLE
MultivaluedSection did remove row callback?

### ISSUE THREAD

**Issue by pluckq** [xmartlabs/Eureka#1076]
Is there any way to get that?

**Comment by Laptopmini** [comment]
+1

**Comment by macrigiuseppe** [comment]
+1

**Comment by fabiodursoexin** [comment]
+1

**Comment by mtnbarreto** [comment]
Take a look at https://github.com/xmartlabs/Eureka/pull/1136

**Comment by stonkeep** [comment]
See on https://stackoverflow.com/questions/48916511/why-cant-delete-row-in-eureka-demo
