### ISSUE TITLE
MultivaluedSection's "rowBy(tag:)" produces syntax error

### ISSUE THREAD

**Issue by Laptopmini** [xmartlabs/Eureka#1077]
Eureka: 3.0.0
XCode: 8.2.1

![http://i.imgur.com/CRsg0Qa.png](http://i.imgur.com/CRsg0Qa.png)

**Comment by AlexandreMinard** [comment]
what is the exact type of your section?
I think you need to do something like

`
let section = deviceShareSection as! TypeOfYourSection
let row = section.rowBy(tag: "tag")
`

**Comment by Laptopmini** [comment]
The variable `deviceShareSection` is already declared as MultivaluedSection. 

I even tried to cast to `Section`, but it does not change the error.

**Comment by Laptopmini** [comment]
Fixed by updating XCode to 8.3.2.

Closing.

**Comment by cerupcat** [comment]
I'm getting this same error on the latest version. Were you able to fix this simply updating XCode? I'm also on the latest XCode.
