### ISSUE TITLE
Can't enter accent on a TextRow

### ISSUE THREAD

**Issue by AlexandreMinard** [xmartlabs/Eureka#1079]
Hi all,

When entering a text in a textrow, while using the keyboard, I'm not able to enter an accent.
I 'long press' a letter (for instance 'e') but the special characters assocaited to it (é,è,...) never appears and all keys of the keyboard are blank.

Am I alone to get that bug?

Regards,
Alexandre

**Comment by AlexandreMinard** [comment]
That's something you can see in the Example project

**Comment by m-revetria** [comment]
Hi @AlexandreMinard, as you can see in the GIF bellow that is something that is working in the examples. Are you using a custom keyboard? Could you provide more info about the environment where you are testing your forms?

![issue_1079](https://user-images.githubusercontent.com/4791678/26954875-37e475fa-4c89-11e7-8d00-6407fb6789fc.gif)

**Comment by AlexandreMinard** [comment]
Hi,

I'm not using a custom keyboard but I've several keyboards installed and the first one is French.
It does work on Simulator but not on my iPhone 6s.

Did you try on a device?

Regards,
Alexandre

**Comment by AlexandreMinard** [comment]
Just checked with latest XCode (8.3.3) and my iPhone: it works fine.
So I close the issue, sorry for that.
