### ISSUE TITLE
"TextAreaRow" autosize?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#108]
How to have the TextAreaRow sizing automatically regarding it's content?

**Comment by ffittschen** [comment]
Hi @marbetschar, you can take a look at https://github.com/xmartlabs/Eureka/issues/90. This is how I solved this problem in the context of the app I'm working on. (If you only want to resize the `TextAreaRow`, you can remove the parts with keyboard appearance etc)

**Comment by marbetschar** [comment]
@ffittschen thank you!!!

**Comment by mtnbarreto** [comment]
@ffittschen @marbetschar 
I would like to have this new `TextAreaRow` capability integrated with the code base. 

I prefer to keep the default `TextAreaRow` behavior (fixed height) and provide a way to enable autoresize functionality.

What do you think?

**Comment by marbetschar** [comment]
@mtnbarreto this sounds amazing!! How about a `$0.autoResize = true` flag?
@ffittschen any chance you may find some time moving this functionality into the official release?

**Comment by ffittschen** [comment]
@mtnbarreto Sounds good :+1: 
@marbetschar I'll see what I can do. We should discuss how to handle the "extra code" like `keyboardDidChangeFrame ` that is necessary. Either we clearly state it in the documentation or we create a protocol with default implementations

**Comment by marbetschar** [comment]
@ffittschen maybe just implementing this feature and adding a pull request would be enough to get started? I'm sure @mtnbarreto would guide you from there on if any further changes should be necessary!

**Comment by ffittschen** [comment]
@marbetschar I will create a PR as soon as my exams are over ;) Probably at the end of this month

**Comment by marbetschar** [comment]
@ffittschen cool!! I'm eager to see this feature in the official release;
but first of all: Good Luck in your exams!!!!!!

**Comment by jbejar** [comment]
Good luck on your exams as well. I ran into a brick wall while trying to implement it, so any help would be appreciated

**Comment by ffittschen** [comment]
@jbejar have you tried to implement it as I described in https://github.com/xmartlabs/Eureka/issues/90 ?
@mtnbarreto I'm following the [SR-661](https://bugs.swift.org/browse/SR-661) issue as well, should I wait until the `fix/Xcode7-3` is merged before creating the PR?

**Comment by mtnbarreto** [comment]
@ffittschen W've already solved Xcode 7.3 issues so feel free to make your pull request!

**Comment by aalfath** [comment]
Hello, is the issue still open? This feature will be very beneficial for the others.

Anyway, thank you for the library!

**Comment by alimir1** [comment]
Hey guys, any updates on this yet?
