### ISSUE TITLE
Leading space issue

### ISSUE THREAD

**Issue by iamabhiee** [xmartlabs/Eureka#1084]
Hi

This is a great library which almost solved my problem, while I am facing some issues with alignment/margin on iPhone 6/7 Plus while on iPhone 6/7 its work fine, What would be some solution to fix this issue? 

I am using TextRow, SwitchRow and Label Row, Textfield Row, but all of them starts at different position

I am attaching the screenshot to explain the issue
![simulator screen shot 06-jun-2017 11 20 16 pm](https://user-images.githubusercontent.com/5380024/26843937-80ddee6a-4b0f-11e7-8d48-24fe1108b645.png)

**Comment by m-revetria** [comment]
Hi @iamabhiee I have ran the examples provided in the repo on an iPhone 7 plus and I don't notice that margin issue. Take a look to the image below, it was taken from the example "Accessory View Navigation".

![image](https://user-images.githubusercontent.com/4791678/27336984-8da312a4-55a7-11e7-8a01-da3f0974e292.png)

Did you make some change in the rows style that can affect their alignment?

**Comment by m-revetria** [comment]
Closing this due to lack of response
