### ISSUE TITLE
(Feature request) Add Follow Readable Width

### ISSUE THREAD

**Issue by alvarlagerlof** [xmartlabs/Eureka#1089]
It would be super handy if it was added, so that the iPad layouts look a bit better.

**Comment by RiverbayChris** [comment]
You can do this for the form's tableView if you add it via Storyboards.  Just check the readable width checkbox.  Also, if you use a push row, you can get the next tableView to also use readable width programmatically with this:

    .onPresent { from, to in
         to.view.subviews       // Need this because to.tableView! is not loaded yet...
         to.tableView?.cellLayoutMarginsFollowReadableWidth = true
    }
