### ISSUE TITLE
Inline Date-, Time- & Countdown Pickers visible

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#109]
Dear Eureka Team

I've just created a demo ViewController, showing me all Date Rows with the following code:

		form +++= Section("Date Rows")
			<<< DateRow("DateRow"){
				$0.title = $0.tag
			}
			<<< DateInlineRow("DateInlineRow"){
				$0.title = $0.tag
			}
			<<<	TimeInlineRow("TimeInlineRow"){
				$0.title = $0.tag
			}
			<<< DateTimeRow("DateTimeRow"){
				$0.title = $0.tag
			}
			<<< DateTimeInlineRow("DateTimeInlineRow"){
				$0.title = $0.tag
			}
			<<< CountDownRow("CountDownRow"){
				$0.title = $0.tag
			}
			<<< CountDownInlineRow("CountDownInlineRow"){
				$0.title = $0.tag
			}
			<<< DatePickerRow("DatePickerRow"){
				$0.title = $0.tag
			}
			<<< TimePickerRow("TimePickerRow"){
				$0.title = $0.tag
			}
			<<< DateTimePickerRow("DateTimePickerRow"){
				$0.title = $0.tag
			}
			<<< CountDownPickerRow("CountDownPickerRow"){
				$0.title = $0.tag
			}

Unfortunately, this shows all pickers below the input fields:

![simulator screen shot 27 11 2015 21 52 15](https://cloud.githubusercontent.com/assets/392542/11448050/43db7872-9551-11e5-80a5-0fb02f7d8b9e.png)

**Comment by mtnbarreto** [comment]
@marbetschar I can't see anything wrong. 

`DateTimePickerRow` and `CountDownPickerRow` shows the UIDatePicker embedded in a table view cell.

**Comment by mtnbarreto** [comment]
@marbetschar f you this this should work differently reopen the issue and give me more details.

**Comment by marbetschar** [comment]
*huh* ?

The cells are all open, without the need of tapping them first. Instead of this, they should be closed till the user taps them...?

**Comment by mtnbarreto** [comment]
According to the image you posted the picker view that appear on the screen are the `DatePickerRow` and `TimePickerRow `. All the rows that appears above or either shows the date picker as a inputView or as a inline cell.
