### ISSUE TITLE
Cannot disable/enable an existing row

### ISSUE THREAD

**Issue by haithngn** [xmartlabs/Eureka#1094]
I have a row with these code:
```
<<< NameRow(){ [unowned self] row in
            row.tag = self.Fields.name
            row.title = "Name"
            row.placeholder = "Ware Name"
            row.value = data.name
```

In another function I try to disable this row but nothing happended:
```
if let nameRow = form.rowBy(tag: Fields.name) as? NameRow
            {
            debugPrint("enabling")
            nameRow.disabled = true
            nameRow.reload()
        }
```

Could you show me how to enable/disable a row in runtime ?

Thanks,

**Comment by haithngn** [comment]
I did figured out the tricks, just call this function
`nameRow.evaluateDisabled()`

I think we should have a documentation for this. :(

**Comment by monica18p** [comment]
This solution doesn't work for me.. I can still edit IntRow :(
