### ISSUE TITLE
Crash for both LocationRow() and ImageRow()

### ISSUE THREAD

**Issue by Maryom** [xmartlabs/Eureka#1095]
Hi,

Thanks for your awesome repo. I used it and I got the below error when:
1. I clicked back in `LocationRow()`
2. I picked an image`ImageRow()`

Any help?

- Environment: Eureka, Xcode and iOS version you are using.
Eureka 3.0.0
Xcode 8.3.3
iOS version 10.3

- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

This is Xcode console output:
```
assertion failed: Duplicate tag Extra Info: file /Pods/Eureka/Source/Core/BaseRow.swift, line 172
2017-06-11 17:25:46.671801+0300 Zcare[3959:981354] assertion failed: Duplicate tag Extra Info: file /Pods/Eureka/Source/Core/BaseRow.swift, line 172
(lldb) 
```

<img width="636" alt="screen shot 2017-06-11 at 5 04 22 pm" src="https://user-images.githubusercontent.com/3218401/27011721-ad0b56d0-4eca-11e7-81ec-02ff33d5ca93.png">

**Comment by Maryom** [comment]
Problem solved 😊 I got this error because I setup the form in `viewWillAppear`. I solved my problem by moving the setup to `viewDidLoad`.

Thanks again for your awesome repo. 👌🏼

**Comment by igordeoliveirasa** [comment]
You saved my day! Thanks.
