### ISSUE TITLE
Swift-4 Branch tries compiling with swift 3 when using Cocoapods

### ISSUE THREAD

**Issue by garfbargle** [xmartlabs/Eureka#1096]
Using the latest Xcode 9 beta and cocoa pods to install Eureka. The Eureka pod has it's project settings to use swift 3 instead of swift 4. Currently using this code in my Podfile to correct it.

```ruby

# Manually making Eureka compiler version be swift 4.0
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'Eureka'
        print "Changing Eureka swift version to 4.0\n"
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
  end

```

**Comment by m-revetria** [comment]
Hi @garfbargle, thanks for the code snippet it will be useful.

Seems that right now there is not an standard way to indicate which Swift version should be used in the Podspec [Cocoapods - #6791](https://github.com/CocoaPods/CocoaPods/issues/6791).

Meanwhile, you can solve it by changing the Podfile as you pointed out or by setting the SWIFT_VERSION flag to 4.0 in your project settings:

![image](https://user-images.githubusercontent.com/4791678/27556846-c26c54ba-5a8d-11e7-8d54-8db43a5a7887.png)

Then reinstall your pods, your'll end up having Eureka compiling with Swift 4

![image](https://user-images.githubusercontent.com/4791678/27556917-01448982-5a8e-11e7-8e4c-a3e4a6a13dc1.png)
