### ISSUE TITLE
Why using "public" keyword on tableView(_:commit editingStyle:forRowAt indexPath:)?

### ISSUE THREAD

**Issue by Eric0625** [xmartlabs/Eureka#1097]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by Eric0625** [comment]
I can see the normal tableview functions are prefixed with "open" keyword, but this function is not. I'm using another table with "form" on the same view controller, so this makes it impossible to customize my table's editing style

**Comment by m-revetria** [comment]
Hi @Eric0625, this was solved in  #1113. It will be available in the next release. Meanwhile, you can use this fix if you point to the commit [d9943830](https://github.com/xmartlabs/Eureka/commit/d99438300b7a427cffb451827008493e28c161c8).
