### ISSUE TITLE
BaseCell error: "Getter for 'height' with Objective-C selector 'height' conflicts with..."

### ISSUE THREAD

**Issue by staz1000** [xmartlabs/Eureka#1099]
All I have done is add the files to a prototype project and I get this error in BaseCell:

> Getter for 'height' with Objective-C selector 'height' conflicts with method 'height()' from superclass 'UIView' with the same Objective-C selector

Really not sure why it happens in this project and not the example one. If I rename the property it all works fine. Anyone having this?

**Comment by santiagofm** [comment]
Hey @staz1000 !
Have you found a solution for this issue ?
