### ISSUE TITLE
Disable selected cell title highlighting

### ISSUE THREAD

**Issue by dwightwatson** [xmartlabs/Eureka#11]
Is it possible to disable the highlighting of the title of the currently selected cell? I don't see it in the documentation, and a quick browse through the code seems to indicate you'd need to manually set the highlight colour to be the same as the default text colour. It would be great if there was a way you could disable it completely.

**Comment by mtnbarreto** [comment]
@dwightwatson 
The easiest way to do that is making use of default row initializers.

The following code disable `NameRow` highlighting.

```swift
NameRow.defaultRowInitializer = { row in
            row.onCellHighlight { _, _  in }
            row.onCellUnHighlight { _, _ in }
        }
```

You should do the same to each row type you want to disable.
Cheers

**Comment by dwightwatson** [comment]
Awesome, nice solution. Thank you!
