### ISSUE TITLE
DateRow returning wrong date

### ISSUE THREAD

**Issue by murraycollingwood** [xmartlabs/Eureka#1100]
- Environment: Eureka, Xcode and iOS version you are using.
Not sure where to find the Eureka version - it's only a few weeks old so I'm assuming it is the latest:
### [3.0.0](https://github.com/xmartlabs/Eureka/releases/tag/3.0.0)

Xcode 8.3.3
iOS 10.3 on iphone 6 (simulator)

I add a DateRow to my form, the date I select is 15-6-2017 but the date that arrives at the server is 14-6-2017

Timezone for the phone is Australia/Brisbane
Timezone for the server is Pacific/Auckland

On my app in the DateRow I select 15-6-2017
When printed from my app it says "sox_datebegin" = "2017-06-14 14:00:00 +0000";
At my server it still says [sox_datebegin] => 2017-06-14 14:00:00  0000

However, I'm not sure what I'm supposed to do with this value to translate it back to 15-6-2017

**Comment by murraycollingwood** [comment]
I've been playing with this some more and have just realised you can't really pass just a date to this control.  The date must be a date/time value and passed in a full GMT (with timezone) format to the make this work correctly, otherwise the wrong date can be displayed.
It's good to have a consistent way of handling dates, but to support different timezones there is a lot of converting to/from GMT.
Personally I like to work with just two, one is the local time and the other is the server time, and then a simple function to convert from one to the other.

**Comment by m-revetria** [comment]
Hi @murraycollingwood,

This doesn't seem to be an Eureka issue, there is not a date-only class (without time) on iOS. You'll have to keep that in mind when using the date value returned by the Eureka's cell. It only takes care of the presentation of a date-time value allowing users to enter just the date part.

So if you want to only send the date to your server, you have to consider adding the timezone offset to the date value got from Eureka's cell and then get rid of the time part when sending it to your server. If you are using ISO-8601 format you can send it as follow "yyyy-MM-dd"

Regards

**Comment by m-revetria** [comment]
I'm closing this due to lack of response.
