### ISSUE TITLE
SetValues not working

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1102]
Trying to update separate rows once values have changed in target row. The setValues() func does not seem to be updating. Currently have:

```
                }.onChange{ row in
                    self.form.setValues(["OtherBooleanRowTag": true])
        }
```

Not sure the reason this seems not to be working, unless need to assign delegate to the current row.

**Comment by m-revetria** [comment]
Hi @JesseNoBata you can either reload the row (`self.form.allRows.first(where: { $0.tag == "OtherBooleanRowTag"})?.reload()`) or the entire table (`self.tableView.reloadData()`)

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
