### ISSUE TITLE
Cocoapods dependency is not updated between Eureka and ImageRow

### ISSUE THREAD

**Issue by Kibonakamura** [xmartlabs/Eureka#1104]
Trying to install both frameworks, I saw that the dependency are not updated. 

The error in the terminal is:
- `Eureka (~> 3.0)` required by `Podfile`
- `Eureka (~> 2.0.0-beta.1)` required by `ImageRow (1.0.0)`

Thank you!

**Comment by m-revetria** [comment]
@Kibonakamura, `ImageRow`'s version [2.0.0](https://github.com/EurekaCommunity/ImageRow/releases/tag/2.0.0) has support for Eureka 3.0.0. It was released on May 25th.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
