### ISSUE TITLE
Crashing when deleting a row in MultivaluedSection

### ISSUE THREAD

**Issue by LeonardoCardoso** [xmartlabs/Eureka#1108]
Hey guys, I've been trying to use MultivaluedSection but it crashes when removing an item. And I've tried in all main branches: `master`, `swift-4`, `swif3.2`.

- Environment: Eureka 3.0.0, Xcode 8 and 9 and iOS 10 and 11.

<img width="1407" alt="screen shot 2017-06-17 at 01 20 05" src="https://user-images.githubusercontent.com/1775157/27247717-7886380a-52fb-11e7-946a-0d6c6c8fa754.png">

Any hint of what is causing it?

**Comment by LeonardoCardoso** [comment]
I noticed that `public func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath)` is being called twice when removing the last row of a section and more than that when another row other than last one is removed.

I've fixed that by removing the following lines
```swift
DispatchQueue.main.async {
 tableView.isEditing = !tableView.isEditing
 tableView.isEditing = !tableView.isEditing
}
```
[Core.swift#L780-L783](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Core.swift#L780-L783)

And editing this subscript.

```swift
public subscript(indexPath: IndexPath) -> BaseRow {
   return allSections[indexPath.section].count > indexPath.row ? self[indexPath.section][indexPath.row] : BaseRow()
}
```
[Form.swift#L66-L68](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Form.swift#L66-L68)

**Comment by m-revetria** [comment]
@LeonardoCardoso I tried the examples provided in the repo by deleting and inserting rows to the multivalued section without any issue. You can take a look to the examples under "Multivalued Sections" and play around with the several examples there.

Please provide us with part of the code that is crashing or with an example project where we can reproduce the bug.

**Comment by LeonardoCardoso** [comment]
I retried `pod update` with the provided examples and still crashing. I’ve decided to use the standard table view. It might be some configuration of mine. I’m closing the issue for now.
