### ISSUE TITLE
Minimum Date not being applied to DateTimeInlineRow

### ISSUE THREAD

**Issue by Gman9855** [xmartlabs/Eureka#111]
I want my minimum date on the date picker to be the current date.  So i simply set it like so...  $0.minimumDate = NSDate() but it doesn't seem to change anything.  Am i missing something?

**Comment by mtnbarreto** [comment]
@Gman9855 Could you post the code that define the date row?

**Comment by mtnbarreto** [comment]
<<< DatePickerRow() { $0.minimumDate = NSDate() } 

using the code above the UIPickerView doesn't allows me to select a earlier date than NSDate.

Could you confirm you are setting $0.minimumDate from the row constructor block?

**Comment by Gman9855** [comment]
I'm not using a DatePickerRow, i'm using a DateTimeInlineRow

**Comment by Gman9855** [comment]
Figured it out-  need to call onExpandInlineRow and then set the minimumDate property on the DateTimePickerRow from the callback

**Comment by mtnbarreto** [comment]
Did you mean `onPresentInlineRow`?

**Comment by Gman9855** [comment]
Well maybe it works there too-  but i'm doing it in onExpandInlineRow, where i can grab a reference to the DateTimePickerRow

**Comment by mtnbarreto** [comment]
This is actually a bug :(. Shouldn't be necessary to set up again the property from `onExpandInlineRow `.
