### ISSUE TITLE
makeRowVisible: scrollToRow feature request for inlineRow

### ISSUE THREAD

**Issue by yurevich1** [xmartlabs/Eureka#1110]
It would be nice if you will implement state function where the table will scroll (top or bottom of the cell) after inlinerow is rolled out.

To implement I've wrote these changes. Please, add them into main branch.

1.  at [BaseRow.swift](https://github.com/xmartlabs/Eureka/blob/547b9b8f66bf4f1d8e875b17a43e55fee5e1c016/Source/Core/BaseRow.swift#L104) add this method 

```
/**
     scrolls to wanted part of view
     */
    open func scrollToTop() -> Bool {
        return false
    }
```

2. at [InlineRowType](https://github.com/xmartlabs/Eureka/blob/547b9b8f66bf4f1d8e875b17a43e55fee5e1c016/Source/Core/InlineRowType.swift#L88)

```
let stt = scrollToTop()
cell.formViewController()?.makeRowVisible(inline,stt)
```

3. at [Core](https://github.com/xmartlabs/Eureka/blob/074ad432e697650087276e01c67bbb255e3ab1f4/Source/Core/Core.swift#L1052) change into 
```
func makeRowVisible(_ row: BaseRow, _ scrollToTop:Bool){
```

4. at [Core](https://github.com/xmartlabs/Eureka/blob/074ad432e697650087276e01c67bbb255e3ab1f4/Source/Core/Core.swift#L1055) change into 
```
tableView.scrollToRow(at: indexPath, at: scrollToTop ? .top :.bottom, animated: true)
```

***Usage*** :
override this method somewhere in new class.

```
//scrollToTop
    open override func scrollToTop() -> Bool {
        return true
    }
```

Thanks.

**Comment by m-revetria** [comment]
Hi @yurevich1, seems that you have it already working. Would be great if you open a PR with the changes you've made so far. We'll review it and merge into main branch if everything looks good. 

Thanks!

**Comment by yurevich1** [comment]
I will do this asap

**Comment by yurevich1** [comment]
I can't push the chages. I'm receiving this.
```
git push --set-upstream origin final-scroll-position-type
Username for 'https://github.com': yurevich1
Password for 'https://yurevich1@github.com': 
remote: Permission to xmartlabs/Eureka.git denied to yurevich1.
fatal: unable to access 'https://github.com/xmartlabs/Eureka/': The requested URL returned error: 403
```

**Comment by yurevich1** [comment]
@m-revetria please check my pull request

**Comment by mtnbarreto** [comment]
Seems it was already merged. Closing...
