### ISSUE TITLE
Email error: "Unexpected CFBundleExecutable Key"

### ISSUE THREAD

**Issue by mafer-bc** [xmartlabs/Eureka#1119]
Hi, I'm getting an error with the Info.plist when uploading my iOS app to App Store. The error comes via email right after the upload to App Store finishes.
The deployment target of the app is iOS 10.0 and I'm using the latest version of the SDK -> 3.0.0.

This is the error:

> Unexpected CFBundleExecutable Key - The bundle at '/Payload/APP_NAME.app/Target Support Files/Eureka/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

If I do what is described in the error and erase the CFBundleExecutable Key, the app doesn't run in Xcode, and that's the only solution I have found in forums. I have also tried only changing the CFBundlePackageType to BNDL and setting Enable Bitcode to NO in my Project Settings, but it doesn't work.

I use CocoaPods to manage the library.

Any thoughts on what it can be?

**Comment by m-revetria** [comment]
Hi @mafer-bc that's weird. The framework's plist file is generated by cocoapods when you install it. If you check in the rest of pods that you are using, all of them have a pretty similar plist file. We even have released some apps a few days ago using Eureka without any issue.

Can you check if your target's plist file is included in the "Copy Bundle Resources" build phase? **It shouldn't be added**, that might produce some issue while uploading to the App Store, ref: https://stackoverflow.com/a/39615474/1070393

**Comment by mafer-bc** [comment]
Hi! I had already checked that, and the plist file wasn't there. 
I only have the localized plist, but it is a .strings file and the GoogleService-Info.plist, which is needed to use Google Services:

<img width="918" alt="screen shot 2017-06-21 at 3 10 08 pm" src="https://user-images.githubusercontent.com/17325089/27404565-2d1d7148-5694-11e7-81a6-0b348476cc2d.png">

The other files are fonts or other localized files. 
I noticed that the folder called "Target Support Files" that CocoaPods generates is in the "Copy Bundle Resources", I don't know if this is expected or needed?

**Comment by m-revetria** [comment]
I checked out some of my projects and I didn't see that folder being included in neither of them. This folder includes the Info.plist files for all the installed pods, so it can be the cause of your issue.

Can you try by removing it?

**Comment by mafer-bc** [comment]
Sure!
I'm building them archive right now 😀

**Comment by mafer-bc** [comment]
That worked! Thanks, I was struggling with this for a while!

**Comment by m-revetria** [comment]
Ok cool, I don't have idea how you ended up with that folder included in the "Copy Bundle Resources" phase.

**Comment by thankmelater23** [comment]
I'm having this issue.  Do i remove the info plist from my project target - build phases - copy bundle resources?  I just localized my info.plist file also.

**Comment by Alwaz** [comment]
> Target Support Files

I neither have info.plist nor "Target Support Files" folder but still facing this issue in 2023 Xcode 14.2. Any leads please?
