### ISSUE TITLE
Detecting taps in  UITableViewCellAccessoryview detailDisclosureButton?

### ISSUE THREAD

**Issue by dhmspector** [xmartlabs/Eureka#1121]
Is there a way to detect taps in the `row.cell.accessoryView` (for example if you've set it to  `UITableViewCellAccessoryType.detailDisclosureButton`)?  

- Environment:
 Eureka: v3.0
 Xcode:8.3.2
 iOS: 10.3

**Comment by m-revetria** [comment]
Hi @dhmspector,

You have to implement the function [`tableView(_:accessoryButtonTappedForRowWith:)`](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614996-tableview)
in your form view controller.

**Comment by m-revetria** [comment]
Closing this, seems that it's solved.
