### ISSUE TITLE
Pushrow Onpresenter event not working

### ISSUE THREAD

**Issue by kecoli2** [xmartlabs/Eureka#1126]
Version : 3.0.0

Xcode 8.3.3
iOS 10.3 on iphone 7 (simulator)
I add pushrow to my form .The pushrow no input primitive type .
The Onpresenter event does not work if the value is a class

            <<< PushRow<Adress>(){
                $0.title = "Address".fromResource
                $0.options = adressList
                }.onPresent{ form, to in
                    to.sectionKeyForValue = { option in
                       return option.accessoryText!
                    }
                }
But if the value is string or integer type the onpresenter event do works
Finally
This scenario works perfectly for the Multiple Selected Row type

**Comment by m-revetria** [comment]
Hi @kecoli2, what do you mean when you say that `onPresent` event doesn't work if the value is a class?

Could you please provide a project example where we can reproduce this issue. I just tried `PushRow` out on the Eureka's example project and it is working.

Regards

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
