### ISSUE TITLE
SliderRow left margin not aligned for iPhone Plus

### ISSUE THREAD

**Issue by Ziqi-Li** [xmartlabs/Eureka#1127]
Xcode: 8.3.3
Eureka: 3.0.0

SliderRow left margin is not aligned with other rows for iPhone Plus and SE.
Below is a screenshot showing this issue using iPhone 7 Plus simulator. Note the `SliderRow` is not aligned with the first `SwitchRow`.

<img width="352" alt="untitled" src="https://user-images.githubusercontent.com/5518908/27759810-491419c2-5dee-11e7-91b5-5c470b3c05d5.png">

I am using default settings for the SliderRow without setting:
```
<<< SliderRow(){
            $0.title = "Magnitude Threshold"
            $0.value = defaults.float(forKey: "alertLevel")
            $0.minimumValue = 1.0
            $0.maximumValue = 9.0
            $0.steps = 8
            $0.hidden = "$sub == false"
            }.cellUpdate{ cell, row in
            cell.textLabel?.font = UIFont(name: "Helvetica-Light", size: 16)
            cell.valueLabel.font = UIFont(name: "Helvetica-Light", size: 16)
            }.onChange { row in
                self.defaults.set(row.value, forKey: "alertLevel")
            }

```

**Comment by m-revetria** [comment]
Hi @Ziqi-Li, thanks for the report. We just made a PR fixing this: #1168.
