### ISSUE TITLE
Problems with OnChange

### ISSUE THREAD

**Issue by prsolucoes** [xmartlabs/Eureka#1129]
Im using last xcode/eureka version from cocoapods. After reopen my project until 2016 to fix a bug im trying to recompile it but get the errors:

<img width="989" alt="screenshot 2017-07-05 17 27 55" src="https://user-images.githubusercontent.com/395096/27883598-7a6764d6-61a7-11e7-87ca-5e2aefe26184.png">

**Comment by mtnbarreto** [comment]
Not sure what is going wrong but try using self?.form?.rowBy(tag: .....) (notice the ? after form property)

**Comment by prsolucoes** [comment]
Hi, didnt work.

<img width="984" alt="screenshot 2017-07-06 00 27 33" src="https://user-images.githubusercontent.com/395096/27894350-fc33f224-61e1-11e7-9496-6770859f1ea2.png">

**Comment by prsolucoes** [comment]
Can anyone help?

**Comment by Saruul-Ulzii** [comment]
pls upload whole class.

**Comment by Saruul-Ulzii** [comment]
pls try to remove self?, just form.rowBy()

**Comment by Saruul-Ulzii** [comment]
https://github.com/xmartlabs/Eureka/issues/113

**Comment by prsolucoes** [comment]
Hi,

I solve the problem using with this way:

```
if let row = self!.form.rowBy(tag: "name") as? TextRow {
```

Thanks, can close the issue.

**Comment by m-revetria** [comment]
Hi, thanks for let us know you found a solution! I'm closing this to keep the issue tracker clean.

Regards
