### ISSUE TITLE
why i cann't pod install it now, that is some trouble in Xcode9beta, so i change it from 2.0 to 3.0,but now i cann't install it successfully

### ISSUE THREAD

**Issue by 1432961067** [xmartlabs/Eureka#1132]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by m-revetria** [comment]
Hi @1432961067, can you share the error you're having when installing the pod?

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
