### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by deepanshg** [xmartlabs/Eureka#1133]
I am generating dynamic form using a json. Form consists of 400+ rows due to which it takes time to push the viewcontroller on the screen. I tried loading 100 rows first and then when screen is displayed other are added using a thread. But it didn't worked and showed errors. Can you tell me any other way to reduce the time.
I am using cocapods and master eureka

**Comment by deepanshg** [comment]
@m-revetria  can you please help me?

**Comment by mtnbarreto** [comment]
Can you please elaborate more on the question providing your code so we can reproduce the issue or at least see how you are adding the rows..?

> I have never seen a form with 400 rows.

**Comment by deepanshg** [comment]
`class Checkbox {
    var index: Int
    var form: Form
    
    init(index: Int, toform form: Form) {
        self.index = index
        self.form = form
        self.addSection()
        self.addQuestion()
        self.addOption()
    }
    
    func addSection(){
        form +++ SelectableSection<ImageCheckRow<String>>("", selectionType: .multipleSelection){section in
            var header = HeaderFooterView(title: "")
            header?.height = { 1 }
            section.header = header
            
            var footer = HeaderFooterView(title: "")
            footer?.height = { 1 }
            section.footer = footer

            section.tag = quesNumber
        }
    }
    
    func addQuestion()
    {
        let ques: String
        if(question[self.index][hindQues].stringValue != "")
        {
            ques = question[self.index][quesNumber].stringValue + " " + question[self.index][engQues].stringValue + "\n" + question[self.index][hindQues].stringValue
        } else{
            ques = question[self.index][quesNumber].stringValue + " " + question[self.index][engQues].stringValue
        }
        
        form.last!
            <<< LabelRow(){
                $0.title = ques
                $0.cell.textLabel?.numberOfLines = 0
                $0.cell.textLabel?.layoutMargins.left = 0
                
                
                }
                .cellSetup({ (cell, row) in
                    //         cell.height = ({return 10})
                })
    }

    
    func addOption(){
        for i in 0..<question[self.index][engOption].count {
            form.last! <<< ImageCheckRow<String>(question[self.index][quesIndex].stringValue + "." + String(i)) { lrow in
                lrow.title = question[self.index][engOption][i].stringValue
                lrow.selectableValue = question[self.index][engOption][i].stringValue + "." + String(i)
                
                lrow.value = nil
                }
                .cellSetup { cell, _ in
                    cell.trueImage = UIImage(named: "selectedRectangle")!
                    cell.falseImage = UIImage(named: "unselectedRectangle")!
                }
                
                <<< LabelRow () {
                    $0.title = question[self.index][hindOption][i].stringValue
                    $0.cell.textLabel?.numberOfLines = 0
                    }
        }
        
    
    }
}

`
This is a class for adding checkbox questions, similar classes exist for adding subjective, radio, number and other type of questions. The form consists of 150 questions which come from a json. Each question has separate section.

**Comment by deepanshg** [comment]
And if i ever use a background thread to add question it shows warning
`DispatchQueue.global(qos: .background).async {
 add()  //function which adds more question
}`
Why i cannot add using background thread.

**Comment by deepanshg** [comment]
@mtnbarreto Do you get my problem now?
