### ISSUE TITLE
MultivaluedSection showInsertIconInAddButton property does not have any effect

### ISSUE THREAD

**Issue by SkylerSeamans** [xmartlabs/Eureka#1135]
Setting showInsertIconInAddButton to false in a MultivaluedSection still shows the green Insert button.

This can be observed in the Example project in ViewController.swift line 1625 (Multivalued Only Insert)

Environment: Eureka 3.0.0, Xcode 8.3.3 and iOS 10.3

**Comment by harri121** [comment]
You can override the tableView delegate as a workaround:

`override func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCellEditingStyle {
        return .none
    }`

**Comment by rafalwojcik** [comment]
@mtnbarreto Fixed in my PR :)

**Comment by mtnbarreto** [comment]
#1557 fixes it.
