### ISSUE TITLE
How to update a Section?

### ISSUE THREAD

**Issue by prsolucoes** [xmartlabs/Eureka#114]
The section is updated, but only refresh if i scroll the form:

```
if let section = self?.form.sectionByTag("data") as Section? {
    section.header?.title = "Data"
}
```

How to force a section refresh?

**Comment by mats-claassen** [comment]
Hi, you can try by calling `tableView.reloadData()`. If you do not want to do that you could just reload that section using `tableView?.reloadSections(...)`.
Tell me if that works.
