### ISSUE TITLE
Rule Id always nil

### ISSUE THREAD

**Issue by linkrjr** [xmartlabs/Eureka#1140]
Hi,

I need to remove a rule I add on the fly but it seems all the Rules are created with nil ids

Is there any other way to obtain the rule identifier that the remove(ruleWithIdentifier: String) requires?

I am running the latest Eureka

**Comment by mspasov** [comment]
Create the rule, then assign an identifier to it and then add it to the row ruleset. After that you will be able to remove it by id.

**Comment by linkrjr** [comment]
@mspasov 

That is exactly what I did for the time being but I would expect the rules to have a regular initialiser that sets a random id or at least a convenience initialiser that accepts one.

It is a bit cumbersome having to set the ids on rules on a separate line
