### ISSUE TITLE
Compiler segmentation fault when compiling with Xcode9b3

### ISSUE THREAD

**Issue by anlaital** [xmartlabs/Eureka#1141]
Eureka version 3.0.0. This crash occurs across all branches. It's reproducible every time. I tested this with the `swift3.2` branch.

The culprit for the crash is the following:

```
extension SelectableSectionType where Self: Section {
...
}
```

Moving this implementation out of the `extension` to `Section` (where part of this already resides) fixes the compiler crash.

**Comment by akac** [comment]
If you use the Swift 4 branch and the Development version of Swift from swift.org, does that work? I went back to xcode9b2 because of this issue - it was happening all over the place for me.

**Comment by mspasov** [comment]
@akac yes, it works.

**Comment by mtnbarreto** [comment]
Please use https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift4 or  https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift3_2 with Xcode 9 Beta .
