### ISSUE TITLE
error: unable to execute command: Segmentation fault: 11  with xcode9b3

### ISSUE THREAD

**Issue by sandyway** [xmartlabs/Eureka#1142]
I tested with branch 3.2,4.
Both branch have the same error

**Comment by tosbaha** [comment]
It is a bug in compiler. Only fix for now is to use development branch of Swift Compiler.
1. Download [Development branch for Xcode](https://swift.org/download/#snapshots)
2. Install it
3. Open Xcode choose Toolchains and select Swift Development Snapshot

**Comment by funkenstrahlen** [comment]
So this will be fixed with the next Xcode beta?

**Comment by mspasov** [comment]
For sure. It's already been fixed in the tool chain.

**Comment by sandyway** [comment]
Thanks,it's been fixed in the lastest tool chain.
But there's some other issue with xcode9b3 not in Eureka.What a pity!I go back to xcode9b2.
