### ISSUE TITLE
swift4?

### ISSUE THREAD

**Issue by CoderJin** [xmartlabs/Eureka#1143]
github "xmartlabs/Eureka"  ??

**Comment by tosbaha** [comment]
github "xmartlabs/Eureka" "swift-4"

However, if you are using Xcode 9 beta 3, it won't compile. Check [this issue](https://github.com/xmartlabs/Eureka/issues/1142) for workaround

**Comment by CoderJin** [comment]
Can I compile with this branch? I tried it as if it was open。

**Comment by tosbaha** [comment]
I tried and it is working. I use Cocoapods but I don't think it matters as long as you use Development Branch of Swift Compiler.

**Comment by CoderJin** [comment]
I did not directly use the source code compiler, I did not Cocoapods, open the project directly suggested that the wrong, I try again, with Cocoapods, xcode9-beta3 feel unstable.

**Comment by mtnbarreto** [comment]
Please use https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift4 branch .

**Comment by jorgelub12** [comment]
How can I use https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift4 ?
