### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by phatmann** [xmartlabs/Eureka#1146]
The last release was in April, and there have been meaningful changes since then. Can you put out a new release to CocoaPods? Thanks.

**Comment by SkylerSeamans** [comment]
+1

**Comment by mtnbarreto** [comment]
Hi! We will do it shortly.

**Comment by wjiuxing** [comment]
any progress pls?

**Comment by mtnbarreto** [comment]
Done!! 3.1.0 is the latest release now.
