### ISSUE TITLE
Carthage: Build Failed Error65 - Xcode9 beta, Swift 3.2, HighSierra

### ISSUE THREAD

**Issue by carlchen1986** [xmartlabs/Eureka#1147]
Using Carthage with 

`github "xmartlabs/Eureka" ~> 3.0`

results in Error 65 during Build Command. I have a target setting in my project for Swift 3.2 in XCode9 Beta.  Can you help me with the issue so that I can build it and use it ? 

`
*** Building scheme "Eureka" in Eureka.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/thorsten/Apps/EurekaTest/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/thorsten/Library/Caches/org.carthage.CarthageKit/DerivedData/Eureka/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/thorsten/Apps/EurekaTest/Carthage/Checkouts/Eureka)`

Thanks
Thorsten

**Comment by christianselig** [comment]
I can't use the Swift 3.2 Xcode 9 branch with Cocoapods either (it won't compile).

**Comment by mtnbarreto** [comment]
@carlchen1986 Have you tested it with the lastest toolchain snapshot?

**Comment by christianselig** [comment]
@mtnbarreto Heh, what exactly does that mean? The lastest toolchain of Xcode? I'm aware it's under beta testing; totally not placing the blame on you!

**Comment by carlchen1986** [comment]
Sorry for the late response. I have meanwhile switched back to Sierra and Xcode 8.3.3. Will try this again when the stable releases are out and I have the proper time to test it. 

Thanks for the help.
