### ISSUE TITLE
In latest swift-3.2 branch, SelectableSection doesn't work properly

### ISSUE THREAD

**Issue by christianselig** [xmartlabs/Eureka#1149]
- Environment: Eureka 3.0 (Swift 3.2 branch), Xcode 9 (beta 3), iOS 10.3.3

Compared to the regular (Swift 3.0) version of Eureka, `SelectableSection` no longer updates the checkmark when selecting a new row, instead nothing happens at all. Identical code from the example project between the two versions behaves differently.

I'm not sure if this occurred only in the most recent Swift 3.2 update to Eureka, or if it's been there since the initial 3.0 -> 3.2 move.

**Comment by mtnbarreto** [comment]
Hi! Are you tanking about https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift3_2 branch?

**Comment by christianselig** [comment]
@mtnbarreto Indeed! Admittedly with a fresh project I can't even get it to compile anymore. Xcode 9 Beta 3.

Podfile:

```ruby
platform :ios, '9.0'
use_frameworks!

target 'Example' do
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
end
```

And it gives "Command failed due to signal: Segmentation fault: 11".

**Comment by christianselig** [comment]
@mtnbarreto Here's an example project showing it; pod is incorporated so no need to install. Fresh project from Xcode 9 with the only change being Swift 4 -> Swift 3.2.

[Example.zip](https://github.com/xmartlabs/Eureka/files/1146320/Hmm.zip)

**Comment by mtnbarreto** [comment]
@christianselig. Seems to me the same as #1147. Please use the latest toolchain development snapshot.

**Comment by christianselig** [comment]
@mtnbarreto Do you know of an article that dives into how to do that? I'm coming up short…

**Comment by christianselig** [comment]
Update! Figured it out, was searching for Xcode but it's a Swift toolchain, duh. Installed and all works well, thanks for the prompt help and awesome project! *closes*

**Comment by sthwicked** [comment]
@christianselig can I have a bit of help on this? I'm having the same issue

**Comment by sthwicked** [comment]
Just figured it out! For everyone else out there that is as clueless about this as I, use this guide: https://www.hackingwithswift.com/example-code/language/how-to-install-a-beta-version-of-swift
