### ISSUE TITLE
Contents under navigation bar

### ISSUE THREAD

**Issue by imWildCat** [xmartlabs/Eureka#116]
Code:
```swift
        form +++= Section() { section in
//            section.header = HeaderFooterView<UIView>(.Class)
//            section.header?.height = { 65 + 32 } // Only by doing this can fix the problem
            }
            <<< LabelRow() { label in
                label.title = "Title"
        }
```

![screenflow](https://cloud.githubusercontent.com/assets/2396817/11500246/e46baa74-9866-11e5-93bc-2d724f046a32.gif)

**Comment by mtnbarreto** [comment]
@imWildCat 
Which is the iOS sdk version? Are you using storyboards? or FormViewController was created programatically?

**Comment by imWildCat** [comment]
@mtnbarreto Sorry, I forgot to mention the details.

- iOS SDK: 9.1
- Using storyboard: Yes
- Xcode: 7.1.1
- System: 10.11.1

**Comment by mtnbarreto** [comment]
Thanks,
Could you please make sure that the table view IBOutlet and UITableview constraints are properly set up? It seems to me that this has nothing to do with Eureka.

**Comment by imWildCat** [comment]
Thank you very much.

I followed the storyboard of examples and fixed it.
