### ISSUE TITLE
Eureka reset some fields

### ISSUE THREAD

**Issue by alaindixon** [xmartlabs/Eureka#1161]
Hi,

I came across a weird thing. When I select some fields like a radio button Eureka clear some others text fields that I have previously setup.

Do you know what happen?

Cheers

Alain

**Comment by mtnbarreto** [comment]
@alaindixon Please share your form conposition and any custom row implementation you might have. Could you please follow the repository contribution guideline so I can give support more easily..?

Cheers

**Comment by mtnbarreto** [comment]
I will close the issue for now. @alaindixon  Reopen it adding the required info whenever you want.
