### ISSUE TITLE
Feature request: SelectorRow with ability to enter a new value

### ISSUE THREAD

**Issue by sverin** [xmartlabs/Eureka#1165]
In my use case I want to be able to use a PushRow (or other SelectorRow), but also let the user have to ability to enter a new value. Is this possible today? If not I would be a really neat feature.

Using latest version of branch: feature/Xcode9-Swift4

**Comment by realcarlos** [comment]
Yes , I need this kind of row  too

**Comment by mtnbarreto** [comment]
You will have to implement a custom row.
