### ISSUE TITLE
UITableViewRowAction - not appearing

### ISSUE THREAD

**Issue by pgawlowski** [xmartlabs/Eureka#1167]
Hi,

I'm trying to use MultivaluedSection form with `[.Insert]` option as well as default `UITableViewRowAction`

I'm implementing 
```
 func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]? {
        let delete = UITableViewRowAction(style: .destructive, title: "Delete") { (action, indexPath) in
        }
        let edit = UITableViewRowAction(style: .normal, title: "Edit") { (action, indexPath) in
        }
        
        return [delete, edit]
    }

```

as well as overriding 
```
   override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
```

However I am unable to use swipe action on cell. The `editActionsForRowAt` function works fine - when I was using option `[.Delete]` with control button provided by default it was showing the correct options, however I need to introduce this feature as a swipe-on-row.

Cheers!

**Comment by mkoorn** [comment]
Same issue for me.

**Comment by mkoorn** [comment]
@pgawlowski did you find a fix for this issue?

**Comment by pgawlowski** [comment]
@mkoorn yup :) 

As far as I remember I had to set
`        tableView.setEditing(false, animated: false)
`

In `viewDidLoad`
