### ISSUE TITLE
why in defaultCellUpdate block cell.width not equal tableView.width?

### ISSUE THREAD

**Issue by Pr-Chen** [xmartlabs/Eureka#1169]
when the cell display at the first time, cell.width is not equal tableView.width, when i scroll the tableView, the cell appear again, cell.width is right.

the demo is run in my iphone 5s, tableview.width is 300, cell.width is 320 at first time.so that the right round corner is wrong
https://ws2.sinaimg.cn/large/006tKfTcly1fhx2sui59rg30hs0vkx6v.gif
![](https://ws2.sinaimg.cn/large/006tKfTcly1fhx2sui59rg30hs0vkx6v.gif)

this is my code:
![](https://ws3.sinaimg.cn/large/006tKfTcly1fhx1s6yyorj318k0t6ahk.jpg)
![](https://ws4.sinaimg.cn/large/006tKfTcly1fhx1y3l5grj317s0gg780.jpg)

and i need write the code at defaultCellUpdate, why not defaultCellSetup?

**Comment by mats-claassen** [comment]
`cell.textLabel.textColor` should be set in cellUpdate. The other things could be set in cell setup.

Cells having the wrong width often comes from wrong constraints or some iOS layout issue. You could try to reload the tableView at the beginning to fix this as well.
