### ISSUE TITLE
ListCheckRow evaluateDisabled() broken if row is checked

### ISSUE THREAD

**Issue by dazeili** [xmartlabs/Eureka#1170]
I got a FormViewController with an edit/done button. At start all rows are disabled.

When i segue to the form evaluation is working. My rows are disabled, also the checked ones. When I  tap the edit button, which is calling: `form.rows.forEach{ $0.evaluateDisabled() }` every row gets enabled. 
And now the error occurs: I click the done button and all rows except the checked listCheckRows get disabled. Now functionality for this rows is broken.

Here is my row code:

```swift
form.last! <<< ListCheckRow<Diary>{
                $0.title = diary.title
                $0.selectableValue = diary
                $0.value = (entry?.diaries?.contains(diary) ?? false) ? diary : nil
                $0.disabled = Condition.function([]) { _ in return !self.editMode }
            }
```

![simulator screen shot - iphone 7 - 2017-07-26 at 12 58 22](https://user-images.githubusercontent.com/554864/28617801-21fb4144-7202-11e7-81c9-4166ec773fe2.png)

**Comment by mtnbarreto** [comment]
You should invoke `evaluateDisabled` as documentation indicates. https://github.com/xmartlabs/Eureka#row-does-not-update-after-changing-hidden-or-disabled-condition
