### ISSUE TITLE
How to disable copy and paste feature on specific field?

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#1171]
I didnt managed to find anything except to sub class `UITextField` in order to use the

`canPerformAction func`

is there anything that i can check in order to disable copy and paste feature?

Cheers

Desmond

**Comment by kohdesmond** [comment]
@mtnbarreto any ideas about it?

**Comment by ltblueberry0** [comment]
https://stackoverflow.com/questions/6701019/how-to-disable-copy-paste-option-from-uitextfield-programmatically

**Comment by mats-claassen** [comment]
I d not know another way of implementing that. Subclassing seems to be the way to go.
