### ISSUE TITLE
textLabel overlaps detailTextLabel when using long String

### ISSUE THREAD

**Issue by Laptopmini** [xmartlabs/Eureka#1172]
**Environment:**
* Eureka: 3.0.0
* XCode: 8.3.2

**Description of Issue:**
When using a long String as the title of a Row, this title may overlap onto its value.

**Suggested Fix:**
* Set proper trailing/leading constraint to avoid overlap.
* (Optional) Set minimum font scale

**Potential (hack) workaround:**
* Set `textLabel`'s `numberOfLines` to `0`
* Set Cell static height in `cellSetup` based on `textLabel` value character count.

**Screenshot:**
![http://i.imgur.com/8kawTf4.png](http://i.imgur.com/8kawTf4.png)

**Related Issue(s):**
#900, #762

**Comment by mtnbarreto** [comment]
Could you fix it? From my understanding we are using UIkit native UItableViewCell to display these rows. It should also happens in non-eureka cell. 

Have you tested in swift 4?

**Comment by Laptopmini** [comment]
Using the suggested fix, this is the best result I am able to reach at the moment:
![](http://i.imgur.com/1BIuawh.png)

I'm trying to add some constraints to make it behave correctly, but it's not being very friendly.

**Comment by Laptopmini** [comment]
Suggestions are welcome. I tried disabling `translatesAutoresizingMaskIntoConstraints` on both labels and just redoing to AutoLayout constraints, but it just results in more unpredictable behavior.

**Comment by laurens325** [comment]
This same problem also occurs for StepperRows: 
![schermafbeelding 2017-07-28 om 20 21 51](https://user-images.githubusercontent.com/14941372/28731027-9c85eb0e-73d2-11e7-849e-84d7583807b6.png)

**Comment by leesherwood** [comment]
Not sure if this helps anyone. But using Auto-Layout you can at very least make things truncate or `adjustSizeToFit` so nothing overlaps. If you move the control into the cell's contentview along with the text label, then you get a little more layout control (or at least that's what i needed to do to get this example working, I haven't spent hours on it).

I have no idea if moving the controls into the content view will have any knock on effect with other UI parts of this library, but the example i've got below seems to work fine. To be fair this is probably where you should be using a custom cell of some kind or using a custom textLabel.

Please note that i've only been using this library for about 2 hours and I've literally thrown this example together as I happened to stumble across this issue when searching for something similar and thought I could contribute something back. The code could definitely be cleaned up! Oh and it's using SnapKit for Auto-Layout, but i'm sure you can work it out if your not using SK.

    +++ Section("Truncated Stepper")
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.cellSetup { cell, _ in
                
                    cell.textLabel!.setContentCompressionResistancePriority(500, for: .horizontal)
                    cell.textLabel!.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.left.equalToSuperview().offset(15)
                    }
                    
                    cell.valueLabel?.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.left.equalTo(cell.textLabel!.snp.right).offset(10)
                        make.right.equalTo(cell.stepper.snp.left).offset(-10)
                    }
                    
                    cell.stepper.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.right.equalToSuperview().offset(-15)
                    }
                    
                }
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
        
        
            +++ Section("Shrinking Stepper")
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.cellSetup { cell, _ in
                    cell.textLabel!.adjustsFontSizeToFitWidth = true
                    cell.textLabel!.setContentCompressionResistancePriority(500, for: .horizontal)
                    cell.textLabel!.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.left.equalToSuperview().offset(15)
                    }
                    
                    cell.valueLabel?.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.left.equalTo(cell.textLabel!.snp.right).offset(10)
                        make.right.equalTo(cell.stepper.snp.left).offset(-10)
                    }
                    
                    cell.stepper.snp.makeConstraints { make in
                        make.centerY.equalToSuperview()
                        make.right.equalToSuperview().offset(-15)
                    }
                    
                }
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
            
            +++ Section("Multiline Stepper")
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right, i've added some extra text to make this even bigger"
                $0.value = 1
                $0.cellSetup { cell, _ in
                    
                    // Move the ui into the content view... :/
                    cell.contentView.addSubview(cell.valueLabel!)
                    cell.contentView.addSubview(cell.stepper)
                    
                    
                    cell.textLabel!.adjustsFontSizeToFitWidth = false
                    cell.textLabel!.lineBreakMode = .byWordWrapping
                    cell.textLabel!.numberOfLines = 0
                    cell.textLabel!.setContentCompressionResistancePriority(500, for: .horizontal)
                    cell.textLabel!.translatesAutoresizingMaskIntoConstraints = false
                    cell.textLabel!.snp.makeConstraints { make in
                        make.top.bottom.equalToSuperview().inset(15)
                        make.left.equalToSuperview().offset(15)
                    }
                    
                    
                    cell.valueLabel?.snp.makeConstraints { make in
                        make.top.equalTo(cell.textLabel!.snp.top)
                        make.left.equalTo(cell.textLabel!.snp.right).offset(10)
                        make.right.equalTo(cell.stepper.snp.left).offset(-10)
                    }
                    
                    cell.stepper.snp.makeConstraints { make in
                        make.top.equalTo(cell.textLabel!.snp.top)
                        make.right.equalToSuperview().offset(-15)
                    }
                    
                    cell.updateConstraintsIfNeeded()
                    
                }
                
                $0.displayValueFor = { v in
                    return "\(v!)"
                }
                
            }
        
            +++ Section("Full line Stepper")
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right"
                $0.value = 1
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
            }
            <<< StepperRow() {
                $0.title = "Please select a value using the stepper control to the right, and this long piece of text should make the cell grow"
                $0.value = 1
                $0.cellSetup { cell, _ in
                    
                    // Move the ui into the content view... :/
                    cell.contentView.addSubview(cell.valueLabel!)
                    cell.contentView.addSubview(cell.stepper)
                    
                    cell.textLabel!.adjustsFontSizeToFitWidth = false
                    cell.textLabel!.lineBreakMode = .byWordWrapping
                    cell.textLabel!.numberOfLines = 0
                    cell.textLabel!.translatesAutoresizingMaskIntoConstraints = false
                    cell.textLabel!.snp.makeConstraints { make in
                        make.top.left.right.equalToSuperview().inset(15)
                    }
                    cell.valueLabel?.snp.makeConstraints { make in
                        make.top.equalTo(cell.textLabel!.snp.bottom).offset(10)
                        make.left.equalTo(cell.textLabel!.snp.left)
                        make.right.equalTo(cell.stepper.snp.left).offset(-10)
                    }
                    
                    cell.stepper.snp.makeConstraints { make in
                        make.top.equalTo(cell.valueLabel!.snp.top)
                        make.right.equalToSuperview().offset(-15)
                        make.bottom.equalTo(cell.contentView.snp.bottom).offset(-10)
                    }
                    
                    cell.updateConstraintsIfNeeded()

                    
                }
                $0.displayValueFor = { v in
                    return "Value is \(v!) now"
                }
                
        }


![image](https://user-images.githubusercontent.com/1732877/30608965-e6f830f2-9d71-11e7-97be-c59bc6586bb3.png)

![image](https://user-images.githubusercontent.com/1732877/30608974-ef53804e-9d71-11e7-83fb-2c66349b7a2e.png)


Auto-layout seems happy enough with it too, no ambiguity :)

![image](https://user-images.githubusercontent.com/1732877/30608999-0357050c-9d72-11e7-9259-7753c886836a.png)

**Comment by lucasromanomr** [comment]
O mesmo esta acontecendo comigo, porém estou usando Xcode 9 + Swift 4. Está ultima versão fez com que não funcionasse mais o `numberOfLines = 0`, antes bastava colocar isso para que o autolayout funcionasse.

**Comment by micchyboy1023** [comment]
`numberOfLines = 0` didn't work for me too.
When I use SegmentedRow, the long title overlaps segmented control.

**Comment by mats-claassen** [comment]
This issue is addressed in #1701 and #1702 for StepperRow and SegmentedRow.

**Comment by mats-claassen** [comment]
The PRs have been merged so that we will close this. Please open a new issue if it appears on another row.

**Comment by PreetikaSingh** [comment]
Hi Im facing issue on this

![Screen Shot 2019-03-29 at 4 55 55 PM](https://user-images.githubusercontent.com/46670148/55229644-9c4ba380-5243-11e9-8113-9e072bef5659.png)

Please let me know what is snp here ?

**Comment by anhhtbk** [comment]
@PreetikaSingh Did you install and import `SnapKit`
