### ISSUE TITLE
Validation.swift 's filename conflict with Alamofire

### ISSUE THREAD

**Issue by neil-wu** [xmartlabs/Eureka#1173]
[Alamofire](https://github.com/Alamofire/Alamofire) project has a same file named `Validation.swift`. When we use Alamofire and Eureka 's source code (not cocoapod)  in one project, xcode will give an error like this: `error: filename "Validation.swift" used twice`.  Just rename one of them will solve this error.

- Environment: Eureka, Xcode  8.3.3 (8E3004b) and iOS 9.0.2

**Comment by mtnbarreto** [comment]
@neil-wu  Why are you adding the source files directly to the project?

**Comment by mtnbarreto** [comment]
Please use Eureka library as a Framework and prefix the `Validation` class with module name, `Eureka. Validation`.
