### ISSUE TITLE
Shouldn't a ButtonCell's tintColor be the same as the window's tintColor by default?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#1175]
I often set `window.tintColor` in the application did finish launching method to get all everything tinted the right color. However, `ButtonCell`'s color is by default always the blueish color. Wouldn't it make more sense to make it the same as the windows tint color?

**Comment by karlvr** [comment]
I believe this issue is tied into the troubled #1439. Just for reference, we're trying to fix it :-)

**Comment by karlvr** [comment]
And now #1492. I suggest closing this issue if / when #1492 is closed.

**Comment by mats-claassen** [comment]
This should be fixed. Please open new issue if problem arises again
