### ISSUE TITLE
SliderRow .disabled not working

### ISSUE THREAD

**Issue by Iambecomeroot** [xmartlabs/Eureka#1176]
## Environment:
* Eureka: 3.1.0
* Xcode: 8.3.3 (8E3004b)
* iOS: 10.3

## Problem
I am trying to disable a slider based on the state of a `SegmentedRow`. My code looks like this:

```swift
$0.disabled = .function(["state"], {
  let disabled = ($0.rowBy(tag: "state") as? SegmentedRow<State>)?.value != .manual
  print(disabled)
  return disabled
})
```

If I set `.cell.slider.isEnabled` in the segmented row's `.onChange`, everything works perfectly. It would be nice if `.disabled` worked though.

Also, is there a way to write that `.disabled` function as a string? Something like `.disabled = "$state != .manual"`?

**Comment by mtnbarreto** [comment]
Hi @Iambecomeroot!
It seems to me this issue was already fixed.
