### ISSUE TITLE
can we add #if swift(>=3.2) to swift branch to pull into master

### ISSUE THREAD

**Issue by jaz-ah** [xmartlabs/Eureka#1178]
Ideally instead of having to point my Pods to your swift feature branches, we would add #if swift conditionals in the code to compile correctly on either Xcode8.3.3 or Xcode9.0 - then you could release a new version that compiles for either and we wouldn't have to have feature branches to point to different pod versions in our own codebase.... @mtnbarreto thoughts?

**Comment by jaz-ah** [comment]
for example in Section.swift:

    #if swift(>=3.2)
    public subscript (range: Range<Int>) -> ArraySlice<BaseRow> {
        get { return kvoWrapper.rows.map({ $0 as! BaseRow })[range.lowerBound...range.upperBound] }
        set {
            replaceSubrange(range, with: newValue)
        }
    }
    #else
    public subscript (range: Range<Int>) -> [BaseRow] {
        get { return kvoWrapper.rows.objects(at: IndexSet(integersIn: range)) as! [BaseRow] }
        set {
            replaceSubrange(range, with: newValue)
        }
    }
    #endif

**Comment by mtnbarreto** [comment]
Hi @jaz-ah , Once Xcode 9 gets released, the latest Eureka release source code will be in swift 4. According Swift documentation we can continue having our code in swift 3 and some frameworks (including Eureka) in swift 4 due to swift 4 compatibility capabilities.

**Comment by jaz-ah** [comment]
@mtnbarreto understood, but I'm wondering until then if we can make master at least swift3.2 compatible w/ the #if's above?

**Comment by ldiqual** [comment]
@mtnbarreto My understanding is that the Swift 3.2 branch does not compile on Xcode 8, which means our devs have to use the Swift 3.2 compiler as soon as our app bumps the eureka dependency. Is conditional compiling for <3.2 something that is into consideration? Any alternative maybe?

**Comment by jaz-ah** [comment]
y - simplest changes are to conditionally compile like my example above which is compatible w/ both xcode8+9 and means devs don't have to have different branches/etc... while we're waiting for xcode9/swift4 to be final yet...

**Comment by mspasov** [comment]
@jaz-ah is right, it's very convenient to have Xcode 8 & Xcode 9 compatibility in the pre-swift 4 branch . Swift compiler conditionals are a safe bet. This would allow working on the project with Xcode9, but compiling it for App Store release with Xcode 8.3. I can prepare a PR for this.

**Comment by ldiqual** [comment]
I opened a PR for Swift 3.1 / Xcode 8 support here: https://github.com/xmartlabs/Eureka/pull/1199. Feel free to review!

**Comment by jaz-ah** [comment]
non-issue now that Swift4 support is in the main branch but in the future for swift updates this would still be helpful instead of dealing w/ multiple branches.
