### ISSUE TITLE
Eureka Build Fail

### ISSUE THREAD

**Issue by bmoshirian** [xmartlabs/Eureka#1180]
Latest Eureka via pod file (3.0)
Xcode 8.3.3
Swift 3
iOS version 9.0 +

Error Shown with any row type added to code:
"Cannot convert value of type '(_) -> ()' to expected argument type 'String?' "

How can this be resolved?
An example has been provided below.

<img width="541" alt="screen shot 2017-08-02 at 2 42 55 pm" src="https://user-images.githubusercontent.com/12250493/28858003-e9012392-7790-11e7-8f6f-ca11c85efe46.png">

**Comment by mtnbarreto** [comment]
`Form` should be in lowercase, it's a controller variable.

**Comment by bmoshirian** [comment]
Thank you @mtnbarreto, I had another error which led me to change "form" to "Form". Both are fixed. Absolute legend.
