### ISSUE TITLE
Cannot find interface declaration for 'FormViewController

### ISSUE THREAD

**Issue by HeyYouNotYouYou** [xmartlabs/Eureka#1181]
Xcode 8.3.2, latest pod version of Eureka

I tried adding Eureka through pods and everything works fine, Until I subclass FormViewController.
My project is mainly Swift with some objective-c and c++. When Xcode tries to generate objective-c interface headers for my swift files, it outputs an error on myViewController: FormViewController.

The error is in "myproject-swift.h" header file : 'Cannot find interface declaration for 'FormViewController', superclass of 'myViewController'.

**Comment by tttthiagoooo** [comment]
I also had the same problem, but with Xcode 9.3. Did you solve it?

**Comment by jeremiasdsa** [comment]
Same problem here.

**Comment by jeremiasdsa** [comment]
Got it solved for me.

**Comment by mtnbarreto** [comment]
@tttthiagoooo @HeyYouNotYouYou  Have you solved the issue?

@jeremiasdsa What was wrong?

**Comment by mtnbarreto** [comment]
Closing the issue for now. Reopen if you still need help.

**Comment by jeremiasdsa** [comment]
Hi @mtnbarreto,

I had to create a custom header file  "Custom-myproject-swift.h" and remove the interfaces that make reference to FormViewController. So I could import #Custom-myproject-swift.h on my Objective-C portion of code. While keeping the FormViewController reference on "myproject-swift.h" to use Eureka on my swift portion of code.

**Comment by bvirlet** [comment]
I'm facing this exact issue as i migrated to Swift 5. 

For some reason, some Swift-only view controllers are imported in the -Swift.h header. Since they inherit from `FormViewController` which is not exposed to Objective-C, we have a problem.

MyProject-Swift.h:
```
SWIFT_CLASS("…")
@interface AuthViewController : FormViewController // <-- problem here
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end
```

**Comment by OxyFlax** [comment]
Same issue on my side. Becoming very important as we cannot build with new version of Xcode...

**Comment by bvirlet** [comment]
I think it will be fixed with the next release of Carthage (https://github.com/Carthage/Carthage/pull/2723)

**Comment by OxyFlax** [comment]
> I think it will be fixed with the next release of Carthage ([Carthage/Carthage#2723](https://github.com/Carthage/Carthage/pull/2723))

I'm using cocoapods and having the issue ;)

**Comment by TofPlay** [comment]
> I'm facing this exact issue as i migrated to Swift 5.
Same as @bvirlet

**Comment by marekpridal** [comment]
Same issue, I am unable to compile project (objc, objc++, swift) for simulator using Swift 5 compiler. I have same issue with https://github.com/danielgindi/Charts library, too.

**Comment by bvirlet** [comment]
@TofPlay the latest version of Carthage release _after_ my comment is 0.33.0. It does solve the issue for me.

**Comment by marekpridal** [comment]
Carthage 0.33.0 fixes this issue 👍
