### ISSUE TITLE
Xcode 9 Beta 4 - Several build errors

### ISSUE THREAD

**Issue by chwebb1** [xmartlabs/Eureka#1182]
I am having several issues compiling on Xcode 9 Beta 4.

Type ‘Section’ does not conform to protocol ‘BidirectionalCollection’

‘Collection’ requires the types ‘Section.SubSequence’ (aka ‘Array<BaseRow>‘) and ‘ArraySlice<BaseRow>’ be equivalent

Type ‘Section’ does not conform to protocol ‘RangeReplaceableCollection’
![screenshot2_720](https://user-images.githubusercontent.com/3332782/28927705-415d0a1c-7839-11e7-890e-1418f77ca4a1.png)
![screenshot1_720](https://user-images.githubusercontent.com/3332782/28927706-416584e4-7839-11e7-8569-775e1d0c772c.png)

I am using Eureka v. 3.1.0, and I have cleaned the build folder/cleaned the project. The project builds correctly on Xcode 8.

**Comment by jaz-ah** [comment]
@chwebb1 you should change your code to use the Eureka feature/swift3.2 branch and that will make things work

**Comment by jaz-ah** [comment]
see also https://github.com/xmartlabs/Eureka/issues/1178 - I filed this to @mtnbarreto so theoretically we could just fix this in the main branch so people wouldn't have to checkout different branches to make both xcode8+9 work.

**Comment by zoul** [comment]
FWIW, the branch that works in Xcode 9 was apparently renamed to `feature/Xcode9-Swift3_2`.

**Comment by mtnbarreto** [comment]
Please use feature/Xcode9-Swift3_2 or feature/Xcode9-Swift4 which supports Xcode 9. 
Once Xcode 9 get released we will have a Eureka release supporting Swift 4 as Swift 4 is the default Xcode 9 swift version.

**Comment by ravinleague** [comment]
Please use feature/Xcode9-Swift3_2 or feature/Xcode9-Swift4 
How do I use this ? Does this mean I have to change pod file ?

**Comment by ferbracaroto** [comment]
@ravinleague pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'

**Comment by umadhashna** [comment]
I am having several issues compiling on version Xcode 9.3 Beta 4.

Type 'Section' does not conform to protocol 'RangeReplaceableCollection'
