### ISSUE TITLE
Disable autocorrect and autocapitalization.

### ISSUE THREAD

**Issue by AndyIbanez** [xmartlabs/Eureka#1184]
How do I disable autocorrect and autocapitalization? I can't find a way to modify the underlying text field on TextRow and TextAreaRow. I also couldn't find any properties that were exposed for this.

**Comment by vadimue** [comment]
Hi, @AndyIbanez. You just simply can call cellSetup callback and initialize any UITextField properties.
``` swift
<<< TextRow() {
    $0.title = "TextRow"
    $0.placeholder = "Placeholder"
}
    .cellSetup { (cell, row) in
        cell.textField.autocorrectionType = .no
    }
```
