### ISSUE TITLE
Custom GenericMultipleSelectorRow details view controller

### ISSUE THREAD

**Issue by AlexZd** [xmartlabs/Eureka#1186]
Hi, trying to implement custom details view controller, but in latest version `generic` was replaced to `typealias` which I can't override.

In `GenericMultipleSelectorRow` class there is
```swift
public typealias PresentedController = MultipleSelectorViewController<GenericMultipleSelectorRow<T,Cell>>
```
and I can't override it from child, and always getting default `MultipleSelectorViewController`. In previous versions I was passing `VCType` which should be pushed and it was working fine.

Also, I tried to override block:
```swift
presentationMode = .show(controllerProvider: ControllerProvider.callback {
                return MultipleSelectorViewController<GenericMultipleSelectorRow<T,Cell>>()
        }, onDismiss: { vc in
            let _ = vc.navigationController?.popViewController(animated: true)
        })
```
which I also can't do, because of 
```swift
/// Defines how the view controller will be presented, pushed, etc.
    open var presentationMode: PresentationMode<PresentedController>?
```
and it has different type

so at the end, my row is like:
```swift
class _SCMultipleSelectorRow<T: Hashable, Cell: CellType>: GenericMultipleSelectorRow<T, Cell> where Cell: BaseCell, Cell: TypedCellType, Cell.Value == Set<T> {
    typealias PresentedController = SCMultipleSelectorViewController<GenericMultipleSelectorRow<T,Cell>>
    
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}
```
and it does not override push view controller.

I'm able to do duplicate `GenericMultipleSelectorRow` for my own project with my details VC and get it work, but I guess this wasn't idea.

Thank you

**Comment by mtnbarreto** [comment]
> I'm able to do duplicate GenericMultipleSelectorRow for my own project with my details VC and get it work, but I guess this wasn't idea. 

As you said, you will have to create your own GenericMultipleSelectorRow. I's the only way to conform to `PresenterRowType` and be able to set the presented view controller type.
