### ISSUE TITLE
onFormBuilded() callback?

### ISSUE THREAD

**Issue by EvsenevDev** [xmartlabs/Eureka#1188]
Do you have callback after form is builded? 
For example:  **onFormBuilded()**

I need to scroll form on this event. On **viewWillAppear** tableview is **empty** and i can't found a good place for call **tableView.scrollToRow**

I added in viewWillAppear **async** call and it's works fine. You know better place or callback for it? If no, i can add this callback and create Pull Request.

**Comment by m-revetria** [comment]
Hi @EvsenevDev,

Right now there is not a function called when a form is loaded. Eureka forms use UITableView's to render their rows and tables don't provide such notification / callback.

If you want to start your form view controller scrolled down to some row, you can try next code:

```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tableView.reloadData()
        if let indexPath = form.rowBy(tag: "some_tag")?.indexPath {
            tableView.scrollToRow(at: indexPath, at: .bottom, animated: animated)
        }
    }
```

It uses `viewWillAppear` but first, it forces the table to load all the rows. Then you will be able to scroll until the row position you want.

**Comment by mcousillas6** [comment]
Closing this due to lack of response.
