### ISSUE TITLE
Multisection insert delete but with custom cell

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#1190]
is it possible to insert multiple rows on button tap ,but the sender and receiver both cell should be custom 
Can you provide this feature 
I used this lib and now am unable to do this
if this feature is not possible ,i have to srapcout this lib from my project and i have to work a lot 
pelase do the favour :( 

Instead of default red and green button for edit delete with multivalued section can you provide support for Custom button on any side.

**Comment by mats-claassen** [comment]
The red and green buttons are provided by iOS and not implemented in Eureka. We won't support this but you could possibly achieve this with a custom cell by overriding `setEditing:animated:` (and maybe others)
