### ISSUE TITLE
You cannot just blow off supporting Swift 2.3 when some people adopted your framework.

### ISSUE THREAD

**Issue by tomcondon** [xmartlabs/Eureka#1196]
You cannot seriously expect adoptation of your framework when you remove the availability of a version that is for an official version of Swift that might get deprecated by Apple.  Some developers are stuck supporting older Xcode/iOS versions and for you to just remove the availability of a particular version/branch/tag of Eureka is totally irresponsible.

See: https://github.com/xmartlabs/Eureka/issues/687

**Comment by mtnbarreto** [comment]
In your case you should go for an older official Eureka release that supports swift 2.3. 

The reason why we do not maintain other than the latest official swift version is the time we can spend on the project. 
Eventually every app should be updated to a new swift version so there is no problem on that.

When beta swift version come out we create a branch that support it checking that everything works as expected. Once the new swift version gets out of beta testing we merge these change into master and release a new official Eureka version. 

I have the eureka swift 2.3 branch (locally) if you need it, but again you should target the official Eureka release and not the deprecated swift version branch. 

Does this approach work for you?

**Comment by tomcondon** [comment]
I fortunately found that I had checked out a repository branch that supports swift 2.3.

The point I was making is you casually suggest that everyone can just keep upgrading with Apple’s upgrades and that is not the case in real life.  There are many times when you use a multitude if 3rd party libraries/frameworks when one vendor of your libraries refuses to update in a timely manner, as is the case with an MDM vendor I am dealing with.  In that case one is stuck on an older version of swift until all the cocoa pods you use are available for a given version.

Maintaining a release branch or even a tag for a true swift 2.3 version in your repository is bot that hard and is common practice for many cocoa pod developers.

**Comment by kylebrowning** [comment]
Its pretty common in open source community to drop support of older versions. Things usually still work, but you cant expect the maintainers to spend their time.

I dont think anyone has to worry about adoption of this library.

Side note, by assuming its not that `hard` to maintain and release new features in older versions of code definitely means you haven't maintained an open source library before.

Furthermore, Xcode doesnt even support 2.3, and its `not that hard` for you to add a branch/release to your Cartfile or Podfile so frankly, you just sound entitled.

@mtnbarreto You should close this ticket.

**Comment by mtnbarreto** [comment]
@tomcondon 👍 . Causing troubles was never my intention.

**Comment by mradzinski** [comment]
@mtnbarreto Is there any chance to upload the 2.3 branch as it was? No need to maintain it nor make any changes to it, it's just that it seems there's still people working on legacy projects (me myself included). 

Last week I had to format my mac and now I can't compile my project any longer because it was targeting that branch in particular 😞

**Comment by marcosMorales** [comment]
can you upload the 2.3 branch @mtnbarreto @tomcondon? I need it too

**Comment by mtnbarreto** [comment]
done https://github.com/xmartlabs/Eureka/tree/swift2.3

**Comment by mtnbarreto** [comment]
@marcosMorales @mradzinski

**Comment by mtnbarreto** [comment]
@tomcondon
