### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by StayGoldenRobbyBoy** [xmartlabs/Eureka#1203]
xCode 8.3.3
Using  pod 'Eureka'

Hello,

I've just installed Eureka with cocoapods and was following the "Usage" section of the readme and ran into a "Type of expression is ambiguous without more context" error when trying to compile. My code looks like this (just copied from the readme):

```
import Eureka

class MyFormViewController: FormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        form +++ Section("Section1")
            <<< TextRow(){ row in
                row.title = "Text Row"
                row.placeholder = "Enter text here"
            }
            <<< PhoneRow(){
                $0.title = "Phone Row"
                $0.placeholder = "And numbers here"
            }
        +++ Section("Section2")
            <<< DateRow(){
                $0.title = "Date Row"
                $0.value = Date(timeIntervalSinceReferenceDate: 0)
            }
    }
}
```
The error happens here at 
`form +++ Section("Section1")`

I've tried cleaning my project and rebuilding, but no luck.

Issue #1020 is similar, but no solution was given.

Anyone know what do to?

**Comment by StayGoldenRobbyBoy** [comment]
Turns out I was having a name conflict with "FormViewController". After renaming my own class it worked.

**Comment by jtaytshungman** [comment]
So what is the actual solution? I'm facing a similar situation while using Eureka's API

**Comment by StayGoldenRobbyBoy** [comment]
In my case, I had an object called "Form" that I created which name conflicted with Eureka's "Form" object. I ended up renaming my object to "FormModel" which then solved the problem.

I think I could have solved it as well by specifying the what library the object "belongs" to. For example
`Eureka.form +++ Section("Section1")`
