### ISSUE TITLE
multiple multivaluedSection

### ISSUE THREAD

**Issue by noobDev009** [xmartlabs/Eureka#1205]
Hi, I have an issue when trying to 2 row inside the same multivaluedSection.
I tried something like this but I can only add the country....
```swift
+++ MultivaluedSection(multivaluedOptions: [.Insert]) { row in      
    row.multivaluedRowToInsertAt = { index in     
        return PushRow<String>("tag_\(index+1)") {  
            $0.title = "Country \(index+1)"
            $0.options = ["USA","France"...]
        }
    }
   row.multivaluedRowToInsertAt = { index in   
        return PhoneRow("tagg\(index+1)"){
            $0.title = "Phone number"
        }
    }
} 
```

Thanks

**Comment by m-revetria** [comment]
Hi @noobDev009, actually you are not adding 2 rows to the multivalued section, you are setting twice the same property which will be used to create new rows to be inserted into the section later. So the second assignation is overriding the first one.

If you want to have multiple countries and multiple phones in your form, you should have two different multivalued sections: one for the countries and another for the phone numbers:

```swift
+++ MultivaluedSection(multivaluedOptions: [.Insert]) { row in      
    row.multivaluedRowToInsertAt = { index in     
        return PushRow<String>("tag_\(index+1)") {  
            $0.title = "Country \(index+1)"
            $0.options = ["USA","France"...]
        }
    }
}
+++ MultivaluedSection(multivaluedOptions: [.Insert]) { row in      
   row.multivaluedRowToInsertAt = { index in   
        return PhoneRow("tagg\(index+1)"){
            $0.title = "Phone number"
        }
    }
} 
```

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
