### ISSUE TITLE
TextFloatLabelRow dynamic height??

### ISSUE THREAD

**Issue by cdreher** [xmartlabs/Eureka#1207]
Hello, I am using the TextFloatLabelRow in the CustomCells.swift file in eureka. I pulled the eureka repo from github correctly, have the latest version of Xcode running successfully on my laptop. I am wondering if there is a way to have a dynamic height on this type of row similar to that of a TextAreaRow. 

I want to have the floating label animation display on a TextAreaRow essentially. Is there a Eureka element similar to that already implemented? I have been trying to combine the code for the two and am not able to get it to work correctly.

Please advise.

**Comment by mtnbarreto** [comment]
Please add the issue in the proper repository:  https://github.com/EurekaCommunity/FloatLabelRow/issues .
