### ISSUE TITLE
Slow/Lag on bounce.

### ISSUE THREAD

**Issue by stoprocent** [xmartlabs/Eureka#121]
Hi guys

I didnt have enough time to profile it very well but from what I've seen there is a lag when scrolling fast and when you reach end of the table and scroll view bounces.

This is related to autolayout recalculating constraints for some rows. Any idea how can I cache rows/cells to speed it up a little bit ?

**Comment by stoprocent** [comment]
Reason for lagging is ```form[indexPath].updateCell()``` in ```willDisplayCell``` call.
There is some crazy number of constraint updates from ```willDisplayCell``` and also observers in ```_FieldCell```. Workaround for me which is way more responsive is this ...
```Swift
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        form[indexPath].updateCell()
        return super.tableView(tableView, cellForRowAtIndexPath: indexPath)
    }
    
    override func tableView(tableView: UITableView, willDisplayCell cell: UITableViewCell, forRowAtIndexPath indexPath: NSIndexPath) {
        // do nothing
    }
```
In general Eureka is great for speeding up creating Table View Forms but isnt there yet.
I promise I will try to help contributing when I will have a bit more time.

Thanks for the great tools!

**Comment by mtnbarreto** [comment]
We have already fixed this following your recommendation. Thanks for helping us improve Eureka!
