### ISSUE TITLE
Eureka cells gets disappeared on scrolling.

### ISSUE THREAD

**Issue by ankchdry** [xmartlabs/Eureka#1210]
Whenever I'm trying to enter anything in textfield, custom rows of Eureka gets disappeared(on scrolling). Please find the following photo for further reference.

![image uploaded from ios](https://user-images.githubusercontent.com/5436856/30061568-782df664-9265-11e7-93c0-87b83c7fc4ce.jpg)
![image uploaded from ios 1](https://user-images.githubusercontent.com/5436856/30061576-7d4a3018-9265-11e7-9e10-3653ae84d469.jpg)

**Comment by mtnbarreto** [comment]
Please, check that table view is properly connected with `FormViewController` outlet. 
If everything is ok, here may be something wrongly implemented in the custom row. I will need more info to help.

**Comment by ankchdry** [comment]
Actually it worked for me after i replaced the "keyboardwillshow" & "keyboardwillHide" with the IQKeyboard
