### ISSUE TITLE
How do we perform a condition after we click on a cell

### ISSUE THREAD

**Issue by r00tify** [xmartlabs/Eureka#1211]
I'm using the code below:

`            <<< ButtonRow("MyCell") {
                $0.title = $0.tag
                $0.presentationMode = .segueName(segueName: "ShowMyScreen", onDismiss: nil)
            }
`

Now, I need to perform a conditon on click and move only if it's true and show an alert if it's false. Then move if the user clicks on ok from the alert.
How do I do that?

**Comment by m-revetria** [comment]
Hi @r00tify, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

That being said, you can use `onCellSelection` callback to either perform such segue or show an alert:

```swift
<<< ButtonRow("MyCell") {
    $0.title = $0.tag
}.onCellSelection { [weak self] _, _ in
    if condition {
        self?.performSegue(withIdentifier: "ShowMyScreen", sender: self)
    } else {
        self?.showAlert()
    }
}
```

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
