### ISSUE TITLE
How to change PasswordRow placeholder font size?

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#1213]
Hi there, 

As per subject

**Comment by thecorsair** [comment]
same question

**Comment by thecorsair** [comment]
in cellupdate or defaultCellUpdate
cell.textField.font = UIFont.systemFont(ofSize: 15.0)

**Comment by m-revetria** [comment]
Hi @kohdesmond, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

From README:

```
* cellUpdate()

Called each time the cell appears on screen. You can change the appearance here using variables that may not be present on cellSetup().
```

And there is an example using SwitchRow, but the idea is the same:

```swift
let row = SwitchRow("SwitchRow") { row in      // initializer
    row.title = "The title"
}.onChange { row in
    row.title = (row.value ?? false) ? "The title expands when on" : "The title"
    row.updateCell()
}.cellSetup { cell, row in
    cell.backgroundColor = .lightGray
}.cellUpdate { cell, row in
    cell.textLabel?.font = .italicSystemFont(ofSize: 18.0)
}
```
