### ISSUE TITLE
Selectable list sections aren't selectable in Xcode 9/Swift 4

### ISSUE THREAD

**Issue by christianselig** [xmartlabs/Eureka#1218]
Using the latest build of Xcode 9/iOS 11 and Eureka's Xcode 9/Swift 4 branch.

Selectable list sections don't seem to work in the most recent Xcode 9 build. When you select the first option it works fine, but after selecting further ones they only update occasionally to being checked. (From what I can tell, when choosing a value the first time it'll work, but you can't choose the same value twice if you say, change your mind.)

If I create a simple "Single View App" project, and have this as `ViewController.swift` (code taken from the example in the README):

````swift
import UIKit
import Eureka

class ViewController: FormViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .green
        
        form +++ SelectableSection<ListCheckRow<String>>("Where do you live", selectionType: .singleSelection(enableDeselection: true))
        
        let continents = ["Africa", "Antarctica", "Asia", "Australia", "Europe", "North America", "South America"]
        for option in continents {
            form.last! <<< ListCheckRow<String>(option){ listRow in
                listRow.title = option
                listRow.selectableValue = option
                listRow.value = nil
            }
        }
    }
}
````

The behaviour can be seen in that code in Xcode 9. In Xcode 8 it works properly.

**Comment by AndrewBennet** [comment]
Is there a known workaround for this?

**Comment by ilyapuchka** [comment]
I discovered the same issue, it seams that for some reason section is being deallocated when `onCellSelection` is called on previously selected option (SelectableSection.swift:86).

**Comment by davros1970** [comment]
I didn't use any of the Xcode 9 Beta or GM. Was on Xcode 8.3.3 with Swift 3.2 until this morning. Got official Xcode 9 release from App Store, and subsequent Eureka build errors. Here's how I got Eureka to compile and seems to run fine for me this morning.

Podfile:
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift4'

- In Xcode 9, tap the 'Pods' project in the Project Navigator.
- Tap 'Eureka' in the 'Targets'
- Build Settings
- Search for 'Swift Lang'
- Change 'Swift Language Version' to 'Swift 4.0' (Everything else in my world is set up for Swift 3.2...)
- I nuked the contents of the DerivedData folder just to be sure. Not sure if this helps, but it can't hurt!
- Clean
- Build
- Joy!

**Comment by mtnbarreto** [comment]
Fix was already merged..
