### ISSUE TITLE
Xcode 9 GM | Issue on compilation 

### ISSUE THREAD

**Issue by RSickenberg** [xmartlabs/Eureka#1220]
Hi, here is the error on loading for me.
![image](https://user-images.githubusercontent.com/16922548/30376612-51fe4858-988d-11e7-9975-d78c91318210.png)
![image](https://user-images.githubusercontent.com/16922548/30376839-00f98548-988e-11e7-9aa9-5a6542f0fa93.png)

- Environment: Eureka, Xcode 9 and iOS 11.

**Comment by mtnbarreto** [comment]
I will take a look shortly! Which repository branch are you using?

**Comment by csimmonsbluebook** [comment]
@mtnbarreto I get the same error using the feature/Xcode9-Swift4 branch

**Comment by FredvanRijswijk** [comment]
same problem here... after update xcode GM version

**Comment by bluepi0j** [comment]
<img width="468" alt="screen shot 2017-09-14 at 12 20 55 am" src="https://user-images.githubusercontent.com/3591809/30412003-a68f68a2-98e2-11e7-8196-50d45420ce66.png">

**Comment by FredvanRijswijk** [comment]
Problem is solved if you use this updated file: https://raw.githubusercontent.com/xmartlabs/Eureka/142d80535b27b3634ac5a38514bde948b8ed42de/Source/Core/Section.swift

**Comment by dhmspector** [comment]
Is this in a tagged commit so that it can be tried using either cocoa pods or carthage?

**Comment by RSickenberg** [comment]
@mtnbarreto Master for now

**Comment by RSickenberg** [comment]
@FredvanRijswijk On your fix, I have the `Cannot call value of non-function type 'UITableView?'` on the 458 and 469 line

**Comment by AAverin** [comment]
I was wrong to update xcode, I am sorry and will not do this again =(
Gonna wait for the next release with fixes

**Comment by TCOA** [comment]
This ticket is closed - and the tickets pointing to it are closed........

So, where is the FIX????  (nothing suggested by anyone totally fixes this - they just cause other errors!)

**Comment by tuantmdev** [comment]
@TCOA After take some time to research, here the fix:

1. Update podfile using master branch `pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'`
2. Add this to the end of podfile to set Euraka using Swift 4 (In case your project not support Swift 4 yet)
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if  target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
3. Run `pod install`
4. Clear project and Rebuild

**Comment by TCOA** [comment]
Thanks, though now I get another issue......

Pre-downloading: `Eureka` from `https://github.com/xmartlabs/Eureka.git`
[!] Unable to satisfy the following requirements:

- `Eureka (from `https://github.com/xmartlabs/Eureka.git`)` required by `Podfile`
- `Eureka (~> 2.0.0-beta.1)` required by `ImageRow (1.0.0)`

Suggestions on that (I know it is not the same project/group, but it is still 'Eureka' to me...)?

**Comment by TCOA** [comment]
For others that are finding 'challenges' in getting this to work.....

Put this in your podfile
`pod 'Eureka', '~> 3.0'
pod 'ImageRow', '~> 2.0'
`
then 'pod install'

That will get the pod stuff installed.

HOWEVER, when trying to compile, we are back to the same error as before......

in Section.swift, line 201, I get 2 errors:

`Type 'Section' does not conform to protocol 'BidirectionalCollection'
'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent`

and on line 227, the 
`Type 'Section' does not conform to protocol 'BidirectionalCollection'`

So, still no 'joy'........

ANYONE HAVE A FIX THAT WORKS FOR EUREKA AND IMAGE ROW????

**Comment by EliteTechnicalCare** [comment]
Simply removing the non-updated rows and installing Eureka yields version 4.0 which works perfect. I had to drop the post office row and the image row, but at least it works. Frankly Eureka should have come out with the Swift 4/Xcode 9 version earlier to allow devs time to update the custom rows.

**Comment by RSickenberg** [comment]
Still no update with Xcode 9.0.1 🤕

**Comment by RSickenberg** [comment]
The fix of @tuantmdev worked for me !

**Comment by jlnbuiles** [comment]
@tuantmdev fix worked for me as well!
