### ISSUE TITLE
Xcode 9 GM | Build Fail

### ISSUE THREAD

**Issue by alexyu1989** [xmartlabs/Eureka#1222]
*/Pods/Eureka/Source/Core/Section.swift:202:1: Type 'Section' does not conform to protocol 'BidirectionalCollection'

*/Pods/Eureka/Source/Core/Section.swift:202:1: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent

*/Pods/Eureka/Source/Core/Section.swift:247:1: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

**Comment by xavierjurado** [comment]
Until the changes are merged into master and a new release is published you can point your Podfile to use the feature branch `feature/Xcode9-Swift3_2` to fix Xcode 9 compilation issues.

**Comment by AndrewBennet** [comment]
The Swift3_2 branch is also failing compilation for me, with the error:

> Pods/Eureka/Source/Core/Section.swift:56:29: 'dynamic' var '_rows' must also be '@objc'

This happens even when I have "Swift 3 @objc Inference" set to "ON".

**Comment by edasque** [comment]
Yes, I don't think there is a way to make it work today in Xcode 9, regardless of the branch you pull in, 3.2 or 4.0

**Comment by Laptopmini** [comment]
Duplicate Issue of #1220

**Comment by ravinleague** [comment]
Guys, is there a remedy to this ? its high time..

**Comment by AmmarMujeeb** [comment]
Xcode 9,  using branch "feature/Xcode9-Swift3_2" still getting issue as follows 
`'dynamic' var '_rows' must also be '@objc'

**Comment by AmmarMujeeb** [comment]
Below worked for me as described here [https://github.com/xmartlabs/Eureka/issues/1220]
After take some time to research, here's the fix:

Update podfile using master branch pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
Add this to the end of podfile to set Eureka using Swift 4 (In case your project not support Swift 4 yet)
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if  target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
Run pod install
Clear project and Rebuild

**Comment by xavisavvy** [comment]
@AmmarMujeeb your helper post_install didn't make it in the comment block.~

**Comment by furkanvijapura** [comment]
I have faced this issue in Section.swift file
error : 
1>> Type 'Section' does not conform to protocol 'BidirectionalCollection'
2>> 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent

**Comment by michaelmoulsdale** [comment]
Xcode has annoyingly updated to 3.3, and so this issue has resurrected even with the Xcode9-Swift3_2 branch. Are there any plans to release a 3.3 compatible version. The master branch still fails in multiple areas with 3.3
