### ISSUE TITLE
How i can use masked phone row?

### ISSUE THREAD

**Issue by krasnodar95** [xmartlabs/Eureka#1223]
How i can use masked phone row? Please give me a solution

**Comment by spydercapriani** [comment]
I used the cellSetup to just mark the textfield as secure entry to get this behavior.

```swift
.cellSetup{ cell, row in
       cell.textField.isSecureTextEntry = true
       cell.textField.delegate = self
}
```

**Comment by krasnodar95** [comment]
@spydercapriani I mean mask as +7 (999) 999-99-99 instead 79999999999

**Comment by spydercapriani** [comment]
@krasnodar95 Sorry for the delayed response. If you're still looking, this is sort of what I did for credit card numbers that can be applied to phone numbers as well.

first, use the .onChange method
`
.onChange {
    // pass the textfield to a separate function
    self.reformatAsExpiration($0.cell.textField)
}
`
Then within the reformatAsExpiration is where I put the logic to automatically insert a delimiter or format it as you'd like.

**Comment by Nurgunkalol** [comment]
@spydercapriani can u show full example, because phone mask its very common

**Comment by spydercapriani** [comment]
@Nurgunkalol So I recently implemented this with the help of [Phone Number Kit](https://github.com/marmelroy/PhoneNumberKit)

```swift
import PhoneNumberKit
import Eureka

private func buildForm() {
        <<< PhoneFloatLabelRow {
                $0.title = model.phoneConfig.title
                $0.add(ruleSet: model.phoneConfig.validationRules)
                $0.tag = model.phoneConfig.tag
                $0.onChange { [unowned self] row in
                    self.formatAsPhoneNumber(row.cell.textField)
                }
        }
}

func formatAsPhoneNumber(_ textField: UITextField) {
        guard let phoneNumber = textField.text else { return }
        
        textField.text = PartialFormatter().formatPartial(phoneNumber)
}
```

**Comment by Nurgunkalol** [comment]
@spydercapriani thx for help! but I have more masks like card number, document numbers and etc, do u know any kit thats I can use custom masks?

**Comment by spydercapriani** [comment]
@Nurgunkalol For credit cards, thus far I've mostly just used the [Credit Card Row](https://github.com/EurekaCommunity/CreditCardRow) available for Eureka. However, searching around I found [Cashien](https://github.com/prolificinteractive/Caishen) which seems promising for Credit Cards. However, as long as you realize that you can manipulate the textfield in the `.onChange` you can always add custom logic as needed.

**Comment by mats-claassen** [comment]
This is best implemented as a custom row like [CreditCardRow](https://github.com/EurekaCommunity/CreditCardRow) as mentioned above. Closing this as we won't implement this into Eureka core
