### ISSUE TITLE
HEEEELLLLLPPPP!!!!!! HOW TO USE?????

### ISSUE THREAD

**Issue by yerzhanserikbay** [xmartlabs/Eureka#1226]
public protocol SectionDelegate: class {
func rowsHaveBeenAdded(_ rows: [BaseRow], at: IndexSet)
func rowsHaveBeenRemoved(_ rows: [BaseRow], at: IndexSet)
func rowsHaveBeenReplaced(oldRows: [BaseRow], newRows: [BaseRow], at: IndexSet)
}

**Comment by mtnbarreto** [comment]
These methods are not indented to be overrated. If you do so, please make sure super implementation is invoked. 

Whenever a row is added, removed, replaced in a section these `FormViewController`'s methods are invoked. So you can extend `FormViewController` and do something useful in your code. **I do not recommend it.**
