### ISSUE TITLE
Action after multivaluedOptions.delete

### ISSUE THREAD

**Issue by yerzhanserikbay** [xmartlabs/Eureka#1227]

**Comment by mtnbarreto** [comment]
??

**Comment by yerzhanserikbay** [comment]
Hello @mtnbarreto! Thanks for your responding. I really need your help. I can't finish my project without this. 

I have problems with delete and reordering. Actually in index of the row. When I delete or reorder a row, his index don't change. 

![simulator screen shot sep 22 2017 6 59 21 am](https://user-images.githubusercontent.com/28862203/30722457-f6d186f6-9f63-11e7-8368-b68dc9da9750.png)

Thanks!
