### ISSUE TITLE
Xcode 9 GM | Build Failing *NEED FAST SUPPORT*

### ISSUE THREAD

**Issue by mattfrias** [xmartlabs/Eureka#1228]
![error](https://user-images.githubusercontent.com/22482659/30610841-817ef950-9d4d-11e7-8ff4-4cb615447dee.jpeg)

I need Eureka working because I have a very critical bug that needs to be fixed and uploaded to the App Store as an update. I also did not know that updating to Xcode 9 would break anything because I am using the Xcode 9 branch.

**Comment by eliburke** [comment]
I've been struggling for two days with the xcode9 upgrade. My suggestion, if you are able, is to revert to xcode 8.3.3 using xcode-select to fix your bug. Then, keep a separate copy of your code forked for xcode 8 while you get everything working /w xcode 9

Some gotchas: 
* make sure you launch xcode 8. xcode-select only changes the compiler for command line tools  
* don't put any spaces in the path "/Application/Xcode8.app/Contents/Developer/" 😜
* if you use carthage, nuke the derived data directory between builds: `rm -rf ~/Library/Caches/org.carthage.CarthageKit/DerivedData/`. CocoaPods may have something similar
* clean the project AND the build folder (hold down option when you click the Product menu)

**Comment by mattfrias** [comment]
@eliburke I tried to downgrade back to 8.3.3 but I can't so I'm really depending on the repo owner to fix it quickly so I can get this update out. But thank you for the help.

**Comment by Laptopmini** [comment]
Duplicate Issue of #1220

**Comment by mattfrias** [comment]
Yes, I know but that issue does not have a solution. Hence why I have made a duplicate issue.

**Comment by Laptopmini** [comment]
How does that seem like a valid reason to you? Should you flood the issue section with duplicate threads until you get your answer by that logic?

You could've at least bothered to participate in it or voice your opinion.

**Comment by mattfrias** [comment]
Why would I "voice my opinion" in someone else's thread (which is 6 days old), when I can just make my own post. If you are not helping in the issue, don't post a comment, so you are completely irrelevant to the topic being addressed. I don't have time for ignorant Github users who feel like they need to comment everything that comes to their mind. I have a critical bug that needs to be addressed that I cannot because Apple likes to do auto-updates while I'm not at my computer, that I cannot control if I didn't know was happening.

**Comment by RSickenberg** [comment]
@mattfrias Joined github on 27 September 2016 and @Laptopmini on 4 Mai 2014, who is ignorant github users 🤦‍♂️ .

**Comment by davros1970** [comment]
I didn't use any of the Xcode 9 Beta or GM. Was on Xcode 8.3.3 with Swift 3.2 until this morning. Got official Xcode 9 release from App Store, and subsequent Eureka build errors. Here's how I got Eureka to compile and seems to run fine for me this morning.

Podfile:
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift4'

In Xcode 9, tap the 'Pods' project in the Project Navigator.
Tap 'Eureka' in the 'Targets'
Build Settings
Search for 'Swift Lang'
Change 'Swift Language Version' to 'Swift 4.0' (Everything else in my world is set up for Swift 3.2...)
I nuked the contents of the DerivedData folder just to be sure. Not sure if this helps, but it can't hurt!
Clean
Build
Joy!

**Comment by edasque** [comment]
@davros1970 steps worked for me.

**Comment by barteljan** [comment]
try the following in your podfile:

```
post_install do |installer|
        installer.pods_project.targets.each do |target|

            if  target.name == "Eureka"
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
```

**Comment by mattfrias** [comment]
@barteljan Thank you that worked. 😄👍

**Comment by tuantmdev** [comment]
@barteljan Not working for me

![screen shot 2017-09-26 at 09 52 05](https://user-images.githubusercontent.com/3973450/30840304-b20f99a0-a2a0-11e7-8db8-64fafd00347a.png)

**Comment by barteljan** [comment]
@tuantmdev Which eureka branch are you using ?

**Comment by tuantmdev** [comment]
@barteljan Thanks, it works for me now after using master branch
