### ISSUE TITLE
Custom Button at the end of the Form

### ISSUE THREAD

**Issue by quangdng** [xmartlabs/Eureka#123]
Hi Authors,

Thanks for creating a superb control for Swift. I never thought creating form in iOS could be this easy. However, there is a small issue for me. 

I've come to the situation that I want to add a Submit Button with my very own logic at the end of the created form. I understand that I can simply add another Section with Button Row, however, I can't style the button as I may want to (get rid of the separator border etc.). Therefore, please guide me how I can achieve this.

Thanks for your time and support.

Best Regards,

Justin.

**Comment by mtnbarreto** [comment]
Build-in rows (rows provided by default) don't cover this particular scenario. 

Anyway, you can easily create a custom row and make it looks like as you want. Take a look at [Extensibility](https://github.com/xmartlabs/Eureka#extensibility) readme section that explains how to implement custom rows. 

Also take a look at issues marked with [customRow label](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22custom+row%22+)  , they may be useful.

Regards
