### ISSUE TITLE
no member dataProvider

### ISSUE THREAD

**Issue by allaire** [xmartlabs/Eureka#1232]
Hi, I tried to use the Swift-4 branch (Swift_32 branch works), and I'm getting the following error in one of my custom cell/row :

![image 2017-09-21 at 09 30 02-1](https://user-images.githubusercontent.com/304461/30698515-362e7e62-9eb0-11e7-839d-b829123df95c.png)

I tried to search previous issues, but I can't find anything pointing to that code change.

Thanks!

**Comment by yannickl** [comment]
I didn't find documentation but by following the [MultipleSelectorViewController.swift](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Controllers/MultipleSelectorViewController.swift) it helped me for the migration.

**Comment by allaire** [comment]
@yannickl Thanks for the link.

I'm also wondering why I'm getting this error in the swift4 branch, but not on the swift32 one. Shouldn't they be equivalent, with just the syntax fixes needed for each version?

**Comment by allaire** [comment]
@mtnbarreto I'm still unsure on how to update, any hints?

Thanks!

**Comment by allaire** [comment]
For anyone wondering, found this gist which was really helpful! https://gist.github.com/gotelgest/cf309f6e2095ff22a20b09ba5c95be36
