### ISSUE TITLE
What's the timeline for the next release that supports Xcode 9 ?

### ISSUE THREAD

**Issue by zhuhuihuihui** [xmartlabs/Eureka#1233]
Our pod depends on Eurake, and pod dependencies do not support specifying branches.

**Comment by EliteTechnicalCare** [comment]
This is a serious issue. We use over 30 different pods, Xcode 9 beta has been out for almost 4 months and the release candidate for nearly a month. Absolutely no reason why this is still lagging behind.

**Comment by barteljan** [comment]
Put the following in your Podfile:

```
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
```

**Comment by zhuhuihuihui** [comment]
@barteljan podspec  does not support that

**Comment by davros1970** [comment]
@zhuhuihuihui I know its not ideal, but the consumers of your pod/framework will need to add a line item for Eureka like @barteljan has proposed in their app's Podfile. I've had to do this in the past to solve a similar issue with a different pod. Its ugly, but does work.

**Comment by EliteTechnicalCare** [comment]
@davros1970 
I manually dragged the files into my projects, however this still doesn't answer the question: "What is the timeline" Xcode 9 has been officially released by apple via the App Store and stopped offering the download at developer.apple.com

**Comment by 1432961067** [comment]
@EliteTechnicalCare I want to know that It's is work now?

**Comment by zhuhuihuihui** [comment]
Just think this of my conversation with @dnkoutso from CocoaPods might be helpful for people here,  https://github.com/CocoaPods/CocoaPods/issues/7055

**Comment by dnkoutso** [comment]
1.4.0.beta.1 of cocoapods was released yesterday including an update to Xcodeproj. Keep in mind this is still a beta and there might be some issues remaining.

**Comment by spydercapriani** [comment]
I saw that 4.0.0 release has been created for Eureka but I can only assume that this hasn't yet been pushed to the cocoapods master repo as `pod update Eureka` will not pull in 4.0.0 release.

**Comment by mtnbarreto** [comment]
It was already pushed to cocoapods. Check it out https://cocoapods.org/pods/Eureka
