### ISSUE TITLE
[Bug] singleSelection form allowing multipleSelection in a specific situation

### ISSUE THREAD

**Issue by bernaferrari** [xmartlabs/Eureka#1235]
On Xcode 8 / Swift 3 with Eureka 3.1.0, I am having the following bug with the following code:

![screen shot 2017-09-22 at 07 52 09](https://user-images.githubusercontent.com/351125/30741495-59432c3e-9f6b-11e7-843f-55951b5bc5c7.png)

```
  self.form +++ SelectableSection<ListCheckRow<String>>("c", selectionType: .singleSelection(enableDeselection: false))
        
        self.form.last! <<< ListCheckRow<String>("a") { listRow in
            listRow.title = "No!"
            listRow.selectableValue = "No!"
            listRow.value = nil
        }
        
        self.form.last! <<< ListCheckRow<String>("b") { listRow in
            listRow.title = "Yes!"
            listRow.selectableValue = "Yes!"
            listRow.value = nil
        }
        
        self.form.last! <<< TextRow() { row in
            row.title = "    Write:"
            row.placeholder = "here"
            row.tag = "write"
            row.onChange({a in
                if (self.form.rowBy(tag: "b")?.baseValue == nil){
                    let a = row.value
                    
                    self.form.rowBy(tag: "b")?.didSelect()
                    
                    row.value = a
                    row.updateCell()
                }
            })
        }
```

How to reproduce:
- Type something in the 'write box'. The 'yes!' should select.
-  Tap on 'no!', and both will be selected.

If you tap again on 'no!', it will remove the 'yes!' selection (which should've been doing since the first time).

**Comment by m-revetria** [comment]
Hi @bernaferrari, I've tried the code you provided and it's working fine using latest Eureka code (from master branch).

Could you please check if latest Eureka's version is working for you?

**Comment by bernaferrari** [comment]
Nice to see Eureka is alive and well again. Yeah, looks like someone fixed it. Thanks!
