### ISSUE TITLE
[ImageRow Swift 4 , Euraka 3.1.0 ] SelectorRow not working with community custom ImageRow 

### ISSUE THREAD

**Issue by StriderHND** [xmartlabs/Eureka#1236]
Hello Guys

With all the changes to the rows for the newest updates for the eureka forms for swift 4 some of the community rows are been affected about this for example : 
ImageRow(https://github.com/EurekaCommunity/ImageRow)

I'm getting this kind of error "Generic type 'SelectorRow' specialized with too many type parameters (got 2, but expected 1)" and a lot of other be consequence of this.

![screen shot 2017-09-22 at 11 43 48 am](https://user-images.githubusercontent.com/430328/30757526-40262d20-9f8c-11e7-9c6a-704b063bfb5f.png)

This the line of the error, in the class definition:
`open class _ImageRow<VCType: TypedRowControllerType, Cell: CellType>: SelectorRow<Cell, VCType>, ImageRowProtocol where VCType: UIImagePickerController, VCType.RowValue == UIImage, Cell: BaseCell, Cell: TypedCellType, Cell.Value == UIImage {`

I look to the SelectorRow definition and I found changes to the class
`open class SelectorRow<Cell: CellType>: OptionsRow<Cell>, PresenterRowType where Cell: BaseCell `

I made some changes to the code but still I have issues with how do the presentation mode.

![screen shot 2017-09-22 at 11 51 39 am](https://user-images.githubusercontent.com/430328/30757613-891002ea-9f8c-11e7-87c2-e9114641d1d7.png)

would be great some help to update this and update the community repo.

Thanks for the help.

Erick

**Comment by CaptainYukinoshitaHachiman** [comment]
Here the same problem

**Comment by mtnbarreto** [comment]
Last ImageRow and Eureka versions no longer have this issue.
