### ISSUE TITLE
How to create a PickerRow with multiple components

### ISSUE THREAD

**Issue by martinregas** [xmartlabs/Eureka#1237]
It is posible create a PickerRow or PickerInlineRow with multiple components?

**Comment by zenghaojim33** [comment]
Is there any solution now?

**Comment by mats-claassen** [comment]
This has not been implemented. You can do it by creating a custom row subclassing from PickerCell for example. Have a look at the [readme's custom row section](https://github.com/xmartlabs/Eureka#custom-rows)
