### ISSUE TITLE
Can not work with Xcode 9

### ISSUE THREAD

**Issue by LinhTN-AltPlus** [xmartlabs/Eureka#1240]
I'm trying to use Eureka and got issue while using Eureka 3.1.0 in Xcode 9.
Xcode show these errors:
![screen shot 2017-09-25 at 10 17 25 am](https://user-images.githubusercontent.com/25579305/30791201-13b02146-a1db-11e7-95c3-18b4048b9862.png)

**Comment by mludi** [comment]
There is an feature/Xcode9-Swift4 branch, try to use that instead

**Comment by spydercapriani** [comment]
When will the feature/Xcode9-Swift4 branch be turned into a release? Pods which require Eureka as a dependency cannot push out new versions as `pod repo push` / `pod lib lint` doesn't allow for specifying branches during validation (that I have found).

**Comment by rlam3** [comment]
+1

**Comment by rlam3** [comment]
@LinhTN-AltPlus How did you resolve this? Thanks!

**Comment by LinhTN-AltPlus** [comment]
@rlam3  It's OK.

**Comment by adrianodiasx93** [comment]
@LinhTN-AltPlus so even with the warning it works? I haven't noticed some bug related to it, but the warning annoys/worries me since  I am implementing a custom `SelectorRow` in my application. 

`guard let rowVC = segue.destination as? PresenterRow else { return }`

> Cast from 'UIViewController' to unrelated type 'SelectorViewController<SelectorRow<Cell>>' always fails

**Comment by rlam3** [comment]
@adrianodiasx93 doesn't work for me still... I think they may have done some work around @LinhTN-AltPlus
