### ISSUE TITLE
Hiding using a function condition not working

### ISSUE THREAD

**Issue by lukwin91** [xmartlabs/Eureka#1242]
For Eureka v3.0.0 hiding/showing rows not working.

Example of use is in [tutorial](https://github.com/xmartlabs/Eureka#hiding-using-a-function-condition)

Eureka is downloaded from CocoaPods: `pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'`
using xCode 9.0 and iOS 11

**Comment by matteozajac** [comment]
Maybe you override viewWillAppear without calling super.

**Comment by lukwin91** [comment]
Yes. That was a problem.
`super.viewWillAppear(animated)`
fixes it.
