### ISSUE TITLE
Please add Swift 4.* support.

### ISSUE THREAD

**Issue by fahad-larasoft** [xmartlabs/Eureka#1243]
I am using XCode Version 9.0 and iOS Version 11

Please find errors in attached screenshots.
<img width="274" alt="screen shot 2017-09-25 at 7 21 24 pm" src="https://user-images.githubusercontent.com/7126820/30813524-21d32588-a227-11e7-9afe-2d04a3d8d7df.png">
<img width="1165" alt="screen shot 2017-09-25 at 7 21 49 pm" src="https://user-images.githubusercontent.com/7126820/30813527-2253ab86-a227-11e7-92b4-4e75d2eb835e.png">
<img width="1168" alt="screen shot 2017-09-25 at 7 22 01 pm" src="https://user-images.githubusercontent.com/7126820/30813526-222703f6-a227-11e7-8da8-8d8cda16b785.png">
<img width="1167" alt="screen shot 2017-09-25 at 7 22 09 pm" src="https://user-images.githubusercontent.com/7126820/30813525-21daae20-a227-11e7-8f60-0b4b314454cc.png">

**Comment by lognaturel** [comment]
https://github.com/xmartlabs/Eureka/issues/1240
https://github.com/xmartlabs/Eureka/issues/1182
https://github.com/xmartlabs/Eureka/issues/1143 
and many other issues address Swift 4 support.

Have you tried using the https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift4 branch?

You can specify a branch using cocoapods following instructions at https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by barteljan** [comment]
@mrnbarreto is there a roadmap for the next stable version ? Can we support you with a specific pull request to achieve a Xcode 9 compatible version ?

**Comment by danielsimons1** [comment]
For feature branch Xcode9-Swift3_2, I get a compile error "'dynamic' var '_rows' must also be '@objc'" at line 56 of Section.swift
![screen shot 2017-09-29 at 12 29 19 pm](https://user-images.githubusercontent.com/931458/31028031-11eebbf8-a512-11e7-86b6-087e12f89334.png)

**Comment by fahad-larasoft** [comment]
@lognaturel I am still getting some Swift Compiler Error as you can see in attached screenshot:

I am using XCode 9.0, Swift 4


<img width="318" alt="screen shot 2017-10-02 at 10 26 58 am" src="https://user-images.githubusercontent.com/7126820/31065107-4706ebca-a75c-11e7-8ba4-c6cadf36cd4a.png">
<img width="1041" alt="screen shot 2017-10-02 at 10 27 07 am" src="https://user-images.githubusercontent.com/7126820/31065108-473d7ac8-a75c-11e7-9a00-aa16eb28dfba.png">

**Comment by mtnbarreto** [comment]
@barteljan Version 4.0.0 is already out and supports swift 4.

**Comment by mtnbarreto** [comment]
@danielsimons1 we no longer need swift 3.2 branch. You should be able to use use latest Eureka release which is written in swift 4 from swift 3.2 ios project.
