### ISSUE TITLE
How to use Eureka for swift 4 with ImageRow?

### ISSUE THREAD

**Issue by moonvader** [xmartlabs/Eureka#1250]
```
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :commit => 'a238bbd'
  pod 'ImageRow', :git => 'https://github.com/EurekaCommunity/ImageRow.git', :commit => '1456406'
```

> [!] Unable to satisfy the following requirements:
> 
> - `Eureka (from `https://github.com/xmartlabs/Eureka.git`, commit `a238bbd`)` required by `Podfile`
> - `Eureka (= 3.1.0)` required by `Podfile.lock`
> - `Eureka (= 3.0)` required by `ImageRow (2.0.0)`

**Comment by hpopp** [comment]
Currently a PR open at https://github.com/EurekaCommunity/ImageRow/pull/21

**Comment by mtnbarreto** [comment]
Just released a compatible ImageRow version with Eureka ~> 4.0. https://github.com/EurekaCommunity/ImageRow/releases/tag/3.0.0
