### ISSUE TITLE
ImageView and textfields in a single line

### ISSUE THREAD

**Issue by martinregas** [xmartlabs/Eureka#1251]
I want my form to have a ImageView on the left side, and textfields or labels on the right side, as shown in the picture.  Any ideas of what I need to do to accomplish this? 

<img width="444" alt="screen shot 2017-09-26 at 4 10 20 pm" src="https://user-images.githubusercontent.com/4209811/30879274-57c09532-a2d5-11e7-99b7-8e8197f49907.png">

**Comment by KevinGong2013** [comment]
Implement your custom row&cell.

**Comment by mtnbarreto** [comment]
You should go for a custom row. After implementing it it would be great to share it by adding the custom cell to https://github.com/EurekaCommunity
