### ISSUE TITLE
Incorrect cell heights and overlapping

### ISSUE THREAD

**Issue by classified** [xmartlabs/Eureka#1255]
i am currently using master branch with swift 4 version for ios 11 and i'm getting this bug. Dynamic cell heights are not working and it's getting overlapped. does anyone knows how to fix it?

![cc8384b2-9952-4a6a-a8cb-1b8fe75a160b](https://user-images.githubusercontent.com/1496524/31003247-4f3611f6-a50c-11e7-9006-55e9c7930fab.jpg)
![23b4b9a0-65c3-4ea2-a1cf-9cf709bacb2f](https://user-images.githubusercontent.com/1496524/31003259-628f08f2-a50c-11e7-9343-d38044389a7d.jpg)

**Comment by Kishimotovn** [comment]
Just add this your view controller:
```
viewDidLoad () {
    ...
    self.tableView.rowHeight = UITableViewAutomaticDimension
    self.tableView.estimatedRowHeight = 100.0
}
```
