### ISSUE TITLE
Complier Error?

### ISSUE THREAD

**Issue by rlam3** [xmartlabs/Eureka#1258]
Before submitting issues ...

<img width="389" alt="screen shot 2017-09-29 at 4 24 21 pm" src="https://user-images.githubusercontent.com/1154044/31036638-c76a62aa-a532-11e7-8b24-27d05391a983.png">

Tried re installing with cocoapods but to no avail.

Eureka 4.0.0
Xcode 9
Swift 4

Would love to know if this is a problem that I can fix or is there some incompatabilities with cocoapods? Thanks!

**Comment by mtnbarreto** [comment]
It seems you either are not using latest eureka version or Xcode 9. Could you check please?

**Comment by rlam3** [comment]
I'm using Xcode 9 as stated in the comments with Eureka 4 in cocoapods. Thanks! Any ideas on how to fix this issue?

**Comment by AlbertTong** [comment]
@mtnbarreto I'm also seeing the same issue using cocoapods, Eureka 4.0.0, Xcode 9.0. If you download the source code zip from the 4.0.0 release and search some of the lines that error out, it clearly has the old code. Looks like the fixes from #1266 and #1261 somehow didn't get merged in to master? It looks like it was merged to feature/Xcode9-Swift4 branch though.

**Comment by AAverin** [comment]
Any update or workaround so far?

**Comment by AlbertTong** [comment]
@AAverin for now I just made the changes I saw in diff #1261 manually in regards to the rawValue parameter labels. Not many lines to fix, but not sure on your other lines in your screenshot. Since I'm using cocoapods, there is a risk that those changes get wiped out on next pod update but I think that'll be a while for my case.

**Comment by AAverin** [comment]
What seem to have worked for me now.
1. point Eureka to master `pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'master'`
2. Got to Pods in Xcode, find Eureka and force it be built with Swift 4.0

**Comment by mtnbarreto** [comment]
Seems there is an issue regarding the swift version that cocoapods use... https://github.com/xmartlabs/Eureka/blob/feature/Xcode9-Swift4/.swift-version
It should be 4.0. 
Sorry for any inconvenience caused.  I'm gonna release a new version in a moment.

**Comment by mtnbarreto** [comment]
same as #1266
