### ISSUE TITLE
xcode9.0/9.1 compiler warnings

### ISSUE THREAD

**Issue by jaz-ah** [xmartlabs/Eureka#1259]
Eureka 4.0
Xcode9.0/9.1

Hit these warnings on Xcode9.0 + 9.1 (the characters deprecations are on 9.1 and are easy to fix, just remove the .characters, the others are from 9.0 and 9.1):

<img width="400" alt="screen shot 2017-09-29 at 2 41 59 pm" src="https://user-images.githubusercontent.com/13263369/31037198-a4445b86-a524-11e7-8327-bf79d0165d00.png">

**Comment by mtnbarreto** [comment]
The warning seems to be swift 4 compiler issues. Please upvote this swift issie so it get fixed.. https://bugs.swift.org/browse/SR-5252

**Comment by mtnbarreto** [comment]
ios 11.1 is under beta version and these warnings won't be fixed on master branch yet. 
I just created https://github.com/xmartlabs/Eureka/tree/ios/11.1 to add ios 11.1 fixes.

**Comment by jaz-ah** [comment]
@mtnbarreto just a note that the "cast from" warnings are from xcode9/ios11.0, only the characters one are from ios11.1/xcode9.1 and the fixes are compatible with xcode9, pretty easy ones to just remove ".characters"

**Comment by jaz-ah** [comment]
just a note that the characters warnings from xcode9.1/ios11.1 when fixed (by removing the word characters) is compatible w/ xcode9/ios10... could be fixed in master and retain compatibility.

**Comment by mtnbarreto** [comment]
@jaz-ah Could you make a pull request removing characters warning?

**Comment by jaz-ah** [comment]
@mtnbarreto no problem - done: https://github.com/xmartlabs/Eureka/pull/1265

**Comment by martheli** [comment]
Getting the master branch by using:  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git' still contains the `Cast from 'UIViewController' to unrelated type 'MultipleSelectorViewController<GenericMultipleSelectorRow<T, Cell>>' always fails` warnings

**Comment by igor9silva** [comment]
It's a compiler bug, as @mtnbarreto stated.

Please everyone vote and comment on this https://bugs.swift.org/browse/SR-5252 so Apple can know many people is being affected by this bug.

**Comment by AleksandarPetrov** [comment]
You can silence the warning by adding **`as Any`**. Example:
`if let sec = section as Any as? CountrySelectableSection<Row> {  ... `
