### ISSUE TITLE
User leaves cell event?

### ISSUE THREAD

**Issue by AAverin** [xmartlabs/Eureka#1262]
Is there an event for when user finished typing and presses "Done", or clicks away from the cell?
I need to trigger complex async validation and if it passes – add new entry to the section.
But validation should happen only when full text is entered.

**Comment by AAverin** [comment]
Exploring other ways of building this functionality (MultivalueSection Insert rows), but would be still great to know if some kind of `onBlur` event is available in general

**Comment by mtnbarreto** [comment]
https://github.com/xmartlabs/Eureka#oncellunhighlight-doesnt-get-called-unless-oncellhighlight-is-also-defined does it. 
Let me know if it works in your scenario...

**Comment by mcousillas6** [comment]
Closing this issue due to lack of response.
