### ISSUE TITLE
Inserting rows to section doesn't work

### ISSUE THREAD

**Issue by AAverin** [xmartlabs/Eureka#1263]
Before submitting issues ...

- Environment: Eureka `feature/Xcode9-Swift3_2`, Xcode 9 and iOS version 9

I am following Example/Validations to show validation error as a LabelRow in my form.
When validation fails LabelRow is properly added, I can see it when I debug for structure, but visually new row is never shown on the screen.

At the same time, everything seems to work fine in the example that I have just fetched from Github and run – `master` branch.

I suspect either something is broken in the Swift3_2 branch or I'm just missing something?

Code sample:
```
+++ Section("List Details")
            <<< NameRow() {
                    $0.title = "Name"
                    $0.add(rule: RuleRequired(msg: "Please provide list name"))
                    $0.add(rule: RuleMinLength(minLength: 1, msg: "Please provide list name"))
                    $0.value = localMeta.title
                    $0.validationOptions = .validatesAlways
                }.cellUpdate { cell, row in
                    if !row.isValid {
                        cell.titleLabel?.textColor = .red
                    }
                }
                .onRowValidationChanged { cell, row in
                    let rowIndex = row.indexPath!.row
                    while row.section!.count > rowIndex + 1 && row.section?[rowIndex  + 1] is LabelRow {
                        row.section?.remove(at: rowIndex + 1)
                    }
                    if !row.isValid {
                        for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
                            let labelRow = LabelRow() {
                                $0.title = validationMsg
                                $0.cell.height = { 30 }
                                $0.cell.contentView.backgroundColor = .red
                                $0.cell.textLabel?.textColor = .white
                                $0.cell.textLabel?.font = UIFont.boldSystemFont(ofSize: 13)
                                $0.cell.textLabel?.textAlignment = .right
                            }
                            row.section?.insert(labelRow, at: row.indexPath!.row + index + 1)
                        }
                    }
                }
```

**Comment by AAverin** [comment]
I have added another NameRow below, just to see if something will be inserted in the middle
<img width="252" alt="screen shot 2017-10-02 at 13 15 10" src="https://user-images.githubusercontent.com/1481332/31075040-d2b1efb4-a773-11e7-8a52-93973e004961.png">

**Comment by mtnbarreto** [comment]
Please use the last eureka release. Let me know if it works..

**Comment by AAverin** [comment]
Blocked by #1266  at the moment

**Comment by AAverin** [comment]
Same on latest version. Row is there, but doesn't show up.
Will try again with example and look if I missed anything

**Comment by AAverin** [comment]
Additionally, when using MultivalueSection with "Add", clicking on the + icon results in 
```
'NSRangeException', reason: '-[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (1) beyond bounds (1) for section (1).'
```

**Comment by AAverin** [comment]
Opened a stackoverflow ticket for 2nd problem: https://stackoverflow.com/questions/46623094/eureka-multivaluedsection-add-nsrangeexception

**Comment by AAverin** [comment]
Figured this out, so both issues are solved.
My custom controller was overriding `viewWillAppear()`, but I forgot to call `super.viewWillAppear()`
If I missed this important in the docs – maybe makes sense to add it there
