### ISSUE TITLE
How to change title row position

### ISSUE THREAD

**Issue by martinregas** [xmartlabs/Eureka#1264]
It's posible to change the row title position using Eureka framework?. Row title's default position is at center of the textfield, and I need set it at top of textfield

![tito](https://user-images.githubusercontent.com/4209811/31093852-730af54a-a789-11e7-87a3-f4d3895e90e4.jpg)

Thanks!

**Comment by guillianbalisi** [comment]
Set the section's title. Before it is like this:

``` 
+++ Section()
<<< TextRow() {
     $0.title = "Label"
}
```

What you want is
``` 
+++ Section("Label")
<<< TextRow()
```

**Comment by martinregas** [comment]
This is what I need, but it's made in a UITableView without Eureka, is it possible to achieve this using Eureka?

![Uploading Tf4zUFA.png…]()

**Comment by guillianbalisi** [comment]
Maybe this custom row will be useful:

https://github.com/EurekaCommunity/FloatLabelRow

**Comment by m-revetria** [comment]
Hi @martinregas, yes off course you can achieve that design using eureka!
If the `FloatLabelRow` previously suggested does not fit your needs, you probably have to make your custom row with the desired design.

If you go for making your own custom row, next blog may help you https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/

**Comment by az-oolloow** [comment]
@guillianbalisi you end up doing this? any tips?
