### ISSUE TITLE
ImageRow Issue!

### ISSUE THREAD

**Issue by ehirebrandon** [xmartlabs/Eureka#1268]
I am using Eureka in Xcode GM & 9.1 and I'm having a problem as such: 
I currently having a TableViewController inside a NavigationController that pushes a EurekaForm on to it. Once EurekaForm is on the NavigationStack(NavigationController) I have an ImageRow that can be used to set photos taken or from the Library. Now my navigation Controller has a back button (<) and a Done Button (Done), and pressing either will dismiss the EurekaForm which is expected. However, when I choose an image and it is chosen and set, it will set that row with the image and dismiss the EurekaForm. A workaround would to present the Eureka Form versus push it on the Navigation controller, but that is not the behavior or style I want. Can someone assist? 

Thank you so much!

**Comment by ehirebrandon** [comment]
Console error: presenting view controllers on detached view controllers is discouraged

**Comment by mtnbarreto** [comment]
This should be fixed in newest eureka versions.
