### ISSUE TITLE
How to implement PushRow

### ISSUE THREAD

**Issue by tapizquent** [xmartlabs/Eureka#1270]
I might not have much experience with Eureka yet but I’ve been going over the information on how to implement a PushRow and there’s not much info on it.
I’ve added the PushRow to my Form and it displays but when I tap on it (expecting for it to do something) nothing happens.
Should PushRow automatically create and open a new view controller with the option values I have set ? Is there anything I’m missing ?

**Comment by m-revetria** [comment]
Hi @tapizquent, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

You can use the example app provided as guide, please check [ViewController.swift#L249](https://github.com/xmartlabs/Eureka/blob/master/Example/Example/ViewController.swift#L249) to see how `PushRow` is used.

**Note**: be sure to have your form view controller embebed within a `UINavigationController`
