### ISSUE TITLE
Setting insert and delete animations to .none still has animation

### ISSUE THREAD

**Issue by cerupcat** [xmartlabs/Eureka#1271]
I'd like to refresh the tableView without any animation. Overriding insert/deleteAnimation for sections and rows and returning `.none` as the type still has an animation. Is there any way insert/delete sections/rows without any animation?

**Comment by mtnbarreto** [comment]
these is the default iOS behavior for `.none`. try adding insertions deletions etc inside  https://developer.apple.com/documentation/uikit/uiview/1622484-performwithoutanimation block. I have never tried but it could work.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response

**Comment by txaiwieser** [comment]
I'm just here to state that using `performwithoutanimation` does work! :)
