### ISSUE TITLE
How to save row values to Firebase? 

### ISSUE THREAD

**Issue by jtaytshungman** [xmartlabs/Eureka#1272]
Hi there, I literally picked up Swift programming 9 weeks ago so I am still quite new to all these. I really like Eureka's form, but I want to know how am I able to save my user's answers to Firebase?

**Comment by CeceXX** [comment]
You need to get the data values (dictionary) and then save those to Firebase using their APIs. `form.values()`

**Comment by m-revetria** [comment]
Thanks @CeceXX for the response!

I'm closing this due to lack of response
