### ISSUE TITLE
Rating cell

### ISSUE THREAD

**Issue by Tomas1405** [xmartlabs/Eureka#1275]
Is possible with this pod create custom row? I need cell for rating (some kind of 5 stars view)

**Comment by elgartoinf** [comment]
yes, its posible, i use this pod https://github.com/evgenyneu/Cosmos and works

**Comment by Tomas1405** [comment]
thank you

**Comment by m-revetria** [comment]
Thanks @elgartoinf for the example code, would be really great if you upload your custom row to [Eureka Community](https://github.com/EurekaCommunity)! It may help a lot of people with the same requirement.

I'm closing this issue
