### ISSUE TITLE
Which function is called after user deletes row from MultivaluedSection?

### ISSUE THREAD

**Issue by cesaredecal** [xmartlabs/Eureka#1276]
Which function is called after user deletes row from MultivaluedSection?

**Comment by mats-claassen** [comment]
As with other sections as well, `rowsHaveBeenRemoved` is called every time a row is removed. You can then filter by the indexPath to see if it is part of the MultivaluedSection you are looking for. So in your FormViewController override:

```swift
override func rowsHaveBeenRemoved(_ rows: [BaseRow], at indexes: [IndexPath]) {
    super.rowsHaveBeenRemoved(rows, at: indexes)
    print("Rows removed", indexes)
}
```
