### ISSUE TITLE
Swift Compiler Warnings.

### ISSUE THREAD

**Issue by rlam3** [xmartlabs/Eureka#1279]
Xcode 9
Swift 4
Mac OS Sierra 

Eureka v 4.0.1

<img width="381" alt="screen shot 2017-10-10 at 10 59 45 am" src="https://user-images.githubusercontent.com/1154044/31396935-49a8d114-adaa-11e7-97b4-09fa9badd37e.png">

Is there a fix for this warning?

**Comment by iOSUser110** [comment]
getting error in FIeld Row for NSAtrubutesString on xcode 9. please update on this

**Comment by mtnbarreto** [comment]
Same as #1259

**Comment by igor9silva** [comment]
It's a compiler bug, as @mtnbarreto stated.

Please everyone vote and comment on this https://bugs.swift.org/browse/SR-5252 so Apple can know many people is being affected by this bug.

**Comment by mtnbarreto** [comment]
solved
