### ISSUE TITLE
Accessing SelectableRow in SelectorViewController subclass

### ISSUE THREAD

**Issue by clayellis** [xmartlabs/Eureka#1280]
It's common that a developer might want to subclass `SelectorViewController` to add some custom behavior (in my case, adding section indices and customizing scrolling behavior). It's also common to want to access the `selectableValue` of the rows in order to create configuration callbacks for the subclass. 

From what I've experienced, it's quite difficult, nearly impossible, to access the `selectableValue` of the options rows. It's possible to access the `section`s and `row`s through the `form` but casting them to `SelectableSection` and `SelectableRow` is impossible.

Looking through the source, I can see that `SelectableSection`s are created and added to the `form` dynamically, but since subclasses don't have access to the `Row` generic constraint, it's impossible to cast `section`s back to `SelectableSection`s. 

**Is there a recommended approach for accessing `selectableValue` on rows in a `SelectorViewController` subclass?**

**Comment by cerupcat** [comment]
Did you ever find this out? I'm looking to do the same thing.

**Comment by mats-claassen** [comment]
@clayellis @cerupcat Say you have a `row` in a SelectableSection that uses ImageCheckRow's, why can't you do:
```
row.section as! SelectableSection<ImageCheckRow<String>>)
```
or:
```
row as! ImageCheckRow<String>
```
❓

**Comment by cerupcat** [comment]
Thanks, that worked.

`form[indexPath] as? ListCheckRow<String>`
