### ISSUE TITLE
Advice on adding a subview to a FieldRow

### ISSUE THREAD

**Issue by Laptopmini** [xmartlabs/Eureka#1285]
**Environment:**
- Eureka: 3.0.0
- XCode: 8.3.2

I am currently trying to use the following Cells and add a unit such as "KM/H" on the right-hand side of their UITextField:
- `IntRow`
- `DecimalRow`
- `TextRow`

The idea is that I would like to subclass them so that I can benefit from all their already existing implementations of methods and related protocols.

All I need is to add a `UILabel` to the right of the `UITextField` so that I can display a unit associated with the value requested.

My first attempt was to "hack" it using `cellUpdate` to insert the new subview and setting up the proper constraints:
```swift
.cellUpdate({ cell , row in
    // View
    let unitLabel = UILabel()
    unitLabel.translatesAutoresizingMaskIntoConstraints = false
    unitLabel.text = "km/h"
    unitLabel.textAlignment = .center
    unitLabel.layer.borderWidth = 1
    unitLabel.layer.borderColor = UIColor.red.cgColor
    cell.addSubview(unitLabel)
    
    cell.textField.layer.borderColor = UIColor.blue.cgColor
    cell.textField.layer.borderWidth = 1
    cell.textField.removeConstraints(cell.textField.constraints)
    
    cell.textLabel?.layer.borderColor = UIColor.green.cgColor
    cell.textLabel?.layer.borderWidth = 1
    if let constraints = cell.textLabel?.constraints {
        cell.textLabel?.removeConstraints(constraints)
    }
    
    // Constraints
    let views: [String:Any] = ["label": cell.textLabel!,"field": cell.textField, "unit": unitLabel]
    let constraints = NSLayoutConstraint.constraints(withVisualFormat: "H:|-[label]-[field]-[unit]-|", options: [], metrics: nil, views: views) //.alignAllLastBaseline
        + NSLayoutConstraint.constraints(withVisualFormat: "V:|-(11)-[label]-(11)-|", options: .alignAllLastBaseline, metrics: nil, views: views)
        + NSLayoutConstraint.constraints(withVisualFormat: "V:|-(11)-[field]-(11)-|", options: .alignAllLastBaseline, metrics: nil, views: views)
        + NSLayoutConstraint.constraints(withVisualFormat: "V:|-(11)-[unit]-(11)-|", options: .alignAllLastBaseline, metrics: nil, views: views)
    cell.addConstraints(constraints)
})
```
I've added borders around the views to make it easier to visually debug. 

However this fails pretty badly as it seems to continue to enable conflicting constraints:
```
(
    "<NSAutoresizingMaskLayoutConstraint:0x170481680 h=--& v=--& UITableViewCellContentView:0x107053cf0.midX == 160   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x1704816d0 h=--& v=--& UITableViewCellContentView:0x107053cf0.width == 320   (active)>",
    "<NSLayoutConstraint:0x170480b90 H:[UITextField:0x107053380]-(NSSpace(8))-[UILabel:0x1070573b0'km/h']   (active)>",
    "<NSLayoutConstraint:0x170480be0 Eureka.TextCell:0x1039e3a00.trailingMargin == UILabel:0x1070573b0'km/h'.trailing   (active)>",
    "<NSLayoutConstraint:0x1704812c0 UITableViewCellContentView:0x107053cf0.trailingMargin == UITextField:0x107053380.trailing   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x170481450 h=-&- v=--& 'UIView-Encapsulated-Layout-Left' Eureka.TextCell:0x1039e3a00.minX == 0   (active, names: '|':UITableViewWrapperView:0x103800000 )>",
    "<NSLayoutConstraint:0x1704813b0 'UIView-Encapsulated-Layout-Width' Eureka.TextCell:0x1039e3a00.width == 320   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1704812c0 UITableViewCellContentView:0x107053cf0.trailingMargin == UITextField:0x107053380.trailing   (active)>
```
From what I can tell, the `contentView` of the Cell has itself its own constraints with the `UITextField` telling it to hug the right side of the cell (where I am trying to place my unit).

So, messing with `contentView` constraints from `cellUpdate` would be too messy/complicated, so from there I tried to take the route of subclassing. It seems all 3 of the Rows I am interested in are actually `FieldRow`s.
https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Common/FieldRow.swift

But the more I look into it, the more I feel like I'm jumping down a rabbit hole...

Any advice on the simplest way for me to add a subview `UILabel` in the format `H:|-[label]-[field]-[unit]-|` to FieldRow or its subclasses specifically?
Any help is appreciated!

**Comment by KevinGong2013** [comment]
Add subview to FieldCell is not needed.
You Can:
Custom number formatter OR Set textfield's rightView.

**Comment by Laptopmini** [comment]
@KevinGong2013 Thanks for the reply!

Using the `cell.textField.rightView` seems to be the way to go. However, I am still running into an issue where the view is invisible if `.sizeToFit()` is not called before the label is set to the `rightView`.

```swift
.cellUpdate({ cell , row in
    let unitLabel = UILabel()
    unitLabel.text = "km/h"
    unitLabel.textAlignment = .right
    
    let size = unitLabel.systemLayoutSizeFitting(UILayoutFittingCompressedSize)
    unitLabel.frame = CGRect(x: 0, y: 0, width: size.width + 10, height: cell.textField.frame.height)
    // unitLabel.sizeToFit()  << OMMITING THIS RESULT IN INVISIBLE VIEW
    
    cell.textField.rightView = unitLabel
    cell.textField.rightViewMode = UITextFieldViewMode.always
})
```

Once the cell's field becomes the first responder/the row is reloaded, the view appears magically. Very weird. Any advice?

With `.sizeToFit()`:
![Image](https://i.imgur.com/fAQgYn7.png)

Without `.sizeToFit()`:
![Image](https://i.imgur.com/gpK4av0.png)

**Comment by Laptopmini** [comment]
With some tweaking I got it to display exactly how I wanted.

Thanks for the help @KevinGong2013!

**Comment by mannguyen0107** [comment]
@Laptopmini I'm trying to do this could you please tell me what you tweak that got it working?
