### ISSUE TITLE
4 warnings by just installing for swift 4

### ISSUE THREAD

**Issue by thomaskblr** [xmartlabs/Eureka#1286]
For some reason with after upgrading to the newest Xcode and newest iOS I am running into these 4 warnings 

Cast from 'UIViewController' to unrelated type 'MultipleSelectorViewController<GenericMultipleSelectorRow<T, Cell>>' always fails

Cast from 'RowOf<OptionsRow.Cell.Value>!' to unrelated type 'OptionsRow' always fails

Cast from 'UIViewController' to unrelated type 'SelectorViewController<SelectorRow<Cell>>' always fails

Cast from 'Section' to unrelated type 'SelectableSection<Row>' always fails

They dont stop the app from running but they are coming up as a warning. Is there a way to fix these issues?

**Comment by francoisduchemin** [comment]
I have the same warnings...

**Comment by mtnbarreto** [comment]
same as #1259

**Comment by akabab** [comment]
characters warning from #1259 have been removed, those 4 remains

**Comment by sarbogast** [comment]
Yes, this is not done. Please fix.

**Comment by akabab** [comment]
@mtnbarreto or at least re-open so contributors know where to hit :)

**Comment by dtroupe18** [comment]
This issue still exists in version 4.0.1 any update on this?

**Comment by mats-claassen** [comment]
These warnings are Swift issues. All these casts actually work (and the classes aren't unrelated) but it seems Swift has problems realizing that with generics. You could file a radar with Swift or check if there already is one.
