### ISSUE TITLE
Not working with swift 4 and xcode 9 

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#1289]
getting error as below  screenshot 
<img width="1148" alt="screen shot 2017-10-16 at 12 13 42 pm" src="https://user-images.githubusercontent.com/2657399/31598469-80ec21d8-b26b-11e7-8ca4-c84129db4308.png">

please update on this :(

**Comment by sittingbool** [comment]
same here

**Comment by kmentrobin** [comment]
Try to change Swift Version in Build Settings in your Pods
<img width="914" alt="snimek obrazovky 2017-10-16 v 14 05 26" src="https://user-images.githubusercontent.com/26112566/31611132-2386a92c-b27b-11e7-8c12-16a7e04eb6d4.png">

**Comment by wilyamx** [comment]
I tried the suggestion above and I still got the same error.

**Comment by kmentrobin** [comment]
Did you try 
`pod update` ?

**Comment by sittingbool** [comment]
Helped for me, although I had to update the whole code to Swift 4. You have to do ist for your app target as well as for each of the swift targets in your Pods project.

**Comment by mtnbarreto** [comment]
same as https://github.com/xmartlabs/Eureka/issues/1266

**Comment by mtnbarreto** [comment]
Seems cocoapods use swift 3.2 by default. You should specify the swift version to use in each pod from your podfile file as  https://github.com/xmartlabs/Eureka/issues/1266#issuecomment-335937065 indicates.
