### ISSUE TITLE
OnCellUnHighlight never called

### ISSUE THREAD

**Issue by vshahpledge** [xmartlabs/Eureka#129]
I have the following: 

            <<< DecimalRow() {
                //set current value and placeholder
                $0.title = "Weight"
                $0.placeholder = "Pounds"
                let weight: String? = Member.currentMemberInContext(nil)?.weight
                if let uWeight = weight {
                    $0.value = Float(uWeight)
                }
                }.onCellUnHighlight({ (cell, row) -> () in
                    //save value to server
                })

But the onCellUnHighlight callback is never called when the decimal row resigns first responder.

The onChange callback works alright, but I'd rather not make a network call every time a character is changed.

**Comment by mats-claassen** [comment]
Hi, this is because currently the onCellHighlight overrides the onCellUnHighlight. Look at how the `DecimalRow` is defined. In fact most of the rows are defined like this.
```
public final class DecimalRow: _DecimalRow, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        onCellHighlight { cell, row  in
            let color = cell.textLabel?.textColor
            row.onCellUnHighlight { cell, _ in
                cell.textLabel?.textColor = color
            }
            cell.textLabel?.textColor = cell.tintColor
        }
    }
}
```
 So if you want to use the 'unhighlight' callback you must override the `onCellHighlight` as well.

**Comment by mtnbarreto** [comment]
Same as #96
