### ISSUE TITLE
Can't customize backgroundColor on ButtonRow's textLabel

### ISSUE THREAD

**Issue by yousefhamza** [xmartlabs/Eureka#1297]
When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

I'm on Eureka v4.0.1
Xcode 9, iOS 11

I'm trying to set `backgroundColor` on the `textLabel` but it won't be set 
```
.cellUpdate({ (cell, row) in
                    cell.textLabel?.backgroundColor = .red
}
```

After quite some time thinking that it was maybe overirdden some where in Eureka I found out that you can only customize it in `- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath`
Which isn't where `updateCell` is called (`cellForRow`).

I couldn't customize the cell either because it depends on the UITableViewCell and there's no outlet to customize it in the nib.

So from what I see there's 2 solutions:
1_ (fast & hacky) call `updateCell` in `willDisplayCell`
2_ Decouple base cell from UITableViewCell

**Comment by mats-claassen** [comment]
You can also oveerride `- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath` in your FormViewController and, if it is the cell you wan to customize then change its textLabel's backgroundColor
