### ISSUE TITLE
how to  Refresh List

### ISSUE THREAD

**Issue by godwar10** [xmartlabs/Eureka#1298]
self.tableView?.reloadData() can not reloadData

**Comment by alexge12** [comment]
where you call the method self.tableView?.reloadData() ?

**Comment by godwar10** [comment]
In the main controller loading list and request data refresh list

**Comment by godwar10** [comment]
who can tell me how to reload cell.

**Comment by godwar10** [comment]
ok now.i do not add cellUpdate
