### ISSUE TITLE
Custom Filter

### ISSUE THREAD

**Issue by alexge12** [xmartlabs/Eureka#1301]
Hi
I would like to create a multi-level field, but I don't know how to do this. 
For example, there are MultipleSelectorRow field named "vehicle" which contains two options: "Audi" and Mercedes. 
I want, when user clicks on option "Audi", new list appearing where he can choose needed option "Quatro".
Vehicle -> Audi -> A5, A6, Quatro

Sorry, that I write here
I do not know who to ask

**Comment by mats-claassen** [comment]
You can add sections behind the `MultipleSelectorRow` and use the `hidden` variable to show those sections only if the respective option is selected in the `MultipleSelectorRow`. Have a look at the readme to know more about the `hidden` variable
