### ISSUE TITLE
Use Of Undeclared Type 'Emoji'

### ISSUE THREAD

**Issue by deborahepadilla** [xmartlabs/Eureka#1302]
I'm trying to implement multiple selections with emojis. I'm getting this error though in this line: 
```swift
<<< MultipleSelectorRow<Emoji>() {
}
```
(For some reason the emoji line isn't appearing above, sorry about that!)

I tried cleaning and rebuilding, but it doesn't work. Everything else is working fine. Any thoughts on how to fix this? Thanks!

**Comment by mtnbarreto** [comment]
Emoji is nothing else than a String typealias as https://github.com/xmartlabs/Eureka/blob/0895eccb3fbbdc31ff881c90d3d1f21a8ed4b05e/Example/Example/ViewController.swift#L132 indicates.

Do you have such typealias in your code?
