### ISSUE TITLE
How to set the position of the text in LabelRow?

### ISSUE THREAD

**Issue by carlosbdw** [xmartlabs/Eureka#1306]
![2017-11-01 10 00 37](https://user-images.githubusercontent.com/21432033/32256826-6822a298-beec-11e7-8943-fc550a9bfc14.png)

the text is not center alignment vertically.

**Comment by kaich** [comment]
`open class LabelCellOf<T: Equatable>: Cell<T>, CellType`. So you can't change position with custom xib. I think it's simple to create a custom row for yourself.

**Comment by mats-claassen** [comment]
Yes if you use the default LabelCell to display the errors then it will use `UITableViewCell`'s textLabel. Possibly the best way to fully customize this is to create a custom row.
