### ISSUE TITLE
Cannot select row of single component list in UIPickerView of PickerCell<T>

### ISSUE THREAD

**Issue by chappejw** [xmartlabs/Eureka#1309]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
I am using version 4.0.1

- Make sure your Xcode version is the latest stable one.
Xcode 9.1

- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".
Not previously reported

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
Eureka 4.0.1, Xcode 9.1, iOS 11.1

- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
This is a feature request more or less.

- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Problem Description:**
There is a usability issue with the PickerCell class where if there is only a single row in the picker, the user cannot select it because the currently selected row is only updated when there is an onChange row event from a scroll action, and so the user is unable to complete the task of selecting the only row in the picker. I am looking for a way to add a gesture recognizer to the picker row so that it can be selected either by scrolling to the desired row and pick up the onChange event ( which already happens, but not with a single row picker since the picker cannot be scrolled ), or by simply tapping on the row already displayed in the picker to select it.

Can anyone suggest a best way of allowing the user to select the single row case in the UIPickerView?

Best Regards,
Jacob

**Comment by m-revetria** [comment]
Duplicates #1354, you can see my comment there.
