### ISSUE TITLE
A field's title label text dissapears or becomes white when selected

### ISSUE THREAD

**Issue by jlnbuiles** [xmartlabs/Eureka#1311]
Hey, so i'm having this issue on all text fields on my form when they become active. Once deselected the label comes back and it's visible.

I am NOT doing any UI configuration/changes on my end. Simply setting values like these:
` <<< 
            
        EmailRow(){
            $0.title = "Email"            
            $0.placeholder = "name@mail.com"
            $0.value = user?.email
            $0.tag = RowTag.email.rawValue
        }
`

Am I missing a configuration step or is there a bug?

![simulator screen shot - iphone 6 - 2017-11-04 at 15 42 36](https://user-images.githubusercontent.com/860812/32409281-f15e2a1e-c176-11e7-8a09-ed5b4ae0bf1e.png)

note: I'm importing the lib with this line:
`pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'`

**Comment by jlnbuiles** [comment]
I was able to resolve this using one of the callbacks, but I feel like this sholdn't be necessary.
`
    .onCellHighlightChanged({ (cell, row) in
        cell.titleLabel?.textColor = .black
    })
`

**Comment by gerryka** [comment]
In my case i could resolve it by setting the global tint of my storyboard back to default. I had previously set that to white, which was causing the labels and even the cursor in Eureka generated fields to be white.

**Comment by mcousillas6** [comment]
Does this approach worked?

**Comment by manjuhere** [comment]
@gerryka you're right.
I guess, Eureka depends on Global Tint property to tint all its elements. If you want to retain the white tint colour and yet, have a unique tint for your form, set the tint for the table view like this -

`self.tableView.tintColor = UIColor.blue`

**Comment by m-revetria** [comment]
I'm closing this as seems a solution was found and no change is required from Eureka.

Thanks
