### ISSUE TITLE
LayoutConstraints issue

### ISSUE THREAD

**Issue by sverin** [xmartlabs/Eureka#1312]
I'm having a LayoutConstraint issue when I use the framework. It happens with a basic form with only two text fields. I have run it in the simulator (iOS 11.2 beta) and on a device (iOS 11.0). As soon as I have pressed the first textfield and then press the second I receive a LayoutConstraint warning. Don't know if it's a bug in iOS or in Eureka? Using version 4.0.0

    class ViewController: FormViewController {

        override func viewDidLoad() {

            super.viewDidLoad()
        
            form +++ Section()
        
                <<< TextRow("field1") {
                    $0.title = "My Label 1"
                }
            
                <<< TextRow("field2") {
                    $0.title = "My Label 2"
                }
        
        }
    }

**Comment by mats-claassen** [comment]
@sverin Is this still the case? What does the warning say?

**Comment by sverin** [comment]
@mats-claassen No, with the latest release 4.1.1 I'm testing now, it works fine. The warning is gone.
