### ISSUE TITLE
Segue from custom HeaderFooterView

### ISSUE THREAD

**Issue by csimmonsbluebook** [xmartlabs/Eureka#1314]
How can you segue from the selection of a `HeaderFooterView` created from a custom `UIView`?

The code I'm using to create the `HeaderFooterView` is as follows:
```
form +++ Section() { section in
    var header = HeaderFooterView<ReportDetailsHeaderView>(.class)
    header.height = { 140 }
    header.onSetupView = { v, s in
        v.configureView(item: self.item)
    }
    section.header = header
}
```

Xcode: 9.1
Eureka: 4.0.1
iOS: 11.1

**Comment by m-revetria** [comment]
Hi @csimmonsbluebook a form section header is not a selectable view by default. You can add either a touchable view (like a button) or a gesture recognizer in your custom section header view and then handle touches over it in order to perform a segue.

**Comment by csimmonsbluebook** [comment]
@m-revetria Thanks for your response. Sorry I haven't closed this issue sooner. I actually had solved this using a clear view overlaid over top my section header with a tap recognizer, same as you recommended.
