### ISSUE TITLE
FormViewController does not respect `largeTitleDisplayMode = .automatic`

### ISSUE THREAD

**Issue by minuscorp** [xmartlabs/Eureka#1318]
There's an issue with Eureka 4.0.1 used with iOS 11 and the latest Xcode 9.1. When an `UINavigationController` defines its own large title attributes they are not working as expected with another `UIViewControllers` in an application.

If you define your custom `UINavigationController` as:
```swift
private func initialize() {
   [...]
   if #available(iOS 11.0, *) {
            self.navigationBar.prefersLargeTitles = true
            self.navigationBar.largeTitleTextAttributes = myAttributeArray
        }
}
override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 11.0, *) {
            self.navigationItem.largeTitleDisplayMode = .automatic
        }
}
```

It makes that any `UIViewController`'s navigation title automatically collapses when scrolling whenever it contains any kind of scroll (i.e., `UITableView`, `UICollectionView`). But this is not happening with the `FormViewController`. It stays large even when scrolling.

**Comment by minuscorp** [comment]
This is getting some attention please? 😅

**Comment by mats-claassen** [comment]
Just tested this on the latest version and it seems to work as intended. The large title are shown and scrolled in/out together with the tableView. If you still experience the problem feel free to reopen the issue
