### ISSUE TITLE
xcode 9.1: custom cell no longer visible as custom class in interface builder

### ISSUE THREAD

**Issue by orthoteks** [xmartlabs/Eureka#1319]
This seemed to work befor xcode 9.1/High Sierra. Anybody else seeing this issue? Using Eureka 4.0.1 (cocoapods). 

Previously a custom cell with similar class signature worked fine:
`public class CustomCell: Cell<Bool>, CellType {`

![screen shot 2017-11-10 at 6 45 09 pm](https://user-images.githubusercontent.com/33560508/32683438-362ef944-c649-11e7-95f6-199068eab4a6.png)

This compiles fine, but the CustomCell is not visible as custom class for nib, therefore cant link outlets.

Interestingly, removing the generic <Bool> makes it visible in interface builder (but wont compile).
`public class CustomCell: Cell, CellType {`

Im assuming this is a Xcode 9.1 bug, but I haven't seen anything specific about it.

Any ideas?

Thanks

**Comment by mtnbarreto** [comment]
As a workaround, try removing the CellType protocol, then connect the class using interface builder if it appears, finally put back CellType protocol. 

Let me know if it works for you

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
