### ISSUE TITLE
Autocomplete row

### ISSUE THREAD

**Issue by Tomas1405** [xmartlabs/Eureka#1320]
Hello, I need to my formular row with textfield with autocomplete options, have anybody some good solution?

**Comment by gorbat-o** [comment]
I guess a custom row can be a good idea :)
that is what i would do if i have to make a special textfield like that

**Comment by lognaturel** [comment]
You may be interested in https://github.com/EurekaCommunity/SuggestionRow

**Comment by mcousillas6** [comment]
The provided link has the best approach.
