### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 3]'

### ISSUE THREAD

**Issue by alexanderkhitev** [xmartlabs/Eureka#1321]
Hello! When the number of participants becomes zero, I hide the section of participants in the class heir from FormViewController. During testing there was only one participant. I added and deleted this member very quickly, it turns out there was one row in the section with index 0. After deleting and the user, I always do a check for the fact that the section has other rows or not, I check so

```
if section.isEmpty {
            section.evaluateHidden()
        }
```

After that, I got the app crash here

```
extension Form: MutableCollection {

    // MARK: MutableCollectionType

    public subscript (_ position: Int) -> Section {
        get { return kvoWrapper.sections[position] as! Section } // ****App Crash**  position is 4**
        set {
            if position > kvoWrapper.sections.count {
                assertionFailure("Form: Index out of bounds")
            }

            if position < kvoWrapper.sections.count {
                let oldSection = kvoWrapper.sections[position]
                let oldSectionIndex = kvoWrapper._allSections.index(of: oldSection as! Section)!
                // Remove the previous section from the form
                kvoWrapper._allSections[oldSectionIndex].willBeRemovedFromForm()
                kvoWrapper._allSections[oldSectionIndex] = newValue
            } else {
                kvoWrapper._allSections.append(newValue)
            }

            kvoWrapper.sections[position] = newValue
            newValue.wasAddedTo(form: self)
        }
    }
    public func index(after i: Int) -> Int {
        return i+1 <= endIndex ? i+1 : endIndex
    }
    public func index(before i: Int) -> Int {
        return i > startIndex ? i-1 : startIndex
    }
    public var last: Section? {
        return reversed().first
    }

}
```
Sections only 4, but it turns out that this code tries to take the 5 section

**Update 1:**
 ```
debugPrint("kvoWrapper.sections", kvoWrapper.sections.count, "position", position)
            return kvoWrapper.sections[position] as! Section 
```
Returns the following result

`"kvoWrapper.sections" 4 "position" 4`

**Update 2:** I removed first all the sections except one where changes are constantly occurring, continued to test, everything is fine. Then I added the top sections above the variable section, tested it and did not get the app crash. Then I added the lower sections that do not fit on the screen, and after the changes (adding deletion) I got an app crash.

**Comment by alexanderkhitev** [comment]
@mtnbarreto Please look at this issue. Maybe you can tell me something.

**Comment by alexanderkhitev** [comment]
When I noticed that section header height is not stable (although it is specified), I decided to do so header.height = {height}, after that I tested, section header height remained correct and I did not receive app crash anymore.
before 

```
     section.header = {
                guard let height = headerHeight else { return nil }
                var header = HeaderFooterView<UIView>(.callback({
                    let view = UpcomingHeaderFooterView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: height))
                   //////
                   return view
                }))
```

after  
```
     section.header = {
                guard let height = headerHeight else { return nil }
                var header = HeaderFooterView<UIView>(.callback({
                    let view = UpcomingHeaderFooterView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: height))
                   //////
                   return view
                }))
                header.height = { height }
```

**Comment by melloskitten** [comment]
For anyone experiencing the same problem, make sure to check whether you are appropriately calling the super methods in `viewWillAppear_ animated: Bool)`and `viewWillDisappear(_ animated: Bool)`. For me, not calling the supers resulted either in an out of bounds crash or the cell not doing anything at all, similarly to issue #1656.
