### ISSUE TITLE
Is it possible to realize sub-forms with Eureka?

### ISSUE THREAD

**Issue by M-HERBRICH-ITC** [xmartlabs/Eureka#1322]
Hi,
I need to create sub-forms. So if you tap a row, it will open a simple subform (e.g. text and number cell).
Is this possible with Eureka right now?
Best regards,
Matthias

**Comment by gorbat-o** [comment]
hey, you can maybe take a look over there,
https://github.com/xmartlabs/Eureka#hiding-using-a-function-condition

replace the switch with the taprow :)

**Comment by M-HERBRICH-ITC** [comment]
@gorbat-o 
Sry, this isn't what I was looking for.
But I could realize my request by implementing custom presenter row which includes another form
