### ISSUE TITLE
[Sort Rows] Sorted array of objects, reload associated rows

### ISSUE THREAD

**Issue by gorbat-o** [xmartlabs/Eureka#1325]
Hey guys,

I'm using:

Eureka: 4.0.1
Xcode: Version 9.1 (9B55)

I have an array of objects, with a field called firstAndLastName,
I loaded the data in the form, it works pretty well.
and after I sorted this array with that, works too

```
fileprivate func sortByNames() {
        self.cases.sort { rowOne, rowTwo -> Bool in
            return rowOne.firstAndLastName < rowTwo.firstAndLastName
        }
}
```

I'm wondering if I have to completely reload the tableview, or can I update only the cells which I need, and make a kinda visual effect with the rows which move to the right place ??

Thanks :)

**Comment by mats-claassen** [comment]
Hey, sorry for the late reply.

If you want to reorder the rows on the table you will have to call `tableView.reload`. If you have them all in one section you can use `func reload(with rowAnimation: UITableViewRowAnimation = .none)`.
