### ISSUE TITLE
Use Of Unresolved Identifier Row

### ISSUE THREAD

**Issue by deborahepadilla** [xmartlabs/Eureka#1328]
I'm trying to assign a tag name to each field. I'm getting the error, "Use Of Unresolved Identifier 'row'". Not sure how to fix. I tried a few resources on StackOverFlow and it seems to be fine, so I'm not sure why it's giving me an issue.

Below is what's giving me an error (row). However it works for other fields I have in my project:
```swift       
            <<< EmailRow() {
                $0.title = "Email"
                $0.value = "email@email.com"
                row.tag = "emailRowTag"
            }
            
            <<< PasswordRow() {
                $0.title = "Password"
                $0.placeholder = "password123"
                row.tag = "passwordRowTag"
                    
            }
            
            <<< PhoneRow() {
                $0.title = "Mobile Phone"
                $0.placeholder = "123-456-789"
                row.tag = "phoneRowTag"
            }
```

**Comment by m-revetria** [comment]
Hi @deborahepadilla, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-----------

That being said, the error in your code is that you've not declared a variable named `row` within rows construction callbacks.

You can use either one of:

```swift
<<< EmailRow() {
    $0.title = "Email"
    $0.value = "email@email.com"
    $0.tag = "emailRowTag"
}
```

Or

```swift
<<< EmailRow() { row in
    row.title = "Email"
    row.value = "email@email.com"
    row.tag = "emailRowTag"
}
```
