### ISSUE TITLE
How can I update a section footer after .onChange

### ISSUE THREAD

**Issue by szalaidaniel** [xmartlabs/Eureka#133]
Hi!

I would like to update the footer after the sellingPrice row is changed. New footer text example: You get \(sellerPrice) after you sell successfully.
How can I do it?

Thanks

```          
            +++ Section (header: "Header Text", footer: "If your sell is successfully we get 80% commission.")
        
                <<< IntFloatLabelRow("sellingPrice") {
                    $0.title = "Selling Price"
                }
                   .onChange { row in
                        if row.value != nil {
                        let sellerPrice = Double(row.value!) * 0.80
                            print(sellerPrice)
                        }
                        else{
                          }
                   }

```

**Comment by mats-claassen** [comment]
Why don't  you try this:
```
 row.section?.footer = HeaderFooterView(title: "You get \(sellerPrice) after you sell successfully.")
```

**Comment by szalaidaniel** [comment]
Doesn't work. :( (Build Failed)

Only work this: row.section?.footer = "You get after you sell successfully." as HeaderFooterView
But it's not good because:
- not support String interpolation
- if you originally have header / footer on the section: run, but not working (works only if you have Section ("text")

**Comment by mtnbarreto** [comment]
@szalaidaniel We've added a new readme FAQ question to show how section header footer can be updated, take a look at https://github.com/xmartlabs/Eureka#how-to-update-a-section-headerfooter
Regards
