### ISSUE TITLE
PushRow Selecting, Not Returning

### ISSUE THREAD

**Issue by deborahepadilla** [xmartlabs/Eureka#1330]
Below is my code. I am able to pick a city and it 'checks it off', but it does not go back to the form view controller, after I pick it. I tried looking, but cannot seem to find a solution. I also tried looking at [YouTube](https://www.youtube.com/watch?v=3v5yT2wTc9I&t=943s), and I seem to be doing it right. Not sure what's wrong. Thanks!

```swift
<<< PushRow<String>() {
    $0.title = "Your City"
    $0.options = ["New York", "Boston", "Philadelphia", "Atlanta", "Chicago", "Los Angeles"]
    $0.value = ""
    $0.selectorTitle = "Choose City"
    $0.tag = "cityRowTag"
} .onPresent({ (from, to) in
    to.dismissOnSelection = true
    to.dismissOnChange = false
})
```

**Comment by uknowmeright** [comment]
I am having the same issue. I am using a viewController with a tableview in it. The viewController is also being pushed onto a navigation controller. Would this make a difference?

**Comment by indrajitsinh** [comment]
Wrap your controller class in UINavigation Controller it should work

**Comment by m-revetria** [comment]
@deborahepadilla I've tried the provided code and it is working fine on latest Eureka's code (from `master` branch). Could you please let us know which Eureka's version you are using?

Also, could you please provide us with the entire form creation code to reproduce the error on our side? It will be really helpful.

Thanks

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
