### ISSUE TITLE
FormViewController with Storyboards

### ISSUE THREAD

**Issue by sverin** [xmartlabs/Eureka#1331]
I try to create a UIViewController that extends FormViewController and than use it in a storyboard. In the storyboard I can't find or access the UITableView. So I can't connect them.

```
class MyFormViewController: FormViewController {
   ...
}
```
However, if I look in the example when I download the Eureka library this works. What am I doing wrong?

**Comment by m-revetria** [comment]
Hi @sverin, can you provide me with more information on how you are including Eureka into your project and what Eureka's version you are using?

If you are using Carthage, you might find helpful next issues:
* #663 
* #295

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
