### ISSUE TITLE
How to change the title of AlertRow cancel button ?

### ISSUE THREAD

**Issue by carlosbdw** [xmartlabs/Eureka#1335]
Because I don't want to display "Cancel" , my codes : 
.onPresent{_,  to in
          to.cancelTitle = "test"
      }

But it does not work, please help ,thank you.

or how to hide the cancel button ?

**Comment by m-revetria** [comment]
Hi @carlosbdw,

Right now changing the `cancelTitle` property will have effect if you do it at the top of the `onPresent` block. Concretely, you must avoid calling `to.view.<something>` before setting `cancelTitle`.

``` swift
.onPresent{ _, to in
   to.cancelTitle = "test"
   to.view.tintColor = .purple // Must be placed after setting `cancelTitle` property
}
```

Hiding cancel button is not an option right now.

**Comment by m-revetria** [comment]
I'm closing this issue as #1357 was merged.

Thanks!
