### ISSUE TITLE
How can I add a value into Eureka Form? 

### ISSUE THREAD

**Issue by synabreu** [xmartlabs/Eureka#1336]
Hello everyone

When I selected name on Contacts Dialog, I would like to add value to Eureka's Form.
But it occurs an error as below: Argument labels '(_:)' do not match any available overloads.  

```swift
func contactPicker(_ picker: CNContactPickerViewController, didSelect contact: CNContact) {
        let fullName = "\(contact.givenName) \(contact.familyName)"
        LabelRow.Cell("event_contacts").row.title = fullName <-- error occurred
}

<<< LabelRow () {
    $0.title = "Invitees"
    $0.value = "choices"
    $0.tag = "event_contacts"
    }
    .onCellSelection { cell, row in
    self.openContacts() // call Contacts UI Form
    row.reload() 
    }
```

So my question is, how can I define a property or an attribute in Eureka's form like  LabelRow.Cell("event_contacts").row.title?
Thanks in advance!

**Comment by m-revetria** [comment]
Hi @synabreu,

The proper way to access a row already added to form is using `Form.rowByTag(tag: string)`. Use next code as snippet:

```swift
form.rowBy(tag: "event_contacts")?.title = fullName
```

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
