### ISSUE TITLE
UIDatePicker timezone

### ISSUE THREAD

**Issue by dastanbb** [xmartlabs/Eureka#1337]
Hi!
I'm using **DateTimeRow** to display date and time depending on custom time zone. The problem is when user taps on the row UIDatePicker appears with date related to device time zone.
I've tried to call `cell.datePicker.timeZone = customTimeZone` on **cellSetup** but with no luck
Does anyone know how to solve this?

**Comment by dastanbb** [comment]
The solution was to set  datePicker's time zone **onSelection** event:

` 
DateTimeRow(RowTag.endDate.rawValue) { 
    $0.value = Date()
   $0.dateFormatter = customDateFormatter
   }.onCellSelection { [unowned self ] cell, _ in
                cell.datePicker.timeZone = self.customDateFormatter.timeZone
        }
`

**Comment by serbuk** [comment]
Thank you! It works.
