### ISSUE TITLE
How to make DateTimeInlineRow value show in textLabel rather than detailTextLabel

### ISSUE THREAD

**Issue by r00tify** [xmartlabs/Eureka#1340]
So I'm trying to customize the DateTimeInlineRow from Eureka library to show the selected date in title position rather than detail position. To replace the 'placeholder' "Date" shown in the following picture: 

[https://i.stack.imgur.com/dISli.png](url)

I tried a lot of approaches with no success, this is my last attempt:

```
        <<< DateTimeInlineRow() { row in
            row.tag = "date"
            }.cellSetup { cell, row in
                row.title = "Date"
            }.cellUpdate { cell , row in
                if let date = row.value {
                    row.title = DateFormatter().string(from: date)
                }
                cell.textLabel?.textColor = row.title == "Date" ? .gray : .black
            }

```

**Comment by mats-claassen** [comment]
You should set `row.title` in `onChange` callback instead of cellUpdate.
And set `cell.detailTextLabel?.text = nil` in cellUpdate
