### ISSUE TITLE
Ability to pass in a dictionary of data for PopoverSelectorRow

### ISSUE THREAD

**Issue by anthonycastelli** [xmartlabs/Eureka#1342]
I've run into a bit of a situation here. 
1. You can't have duplicate names
2. Trying to categories things can be a bit of a nightmare. 

It would make much more sense be able to pass in a dictionary of data to the `optionsProvider`. Something like this:

```swift
$0.optionsProvider = ["category_name": ["item 1", "item 2", "item 3"]]
```
Of even more descriptive 
```swift
$0.optionsProvider = [["section_title": "category_name", "section_items": ["item 1", "item 2", "item 3"]]
```

The problem with the current implementation is I have to construct arrays and manually go through each category of items I have and see if the name matches an item in the list, however, this brings up another issue, the fact that you have to have unique names for each item. 

Is there any easy workaround for this?

Environment: Cocoapods, Xcode 9.2, iOS 10.2

**Comment by mats-claassen** [comment]
@anthonycastelli Sorry for the late reply. The `optionsProvider` doesn't have to be a String. You can set any Equatable type as options for any OptionsRow like `PopoverSelectorRow`.

This means you can set multiple objects that have a different identifier but are displayed as the same.
