### ISSUE TITLE
Carthage error: 2.0.0-beta-1

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#1343]
The following line in the `Cartfile`:

```
github "xmartlabs/Eureka" ~> 4.0
```

Is resolved to the Eureka tag `2.0.0-beta.1`. Probably due to this bug: https://github.com/Carthage/Carthage/issues/469

I'm aware this is an error on the `Carthage` end, but please delete the `2.0.0-beta-1` tag, so we can get proper version resolution for now.

**Comment by marbetschar** [comment]
FWIW: All `EurekaCommunity`projects are not working properly due to this bug, if `Carthage` is used for dependency resolution.

**Comment by mtnbarreto** [comment]
Seems no one else had this issue. I will close it for now. 
Thanks for reporting it.
