### ISSUE TITLE
Changing Text Input Traits

### ISSUE THREAD

**Issue by zajil** [xmartlabs/Eureka#1346]
Hi,

I am wondering how I can change the Text Input Traits such as Capitalization and Correction.

Thanks
![2iur6](https://user-images.githubusercontent.com/1737213/33820328-f287cca0-de5f-11e7-9bef-827e8da472ba.png)

**Comment by m-revetria** [comment]
Hi @zajil , as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-----------

If you're using an Eureka's row (e.g.: EmailRow, NameRow, TextRow, etc.), you have to access `textField` property from it and change its properties. The common place to change traits is from `cellSetup` callback when adding a row:

```swift
form +++ Section()
<<< TextRow("nick").cellSetup { cell, _ in
    cell.textField.autocapitalizationType = .allCharacters
    cell.textField.autocorrectionType = .no
}
```
