### ISSUE TITLE
Error duplicate symbol when compiling

### ISSUE THREAD

**Issue by B0Dim** [xmartlabs/Eureka#1347]
Hi,
- Environment: Eureka, Xcode 8, Cocoapods

I have couple LabelRows, PhoneRows, URLRows etc. and I'm getting a compiler error:

`duplicate symbol __TFC6Former18FormViewControllerCfT5styleOSC16UITableViewStyle_S0_ in:
    /Users/.../Library/Developer/Xcode/DerivedData/.../Objects-normal/x86_64/SalonProfileViewController.o
    /Users/.../Library/Developer/Xcode/DerivedData/.../Objects-normal/x86_64/MasterProfileViewController.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Any Ideas how I can fix this?

Thanks!

**Comment by mtnbarreto** [comment]
Hi @B0Dim ! Please follow https://github.com/xmartlabs/Eureka/blob/master/.github/ISSUE_TEMPLATE.md so the community can help you quickly and without unnecessary extra communication just to know basic information such as the environment.

**Comment by mtnbarreto** [comment]
Closing due to lack of response....
