### ISSUE TITLE
ActionSheetRow set value and displayValue based on objects

### ISSUE THREAD

**Issue by 99xs** [xmartlabs/Eureka#1348]
Hi there,

I have found some info on adding ActionSheetRow with value and display value, but nothing complete in my opinion. I have an object like the one below and I'm trying to add a new row. Please have a look at the code below and let me know where I'm doing wrong.
```swift
    <<< ActionSheetRow<Option>() {
            $0.title = option.title
            $0.selectorTitle = option.title
            $0.displayValueFor = {(rowValue: Set<Selection>?) in
                   return rowValue?.map({ $0.title! }).sorted().joined(separator: ", ")
             }
    }
```

The Option and selection models are: 

```swift
    class Option: Hashable {
        var id:Int
        var title:String
        var selections:[Selection]
        var hashValue: Int {
            return self.id
        }
    }

    class Selection: Hashable {
        var title:String
        var valueId:Int
        var hashValue: Int {
            return self.valueId
        }
    }
```

Basically, what I'm trying to do is to have a row for each Option and the values to be the Selections. The end goal is to know what Selection  was selected for the Option.

**Comment by m-revetria** [comment]
Hi @99xs, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-----------

That being said, the error I see in your code is in the signature of `displayValueFor`. As you defined your row as `ActionSheetRow<Option>`, the value for `displayValueFor` is `((Option?) -> String?)?` while in your code it is defined as `((Set<Selection>?) -> String?)?`

Then, the correct code would be:

```swift
    <<< ActionSheetRow<Option>() {
            $0.title = option.title
            $0.selectorTitle = option.title
            $0.displayValueFor = { (rowValue: Option?) in
                   return rowValue?. selections.map({ $0.title! }).sorted().joined(separator: ", ")
             }
    }
```

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
