### ISSUE TITLE
How to make top section 'sticky' to top of the screen

### ISSUE THREAD

**Issue by JanJasper** [xmartlabs/Eureka#135]
First of all, thanks for developing Eureka, it's amazingly useful!

Q: In my form I have a top section with an image and a progress tracker, made using a xib file and HeaderFooterProvider.NibFile (basically the same as in the example). Is there a way to make this section 'stick' to the top of the screen while one scrolls down the form?

Adding a separate view above the tableview in the storyboard doesn't work well, as it messes up the formatting and gives issues with updating my progress tracker programmatically. 

Thanks!

**Comment by mtnbarreto** [comment]
Have you tried using a `UITableViewStyle.Plain` as tableView style? 
You may run into some issues if you have many section headers and want only the first one to be fixed at the top. 

Could you clarify on the reasons a separate view does not work? If you provide more information I would provide some help.

**Comment by prbaron** [comment]
How can we define the table view to Plain ?

**Comment by diegomedina248** [comment]
@prbaron You can do this in the Attributes inspector of the `UITableView` you are trying to style

**Comment by mtnbarreto** [comment]
in case you were no using storyboards you can do it programmatically by instantiating the form view controller with...

```swift
public init(style: UITableViewStyle)
```
