### ISSUE TITLE
“UITextField.textAlignment must be used from main thread only” Can't reset TextRows in iOS 11 xcode 9.1

### ISSUE THREAD

**Issue by heisenberg7594** [xmartlabs/Eureka#1351]
Xcode 9.1 iOS 11.1 
I am trying to reset all textRows after clicking submit button but the xcode is telling me to use main thread to update the text field. There is no error in ios 10 but in iOS 11.
This is what I am trying:-
![screen shot 2017-12-14 at 5 58 37 pm](https://user-images.githubusercontent.com/31646541/33992476-bf89cbe6-e0f8-11e7-8887-5c795b730391.png)
This is what I am getting:- 
![screen shot 2017-12-13 at 6 00 18 pm](https://user-images.githubusercontent.com/31646541/33939410-18fc3fec-e031-11e7-9877-8fdd1188e7e7.png)

**Comment by telbaum** [comment]
Probably by putting the code within a DispatchQueue.main.async { } block.
