### ISSUE TITLE
"[UITableViewCell setNeedsUpdateConstraints] must be used from main thread only" can't reset TextRows in iOS 11 xcode 9.1

### ISSUE THREAD

**Issue by heisenberg7594** [xmartlabs/Eureka#1352]
Xcode 9.1 iOS 11.1
I am trying to clear all textRows after submitting the form but the xcode is telling me to use main thread to update the text field. There is no error in ios 10 but in iOS 11.
This is what I am trying:-
![screen shot 2017-12-14 at 5 58 37 pm](https://user-images.githubusercontent.com/31646541/33992423-831d2496-e0f8-11e7-9c3f-6eb588cdba4a.png)

And this is what I am getting:- 
![screen shot 2017-12-14 at 5 58 55 pm](https://user-images.githubusercontent.com/31646541/33992432-8a9acd7c-e0f8-11e7-938e-bac9d825949b.png)

**Comment by abhik-technicise** [comment]
https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1159
