### ISSUE TITLE
Xcode 9.1 | Build Fail

### ISSUE THREAD

**Issue by mjhassan** [xmartlabs/Eureka#1353]
## Environment:

- Eureka 3.1.0, using Cocoapod 1.3.1
- Xcode 9.1 (9B55)
- iOS 11.1
- Swift 3.2

## Problem

After installing Eureka 3.1.0, using `Pod 'Eureka', '~> 3.0'`, project build fails with following error:

![screen shot 2017-12-14 at 7 32 13 pm](https://user-images.githubusercontent.com/4034940/33994663-9acc7d96-e105-11e7-8d16-54af43993404.png)
![screen shot 2017-12-14 at 7 32 32 pm](https://user-images.githubusercontent.com/4034940/33994658-98a22a52-e105-11e7-8ac2-e4bacda56c54.png)

FYI, these two errors are in `Section.swift` file.
I've check closed issue [1220](https://github.com/xmartlabs/Eureka/issues/1220) and [1222](https://github.com/xmartlabs/Eureka/issues/1222). But none of those seems working for Swift 3.2.

**Comment by joeybuddy** [comment]
Exactly the same problem for **Xcode 9.2** and **Swift 4** (`Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2).`)

**Comment by kjhatis** [comment]
This solved using this:
`target 'EurekaToDo' do
  use_frameworks!
  pod 'Eureka', '~> 4.0.0'
  pod 'ImageRow', '~> 3.0'
end
`

But now i am getting this error:

`
Module file's minimum deployment target is ios11.2 v11.2: /Users/ravikantjha/Library/Developer/Xcode/DerivedData/EurekaToDo-btezhxyuybavaibjcdayyrutzvzm/Build/Products/Debug-iphonesimulator/Eureka/Eureka.framework/Modules/Eureka.swiftmodule/x86_64.swiftmodule
`

**Comment by mtnbarreto** [comment]
Hi @mjhassan @kjhatis  You should use Eureka ~> 4.0. https://github.com/xmartlabs/Eureka/issues/1266#issuecomment-335937065 may help too.

**Comment by mjhassan** [comment]
But `Eureka ~> 4.0` doesn't support `Swift 3.2`, does it? @mtnbarreto
