### ISSUE TITLE
Detect tap on row for 

### ISSUE THREAD

**Issue by vadimux** [xmartlabs/Eureka#1354]
Is it possible to detect tapping on row? I have an issue related to this case, when user see list of countries, but he want to select first country (row) without scrolling of Picker (tap on first country). How to detect this?
`.onChange` is working when user is scrolling.
my code doesn't work for this case (tap on first row):
```swift
            <<< PickerInputRow<String>("List of countries") {
                    $0.noValueDisplayText = "Country"
                    $0.options = viewModel.arrayCountries
                    if  let currentCountry = viewModel.user.country {
                        $0.value = viewModel.displayNameFor(currentCountry)
                    }
                }
                .onChange { [weak self] row in
                    guard let weakSelf = self else { return }
                    if  let rowValue = row.value, let newCountryCode = weakSelf.viewModel.countryFromDisplayString(rowValue) {
                        weakSelf.viewModel.uploadUser.country = newCountryCode
                    }
                }
                .cellUpdate { cell, row in
                }

```
- Environment: Eureka 4.0.1, Xcode 9.2 and iOS 11.2 version.

**Comment by m-revetria** [comment]
Hi @vadimux, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-----------

That being said, that is the way UIPickerView works. It only notifies changes on the selected row through its delegate [UIPickerViewDelegate](https://developer.apple.com/documentation/uikit/uipickerviewdelegate).

As a workaround, you can add a first option to the country list to indicate no value was selected.

**Comment by m-revetria** [comment]
I'm closing this
