### ISSUE TITLE
How to change Status Bar Style of PushRow View Controller?

### ISSUE THREAD

**Issue by kbokdia** [xmartlabs/Eureka#1355]

**Comment by m-revetria** [comment]
Hi @kbokdia, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

--------------------

How to change status bar style? You'll need to subclass `SelectorViewController` and assign the row's `presentationMode` with the proper value. You can use the code bellow as a snippet:

```swift
class MyPushViewController: SelectorViewController<SelectorRow<PushSelectorCell<String>>> {
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
}

// Within your form view controller
section <<< PushRow<String>() {
    // Your configuration
    $0.presentationMode = PresentationMode.show(
        controllerProvider: ControllerProvider.callback(builder: { return MyPushViewController() }),
        onDismiss: { vc in let _ = vc.navigationController?.popViewController(animated: true) }
    )
}
```

> Take into account you need to override `preferredStatusBarStyle` in your custom `UINavigationController` to make previous code works. Next may help:

```swift
class MyNavigationController: UINavigationController {
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return topViewController?.preferredStatusBarStyle ?? .default
    }
}
```

**Comment by kbokdia** [comment]
On creating class gives error "Generic type 'SelectorRow' specialized with too few type parameters (got 1, but expected 2)"

class MyPushViewController: SelectorViewController<SelectorRow<PushSelectorCell<String>>> {
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
}

I am using eureka swift 3.2 branch.
And sorry for missing the guidelines. Will make a note of that.
