### ISSUE TITLE
Customizations on DateRow

### ISSUE THREAD

**Issue by cesaredecal** [xmartlabs/Eureka#1358]
I have my own date picker for the date row (orange pop up in the picture below). How do I stop the date picker of the Date Row from appearing?

<img width="536" alt="screen shot 2017-12-18 at 6 31 58 pm 1" src="https://user-images.githubusercontent.com/10504710/34119303-f0dc471a-e421-11e7-93f2-d6d62e0bb58a.png">

**Comment by simonbromberg** [comment]
Did you come up with any solutions yet? Trying to do something similar. 
The built-in functionality of a DateRow is useful so you don't have to worry about formatting the date value, plus it is convenient to use `noValueDisplayText` when the date is nil.
I'm thinking though it would either have to be a `LabelCell` with a detail label (and you'd have to handle the formatting and the no value) or a whole custom row; Would be nice to use `DateCell` or something similar as the cell type, but not sure how one would load its interface for the cellProvider…

**Comment by CeceXX** [comment]
@simonbromberg exactly, it's very convenient for the exact reasons you listed. yeah, I've commented out the date picker component from the code (temporary workaround), but a little toolbar at the bottom to navigate between rows of the form (something like this " < .... > ") still appears. Please let me know if you find any solution 👍

**Comment by simonbromberg** [comment]
Well, maybe the toolbar wouldn't show up if you did the same thing but
using the DateInlineRow?

**Comment by CeceXX** [comment]
@simonbromberg thank you, yes! That works well. I've just commented out the `expandInlineRow` method. Not the best way to fix this long-term but hey, it works.

**Comment by simonbromberg** [comment]
#158 related

**Comment by simonbromberg** [comment]
Wound up just creating a custom row, which required a custom cell as well. For increased simplicity one could subclass `DateCell` directly and just return false for `canBecomeFirstResponder` and `nil` for `inputView` but then the instance has all those date picker methods / properties you don't need. The `CustomDateRow` does force you to repeat some of the setup code for the formatter and display value, but at least then you have direct control over it.

```
final class CustomDateRow: Row<CustomDateCell>, RowType, NoValueDisplayTextConformance {
    open var noValueDisplayText: String? = nil
    open var dateFormatter: DateFormatter?
    
    required init(tag: String?) {
        super.init(tag: tag)
        dateFormatter = DateFormatter()
        dateFormatter?.timeStyle = .none
        dateFormatter?.dateStyle = .medium
        dateFormatter?.locale = Locale.current
        
        displayValueFor = { [unowned self] value in
            guard let val = value, let formatter = self.dateFormatter else { return nil }
            return formatter.string(from: val)
        }
    }
}

open class CustomDateCell: Cell<Date>, CellType {
    
    open override func setup() {
        super.setup()
        accessoryType = .none
        editingAccessoryType =  .none
    }
    
    open override func update() {
        super.update()
        selectionStyle = row.isDisabled ? .none : .default
    }
    
    open override func didSelect() {
        super.didSelect()
        row.deselect()
    }
    
    override open var inputView: UIView? {
        return nil
    }
    
    open override func cellCanBecomeFirstResponder() -> Bool {
        return false
    }
}
```

**Comment by CeceXX** [comment]
amazing, thank you, Simon!

**Comment by simonbromberg** [comment]
You're welcome.

I would argue it's still worth keeping this issue open. It may be worthwhile to allow opting out of the default picker functionality of the `DateRow` so you don't have to resort to this.

**Comment by mtnbarreto** [comment]
Hi @cesaredecal ! this date row should be implementing by creating a custom row. It will share a lot of code with date row but such level of UI customization is allowed by implementing custom rows. 
> There is no difference between native and custom rows, we just call custom rows to these rows that are not included in eureka library by default. 

Check custom rows implemented by the community here: https://github.com/EurekaCommunity
I would also recommend you to read all related [issues](https://github.com/xmartlabs/Eureka/labels/custom%20row).
If you want to share a custom row i can invite you to EurekaCommunity github organization.
