### ISSUE TITLE
Adding rules to MultivaluedSection

### ISSUE THREAD

**Issue by calli23** [xmartlabs/Eureka#1362]
Is it possible to add rules to a whole MultivaluedSections?

My intention is to count the number of DateRows added in a MultivaluedSection and check if there is at least one DateRow in that section to enable a save button.

One way could be to overwrite methods like rowsHaveBeenAdded and rowsHaveBeenRemoved.

However, the easiest way would be to add RuleRequired to the whole section if possible.

**Comment by m-revetria** [comment]
Hi @calli23, right now there is no way to add rules to an entire section even if it is a `MultivaluedSection`.

You can try next approach:

1. Add a disable rule to your "save" button to check if there is any value already added to the multivalued section.
   ```swift
   +++ Section("save")
     <<< ButtonRow("save") { [weak self] in
         $0.title = "Save"
         $0.disabled = Condition.function([]) { form in
             let section = form.sectionBy(tag: "textfields") as! MultivaluedSection
             return section.values().isEmpty
         }
     }
   ```

2. Change how rows are added to the section, implement `onChange` callback to re-evaluate the save button's disable condition
   ```swift
   form +++
   MultivaluedSection(multivaluedOptions: [.Reorder, .Insert, .Delete],
                      header: "Multivalued TextField",
                      footer: ".Insert multivaluedOption adds the 'Add New Tag' button row as last cell.") {
     // Section settings
     $0.multivaluedRowToInsertAt = { index in
         return NameRow() {
             $0.placeholder = "Tag Name"
         }.onChange { [weak self] _ in
             // Re-evaluate save button's disabled condition
             self?.form.rowBy(tag: "save")?.evaluateDisabled()
         }
      }
   }
   ```

3. Override `rowsHaveBeenAdded` and `rowsHaveBeenRemoved` to re-evaluate save button's disable condition.
   ```swift
   override func rowsHaveBeenAdded(_ rows: [BaseRow], at indexes: [IndexPath]) {
       super.rowsHaveBeenAdded(rows, at: indexes)
       // For the moment, we need to use `async` due to this function is called before the multivalued
       // section's `values` property is updated.
       DispatchQueue.main.async { [weak self] in
           self?.form.rowBy(tag: "save")?.evaluateDisabled()
       }
   }
   
   override func rowsHaveBeenRemoved(_ rows: [BaseRow], at indexes: [IndexPath]) {
       super.rowsHaveBeenRemoved(rows, at: indexes)
       // For the moment, we need to use `async` due to this function is called before the multivalued
       // section's `values` property is updated.
       DispatchQueue.main.async { [weak self] in
           self?.form.rowBy(tag: "save")?.evaluateDisabled()
       }
   }
   ```

> Note: I've used the example provided as base code for this, check on the ViewController.swift class if you need more context.

**Comment by m-revetria** [comment]
Hi @calli23, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

**Comment by m-revetria** [comment]
I'm closing this

**Comment by aluco100** [comment]
Hi there,

I put this and works:

```
            $0.cell.layoutMargins = .zero
            $0.cell.separatorInset = .zero
            $0.cell.preservesSuperviewLayoutMargins = false
            $0.cell.contentView.layoutMargins.left = 8.0
```

Happy coding
