### ISSUE TITLE
sectionKeyForValue for a MultipleSelectorRo always return the same value.

### ISSUE THREAD

**Issue by Ferannor** [xmartlabs/Eureka#1363]
When you want to use the block sectionKeyForValue for a MultipleSelectorRow the variable option of the block is always the first value of the option array. The problem appear each time and is present in the example project. (Rows > SectionedMultipleSelectorRow).

**Comment by dangthaison91** [comment]
@Ferannor I think PR #1333 will fix this issue.

**Comment by mtnbarreto** [comment]
We've already merged #1333 .
