### ISSUE TITLE
Why disabled button still recieve onCellSelection event?

### ISSUE THREAD

**Issue by Eric0625** [xmartlabs/Eureka#1368]
It's xCode 9.2, (9C40b), Eureka (4.0.1)
I set `buttonRow.disabled = true`
The display style is corretly disabled, but when I tap the row, it still triggers onCellSelection event.

**Comment by mtnbarreto** [comment]
Hi @Eric0625 ! 

`onCellSelection` is called even if the row is disabled. 

use the following code to check if row is disabled..

```swift
 row.onCellSelection { cell, row in
         guard !row.isDisabled else { return }
         // your code
}
```

**Comment by mtnbarreto** [comment]
same as #284

**Comment by Andy0570** [comment]
I recommend adding this tip to the README to avoid confusing others.
