### ISSUE TITLE
How to get the precise height of the form?

### ISSUE THREAD

**Issue by Eric0625** [xmartlabs/Eureka#1369]
I want to get the height of the form, at first I used like view.frame.height, or tableView.fram.height, but they are all too long. So I have to use a fixed height to display it. How can I get the blue circle's height, so I can get rid of the background within the red circle?
![default](https://user-images.githubusercontent.com/18132007/34289743-e72e01ee-e72e-11e7-98fc-170bbbce3dd3.PNG)

**Comment by manjuhere** [comment]
If it's just a simple form as shown above, then after setting up the form you could just do this -

        var tHeight:CGFloat = 0.0
        for row in form.allRows {
            if row.isHidden == false {
                tHeight += row.baseCell.frame.size.height
            }
        }
        print(tHeight)

But when you update the form rows (like hide/show) I guess, you would call the same code above in 
`tableView: willDisplay cell: forRowAt indexPath:` delegate method of tableview

**Comment by mtnbarreto** [comment]
Closing the issue due to the lack of response.
