### ISSUE TITLE
Populate Eureka elements with Json from Alamofire

### ISSUE THREAD

**Issue by peter369** [xmartlabs/Eureka#1370]
Hello, I want to populate the PickerInputRow with an array that I receive converted from JSON using Alamofire, but I can't use it to fill options in Picker in Eureka.

```swift
  <<< PickerInputRow<String>("Fabricante"){
                $0.title = "Fabricante"
            
                var fabricantes = [String]()
                obtenerFabricantes(resultado: {
                    resultado in
                    
                    fabricantes = resultado
                    print("el valor es \(fabricantes)")
                    
                    $0.options = self.fabricantes //THIS FAILS: Anonymous closure arguments cannot be used inside a closure that has explicit arguments; did you mean 'resultado'?, Replace '$0' with 'resultado', Value of type '[String]' has no member 'options'

                })
               
                $0.value = $0.options.first
            }
  ```

**Comment by manjuhere** [comment]
within the network closure you have an explicit argument (`resultado`) hence you can't use an anonymous argument (`$0`). so its better you explicitly define your row in the outer closure -

            <<< PickerInputRow<String>("Fabricante"){ row in
                row.title = "Fabricante"

                obtenerFabricantes(resultado: {resultado in
                    
                    var fabricantes = [String]()
                    fabricantes = resultado
                    print("el valor es \(fabricantes)")
                    
                    row.options = self.fabricantes
                    row.value = row.options.first
                    row.reload()

                })
            }

also, you will set the row value when you have values for the row. Since you get the values in the network closure, set the value of the row in that particular closure and then reload the row.

**Comment by m-revetria** [comment]
Hi @peter369, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

@manjuhere's response is the correct answer, thanks!
