### ISSUE TITLE
expandability thinking

### ISSUE THREAD

**Issue by kaich** [xmartlabs/Eureka#1371]
I want to use Eureka. But I find it's not well expandability. So many Row extend `BaseCell`. And you use the default property of UITableViewCell. eg: `textLabel`. When I have same property. But I want to custom cell appearance only through xib file. I can't implement it with bind property to xib. So I think. The basic cell can use a cell extend `UITableViewCell`, Add subview to the cell and bind it to property rather than use `textLabel`. 

It's my thought. Do anyone have other good idea? Wish your replay!

**Comment by MaG21** [comment]
I believe the trouble it's bigger than the advantage you gain by using Eureka. It might be better if you don't use Eureka at all. If possible, consider programming this logic by yourself.
