### ISSUE TITLE
Incorrect example in Readme with Row<Date> type

### ISSUE THREAD

**Issue by simonbromberg** [xmartlabs/Eureka#1374]
In the Readme currently, in the FAQ section, "How to get a Row using its tag value" there is the following line:

    let dateRow2: Row<Date>? = form.rowBy(tag: "dateRowTag")

But if you copy that into a `FormViewController` subclass, you get the following compiler error:

> 'Row' requires that 'Date' inherit from 'BaseCell'

Not quite sure what was intended here, or perhaps it is just outdated?

Possibly supposed to say `Row<DateCell>` although would still need an `as? Row<DateCell>` at the end of the line then.

**Comment by m-revetria** [comment]
Hi @simonbromberg thanks for pointing out the error on the documentation. It should say

```swift
let dateRow2: DateRow? = form.rowBy(tag: "dateRowTag")
```

> Notice you don't need to cast `form.rowBy(tag: string)`'s result
