### ISSUE TITLE
Method signature for valueHasBeenChanged(for: …) missing separate parameter name

### ISSUE THREAD

**Issue by simonbromberg** [xmartlabs/Eureka#1375]
In the `FormViewController` / `FormViewControllerDelegate` the first parameter, by default, of `valueHasBeenChanged(for: BaseRow, oldValue: Any?, newValue: Any?)` is `for` which obviously conflicts with the for loop syntax.

You can of course add a parameter name yourself when you implement it, so that `for` becomes the argument label, but it ought to be included in the signature by default so that when you autocomplete it's already good to go.

Based on Swift conventions I would suggest changing this `for` to `forRow` and adding a parameter name `row` or something similar so it looks like this:

`valueHasBeenChanged(forRow row: BaseRow, oldValue: Any?, newValue: Any?)`

**Comment by m-revetria** [comment]
Hi @simonbromberg thanks for the suggestion, we'll review `FormDelegate` definition and come back to you.

Meanwhile you can override that function adding a label for the variable name:

```swift
class MyFormController: FormController {
    override func valueHasBeenChanged(for row: BaseRow, oldValue: Any?, newValue: Any?) {
        super.valueHasBeenChanged(for: row, oldValue: oldValue, newValue: newValue)
        // Your stuff
    }
}
```

**Comment by simonbromberg** [comment]
Why did you close it? Either this or #1308 should remain open until it is fixed — and it is a very easy fix.

**Comment by mtnbarreto** [comment]
Hi @simonbromberg ! I think we should not change the method signature because it's a breaking change and we can also rename its parameter like @m-revetria explains, which is the approach we use when implementing/overriding this method to avoid `for` key reserved key.  

If i'm missing something let me know

**Comment by simonbromberg** [comment]
That's not really a reason not to fix it.
