### ISSUE TITLE
SectionedPushRow order is alphabetical rather than order added

### ISSUE THREAD

**Issue by cerupcat** [xmartlabs/Eureka#1377]
When creating a SectionedPushRow, the order of each section is by section title rather than the order of the array. Is there a way to change this?

**Comment by mtnbarreto** [comment]
As you said, currently the order of the section is determined by section title as the following snippets show..

https://github.com/xmartlabs/Eureka/blob/0895eccb3fbbdc31ff881c90d3d1f21a8ed4b05e/Source/Rows/Controllers/SelectorViewController.swift#L188

and 

https://github.com/xmartlabs/Eureka/blob/0895eccb3fbbdc31ff881c90d3d1f21a8ed4b05e/Source/Rows/Controllers/MultipleSelectorViewController.swift#L106

in case of multiple selector


> I'm open to consider a pull request that adds the ability to sort the sections differently if it maintains the current behavior by default.

**Comment by mtnbarreto** [comment]
Hi @cerupcat !

According Eureka readme https://github.com/xmartlabs/Eureka#grouping-options-in-sections , now we can use `sectionHeaderTitleForKey` and `sectionFooterTitleForKey`.

Sections are sorted by sectionKey which is set up by implementing `sectionKeyForValue `,  then by using `sectionHeaderTitleForKey` you can change the section title for a particular key. 

So we should not return the section title in `sectionKeyForValue` if the section list order we want doesn't match with its alphabetical order.
