### ISSUE TITLE
ZipCode Keyboard: Not .NumbersAndPunctuation?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#138]
Dear xmartlabs

Shouldn't the ZipCodeRow use a .NumbersAndPunctuation Keyboard?

At least this was what I expected, and as it doesn't I can't see the purpose comparing it to a TextRow?

**Comment by marbetschar** [comment]
?

**Comment by mtnbarreto** [comment]
@marbetschar thanks for the suggestion.

**Comment by marbetschar** [comment]
Thanks for the fix!!
