### ISSUE TITLE
How to handle long text in the options for a PickerInputRow

### ISSUE THREAD

**Issue by dote** [xmartlabs/Eureka#1380]
Hi I am using a pickerinputrow. The options are rather long so if the option selected is rendered in the same row as the label, it won't fit. Is there a way to make the selected option font smaller and appear on a new line BELOW the label?

Here you can see the long text doesn't fit so you can't really see what option you've chosen.
![form](https://user-images.githubusercontent.com/396101/34849921-0fdf11b6-f6c8-11e7-83fa-239e2e9fcbc9.jpg)

**Comment by dote** [comment]
OMG figured out a solution that works for me, $0.cellStyle = UITableViewCellStyle.subtitle.

**Comment by m-revetria** [comment]
Hi @dote nice you found a solution. I'm closing this issue as the shared approach is fine.

Thanks

**Comment by iadwait** [comment]
@tapiki  Thanks a lot for the solution !!
