### ISSUE TITLE
Implementing a form not in a FormViewController

### ISSUE THREAD

**Issue by aliparr-** [xmartlabs/Eureka#1381]
I'd like to be able to use a Eureka form inside of a UICollectionViewCell. It's not clear to me how to implement a form without inheriting from FormViewController, which is not possible in this case.

Can anyone please provide some guidance, or point me to somewhere that might hint at how this can be done? 

The readme states: "You could create a form by just setting up the form property by yourself without extending from FormViewController but this method is typically more convenient." - but when it's not clear how that's done.

**Comment by m-revetria** [comment]
Hi @aliparr-, I'm closing this issue as it duplicates #1323.
