### ISSUE TITLE
Internacionalization

### ISSUE THREAD

**Issue by vortek** [xmartlabs/Eureka#1382]
Hello, How do I translate the "Done" button on the keyboard toolbar?
Thanks you.

**Comment by m-revetria** [comment]
Hi @vortek, thanks for using Eureka!

As it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-----------

That being said, the system done button is used there, it has native translation support. It will be translated to all the languages your app supports.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
