### ISSUE TITLE
Compiler error for _ListCheckRow

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#1383]
I'm not quite sure where to post this, because it's more a programming than a usage question. And as I looked at the [StackOverflow activity of this topic](https://stackoverflow.com/questions/48261972/compiler-error-for-custom-listcheckrow), I felt like it may be better to post here too. Feel free to close if unappropriate:

I'm trying to create a custom row for Eureka forms. For this I'd like to customize the way a ListCheckCell looks like.

In order to achieve this goal I plan to use a generic `_ListCheckRow` in my code in order to allow developers to subclass it and throw a different styled one to my code.

Unfortunately the Swift compiler complains. I'm especially interested in why it complains that `Cell` does not inherit from` ListCheckCell`...?

`Col 12: type 'EditorViewController' does not conform to protocol 'TypedEditorViewController' Unable to infer associated type 'RowCell' for protocol 'TypedEditorViewController' (line 21, col 17) Inferred type 'Cell' (by matching requirement 'checkRow') is invalid: does not inherit from 'ListCheckCell' (line 25, col 13)`

The following snippet throws the error:

```
protocol TypedEditorViewController{
    associatedtype RowValue
    associatedtype RowCell: ListCheckCell<RowValue>
    var checkRow: _ListCheckRow<RowValue,RowCell>!{ get set }
}
open class EditorViewController<T, Cell: ListCheckCell<T>>: TypedEditorViewController  {
    public var checkRow: _ListCheckRow<T,Cell>!
}
```

And here's the full code which does not want to compile. Any help is greaty appreciated. Please note this is code is simplified code for evaluating this scenario.

```
open class RowOf<T> where T: Equatable{}
public protocol TypedCellType {
    associatedtype Value: Equatable
    var row: RowOf<Value>! { get set }
}
public protocol CellType: TypedCellType {}
open class Cell<T>: TypedCellType where T: Equatable {
    public typealias Value = T
    public weak var row: RowOf<T>!
}
open class Row<Cell: CellType>: RowOf<Cell.Value>{}
open class ListCheckCell<T: Equatable> : Cell<T>, CellType {}

open class _ListCheckRow<T, Cell: ListCheckCell<T>>: Row<Cell> {
    public var selectableValue: T?
}

protocol TypedEditorViewController{
    associatedtype RowValue
    associatedtype RowCell: ListCheckCell<RowValue>
    var checkRow: _ListCheckRow<RowValue,RowCell>!{ get set }
}
open class EditorViewController<T, Cell: ListCheckCell<T>>: TypedEditorViewController  {
    public var checkRow: _ListCheckRow<T,Cell>!
}
```

**Comment by mtnbarreto** [comment]
Hey @marbetschar , Have you solved this?

**Comment by marbetschar** [comment]
@mtnbarreto not solved; but found a solution which works - that said, we can close this issue.
