### ISSUE TITLE
Version for Xcode 9.2 Swift 3.2?

### ISSUE THREAD

**Issue by TofPlay** [xmartlabs/Eureka#1386]
Hi, I'm stuck with a old project with CocoaPods and Swift 3.2  😥
Do you have a version of your component compatible with Swift 3.2?

**Comment by mtnbarreto** [comment]
https://github.com/xmartlabs/Eureka/tree/feature/Xcode9-Swift3_2

**Comment by TofPlay** [comment]
Thanks @mtnbarreto :-)

**Comment by TofPlay** [comment]
Is it possible to create a tag like `3.2`?
I use your component on my own pod and on the podspec I can not specify a branch just a tag

**Comment by the** [comment]
It seems the `Xcode9-Swift3_2` got deleted. It would be nice if you could restore it again as it breaks re-building old versions of applications.
