### ISSUE TITLE
track changes in all values of form

### ISSUE THREAD

**Issue by arakweker** [xmartlabs/Eureka#1388]
In my use case I present a form so the user can edit the values. Most of the time nothing changes and the user taps back. Then I still ask if the user wants to save (although nothing changed). Is there a Eureka function / variable or anything else I can make use of to track those changes? Or is it my own housekeeping? (in which case I declare a Bool and have to set it in each row?).

**Comment by mtnbarreto** [comment]
You can get the form values when the user want to get back to previous screen and then compare these values with form default values, if there is any change you will have to show the dialog asking to save the new data.

> https://github.com/xmartlabs/Eureka#getting-row-values
