### ISSUE TITLE
Cell label's tint customization

### ISSUE THREAD

**Issue by tylyo** [xmartlabs/Eureka#1389]
I was trying to apply some graphics customization using the UIControl.appearance protocol in order to change the **default** text color of a row.

what I tried with no result:

- UILabel.appearance(whenContainedInInstancesOf: [UITableViewCell.self]).textColor = tintColor
- UILabel.appearance(whenContainedInInstancesOf: [BaseCell.self]).textColor = tintColor
- UILabel.appearance(whenContainedInInstancesOf: [BaseCell.self]).tintColor = tintColor

```swift
 LabelRow.defaultCellSetup = { cell, row in
            cell.textLabel?.textColor = APColor.defaultTint
            cell.backgroundColor = UIColor.clear
        }
        TextRow.defaultCellSetup = { cell, row in
                cell.textLabel?.textColor = APColor.defaultTint
                cell.textLabel?.tintColor = APColor.defaultTint
                cell.tintColor = APColor.defaultTint
                cell.textField?.tintColor = APColor.defaultTint
                cell.textField?.textColor = APColor.defaultTint
            cell.backgroundColor = UIColor.clear
        }
        EmailRow.defaultCellSetup = { cell, row in
            cell.textLabel?.tintColor = APColor.defaultTint
            cell.backgroundColor = UIColor.clear
        } 
```

where APColor.defaultTint = .yellow

how can I achieve the result to change the UILabel's tint

**Comment by mtnbarreto** [comment]
text color is updated each time the row is rendered which means each time `cellForRowAtIndexPath is invoked` as https://github.com/xmartlabs/Eureka/blob/ba0c7975552a2b4154dadcd5419ddaaa6c3be6ba/Source/Rows/Common/FieldRow.swift#L226 shows 

If you want to set up new colors to `TextRow` 's you will have to set up defaultCellUpdate for every the row types you want to change it. 

```swift
TextRow.defaultCellUpdate = { cell, row in
      textField.textColor = row.isDisabled ? .gray : .yellow
} 
```
