### ISSUE TITLE
Dynamic rows in section

### ISSUE THREAD

**Issue by gchimera** [xmartlabs/Eureka#1390]
Hello,
Is it possible create dynamic rows using class and objects? 
I mean something like this: func addRow(title: String, type: RowType) { ... }

to be called as:  
addRow("ListToDo", MultipleSelectorRow) { ... }

Many thanks in advance!

**Comment by mtnbarreto** [comment]
Hi @gchimera  could you please elaborate more on this?

**Comment by gchimera** [comment]
Hi, sure! 
I'm going to create a custom row similar to 'MultivaluedSection' with .xib
I don't know how adding a row dynamically when a button inside the row is pressed.

**Comment by mtnbarreto** [comment]
Hi @gchimera , 
The way to add new rows to the form is explained in the readme.
Doesn't mind if the form is already displayed or not, the way to add new rows is the same.
