### ISSUE TITLE
Cannot assign value of type 'Bool' to type 'Condition?'

### ISSUE THREAD

**Issue by hstdt** [xmartlabs/Eureka#1393]
Maybe an error of swift. Xcode9.1 , swift 4

![image](https://user-images.githubusercontent.com/10215098/35432186-3940ab48-02ba-11e8-87b0-8532f965f79f.png)

**Comment by mtnbarreto** [comment]
Hi! you can only assign boolean literals. 

You can also use:

```swift
let disabled = true
row.disabled = Condition(booleanLiteral: disabled)
```

**Comment by hstdt** [comment]
@mtnbarreto Nice! Thank you!
