### ISSUE TITLE
How to create a section in Multivalued Sections?

### ISSUE THREAD

**Issue by MorningStarJ** [xmartlabs/Eureka#1394]

**Comment by m-revetria** [comment]
Hi @MorningStarJ, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

That being said, a multivalued section is a section itself. So, you can add any number of multivalued sections in the same form. Please refer to the doc for more info about how to use multivalued sections: https://github.com/xmartlabs/Eureka#multivalued-sections.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
