### ISSUE TITLE
Totally custom Accessory View

### ISSUE THREAD

**Issue by falcon283** [xmartlabs/Eureka#1395]
Due to inputAccessoryView is a `UIView?` on `UIResponder`, would be great to have a `navigationAccessoryView` to be any kind of view instead of just a `UIToolbar`. 
This can be easily achieved using callbacks. When the developer provide the Custom View, the Core will inject the functions, while the callbacks are invoked by the custom implementation when the user interact with the custom view.

I would be happy to provide you a PR as soon as I can.

**Comment by falcon283** [comment]
Here my pull request #1397

**Comment by mats-claassen** [comment]
Merged PR
