### ISSUE TITLE
Would it be possible to subclass an ImageRow?

### ISSUE THREAD

**Issue by CeceXX** [xmartlabs/Eureka#1396]
If so, how? I want to use the built-in functionality of [ImageRow](https://github.com/EurekaCommunity/ImageRow)s but I find it really confusing somehow. I've already read the two blog posts which teach how to create a custom row. What I want to know how to do is subclassing a row. 

We've already talked about this [here](https://github.com/xmartlabs/Eureka/issues/734).

This is my code for reference: 

    import UIKit
    import Eureka
    
    public class LogoSubscriptionCell: Cell<Bool>, CellType {
        var logoImageView: UIImageView = {
            let logoImageView = UIImageView()
            logoImageView.translatesAutoresizingMaskIntoConstraints = false
            logoImageView.contentMode = .scaleAspectFit
            logoImageView.layer.masksToBounds = true
            logoImageView.layer.cornerRadius = 10
            return logoImageView
        }()
        
        public override func setup() {
            super.setup()
            backgroundColor = .white
            addSubview(logoImageView)
            logoImageView.centerYAnchor.constraint(equalTo: centerYAnchor).isActive = true
            logoImageView.centerXAnchor.constraint(equalTo: centerXAnchor).isActive = true
            logoImageView.widthAnchor.constraint(equalToConstant: 146).isActive = true
            logoImageView.heightAnchor.constraint(equalToConstant: 146).isActive = true
        }
    }
    
    // The custom Row also has the cell: DetailSubscriptionCell and its correspond value
    public final class LogoCustomRow: Row<LogoSubscriptionCell>, RowType {
        required public init(tag: String?) {
            super.init(tag: tag)
        }
    }

**Comment by mats-claassen** [comment]
You can do it like this to use the logic from `_ImageRow`.
```
/// A selector row where the user can pick an image
public final class MyImageRow: _ImageRow<LogoSuscriptionCell>, RowType {
  public required init(tag: String?) {
    super.init(tag: tag)
  }
}
```

**Comment by CeceXX** [comment]
thanks!
