### ISSUE TITLE
Dropdown with textarea

### ISSUE THREAD

**Issue by sundeepios** [xmartlabs/Eureka#1398]
Would it possible to give dropdown with textarea, so that user can enter values other that dropdown values

**Comment by mats-claassen** [comment]
This would be a custom row. You can have a look at the blogposts [part one](https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/) and [part two](https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/). The Readme can also be helpful.
