### ISSUE TITLE
EditActions no longer available for FormViewController without swipe

### ISSUE THREAD

**Issue by OskarGroth** [xmartlabs/Eureka#1399]
In Eureka 4.0.1, `FormViewController` now implements:

	public func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?{
		return form[indexPath].trailingSwipe.contextualActions as? [UITableViewRowAction]
	}

Which only looks for `SwipeActions`.

As a result, our cells placed in a `MultivaluedSection` with `multivaluedOptions: [.Delete]`, but with no swipe actions (because we have an Edit button), no longer displays the edit action item:

![card](https://user-images.githubusercontent.com/1417019/35569776-5e300316-05cd-11e8-9700-626c8de27ed5.gif)

Since the function is `public`, it can not be overridden. As a result, functionality is broken.

Please consider making this function `open` or refactoring the behaviour. It should be possible to edit items in other ways than swiping.

**Comment by OskarGroth** [comment]
![skarmavbild 2018-01-30 kl 17 31 54](https://user-images.githubusercontent.com/1417019/35578220-b87d0164-05e3-11e8-92d7-3da5e6e53337.png)

Issue also occurring in the Eureka Demo on master.

**Comment by mats-claassen** [comment]
@mtnbarreto This is fixed, right?

**Comment by mats-claassen** [comment]
Fixed in #1442

**Comment by mtnbarreto** [comment]
@mats-claassen @OskarGroth  It was already fixed.
