### ISSUE TITLE
Question: is there support for the state restoration

### ISSUE THREAD

**Issue by aptly-io** [xmartlabs/Eureka#1403]
I looked in the readme and current issues but do not find a hint whether there's 'automated' support for:
- `override func encodeRestorableState(with coder: NSCoder)` 
- `override func decodeRestorableState(with coder: NSCoder)`

It would be handy to have something like:
- `self.form.encodeRestorableState(with: NSCoder, key: "my-form-values")`
and its reverse:
- `self.form.decodeDecodable(with: NSCoder, key: "my-form-values")`

Thanks

**Comment by mats-claassen** [comment]
You have FormViewController's `values()` and  `setValues()` which should do what you want.

**Comment by mtnbarreto** [comment]
Hi @aptly-io  https://github.com/xmartlabs/Eureka#how-to-set-the-form-values-using-a-dictionary can also be helpful
