### ISSUE TITLE
Question: How to customize TokenRow?

### ISSUE THREAD

**Issue by thomasmbr** [xmartlabs/Eureka#1404]
Hello everyone, I need help. I'm trying to make my TokenTableRow (Email) look the same as the default TextRow (LastName). But I can not change it. I tried to change the color of the cell.textLabel! .textColor to UIColor.black both using the cellSetup call and cellUpdate, but got no result. Can anyone tell me how to do this?

![captura de tela 2018-02-05 as 22 23 54](https://user-images.githubusercontent.com/13890644/35836047-564540e2-0ac5-11e8-8098-74484b897150.png)

Note: I also need to align the text field to the right.
Thank you.

I'm using the TokenRow library: https://github.com/EurekaCommunity/TokenRow

**Comment by mats-claassen** [comment]
That issue should go in that repository.

You can set the title color through `cell.tokenView.fieldColor = .black` in `cellUpdate`
You can't change the tokenView's alignment as far as I know.

**Comment by thomasmbr** [comment]
Thank you very much. Sorry for asking the question in the wrong repository.
