### ISSUE TITLE
Status of 4.1 release

### ISSUE THREAD

**Issue by gplocke** [xmartlabs/Eureka#1413]
This isn't so much an issue as it is as question, but I wasn't sure how else to ask.  So I apologize if this is way off base.
#
But I was wondering what the status of a 4.1 release is?  Is there a planned date for that yet? I'm really interested in some the features that are in master, but I'd prefer to use an official release over my own fork and hadn't seen any indication that anything was heading towards a release and it's been a while since the last one.

**Comment by mtnbarreto** [comment]
Hi @gplocke! Probably we have a new release by the end of next week.

**Comment by gplocke** [comment]
Awesome! That’ll perfect. Thanks!

**Comment by zsxawerdu** [comment]
@mtnbarreto i freaking love you and the rest of the team.

**Comment by matiasvillaverde** [comment]
Is going to be this week the release 4.1? Thanks

**Comment by gplocke** [comment]
Hey @mtnbarreto, I was just wondering if there was any update on the progress of this?

Thanks!

**Comment by mtnbarreto** [comment]
Hi @gplocke,  Could you please try using https://github.com/xmartlabs/Eureka/tree/swift4.1 either in swift 4 or swift 4.1. It should work in both swift version. 
Let me know if it works.

**Comment by gplocke** [comment]
Yep, I can try to test it out sometime today and I'll post back.  Thanks!

**Comment by gplocke** [comment]
@mtnbarreto  Sorry it took so long.  I had a bunch of stuff I needed to do first.  But I've been using the swift4.1 branch for a couple of days now and it looks good to me so far!

**Comment by mtnbarreto** [comment]
We've finally released Eureka 4.1.0!  Check it out here: https://github.com/xmartlabs/Eureka/releases/tag/4.1.0 Sorry for the delay. 

@gplocke @matiasvillaverde @zsxawerdu
