### ISSUE TITLE
How to change the UI of TextRow, EmailRow etc?

### ISSUE THREAD

**Issue by SebastianBoldt** [xmartlabs/Eureka#1416]
Is it somehow possible to create custom text cells that use the underlying functionality of the standard textcell/row? I tried to find out an elegant way of doing so, but inside the documentation, there is just a tutorial about how to create you unique custom cell but not about how to modify already existing row types?

**Comment by mtnbarreto** [comment]
General customization section of https://blog.xmartlabs.com/2015/09/29/Introducing-Eureka-iOS-form-library-written-in-pure-Swift/ may help.
