### ISSUE TITLE
Example fails deleting an item in the multi value section

### ISSUE THREAD

**Issue by aptly-io** [xmartlabs/Eureka#1418]
Hello,

Eureka version tagged as 4.0.1 on xcode 9.2 and iOS 11.2

I want to use the multi valued sections and was checking the Example app. On both an simulator and real iPhone device I see 2 strange behaviours after opening the multi valued form "Only delete" 
1) The right navigation button item reads "Edit", while the editing mode seems active already active.

![screen shot 2018-02-14 at 07 27 37](https://user-images.githubusercontent.com/12727215/36190687-e11621f6-1159-11e8-9acc-ca2f752ce056.png)

2) Trying to delete an item, it slides halfway and is than stuck. It's not removed. One can no longer delete other items. The app is not completely unresponsive though (all other controls still react).

![screen shot 2018-02-14 at 07 27 59](https://user-images.githubusercontent.com/12727215/36190698-f44c606e-1159-11e8-994d-e2b3b548e733.png)

Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by aptly-io** [comment]
The "edit" mode issue seems also reported in #1410

**Comment by aptly-io** [comment]
These issues only appear in the simulator. I don't see the issue when running on a real device.

**Comment by mats-claassen** [comment]
Fixed in #1442
