### ISSUE TITLE
How to center the image into the center of the row on a buttonrow?

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1426]
<<< ButtonRow() {
                $0.title = ""
                }
                .cellSetup{ cell, row in
                    cell.imageView?.image = UIImage(data: self.ImageData! as Data)
                    cell.imageView?.frame = CGRect(x: cell.center, y: 0, width: 100, height: 100)
                    cell.height = ({return 130})
}
.frame doesn't seem to work.

**Comment by mats-claassen** [comment]
Changing UITableViewCell's imageView is not easy (https://stackoverflow.com/a/3131834/4708657)

I would go for a subclass in that case. Have a look at the readme or blogposts if you need help with that
