### ISSUE TITLE
Text alignment for TextRow()

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1427]
<<< TextRow(){ row in
                row.title = companyName
            
            }.cellSetup{ cell, row in
                cell.textLabel?.textAlignment = .center
            }.cellUpdate{ cell, row in
                cell.textLabel?.textAlignment = .center
        }

Neither of the above two formats centers the text.

**Comment by mats-claassen** [comment]
All the field rows (like TextRow) have constraints and use `titleLabel` instead of `textLabel`.
If the textAlignment doesn't do what you want you have to subclass _FieldCell and override `customConstraints`
