### ISSUE TITLE
TextRow() text color

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1428]
<<< TextRow(){ row in
                row.title = name
            }.cellSetup{ cell, row in
                cell.textLabel?.textColor = .white
                cell.textLabel?.tintColor = .white
                cell.tintColor = .white
            }
None of the solutions above change the text color

**Comment by mats-claassen** [comment]
Use `cell.titleLabel` and always change colors in `cellUpdate`, not `cellSetup`

**Comment by JesseNoBata** [comment]
Worked. Thanks
