### ISSUE TITLE
ERROR - Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

### ISSUE THREAD

**Issue by FrankDoersam** [xmartlabs/Eureka#1429]
Hello,

we get the following error:

IN Swift 4.0 / IOS 11.3...
<img width="370" alt="bildschirmfoto 2018-02-20 um 18 35 15" src="https://user-images.githubusercontent.com/16541879/36439326-d4f243b0-166c-11e8-9581-7e93aa98bf78.png">

Do you have a solution. In IOS 11.2 we could successful start the app :)

Best regards,
Frank Dörsam

**Comment by mats-claassen** [comment]
Yes, have a look at #1412

**Comment by FrankDoersam** [comment]
i have download the newest version of Xcode. 
I get the same error... 
Have you a Solution ?

Best regads
Frank

**Comment by FrankDoersam** [comment]
<img width="1308" alt="bildschirmfoto 2018-02-20 um 19 41 23" src="https://user-images.githubusercontent.com/16541879/36442439-122287b4-1676-11e8-80f9-7d5387e5f908.png">

**Comment by mats-claassen** [comment]
You have to use `swift4.1` branch. (https://github.com/xmartlabs/Eureka/issues/1412#issuecomment-366783517)

**Comment by pvikrant** [comment]
<img width="743" alt="screen shot 2018-06-08 at 12 10 32 pm" src="https://user-images.githubusercontent.com/25882266/41142899-0c540490-6b15-11e8-9748-e10b6d0017d9.png">

I have same error like this 

Please reply me

**Comment by mats-claassen** [comment]
@pvikrant That is not an Eureka issue. Please ask for help in that library or on StackOverflow
