### ISSUE TITLE
Refresh button row image

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1434]
Unable to refresh button row image via user imagedatapicker. Seems you should be able to call .reloadData(), but this doesn't update the buttonrow image:

            <<< ButtonRow() {
                    $0.title = ""
                    $0.tag = "buttonRow1"
                }  .cellSetup{ cell, row in
                    cell.imageView?.image = UIImage(data: self.imageData! as Data)         
                }
            .onCellSelection { cell, row in
                    self.handleSelectPhoto()  // function to display imagePicker
                                                              // for photos; this part works
                    cell.imageView?.image = UIImage(data: self.imageData! as Data)
                    self.form.rowBy(tag: "buttonRow1")?.updateCell()
                    self.tableView.reloadData()
                }.cellUpdate{cell, row in
                    cell.imageView?.image = UIImage(data: self.imageData! as Data)
                    self.tableView.reloadData()
            }

The value for self.imageData is updated correctly, but the image on the buttonRow once call back is finished, doesn't get updated until selecting on the button row a 2nd time. Should update once done with .onCellSelection finishes? Have also tried refreshing tableView directly inside handleSelectPhoto(). Is there a callback portion I am missing where reload should be used?

Ideally, on returning to form from imagePicker, the button image should upload with the new image.

**Comment by mats-claassen** [comment]
I guess your `handleSelectPhoto` pushes the image picker which then returns asynchronously while the rest of the `onCellSelection` will execute immediately. You should update the image in the image picker callback

**Comment by mtnbarreto** [comment]
Closing the issue due to lack of response
