### ISSUE TITLE
validationErrors property not reset

### ISSUE THREAD

**Issue by MillerApps** [xmartlabs/Eureka#1435]
- Environment: Eureka: 4.0.1, Xcode: 9.2 and iOS: 10 for deployment target
- Issue: When navigating from segment to segment the previous segments errors persist.
 - Excepted behavior: Upon switching segments the validationErrors property should not persist.
 Code can be found here: https://github.com/TrustWallet/trust-wallet-ios/blob/master/Trust/Wallet/ViewControllers/ImportWalletViewController.swift#L86

**Comment by MillerApps** [comment]
@mtnbarreto could you shed some light on this? Thanks in advance!

**Comment by MillerApps** [comment]
Does anyone have any ideas?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mats-claassen** [comment]
What do you mean by segments?

**Comment by MillerApps** [comment]
@mats-claassen  I was referring to segmented rows. If you would like to a demo of the issue, let me know. Thanks!

**Comment by mats-claassen** [comment]
Yes it would be nice to have a small demo to show this issue

**Comment by MillerApps** [comment]
![3b4e7fc1-95eb-4b16-ba5c-dd89d2a5a5e7](https://user-images.githubusercontent.com/3836934/36845985-d2e04750-1d26-11e8-9ee2-b6add8432caa.gif)

**Comment by mats-claassen** [comment]
When you call `validate()` only the rows that are not hidden are validated.  The hidden row's validationErrors will stay the same. The error is showing them when the row is hidden. How are you displaying the validation errors?

**Comment by MillerApps** [comment]
I don't believe we actually handle displaying the errors on screen. I may be mistaken but it would appear Eureka handles this. 

```
  form
            +++ Section {
                var header = HeaderFooterView<InfoHeaderView>(.class)
                header.height = { 90 }
                header.onSetupView = { (view, section) -> Void in
                    view.label.attributedText = NSAttributedString(string: "Importing wallet as easy as creating", attributes: [
                        NSAttributedStringKey.font: UIFont.systemFont(ofSize: 14, weight: UIFont.Weight.regular),
                        NSAttributedStringKey.foregroundColor: UIColor(hex: "6e6e72"),
                        NSAttributedStringKey.paragraphStyle: self.pargraphStyle,
                        ])
                    view.logoImageView.image = R.image.create_wallet_import()
                }
                $0.header = header
            }

            <<< SegmentedRow<String>(Values.segment) {
                $0.options = [
                    //ImportSelectionType.mnemonic.title,
                    ImportSelectionType.keystore.title,
                    ImportSelectionType.privateKey.title,
                    ImportSelectionType.watch.title,
                ]
                $0.value = ImportSelectionType.keystore.title
            }

            <<< AppFormAppearance.textArea(tag: Values.mnemonic) {
                $0.placeholder = NSLocalizedString("Mnemonic", value: "Mnemonic", comment: "")
                $0.textAreaHeight = .fixed(cellHeight: 140)
                $0.add(rule: RuleRequired())

                $0.hidden = Eureka.Condition.function([Values.segment], { _ in
                    return self.segmentRow?.value != ImportSelectionType.mnemonic.title
                })
            }

            <<< AppFormAppearance.textArea(tag: Values.keystore) {
                $0.placeholder = NSLocalizedString("Keystore JSON", value: "Keystore JSON", comment: "")
                $0.textAreaHeight = .fixed(cellHeight: 140)
                $0.add(rule: RuleRequired())

                $0.hidden = Eureka.Condition.function([Values.segment], { _ in
                    return self.segmentRow?.value != ImportSelectionType.keystore.title
                })
            }

            <<< AppFormAppearance.textArea(tag: Values.privateKey) {
                $0.placeholder = NSLocalizedString("Private Key", value: "Private Key", comment: "")
                $0.textAreaHeight = .fixed(cellHeight: 140)
                $0.add(rule: RuleRequired())
                $0.add(rule: PrivateKeyRule())
                $0.hidden = Eureka.Condition.function([Values.segment], { _ in
                    return self.segmentRow?.value != ImportSelectionType.privateKey.title
                })
            }

            <<< AppFormAppearance.textFieldFloat(tag: Values.watch) {
                $0.add(rule: RuleRequired())
                $0.add(rule: EthereumAddressRule())
                $0.hidden = Eureka.Condition.function([Values.segment], { _ in
                 return self.segmentRow?.value != ImportSelectionType.watch.title
            })
            }.cellUpdate { cell, _ in
                cell.textField.placeholder = self.viewModel.watchAddressPlaceholder
                cell.textField.rightView = recipientRightView
                cell.textField.rightViewMode = .always
            }

            <<< AppFormAppearance.textFieldFloat(tag: Values.password) {
                $0.validationOptions = .validatesOnDemand
                $0.hidden = Eureka.Condition.function([Values.segment], { _ in
                    return self.segmentRow?.value != ImportSelectionType.keystore.title
                })
            }.cellUpdate { cell, _ in
                cell.textField.isSecureTextEntry = true
                cell.textField.textAlignment = .left
                cell.textField.placeholder = NSLocalizedString("Password", value: "Password", comment: "")
            }

            +++ Section("")

            <<< ButtonRow(NSLocalizedString("importWallet.import.button.title", value: "Import", comment: "")) {
                $0.title = $0.tag
            }.onCellSelection { [unowned self] _, _ in
                self.importWallet()
            }
    }

```

**Comment by mats-claassen** [comment]
You do here: https://github.com/TrustWallet/trust-wallet-ios/blob/06ed371b3ada690264a9f206320b6891e300ba74/Trust/UI/FormAppearance.swift#L60

**Comment by MillerApps** [comment]
Is there something special to do when using segment rows? That looks like how the validation is handled in the Eureka example project.

**Comment by mats-claassen** [comment]
There are many things you can do like adding a red border to the cell, changing the title color to red (if you have a title). The idea is just to catch the attention of the user so that he knows which row is not valid.

You can also go with adding a row like you are doing but you should then hide that row when the segment changes. Just use `hidden` in the validation row as well

**Comment by mats-claassen** [comment]
Try something like:

```
let labelRow = LabelRow {
           $0.title = validationMsg
           $0.cell.height = { 20 }
           $0.cell.textLabel?.textColor = .red  // BTW should be done in cellUpdate
           $0.hidden = "$segmentRow == whateverValue"  // <- Change the tag and value
   }

```

**Comment by MillerApps** [comment]
Unfortunately that doesn't seem to work. It hides the label on the current segmentedRow, not upon switching.

**Comment by MillerApps** [comment]
@mats-claassen any other ideas?

**Comment by mats-claassen** [comment]
Did you set the `hidden` property correctly? I don't know your tags and the values for the Segmented row but this should work:

`$0.hidden = "$<segmented_row_tag> != <my_segmented_row_value>"`

**Comment by MillerApps** [comment]
@mats-claassen The tag for the segmentedRow is always segment and the value is either Keystore, Private Key, or Watch. So I don't see how the above will work since it will always evaluate to true. 

Is this not the correct way to retrieve the segmentedRow? 

```
guard let segmentRow: SegmentedRow<String> = rowSection.form?.rowBy(tag: "segment"), let segmentValue = segmentRow.value else { return }
```

Thanks, again for the help, hopefully I'm just making a simple mistake!

**Comment by mats-claassen** [comment]
@MillerApps If you use the same `hidden` function for the validation error LabelRow than for the row it validates then it works. In my case something like:

```
$0.hidden = Condition.function(["my_segment"]) { form in
                            if let val = form.rowBy(tag: "my_segment")?.baseValue as? String {
                                return val != "One"
                            }
                            return false
                        }
```

**Comment by XiaoyuZheng666** [comment]
@mats-claassen it seems you didn't fix this problem, validationErrors not reset

**Comment by XiaoyuZheng666** [comment]
@MillerApps did you find the reason why validationErrors property not reset?

**Comment by MillerApps** [comment]
@XiaoyuZheng666 no. The above only works for exactly one segment. In my case my segmented row had four segments. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fukemy** [comment]
> https://github.com/TrustWallet/trust-wallet-ios/blob/06ed371b3ada690264a9f206320b6891e300ba74/Trust/UI/FormAppearance.swift#L60

how did u make tint color of segment? Thanks
