### ISSUE TITLE
Trouble formatting textfield / textview cells

### ISSUE THREAD

**Issue by grubbr** [xmartlabs/Eureka#144]
I am having difficulty formatting the font style (size/color) of `textfield` / `textview` cells in selected rows, namely `NameRow`, `TextRow`, `URLRow` and `TwitterRow`.

I have setup defaults and the form as follows:

```
func configForm() {
        
        let font = UIFont(name: Default.lighterFontName, size: 12)
        
        NameRow.defaultCellSetup = { cell, row in
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
        
        TextRow.defaultCellSetup = { cell, row in
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
        
        TextAreaRow.defaultCellSetup = { cell, row in
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
        
        URLRow.defaultCellSetup = { cell, row in
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
        
        TwitterRow.defaultCellSetup = { cell, row in
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
        
        form  +++
            
            Section() {
                $0.header?.height = { 15 }
            }
            
            <<< NameRow() {
                $0.title =  "Full Name"
                $0.value = user.name
            }
            
            <<< TextRow() {
                $0.title = "Town or City"
                $0.value = user.location
            }
            
            <<< PushRow<String>() {
                $0.title = "Country"
                $0.options = countries
                $0.value = user.country
                $0.selectorTitle = "Select a country"
                }
                .cellSetup({ (cell, row) -> () in
                    cell.textLabel?.font = font
                    cell.detailTextLabel?.font = font
                })
                .onPresent({ (FormViewController, SelectorViewController) -> () in
                    // TODO: Format the selector view
                })
            
            <<< URLRow() {
                $0.title = "Website"
                $0.placeholder = "http://"
                $0.value = NSURL(string: "\(user.website)")
            }
            
            <<< TwitterRow() {
                $0.title = "Twitter"
                $0.placeholder = "@"
                $0.value = user.twitter
            }
            
            +++
            
            Section("Describe yourself in 140 characters or less") {
                $0.header?.height = { 20 }
            }
            
            <<< TextAreaRow() {
                $0.value = user.about
                }
                .cellSetup({ (cell, row) -> () in
                    cell.textLabel?.font = font
                    cell.detailTextLabel?.font = font
                })
    
    }
```

And here is how the simulator renders this configuration:
![screen shot 2015-12-20 at 16 26 34](https://cloud.githubusercontent.com/assets/10615121/11918756/7dede2c4-a736-11e5-9d58-98e4f66b7bc2.png)

As you can see, the Name, City, Website, Twitter and TextArea textfields all ignore the `defaultCellSetup` configuration but the `cell.textLabel` is set correctly for each. My presumption was that the `cell.detailTextLabel` would govern the styling of this element but clearly it does not.

Oddly enough, the `PushRow` seems to work (bonus points if anyone can point out how to correctly style the selector view?).

![screen shot 2015-12-20 at 16 42 48](https://cloud.githubusercontent.com/assets/10615121/11918875/c457b904-a738-11e5-876a-fb23f02a71d9.png)

Seems like a straightforward task but somehow the obvious escapes me :-(

Any help, truly appreciated!

**Comment by grubbr** [comment]
OK managed to solve the first formatting issue with `cell.textField.font` which I hadn't seen documented anywhere previously.

If anyone can help on the second point (how to style the selector view from a `PushRow`) that would be appreciated.

**Comment by innoreq** [comment]
I have the same problem, trying to format the text using

```swift

		TextRow.defaultCellSetup = { cell, row in
			
			cell.backgroundColor = UIColor.yellowColor()
			cell.textField.textColor = UIColor.redColor()
			cell.detailTextLabel!.textColor = UIColor.brownColor()
		}
```

but except the cell.backgroundColor, all other settings are ignored. Any idea?

BTW: The Eureka lib is really great!

**Comment by innoreq** [comment]
After grooming this forum, I found the solution: not only define `.defaultCellSetup`, but also `.defaultCellUpdate` (as described here: [https://github.com/xmartlabs/Eureka/issues/110]).

Perhaps you should enhance the manual to point this out?

**Comment by mtnbarreto** [comment]
For the second drawback you faced, these issues provide the solution https://github.com/xmartlabs/Eureka/issues?q=is%3Aissue+selectableRowCellUpdate+is%3Aclosed

**Comment by davros1970** [comment]
Might be me, but I've found the TextRow.defaultCellSetup tips no longer work after updating to 2.0.1. Worked perfectly fine in previous versions. Now, the defaultCellSetup closure I provide is no longer invoked by Eureka.

I had been doing that setup in my FormViewController.viewDidLoad() before setting up the form itself.

`
FormViewController.viewDidLoad() {

    super.viewDidLoad()

    TextRow.defaultCellSetup = { cell, row in
        // Hey! Not being called in version 2.0.1!
    }

    form
    +++ Section (etc...)
    }
`

**Comment by RowanG1** [comment]
It seems to me that textfield is not used anymore for textarearow. This works for me: cell.textView.font
