### ISSUE TITLE
[Question] How to form.validate() without the side effect that each row has is isValid set to false?

### ISSUE THREAD

**Issue by aptly-io** [xmartlabs/Eureka#1440]
When I push an Eureka `Form`, it's rows are populated with the values from a struct's field. I disable the `Save` `UIBarButtonItem` as long as there are _invalid_ rows. Therefore I do a `form.validate()` whenever `valueHasBeenChanged()` is called; if there are no errors, the `Save` button is enabled.

In case a new (hence empty) struct is used to fill the form's rows, most row are invalid. Calling `form.validate()` has the side effect of changing each row's `validationErrors` property. Resulting in all row's title to be highlighted _red_. I'd like to prevent such pedantic colouring. (Each row's validationOption has a `.validatesOnBlur`)

Does someone know how to validate without this annoying side-effect?

Environment: Eureka from cocoa pods, Xcode 9.2 and iOS version 11.x.

**Comment by mats-claassen** [comment]
I suppose you are setting the forms titles to red somewhere checking for `isValid`. You could combine that `isValid` with `wasChanged` like `if !row.isValid && row.wasChanged `

**Comment by aptly-io** [comment]
@mats-claassen The answer I was looking for!
