### ISSUE TITLE
Row type for hue color

### ISSUE THREAD

**Issue by FrankDoersam** [xmartlabs/Eureka#1446]
type: feature request

new row type for hue color like this.
<img width="182" alt="bildschirmfoto 2018-03-01 um 18 39 19" src="https://user-images.githubusercontent.com/16541879/36859899-2486fd0c-1d80-11e8-8bb2-f234c1f8a340.png">

**Comment by alexanderkhitev** [comment]
@FrankDoersam you can create your own custom cell

**Comment by mtnbarreto** [comment]
Hi Frank! take a look at the relate issues tagged with `custom row` and `Eureka community` to see how to implement the custom row.
