### ISSUE TITLE
Help on Selecting/Deselecting all options in MultipleSelectorRow

### ISSUE THREAD

**Issue by kiwiswift** [xmartlabs/Eureka#1448]
I have a MultipleSelectorRow and I'm trying to implement a switchRow for selecting and deselecting all options, i.e. when I switch on the switchRow all options get selected and vice-versa. The cells are getting updated correctly with the checkmark accessory, however the MultipleSelectorRow value is not returning with the selected options.

The row value gets updated correctly when the options selected individually though (i.e. when selecting the rows one by one), it's only when I select and deselect through the switchRow that doesn't work as expected.

Here is my code:

```swift
        form +++ Section("Selection Rows")
            <<< MultipleSelectorRow<Products>("Shopping List"){
                $0.title = $0.tag
                $0.options = Products.cases.map{ $0 }
                $0.value = nil
                }.onPresent{ from, to in
                    to.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Done", style: .done, target: from, action: #selector(ViewController.buttonTapped))
                    to.sectionKeyForValue = { product in
                        return product.section
                    }
                    //Add Section and Row for selecting all options
                    to.form +++ SwitchRow{
                        $0.title = "Select all Fruits"
                        $0.value = false
                        }.onChange{ switchRow in
                            //When Select All row is tapped,
                            let selectAll = switchRow.value!
                            //Get all sections except the "Select All" section
                            let allSections = to.form.allSections.filter{ $0 != switchRow.section }
                            //Change all rows
                            allSections.forEach{ section in
                                section.forEach { selectableOptionRow in
                                    let option = (selectableOptionRow as! ListCheckRow<Products>)
                                    option.value = selectAll ? option.selectableValue : nil
                                    option.updateCell()
                                }
                            }
                    }
        }
```

Am I missing something?

My environment: Eureka 4.0.1, Xcode 9.2

**Comment by mats-claassen** [comment]
MultipleSelectorRow uses SelectableSection's in the view controller it presents. This view controller also has a reference to the MultipleSelectorRow (`self.row`). The sections use the `onSelectSelectableRow` callback to set the value of the MultipleSelectorRow. As you aren't selecting the rows, the value isn't being updated. You can do it manually inside your forEach loops.

The following code might help you:
https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Controllers/MultipleSelectorViewController.swift#L111-L118

**Comment by kiwiswift** [comment]
Thanks a lot @mats-claassen, that makes sense.

I've implemented a slightly different approach as the sections are being defined by sectionKeyForValue. So this is what I've done and it works:


```
 let multipleSelectorRow = from.form.rowBy(tag: "Shopping List") as! MultipleSelectorRow<Products>
 allSections.forEach{ section in
     section.forEach { selectableOptionRow in
         let option = (selectableOptionRow as! ListCheckRow<Products>)
         if selectAll{
             option.value = option.selectableValue
             multipleSelectorRow.value?.insert(option.selectableValue!)
         } else {
             option.value = nil
             multipleSelectorRow.value?.remove(option.selectableValue!)
         }
         option.updateCell()
     }
 }
```

**Comment by mats-claassen** [comment]
Did it work?

**Comment by kiwiswift** [comment]
Yes, it did work and I'm closing this issue.
