### ISSUE TITLE
Issues with XCode 9.3 beta 4 + Eureka 4.1.0

### ISSUE THREAD

**Issue by kamerc** [xmartlabs/Eureka#1449]
Prior to updating to Eureka 4.1.0, I was seeing the compile issue described [here](https://github.com/xmartlabs/Eureka/issues/1412). I was using 4.0.1 before I upgraded.

What I am seeing now with 4.1.0 is that several of my Eureka rows are acting like they are disabled. For example, on one of my existing tables, nothing happens if I click on any rows of type Action Sheet, Push Row, Inline Date. However the TextRow, TextAreaRow and SwitchRows are working perfectly fine. I do not have any logic related to disabling rows anywhere in my code.

This issue is reproducible on all devices running iOS 11.3 (simulators and the latest iPhones & iPads).

All Eureka rows still work perfectly on XCode 9.2 running 11.2.5. Also I have not been able to rep this in the Example project that is using Eureka 4.1.0.

I am still digging through my code trying to figure out what could be causing this behavior with certain row types. But in the meantime I wanted to check & see if anybody else was seeing this behavior. Also if anyone has any ideas as to what in the changes made on 2/28 for compatibility could have caused some table rows to act this way.

**Comment by kamerc** [comment]
Closing the ticket because I figured out what the issue was on my end. For some reason the value of the Table View Selection attribute in Storyboard was set to 'No Selection.' No idea why this didn't cause any impact in the previous version of Eureka and why certain fields continued to work regardless. Anyway, FYI that was the fix in case anyone else runs into this odd issue.

**Comment by mtnbarreto** [comment]
@kamerc thanks for taking the time to share what was causing the issue.

**Comment by lincolntran** [comment]
@kamerc How to you use 4.1.0?  I have pod 'Eureka' but it only pulls 4.0.1 , I tried pod '4.1.0' but it threw me the usual pod error.

**Comment by jwdawson** [comment]
This is my pod file and it pulls 4.1 just fine.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RPZForms' do
    pod 'Eureka'
end

**Comment by lincolntran** [comment]
That's what I have and the result is:  

Using Eureka (4.0.1)

**Comment by lincolntran** [comment]
I had to do a pod update first.   Thanks.

**Comment by ReissZ** [comment]
tried both:
pod 'Eureka', '~> 4.1.0' 
and 
pod 'Eureka'

still getting 
Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

Thanks!

**Comment by kamerc** [comment]
@ReissZ  did you run "pod update" and then try cleaning your XCode workspace?

**Comment by ReissZ** [comment]
@kamerc yes. Terminal says Using Eureka (4.1.1)
I used pod update, cleaned and restarted Xcode. Same error. Thanks!
