### ISSUE TITLE
Add a referencing outlet to the Eureka FormViewController

### ISSUE THREAD

**Issue by appfrancois** [xmartlabs/Eureka#145]
I have setup a UIViewController with Eureka. Everything works fine except on iPads devices on which it looks like this: http://imgur.com/gku7Jt0

To fix this issue, it looks like I have to setup a tableview inside (style grouped) and a referencing outlet to the FormViewController owned by the UIViewController. Then the same screen looks like this: http://imgur.com/Qjid3Oc

The issue is that I have no outlet option available in my project: http://imgur.com/fOxqzXE

How should I proceed? Use Eureka source like in the example instead of Eureka.framework?

**Comment by mats-claassen** [comment]
Hi @appfrancois , have you solved this?
Why are you using it inside a UIViewController and not a FormViewController (which is a UIViewController)

**Comment by mtnbarreto** [comment]
@appfrancois Check out this issue #295, could be related with yours.
