### ISSUE TITLE
integrating google maps in the cell itself?

### ISSUE THREAD

**Issue by lagagne72** [xmartlabs/Eureka#1450]
Hello, is it possible to integrate a google map inside a custom cell? 

I am aware of the LocationRow example but it displays a map in a separate view (only the coordinates are displayed in the cell) and I am unable to display the map in the cell itself.

I have also tried creating a custom cell with a GMSMapView inside it, but the location manager callback doesn't work from some reason. I think it is because the didUpdateLocations are @objc and are incompatible with the Cell class.

I also tried using a separate ViewController to handle the callbacks but didn't work either...

Any ideas? thanks!

**Comment by mats-claassen** [comment]
I don't think there should be problems with integrating a map inside a cell. There might be a problem with the callback setup but I can't say without your code.

Anyway this is a question better asked on StackOverflow.

**Comment by lagagne72** [comment]
Thanks for the reply. 

My code is super basic so I might as well post it here. I have a MapCell.xib with a single UIView called mainView. Then I use the code below. The map initialises at the correct location, but never updates afterwards. The callback functions require @nonobjc otherwise swift won’t compile. I'm kinda suspecting that's the issue.

```
//
//  MapCell.swift
//

import Foundation
import Eureka
import GoogleMaps

final class MapCell: Cell<MapInfo>, CellType, GMSMapViewDelegate {

  //MARK: Vars
  @IBOutlet var mainView: UIView!
  var _mapView = GMSMapView()
  private  var _locationManager = CLLocationManager()

  //MARK: Init
  required init(style: UITableViewCellStyle, reuseIdentifier: String?) {
    super.init(style: style, reuseIdentifier: reuseIdentifier)
  }
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }

  //MARK: Cell setup & update
  override func setup() {
    super.setup()
    
    //camera & view
    let camera = GMSCameraPosition.camera(withLatitude:  51.507351, longitude: -0.127758,zoom: 10)
    _mapView = GMSMapView.map(withFrame: mainView.bounds, camera: camera)
    _mapView.isMyLocationEnabled = true
    _mapView.delegate = self
    mainView.addSubview(_mapView)
   
    _locationManager.delegate = self
  
 }
  
  override func update() {
    super.update()
  }
  
}

//MARK: MapRow
final class MapRow: Row<MapCell>, RowType {
  required init(tag: String?) {
    super.init(tag: tag)
    cellProvider = CellProvider<MapCell>(nibName: "MapCell")
  }
}

//MARK: MapInfo
struct MapInfo: Equatable {
  static func ==(lhs: MapInfo, rhs: MapInfo) -> Bool {
    return lhs == rhs
  }
}

//MARK: Callbacks
extension MapCell: CLLocationManagerDelegate {

   @nonobjc func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
    
    print("didChangeAuthorization")
    
    guard status == .authorizedWhenInUse else {
      return
    }
    
    _locationManager.startUpdatingLocation()
    _mapView.isMyLocationEnabled = true
    _mapView.settings.myLocationButton = true
  }
  
  @nonobjc func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
    
    print("didUpdateLocations")

    guard let location = locations.first else {
      return
    }
    
    _mapView.camera = GMSCameraPosition(target: location.coordinate, zoom: 18, bearing: 0, viewingAngle: 0)
    _locationManager.stopUpdatingLocation()
  }
} 
```

Thanks in any case. Eureka is a really cool library and a great time saver :)

**Comment by macoapps** [comment]
I used ViewRow from Eureka Community to handle my map inside a cell => ViewRow<GMSMapView>. It works like a charm
