### ISSUE TITLE
Adding section dynamically

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#1453]
Hello everyone,

can someone gives me a hint how can I implement "Add new section" functionality.
How can I duplicate a section and change row tag for the new section.

Thanks,
Daniel

**Comment by Kaakati** [comment]
+1

**Comment by mtnbarreto** [comment]
There is no a simple section/row copy functionality since each row has its correspond tableView cell, we can't just reuse it in another part of the form, it won't work. 

The main issue is that we do not have total visibility over the row properties, such as callback properties so it's hard to completely copy a row. 

If you are looking for a simple copy (type and value), this may help:

```swift
  func rowCopy<Row>(row:Row) where Row: BaseRow, Row: RowType {
        let rowCopy = Row.init(row.tag ?? "" + "\(random)") { _ in }
        rowCopy.value = row.value
        // here we can check if row conforms to some protocol to copy row specific properties
       // As I said, since callbacks properties are internal it's hard to copy them. At this point probably you 
          can use some method to recreate them, I mean a method that given a row is able to set up the callback like we do after row initialization
   }
```

Hope it helps..

**Comment by alonreptor** [comment]
@dneykov,
This helped for me:
At the end of a the section, add a buttonRow with block completion:  .**onCellSelection** witch will
Call a func to build again the section. dont forget to pass and increase  the tag value by 1 every time...
         

```


  <<< ButtonRow() {
                $0.title = "Add"
                $0.cellStyle = .value1
                }.cellUpdate { cell, _ in
                    cell.textLabel?.textAlignment = .left
                    cell.imageView?.image = UIImage(named:"plus_image")
                    
                }.onCellSelection { cell, row in
                    self.buildSectionFollowUp(form: form, i: self.countNumberOfFollowUpSection)
                    self.countNumberOfFollowUpSection = self.countNumberOfFollowUpSection + 1
                    
        }
```

**Comment by dneykov** [comment]
Thanks @alonreptor 
I came up with something very similar.

**Comment by techstylemom** [comment]
Thank you @alonreptor this is very helpful
