### ISSUE TITLE
[question] ButtonRowWithPresent and a UINavigationController

### ISSUE THREAD

**Issue by aptly-io** [xmartlabs/Eureka#1458]
I use a `ButtonRowWithPresent<>` and set its `presentationMode` to `.segueName()`. With its `onPresent` I want to set some initialization values on the pushed form's instance.

Since the pushed form is controlled by an `UINavigationController`, my `onPresent` is never triggered; it fails in `prepare(for:)`. 

Is there any other way to use the `ButtonRowWithPresent` in combination with a `UINavigationController`? 
What is there a reason to be opinionated by requiring the type parameter to be `VCType` and having `onDismissCallback` and `row` properties on the pushed form (it requires existing view controllers to be refactored)? (Maybe I do not understand that part).

```swift
    open override func prepare(for segue: UIStoryboardSegue) {
        super.prepare(for: segue)
        guard let rowVC = segue.destination as? VCType else {
            return  // QUITS HERE BECAUSE ITS destination IS A UINavigationController
        }
        if let callback = presentationMode?.onDismissCallback {
            rowVC.onDismissCallback = callback
        }
        rowVC.row = self
        // NEVER GETS HERE
        onPresentCallback?(cell.formViewController()!, rowVC)
    }
}
```

- Environment: Eureka 4.1.0, Xcode 9.2 and iOS version 11.2.

**Comment by aptly-io** [comment]
Currently I use this workaround: override those methods that prevent me from using the `ButtonRowWithPresent` due to the `UINavigationController` getting in the way. Maybe there's a more elegant solution?

```swift
final class ButtonRowWithPresent2<VCType:
        TypedRowControllerType> : _ButtonRowWithPresent<VCType>,
        RowType where VCType: UIViewController {

    var onPresentCallback2: ((FormViewController, UINavigationController) -> Void)?

    public func onPresent2(_ callback: ((FormViewController, UINavigationController) -> Void)?) -> Self {
        onPresentCallback2 = callback
        return self
    }

    override func prepare(for segue: UIStoryboardSegue) {
        super.prepare(for: segue)
        guard let nav = segue.destination as? UINavigationController else {
            return
        }
        // for now ignore the onDismissCallback and row property
        // as we have a UINavigationController only ...
        onPresentCallback2?(cell.formViewController()!, nav)
    }
}
```

**Comment by mats-claassen** [comment]
That is a valid workaround for custom implementations. 
Why are you pushing a navigation controller from a ButtonRow?

**Comment by mtnbarreto** [comment]
`(segue.destination as? UINavigationController ).topViewController` may help.

Closing due to lack of response.
