### ISSUE TITLE
Changing the appearance of SegmentedRow using a xib file

### ISSUE THREAD

**Issue by ablegreen** [xmartlabs/Eureka#1460]
Eureka: 4.0
Xcode: 9.2
iOS: 11.2

I was able to change the appearance of TextCell by creating a xib file and connecting the appropriate outlets. It works great:

```swift
import Eureka

final class MyTextRow: Row<MyTextCell>, RowType {
    required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<MyTextCell>(nibName: "MyTextCell")
    }
}

class MyTextCell: _FieldCell<String>, CellType { }
```

Next, I'd like to change the appearance of SegmentedCell with a xib file:

```swift
import Eureka

final class MySegmentedRow<T: Equatable>: OptionsRow<MySegmentedCell<T>>, RowType {
    required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<MySegmentedCell>(nibName: "MySegmentedCell")
    }
}

class MySegmentedCell<T: Equatable> : Cell<T>, CellType { }
```

This gives me a compiler error:

`'CellProvider' requires that 'MySegmentedCell' inherit from 'BaseCell'`

What am I doing wrong? I just want to change the appearance of SegmentedRow (such as the width of the control) and keep all the default behavior with minimal effort. Is this possible?

Thanks.

**Comment by StriderHND** [comment]
Having the Same problem trying to do the same with the ImageCheckRow

**Comment by mtnbarreto** [comment]
I might this is happens because inteface builder does not allow generics types, in your case `MySegmentedCell<T: Equatable>`. 

As a workaround, remove generic type from  MySegmentedCell, open MySegmentedCell xib and connect the cell to MySegmentedCell, save the xib, finally put back generic type in MySegmentedCell.swift source code.
