### ISSUE TITLE
'CellProvider' requires that 'SelectExtrasCell' inherit from 'BaseCell'

### ISSUE THREAD

**Issue by StriderHND** [xmartlabs/Eureka#1462]
Did I'm missing something here, I'm trying to create a custom Row from a ImageCheckRow

```Swift
public final class SelectExtrasRow<T: Equatable>: Row<SelectExtrasCell<T>>, SelectableRowType, RowType {
    public var selectableValue: T?
    required public init(tag: String?) {
        super.init(tag: tag)
        displayValueFor = nil
        cellProvider = CellProvider<SelectExtrasCell>(nibName: "CLINExtrasCell", bundle: Bundle.main)
    }
}

public class SelectExtrasCell<T: Equatable> : Cell<T>, CellType{
  //rest of the code.
}
```

**Comment by mtnbarreto** [comment]
All Eureka cells must extend Cell<T> or a extension of it.

By definition Cell<T> extends BaseCell according `open class Cell<T>: BaseCell, TypedCellType where T: Equatable`

So SelectExtrasCell already extends BasCell since it extends Cell<T> according your code.

**Comment by mtnbarreto** [comment]
Hi @StriderHND check out #1460, seems my proposed solution works for you too.

**Comment by StriderHND** [comment]
What you suggested in #1460  worked correctly but I still have issues with with compiler, maybe I'm missing something

this is the whole SelectExtrasCell Class 
```Swift
public class SelectExtrasCell<T: Equatable>: Cell<T>, CellType{
    
    @IBOutlet weak var ExtraPrice:UILabel!
    
    required public init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    /// Image for selected state
    lazy public var trueImage: UIImage = {
        return UIImage(named: "selected")!
    }()
    
    /// Image for unselected state
    lazy public var falseImage: UIImage = {
        return UIImage(named: "unselected")!
    }()
    
    public override func update() {
        super.update()
        checkImageView?.image = row.value != nil ? trueImage : falseImage
        checkImageView?.sizeToFit()
    }
    
    /// Image view to render images. If `accessoryType` is set to `checkmark`
    /// will create a new `UIImageView` and set it as `accessoryView`.
    /// Otherwise returns `self.imageView`.
    open var checkImageView: UIImageView? {
        guard accessoryType == .checkmark else {
            return self.imageView
        }
        
        guard let accessoryView = accessoryView else {
            let imageView = UIImageView()
            self.accessoryView = imageView
            return imageView
        }
        
        return accessoryView as? UIImageView
    }
    
    public override func setup() {
        super.setup()
        accessoryType = .none
    }
    
    public override func didSelect() {
        row.reload()
        row.select()
        row.deselect()
    }
    
}
``` 

You can see the attachment:
![screen shot 2018-03-16 at 2 41 42 pm](https://user-images.githubusercontent.com/430328/37543756-45f1117c-2928-11e8-8312-a9e022eb6fc9.png)

**Comment by mtnbarreto** [comment]
Hi @StriderHND . 

Seems you forgot to specify SelectExtrasCell generic type. 

```
cellProvider = CellProvider<SelectExtrasCell<T>>(... should be used insted. 
```

> Notice I have added <T> in the above sentence.

**Comment by StriderHND** [comment]
Hi @mtnbarreto 

The change worked out, but there is now a problem with IB I'm getting an Crash when trying to open the view with the new Cells.

´´´´
2018-03-19 14:18:08.387909-0600 Clin[3845:2153979] Unknown class _TtC4Clin16SelectExtrasCell in Interface Builder file.
2018-03-19 14:18:08.390751-0600 Clin[3845:2153979] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITableViewCell 0x105c34200> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key ExtraPrice.' ´´´´

Any ideas¿

Thanks

Erick

**Comment by StriderHND** [comment]
Any thoughts?

**Comment by mtnbarreto** [comment]
remove `ExtraPrice` outlet from cell xib and connect it again, then try again.

**Comment by StriderHND** [comment]
For some reason still get the error, I have remove the outlet of the xib and connected again but still I get the same error

**Comment by StriderHND** [comment]
Finally resolve thanks!

**Comment by A-Helberg** [comment]
@StriderHND What did you do to solve it?

I've removed the outlet and re added it multiple times and still get the same error.
If I manually set up the view items with `viewWithTag(x)` I can get it to work

**Comment by StriderHND** [comment]
> @StriderHND What did you do to solve it?
> 
> I've removed the outlet and re added it multiple times and still get the same error.
> If I manually set up the view items with `viewWithTag(x)` I can get it to work

If you check my class example 

` public override func didSelect() {
        row.reload()
        row.select()
        row.deselect()
    }`

the `row.select()` was causing the issue. I removed that and finally get working the class as expected.
I'm sorry for my late response.
