### ISSUE TITLE
Custom ButtonRow as addButtonProvider

### ISSUE THREAD

**Issue by thierrybucco** [xmartlabs/Eureka#1467]
Hi,

I would like to use a MultivaluedSection with custom addButtonProvider is there a way to do this?

Thanks!

**Comment by AndrewBennet** [comment]
I've also come across a need for this. I wonder whether `addButtonProvider: ((MultivaluedSection) -> ButtonRow)` could be changed to `addButtonProvider: ((MultivaluedSection) -> _ButtonRowOf<String>)`...

**Comment by jacktiong92** [comment]
Hi @AndrewBennet, did you managed to customise the add button?

**Comment by dkroukamp** [comment]
This feature is really needed, a new release with this in would be very much appreciated, as forking is really my last option :(

**Comment by mats-claassen** [comment]
You can use the commit of #1843 while it is being reviewed. Please post if there is any issue with those changes. Docs are also added in that pull request.

**Comment by dkroukamp** [comment]
> You can use the commit of #1843 while it is being reviewed. Please post if there is any issue with those changes. Docs are also added in that pull request.

I see nice even if I'm using cocoapods?
