### ISSUE TITLE
Transfer data with segue

### ISSUE THREAD

**Issue by jonhsnow** [xmartlabs/Eureka#147]
How to transfer some data with segue?
For example with 2 rows different data
```
<<< ButtonRow("Demo1") {
    $0.title = $0.tag
    $0.presentationMode = .SegueName(segueName: "RowsExampleViewControllerSegue", completionCallback: nil)
      }

<<< ButtonRow("Demo2") {
    $0.title = $0.tag
    $0.presentationMode = .SegueName(segueName: "RowsExampleViewControllerSegue", completionCallback: nil)
      }
```

**Comment by N15ee** [comment]
asked myself the same question!

**Comment by bharatkrishna** [comment]
I am using a PushRow to present a custom tableview. When a row is selected in that view, how do I set the value of PushRow to the selected row's text? 

This is the code I have:

```swift
            <<< PushRow<String>() {
                $0.title = "Location"
                $0.presentationMode = .SegueName(segueName: "showLocationsFromAddItem", completionCallback: nil)
                $0.value = self.location?.address ?? ""
            }
```

where self.location passed on from the second view controller which the segue invokes. It is passed on using a custom delegate. How do I set the PushRow's value to the self.location.address ? Should I use completionCallback?

**Comment by N15ee** [comment]
you got to override the prepareFor Segue function.
There you have to get the TAG from the Row ->`<addr>` (sender as! PushRow).tag! 

For this you have to set the tag in the PushRow 
`<addr>`PushRow<String>("InsertTagIDhere")
After:

`<addr>`override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
`<addr>`if segue.identifier == "ContractDetail" {
`<addr>`let destinationVC = segue.destinationViewController as! ContractDetailVC
`<addr>`destinationVC.contractId = (sender as! ButtonRow).tag!
`<addr>`}
`<addr>`}

**Comment by mats-claassen** [comment]
Sorry for the late answer, the presented controller should conform to the `TypedRowControllerType` protocol. If so then you can directly set the chosen location to that row. You can then use the onChange callback on that row to update self.location if that is what you want.

You can also use the completionCallback as well

**Comment by mtnbarreto** [comment]
You can also use this row...
```swift
public final class ButtonRowWithPresent<T: Equatable, VCType: TypedRowControllerType where VCType: UIViewController, VCType.RowValue == T> : _ButtonRowWithPresent<T, VCType>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}
```

then set up `onPresent` callback...

```swift
.onPresent { from, to in
     // to.myVariable = myVariableValue
}
```

**Comment by mrvincenzo** [comment]
`onPresent` is not called when using `ButtonRowWithPresent` with `presentationMode = .SegueName(segueName, completionCallback:)`

**Comment by dallaverde** [comment]
@EEimer Hi, I am trying to pass information from rows to a label in another CV when I touched at a "save" button. 

I tried the same thing that u said. 

   override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == "ContractDetail" {
            let destinationVC = segue.destinationViewController as! ContractDetailVC
            destinationVC.contractId = (sender as! ButtonRow).tag!
        }
    }

But instead use ButtonRow, I used TextRow or DateInLineRow. And not works. Can u help me? pls 

Thx
