### ISSUE TITLE
Swift 3.2 to Swift 4 migration & Eureka 

### ISSUE THREAD

**Issue by skoricnik1** [xmartlabs/Eureka#1470]
Hey guys, I have some problems with Eureka in Swift 4. Code below is written in Swift 3.2, and I'm doing migration to Swift 4, so I'm confused with errors shown on image. Can someone provide me solution for this? Thanks. 

Is there any documentation for migration from Swift 3 to Swift 4?
I'm using Xcode Version 9.2 (9C40b) with CocoaPods, and lastest Eureka version.

![screen shot 2018-03-20 at 12 27 05](https://user-images.githubusercontent.com/36270965/37652058-797199b2-2c3a-11e8-92d1-47f43901bf6b.png)

**Comment by mats-claassen** [comment]
Hi, from version 4 in `SelectorRow` only takes one generic parameter and `_SelectorViewController` two.

**Comment by mtnbarreto** [comment]
Hi @skoricnik1, Any update on this?

**Comment by skoricnik1** [comment]
Hello, I saw that SelectorRow and _SelectorViewController are changed, but still I cannot make it work as it worked with older version.

**Comment by mtnbarreto** [comment]
@skoricnik1 Please share the new compilation errors you are having.. so ui can take a look.

**Comment by skoricnik1** [comment]
As I can assume, SelectorRow now doesn't have ability to present new controller. Also I'm not sure about declaration of NoteIconSelectorViewController and NoteIconListCheckRow, is that correct.

![screen shot 2018-03-27 at 13 15 32](https://user-images.githubusercontent.com/36270965/37964371-827dd4b2-31c1-11e8-8b99-3cb2b6f9d3a1.png)

**Comment by skoricnik1** [comment]
It's okay now, I've solved the problem.

**Comment by SachinTanpure** [comment]
@skoricnik1 i am facing exactly same issue. Can you please share how do you solved this issue?

**Comment by murraycollingwood** [comment]
@skoricnik1 i am facing exactly same issue. Can you please share how do you solved this issue?
