### ISSUE TITLE
SelectorRow Disabling doesn't seem to work

### ISSUE THREAD

**Issue by JesseNoBata** [xmartlabs/Eureka#1471]
Have tried disabling selectorrow using: 

```swift
<<< SelectorRow("targetRowTag"){
      $0.disabled = true
```

and with targeting row via id-tag as follows:

```swift
targetRow?.evaluateDisabled()
```

Neither approach works-- can still click on individual 'boxes' of the row and the values get processed. Additionally, clicking on the images accompanying them updates boxes. Disabling other rows works via *.disabled = true just fine.

**Comment by mtnbarreto** [comment]
Is targetRow not nil?

**Comment by JesseNoBata** [comment]
Yes, currently : 

$0.value = []

I attempted per front-page docs to set: 

targetRow.value = nil

But during .cellSetup get an error about unwrapping a nil value for that row-- Ultimately I thought to set default boxes via .cellSetup; i.e. I would like the selectorRow to have certain pre-defined values that are initially not changeable but later on may become changeable.However the disabled still allows user selection. Is this functionality allowed via Eureka, having pre-set, disabled values for a selectorRow or do they have to be nil? If they have to be nil, is this a potential addition to the functionality to have pre-set, immutable values?

**Comment by JesseNoBata** [comment]
Bumping as same issue as [Issue  #924 ](https://github.com/xmartlabs/Eureka/issues/924)

**Comment by mats-claassen** [comment]
Are you using a `SelectorRow`? or one of its subclasses? Normally we would do the latter. And if you use the SelectorRow itself you must specify which cell it uses. ( you can't instatiate it like `SelectorRow("targetRowTag")`.

**Comment by mtnbarreto** [comment]
Closing due to lack of response..
