### ISSUE TITLE
Dynamic insert lots of rows into section have bad performance

### ISSUE THREAD

**Issue by danjiang** [xmartlabs/Eureka#1474]
I use `append<S: Sequence>(contentsOf newElements: S)` of Section to dynamic insert 125 rows. But it also invoke `func rowsHaveBeenAdded(_ rows: [BaseRow], at indexes: [IndexPath])` of FormViewController 125 times. Bad performance.

**Comment by mtnbarreto** [comment]
Hi @danjiang ! 
Unfortunately this was the only option we had to automatically update the table view based on the DSL. Anyway I'm open to consider a more performant solution. 

Are you using Eureka for something different than a form? I can't image a form with 125 rows.
> As a workaround, try adding a new section instead of adding rows to already created section.

**Comment by danjiang** [comment]
I am currently using adding a new section to solve the problem. 

My requirement is allowing user type in  a number and dynamically insert rows base on that number. 200 is the edge case. Around 10 is normal case.

Anyway. If `append<S: Sequence>(contentsOf newElements: S)` of Section have same effect like `append(_ formRow: BaseRow)` of Section in a foreach. It is more appropriate to just make `append(_ formRow: BaseRow)` of Section as public interface. From point of framework user, I will consider  `append<S: Sequence>(contentsOf newElements: S)` of Section is batch inserts. Just like insert lots of index paths into table.

**Comment by mtnbarreto** [comment]
Evaluate hidden, disabled conditions take some time and consumes cpu. 

There are 2 things that you can do to improve performance. Add a section and remove disabled, hidden conditions.
