### ISSUE TITLE
Is it possible to build a tree view using inline nested rows?

### ISSUE THREAD

**Issue by sedwo** [xmartlabs/Eureka#1481]
Wanting to stick with Eureka, I'm researching methods to mimic something similar to a tree view of rows.

Design example:
![image](https://user-images.githubusercontent.com/1434449/37975687-dd254954-31ad-11e8-8032-34c4c2f4ea15.png)

Similar to this:  https://github.com/gringoireDM/LNZTreeView

**Comment by mtnbarreto** [comment]
I would recommend to create a new row that holds nested rows and so on. This new row should know if the nested rows are visible or not. 

`1- Floor 1`, `1- Floor 2`, ... are just `PushRow`s  that have padding/marging configuration.

**Comment by sedwo** [comment]
@mtnbarreto Would you suggest this custom `tree row` design take on a _regular_ `row` or be like an `inline row` type?   (Is it possible to even deeply nest multiple `inline rows`?)
