### ISSUE TITLE
Getting all rows in section including hidden

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#1482]
Hello everyone,

I'm trying to get all rows in a section including hidden rows but cannot achieve it. Anyone can help with that?

I'm iterating the rows with this but only visible rows are there.

```swift
//let section: Section
for let row in section {
  let value: Any? =  row.baseValue
}
```

Thanks.

**Comment by mtnbarreto** [comment]
Hi @dneykov ! We can get all rows that belong the form and filter them according the section like the code below..

```swift
let form: Form = ....
let section = ....
let allSectionRows = form.allRows.filter{ $0.section === section }
```

Let me know if it works.

**Comment by dneykov** [comment]
Hi @mtnbarreto,

the case is that I have multiple sections with same tag and I'm getting them filtering through all sections and then iterating rows in each section. Final result which I want to achieve is values in following structure `[[String: String]]`

But I think I should change my logic and my starting point should be `form.allRows`

**Comment by dneykov** [comment]
I get the result I want getting all rows and them grouping them into `[[BaseRow]]` depending on `section.index`

Thanks @mtnbarreto
