### ISSUE TITLE
TextAreaCell, PickerInputCell center alignment

### ISSUE THREAD

**Issue by arnauddorgans** [xmartlabs/Eureka#1491]
- Environment: Eureka: 4.1.1, iOS 11

I can't set TextAreaCell placeholder label align center, i have a weird bug when, on the first becomeFirstResponder the placeholder label have a left alignement and after typing have the correct alignment center
`cell.textView.textAlignment = self.alignment`
`cell.placeholderLabel?.textAlignment = self.alignment`
![textarea](https://user-images.githubusercontent.com/10015557/38130921-37502206-3405-11e8-88b0-4b489529b497.gif)

And I can't set PickerInputCell alignment, 
`cell.textLabel?.textAlignment = .center // do nothing ` 
![input](https://user-images.githubusercontent.com/10015557/38130976-6fc80a7c-3405-11e8-9514-0164ff0553a4.png)

**Comment by dushansapu** [comment]
I have faced too..
