### ISSUE TITLE
Eureka on specific UITableView?

### ISSUE THREAD

**Issue by TofPlay** [xmartlabs/Eureka#1493]
Hi,
On my app I can not use `FormViewController` but I can define an `UITableView`.
Is it possible to specify in Eureka to use this UITableView?
If yes how should it be done?

**Comment by leondobnik** [comment]
@TofPlay You haven't specified much details, what is the problem of using / not using FormViewController. However just to give you a tip if it helps: if you have a screen, where you would like to have a form + several other custom UI components, iOS has solution for you. Use ContainerView and draw segue to custom implementation of FormViewController. This will embeed VC into your screen.

**Comment by mtnbarreto** [comment]
@TofPlay As @leondobnik you should probably add a containerView to hold eureka table view and FormViewController.

**Comment by zunjae** [comment]
Is this part of the official documentation? It took me too long to find this
