### ISSUE TITLE
Feed a MultivaluedSection with data

### ISSUE THREAD

**Issue by DesdeChaves** [xmartlabs/Eureka#1494]
Is there a easy way   to feed a multivaluedsection with data? 

I can feed TextRow in this way:

In my viewModel I define 

 ```swift
    var studentName: String? {
            get { return  myStudent.name}
            set { myStudent.name = newValue}
        }
```

In the view controller:

```swift
     <<< TextRow() {
        $0.title = "Student name"
        $0.placeholder = "student name"
        $0.value = viewModel.studentName
        $0.onChange { [unowned self] row in
          self.viewModel.studentName = row.value
        }
        $0.add(rule: RuleRequired())
        $0.validationOptions = .validatesOnChange
        $0.cellUpdate { (cell, row) in 
          if !row.isValid {
            cell.titleLabel?.textColor = .red
          }
        }
    }
```
    
But If I had a array of student names, How can I feed a multivaluedsection with this data?

For example, with this array allStudents = ["John", "Marie", "Elvis", "Schumacker"]  I need  to have a multivaluedsection with four cells for update, delete a and new students.

Sorry for my small brain.

**Comment by mtnbarreto** [comment]
There is no a direct way to do so. 

Create the form is pretty easy. 
```swift
allStudents.forEach { 
     section <<< TextRow() {
        $0.title = "Student name"
        $0.placeholder = "student name"
        $0.value = $0
        $0.add(rule: RuleRequired())
        $0.validationOptions = .validatesOnChange
        $0.cellUpdate { (cell, row) in 
          if !row.isValid {
            cell.titleLabel?.textColor = .red
          }
        }
    }
}
```

I recommend you to obtain the MultivalueSection values and update your model before the user leaves the view controller.
