### ISSUE TITLE
Xcode 9.3 error

### ISSUE THREAD

**Issue by LanWor** [xmartlabs/Eureka#1495]
Versions:
Eureka 4.0.1 
Xcode 9.3
iOS 11.3
Swift 4.1
<img width="962" alt="2018-04-02 9 32 18" src="https://user-images.githubusercontent.com/16620492/38179708-e49be63e-3658-11e8-90d6-57561e742c3b.png">
when i update my Xcode to 9.3 And iOS 11.3,this project tell me the error ---- 
<img width="1008" alt="2018-04-02 9 35 01" src="https://user-images.githubusercontent.com/16620492/38179750-343485e8-3659-11e8-82c2-389beac4a668.png">

**Comment by mohammdsss1** [comment]
@LanWor I did update Eureka to 4.1.1 and the error gone away

**Comment by tuantmdev** [comment]
Update to Xcode 9.3, using Eureka 4.1.1 and same issue

**Comment by JMCPH** [comment]
Updated to 4.1.1 and cleaned the project and build folder - now it works 💪🏼

**Comment by mats-claassen** [comment]
I just built it with Xcode 9.3 without issues.
