### ISSUE TITLE
Not visible rows disappearing when changing PushRow values

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#1496]
Hello,

I have problem with disappearing rows. Rows which are not visible are disappearing when changing PushRow values. When I change a value and scroll down rows are not there but if I scroll back and return to the missing rows they appears. All rows have unique tags, I have connected IBOutlet tableView.

Any suggestions what could be the problem? I have lots of forms in my app but this one is big form and the problem appears only for that form.

Thanks.

**Comment by mtnbarreto** [comment]
Probably the problem is caused by wrongly connected IBOutlet.
