### ISSUE TITLE
xib error

### ISSUE THREAD

**Issue by GMlc** [xmartlabs/Eureka#1499]
here is the code 
```
public class CellPurchaseList<T : Equatable> : Cell<T> ,CellType{}

public final class RowPurchaseList<T :Equatable> : Row<CellPurchaseList<T>>,RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<CellPurchaseList<T>>(nibName: "RowPurchaseList")
    }
}
```
and then I created a xib file related to CellPurhcaseList ,but when I try to open the new form with cellpurchaselist Xcode crash :

> Unknown class _TtC12ManageSystem16CellPurchaseList in Interface Builder file.
> Could not cast value of type 'UITableViewCell' (0x1087c4560) to 'ManageSystem.CellPurchaseList<Swift.String>' (0x7f8ffb0bd180).

somebody help me !!!!!

**Comment by mats-claassen** [comment]
I think xib files have problems with generic classes. You would have to use a non-generic class as Cell
