### ISSUE TITLE
Multivalued section not showing insert/delete accessory buttons initially

### ISSUE THREAD

**Issue by simonbromberg** [xmartlabs/Eureka#1503]
After updating to Eureka 4.1.1 (had to because of Xcode 9.3) I noticed the green insert / red delete buttons on the left side of cells in my multivalued section were not showing up. At first I thought it was some new update and if I wanted them I would have to set some property, but then I noticed they came back when I pushed another view controller onto the navigation stack and then returned to the form view controller.

The rows are still deletable by swiping and tapping on the revealed delete button and the insert button still works, just the accessory buttons are missing.

Tested in iOS 10. as well as 11.3. Running off Xcode 9.3. Occurs on simulator and device.

Note: It is only a problem when the multivalued section is initially hidden (hiding toggled via a switch row). If the multivalued section is visible initially, it works properly as it did before the update.

I have it set up so that it can never delete the last valued row in the section, and it initializes the section with one row.

(removed code because no longer seems relevant)

**Comment by simonbromberg** [comment]
Yes, looks like it is.

I am not sure what change is responsible for this or if it was intentional though.

**Comment by briankoksal** [comment]
I noticed this change in behavior also. I had the opposite problem where the delete buttons would show up initially when they weren't before. I moved the "tableView.isEditing = false" from the viewDidLoad to the viewWillAppear so that it gets called after the Eureka form code and now it is working. Not sure the reason for this either yet..

**Comment by RowanG1** [comment]
I am using current version of Eureka, and latest swift - The delete icon in multivalued form with delete enabled, is not showing.
