### ISSUE TITLE
Problem with inlineRow after update $4.1.1

### ISSUE THREAD

**Issue by jbocio** [xmartlabs/Eureka#1506]
Hi,

Recently I've updated Eureka to v4.1.1, due to the update of iOS 11.3.

I have problems with all the row that show inlineRow, or rows hidden depending from another row.
The kind of errors is differents in some cases, and in other cases there just no error, simply doesn't run as expected.

One of the erros is i.e. `contentOffsetForScrollingToRowAtIndexPath`

My whole app depends on forms... So I'll agree a solution.

Thanks in advance,

Jaime

**Comment by mats-claassen** [comment]
Hi, could you describe the errors more specifically and give examples on how to reproduce them?

**Comment by jbocio** [comment]
Sorry, I've just realized that the problem is with my code, and not a general problem of Eureka. Anyway I don't understand the reason.

I wanted to put a background image for all the FormViewController of my app, so I override the viewWillAppear.

```
extension FormViewController {
    
   open override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tableView.backgroundView = FuncionesGeneral.imageViewLogoMarcaDeAgua()
    }
}
```

WIth these code I have all the problems. I remove and the problems are solved. Why? How can I put a generic background image for all the FormViewController? I try to override viewDidLoad, but Xcode doesn't allow me.

Thanks
