### ISSUE TITLE
SelectableSection singleSelection or multipleSelection bump

### ISSUE THREAD

**Issue by StriderHND** [xmartlabs/Eureka#1507]
Hello we are having an issue using the SelectableSection 

Each time we select/deselect a row there is a scroll movement or bump the view tries to do something 

We are using eureka version : 4.1.1

I've attached a gif that shows the problem

Thanks

Erick

![glamorousdirtyanemoneshrimp-max-14mb](https://user-images.githubusercontent.com/430328/38520567-5fa5d8c4-3c00-11e8-8cdb-ded1a927044a.gif)

**Comment by mats-claassen** [comment]
I can reproduce this in the Examples (List Sections) but only in portrait and for a very specific scroll position. And as soon as I add another section to the form the issue does not appear anymore

**Comment by mats-claassen** [comment]
The issue seems to go away if I remove the call to `row.reload()` in `ImageCheckCell.didSelect`. Does that fix it for you as well?

**Comment by StriderHND** [comment]
I'll try this, I'll update the case if the problem persist

**Comment by StriderHND** [comment]
Hello @mats-claassen I just tried this to remove the reload() I had for the row section, still the problem is persistent here is how I have the code right now


Multiple section 
`form +++ SelectableSection<SelectExtrasRow<JSON>>(" ", selectionType: .multipleSelection){ section in
            var header = HeaderFooterView<UILabel>(.class)
            header.height = { 25 }
            header.onSetupView = {view, _ in
                view.textColor = UIColor(ColorWithHexValue: 0x5E5552)
                view.text = "   "+sectionName
                view.font = UIFont(name:"Arial-BoldMT", size: 16.0)
            }
            section.tag = sectionName
            section.header = header
        }
        for option in items {
            form.last! <<< SelectExtrasRow<JSON>(option["name"].stringValue){ lrow in
                lrow.title = option["name"].stringValue
                lrow.selectableValue = option
                lrow.value = nil
                }.cellSetup { cell, _ in
                    cell.trueImage = #imageLiteral(resourceName: "ExtrasMultipleSelectionTrue")
                    cell.falseImage = #imageLiteral(resourceName: "ExtrasMultipleSelectionFalse")
                    let extraPrice = UILabel(frame: CGRect(x: 0, y: 0, width:70, height: 40))
                    extraPrice.text = HNL(floatLiteral: option["price"].doubleValue).description
                    extraPrice.textColor = UIColor(hex: 0x757170)
                    extraPrice.font = UIFont(name:"ArialMT", size: 12.0)
                    extraPrice.textAlignment = .right
                    cell.accessoryView = extraPrice
                }.onChange { row in
                    self.GetTotalDishPrice()
                    if let _ = row.value {
                        let count = row.section!.filter { $0.baseValue != nil }.count
                        if count > limit {
                            row.value = nil
                            //row.section?.reload()
                        }
                    }
                }
            }`

Single Selection 

`form +++ SelectableSection<SelectExtrasRow<JSON>>(sectionName, selectionType: .singleSelection(enableDeselection: optional)){ section in
            var header = HeaderFooterView<UILabel>(.class)
            header.height = { 25 }
            header.onSetupView = {view, _ in
                view.textColor = UIColor(ColorWithHexValue: 0x5E5552)
                view.text = "   "+sectionName
                view.font = UIFont(name:"Arial-BoldMT", size: 16.0)
            }
            section.tag = sectionName
            section.header = header
        }
        for option in items {
            form.last! <<< SelectExtrasRow<JSON>(option["name"].stringValue){ lrow in
                lrow.title = option["name"].stringValue
                lrow.selectableValue = option
                lrow.value = nil
                }.cellSetup { cell, _ in
                    cell.trueImage = #imageLiteral(resourceName: "ExtrasSingleSelectionTrue")
                    cell.falseImage = #imageLiteral(resourceName: "ExtrasSingleSelectionFalse")
                    let extraPrice = UILabel(frame: CGRect(x: 0, y: 0, width:70, height: 40))
                    extraPrice.text = HNL(floatLiteral: option["price"].doubleValue).description
                    extraPrice.textColor = UIColor(hex: 0x757170)
                    extraPrice.font = UIFont(name:"ArialMT", size: 12.0)
                    extraPrice.textAlignment = .right
                    cell.accessoryView = extraPrice
                }.onChange({ (row) in
                    self.GetTotalDishPrice()
                })
        }`

**Comment by mats-claassen** [comment]
You are using a `SelectExtrasRow`, from which class is it subclassing? And are you calling `row.reload` somewhere in that implementation or its super class?

**Comment by StriderHND** [comment]
@mats-claassen this is the ```SelectExtrasRow``` class it's a SelectableRowType nothing more, if you find any observations please let me know

```
import Foundation
import UIKit
import Eureka
import SwiftyJSON
import Money


public final class SelectExtrasRow<T: Equatable>: Row<SelectExtrasCell<T>>, SelectableRowType, RowType {
    public var selectableValue: T?
    required public init(tag: String?) {
        super.init(tag: tag)
        displayValueFor = nil
        //cellProvider = CellProvider<SelectExtrasCell<T>>(nibName: "SelectExtrasCell", bundle: Bundle.main)
    }
}
 
public class SelectExtrasCell<T: Equatable>:Cell<T>, CellType{
    
    required public init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    /// Image for selected state
    lazy public var trueImage: UIImage = {
        return UIImage(named: "selected")!
    }()
    
    /// Image for unselected state
    lazy public var falseImage: UIImage = {
        return UIImage(named: "unselected")!
    }()
    
    public override func update() {
        super.update()
        checkImageView?.image = row.value != nil ? trueImage : falseImage
        checkImageView?.sizeToFit()
    }
    
    /// Image view to render images. If `accessoryType` is set to `checkmark`
    /// will create a new `UIImageView` and set it as `accessoryView`.
    /// Otherwise returns `self.imageView`.
    open var checkImageView: UIImageView? {
        guard accessoryType == .checkmark else {
            return self.imageView
        }
        
        guard let accessoryView = accessoryView else {
            let imageView = UIImageView()
            self.accessoryView = imageView
            return imageView
        }
        
        return accessoryView as? UIImageView
    }
    
    public override func setup() {
        super.setup()
        accessoryType = .none
    }
    
    public override func didSelect() {
        row.reload()
        row.select()
        row.deselect()
    }
    
}

```

**Comment by mats-claassen** [comment]
So you are calling `row.reload()` in `didSelect`. What happens if you remove that line?

**Comment by StriderHND** [comment]
Worked thanks Mats!
