### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11 compile error

### ISSUE THREAD

**Issue by SrikanthSrip** [xmartlabs/Eureka#1512]
Hey there, after adding another cocoapods dependency to my project. My release builds started to fail with this error:
Command failed due to signal: Segmentation fault: 11

The error log is long, but this is at the bottom of it:

While emitting IR SIL function @_TTSg5SSSSs9Equatables_C6Eureka12TextAreaCellS1_S0_8CellTypeS0_uRxS0_18InputTypeInitiablexS_rGCS0_13_TextAreaCellx_S0_13TextInputCellS0_S1_S0_13TypedCellTypeS0____TFFC6Eureka15FormatteableRowcFT3tagGSqSS__GS0_xq__U_FGSqQ__GSqSS_ for expression at [/Users/MyPcName/Desktop/IOSProjectsFolder/MyAppName/Pods/Eureka/Source/Rows/Common/FieldRow.swift:73:27 - line:80:9] RangeText="{ [unowned self] value in
            guard let v = value else { return nil }
            guard let formatter = self.formatter else { return String(v) }
            if (self.cell.textInput as? UIView)?.isFirstResponder() == true {
                return self.useFormatterDuringInput ? formatter.editingStringForObjectValue(v as! AnyObject) : String(v)
            }
            return formatter.stringForObjectValue(v as! AnyObject)
Environment: Eureka 1.6.0, Xcode 7.3

**Comment by mtnbarreto** [comment]
Which is the another dependency that causes the compilation error?

**Comment by SrikanthSrip** [comment]
JSQMessageViewController and Socket.IO-Client-Swift

**Comment by mtnbarreto** [comment]
Hi @SrikanthSrip. 
We are not able to provide such kind of support because your project Eureka version is too old and the issue arises when other libraries are added into the project.

If possible, I recommend you to update Eureka version.

Best, Martin
