### ISSUE TITLE
showing validation messages from Json object returned from an api

### ISSUE THREAD

**Issue by john1452** [xmartlabs/Eureka#1513]
Hi is there a way to show validation messages that are returned from an API in a JSON object.
The Api that I am using returns error messages in the following format.

```
[
   {
       "field": "phoneNumber",
        "message": "Phone Number does not match required format"
   },
   {
       "field": "phoneNumberType",
        "message": "Invalid phone number type"
   }
] 
```

I want to be able to map the error returned to my form.  My form looks like:

Phone Number       [enterPhoneNumber] 
Phone Type            [enterPhoneNumber Type]

I am constructing the form as below:

```
 form +++ Section("Details")
             <<< PhoneRow(){ row in
                 row.title = "Phone Number"
                 row.placeholder = "Enter Phone Number"
        }     <<< SegmentedRow<String>() {

                 $0.options = ["Mobile","Work","Emergency"]
                 $0.value = "Mobile"
        }

```
I tried this out by doing the following. It does not seem to work.

```

  let s  =  ValidationError(msg: "message")
        form.rows[0].validationErrors.append(s)
        form.rows[0].validate()
```

any help is appreciated

**Comment by mats-claassen** [comment]
By calling `validate` you reset the validationErrors.

You could try:
```
let s  =  ValidationError(msg: "message")
form.rows[0].validationErrors.append(s)
form.rows[0].updateCell()
```

But even then as soon as the row is validated again the error will disappear. If that is OK for you then try that, if not you will have to handle it manually

**Comment by mtnbarreto** [comment]
Why don't add validation rules and change the rule message??


closing due to lack of response..
