### ISSUE TITLE
PickerInlineRow validation Issue. 

### ISSUE THREAD

**Issue by jaymathew** [xmartlabs/Eureka#1517]
Eureka:  4.1.1
xcode: 9.3
iOS: 11.3 

I am adding validation to all my Eureka rows, but I'm having trouble with PickerInlineRow<String>.  In-particularly in .cellUpdate when trying to change the titleLabel to red.

When using cell.titleLabel?.textColor = .red, I get an error in Xcode "Value of type 'PickerInlineCell<String>' has no member 'titleLabel'".  What is the general excepted way to workaround this issue ?

Thank you.

**Comment by mtnbarreto** [comment]
Have you tried using `textLabel`. there is no `textLabel` in PickerInlineCell.
