### ISSUE TITLE
Update options value for a pushRow dynamicaly ?

### ISSUE THREAD

**Issue by stodeo** [xmartlabs/Eureka#152]
Hello,
Is there a method to update dynamicaly the options field of a pushRow ?

I can update the baseValue but i can't figure it out for the options ( String Array )

Thanks

**Comment by Domsware** [comment]
Why is this comment closed without any explanation?

**Comment by xrnd** [comment]
This issue is still unanswered

**Comment by danielsimons1** [comment]
I am looking for a solution to this. pushRow.updateCell() does not seem to do the job.

**Comment by mats-claassen** [comment]
It works for me just changing the `options`.

```swift
(form.rowBy(tag: "the_tag") as? PushRow<Emoji>)?.options = [💁🏻, 🍐, 👦🏼]
```
