### ISSUE TITLE
@IBOutlets not visible in XIBs

### ISSUE THREAD

**Issue by leondobnik** [xmartlabs/Eureka#1521]
Environment: Eureka 4.1, xCode 9.3 and iOS 11

First guys this framework is really awesome, but I have one issue and I wonder if you can check if this is my local issue, library bug or my misuse of library. So here it goes.

Your TextCell class suits my needs in terms of validation, but layout must be different. So the idea is to fully reuse already implemented TextCell, but define different nib. Here I come to the problem: in my custom cell nib I don't see Outlets defined by the TextCell - so I would be able to connect UILabel and UITextField to the outlets already defined in the TextCell class. (To be more precise TextCell inherits from _FieldCell, and in it there are two outlets defined: @IBOutlet public weak var textField: UITextField!, @IBOutlet public weak var titleLabel: UILabel?.

So the question is: should this be visible, or I am doing it wrong way?

Example conceptual implementation:
`
CustomTextTableViewCell.nib and following two classes:

class CustomTextTableViewCell: TextCell {
    
    // MARK: - Outlets
    
    required init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
    }
}

final class CustomTextRow: Row<CustomTextTableViewCell>, RowType {
    
    required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<CustomTextTableViewCell>(nibName: "CustomTextTableViewCell")
    }
}`

**Comment by mtnbarreto** [comment]
@leondobnik please follow second alternative @mats-claassen gave you.

**Comment by mtnbarreto** [comment]
same as #1460
