### ISSUE TITLE
Custom Init OptionsRow

### ISSUE THREAD

**Issue by darnat** [xmartlabs/Eureka#1522]
I'm actually working on a project using the last version of Eureka and Swift 4. I'm facing a problem.
I created a customRow, but I need to inject some params in this custom row. I tried to create a custom init but nothing work, any Idea ?
Here is my custom init
```
required init(tag: String?, customParam: String) {
        self. customParam = customParam
        super.init(tag: tag)
}
```
And my call :
`<<< CurrencyRow(tag: "CurrencyRow", customParam: String)`
But I get this error on the line above :

> Type of expression is ambiguous without more context

**Comment by zenghaojim33** [comment]
Encounter the same problem, can you share the solutions?

**Comment by rizwan95** [comment]
Same problem, can you please help us with this issue?

**Comment by rizwan95** [comment]
Any solution for this problem?

**Comment by mats-claassen** [comment]
The `init` commonly used is the one defined in the `RowType` protocol

```swift
init(_ tag: String?, _ initializer: (Self) -> Void)
```

which then calls the `init(tag: String?)` method of the row.

So for adding a custom init, add the `initializer` parameter apart from your custom parameters, and call `super.init(_ tag: String?, _ initializer: (Self) -> Void)` inside your init.

**Comment by rizwan95** [comment]
Thanks for the reply. @mats-claassen

**Comment by dazeili** [comment]
@mats-claassen I cant figure it out. I cant call the super.init from RowType. Can you provide some detailed sample code please? Thanks man!

**Comment by mats-claassen** [comment]
Add an init like this, with all the params you want:

```swift
convenience init(tag: String?, customParam: Int, initializer: (<#your row type#>) -> Void) {
        self.init(tag, initializer)
    }
```

**Comment by dazeili** [comment]
Nice. That worked! Thanks!
