### ISSUE TITLE
Having a row of one type but exporting just a portion of the row value

### ISSUE THREAD

**Issue by cesaredecal** [xmartlabs/Eureka#1526]
I have a row of type Currency (which is a struct I have created that contains properties such as currency code, country code, etc.). When I call form.values() I would only like to export the currency code (not the object) so that I can easily send the string value to the server. Is there an easy way to do it instead of parsing the form.values dict directly?

**Comment by mtnbarreto** [comment]
Hi @cesaredecal , 
There is no another way to do so. 
You will have to get the value for the specific row key and reset it.
