### ISSUE TITLE
How do you change language for DatePick in DateInlineRow? - 2

### ISSUE THREAD

**Issue by IamBeginnerDeveloper** [xmartlabs/Eureka#1527]
Sorry, I  worried how to change  language for DateInlineRow.
I use Eureka for the first time Today.
I search older issues below ↓ but I can't.
https://github.com/xmartlabs/Eureka/issues/501

Below MyCode1 & MyCode2 doesn't work.
I want' to use this useful library.

-------------------------------------
MyCode1
-------------------------------------
class ViewController: FormViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
		
		DateRow.defaultCellSetup = { cell,row in
			cell.datePicker.locale = NSLocale(localeIdentifier: "jp_JP") as Locale
		}
		
		form +++ Section(label)
			<<< DateInlineRow() {
				$0.title = "test"
		}

-------------------------------------
MyCode2
-------------------------------------
class ViewController: FormViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
		
		form +++ Section(label)
			<<< DateInlineRow() {
				$0.title = "test"
				let formatter = DateFormatter()
				formatter.locale = .current
				formatter.dateStyle = .short
				$0.dateFormatter = formatter
			}

**Comment by gudleyd** [comment]
How you solved this problem?

**Comment by IamBeginnerDeveloper** [comment]
I think that was like this
https://github.com/xmartlabs/Eureka/issues/501

DateInlineRow.InlineRow.defaultCellSetup = { cell,row in
   cell.datePicker.locale = Locale(Identifier: "en_US")        
 }



Mistake of MyCode1
 Wrong: "jp_JP"
Correct: "ja_JP"
