### ISSUE TITLE
Cell row height bug with latest version?

### ISSUE THREAD

**Issue by cesaredecal** [xmartlabs/Eureka#1528]
Hi, I've updated my dependencies a few days ago and I've found that `cell.height = { return 250 }()` no longer works to set the cell height? Neither `row.cell.height = { return 250 }()` works, it doesn't matter where I put it `cellUpdate`/`cellSetup`/etc. Any hints on what's going on?

**Comment by cesaredecal** [comment]
Turns out it wasn't an issue with this library.

**Comment by EthanDoan** [comment]
Hi cesaredecal,
Can you share what is the cause of the issue?

**Comment by cesaredecal** [comment]
@EthanDoan I don't remember unfortunately :(
