### ISSUE TITLE
Cannot change background color of PushRow

### ISSUE THREAD

**Issue by prbaron** [xmartlabs/Eureka#153]
Hello,
I am trying to change the background color of the PushRow but it is not working. The `to.tableView` is equal to nil in the `onPresent` function.

```
<<< PushRow<Category>("category") {
                $0.title = NSLocalizedString("ENTRY_CATEGORY", comment:"")
                $0.selectorTitle = NSLocalizedString("ENTRY_CATEGORY_SUBTITLE", comment:"")
                $0.options = Array(categories)
                $0.value = defaultCategory
                $0.hidden = Condition.Function([]) { form in
                    return categories.count == 0
                }
            }.onChange{ row in
                if row.value == nil {
                    row.value = CategoryRepository.getNoCategory()
                }
            }.onPresent{ from, to in
                to.tableView?.backgroundColor = UIColor.appBackgroundColor()
                to.view.backgroundColor = UIColor.appBackgroundColor()
            }

```

Best Regards

**Comment by schweigechris** [comment]
Try this one

```
.onPresent{ from, to in
     to.view.layoutSubviews()

     // Appearance
     to.tableView?.backgroundColor = UIColor.appBackgroundColor()
}
```

**Comment by akabab** [comment]
@schweigechris this actually work, thanks. Still a pain to setup a whole dark theme, check #269

**Comment by alexvazquez** [comment]
Hi, I have the same issue and I have done:

```
 }.onPresent{ from, to in
              
                to.view.layoutSubviews()
             
                to.tableView!.backgroundColor = UIColor.lightGrayColor()
           
            }
```

And its not working. Any clue? Did I miss something?

**Comment by iIias** [comment]
This worked for me, thanks.
Hope you were able to fix your issue as well

**Comment by vyatri** [comment]
i'm using 3.1.0 and this works:

`<<< PushRow<String>() {
                $0.title = "title"
                $0.options = ["foo", "bar"]
                $0.value = "foo"
                $0.tag = "title"
                }.onPresent({ from, to in
                    to.view.layoutSubviews()
                    to.tableView?.backgroundColor = UIColor.lightGrayColor()
                })`

**Comment by eliburke** [comment]
A quick caveat for anyone using this technique.. layoutSubviews() will trigger setupForm. If you are trying to use the sectionKeyForValue callback, you need to set it BEFORE you call layoutSubviews. 

e.g. this won't work

    .onPresent { (parentForm, form) in
        // force the framwork to instantiate the tableView
        form.view.layoutSubviews()
        form.tableView.backgroundColor = UIColor.purple

        // oops! too late to set this!
        form.sectionKeyForValue = { option in
             return "FooBar"
       }
    }

I am also still trying to find a way to set the color of the title in the Header/Footer views of the PushRow table. Anyone have any luck with that?

**Comment by Haseena-Sagoul** [comment]
Those who are using **PushRow table with Header/Footer** can use this snippet!

```
.onPresent { (parentForm, form) in
    // This sets the section for the table.
    form.sectionKeyForValue = { option in
         return "Section Title"
   }
    // After setting up the section, this forces the framework to instantiate the tableView.
    form.view.layoutSubviews()
    form.tableView.backgroundColor = UIColor.lightGray
}
```
