### ISSUE TITLE
How can I handle nested options with Eureka (with PushRow or PickerRow)

### ISSUE THREAD

**Issue by zenghaojim33** [xmartlabs/Eureka#1533]
I want to find a general solution to handle nested options nicely (e.g. select the country first and select the city, from json data like    `{
      "Afghanistan": [
        "Herat",
        "Kabul",
        "Kandahar",
        ...
      ],
      "Albania": [
        "Elbasan",
        "Petran",
        "Pogradec",
        ...
      ],
      ...
   }`).  However `options` can only be assign with items array.  Is there any clean and nice solution to this problem?

**Comment by mats-claassen** [comment]
I would go with one row to select the country and another row for the city.

You then disable the city row until the country row has a value. And using the `onChange` in country row you change the options in the city row (and reset its value to nil)
