### ISSUE TITLE
Eureka gets extremely slow when creating really large forms (>1h for 300rows)

### ISSUE THREAD

**Issue by M-HERBRICH-ITC** [xmartlabs/Eureka#1537]
Using...
Eureka 4.1.1
Xcode Version 9.3 (9E145)

With small forms my app is working well using Eureka. But now I need to show a really large form with about 300-400 rows. Eureka gets really slow. When building the form, CPU usage goes to 100% and memory is growing constantly. After an hour of waiting the form is still not finished building and I have to stop it.
I added some console printouts to localize the problem. It's starting really fast, but as more rows are added, it gets slower and slower.

I guess it's the wasAddedTo function from Eureka framework which is called after added a new row and it iterates all existing rows to add observer, validate hidden and validate enabled. But this is only an assumption from me.
If so, is it possible to skip the validation and run it one time after the form is fully build?

Do you have similar experience with large forms and is there a reference about how much rows are possible?

**Comment by mats-claassen** [comment]
We have had similar comments about big forms. My question is, why do you have so many rows in the form? Does it have to be a form and not simply a table view?

Something you could try is to add all the rows at once to the form to see if that changes something.

**Comment by mtnbarreto** [comment]
Closing due to lack of response.
