### ISSUE TITLE
Make custom operators optional

### ISSUE THREAD

**Issue by ollieatkinson** [xmartlabs/Eureka#154]
The custom operators are difficult to debug quickly, as new members join a project there is a steeper learning curve to understand what is going on.

These operators should be optional and should call straight through to functions.

Using this approach you won't be deciphering over the differences of ++== and +++=.

**Comment by RobDay** [comment]
I fully agree with this.  The major risk with custom operators is that it makes code less obvious.  Custom operators do have utility, but they can easily be abused.  Having no fallback for custom operators really limits the project.

**Comment by patters** [comment]
+1. Leaning on an entire *set* of custom operators to achieve API "fluency" points to the flaws in the underlying design of those APIs.

**Comment by mtnbarreto** [comment]
@ollieatkinson @RobDay @patters  I added some notes about how to use Eureka without using its custom operators.
For more info, take a look here:
https://github.com/xmartlabs/Eureka/tree/document/154#dont-want-to-use-eureka-custom-operators
