### ISSUE TITLE
Problem with selecting field rows

### ISSUE THREAD

**Issue by BertPorter** [xmartlabs/Eureka#1541]
Environment: Eureka 4.1.1, Xcode 9.3 (9E145) and iOS 11.3

On a form, I am able to edit fields and then later on the fields are frozen. But not all the fields.

I determined when this happens. Every time I display another Eureka form in a separate part of the app and then display this form, the fields are frozen. Consistently the same fields are frozen and always after the same action.

Through print statements I determined that row.isDisabled is being set to true - somehow?

My workaround was to add the following code in viewDidLoad:
        DoubleRow.defaultCellSetup = { cell, row in
            row.disabled = false
        }
        
I created my own row type for Doubles as DecimalRow wasn't working well for me. I am attaching that code in case I am doing something that is causing this problem.

Would you like me send you the code for my app? I don't want to publish it on GitHub for obvious reasons. My brute force solution works, but it would be preferable to correct the problem.

Please advise.

**Comment by mats-claassen** [comment]
I don't see anything in your code that would disable those rows. I would search in the whole project to see if somewhere you set `disabled` to true.

**Comment by BertPorter** [comment]
I am not setting disabled to true on this form. Somehow it is being set by itself.

**Comment by BertPorter** [comment]
I do set disabled = true on another form. But this form is loaded after that form is no longer loaded.

**Comment by BertPorter** [comment]
I am attaching screen shots to show the steps that happen before the rows are frozen. This is consistent across iPhone X, iPad Pro, Simulator.
[Flow of Issue.pdf](https://github.com/xmartlabs/Eureka/files/1992640/Flow.of.Issue.pdf)

**Comment by BertPorter** [comment]
Resolved.
In viewDIdLoad() of another FormViewController:
        DoubleRow.defaultCellSetup = { cell, row in
            row.disabled = true
        }
I didn't realize this was global.
So it is still active in the current view controller.
