### ISSUE TITLE
DateTimeRow fields are empty when i edit the form with preset values

### ISSUE THREAD

**Issue by sangram-appzop** [xmartlabs/Eureka#1542]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by mtnbarreto** [comment]
hi @sangram-appzop ! 
Do you mind sharing the row set up code and the code where you set the form values?

**Comment by dheeraj-appzop** [comment]
<<< DateTimeRow(){ row in
                row.title = "Date"
                row.tag = "2"
                row.value = Date()
            } .cellUpdate() { cell, row in
                if row.isValid {
                }
                else{
                }
                cell.datePicker.datePickerMode = .dateAndTime
            }
this is the row in the form and when I click the cell in the table view its value is current date instead of the one which is stored in database.
I am retrieving the date from database and setting  it as below

        self.form.setValues(["2" : self.date])

**Comment by dheeraj-appzop** [comment]
How do I set the date value while editing the form?

**Comment by mtnbarreto** [comment]
If the form was already presented you should reload the row.

> `self.form.setValues(["2" : self.date])` seems okay.

**Comment by dheeraj-appzop** [comment]
self.form.rowBy(tag: "2")?.reload()
displays an empty value..
Until we again click on the row and select the time it does not display any value.

**Comment by dheeraj-appzop** [comment]
self.form.rowBy(tag: "2")?.reload() works only if we are sending the proper date format as expected in the row.
It is working as expected.

**Comment by mats-claassen** [comment]
@dheeraj-appzop What is the status of this? Is it working?

**Comment by abhishek-inxite** [comment]
Yes.It is working as expected.
Thanks..

**Comment by dheeraj-appzop** [comment]
Yes it is working as expected..
Thanks..

**Comment by mats-claassen** [comment]
So we can close this
