### ISSUE TITLE
Swipe with UITableViewRowAction with Eureka 4.1.1

### ISSUE THREAD

**Issue by epigore** [xmartlabs/Eureka#1543]
Hi,

I'm upgrading my application from Xcode 9.2 to 9.3 and have a problem with Swiping.

With Eureka 4.0.1 I used UITableViewRowAction for Swipe Actions but with the current version 4.1.1 the method **tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?** is not called any more.

My old swipe method:
```swift
@objc(tableView:editActionsForRowAtIndexPath:)
open func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]? {
...
}
```

This method was added with 4.1.0 and on 07.05.2018 there is commit to change it from public to open (TableView actions functions are open instead of public. #1529)

```swift
open func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?{
    guard let actions = form[indexPath].trailingSwipe.contextualActions as? [UITableViewRowAction], !actions.isEmpty else {
        return nil
    }
    return actions
}
```

The other two methods for leading and trailing swipe are working but not editActionsForRowAt.

```swift
@available(iOS 11,*)
open func tableView(_ tableView: UITableView, leadingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
    return form[indexPath].leadingSwipe.contextualConfiguration
}

@available(iOS 11,*)
open func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
    return form[indexPath].trailingSwipe.contextualConfiguration
}
```
I would like to continue to use my old swipe method with UITableViewRowAction (override).
Is this a bug or am I doing something wrong?

**Comment by mtnbarreto** [comment]
Hi @epigore,

Since Eureka version 4.0, swipe actions is supported natively so you should use Eureka way to declare them.  

Please follow https://github.com/xmartlabs/Eureka#swipe-actions to migrate your code.
