### ISSUE TITLE
Determine when footer with <>/Done is active

### ISSUE THREAD

**Issue by donhill** [xmartlabs/Eureka#1544]
I am not sure if this is the correct place to ask questions. 

I would to know if there is a callback that will tell me when the footer with <>/Done is active/inactive? It looks like this has todo with editing mode but not sure. The problem I face is that my value class gets updated in cellUpdate and if I have changed the value it doesn't get updated until I navigate away.

**Comment by mtnbarreto** [comment]
StackOverflow is the place to ask questions regarding how to use Eureka as contribution guidelines indicates. 

Every row has a `updateCell()` method that updates the row UI. 
`cellUpdate` it's trigger each time the cell appears on screen so it's wired that your row values changes its value from `cellUpdate`.
