### ISSUE TITLE
Multivalued Section index is not updating 

### ISSUE THREAD

**Issue by umerabduljabbar** [xmartlabs/Eureka#1545]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by umerabduljabbar** [comment]
Eureka version is 4.1.1
Xcode Version 9.3 (9E145)

Eureka is not updating index of previously created row in multivalued section when I updated to eureka for swift 4.1. Before updating it was working fine but now I can't do many things. Please help me to fix this issue. 
*I am not good at english

<img width="375" alt="screen shot 2018-05-16 at 5 10 02 pm" src="https://user-images.githubusercontent.com/21955126/40116108-0b739680-592c-11e8-8b8e-e67ecf7b397c.png">

I added 5 rows in above screenshot and when I deleted row index 2 and added another row it rows two same title image.
I tried updating all rows but it didn't work.

<img width="375" alt="screen shot 2018-05-16 at 5 10 16 pm" src="https://user-images.githubusercontent.com/21955126/40116111-0e4daf26-592c-11e8-9dff-54cb660305a5.png">

Thank You

**Comment by mtnbarreto** [comment]
Hi @umerabduljabbar , the index parameter represent the place where the new row will be added. 
If you want a unique index you can discard the index parameter and use another value such as a static var.
