### ISSUE TITLE
Removing an entire Section error.

### ISSUE THREAD

**Issue by iguron** [xmartlabs/Eureka#1548]
Hi,

I´m trying to delete an entire section (assuming that all rows in the section would be deleted also).

I check that I have two sections and I want to delete the second one, with tag "abc".

I tried.

self.form.remove(at: 1)
or
self.form.remove(at: (form.sectionBy(tag: "otherFields")?.index!)!)

in both cases with the error:
Can't remove from an empty collection

the idea is to "replace" the whole section with a new one, so I´m deleting and adding again.

Thanks in advance

**Comment by mtnbarreto** [comment]
this is a basic feature and should work properly, I guess you are doing something wrong when creating the form.
Could you please share all the form code?

**Comment by iguron** [comment]
I´m not doing anything strange.

I have a class with a two functions each one creates one section.

func cargarCamposGenerales(form:Form ) -> Void{...
func cargarCamposOpcionales( form:Form, idCategory:Int ) -> Void{...

--both functions starts with similar code:

 form +++ Section("General Data"){
            $0.header?.height = { 30 }
            $0.tag = "generalFields"
        }

From the main view I´m calling these functions like

cargarCamposGenerales(form:form )
cargarCamposOpcionales( form:form, idCategory:0 )

QUESTION. Should I initialize somehow the "form" variable? I´m not doing it...

The problems is that in the first section I have a pushRow for the "category" and according to the returned value, I need to update entirely the second section. The best way I found, is to remove the section and create the rows again in the beginning of the second function.

Thanks in advance.

**Comment by mats-claassen** [comment]
Another way to do what you want is using the `hidden` variable. You would then add all the sections to the from and only show the one that belongs to the chosen category.

As for removing and adding sections, this should like just the same way as you would do it with replacing elements in arrays.
