### ISSUE TITLE
How to change title of UITableViewRowAction title to another

### ISSUE THREAD

**Issue by IamBeginnerDeveloper** [xmartlabs/Eureka#1558]
Sorry, I want to change title of UITableViewRowAction "Delete" to another string like "Trash".
But I don't know how to change this.
Could you teach me this ? Please.

[Info]
● I want to to change delete title , so  I write "override  editActionsForRowAt ",
   But this error was shown "Overriding non-open instance method outside of its defining module"
   -> Can't Change the title.
●　I'm using this module and implements like sample.
"EurekaExample" -> "MultiValued Examples" -> "MultiValued TextField" -> "MultivaluedController"
●　Xcode 9.3.1 / iOS 11

<img width="289" alt="screenshot" src="https://user-images.githubusercontent.com/38688802/40572340-39c72870-60e4-11e8-8e09-ce890023e701.png">
<img width="853" alt="screenshot3" src="https://user-images.githubusercontent.com/38688802/40572636-00b501da-60ec-11e8-9b25-d248e0c4bf02.png">

**Comment by epigore** [comment]
Hi,
I have a similar problem [(Issue 1543)](https://github.com/xmartlabs/Eureka/issues/1543) and the answer is to use the new SwipeAction of Eureka.
https://github.com/xmartlabs/Eureka#swipe-actions

**Comment by IamBeginnerDeveloper** [comment]
Thank you for your reply ! !! 

I notice my wrong way, and the solution (in this case) is below...sorry.
I don't want to swipe this table view cell .

I'll use your teaching method  at  another tableView !!

-----------------------
I can solved this issue this easy code.....sorry.

`func tableView(_ tableView: UITableView, titleForDeleteConfirmationButtonForRowAt indexPath: IndexPath) -> String? {
		return "Trash"
	}`
