### ISSUE TITLE
FieldRow onCellSelection does not trigger when clicking on textField

### ISSUE THREAD

**Issue by TooLilTooMuch** [xmartlabs/Eureka#1559]
Eureka 4.1.1
Xcode 9.3.1
iOS 11.0+

Is it expected that .onCellSelection does not trigger unless you are clicking on the textLabel / title rather than the textField side of the row? All I am trying to do is clear the field when a user clicks on it but it would only clear if they happen to click on the left side of the row ...

```
<<< IntRow(K.SESSIONFIELD.buyIn) {
            $0.title = K.SESSIONFIELD.buyIn
            $0.value = sessionResult?.buyIn ?? 0
            $0.placeholder = "Enter Buy In"
            $0.formatter = SessionFieldFormatter.getFormatterForCurrency()
            $0.add(ruleSet: getCurrencyRuleSetInt())
        }.cellUpdate { cell, row in
            print ("##cellUpdate is called")
            row.value = !row.isValid ? 0 : row.value
        }.onChange { row in
            self.form.rowBy(tag: K.SESSIONFIELD.pnl)?.updateCell()
        }.onCellSelection({ (cell, row) in
            print("##cellSelection is called")
            if row.value == 0 || row.value == nil {
                cell.textField.text = ""
            }
        })
```

**Comment by damiancesar** [comment]
@TooLilTooMuch this should give you the functionality you're looking for.

```
.onCellHighlightChanged { cell, row in
    if row.isHighlighted {
        row.value = nil
    }
}
```

**Comment by TooLilTooMuch** [comment]
@damiancesar   Thanks. I was a little anxious to get this done so I rewrote my formatter to deal with the scenario differently. I remember trying .onCellHighlightChanged and was having some other problem. Will try it again in my next form!
