### ISSUE TITLE
Triggering 'onChange' from custom row/cell

### ISSUE THREAD

**Issue by mbopp** [xmartlabs/Eureka#156]
I've written a custom row that contains two textfields and stores it's data in a struct containing two values.  I update the two values of this struct whenever the two textfields in my custom cell change.  What do I need to call in order for the `onChange` event callback handler to fire, as it does not seem to be happening at this time.  Is there a method I can call to let the row know values have been changed?

Thanks so much.

**Comment by mbopp** [comment]
I think I have found the answer, or at least a solution.  It looks like Eureka uses `didSet` to trigger `onChange`.  Changing a property/member of a struct does not cause `didSet` to execute.  So my solution is to set the value of my custom row with a new instance of the custom struct every time the value of either textfield changes.  

With my custom struct

    public struct RangeResult {
      var lower: NSNumber?
      var upper: NSNumber?
    }

Instead of...

    self.row.value?.lower = newValue

I am doing (where `RangeResult` is my custom struct for the row value)

    self.row.value = RangeResult(lower: newValue, upper: self.row.value?.upper)

**Comment by mtnbarreto** [comment]
@mbopp Is the custom row value type `Equatable`? 
Has the custom row added to a section and the section added to a form? 
Do you set up the delegate of the form?

Make sure that your custom row code updates row.value whenever any of the text fields' text change.

This is the eureka source code that invokes onchange callback, see `callbackOnChange?()`. It would be great if you can debug these lines of code right after you update the custom row value. 

```swift
public class RowOf<T: Equatable>: BaseRow {
    
    /// The typed value of this row.
    public var value : T?{
        didSet {
            guard value != oldValue else { return }
            guard let form = section?.form else { return }
            if let delegate = form.delegate {
                delegate.rowValueHasBeenChanged(self, oldValue: oldValue, newValue: value)
                callbackOnChange?()
            }
            guard let t = tag else { return }
            if let rowObservers = form.rowObservers[t]?[.Hidden]{
                for rowObserver in rowObservers {
                    (rowObserver as? Hidable)?.evaluateHidden()
                }
            }
            if let rowObservers = form.rowObservers[t]?[.Disabled]{
                for rowObserver in rowObservers {
                    (rowObserver as? Disableable)?.evaluateDisabled()
                }
            }
        }
    }

..
```

**Comment by mbopp** [comment]
Thanks for the fast response mtnbarreto.  I think I am using the `Equatable` protocol correctly.  Though I'm not certain, and maybe that is the problem.

**Comment by mtnbarreto** [comment]
@mbopp :+1: , sorry i forgot about your point, `Do not use mutating properties on structs`. it will not invoke `didSet` and `onChange` callback will not be invoked as a result.

Thanks for the clarification!
