### ISSUE TITLE
Issue using List Sections

### ISSUE THREAD

**Issue by ArsalanWahid** [xmartlabs/Eureka#1564]
When using the code for List sections I keep getting error for

Use of undeclared type `ImageCheckRow`

Any Reasons why , Im using the FormViewController class... and have import the package as well.

**Comment by mtnbarreto** [comment]
`ImageCheckRow` isn't part of Eureka core (they are included in Example project) so you will have to include `ImageCheckRow` files to your project. in oder to use it.
