### ISSUE TITLE
TitleLabel from nil/empty valued Rows go out of the form after validation

### ISSUE THREAD

**Issue by adrianodiasx93** [xmartlabs/Eureka#1567]
When validating a row with a nil/empty value, the tittleLabel weirdly go out of the form. I am using:

`$0.add(rule: RuleRequired(msg: someStringVariable))` on the cell.

And the following when the green button is pressed.
```swift
func isFormValid() -> Bool {
        var satisfied = true
        for row in form.allRows {
            _ = row.validate()
            if !row.isValid && !row.isHidden {
                satisfied = false
                let alert = SCLAlertView(newWindow: ())
                alertaErro!.showError("Error", subTitle: row.validationErrors.first?.msg ?? "",
                                      closeButtonTitle: "Close", duration: 0)
                break
            }
        }
        return satisfied
    }
```
Besides the one in the screenshot, which is a default PushRow, the same occurs to the one before it, which is a default LabelRow. Same rule used.

I tried with the last two releases, as well directly from `master` and got the same problem. Apparently the error only occurs with nil values/RuleRequired. I use RuleGreaterOrEqualThan on the DecimalRow and works great.

<img width="327" alt="screen shot 2018-06-04 at 11 17 18 pm" src="https://user-images.githubusercontent.com/5974969/40951473-83712d5c-684d-11e8-9176-32761ffacf65.png">
<img width="323" alt="screen shot 2018-06-04 at 11 17 27 pm" src="https://user-images.githubusercontent.com/5974969/40951474-8391308e-684d-11e8-9fe3-ef5f113dde8e.png">

Could you guys help me? I appreciate the attention!

**Comment by mtnbarreto** [comment]
Could you reproduce the issue using Eureka Example project and share it so I can take a look..?
Seems to me this has to do with your project because Push Cell is just a default UIKit cell with its corresponds default layout.

**Comment by adrianodiasx93** [comment]
@mtnbarreto thanks for the quick response. I believe the use of this lib in my project is quite default, but after work I gonna follow your suggestion and let you know.

**Comment by adrianodiasx93** [comment]
@mtnbarreto haven't be able reproduce easily the bug on the Example project. Didn't have much time to really try though (use all the settings which I use on my project). I will close it for now and get back to you when I have more info.

Thanks!
