### ISSUE TITLE
Issue with CreditCardRow and Eureka with swift 4.1

### ISSUE THREAD

**Issue by iishabrawy** [xmartlabs/Eureka#1572]
i try to use CreditCardRow in my app and the swift version is 4.1

and this is the error message appear to me when i try to make 

`pod install
`
<img width="860" alt="screen shot 2018-06-12 at 5 36 17 am" src="https://user-images.githubusercontent.com/6254386/41268973-fc1dfb3a-6e02-11e8-96d7-c547b1777810.png">

so i can't use Eureka 4.1.1 or CreditCardRow or ImageRow

so i hope to guide me to fix this issue

**Comment by mats-claassen** [comment]
You should use `CreditCardRow` version 3.0.0. How does you Podfile line look like?

**Comment by mats-claassen** [comment]
This is a `CreditCardRow` issue
