### ISSUE TITLE
Suggestion to contract/expand sections on large forms.

### ISSUE THREAD

**Issue by iguron** [xmartlabs/Eureka#1577]
Hi guys,

We are developing an App with a very large form on it, with many sections.

Our idea is to allow the user to contract and expand sections.  (Showing/Hidding the whole Section)

Is there any event to catch the click on the section?

Any other approach would be appreciated.

**Comment by mats-claassen** [comment]
To implement the section collapse/expand functionality I recommend adding a header view to the section in which you add a button or UITagGestureRecognizer and when that is tapped you show the rows, for example by setting its `hidden` value to false.

You could also use a row outside of each section and use the `hidden` variable of the section to hide/show it depending on this row.

**Comment by mats-claassen** [comment]
You can set `hidden` to a boolean like `row.hidden = true`
