### ISSUE TITLE
Generic Picker version of DateRow

### ISSUE THREAD

**Issue by ramblex** [xmartlabs/Eureka#158]
Is there a version of DateRow where I can put in my own list of options? i.e. where the picker is hidden by default. I'm aware there's a PickerRow but that seems to show the Picker before the user taps on the input, I'd like the UIPickerView to be hidden until the user taps the input.

PickerInlineRow is almost there but ideally the picker would appear at the bottom of the screen as in DateRow.

If there isn't something already where would be a good starting point to implementing my own?

**Comment by mtnbarreto** [comment]
Currently Eureka doesn't provide such row but i think is a good row to add. 

The row class could be `InputPickerRow` or `PickerInputRow`.

For now let's support only one component UIPickerView of type T, so we will have to implement the row generic type and the cell generic type.

```swift
// row
public class _PickerInputRow<T where T: Equatable> : Row<T, PickerInputCell<T>>  {
..

public final class PickerInputRow<T where T: Equatable> : _PickerInputRow<T>, RowType {
..
.

//cell
public class PickerInputCell<T where T: Equatable> : Cell<T>, CellType, UIPickerViewDataSource, UIPickerViewDelegate {
```

Taking a closer look at `DateRow`, `PickerRow` and `PickerCell` should make things easier.

Let me know if i can help in anything else.

**Comment by geitoodevs** [comment]
I made a Pull Request for this issue.
Greetings, 
Miguel.

**Comment by mats-claassen** [comment]
`PickerInputRow` is the solution.

**Comment by mtnbarreto** [comment]
We are about to merge https://github.com/xmartlabs/Eureka/pull/1540 which provides multipole component pickerViews functionality.
