### ISSUE TITLE
Warning in Xcode 9.4 (that becomes error in Xcode 10)

### ISSUE THREAD

**Issue by waterskier2007** [xmartlabs/Eureka#1581]
In Xcode 9.4 (using 11.0 deployment target) I get the following warning

`/Users/<username_redacted>/Documents/Projects/<project_redacted>/Pods/Eureka/Source/Core/SwipeActions.swift:40:16: Overlapping accesses to 'action', but modification requires exclusive access; consider copying to a local variable`

This becomes an error in Xcode 10. I know Xcode 10 is a beta, but I just thought I would raise this early

**Comment by funkenstrahlen** [comment]
@waterskier2007 Why is this closed? I see the same error in Xcode 10.

**Comment by mats-claassen** [comment]
This has been fixed in commit b0f9adc13a780e76fae25bf00f9adc49726f0d95 so it is in master branch.

**Comment by waterskier2007** [comment]
@funkenstrahlen, yeah, i opened it and then realized after I forked the code that it had already been fixed, as @mats-claassen said :)
