### ISSUE TITLE
SliderRow UI bug

### ISSUE THREAD

**Issue by Ferannor** [xmartlabs/Eureka#1585]
Hi everybody!

The SliderRow UI bug is back on the last version... 😢
The cell is perfect when you have other rows in the form but you have only a SliderRow in your form this append:
<img width="266" alt="capture d ecran 2018-06-28 a 10 12 34" src="https://user-images.githubusercontent.com/1252443/42021873-14e626c2-7abc-11e8-86c7-33a0666b3e9b.png">

You can test it by removing all cells in RowsExampleViewController.swift on the Example projet. 

I've the same result on my own app.

**Comment by mats-claassen** [comment]
Hi @Ferannor, it seems somehow `updateConstraints` is not getting called when this is the only row. I haven't tested it a lot but adding `setNeedsUpdateConstraints()` to the `setup` method fixes this issue. It should work calling that from `cellSetup` as a workaround.

**Comment by Ferannor** [comment]
I can confirm that `setNeedsUpdateConstraints()` in the `setup` method works but not in the `cellSetup`.
