### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by gbhall** [xmartlabs/Eureka#1587]
Eureka 4.2.0
Xcode 9.4.1

DoublePickerRow.swift
Line 88: `let a = pickerRow.selectedFirst()`

![screen shot 2018-07-01 at 12 14 34 pm](https://user-images.githubusercontent.com/1142713/42130978-857f98e6-7d28-11e8-97f1-bae97123b108.png)

**Comment by mats-claassen** [comment]
@gbhall Can you give us some context? What are you executing? How are you setting up the form?

**Comment by gbhall** [comment]
Pretty sure it's from this setup:
```swift
            +++ MultivaluedSection(multivaluedOptions: [.Insert, .Delete],
                                   header: "Downtime Log") {
                                    $0.tag = "downtimes"
                                    
                                    let mins = Array(1...1440)
                                    let options = ["Mechanical fault", "Hydraulic fault", "Electric fault", "Crusher closed", "Remove steel", "Refueling", "Crib", "No ore"]
                                    
                                    $0.multivaluedRowToInsertAt = { index in
                                        return DoublePickerInlineRow<String, Int> {
                                            $0.title = "Fault, Mins"
                                            $0.firstOptions = { return options}
                                            $0.secondOptions = { _ in return mins}
                                        }
                                    }
                                    $0 <<< DoublePickerInlineRow<String, Int> {
                                        $0.title = "Fault, Mins"
                                        $0.firstOptions = { return options}
                                        $0.secondOptions = { _ in return mins}
                                    }
                }
```

And it happens when selecting the second option (mins), but not always. It happens infrequently, but when it does it's serious as the form is long and a user will lose all data. 


I think the issue in `DoublePickerRow.swift` within the library. 
Line 112 is:
```swift
    func selectedFirst() -> A {
        return value?.a ?? firstOptions()[0]
    }
```

where `firstOptions()[0]` is unwrapping a sometimes optional value. 

You could do something like:
```swift
extension Collection {
    /// Returns the element at the specified index if it is within bounds, otherwise nil.
    subscript (safe index: Index) -> Element? {
        return indices.contains(index) ? self[index] : nil
    }
}

func selectedFirst() -> A? {
    return value?.a ?? firstOptions()[safe: 0]
}
```

**Comment by mats-claassen** [comment]
Hi @gbhall, I tried that code and it did not crash.

However, I would define `mins` and `options` outside of the section. Save them as variables in your form or so. This might fix some crashes.

Otherwise you might have a problem elsewhere in your code

**Comment by gbhall** [comment]
I've just tried that. I don't always get a crash, only once I've filled out the rest of my forms and scrolling up and down through the values multiple times. 

Just got a new crash:
`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

In `DoublePickerRow.swift`, line `64` `pickerRow.displayValueForSecondRow(pickerRow.secondOptions(pickerRow.selectedFirst())[row])`


```swift
    open override func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        if component == 0 {
            return pickerRow.displayValueForFirstRow(pickerRow.firstOptions()[row])
        } else {
            return pickerRow.displayValueForSecondRow(pickerRow.secondOptions(pickerRow.selectedFirst())[row])
        }
    }
```

![screen shot 2018-07-08 at 6 19 29 pm](https://user-images.githubusercontent.com/1142713/42418835-8516f170-82db-11e8-815b-b2f5c5357ec7.png)

**Comment by gbhall** [comment]
I have to go back to that fact that the crashes are caused by pickerRow being nil. 

For whatever reason, using a `DoublePickerInlineRow` within a `MultivaluedSection` and clicking 'Add' and selecting new values in quick succession sometimes causes `pickerRow` to be nil.

The declaration for `pickerRow` shouldn't be declared as a forced unwrap, because currently the library cannot fail gracefully when `pickerRow` is nil. I think a change should be made to the library, it's unsafe to force unwrap when you're not guaranteed it'll never be nil. 

```swift
 private var pickerRow: _DoublePickerRow<A, B>! { return row as? _DoublePickerRow<A, B> }
```
