### ISSUE TITLE
Accessing TextRow textField property

### ISSUE THREAD

**Issue by flizana** [xmartlabs/Eureka#1590]
I am using some TextRow's in a form built entirely with Eureka. Although I can get the cell's textField property, I cannot change the styling of the textField. Personally I want to change the clearButtonMode property of the text field inside TextRow. The following code is what I got, but no clear button appears while editing.

    <<< TextRow(){ row in
        row.tag = "textRow"
        row.title = "Some Text"
        row.cell.textField.clearButtonMode = .whileEditing
    }

How can I acheive this?

**Comment by mats-claassen** [comment]
You should not do anything with the `cell` in the row initializer but in `cellSetup` or `cellUpdate` (look at the Readme's [callback section](https://github.com/xmartlabs/Eureka#callbacks-list))

**Comment by flizana** [comment]
I also tried adding `clearButtonMode` in `cellStup` without any luck.

**Comment by marbetschar** [comment]
@flizana you might want to set `.whileEditing` in `cellUpdate` like:

```
<<< TextRow(){
    ...
}.cellUpdate{ cell, row in
    cell.textField.clearButtonMode = .whileEditing
}
```

If this is not enough, add this line in `cellSetup` too. The reason for this is, there is some default logic in the cell's update handler which does modify the `textField.clearButtonMode` property under certain circumstances. For details see the code at: https://github.com/xmartlabs/Eureka/blob/da77260adccb52e30a68c07a8d056c14d3ac1910/Source/Rows/Common/FieldRow.swift#L210
