### ISSUE TITLE
Customisation of MultivaluedSection delete row animation

### ISSUE THREAD

**Issue by jacktiong92** [xmartlabs/Eureka#1592]
Dear Sir or Madam,

Just a quick question. I would like to know if it's possible to customise the delete row animation as shown below? The reason why it's because the animation seems to be a little buggy.

![ezgif com-add-text 1](https://user-images.githubusercontent.com/10499544/42321288-fb8e19da-808a-11e8-904f-b5db569ef77c.gif)

Environment:-
- Eureka: 4.2.0
- XCode: 9.4.1
- IOS: 11.4

P.S. Thank you for creating such an awesome framework guys!

Thank you.
Best Regards,
Jack Tiong

**Comment by mats-claassen** [comment]
Hi @jacktiong92, the animation can be changed by overriding the following function in your form view controller:

```swift
func deleteAnimation(forRows rows: [BaseRow]) -> UITableViewRowAnimation
```

Eureka does not implement these animations. It is part of iOS. What you change is what type of animation you want.

**Comment by jacktiong92** [comment]
Thank you for your prompt response sir. I tried to override the delete animation function as shown below.

`override func deleteAnimation(forRows rows: [BaseRow]) -> UITableViewRowAnimation {
        return .none
  }
`

But apparently the animation is still showing. Am I doing it wrongly?

**Comment by mats-claassen** [comment]
Possibly not. I found in other threads that `UITableView.deleteRows(at: , with:)` does not work consistently in iOS 11. This method is called with the animation you are passing to the `deleteAnimation` function.

This means it might be an iOS bug. Have a look at [this thread](https://github.com/RxSwiftCommunity/RxDataSources/issues/216) and [this StackOverflow post](https://stackoverflow.com/a/46350318/4708657) for more details and possible workarounds.

**Comment by jacktiong92** [comment]
I just verified that the `UITableView.deleteRows(at: , with:)` function will delete the row with the same animation style regardless of the specified animation in the second clause of the parameter. Well I guess we have no choice but to wait for Apple to fix this bug in the upcoming releases then.
Thank you so much for your support sir!
