### ISSUE TITLE
Adapt to Swift 4.2 version

### ISSUE THREAD

**Issue by SilongLi** [xmartlabs/Eureka#1601]
Error： “Overlapping accesses to 'action', but modification requires exclusive access; consider copying to a local variable”

Xcode Version 10.0 beta
Swift 4.2

**Comment by mats-claassen** [comment]
Are you using branch `Swift-4.2`?

**Comment by SilongLi** [comment]
Yes, when I upgraded the project to Swift-4.2, it reported the error.

**Comment by mats-claassen** [comment]
I mean Eureka branch Swift-4.2. It builds correctly in Xcode 10 beta

**Comment by JoJoTawk** [comment]
Multiple errors when using Eureka on Xcode 10, even the new update is not working.
I have multiple old projects using Eureka even after pod update still getting issues.
Are there any additional steps we need to follow in order to fix the problems?
Thanks
