### ISSUE TITLE
Insert row in first line

### ISSUE THREAD

**Issue by balancin** [xmartlabs/Eureka#1604]
How I can add one row in top of my section?

I'm using this way:
```
try section!
                <<< UserInfoRow() { row in
                    row.value = groupMessage
            }    
```

But this way only add on end of section.

Thanks!

**Comment by mats-claassen** [comment]
Have a look at this [Readme section here](https://github.com/xmartlabs/Eureka#dont-want-to-use-eureka-custom-operators).

Please ask usage questions on StackOverflow
