### ISSUE TITLE
VideoRow

### ISSUE THREAD

**Issue by Smiller193** [xmartlabs/Eureka#1606]
Has anyone made a video row?

**Comment by SebastianBO** [comment]
Any update on this?

**Comment by Smiller193** [comment]
i wish

**Comment by mats-claassen** [comment]
Duplicate of #33.

Just as I mentioned there, you should be able to do this using [ImageRow](https://github.com/EurekaCommunity/ImageRow) by changing a few variables of its ImagePickerController. As with most of these rows, the layout of the row will probably be different for each project.

**Comment by mats-claassen** [comment]
A [VideoRow](https://github.com/EurekaCommunity/VideoRow) is implemented in EurekaCommunity
