### ISSUE TITLE
minimumValue and maximumValue properties removed from SliderRow 

### ISSUE THREAD

**Issue by alldritt** [xmartlabs/Eureka#1608]
Hello,

I just did a pod update and found that the minimumValue and maximumValue properties of SliderRow have been removed.  I was using those.  The 0..10 range provided by default is a bit arbitrary.

- pod 'Eureka', '>= 4.0.0'
- Xcode 9.4.1, iOS 10.0+.

Cheers
-Mark

**Comment by FredRuniT** [comment]
let maxValue: Float = 1.0
                let minValue: Float = 0.25
                $0.cell.slider.minimumValue = minValue
                $0.cell.slider.maximumValue = maxValue

**Comment by espiegelberg** [comment]
It seems cell.slider has been renamed from cell.slider to cell.stepper. This worked for me:

cell.stepper.minimumValue = 1
cell.stepper.maximumValue = 10
