### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by angaaron** [xmartlabs/Eureka#1612]
Issue when typing in TextRow and while typing accidentally selecting an ActionSheetRow.

![screen shot 2018-07-18 at 10 25 10 pm](https://user-images.githubusercontent.com/22182876/42876143-df8dbb06-8ad9-11e8-9a2f-3e24f4c6cfef.png)

Also, another issue that when selecting a TextRow the Title text disappears when it should go blue like in the demos.

**Comment by mats-claassen** [comment]
Hi @angaaron I cannot reproduce either of those issues.

Could you show us how you set up the form for that to happen?

**Comment by angaaron** [comment]
Realised that there was actually nothing wrong, just had a create form statement that I had forgotten to delete which resulted in this issue.
