### ISSUE TITLE
How to implement SectionDelegate methods

### ISSUE THREAD

**Issue by flizana** [xmartlabs/Eureka#1614]
I can't seem to override the `SectionDelegate` protocol methods. As there is no documentation on this subject, I cannot possibly know how to implements these methods. According to [https://github.com/xmartlabs/Eureka/pull/1136](url) these methods are called when the user deletes, adds or replaces a row. I want to override these methods to get notified when the user deletes, adds and/or reorders a row in `MultivaluedSection`. Can you please show an example of how to implement this?

Thanks!

**Comment by mats-claassen** [comment]
Your `FormViewController` implements the `SectionDelegate`. You can just:
```swift
override func rowsHaveBeenAdded(_ rows: [BaseRow], at indexes: [IndexPath]) { ... }
```

in there.

**Comment by flizana** [comment]
Thank you very much for your answer. If you do document these method implementations please make sure that `super.rowsHaveBeenAdded` method is called inside the method implementation, or else the application will crash.
