### ISSUE TITLE
Getting a hidden row index?

### ISSUE THREAD

**Issue by andraz-kozelj** [xmartlabs/Eureka#1617]
- Environment: Eureka, Xcode and iOS version you are using.

Eureka: 4.2.0
XCode: 9.4.1
iOS: 10-12

Use case:

I do load up a form, consisting of rows with tags A, B, C, D, ... up to J.
I do hide rows C, D and E, by setting `row.hidden = true` and `row.evaluateHidden()` for each.

Now I would like to insert a new row, whether hidden or not, after row D, which I can only reference by the tag.
If I get the row with `var rowD = form.rowBy(tag: "D")` that's ok, but I cannot get its index in the form.

`rowD.indexPath` is **nil**, because it is not visible and I cannot access the list of hidden rows.
`rowD.section?.index(of: rowD)` is also **nil**.
 
How to get the hidden row index?

**Comment by mats-claassen** [comment]
You can get all the rows of a form with `form.allRows` and then check its index. However, you cannot insert rows there directly as it is get-only

**Comment by andraz-kozelj** [comment]
Ok, got the form-based index.
Is there a way to insert a row in the middle of hidden rows? I have to insert it in a specific section (offset could be calculated), but how to place it in the middle of hidden fields?

**Comment by mats-claassen** [comment]
There is no way currently. 

Just created a PR with that functionality.
