### ISSUE TITLE
 Programmatically insert a row at the top of a MultivaluedSection

### ISSUE THREAD

**Issue by pudility** [xmartlabs/Eureka#1622]
Is there a way to programmatically insert a row at the top of a `MultivaluedSection`? Basically this is what I want to do:

```swift
 form.sectionBy(tag: "someMultivaluedSection")?.insert(row, at: 0)
```
But I get this error:
> Cannot use mutating member on immutable value: function call returns immutable value

I _think_ this is because `MultivaluedSection.self` is immutable.

### Versions:
Eureka: master / latest
Swift: 4.1.2
XCode: 9.4

**Comment by mats-claassen** [comment]
`sectionBy(tag:)` returns an immutable Section. You can do it like this:

```swift
var section = form.sectionBy(tag: "someMultivaluedSection")
section?.insert(row, at: 0)
```

The `var` makes the difference there

**Comment by pudility** [comment]
This worked perfectly, thank you.

**Comment by fukemy** [comment]
![Screen Shot 2021-11-29 at 14 46 30](https://user-images.githubusercontent.com/8202437/143827803-be0ec394-8be6-40a5-9782-b67cff32ce88.png)

i got this error
