### ISSUE TITLE
Reduce the width of the Button Row

### ISSUE THREAD

**Issue by dheeraj-appzop** [xmartlabs/Eureka#1624]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by mats-claassen** [comment]
The ButtonRow is just a cell with `cellStyle` set to default which displays its title in the center.

If you want to change its width you could try changing the margins of the cell but I would suggest to add the button as a UIButton in the `header` or `footer` of a section.

**Comment by dheeraj-appzop** [comment]
I want to move the button and not its content.How could I add the spacing to the button to the left and right so that it looks center aligned.

**Comment by mats-claassen** [comment]
AFAIK you cannot change the width of the cell. As stated above, the best way to have a button that does not expand over the whole width is a custom footer view. You could also play with the selectionStyle of the cell and use `cell.layoutMargins` to reduce the width of the ButtonRow label.
