### ISSUE TITLE
cellSetup not called on custom row

### ISSUE THREAD

**Issue by flizana** [xmartlabs/Eureka#1626]
Hi! I have an issue with a custom made Eureka row. I have a multivalued section in which every row of this section is of type `ListRow`. The cell displays correctly and everything works. The only problem I'm having is that the `cellSetup` callback is not being called for this type of row. The follwing code shows how I'm building the section rows:

    for list in listsArray {
        $0.append(ListRow() {
            $0.title = ""
            let tag = list[Params.list] as? String
            let notes = list[Params.listNotes] as? String
            $0.cell.row.value? = List(tag: tag!, notes: notes!)
            $0.cell.tagTextField.text = tag
            $0.cell.notesTextField.text = notes
            $0.cell.notesTextField.textColor = UIColor.black
                        
            print("CELL INITIAL SETUP")
        }.cellSetup { (cell, row) in
            print("CELL SETUP")
        }.cellUpdate { (cell, row) in
            print("CELL UPDATE")
            cell.tagTextField.clearButtonMode = .whileEditing
        })
    }

The initial setup works fine, and also when I scroll down and move over the row `cellUpdate` is called correctly. The only problem is that `cellSetup` callback never gets called. This shows the output on the console:

    CELL INITIAL SETUP
    CELL UPDATE

**Comment by mats-claassen** [comment]
Did you override `setup` in the custom cell?
 If so, don't forget to call `super.setup()`

**Comment by flizana** [comment]
I did override `setup` and I did call `super.setup()`

This is my code for the custom cell setup:

    override func setup() {
        super.setup()
        
        // Disable selection
        selectionStyle = .none
        
        // Set height
        height = { return 146 }
        
        // Set text field placeholder
        tagTextField.placeholder = "Tag"
        tagTextField.delegate = self
        
        // Set text view placeholder
        notesTextField.text = "Notes"
        notesTextField.textColor = UIColor.lightGray
        notesTextField.delegate = self
        
        // Set initial value
        row.value = List(tag: "", notes: "")
    }

**Comment by flizana** [comment]
Thanks! By removing the code from the row initializer, `cellSetup` was called correctly.
