### ISSUE TITLE
AlertRow crashing when selecting on Beta5

### ISSUE THREAD

**Issue by diegogarciar** [xmartlabs/Eureka#1629]
The following code is working fine on simulator but is crashing on my recently updated iPhone 6s with developer beta 5

``` 
            section <<< AlertRow<String>("logout"){
           
           $0.title = "logoutTitle"
            $0.selectorTitle = "signOutMessage"

            $0.cancelTitle = "cancel"
            
            $0.options = ["ok"]
            
            }.onChange({ (row) in
                self.logout()
            })
```
I'm receiving this error:
Could not cast value of type 'Swift.Optional<Eureka.RowOf<Swift.String>>' (0x114b36648) to 'Eureka._AlertRow<Eureka.AlertSelectorCell<Swift.String>>' (0x114b1d970).

**Comment by diegogarciar** [comment]
What I found during debugging is that ViewDidLoad is being called before it should (at initialization)
    frame #9: 0x0000000102ab7e84 Eureka`SelectorAlertController.viewDidLoad(self=0x0000000136352000) at SelectorAlertController.swift:68
and because of that, its trying to get the row which it is still nil as it is set after initialized

**Comment by mats-claassen** [comment]
I see. I think it is normal that you would gt problems if viewDidLoad is called too early.

I tried this with the AlertRow in the examples and the `viewDidLoad` is always called after setting the row.

Are you accessing the view or the controller of the alert somewhere else in the code which might lead to the view being loaded too early?

**Comment by diegogarciar** [comment]
No, for testing I copied the row and inserted it in an empty form and got same result, I will try now installing the example into my iPhone and let you know.

My app has being working perfectly until I installed the iOS 12 Developer Beta 5, after that even my release apps started crashing. I hope it is a Beta bug, but if it isn't the AlertRow will fail in iOS 12.

**Comment by mats-claassen** [comment]
It's not crashing for me running the examples on the simulator (iOS Beta 4). Did it crash with beta 4 as well for you? Does it only crash on the device?

**Comment by diegogarciar** [comment]
Hey, just installed Beta 6 and it works again! 
(I tested also the Example project)
Thank you anyways for your time

**Comment by mats-claassen** [comment]
Good to hear that. I will close this issue then
