### ISSUE TITLE
No apparent accessibility API

### ISSUE THREAD

**Issue by clayreimann** [xmartlabs/Eureka#1639]
- [x] Latest version of Eureka (carthage)
- [x] Latest version of XCode 9
- [x] Could not find a preexisting issue

I'm building a new app in the BDD style and cannot find a way to apply `accessibilityIdentifier`s to the cells I'm creating. I would expect either:
- `row.tag` to be used as the `accessibilityIdentifier`
- Some API like the following:

```swift
<<< TextRow { row in
    row.accessibilityIdentifier = "myIdentifier"
    row.title = "Title"
    row.placeholder = "Placeholder"
}
```

**Comment by mats-claassen** [comment]
You could have something like this for all the rows that you are testing:
`TextRow.defaultCellSetup = { cell, row in cell.accessibilityIdentifier = row.tag }`

**Comment by clayreimann** [comment]
Is that a method from `BaseRow`? I only used `TextRow` as an example

**Comment by mats-claassen** [comment]
You don't have to nil it out as it is static. `defaultCellSetup` and similar methods should be used for configurations you want these rows to have in your whole app. You could have a function called by the AppDelegate on app launch which sets these configurations for all types of rows that you use in the app.

**Comment by clayreimann** [comment]
I disagree with your assessment that simply because a property is `static` you don't need to `nil` it out, however after re-reading the implementation I think it's reasonably safe in this case. Initially I misread the `wrapper` as calling the current value before calling the new value, which would cause a memory leak if you don't `nil` out the value when the VC that adds the closure is destroyed.

I also didn't realize that `row.cell` was exposed in the row setup closure, so for now I'll just configure accessibility there.

**Comment by mats-claassen** [comment]
You should avoid accessing `row.cell` in the row initializer whenever possible because this forces the creation of the cell. If you want to set properties on the cell use `cellSetup` or `defaultCellSetup`
