### ISSUE TITLE
ButtonRow action?

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#164]
I see that a ButtonRow can perform a segue but I want it to call a method.  That method should have some data/info about the row that called it.

I tried adding a tapGesture but is there a better way?

**Comment by ricardopereira** [comment]
@rlaferla Did you figure it out?

**Comment by ricardopereira** [comment]
```
    ButtonRow() {
        $0.title = "Tap Me!"
        $0.onCellSelection(self.buttonTapped)
    }
```

**Comment by mtnbarreto** [comment]
see #30
