### ISSUE TITLE
How to add the accessory keyboard for next/back and done functionality

### ISSUE THREAD

**Issue by elalienx** [xmartlabs/Eureka#1641]
Hi! I followed this tutorial about creating custom rows in Eureka ([link](https://medium.com/inloopx/creating-forms-in-ios-with-eureka-210223ed600f)). But I have a problem, the custom row lacks this key features:

1.- Changing the "return" key in the keyboard to "next" to go the next field.
2.- The accessory keyboard, the menu that appear on top of the keyboard. That has the "<", ">" and "Done" buttons to go back to the previous field, the next field and to close the keyboard.
3.- The validation rules.

**Custom row without the the "next" button nor accessory keyboard**
<img width="392" alt="screen shot 2018-08-19 at 01 11 23" src="https://user-images.githubusercontent.com/6117977/44306120-b89e6e00-a34d-11e8-88f3-0b68ccc89575.png">

**Default TextRow with the mentioned elements**
<img width="392" alt="screen shot 2018-08-19 at 01 11 27" src="https://user-images.githubusercontent.com/6117977/44306129-e84d7600-a34d-11e8-809a-50e885e8fb0a.png">

**Comment by mats-claassen** [comment]
If you are creating custom text fields you should try to subclass `_FieldCell` to use all the logic implemented in there. If you cannot subclass for whatever reason then have a look at its code, specifically the UITextField delegate methods `textFieldDidBeginEditing` and `textFieldDidEndEditing`. Also make sure that your cell can become first responder.

As for validation rules, which is your problem?

**Comment by korgx9** [comment]
Have the same issue
Added custom field for masking phone numbers. Now I have only inputView without Done button

**Comment by mats-claassen** [comment]
I know this thread is very old but just for reference: For a custom row to show the NavigationAccessoryView it should override these two:

```swift
    open override func cellCanBecomeFirstResponder() -> Bool {
        return canBecomeFirstResponder
    }

    override open var canBecomeFirstResponder: Bool {
        return !row.isDisabled
    }
```
