### ISSUE TITLE
Hi there - How can change the font to be used in a SegmentedRow field ? Thanks!

### ISSUE THREAD

**Issue by KyriDemetriou** [xmartlabs/Eureka#1647]
I have managed to change the font for most of the fields in my form - this is the last one - and so it really sticks out

**Comment by KyriDemetriou** [comment]
Thanks. Tried the following

let titleFont : UIFont = UIFont(name: UIStyle.AppFontName, size: 20)!
 let attributesNormal = [
            NSAttributedStringKey.font : titleFont
        ]

///
<<< SegmentedRow<String>("options"){
            .cellSetup({ (cell, row) in
                cell.titleLabel?.font = titleFontAll
                cell.segmentedControl.setTitleTextAttributes(attributesNormal, for: .normal)
            })

Any ideas ?

**Comment by mats-claassen** [comment]
@KyriDemetriou What problem are you having with that code?

**Comment by KyriDemetriou** [comment]
With this code, the font is unchanged. However, I am using a font I added to my project - would that make a difference ? Thanks.
