### ISSUE TITLE
Extended inline row was collapsed when another inline row was extended

### ISSUE THREAD

**Issue by maxxx777** [xmartlabs/Eureka#1650]
I have several inline rows and when I extend an inline row, the previous extended inline row is collapsed. 
Is it expected behaviour? or is there option to allow extend several inline rows at the same time?

**Comment by elgartoinf** [comment]
regards!
could show us a screenshot of how the error is

**Comment by maxxx777** [comment]
sure, I made a gif demo:

![inline_row_demo](https://user-images.githubusercontent.com/2142832/44860748-4eec6100-ac77-11e8-9c8a-41e35fbaac42.gif)

**Comment by mats-claassen** [comment]
You can use `form.inlineRowHideOptions`. Have a look at the `Inline rows example` to see how you can use it

**Comment by maxxx777** [comment]
Thanks!
