### ISSUE TITLE
Eureka custom cell is reused by other cells

### ISSUE THREAD

**Issue by ningkexin** [xmartlabs/Eureka#1654]
I used code to build a custom cell, but it was reused by TextRow() below. How can I disable this reuse, or need other methods to solve this problem?
The image below is dragged down, back to the top again, and the first cell must have a ghost image.

![image](https://user-images.githubusercontent.com/17719524/45022846-cd764380-b067-11e8-8676-5c1be232c49f.png)

**Comment by mats-claassen** [comment]
Hi @ningkexin, Eureka does not reuse cells (unless you override `tableView(_, cellForRowAt)`).

**Comment by ningkexin** [comment]
@mats-claassen Is my custom cell caused by the `String` type? I have not override any methods of tableview.

```swift
import UIKit
import Eureka

public class BarCodeCell: Cell<String>, CellType,UITextFieldDelegate {
// ....omit
    public override func setup() {
        super.setup()
        row.value = self.barCodeContent.text
    }
    public override func update() {
        super.update()
        row.value = self.barCodeContent.text
    }
    @objc func changeText(nofi:Notification){
        let info = nofi.userInfo!["content"] as! String
        log.info([info])
        self.barCodeContent.text = info
        row.value = self.barCodeContent.text
    }
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    public func textFieldDidEndEditing(_ textField: UITextField) {
        row.value = self.barCodeContent.text
    }
}

public final class CustomBarCodeRow: Row<BarCodeCell>, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<BarCodeCell>()
    }
}

```

**Comment by mats-claassen** [comment]
I am not completely getting which is the problem. Could you explain a bit more how or whcih TextRow is reusing your cell?

 In your custom row, in `update` you should set `detailtextLabel.text = nil` to avoid duplicating the value on the right.

**Comment by mats-claassen** [comment]
I will close this as the issue has been resolved.

If you want to know if `init(style: UITableViewCellStyle, reuseIdentifier : String?)` is being called, put a breakpoint in there. It should not be called when loading the cell from a nib file.
