### ISSUE TITLE
Select multiple rows

### ISSUE THREAD

**Issue by andreybuksha** [xmartlabs/Eureka#1658]
Hi, thanks for the great library! I didn't find in the documentation how to add ability to select multiple rows (see the attached screenshot). I know how to do it with ordinary `UITableView`, but when I use Eureka and call `tableView.setEditing(true, animated: true)` nothing happens, please help.

![](https://i.stack.imgur.com/JzFDr.png)

**Comment by mats-claassen** [comment]
What you are looking for is `MultipleSelectorRow`. You can see examples in the Example project like:

```swift
<<< MultipleSelectorRow<Emoji>() {
                $0.title = "MultipleSelectorRow"
                $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻]
                $0.value = [👦🏼, 🍐, 🐗]
                }
                .onPresent { from, to in
                    to.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: from, action: #selector(RowsExampleViewController.multipleSelectorDone(_:)))
            }
```

**Comment by andreybuksha** [comment]
Thanks for the answer. I need a little different behaviour, I am trying to implement butch editing. For reference go to iMessage and click edit button in nav bar and you will see edit mode for messages where you can select multiple rows and apply an action (delete, read, ...). I've attached a screenshot for clarity. This can be easily implemented with ordinary UITableView - tableView.setEditing(true, animated: true), but when I use it with Eureka nothing happens. Do you think I can implement it with MultipleSelectorRow? I guess it's a wrong way.

![img_6119bf229d00-1](https://user-images.githubusercontent.com/26220655/45496371-f5f3f100-b77d-11e8-8732-f12ee1690b75.jpeg)

**Comment by mats-claassen** [comment]
Eureka is build on `UITableView`'s so that you can override any dataSource or delegate method you want on your FormViewController.

There is also an example in MultiValuedExamples which uses `tableView.setEditing(...)`.
Now, if you want to do something custom on a batch of rows then you could use `MultipleSelectorRow` (or `SelectableSection`) and then get the selected rows and delete/modify them when the user does certain action

**Comment by m3rkus** [comment]
Thanks a lot for the explanation!

**Comment by mats-claassen** [comment]
I will close this issue. If you need help please post to StackOverflow. If you think you found an issue or have a feature request post here. Thanks
