### ISSUE TITLE
How to do this after the DateRow selects the value, let the value be nil？

### ISSUE THREAD

**Issue by YaHoYii** [xmartlabs/Eureka#1659]
When the DateRow selects the value, the selected value will be displayed. Now I want to select the value of nil, no longer display any value, what should I do?

**Comment by mats-claassen** [comment]
You can add a button somewhere and set the value to nil when the user taps it. It could be in the header/footer of a section or in the cell itself if you create a custom layout for the DateRow

**Comment by YaHoYii** [comment]
Thanks, I rewrote the inputAccessoryView property of the cell and set a reset button.
