### ISSUE TITLE
Associate model object with row?

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#166]
Is there a recommended way to associate an optional model/data object with a Row?

**Comment by mtnbarreto** [comment]
@rlaferla  Could you be more specific?

**Comment by rlaferla** [comment]
I'm referring to bindings or controller logic that binds the Model (some custom object, string, dictionary) to the View (row).

**Comment by izonprize** [comment]
I too have a question about this. I would like to pass a model or dictionary to the row options. If the elements in said model or dictionary were ID and Name I would like to display the Name but use the ID value when the form is submitted.

**Comment by mats-claassen** [comment]
We will not be implementing this feature.
If somebody has created something to make this possible then that could be shared but it won't be core functionality as there are too many edge cases to support.
