### ISSUE TITLE
Data validation bug with non-string variants of FloatLabelRow

### ISSUE THREAD

**Issue by eliburke** [xmartlabs/Eureka#1660]
I know that the FloatLabelRow examples are not directly supported, but I wanted to mention a potentially serious bug here in case it helps someone. I opened an issue EurekaCommunity/FloatLabelRow#15 but I'm not sure if it is maintained any longer. 

In short-- if you use any non-string data type (URL, Int, Float, Decimal) and enter invalid characters into a row, the row will visually appear to contain the user-entered value, but the underlying row.value instead contain the last VALID value. 

For example, using a URLFloatLabelRow
👍 type "www.google" -- row.value contains "www.google"
👎 type "www.google .com" -- row.value contains "www.google"
👎 existing value "www.google.com". User selects "www" and pastes in the string "images " (with a trailing space) -- row.value still contains "www.google.com"

**Comment by mats-claassen** [comment]
Thanks for bringing this up @eliburke. We will look at it when we have time. We will continue tracking it in the FloatLabelRow repo.
