### ISSUE TITLE
'automaticDimension' was introduced in Swift 4.2

### ISSUE THREAD

**Issue by akiporoyopida** [xmartlabs/Eureka#1667]
Environment: Eureka 4.3.0 from Pods, iOS 12, Xcode 10.0

In my project there are 35 issues in Eureka.
For example,
/ UKit.UITableView: 64: 22: 'automaticDimension' was introduced in Swift 4.2
I use it via pods, but do I have to wait for the next version?

**Comment by gabzsa** [comment]
Same here.

**Comment by mats-claassen** [comment]
Does not happen to me. Eureka 4.3.0 is in Swift 4.2. Are you trying to build it with Swift 4.1? 
Can you look at `Pods (xcode project) -> Eureka target -> Build Settings -> Swift Language Version` and see if it is Swift 4 or Swift 4.2?

**Comment by harri121** [comment]
+1

**Comment by Kaakati** [comment]
+1

**Comment by sedwo** [comment]
Try this.

Go into your `Pods` project.  Select `Eureka`
![image](https://user-images.githubusercontent.com/1434449/46022608-f317cb00-c0b0-11e8-92dd-69d4fa847e25.png)

And select `Swift 4.2` under `Build Settings`.
![image](https://user-images.githubusercontent.com/1434449/46022546-d54a6600-c0b0-11e8-80ee-3b6dfd98cad6.png)

Then _Rebuild_.

**Comment by akiporoyopida** [comment]
The problem was solved.
Thanks sedwo and all!!

**Comment by dadarenedo** [comment]
hi, I updated eureka to version 4.3, I change Swift 4.2 under Build Settings, it solved most of the complier issues but i still gettin some errors like:

Type 'UIContentSizeCategory' has no member 'NSNotification

what else can i try?
thank you
