### ISSUE TITLE
How Can I Remove SectionHeaderView

### ISSUE THREAD

**Issue by woxihejinghao** [xmartlabs/Eureka#1668]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by woxihejinghao** [comment]
![simulator screen shot - iphone xs - 2018-09-28 at 20 16 15](https://user-images.githubusercontent.com/21906803/46207903-7f4d1b00-c35b-11e8-83fa-603cb460b74d.png)

For example, I want to remove SECTION1 and remove spacing

**Comment by mtnbarreto** [comment]
Hi @woxihejinghao, According the Eureka documentation you can do something like the code below. 
Could you please check if it works..?

```swift
Section(){ section in
    var header = HeaderFooterView<MyCustomUIView>(.class)
    header.height = {0}
    header.onSetupView = { view, _ in
        view.backgroundColor = .clear // on set setup can be removed
    }
    section.header = header
}
```

**Comment by mtnbarreto** [comment]
Please take a look at these two labels that contains additional information.

**Comment by woxihejinghao** [comment]
Thank you very much
