### ISSUE TITLE
Ambiguously suggest a height of zero for a tableview cell's content view

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#167]
I'm seeing what appears to be an autolayout bug with a form that has 1 header row followed by several sections each with 1 or more rows.  The rows are all of type ButtonRow.  

Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.

**Comment by rlaferla** [comment]
This got rid of the warning but the ButtonRow still doesn't appear:

```
        self.tableView?.rowHeight = 40.0
```

**Comment by lyptt** [comment]
I've got the same issue. The hack above seems to work well but it'd be nice if this was fixed properly

**Comment by fxv** [comment]
Hi. Can you please update the pod spec version that includes this fix. Thank you.

**Comment by timvermeulen** [comment]
I'm very new to CocoaPods, but I set everything up yesterday (so I assume I've got the newest versions) and I get this warning too, after using a `PushRow` or an `ActionSheetRow` so far.

**Comment by TCOA** [comment]
Same problem in Swift 4 - the same hack stopped the error message.

**Comment by atereshkov** [comment]
The same problem Swift 4 is for me too. Just set the proper height for row.

```
override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
     return 80.0
}
```

**Comment by MHamayun** [comment]
To implement tableview's delegate method heightForRowAtIndexPath
func tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 50;
}
