### ISSUE TITLE
Disable ButtonRow

### ISSUE THREAD

**Issue by sverin** [xmartlabs/Eureka#1671]
I have a ButtonRow enabled by default that adds a row in`onCellSelection`. Later I wish to disable the ButtonRow and I tried:

```
let row = ...
row.disabled = true
row.evaluateDisabled()
```

The row looks disabled (grayed out) but when I press it `onCellSelection` is evaluated and adds another row. How can I prevent this?

Should I look at `row.isDisabled` before I add the row in `onCellSelection`?

**Comment by mtnbarreto** [comment]
Hi @svedm , You do check for `row.isDisabled` as you said.

**Comment by danqing** [comment]
Is there a reason this is not handled by the framework @mtnbarreto ? I feel like if it's already disabled, then it almost certainly should be logically disabled..

**Comment by zunjae** [comment]
Bit embarrassing I need to add `guard !row.isDisabled else { return }` on a row that's disabled...
