### ISSUE TITLE
Multivalued section row deletion does not work in succession

### ISSUE THREAD

**Issue by AndrewBennet** [xmartlabs/Eureka#1674]
When using a multivalued section which allows row deletion, if two rows are deleted, and the second is deleted while the animation for the first deletion is still running, the second deletion does not occur and the section becomes frozen.

This is demonstrable in the example Eureka app by just deleting the top two rows of the multivalued section in quick succession. (This is hard to do on a simulator though).

![image](https://user-images.githubusercontent.com/2078225/46378734-7f6b5480-c694-11e8-8435-6d22cc4446b7.gif)

Eureka version: 4.3.0
Xcode version: 10.0
iOS: 12.0

**Comment by AndrewBennet** [comment]
Do you know if there is any workaround for this issue?

**Comment by mats-claassen** [comment]
Not to my knowledge but it might be related to #1575. I don't think it's the same issue though

**Comment by serbuk** [comment]
I faced exactly the same issue. The whole form (all the available sections) becomes frozen.

**Comment by ykorshev** [comment]
Any updates?

**Comment by hungeric** [comment]
Hello @mats-claassen did your #1709 fix the frozen thing @serbuk mentioned in the comment above?
also is the fix released?

**Comment by mats-claassen** [comment]
It should be fixed in version 4.3.1 released yesterday
