### ISSUE TITLE
Segmented row disable option

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#1675]
Hi everyone,

I'm trying to disable one of my options in SegmentedRow but is not working. I'm trying to access segmented control via `cell.segmentedControl.setEnabled(true, forSegmentAt: 0)` but it gives error `index out of range`. Trying to access it in `cellSetup`

Any suggestions? Thanks.

**Comment by mats-claassen** [comment]
I think `cellUpdate` is a better place for this. At least if that item could be disabled/enabled afterwards. It worked for me in `cellUpdate`

**Comment by dneykov** [comment]
Perfect. Setting disabled/enabled in `cellUpdate` works.
Thanks.
