### ISSUE TITLE
evaluateHidden performance = slow

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#168]
There should be a way to hide multiple rows and then evaluate them all at once to improve performance.  I have a form with a couple of hundred button rows and it's slow to hide/unhide rows.  Because my logic is complex, I am not using Predicates/Functions but rather setting the "hidden" attribute on specific rows and calling evaluateHidden() for each row during an onChange().

**Comment by mtnbarreto** [comment]
@rlaferla 

The logic behind hiding disabling rows is "complex" and takes some time, it was originally implemented to handle typical ios forms and not forms with hundred of rows. 

In your particular case I suggest you to add and remove rows manually using `section.append` and `section.removeAtIndex` respectively or any variant.

I really appreciate if you can provide more information when you report an issue such as sharing code, benchmark, stack trace, ios/xcode version, device, or any detail that would be useful to understand and reproduce the issue. This information will help a contributor to look into the issue and provide help faster. 
Please, don't get me wrong.

Regards,
Martin
