### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by zhaojiewen** [xmartlabs/Eureka#1683]
*** Building scheme "Eureka" in Eureka.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Volumes/MAC/iOSVPN/ladder-ios/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/yixin/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Eureka/4.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/d0/gr38fsxx6bbgz87lym25np3r0000gp/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Volumes/MAC/iOSVPN/ladder-ios/Carthage/Checkouts/Eureka)

**Comment by mtnbarreto** [comment]
Hi @zhaojiewen ! 
Would you please follow contribution guidelines..?

**Comment by FrankCYQ** [comment]
> Hi @zhaojiewen !
> Would you please follow contribution guidelines..?

I'm not sure what did you mean "contribution guidelines"

**Comment by FrankCYQ** [comment]
> *** Building scheme "Eureka" in Eureka.xcworkspace
> Build Failed
> Task failed with exit code 65:
> /usr/bin/xcrun xcodebuild -workspace /Volumes/MAC/iOSVPN/ladder-ios/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/yixin/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Eureka/4.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/d0/gr38fsxx6bbgz87lym25np3r0000gp/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Volumes/MAC/iOSVPN/ladder-ios/Carthage/Checkouts/Eureka)

how do you fix it
