### ISSUE TITLE
How can I optimize the addition/merge of many rows?

### ISSUE THREAD

**Issue by sedwo** [xmartlabs/Eureka#1684]
Using Eureka v4.3.0.

The following loop inserts and merges a collection of row id's.  ~330 items.

```
struct RowItem {
    let id: String
    let title: String
}

func updateForm(with rowItems: [RowItem]) {
    ...
    // Compare our updated list of items with the current form.
    var allRows = self.form.allRows

    for (index, item) in rowItems.enumerated() {

        if allRows.count == 0 || index >= allRows.count {
            defaultSection.insert(createTitleRow(item), at: index)
        } else if let row = allRows[index] as? TitleRow {
            // row exists, now check if it matches.
            if row.value != item.id || row.title != item.title {
                defaultSection.remove(at: index)
                // add missing row
                defaultSection.insert(createTitleRow(item), at: index)
            } else {
            }
        } else { // insert missing row
            defaultSection.insert(createTitleRow(item), at: index)
        }
    }

}

```
Yes, I'm utilizing Eureka for a simple TableViewController.  But it will eventually expand in features and the framework is really neat for these things.  Regardless, the performance hit with generating 330 items is ~2.2secs.  Which in UI terms is forever.

What steps can I take to optimize such a batch update of row items?

**Comment by mats-claassen** [comment]
As you pointed out, Eureka is not ideal for big and simple table views. One reason for this is because it does not reuse cells which you cannot change. You could try, however, to not insert every single row to the section but to create a temporal section were you insert all the rows and then add the section to the form. This way you won't execute all the UI update so many times

**Comment by sedwo** [comment]
If the UI is the bottleneck, perhaps I can disable a UI update until the insertions are all done?

**Comment by mats-claassen** [comment]
That is what I meant. Try something like this:

```swift
let section = Section()
for x in 0...1000 {
    section <<< MyRow()
}
form +++ section
```

Does that change something for you?

**Comment by sedwo** [comment]
I should have been more clear.
My current setup uses a `Plain` tableview (like 'Contacts' app).  So there is _only one section_.  Which results in me trying to merge details into that single section.

**Comment by mats-claassen** [comment]
I see, maybe you can disable UI animations for that update, yes.
Another  try is to batch insert your rows using `section.insert(contentsOf: , at:)`. So gather all rows in an array and insert them all together.

I personally do not use Eureka for such scenarios. Maybe someone else, has some experience with that.

**Comment by sedwo** [comment]
Optimized!

Swift 4.2, iOS 12.1

```
UIView.performWithoutAnimation {
    self.tableView.beginUpdates()

    defaultSection.insert(contentsOf: allRows, at: 0)
    tableView.reloadData()

    self.tableView.endUpdates()
}

```

If you wrap the Eureka code like above, it will enhance load times 100x.
I went from loading my form with 331 rows in 2.4sec. to 0.106sec.  👍
Regardless if you use the `.insert(contentsOf: , at:)` method or not.

Thank you for your kind support on this.
