### ISSUE TITLE
only 10 characters on phoneRow

### ISSUE THREAD

**Issue by javmorales** [xmartlabs/Eureka#1685]
how i can set only 10 characters on phoneRow?

**Comment by alper** [comment]
I can't get at the cell values while you type, but you can use Eureka validation with something like: `$0.add(rule: RuleMaxLength(maxLength: 10))`.

**Comment by mtnbarreto** [comment]
@ahand thanks for helping! 
I'm not tested it but i guess it works.

**Comment by mats-claassen** [comment]
@javmorales Did that suggestion work for you?

**Comment by anupamchugh** [comment]
It does the validation for the length but does not stop the user from typing more than 10(or the specified value) characters.
