### ISSUE TITLE
Token row issue

### ISSUE THREAD

**Issue by Smiller193** [xmartlabs/Eureka#1689]
I am not sure if anyone is using the token row. But im using it to add user to a list of people that are hosting an event. I am properly querying the users from my back end and getting them. Only issue is for some reason I can't really see the full list of users in the token tableview that appears below. Also If i dismiss the keyboard everything disappears. In addition to that the imageview is way too big.

Can anyone help me with any of these issues?
Attached is a picture
<img width="366" alt="screen shot 2018-10-15 at 1 05 29 pm" src="https://user-images.githubusercontent.com/16108750/46966205-051ad700-d07b-11e8-990a-620038b2d19b.png">

im not sure if that is a similar thing but I can't see that at all.

**Comment by mats-claassen** [comment]
Let's continue this thread in the [TokenRow](https://github.com/EurekaCommunity/TokenRow/issues/11) repo
