### ISSUE TITLE
onDismiss callback is never called for PresentationMode.show

### ISSUE THREAD

**Issue by tosbaha** [xmartlabs/Eureka#1690]
I am trying to update the table with tableView.reloadData() If I do this with viewDidAppear, it works without a problem. However I only want to update it for some cells. I have following code but `onDismiss` callback is never called

```swift
<<< ButtonRow ("Register") {
    $0.title = isSignedIn ?  UserService.sharedInstance.user?.email : NSLocalizedString("Register", comment: "")
    if isSignedIn {
        $0.presentationMode = .show(controllerProvider: .callback(builder: AccountViewController.init),onDismiss: { vc in
            print("AccountViewController I am being dismissed!")})
    } else {
        $0.presentationMode = .show(controllerProvider: .callback(builder: SignupViewController.init),onDismiss: { vc in
            print("SignupViewController I am being dismissed!")
        })
    }
    }.cellUpdate({ (cell, row) in
        print("Cell \(cell) is Being updated!")
        print("Row \(row) is Being updated!")
    })
```

**Comment by mats-claassen** [comment]
Hi @tosbaha, The view controller you use is responsible for calling `onDismiss` when it is dismissed. In this case it is SignupViewController

**Comment by tosbaha** [comment]
SignupViewController is another instance of FormViewController. How I am going to call `onDismiss` from SignupViewController when user swipes back? How other controllers like PushRow detects swipes so that it correctly sets the cell text?

**Comment by mats-claassen** [comment]
You can have a look at `SelectorViewController` which is used by PushRow. It calls inDismiss [here](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Controllers/SelectorViewController.swift#L211) when an item is selected

**Comment by alldritt** [comment]
I ran into this same problem.  The trick is to have your FormViewController subclass adopt the `RowControllerType` protocol.  Here is a little snippet demonstrating how to do it:

```
class MyViewController: FormViewController, RowControllerType {

	// Conform to the RowControllerType protocol
    var onDismissCallback: ((UIViewController) -> Void)?
    
    override func viewDidLoad() {
        super.viewDidLoad()

		//	Make your form
		form
			+++ Section()
				<<< LabelRow() { (row) in
					row.title = "Hello World"
				}
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        //	Detect when your view controller is popped and invoke the callback
        if !isMovingToParent {
            onDismissCallback?(self)
        }
    }
}
```

**Comment by tosbaha** [comment]
Thanks everybody. I managed to solve it like @alldritt did by using `RowControllerType`
