### ISSUE TITLE
Navigation options does not show in Eureka custom row

### ISSUE THREAD

**Issue by Hrvoje0099** [xmartlabs/Eureka#1694]
On pictures below you can see my form. Row "Web page" is my custom row and i have some problem with that row. When I pressed on that row, label doesn't change color and navigation option below dont show.
[![enter image description here][2]][2][![enter image description here][3]][3]

This is code of my custom cell:

    import UIKit
    import Eureka
    import SearchTextField

    final class WebPageCellRow: Row<WebPageCell>, RowType {
      required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<WebPageCell>(nibName: "WebPageCell")
      }
    }

    final class WebPageCell: Cell<String>, CellType {
    
    @IBOutlet weak var labelWebPage: SearchTextField!
    @IBOutlet weak var textFieldWebPage: SearchTextField!
    
    required init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func setup() {
        super.setup()
        
        configureSimpleSearchTextField()
        
        selectionStyle = .none
        height = { return 44.0 }
    }
    
    override func update() {
        super.update()
        
        // we do not want to show the default UITableViewCell's textLabel
        textLabel?.text = nil
        
        // get the value from our row
        guard row.value != nil else { return }
    }
    
    public func configureSimpleSearchTextField() {
        let countries = localCountries()
        textFieldWebPage.filterStrings(countries)
        textFieldWebPage.font = .preferredFont(forTextStyle: .body)
    }
    
    fileprivate func localCountries() -> [String] {
        if let path = Bundle.main.path(forResource: "webpages", ofType: "json") {
            do {
                let jsonData = try Data(contentsOf: URL(fileURLWithPath: path), options: .dataReadingMapped)
                //print("jsonData \(jsonData)")
                
                let jsonResult = try JSONSerialization.jsonObject(with: jsonData, options: .allowFragments) as! [[String:String]]
                //print(jsonResult.count)
                
                var countryNames = [String]()
                for country in jsonResult {
                    //print(country["name"] ?? "banana")
                    countryNames.append(country["name"]!)
                }
                
                return countryNames
            } catch {
                print("Error parsing jSON: \(error)")
                return []
            }
        }
        return []
    }
    
    }

And this is my view controller class:

    import Foundation
    import Eureka
    import GenericPasswordRow

    class ManualPasswordVC: FormViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        initElements()
        
        //navigationOptions = RowNavigationOptions.Disabled
    }
    
    private func initElements(){
        
        form +++ Section(){ section in
            section.header = {
                var header = HeaderFooterView<UIView>(.callback({
                    let view = UIView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
                    //view.backgroundColor = UIColor.gray
                    let lb = UILabel(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 60))
                    lb.text = "Add the password manually"
                    lb.textAlignment = .center
                    view.addSubview(lb)
                    return view
                }))
                header.height = { 60 }
                return header
            }()
        }
            
        +++ Section("Enter title and web page of password"){
            $0.header?.height = { 20 }
        }
        <<< TextRow(){ rowTitle in
            rowTitle.title = "Title"
            rowTitle.tag = "rowtitle"
        }.cellUpdate({ (cellTitle, rowTitle) in
            cellTitle.textField.clearButtonMode = .whileEditing
            //cellTitle.textField.borderStyle = .line
            print(cellTitle.textLabel?.textColor)
            print(cellTitle.titleLabel?.textColor)
        })
        <<< WebPageCellRow(){ rowWebPage in
            rowWebPage.tag = "rowWebPage"
        }.cellUpdate({ (cellWebPage, rowWebPage) in
            cellWebPage.textFieldWebPage.clearButtonMode = .whileEditing
            cellWebPage.textFieldWebPage.textAlignment = .right
        })

        +++ Section("Enter a username or email from the password")
        <<< EmailRow(){ rowEmail in
            rowEmail.title = "Email"
            rowEmail.tag = "rowEmail"
        }.cellUpdate({ (cellEmail, rowEmail) in
            cellEmail.textField.clearButtonMode = .whileEditing
        })
            
        <<< TextRow(){ rowUsername in
            rowUsername.title = "Username"
            rowUsername.tag = "rowUsername"
        }.cellUpdate({ (cellUsername, rowUsername) in
            cellUsername.textField.clearButtonMode = .whileEditing
        })
            
        +++ Section("Enter password")
        <<< GenericPasswordRow(){ rowPassword in
            rowPassword.title = "Password"
            rowPassword.placeholder = ""
        }.cellUpdate({ (cellPassword, rowPassword) in
            cellPassword.textField.clearButtonMode = .whileEditing
            cellPassword.textField.isSecureTextEntry = false
            cellPassword.textField.textAlignment = .right
            cellPassword.dynamicHeight = (48, 48)
        })
            
        +++ Section()
        <<< ButtonRow{ rowSave in
            rowSave.title = "SAVE"
        }
        
    }
    
    }

I want to my cell change label color too and to show navigation options below. Can i do this i how? Thank you! 

  [2]: https://i.stack.imgur.com/HGfKG.png
  [3]: https://i.stack.imgur.com/BkGAK.png

**Comment by Hrvoje0099** [comment]
Hi @mats-claassen thanks on answere. Can I ask you something else? In my custom row, leading constraints of textfield are 20. And when I run app on iPhone XR simulator my custom row and other regular(Eureka) row are all on constraints 20, but when run on iPhone 6s simulator constrains of my custom row still 20 but other are 15 and it's not nice to see. How i can fix that if yu understand me? I can send you screenshot.. Thanks

**Comment by mats-claassen** [comment]
I think you have to add the constraints relative to the margin of the cell, if I don't remember wrong.

Or have a look at how the constraints are set in those other rows.

**Comment by Hrvoje0099** [comment]
@mats-claassen 

> I think you have to add the constraints relative to the margin of the cell, if I don't remember wrong.
> 
> Or have a look at how the constraints are set in those other rows.

@mats-claassen Thanks, it works. First with navigation options in custom row i have not managed to solve so i disabled navigation options.
