### ISSUE TITLE
what version should I use for swift 4.1 xcode 9.4.1 ?

### ISSUE THREAD

**Issue by ismailtosun** [xmartlabs/Eureka#1700]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by onvika** [comment]
Hi, I am using swift 4.1 and Xcode 9.4.1
if I use Eureka '4.2' I get bunches of errors
if I use Eureka '4.0' I get this: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

I have include this: post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end

I think I have read and tried almost all, and yet... I can not solve it ;/
