### ISSUE TITLE
semanticContentAttribute .forceRightToLeft

### ISSUE THREAD

**Issue by Maryom** [xmartlabs/Eureka#1704]
Hey,

Thank you for your useful repo.

I have the same problem as #1039 

- Environment: Eureka v4.3.0, Xcode 10.0 and iOS 11.0

I used the following code to align all the sections in the form to the right:

`tableView?.semanticContentAttribute = .forceRightToLeft`

It worked successfully. However, on click all options are still aligned to the left.

For example:

```
+++ Section()
<<< PushRow<String>() {
        $0.title   = "مرحباً"
        $0.options = heyArray
}
```

Any suggestions how to align options to the right?

**Comment by mats-claassen** [comment]
I have no experience with RTL, but in this case you probably have to set `tableView?.semanticContentAttribute = .forceRightToLeft` also for the tableView of the pushed viewController.

You can use `onPresent` on your PushRow for this:

```
.onPresent { from, to in
                    to.tableView.semanticContentAttribute = .forceRightToLeft
}
```

**Comment by Maryom** [comment]
Hey,

Thanks for your response.

I tried it, it crashed 😅

Any suggestion?

**Comment by Maryom** [comment]
Problem solved :) it just needs the following:

`to.view.layoutSubviews()`

So, it is:
```
+++ Section()
<<< PushRow<String>() {
        $0.title   = "مرحباً"
        $0.options = heyArray
        $0.onPresent { from, to in
            to.view.layoutSubviews()
            to.tableView.semanticContentAttribute = .forceRightToLeft
         }
}
```

Thank you 🙏🏼
