### ISSUE TITLE
Generic PickerInlineRow Alignment

### ISSUE THREAD

**Issue by fatihtan** [xmartlabs/Eureka#1705]
Hi,

I am using PickerInlineRow with String type. 
Is there any way to align Selected Option left or center (Not Right)?
  
Here is my code:

            form
                
            +++ Section("My Section Title")
            <<< PickerInlineRow<String>("mytag") {
                (row : PickerInlineRow<String>) -> Void in
                
                for (ix, item) in self.MyList.enumerated() {
                    row.options.append(item);
                }
            }

Thanks for helping.

**Comment by mats-claassen** [comment]
You mean the option inside the picker or in the row?

To edit the picker view you can use `onCellSelection`:

```swift
.onCellSelection { (cell, row) in
                    if let inlineRow = row.inlineRow {
                        print(inlineRow.cell.picker.frame)
                    }
                }
```
