### ISSUE TITLE
Custom Row Problem

### ISSUE THREAD

**Issue by dazeili** [xmartlabs/Eureka#1711]
I need help. I am trying to create a TagsRow. So small UILabels with a border are shown in this row. But when I segue to the form no labels are shown. When i scroll down and up again all works fine and shows right. So there must be a simple function I can call, that does exactly this redraw. 
I tried: row.reload(), row.updateCell(), setNeedsDisplay(), setNeedsLayout(). But nothing works. Maybe you got a simple idea for that? Else i provided the code down below.

Thanks for your help!

**Comment by dazeili** [comment]
Here is the code for the row: 

`
import Foundation
import Eureka

public final class TagsRow2<T: Hashable>: GenericMultipleSelectorRow<T, TagsCell2<T>>, RowType{
    
    public var displayValueForTag: ((T) -> String)?
    var startup = true
    
    public required init(tag: String?) {
        super.init(tag: tag)
        
        
        cellProvider = CellProvider<TagsCell2<T>>()
    
        
        displayValueFor = nil        
    }
}



public class TagsCell2<T: Hashable>: Cell<Set<T>>, CellType{
    
    var vTags = AZUITagsView()
    
    
    var standardHeight: CGFloat = 44
    var paddingTopBot: CGFloat = 10
    
    private var tableView: UITableView? {
        return self.formViewController()?.tableView
    }
    
    public override func setup() {
        super.setup()
        
        accessoryType = .disclosureIndicator
        
        var tags = [String]()
        
        if let row = row as? TagsRow2<T>, let value = row.value{
            tags = value.map{
                if let displayValueForTag = row.displayValueForTag{
                    return displayValueForTag($0)
                }
                return String(describing: $0)
            }
        }
        
       
        vTags.tags = tags
        print(vTags.tags)
        
        contentView.addSubview(vTags)
        
        vTags.translatesAutoresizingMaskIntoConstraints = false
        contentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|-\(paddingTopBot)-[vTags]-\(paddingTopBot)-|", options: [], metrics: nil, views: ["vTags": vTags]))
        contentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|-8-[vTags]-8-|", options: [], metrics: nil, views: ["vTags": vTags]))
 
        height = getHeight
        
    }
    
    public override func update() {
        super.update()
        print("update")
        
        
        if let value = row.value, value.count > 0{
            textLabel?.text = " "
        }else{
            textLabel?.text = "Tag(s) hinzufügen"
        }
        detailTextLabel?.text = ""
 
        
        guard let row = row as? TagsRow2<T>, let value = row.value else{
            print("RETURN")
            return
        }
        
        vTags.tags = value.map{
            if let displayValueForTag = row.displayValueForTag{
                return displayValueForTag($0)
            }
            return String(describing: $0)
        }
        
        
    }
    
    public override func layoutSubviews() {
        super.layoutSubviews()
        print("layout")
    }
    
    
    private func getHeight() -> CGFloat{
        //return 200
        return vTags.intrinsicContentSize.height > 0 ? (vTags.intrinsicContentSize.height + paddingTopBot * 2) : standardHeight
    }
}
`


Here is the Code for the embedded TagsView(got a layout small bug but not important):

`
import Foundation
import UIKit

@IBDesignable
public class AZUITagsView: UIView {
    
    public var tags = [String](){ didSet{ reloadTags() } }
    
    var minHeight: CGFloat = 26{ didSet{ setNeedsDisplay() }}
    //@IBInspectable var noTagsLabel: String? = nil{ didSet{ reloadTags() }}
    
    @IBInspectable var tagMargin: CGFloat = 8{ didSet{ restyleTagLabels() }}
    @IBInspectable var tagCornerRadius: CGFloat = 6{ didSet{ restyleTagLabels() }}
    @IBInspectable var tagBorderWidth: CGFloat = 0.8{ didSet{ restyleTagLabels() }}
    @IBInspectable var tagColor: UIColor? = nil{ didSet{ restyleTagLabels() }}
    @IBInspectable var tagBackgroundColor: UIColor? = nil{ didSet{ restyleTagLabels() }}
    
    @IBInspectable var fontSize: CGFloat = 14{ didSet{ restyleTagLabels() }}
    
    
    /// creates tagLabel for every tag and styles them. Calls setNeedsDisplay at end.
    private func reloadTags() {
        print("reloadingTags \(tags.count)")
        subviews.forEach({ $0.removeFromSuperview() })
        
        /*if tags.count == 0 && noTagsLabel != nil && noTagsLabel?.replacingOccurrences(of: " ", with: "") != ""{
            let label = PaddingLabel()
            label.text = noTagsLabel
            
            style(label)
            addSubview(label)
        }*/
        for tag in tags{
            let label = PaddingLabel()
            label.text = tag
            label.numberOfLines = 0
            label.lineBreakMode = .byCharWrapping
            
            style(label)
            addSubview(label)
        }
        layoutTags()
    }
    
    /// restyle every tagLabel
    private func restyleTagLabels(){
        for subview in subviews{
            if let tag = subview as? PaddingLabel{
                style(tag)
            }
        }
    }
    
    /// restyle a single tagLabel
    private func style(_ tagLabel: PaddingLabel){
        tagLabel.numberOfLines = 0
        tagLabel.lineBreakMode = .byCharWrapping
        
        tagLabel.font = UIFont.systemFont(ofSize: fontSize)
        
        tagLabel.layer.borderWidth = tagBorderWidth
        tagLabel.layer.cornerRadius = tagCornerRadius
        tagLabel.textAlignment = NSTextAlignment.center
        tagLabel.backgroundColor = tagBackgroundColor == nil ? UIColor.clear : tagBackgroundColor
        
        
        tagLabel.layer.borderColor = tagColor == nil ? tintColor?.cgColor : tagColor?.cgColor
        tagLabel.textColor = tagColor == nil ? tintColor : tagColor
    }
    
    /// moves tags to right position and resizes frame
    private func layoutTags() {
        var posX: CGFloat = frame.minX
        var posY: CGFloat = 0
        
        for subview in subviews{
            if let label = subview as? PaddingLabel{
                label.frame = CGRect(x: posX, y: posY, width: label.intrinsicContentSize.width  , height: label.intrinsicContentSize.height )
                
                // check if label needs a new line
                if frame.width < CGFloat(posX) + label.frame.width{
                    // reset x
                    posX = frame.minX
                    // move to next line (is still a one line label)
                    posY += label.frame.height + tagMargin
                    
                    // check if label is to big -> multilinelabel
                    if label.frame.width > frame.width {
                        
                        //calculate linecount
                        var lines = ceil(label.frame.width / frame.width)
                        let paddingWidth = label.getSidePadding() * CGFloat(lines) + 2
                        lines = ceil((paddingWidth + label.frame.width) / frame.width)
                        
                        label.frame = CGRect(x: posX, y: posY, width: frame.width, height: (label.intrinsicContentSize.height - label.getTopBottomPadding()) * CGFloat(lines) + label.getTopBottomPadding())
                        
                        posX = frame.minX
                        posY += label.frame.height + tagMargin
                        
                    }else{
                        // reposition label
                        label.frame = CGRect(x: posX, y: posY, width: label.frame.width, height: label.frame.height)
                        posX += label.frame.width + tagMargin
                    }
                }else{
                    posX += label.frame.width + tagMargin
                }
            }
        }
    }
    
    
    public override var intrinsicContentSize: CGSize{
        get{
            if let subview = subviews.last{
                return CGSize(width: -1, height: subview.frame.maxY)
            }
            return CGSize(width: -1, height: minHeight)
            
        }
    }
    
    
    public override func tintColorDidChange() {
        restyleTagLabels()
    }
    
    override public func draw(_ rect: CGRect) {
        super.draw(rect)
        print("Draw")
    }
}

`


And here how to use it in the form:

`<<< TagsRow2<String>(){
                $0.selectorTitle = "Tag(s) auswählen"
                $0.options = ["Das", "ist", "ein", "Test", "544411111111111mmmmmmmmmm544411111111111mmmmmmmmmm544411111111111mmmmmmmmmm", "1", "12", "13", "14", "51", "621", "112412", "544411111111111mmmmmmmmmm", "677671"]
                $0.value = ["Das","544411111111111mmmmmmmmmm544411111111111mmmmmmmmmm544411111111111mmmmmmmmmm", "ist", "ein", "Test", "1", "12", "13", "14", "51", "621", "112412", "544411111111111mmmmmmmmmm", "677671"]
            }`
>

**Comment by mats-claassen** [comment]
This is a question for StackOverflow.

Have you had a look at [TokenRow](https://github.com/EurekaCommunity/TokenRow)? It could be helpful in your case.
