### ISSUE TITLE
How to change ButtonRow section height?

### ISSUE THREAD

**Issue by Hrvoje0099** [xmartlabs/Eureka#1713]
![image](https://user-images.githubusercontent.com/24483776/47952499-9beafd00-df70-11e8-8286-d7bc630a72a4.png)

How to change height of header and footer of ButtonRow?

I try:

`        

            rowSave.section?.header?.height = { return 1 }
            rowSave.section?.footer?.height = { return 1 }
            rowSave.reload()
  `

but nothing work.

**Comment by mats-claassen** [comment]
@Hrvoje0099 Have a look at the Readme section about [Headers and Footers](https://github.com/xmartlabs/Eureka#section-header-and-footer)

**Comment by Hrvoje0099** [comment]
@mats-claassen so, the only solution is to use a Custom View from a .xib file?

**Comment by mats-claassen** [comment]
No, you can do this:

```swift
+++ Section() { section in
                var header = HeaderFooterView<UIView>(.class)
                header.height = {100}
                header.onSetupView = { view, _ in
                    view.backgroundColor = .red
                }
                section.header = header
            }
```

**Comment by Hrvoje0099** [comment]
@mats-claassen I try create this section before ButtonRow what I'm talking about and that not solve my problem. When I create simple ButtonRow he create section above him how you can see on my picture. I want to change height of that section which is included with ButtonRow if you understand me. Other row are one bellow the other, but ButtonRow no, he hase that space between other row. Why? Can i fix that? 
Thank you

**Comment by mats-claassen** [comment]
I do not understand you. ButtonRow does not include a header or footer. If you want to change the height of the cell then you should set `cell.height = { someHeightHere }` in `cellSetup`.
How are you setting up the form?

**Comment by Hrvoje0099** [comment]
@mats-claassen now i figured out what the problem is, when i create my ButtonRow I use +++ instead <<<

+++ ButtonRow() create section above
<<< ButtonRow() create normal row

Sorry and thanks!
