### ISSUE TITLE
Question: Multivalued Section Reorder Callback

### ISSUE THREAD

**Issue by Micrococonut** [xmartlabs/Eureka#1714]
Is there a callback that gets called when a row is reordered in multivalued sections? I would like to change the titles of my row items based off of their index. I'm not sure where I can trigger this title text update.

**Comment by mats-claassen** [comment]
Eureka uses UITableView reordering so that you can override all the UITableViewDelegate methods related to reordering. You should always call `super` in these delegate methods to keep the current functionality
