### ISSUE TITLE
Problem with set text in GenericPasswordRow textfield

### ISSUE THREAD

**Issue by Hrvoje0099** [xmartlabs/Eureka#1716]
In my project I use GenericPasswordRow and i want set text in textfield:

```swift
<<< GenericPasswordRow(){ rowPassword in
    rowPassword.tag = "rowPassword"
 }.cellUpdate({ (cellPassword, rowPassword) in
    cellPassword.textField.clearButtonMode = .whileEditing
    cellPassword.textField.text = "Password123"
    cellPassword.updatePasswordStrengthIfNeeded(animated: true)
})
```

and when I first time click on cell text disappear, how to fix this?

![zwv023f6sg-2](https://user-images.githubusercontent.com/24483776/47969779-df329200-e07c-11e8-8873-32679f183bdb.gif)

Thanks

**Comment by mats-claassen** [comment]
You should open this issue in the repository of GenericPasswordRow.

The cells `textField.text` is tied to the value of the row. You should set the value of the row to "Password123"

**Comment by Hrvoje0099** [comment]
@mats-claassen I solve this problem moving in cellSetup and adding textFieldDidChange:

```
<<< GenericPasswordRow(){ rowPassword in
    rowPassword.tag = "rowPassword"
 }.cellSetup({ (cellPassword, rowPassword) in
    cellPassword.textField.clearButtonMode = .whileEditing
    cellPassword.textField.text = "Password123"
    cellPassword.updatePasswordStrengthIfNeeded(animated: true)
    cellPassword.textFieldDidChange(cellPassword.textField)
})
```

Thanks
