### ISSUE TITLE
how i can make selection on LabelRow

### ISSUE THREAD

**Issue by hell4opt** [xmartlabs/Eureka#1722]
?

**Comment by mats-claassen** [comment]
Hi, @hell4opt, can you be more explicit on what you want to achieve?

**Comment by hell4opt** [comment]
> Hi, @hell4opt, can you be more explicit on what you want to achieve?

when i clicked on LabelRow, i want see selection animation like .default, for example when i click ob push row cell

**Comment by mats-claassen** [comment]
Check out `selectionStyle` variable on the `cell`. You can set that in `cellSetup` for example.

```swift 
.cellSetup { (cell, row) in
     cell.selectionStyle = .default
}
```
