### ISSUE TITLE
How to fix layout of title in Eureka TextRow?

### ISSUE THREAD

**Issue by dev4jam** [xmartlabs/Eureka#1724]
I'm trying to use Eureka TextRow (with default values). I just set title and placeholder (Subject field):

```
let subjectRow = TextRow(tag: "Subject")

subjectRow.title = "Subject"
subjectRow.placeholder = "placeholder"

section.append(subjectRow)

```

But on all iPhone Plus models, this field gets additional 5 pixels in front of title label

This issue doesn't appear on iPhone 6/7/8/X. Only on Plus models. Any ideas how to fix this layout issue?

- Environment: Eureka 4.2.0, Xcode 10.1, iOS 12.1.

![simulator screen shot - iphone 6 plus - 2018-11-22 at 12 12 45](https://user-images.githubusercontent.com/34459912/48876399-009fc600-ee52-11e8-89ab-c1b044d13bcb.png)

**Comment by mtnbarreto** [comment]
I could not reproduce it in the Eureka example app. 
Close due to lack of response.
