### ISSUE TITLE
ERROR:  [framework] CUIThemeStore: No theme registered with id=0

### ISSUE THREAD

**Issue by mitchlau** [xmartlabs/Eureka#1726]
The situation is, when i go in the page with Eureka, the whole IOS Simulator will be frozen and 
have the follow thread in Deactivate breakpoint .   **2018-11-23 12:28:16.969038-0600 XXX XXXX[36063:426659] [framework] CUIThemeStore: No theme registered with id=0**
My Xcode is the newest version, swift is 4.2, IOS Deployment target is 12.0, also i didn't change any code in the Eureka's page recently
below is part of the code and the thread,

<img width="1145" alt="screen shot 2018-11-23 at 12 36 29 pm" src="https://user-images.githubusercontent.com/10535856/48957149-82f4bc80-ef1c-11e8-98d7-f1a81df92550.png">

and below is the cartfile.resolved
github "Alamofire/Alamofire" "4.7.3"
github "SwiftyJSON/SwiftyJSON" "4.2.0"
github "facebook/SocketRocket" "0a023409b138039d1ab5ac5431fe61c5f334e86b"
github "xmartlabs/Eureka" "4.3.0"

Please let me know if there is any further information is needed to solve this problem
thanks you.

**Comment by mitchlau** [comment]
i didn't do anything but the bug just gone away............
after 3 hours, i have no idea why would this happen

**Comment by mats-claassen** [comment]
I do not thin this is related to Eureka itself. I have never seen this issue.

Closing as not Eureka related

**Comment by ykphuah** [comment]
I do get this as a warning everytime I go into a page that have Eureka forms in it. My first two page is a CollectionView and TableView, and this warning doesn't come out.

However, there are no crashes whatsoever, it is just a warning.
