### ISSUE TITLE
Creating Tuple3 for TriplePickerInlineRow

### ISSUE THREAD

**Issue by dote** [xmartlabs/Eureka#1730]
Hi, I'm using a TriplePickerInlineRow. i'd like to have the wheels set to specific values by setting the $0.value like I do in other Eureka Swift fields.

If I try to construct a Tuple3 from some stored string values, I get this:
Cast from '(String, String, String)' to unrelated type 'Tuple3<String, String, String>' always fails

What is the correct way to create a Tuple3 such that the TriplePickerInlineRow wheels are set to specific values? Thank you.

**Comment by mats-claassen** [comment]
Well, its not actually a tuple. I can create it like this:
```swift
let a = Tuple3(a: "a", b: "s", c: "w")
```
