### ISSUE TITLE
Question: Eureka flexibility in custom UI and action

### ISSUE THREAD

**Issue by hungeric** [xmartlabs/Eureka#1732]
Hi I just begin using this Eureka yesterday, I have couple observation and questions to ask, but first of all thank you for this awesome framework and all your work.

my initial impression is it seems the design is each cell/row will take the whole width, if i want to do this in my app https://goo.gl/images/6zwwQp i will have to create a custom row (notice the 3 fields in the screen shot does not expand full width because of picture, is this correct assumption?

Second, it seems the framework, the tap event is always at the cell level.  For instance, in the Example app, you click one example, it takes you to another screen.  But now if, I have a custom view, and have a button in it.  I want user to click on the button to go to another screen (instead of cell), it is doable (by wiring up the button event), but it seems I lost all the existing click event chain offered by framework (e.g. customDidSelect and other functions in SelectorRow) because the framework only handles click at the cell level not item within the cell.  Is this the correct observation?

Can anyone please validate my observations above, I just want to make sure I am not missing anything and making my life harder than it needs to be. 

Thank you!

**Comment by mats-claassen** [comment]
Eureka is based on `UITableView`. The tap events are handled when `func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)` is called. So if another view catches the touch this function won't be called.

As for the cells spanning the full width, this also depends on the `tableView`. You can make the tableview smaller or change its margins to make the cells smaller

**Comment by hungeric** [comment]
@mats-claassen  thank you
