### ISSUE TITLE
[Question] .disable with black font

### ISSUE THREAD

**Issue by radekwilczak** [xmartlabs/Eureka#1733]
I want a Row that can't be edited but looks like normal row (with black font).
I saw the .disable flag - but it changes the font to gray.

Any ideas?

**Comment by radekwilczak** [comment]
Oh! I found:
```
TextRow.defaultCellUpdate = { cell, row in
    cell.textLabel?.textColor = .black
}
```
Is it the right way to do it?

**Comment by mats-claassen** [comment]
Yes. You can also just use a `LabelRow`, which has a UILabel instead of UITextField and is not editable
