### ISSUE TITLE
Set minimum and maximum time for CountDownTimer

### ISSUE THREAD

**Issue by marcmatta** [xmartlabs/Eureka#1734]
- Environment: Eureka 4.3.0, Xcode 10.0 and iOS 12.0

I would like to know if it is possible to specify a maximum and a minimum for the CountDownTimer row like per say: minimum = 1 hour and maximum = 12 hours

**Comment by mats-claassen** [comment]
The docs for `UIDatePicker` say "The minimum and maximum dates are also ignored in the countdown-timer mode". So you can't use those variables.
You could either use `onChange` to limit the maximum and minimum values like this:
```
.onChange({ (row) in
    if row.cell.datePicker.countDownDuration > 120 {
        row.cell.datePicker.countDownDuration = 120
        // update row.value accordingly
    }
}
```

This will, however, show all the options in the picker even if the user can't select them. If you want to limit the options you could also use a `DoublePickerRow`
