### ISSUE TITLE
Parameter step from ViewController to FormViewController

### ISSUE THREAD

**Issue by Mobilityappsinc** [xmartlabs/Eureka#1735]
Hello, I have a problem because I have my FormViewContoller with a UiNavigationController and I want to pass a value from the main ViewController to the FormViewContoller where my form is, but apparently it does not detect the variables that I have declared in the latter.

How can I pass a value from my main screen (UiViewController) to my FormViewController via a UiNavigationController?

![image](https://user-images.githubusercontent.com/39609778/49682107-b7678d00-fa73-11e8-8039-3d6ca7457611.png)

![image](https://user-images.githubusercontent.com/39609778/49682146-a3705b00-fa74-11e8-9d8a-c44c842a733e.png)

Eureka Version  'Eureka', '~> 4.0'
Swift 4.2

Greetings.

**Comment by mats-claassen** [comment]
Hi @Mobilityappsinc This is not an Eureka issue so you should ask it on StackOverflow or another help forum.

You are casting the view controller as FormViewController and not as your subclass of FormViewController. `FormViewController` does not have a `Formulario` variable.
