### ISSUE TITLE
How do I tell Eureka to use an existing tableView for building the form?

### ISSUE THREAD

**Issue by skryshi** [xmartlabs/Eureka#1738]
This seems like a simple question, but I can't find an answer anywhere:

How do I tell Eureka to use an existing tableView for building the form?

```
class MyViewController: FormViewController {
    // I want Eureka to use this tableView for placing the form
    @IBOutlet weak var myTableView: UITableView!
}

```

**Comment by mats-claassen** [comment]
Just connect the outlet to the `tableView` variable in `FormViewController`. If Xcode does not allow you to connect the outlet to that variable then do the following:

* Connect your UITableView to an outlet in `MyViewController` and call that outlet `tableView`
* Xcode will say you cannot override the `tableView` variable
* Delete the outlet in `MyViewController`. Your UITableView will still be connected to (the correct) `tableView` in FormViewController
