### ISSUE TITLE
View does not shift down when section is revealed

### ISSUE THREAD

**Issue by martheli** [xmartlabs/Eureka#1739]
Eureka version 4.2.0

I have a form that takes up the whole screen with the last field being a SwitchRow that reveals a section below it if toggled on. When the row gets toggled on and the section becomes visible, the view doesn't shift down to show this new section so user does not know anything happened.

**Comment by mats-claassen** [comment]
You can do this in the `onChange` of the SwitchRow.

Just call `tableView.scrollToRow(...)` or some method like that.

**Comment by martheli** [comment]
How do I get indexpath of the fields in the hidden section?

**Comment by mats-claassen** [comment]
A hidden section has no indexPath but as soon as you show it it has.
You can do it like `section.first?.indexPath` or just get the indexPath of the SwitchRow (`row.indexPath`) and calculate the indexPath for the next section

**Comment by martheli** [comment]
I included the following in my switch row that reveals the section:

.onChange { (row) in
                
                    if row.value == true {
                        
                        let path = (self.form.rowBy(tag: "title") as? SegmentedRow<String>)?.indexPath
                        
                        self.tableView.scrollToRow(at: path!, at: .bottom, animated: true)
                        
                    }
                    
                }

I would like to scroll to the segentedRow that gets shown after switch row becomes true, when running the above, the app crashes when switch row turns to true. Looks like path does not exist.

**Comment by mats-claassen** [comment]
I tried this code in the examples and it worked:

```swift
override func sectionsHaveBeenAdded(_ sections: [Section], at indexes: IndexSet) {
        super.sectionsHaveBeenAdded(sections, at: indexes)
        if sections.first?.index == 3 {
            self.tableView.scrollToRow(at: (sections.first?.last?.indexPath)!, at: .bottom, animated: true)
        }
    }
```

Which is the crash you are having? You could also try with a small delay before calling `scrollToRow`.

**Comment by martheli** [comment]
I would like the form to shift down only when a SwitchRow is set to true. A second section gets revealed when the SwichRow is set to true and I would like form to scroll down into that newly revealed section.

**Comment by martheli** [comment]
I was able to solve by hard coding the row number and section like this:

```
override func sectionsHaveBeenAdded(_ sections: [Section], at indexes: IndexSet) {
        
        super.sectionsHaveBeenAdded(sections, at: indexes)
        
        if (sections.last?.index == 1) {
            
            DispatchQueue.main.async {
                let indexPath = IndexPath(row: 9 , section: 1)
                self.tableView.scrollToRow(at: indexPath, at: .bottom, animated: true)
            }
            
        }
        
    }
```

Thanks for your help.
