### ISSUE TITLE
Problem with memory leak

### ISSUE THREAD

**Issue by Hrvoje0099** [xmartlabs/Eureka#1742]
Question ih here: [link](https://stackoverflow.com/questions/53804253/problem-with-memory-leak-using-eureka-form?noredirect=1#comment94458265_53804253)

And project on github: [link](https://github.com/Hrvoje0099/My-Password-Manager)

**Comment by funkenstrahlen** [comment]
Please do not just past some links here. Try to put all relevant information in here otherwise this will never get enough attention to be fixed.
