### ISSUE TITLE
Eureka not honouring original UIView.setAnimationsEnabled state 

### ISSUE THREAD

**Issue by cameroncooke** [xmartlabs/Eureka#1749]
It's not entirly clear why Eureka is disbaling and enabling animations here, but it should honor the default state.

https://github.com/xmartlabs/Eureka/blob/10cb4824c0a9875a498551b7af5bc3b58bf4536a/Source/Rows/TextAreaRow.swift#L200

We disable animations when running our app under `XCUITest` but Eureka is turning them back on again globally. I feel that Eureka really shouldn't be messing with global settings like this but if it's nesccessary then might be better to check if they are already disabled and if so do nothing here.

**Comment by mtnbarreto** [comment]
Hi @cameroncooke! you are right!
Can you make a pr with the changes?

**Comment by cameroncooke** [comment]
Will do!
