### ISSUE TITLE
Cannot add row horizontally

### ISSUE THREAD

**Issue by kuoliangkwong** [xmartlabs/Eureka#1755]
Environment: Eureka (4.3.0), Xcode (10.1) and iOS (12.1) you are using.

Is there anyway we can add eureka element horizontally as depicted below? Would like to avoid building a custom view
<img width="260" alt="screenshot 2019-01-09 at 4 46 07 pm" src="https://user-images.githubusercontent.com/8188634/50887433-167f3f80-142e-11e9-8a4c-0a5f349e3474.png">

**Comment by mats-claassen** [comment]
You can use [SplitRow](https://github.com/EurekaCommunity/SplitRow), but only for two rows horizontally. There is no support for stacking three rows horizontally. You will have to create a custom row for this. You could get some inspiration from the [PostalAddressRow](https://github.com/EurekaCommunity/PostalAddressRow)

**Comment by kuoliangkwong** [comment]
Thanks. That's a good guidance. From [PostalAddressRow](https://github.com/EurekaCommunity/PostalAddressRow), how do we apply the RuleRequired on the multiple rows? Currently I'm using `self.row.value = nil` if either one of the rows is not filled. I feel that's not the proper to do it

And how do we customize it to get correct value in self.form.params()?

**Comment by mats-claassen** [comment]
I would suggest to use a struct with a variable for each text field but the value could also be a Dictionary as long as `Key` and `Value` of the dictionary are Equatable (I have not tried this).

As for validation rules, the required rule checks that the value is not nil, so in your case you probably want a custom rule, possibly based on `RuleRequired` but replacing the generic `T` with the value type you choose for the row.

**Comment by myoung959** [comment]
For almost any app I create, the ability to place multiple elements horizontally on a single row is fundamental to the app. Kuoliangkwong's request is welcomed. I second the call for allowing multiple elements on a singe row. His example is a simple key to locating a particular unit in a real estate portfolio. I too work in the real estate space and would like, for example, to place rent in a decimal currency field followed by two date picker fields for the lease term from and to. BTW, I'd also like a simple way to have the date pickers as only two components: month and year.

**Comment by myoung959** [comment]
mats-claassen, hope you could add this request as a "feature request"

**Comment by kuoliangkwong** [comment]
> I would suggest to use a struct with a variable for each text field but the value could also be a Dictionary as long as `Key` and `Value` of the dictionary are Equatable (I have not tried this).
> 
> As for validation rules, the required rule checks that the value is not nil, so in your case you probably want a custom rule, possibly based on `RuleRequired` but replacing the generic `T` with the value type you choose for the row.

I tried with struct and `self.form.params()` returns me entire struct object instead of `key` and `value` structure. Did I miss out anything?

**Comment by kuoliangkwong** [comment]
@mats-claassen, yup it would be in this format currently:
```
[
    "address": Address(
        "street": "6/125",
        "city": "Time Square"
    ),
    "phone_number": "111111111"
]
```

But I wanna customize the row so `self.form.params()` returns this instead of the struct:
```
[
    "street": "6/125",
    "city": "Time Square",
    "phone_number": "111111111"
]
```

**Comment by kuoliangkwong** [comment]
Yup @mats-claassen, was referring to `form.values()`. 

I see, i guess i have to manually convert struct to dictionary instead. Thanks alot for ur help.
