### ISSUE TITLE
How to create custom callback?

### ISSUE THREAD

**Issue by CocoaPriest** [xmartlabs/Eureka#1760]
I'm creating a very simple custom cell with a button and try to understand how to create a callback like for example `onChange`. The way it's done in Eureka, all callbacks are defined in the `Row`. 
But when I try to follow this "guideline" I wonder how to call my custom callback from the cell?

**Comment by mats-claassen** [comment]
What is the callback for? 
As you said callbacks are normally defined in the row as the logic part but you could call them from the cell like `(row as? YouRowType)?.yourCallback()`

**Comment by CocoaPriest** [comment]
yeah, that's what I ended doing. Thanks
