### ISSUE TITLE
Possible Memory Leak in _FieldCell textFieldDidChange

### ISSUE THREAD

**Issue by Kbotei** [xmartlabs/Eureka#1764]
Environment:
Eureka 4.3.0 also tested in 4.3.1
Xcode 10.1
macOS 12.14.2

I was profiling my app in instruments and found a memory leak that appears to be caused by the `UnsafeMutablePointer<T>.allocate(capacity: 1)` in the [FieldRow.swift](https://github.com/xmartlabs/Eureka/blob/95f6f1e1dc23fb9321d740e38003984c967b2541/Source/Rows/Common/FieldRow.swift#L367) file. 

I do not know a lot about how the `UnsafeMutablePointer` and `AutoreleasingUnsafeMutablePointer` work, but after looking at Apple's documentation and a bit of googling I modified the code to deallocate the pointer after the textfields value had been formatted.

```
let unsafePointer = UnsafeMutablePointer<T>.allocate(capacity: 1)
defer {
    unsafePointer.deallocate()
}

let value: AutoreleasingUnsafeMutablePointer<AnyObject?> = 
    AutoreleasingUnsafeMutablePointer<AnyObject?>.init(unsafePointer)
```
This appears to fix the memory leak. As I am not that familiar with the way these pointers work I am not sure if there are any side effects with the deferred deallocation, so I would defer to those with more experience with them.

**Comment by mats-claassen** [comment]
Thanks for pointing this out and coming up with a solution. We will review this issue. I tested the code with that fix and did not find any problem for now

**Comment by TheCyberMike** [comment]
This memory leak is also present in the TextAreaRow in the same 'textViewDidChange' func
