### ISSUE TITLE
titleLabel cannot be customized using xib

### ISSUE THREAD

**Issue by libern** [xmartlabs/Eureka#1767]
For latest version,

I have tried connect to @IBOutlet in  _FieldCell which is super class of TextCell.

```
@IBOutlet public weak var titleLabel: UILabel?
```  

I saw the `CustomDesignController` is able to connect and make it effect in action.

However, I can't use my own custom titleLabel, as it is always created from code:

```

    private func setupTitleLabel() {
        titleLabel = self.textLabel
        titleLabel?.translatesAutoresizingMaskIntoConstraints = false
        titleLabel?.setContentHuggingPriority(UILayoutPriority(rawValue: 500), for: .horizontal)
        titleLabel?.setContentCompressionResistancePriority(UILayoutPriority(rawValue: 1000), for: .horizontal)
    }

```

**Comment by krypt-lynx** [comment]
This is a limitation of swift's UITableView cell. I have no idea how you even able to compile that code: it gives me compilation error about overlapping obj-c method.

I'm set it in this way: 
```swift
    @IBOutlet weak var textLabel2 : UILabel?
    override var textLabel : UILabel? {
        get { return textLabel2 }
    }
```
You need to connect your outlet to textLabel2

**Comment by krypt-lynx** [comment]
Oh, I see, you called it "titleLabel". Right name is "textLabel", you need to return your custom label instead of original.

**Comment by mats-claassen** [comment]
Using `titleLabel` is correct for subclasses of `FieldCell`. @libern did you set the `cellProvider` to load your nib file?

```swift
public final class YourCustomRow: Row<YourCellType>, RowType {

    required public init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<YourCellType>(nibName: "YourCellType")
    }
}
```

**Comment by libern** [comment]
@mats-claassen Yes. I just added the titleLabel to the `CustomDesignController` demo -> `TextCell` xib.

**Comment by krypt-lynx** [comment]
Just encountered the same issue:
Design: 
![image](https://user-images.githubusercontent.com/2183611/51862386-2ca26080-2347-11e9-90ca-c2a917ac42e4.png)
Outlets (like I said, IB does not recognises generic classes):
![image](https://user-images.githubusercontent.com/2183611/51862405-36c45f00-2347-11e9-8c82-3b82247992d9.png)
Result:
![image](https://user-images.githubusercontent.com/2183611/51862605-a0dd0400-2347-11e9-91b7-a2424f6dab35.png)

**Comment by krypt-lynx** [comment]
```Swift
    override var textLabel : UILabel? {
        get { return textLabel2 }
    }
```

Does the thing, except `setupTitleLabel()` still screwing constraints:
![image](https://user-images.githubusercontent.com/2183611/51863106-d8987b80-2348-11e9-9ad0-f16b0607fd03.png)
