### ISSUE TITLE
Conditional disabling of DateInlineRow doesn't work

### ISSUE THREAD

**Issue by Geeo** [xmartlabs/Eureka#177]
I'm doing : 
form +++
            Section(header: "GENERAL", footer: "")
                
                <<< TextFloatLabelRow("row1") {
                        $0.title = "Nom"
                        $0.disabled = true
                    }.cellUpdate{cell, row in
                        cell.textField.enabled = self.isEditable!
                    }
            
                <<< DateInlineRow("row4") {
                        $0.title = "Date d'anniversaire"
                        $0.disabled = Condition.Function(["row1"]) { form in
                        if let row : TextFloatLabelRow = form.rowByTag("row1") {
                            return !row.isDisabled
                        }
                        return false
                    }
                    }

But I can't get the condition to be activated.

**Comment by mtnbarreto** [comment]
@Geeo  
Disabled function is automatically evaluated only when a dependent row value changes. In your particular case eureka checks automatically  if `row4` whenever `row1` value changes.

To force the evaluation of the disabled condition you can invoke row's `.evaluateDisabled()` as this 
FAQ question point out: https://github.com/xmartlabs/Eureka#row-does-not-update-after-changing-hidden-or-disabled-condition

Similar issues #48, #10

Regards

**Comment by Geeo** [comment]
Thanks a lot for help !
