### ISSUE TITLE
SegmentedRow Default value

### ISSUE THREAD

**Issue by dbarrett0815** [xmartlabs/Eureka#1771]
How can I have the segmented control default value be the first segment? I have tried setting the selectedSegment to 0 on cellSetup and update which did not work.

**Comment by mats-claassen** [comment]
Why don't you just set the value of the row to that?

**Comment by dbarrett0815** [comment]
Thanks that worked. I was setting both the selectedSegment and value and I was getting an out of bound error but just setting the value works fine. Thanks
