### ISSUE TITLE
.insert() incorrect arguments

### ISSUE THREAD

**Issue by vinczebalazs** [xmartlabs/Eureka#1772]
_**Environment: Eureka 4.3.1, Xcode 10.1 and iOS 12.1.3**_

I am trying to insert a new row into a section, but I keep getting the following error:

`form.sectionBy(tag: "section1").insert(LabelRow() at: 0)`

> Incorrect argument labels in call (have '_:at:', expected 'row:after:')

Strangely enough, **this works:**
`form.rowBy(tag: "row1").section?.insert(LabelRow() at: 0)`

Any ideas what am I doing wrong?

**Comment by mats-claassen** [comment]
It looks like a wrong error message. I think `sectionBy(tag:)` returns Optional, so you should put a `?` after calling it. Did you try that?

**Comment by vinczebalazs** [comment]
Yes unfortunately, I even tried force-unwrapping it but no luck :(

**Comment by mats-claassen** [comment]
Found the issue: `insert(_:at:)` is a mutating function so you have to call it on a `var`.

Do this:

```swift
var s = form.sectionBy(tag: "section1")
s?.insert(LabelRow(), at: 0)
```

**Comment by vinczebalazs** [comment]
So I believe the correct error message would be something like: 
`Cannot use mutating member on immutable value: 'sectionBy(tag:)' returns immutable value`

Thanks for the quick answer!
