### ISSUE TITLE
Problem in  private func initializeChevrons()

### ISSUE THREAD

**Issue by marioGusmao** [xmartlabs/Eureka#1773]
Hello 

I tried to use this menu library https://github.com/jonkykong/SideMenu
and for the menu root view controller I was using a FormViewController but the app crashes in 
- class NavigationAccessoryView   
- func initializeChevrons()

I started developing my menu I another way, just telling the error so maybe you can improve eureka more 
Thanks

**Comment by marioGusmao** [comment]
one other thing if I put a form controller as the first controller in the menu hierarqui the second time I go to that menu item the app also crashes. but if I embed the for in a tabbarcontroler all works well

**Comment by mats-claassen** [comment]
Hi @marioGusmao could you post more information about the crash? (stack trace, how you set up the form, etc.)

**Comment by marioGusmao** [comment]
sorry let that menu for a wile now and now I'm not able to reproduce the error for the next time I trie to save a version of the app crashing and take some screen shots
