### ISSUE TITLE
Action on mutlivalue delete

### ISSUE THREAD

**Issue by martheli** [xmartlabs/Eureka#1774]
I am trying to do some action after a row gets deleted in a multivalue section. If I try to add 

```
override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
         print("Row is now GONE!")
         tableView.deleteRows(at: [indexPath], with: .fade)
        }
    }
```

Then it messes up adding additional rows. Is there a way within Eureka to respond to delete actions? I am using Eureka 4.2.0

**Comment by m3t8d1tr** [comment]
and how?

**Comment by dneykov** [comment]
Hi @martheli did you find a solution for that? Thanks.

**Comment by martheli** [comment]
@dneykov Yes I did, you have to override the method rowsHaveBeenRemoved
