### ISSUE TITLE
How to show the row again after evaluateHidden

### ISSUE THREAD

**Issue by tzzen93** [xmartlabs/Eureka#1777]
How can I able to show again the row after evaluateHidden. Could you please kindly help me? 
Thanks in advance!

**Comment by mats-claassen** [comment]
The row will be shown again when `evaluateHidden` returns `false`. You should set the condition so that this happens. Possibly you'll have to call `evaluateHidden` again.

**Comment by tzzen93** [comment]
Thank you so much bro! It is working well! Thank you!
