### ISSUE TITLE
1.3.1 The top divider of a PickerInlineRow disappears upon selection

### ISSUE THREAD

**Issue by njovy** [xmartlabs/Eureka#178]
<img width="623" alt="screen shot 2016-01-13 at 4 29 57 pm" src="https://cloud.githubusercontent.com/assets/1792070/12287868/2f4e8796-ba13-11e5-811e-10cb1db780cc.png">

Unlike other InlineRowTypes, The top divider of a PickerInlineRow disappears when a value is set. Also, it doesn't highlight the cell upon focus.

**Comment by eflyjason** [comment]
want to ask too

**Comment by Haggan** [comment]
Ive got sort of a "quick fix" for this problem for anyone experiencing it. In the class that inherits FormViewController I override the didSelectRow function like this: 

``// MARK: Override TableViewDelegate invocation
extension SearchOptionsViewController {
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.deselectRowAtIndexPath(indexPath, animated: false) // Fixes the infamous disappearing top separator for picker cells/rows
        super.tableView(tableView, didSelectRowAtIndexPath: indexPath)
    }
}``

**Comment by Haggan** [comment]
Ive got sort of a "quick fix" for this problem for anyone experiencing it. In the class that inherits FormViewController I override the didSelectRow function like this:

```swift
// MARK: Override TableViewDelegate invocation 
extension SearchOptionsViewController { 
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) { 
        // Fixes the infamous disappearing top separator for picker cells/rows 
        tableView.deselectRowAtIndexPath(indexPath, animated: false) 
        super.tableView(tableView, didSelectRowAtIndexPath: indexPath) 
    }
 }
```

**Comment by mtnbarreto** [comment]
Guys, both issues seem fixed now. 
> Xcode 7.3.1, Eureka master branch, ios 9.3.

Please reopen if you still have these issues.

**Comment by mtnbarreto** [comment]
Finally i found what was causing the issue. Should be fixed now.
