### ISSUE TITLE
Extra argument in call error whith Generic inline picker

### ISSUE THREAD

**Issue by pilloom** [xmartlabs/Eureka#1782]
I test Eureka sample code, i import Eureka but trowh error:  **Extra argument in call error** in **("PickerInlineRow")**

`+++ Section("Generic inline picker")`

            <<< PickerInlineRow<Date>("PickerInlineRow") { (row : PickerInlineRow<Date>) -> Void in
                row.title = row.tag
                row.displayValueFor = { (rowValue: Date?) in
                    return rowValue.map { "Year \(Calendar.current.component(.year, from: $0))" }
                }
                row.options = []
                var date = Date()
                for _ in 1...10{
                    row.options.append(date)
                    date = date.addingTimeInterval(60*60*24*365)
                }
                row.value = row.options[0]
        }

I need Slider row inline, thanks

**Comment by mats-claassen** [comment]
Eureka example works fine. Where is the error?

If you need an inline Slider row then you should follow the guides in the Readme and blog posts and create that row yourself
