### ISSUE TITLE
Eureka install for Swift version 4.2.1 an xcode 10.1 - correct podfile for version 4.3.1

### ISSUE THREAD

**Issue by xpediteur** [xmartlabs/Eureka#1783]
I can not find the right version of a "Podfile" to install Eureka for swift 4.2.1 and xcode 10.1. I want to install Eureka version 4.3.1. My POD-version is 1.5.3 . The installation-guide on github/eureka is a old version for iOS 9 without version of eureka. How should a correct Podfile look like. Please give me an example.

**Comment by mats-claassen** [comment]
You can add this to your podfile:

```
pod 'Eureka' , '4.3.1'
```

and run `pod install`

**Comment by lars03** [comment]
Not working
[!] Unable to find a specification for `Eureka (= 4.3.1)`

**Comment by mats-claassen** [comment]
Try running `pod repo update` before `pod install`?
