### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by elbelga** [xmartlabs/Eureka#1786]
I receive an exception when I call to evaluateHidden to hide a Section

The problem is in file Core.swift 

open func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return height(specifiedHeight: form[section].header?.height,
                      sectionView: self.tableView(tableView, viewForHeaderInSection: section),
                      sectionTitle: self.tableView(tableView, titleForHeaderInSection: section))
    }

I have debugged and I see that section is equal to 1 and form.count is equal to 1.

The call stack is as following

![image](https://user-images.githubusercontent.com/1613259/54273219-b6b82880-4585-11e9-9b2c-6cbbff9d5905.png)

**Comment by mats-claassen** [comment]
Is that issue happening constantly or did it crash only once? Do you have some example to reproduce it?

**Comment by elbelga** [comment]
It's happening constantly, I don't have an example

**Comment by mtnbarreto** [comment]
@elbelga we can provide support but we need further information.
If you are able to reproduce the issue in a new form, we appreciate if you share the code.

**Comment by joost4net** [comment]
I had this same issue. Working workaround for me:

`DispatchQueue.main.async() {
    section.evaluateHidden()
}`

**Comment by melloskitten** [comment]
For anyone experiencing the same problem, make sure to check whether you are appropriately calling the super methods in `viewWillAppear_ animated: Bool)`and `viewWillDisappear(_ animated: Bool)`. For me, not calling the supers resulted either in an out of bounds crash or the cell not doing anything at all, similarly to issue #1656.

**Comment by xannonite** [comment]
I was able to resolve this issue by overriding delegate methods in a class extending FormViewController as follows:
```
override func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        if (section < form.count) {
            return super.tableView(tableView, heightForHeaderInSection: section)
        }
        return 0;
    }

override func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        if (section < form.count) {
            return super.tableView(tableView, heightForHeaderInSection: section)
        }
        return 0;
    }
```

**Comment by mats-claassen** [comment]
Closing this as several options to solve have been reported. Please add more details if anyone thinks it is an Eureka issue
