### ISSUE TITLE
onChange function for every row?

### ISSUE THREAD

**Issue by eflyjason** [xmartlabs/Eureka#179]
For example I want to do `saveConfig()` for every row when `.onChange`. Is there any way to do this? Thanks!

**Comment by mtnbarreto** [comment]
@eflyjason you can override the following `FormViewController` method:

```swift
public func rowValueHasBeenChanged(row: BaseRow, oldValue: Any?, newValue: Any?) {}
```

which is invoked every time a row vale is changed as this [line code](https://github.com/xmartlabs/Eureka/blob/0fbccd174a29f4da5bcc0f633e68f13e3010d654/Source/Core.swift#L1519) illustrates.
