### ISSUE TITLE
Setting SwipeAction backgroundColor has no effect

### ISSUE THREAD

**Issue by funkenstrahlen** [xmartlabs/Eureka#1790]
I am using Eureka 4.3.1 in Xcode Version 10.1 (10B61).

Setting the `SwipeAction` backgroundColor does not work. It only uses the default grey color as you can see in the screenshot:

![Simulator Screen Shot - iPhone XS - 2019-03-20 at 15 26 01](https://user-images.githubusercontent.com/144173/54692057-a4f5f880-4b24-11e9-9cfd-e130c59bde0f.png)

I verified the issue with the included example application. The relevant code is this part:

```swift
            <<< LabelRow("Actions Left & Right: iOS >= 11") {
                $0.title = $0.tag

                let moreAction = SwipeAction(style: .normal, title: "More") { (action, row, completionHandler) in
                    print("More")
                    completionHandler?(true)
                }

                let deleteAction = SwipeAction(style: .destructive, title: "Delete", handler: { (action, row, completionHandler) in
                    print("Delete")
                    completionHandler?(true)
                })

                $0.trailingSwipe.actions = [deleteAction,moreAction]
                $0.trailingSwipe.performsFirstActionWithFullSwipe = true

                if #available(iOS 11,*) {
                    let infoAction = SwipeAction(style: .normal, title: "Info", handler: { (action, row, completionHandler) in
                        print("Info")
                        completionHandler?(true)
                    })
                    infoAction.backgroundColor = .blue

                    $0.leadingSwipe.actions = [infoAction]
                    $0.leadingSwipe.performsFirstActionWithFullSwipe = true
                }
```

Expected: The last `infoAction` should have a blue background color.

Actual:  The action only has the default grey background color for normal actions.

**Comment by funkenstrahlen** [comment]
This can be closed as soon as the PR is merged.

**Comment by mkoorn** [comment]
@mtnbarreto are there plans to create a release with this fix? I'm using Eurkea in a development pod and can only reference Eureka depency from pod specs.
thanks.
