### ISSUE TITLE
Segmentation fault: 11 when building to simulator with Xcode 10.2

### ISSUE THREAD

**Issue by jofford** [xmartlabs/Eureka#1794]
Upgraded to latest XCode (10.2, 10E125) and my primary project to Swift 5.  I've cleaned and reinstalled all cocoapods and still get this error, but only when trying to build it in the simulator.  Building works fine when targeting a physical device or "Generic iOS Device".

**Comment by Kbotei** [comment]
I encountered the same issue using cocoapods. I was able to fix the issue by removing the pod and installing via Carthage instead.

**Comment by mtnbarreto** [comment]
Thanks for reporting! I will take a look and release a new version by tomorrow night.

**Comment by 3a4oT** [comment]
@mtnbarreto still have plan to release?

**Comment by mtnbarreto** [comment]
Hi Guys! I just released Eureka 5.0.0. Sorry for the delay.. Let me know if it works!

**Comment by dadixon** [comment]
I'm running Xcode 11.4 with Swift 5 and I get this error as well. Not when I run it in the simulator but when I try to archive the project.

**Comment by arsinio** [comment]
Having same issue with Eureka 5.2.0...only when archiving the project (via Cocoapods)

**Comment by mats-claassen** [comment]
@arsinio Use version 5.2.1

**Comment by arsinio** [comment]
Confirmed this fixed it for me! Thank you!

**Comment by zas9vf** [comment]
This is  great...I just had the same prob w. Xcode 11.4 and bumping to 5.2.1 fixed it!

Good looks guys
