### ISSUE TITLE
textLabel overlaps detailTextLabel when using long String #1172 : getting error on snp

### ISSUE THREAD

**Issue by PreetikaSingh** [xmartlabs/Eureka#1797]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by PreetikaSingh** [comment]
Hi Im facing issue on this

![Screen Shot 2019-03-29 at 4 55 55 PM](https://user-images.githubusercontent.com/46670148/55229855-1d0a9f80-5244-11e9-9f87-977fdf1c0d29.png)


Please let me know what is snp here ? How can we get through it!

**Comment by mats-claassen** [comment]
That is not something related to Eureka. There is no `snp` variable in Eureka
