### ISSUE TITLE
Hidden Section does not evaluateDisabled when its shown.

### ISSUE THREAD

**Issue by dazeili** [xmartlabs/Eureka#1799]
Hi, I got a SwitchRow that hides or shows a section.
And I got an "Edit/Done"-Button in the Navigationbar that enables/disables the whole FVC.

So when i click on Edit only the SwitchRow gets enabled when the section is hidden. So i call the onChange of the switch row to evaluate all rows:

`.onChange({ _ in
                    self.form.rows.forEach{
                        $0.evaluateDisabled()
                    }                    
                })`

but that seems to not trigger cause the show event seems to be executed after. 
Is there a callback like .onShow or an other possible way how to achieve this?

The show condition looks like this:

`
    var hideOnUseNoWeatherCondidion = Condition.function(["useWeather"], { form in
        if let useWeather = (form.rowBy(tag: "useWeather") as? SwitchRow)?.value{
            return !useWeather
        }
        return false
    })`

And the disabled condition like this:

`$0.disabled = Condition.function([]) { _ in return !self.editMode }`

**Comment by mats-claassen** [comment]
Instead of using `form.rows` you could use `form.allRows` or `allSections` to loop over the hidden rows/sections as well and `evaluateDisabled`

**Comment by dazeili** [comment]
Ah very nice. Thank you!

**Comment by mtnbarreto** [comment]
You can also add a hidden row that indicates if the form is in edit mode or not. 

then use this new row id (`editEnabledId`) to hide the rest of the form
`$0.disabled = Condition.function(["editEnabledId"]) { _ in return !self.editMode }`

whenever the edit mode changes reflect the change in the edit hidden row. 

By doing that i think you don't longer need to call `evaluateDisabled` on every row.
