### ISSUE TITLE
Changing the value of an ActionSheetRow from another row ( rowByTag  )

### ISSUE THREAD

**Issue by RafaelGadret** [xmartlabs/Eureka#18]
Hello!
I’m Trying to change a value of a ActionSheetRow based on the value of a DateTimeRow from inside the OnChange() function.
When I try to create a constant “mycell” using the rowByTag function the compiler throws: 'Cannot convert value of type 'BaseRow?' to specified type 'ActionSheetRow!’
But if I change the type to DateTimeRow it compiles fine. See example below.
How can I make it work?
Thanks!

...
  <<< DateTimeRow() { $0.value = NSDate(); $0.title = "DateRow"

            }.onChange(){ [weak self] row in
		// this will not work
                let mycell: ActionSheetRow! = self?.form.rowByTag("myth”)

		// this will work - changed type to DateTimeRow
                let mycell2: DateTimeRow! = self?.form.rowByTag("mytag")

              }

**Comment by RafaelGadret** [comment]
After a little struggle, The correct answer is: 
 let mycell: ActionSheetRow<String>! = self?.form.rowByTag("mytag”)

**Comment by mtnbarreto** [comment]
@RafaelGadret `ActionSheetRow` is a generic type so the proper way to get the row is `let mycell: ActionSheetRow<String>! = self?.form.rowByTag("myth”)` considering the row value type is String. 

If you are using another row value type you should replace String by this type.
