### ISSUE TITLE
Unable to update PickerRow options dynamically

### ISSUE THREAD

**Issue by bourgeois** [xmartlabs/Eureka#180]
I tried multiple ways to update a `PickerRow` options dynamically without any success.

Here are the two ways I tried to update it,

    let pickerRowLocation = pickerRow as! PickerRow<Location>
    pickerRowLocation.options = data
    pickerRowLocation.value = data.first
    pickerRowLocation.updateCell()

And with

    form.setValues(["locations": data])
    self.tableView?.reloadData()

Neither of them seems to work (it shows nothing, like it is not updating).

Am I missing something ? Am I doing it the right way ?

Thanks for any help !

**Comment by bourgeois** [comment]
I managed to make it work by calling `cell.picker.reloadAllComponents()` manually. Maybe this should be added to Eureka code ?

Here the complete solution,

    <<< PickerRow<Location>("locations") {
        $0.hidden = "$destination != 'Plant / Site'"
        $0.title = "Destination"
    }.cellUpdate { cell, row in
        row.options = self.locations
        cell.picker.reloadAllComponents()
    }

**Comment by mtnbarreto** [comment]
@bourgeois thanks for reporting the issue! 

 now  `pickerRowLocation.updateCell()` should work.
