### ISSUE TITLE
Eureka swift 5

### ISSUE THREAD

**Issue by devLoop1** [xmartlabs/Eureka#1801]
Hello, I have a problem with eureka in the version of Swift 5 with xcode 10.2, the problem that it indicates is code and that the pod must be updated, when they update Eureka for swift 5.

Eureka, Swift 5, Xcode 10.2
![alerta](https://user-images.githubusercontent.com/48538624/55324703-43edef00-5459-11e9-938a-3ba049d464de.jpg)

**Comment by mtnbarreto** [comment]
I just pushed a swift 5 compatible version. Let me know if it works now.

**Comment by devLoop1** [comment]
Hi, apparently the update works for swift 5.
However, I get some errors that may not be related to Eureka, but I add a screenshot in case you can help me.
<img width="961" alt="Captura de Pantalla 2019-04-01 a la(s) 17 41 18" src="https://user-images.githubusercontent.com/48538624/55358522-fd72b180-54a5-11e9-889a-97394b604bee.png">
