### ISSUE TITLE
Missing TextFloatLabelRow class in base library

### ISSUE THREAD

**Issue by absoftware** [xmartlabs/Eureka#1802]
I would expect that after `pod install` I will have full working library. But I've met following issue that class `TextFloatLabelRow` from your example is not included into this library. So this example is indeed quite wrong. It shows possible use cases but part of them is implemented in Example project and part of them is available after `pod install`. I had to copy most of source files from your Example project to my project to make it working. More over there is also similar class `TextFloatLabelRow` in another repository https://github.com/EurekaCommunity/FloatLabelRow which is not maintained, but it seems that it's for the same purpose as class `TextFloatLabelRow` in the example. Maybe example just shows how to implement custom cells, but it would be nice to use all stuff from example immediately after `pod install` without copying files manually.

**Comment by mats-claassen** [comment]
The example is indeed trying to show how to implement custom rows from outside of the main library. And as you pointed out, [FloatLabelRow](https://github.com/EurekaCommunity/FloatLabelRow) can be used if you need those rows. If it is not working for the latest release please open an issue in that repository
