### ISSUE TITLE
Carthage build broken for swift 5

### ISSUE THREAD

**Issue by slessans** [xmartlabs/Eureka#1803]
When trying to install release 5.0.0 with carthage, the build fails. The detailed log info terminates with this statement:

```
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Eureka')
```

I am using Swift5, xcode 10.2, carthage 0.31.2.

**Comment by mtnbarreto** [comment]
Can you check that the Eureka code cloned by carthage is the same as master branch...?

**Comment by slessans** [comment]
This was my fault, carthage was using the wrong toolchain (not actually swift 5). Thanks for the quick response.
