### ISSUE TITLE
Removing rows/sections doesn't remove observers - Causes memory leak

### ISSUE THREAD

**Issue by nvonahsen** [xmartlabs/Eureka#1804]
- Environment: Eureka 4.3.1, Xcode 10.1,  iOS 12.1
- Edit: Also on Eureka 5.0.0, Xcode 10.2, iOS 12.1

After running form.removeAll to remove all rows/sections from our form then adding more rows we noticed a memory leak where rows weren't getting released properly.

After looking into it and stepping through the code it seems that form.removeRowObservers isn't removing observers properly, The below screenshots show the state of the rowObservers dictionary before and after the the code that should remove the "showFan2" observer. 

![Screen Shot 2019-04-02 at 12 33 13 PM](https://user-images.githubusercontent.com/16808913/55366073-a9b6a580-5543-11e9-8e3f-d86c44797138.png)
![Screen Shot 2019-04-02 at 12 33 30 PM](https://user-images.githubusercontent.com/16808913/55366074-aa4f3c00-5543-11e9-95a3-dc34bb6fcbb0.png)

As far as I can tell this seems to be a case of editing the local copy arr without applying the changes to the actual observer array at form.rowObservers

I tried editing the eureka code to the below and that seemed to work for me. There might well be a better way to do it, just trying to show the issue.

```
func removeRowObservers(from taggable: Taggable, rowTags: [String], type: ConditionType) {
        for rowTag in rowTags {
            guard var arr = rowObservers[rowTag]?[type], let index = arr.index(where: { $0 === taggable }) else { continue }
            arr.remove(at: index)
            rowObservers[rowTag]?[type] = arr // + this line
        }
   }
```

**Comment by funkenstrahlen** [comment]
Did you ensure your observing closures use weak references? Otherwise this causes a memory cycle and leaks memory.

**Comment by nvonahsen** [comment]
Hey, i've created a simple demo repo to show the issue https://github.com/nvonahsen/EurekaBugDemo (see. EurekaDemo/ViewController)

the issue comes up even when only using a simple listener created by the inbuilt Condition.function:
``` 
row.hidden = Condition.function(["ShowHideRow"], { form in
  ((form.rowBy(tag: "ShowHideRow") as? SwitchRow)?.value ?? false)
})
```

Besides its not a circular reference issue anyway. The problem isn't that the observers don't get de-inited properly, the observer never even gets removed from form.rowObserservers. It actually continues to be called by the form even though the row it's related to has been removed.

(Maybe calling it a memory leak wasn't the right move since its not really leaking memory, the problem is that the observer fails to get removed from the form, even though removeRowObservers definitely looks like it is meant to do this)
