### ISSUE TITLE
Autocomplete/SearchTextField question 

### ISSUE THREAD

**Issue by Nolascoin** [xmartlabs/Eureka#1805]
Question, 

The inline suggestions provided by  https://github.com/apasccon/SearchTextField seems nice, but I don't think we have this with functionality with Eureka, or is there?

So, I mixed the two 
https://gist.github.com/Nolascoin/0769dd2d364efa2a58faa0628dabb083

![sample](https://user-images.githubusercontent.com/45103170/55520132-dd2f2800-5648-11e9-8800-1e2396b8ac16.gif)

**Comment by mats-claassen** [comment]
I think the closest that we have is the [TokenRow](https://github.com/EurekaCommunity/TokenRow) and [SuggestionRow](https://github.com/EurekaCommunity/SuggestionRow)

**Comment by mats-claassen** [comment]
I will close this as it is no issue nor feature request. People looking for a search textfield can still find it
