### ISSUE TITLE
HeaderFooterView is immutable

### ISSUE THREAD

**Issue by AndrewSB** [xmartlabs/Eureka#181]
Hey!
Trying to add a customized HeaderFooterView to my section, getting an error whenever I attempt to assign to a variable of the HeaderFooterView, heres my code: 

```
Section() { section in
var header = HeaderFooterView(title: "lol")
  
  header.onSetupView = { view, _, _ in

  }

  header.height = { 100 }

  section.header = header
}
```

Getting errors on the `header.onSetupView` and `header.height` lines, saying `Cannot assign to property: 'header' is immutable`.

Super confused, any idea what could be wrong?

**Comment by mtnbarreto** [comment]
hey @AndrewSB. 

Note that this init is optional:

```swift
    public init?(title: String?){
        guard let t = title else { return nil }
        self.init(stringLiteral: t)
    }
```

so your code should be changed to:

```swift
Section() { section in
    var header = HeaderFooterView(title: "lol")
    header?.onSetupView = { view, _, _ in 
    }
    header?.height = { 100 }
    section.header = header
}
```

Alternatively you can use `public init(stringLiteral value: String) ` which is not optional and keep your code as it is. 

Regards
