### ISSUE TITLE
SegmentedRow onRowValidationChanged never called.

### ISSUE THREAD

**Issue by dleute** [xmartlabs/Eureka#1818]
This one is simple, onRowValidationChange doesn't seem to get triggered for a SegmentedRow using an object. At least with displayFor.

I have not tested with a simple string array.

I discovered this while creating a callback to update a save button state when the form is invalid. I was going to rely on onRowValidationChanged but found it wasn't called. I moved the button state updating to onChanged. In the case of a SegmentedControl it is exactly the same amount of work.

In addition, I have observed inconsistency in onRowValidationChanged on other rows, but I have not identified a pattern. I switch everything to onChanged for now until I have more time to experiment.

Can anyone verify that onRowValidationChanged does work for SegmentedRow?

**Comment by mats-claassen** [comment]
It works for me. SegmentedRow is different to text rows, for example, as it cannot have focus (be firstResponder). Therefore the options ` validatesOnBlur` and `validatesOnChangeAfterBlurred` do not make sense. You can use any other option for `validationOptions`.

It works with this set up: (`Scientist` is an `Equatable` struct, and `users` is a list of Scientists)

```swift 
<<< SegmentedRow<Scientist>(){
    $0.title = "Who are you?"
    $0.options = users
    $0.value = nil
    $0.add(rule: RuleRequired())
    $0.validationOptions = .validatesAlways
    $0.displayValueFor = { value in
        return value == nil ? "None" : "\(value!.firstName) \(value!.lastName)"
    }
}.onRowValidationChanged({ (cell, row) in
    print(row.isValid)
})
```

`onRowValidationChanged` gets called when the value changes or when `form.validate` or `row.validate` is called
