### ISSUE TITLE
ImageRow doesn't disable

### ISSUE THREAD

**Issue by PeeJWeeJ** [xmartlabs/Eureka#182]
ImageRow seems to no longer be disabled properly. 

I'm guessing it's due to the recent addition of the picker, but I haven't investigated it too far.

If I have a chance soon I'll issue a pull request, but a work around is to subclass/extend the _ImageRow class and add 

```swift
public override func customDidSelect(){
	if(!self.isDisabled && !self.isHidden){
		super.customDidSelect()
	}
}
```

**Comment by weyert** [comment]
Sorry, could well be my mistake.

**Comment by mtnbarreto** [comment]
@PeeJWeeJ Thanks for reporting it!
