### ISSUE TITLE
How can I set the default font for my eureka form

### ISSUE THREAD

**Issue by username10123** [xmartlabs/Eureka#1823]
I'm using a Eureka form with TextRows, SegmentedRows, TextFieldRows, DateRows etc. in Swift.
I'm trying to set the default font of the entire form to a custom font that I just put into my project.
I have tried looping through all of the rows like this:
for row in form.rows {
            row.baseCell.detailTextLabel?.font = UIFontMetrics.default.scaledFont(for: customFont)
            row.baseCell.detailTextLabel?.adjustsFontForContentSizeCategory = true
}
This only updates the detail label in certain rows, and I just want to be able to set the default font of the entire form in one place. 

Is this possible?

**Comment by mats-claassen** [comment]
You cannot set one font for all the labels in the forms of your app. However, you can use the static `defaultCellSetup` on each type of row to set the font for that row type:

```swift
TextRow.defaultCellSetup = { cell, row in cell.titleLabel.font = myCustomFont }
// ...
```

> Note that FieldRow subclasses (those with textField) have a `titleLabel` while most other cells use `textLabel` and possibly `detailTextLabel`

**Comment by username10123** [comment]
Thanks for your response! 

This is working for the title label for text row, but not the "value" label. I'm pre-populating the form, and the TextRow value is being set. My code looks like this:
TextRow.defaultCellSetup = { cell, row in
            cell.titleLabel?.font = formFont
            cell.detailTextLabel?.font = formFont
            cell.textLabel?.font = formFont
}

I tried to see if there was another label I was missing, but couldn't find one.

**Comment by mats-claassen** [comment]
The `TextRow` does not have a value label. It has a `textField`.

The SegmentedRow has a `segmentedControl: UISegmentedControl` which you can edit.

**Comment by username10123** [comment]
@mats-claassen 
I realize none of the rows have a "valueLabel" I just wanted to explain what I was referring to. I just tried to set the textField font for the TextRow and it is still not working.
