### ISSUE TITLE
TextRow Textfield doesn't update with changed value on cellUpdate

### ISSUE THREAD

**Issue by caffeineflo** [xmartlabs/Eureka#1825]
Environment: iOS 12.2, Xcode 10.2.1, latest Eureka version using carthage

I've searched through the issues but the related issues didn't provide a solution.

Here's the related Eureka cell:

```
var selectedCustomer: CNContact? {
        didSet {
            form.rowBy(tag: "customerEmailCellTag")?.evaluateHidden()
            form.rowBy(tag: "customerEmailCellTag")?.updateCell()
            form.rowBy(tag: "customerNameCellTag")?.evaluateHidden()
            form.rowBy(tag: "customerNameCellTag")?.updateCell()
        }
}
...
            <<< TextRow("customerNameCellTag") {
                $0.hidden = Condition.function([], { [weak self] _ in
                    return self?.selectedCustomer == nil
                })
                $0.placeholder = "Customer Name"
            }.cellUpdate { (cell, row) in
                row.value = self.selectedCustomer?.displayName
                cell.textField?.font = UIFont.font(forTextStyle: .callout)
                cell.textField?.textColor = .gray800
            }
... (same customerEmailCellTag cell)
```
 
The app provides it's own VC to have the user select as CNContact called through the onSelection on a ButtonRow. The CNContactPicker is dismissed and the VC receives the selected CNContact. 

**Behaviour:** 
On the first first selection: Rows are no longer hidden, accurate information is filled in for the given value into the textField.
When `selectedCustomer` changes, the cell is not updated (the first time). When `selectedCustomer` changes a second time, the cells are updated perfectly again.

I debugged through cellUpdate and the correct value is supplied, yet, the cell isn't being updated. 
When doing a tableView reload, I'm getting the form to update properly each time and not just every second try. But this doesn't seem to be right. 
Anyone can point out what I'm doing wrong?

Thanks

**Comment by mats-claassen** [comment]
You should not set `row.value` inside `cellUpdate`. `cellUpdate` takes `row.value` and updates the cell with that. This means you should first set `row.value` and then call `updateCell()`

**Comment by PatilRupaliAress** [comment]
> You should not set `row.value` inside `cellUpdate`. `cellUpdate` takes `row.value` and updates the cell with that. This means you should first set `row.value` and then call `updateCell()`

Where to write this code, please suggest.
