### ISSUE TITLE
Result of multivaluedRowToInsertAt not available in section.allRows

### ISSUE THREAD

**Issue by robbiet480** [xmartlabs/Eureka#1830]
It seems that the row returned by `multivaluedRowToInsertAt` in a `MultivaluedSection` is not available after it has been added in `section.allRows`. I need this to work so that I can save the state of the entire section to my database, including the row positions. I've tried digging into this quite a bit tonight but am unable to figure out where the bug exists. Hoping one of the smarter developers can figure it out faster than I'll be able to. 

I'm on bleeding edge Eureka master (specific commit is https://github.com/xmartlabs/Eureka/commit/e73f408c89f9afa48e2843bc650c2ec7dc150efd).

Here's a example implementation that fails. It uses the same example shown in README.md except for the added tag in the `NameRow`:

```swift
let mvSection = MultivaluedSection(multivaluedOptions: [.Reorder, .Insert, .Delete],
                   header: "Multivalued TextField",
                   footer: ".Insert adds a 'Add Item' (Add New Tag) button row as last cell.") {
    $0.addButtonProvider = { section in
        return ButtonRow(){
            $0.title = "Add New Tag"
        }
    }
    $0.multivaluedRowToInsertAt = { index in
        return NameRow() {
            $0.placeholder = "Tag Name"
            $0.tag = "new_row_\(index)"
        }
    }
    $0 <<< NameRow() {
        $0.placeholder = "Tag Name"
    }
}

self.form +++ mvSection

// Some time later, maybe in rowsHaveBeenAdded
print("All rows", mvSection.allRows)
// newRows will contain nothing because the newly added row isn't in allRows
let newRows = mvSection.allRows.filter { $0.tag?.hasPrefix("new_row") }
if newRows.count == 0 {
  fatalError("Couldn't find the new row!")
}
```

**Comment by mats-claassen** [comment]
It works for me. I tried accessing the section not by holding a variable but directly from the form. You can do that using the sections index or its tag. For example, this works in the example project:

```swift
print(form.first?.allRows)
```
