### ISSUE TITLE
Customize addButtonProvider in MultivaluedSection

### ISSUE THREAD

**Issue by jacktiong92** [xmartlabs/Eureka#1832]
Hi everyone!

First of all, thank you so much for maintaining Eureka. It's really awesome!

I would like to know if it's possible to customise the addButtonProvider UI in MultivaluedSection from
![IMG_0182](https://user-images.githubusercontent.com/10499544/57594537-2db47200-7573-11e9-8b46-f945435bc77e.jpg)

to
![image](https://user-images.githubusercontent.com/10499544/57594556-46248c80-7573-11e9-923a-52c46a23a259.png)

Thank you.
Best Regards,
Jack Tiong

**Comment by mats-claassen** [comment]
This is currently not possible but we are looking into it

**Comment by jacktiong92** [comment]
Thank you so much @mats-claassen :)
