### ISSUE TITLE
Change the label, text field position in a TextRow

### ISSUE THREAD

**Issue by vivekanarther** [xmartlabs/Eureka#1834]
I would like to change the label and textField position in a TextCell
Looks like I need to create a custom cell and override the customConstraints method to accomplish this.  Is there any way to accomplish this through the current TextCell itself?

**Comment by mats-claassen** [comment]
You are correct, that is one way of changing the layout of text rows: subclass `_FieldCell` and override at least `customConstraints`.

Another way that should work is using a nib file to design your cell and define your constraints there. Then connect the outlets for the `textField` and `titleLabel` variables. Finally, load the nib file by setting the `cellProvider` of the row:

```swift
<<< TextRow() { row in
   row.cellProvider = CellProvider<MyTextCell>(nibName: "MyCustomTextCell", bundle: Bundle.main)
}
```

**Comment by vivekanarther** [comment]
Thank you!
