### ISSUE TITLE
MultivaluedSection addButtonProvider not working

### ISSUE THREAD

**Issue by dkroukamp** [xmartlabs/Eureka#1837]
Hi there

Im trying to extend the a MultivaluedSection and set the title of the "Add" button in the MultivaluedSection I have adapted my example from here https://github.com/xmartlabs/Eureka#multivalued-sections, but it does not work for me:

```
import Eureka

final class FileResponseMessageFieldRow: MultivaluedSection {
    
    init(tag: String, title: String)
    {
        super.init()
        
        self.tag = tag;
        self.header = HeaderFooterView(title: title)
        self.multivaluedOptions = [.Insert, .Delete]
        //self.footer = HeaderFooterView(title: ".Insert adds a 'Add Item' (Add New Tag) button row as last cell.")
        self.addButtonProvider = { section in
                return ButtonRow() {
                    $0.title = "Add File"
                }
            }
        self.multivaluedRowToInsertAt = { index in
            return FileRow()
        }
        
    }
    
    convenience init(responseMessageField: ResponseMessage.Field)
    {
        self.init(tag: responseMessageField.name, title: responseMessageField.displayName)
    }
    
    required init<S>(_ elements: S) where S : Sequence, S.Element == BaseRow {
        fatalError("init has not been implemented")
    }
    
    required init() {
        fatalError("init() has not been implemented")
    }
    
    required init(multivaluedOptions: MultivaluedOptions, header: String, footer: String, _ initializer: (MultivaluedSection) -> Void) {
        fatalError("init(multivaluedOptions:header:footer:_:) has not been implemented")
    }
}
```

However that simply produces:
![Untitled](https://user-images.githubusercontent.com/37366218/57917091-4cc54380-7894-11e9-9947-08c0b4af7dad.png)
As you can see it does not change the "Add" text to "Add File"

Any help would be appreciated.

**Comment by mats-claassen** [comment]
You should call the init `super.init(multivaluedOptions:, header: , footer: , {})` with the corresponding parameters

**Comment by dkroukamp** [comment]
> You should call the init `super.init(multivaluedOptions:, header: , footer: , {})` with the corresponding parameters

Works a charm thanks mate, initially when I tried `super.init` I passed `{ }` as `initializer: { }`, which didn't work of course.
