### ISSUE TITLE
Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

### ISSUE THREAD

**Issue by onvika** [xmartlabs/Eureka#1845]
Hi, I am using swift 4.1 and Xcode 9.4.1
if I use Eureka '4.2' I get bunches of errors
if I use Eureka '4.0' I get this: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

I have already tried this: pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'

I have include this: post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == 'Eureka'
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '4.1'
end
end
end
end

I think I have read and tried almost all, and yet... I can not solve it ;/
any ideas ??

_Originally posted by @onvika in https://github.com/xmartlabs/Eureka/issues/1568#issuecomment-496016148_

**Comment by mats-claassen** [comment]
When you try Eureka 4.0 then you should build it with Swift 4 (not 4.1). You can change that in the Build Settings of the Eureka target in the Pods project
