### ISSUE TITLE
Clean the values ​​of the textrow and decimal row Formatter

### ISSUE THREAD

**Issue by devLoop1** [xmartlabs/Eureka#1846]
Hi, maybe you can help me do the following:
- I have an itembar that when I click clean the values ​​of the rows.
- I am applying a decimalRow format that gives me 0.51, but I want it to be 5.1, as you can see in the placeholders.
I hope you can help me.
Excuse my English, it's not my language.
The attached file captures the code and the view.

- Swift 5
- Eureka 5
<img width="471" alt="Captura de Pantalla 2019-05-27 a la(s) 12 05 08" src="https://user-images.githubusercontent.com/48538624/58430722-8b1ee780-8078-11e9-93fa-5ee95c771974.png">
<img width="375" alt="Imagen PNG 2" src="https://user-images.githubusercontent.com/48538624/58430708-7b9f9e80-8078-11e9-8139-ed59c951014b.png">
<img width="324" alt="Captura de Pantalla 2019-05-26 a la(s) 23 42 47" src="https://user-images.githubusercontent.com/48538624/58394256-4fe8ce00-8010-11e9-87f6-7b9533cbd4c2.png">

**Comment by mats-claassen** [comment]
To clean the values of the form you can use `form.setValues` with a dictionary mapping the tags of the rows to their value (nil or "" or whatever)

As for the formatting have a look at DecimalFormatter properties. You can change the maximum and minimum fraction digits and so on.
