### ISSUE TITLE
DateInlineRow does not add inline section, fails to expand new table row

### ISSUE THREAD

**Issue by apcro** [xmartlabs/Eureka#1847]
Environment: 
* Eureka 5.0.0 (and 4.3.1 when downgraded for testing)
* XCode 10.1
* Swift 4.2

Details:
A previously-working form with multiple fields now fails with an existing (and previously working) DateInlineRow.
DateInlineRow fails to add the new inline DatePicker section, and also fails to expand the new table row.
When tracing through the podfiles, `InlineRowType.swift` line 87 does not appear to actually append the new inline section (`section` before and after the `.insert` is the same length). The following line (L88) will perform the visible table scroll though.

```
if let indexPath = indexPath {
     _inlineRow = inline
>>>    section.insert(inline, at: indexPath.row + 1)
    cell.formViewController()?.makeRowVisible(inline, destinationScrollPosition: destinationScrollPosition)
}
```
`inline` appears to hold the correct `DatePicker` row, `section` appears to hold all the correct rows as configured in source. `indexPath.row` (and `indexPath.row + 1`) are within the bounds of the number of elements in `section` as well (in my example, `indexPath.row = 2` and `section.count = 11`)

**Comment by mats-claassen** [comment]
DateInlineRow seems to work well in the latest Eureka code. Can you give us a form to reproduce this issue?

**Comment by apcro** [comment]
The following is a (lightly redacted) copy of the form in question. Removed are setting `row.value`, a `PickerDelegate` for Row 6 (which loads data from an API - this normal picker works perfectly), and a `DateInlineRow.defaultCellUpdate` to set the row font. (removing this make no difference either).

The `DateInlineRow` (row 3) still does not work using Xcode 10.2.1/Swift 5 (setting the Eurkea Pod to use Swift 5 explicitly), or with either Eureka 4.3.1 or Eureka 5.0.0 - this was tested by forcing 4.3.1, doing a clean install of all pods (and the pod cache), and switching between 4.3.1 and 5.0.0. The non-working behaviour is exhibited in all cases.

The controller imports only `UIKit` and `Eureka`, and extends `FormViewController`.

The visible action is the picker becomes highlighted when tapped the first time, and greys out when tapped again, however the actual datepicker does not appear in the row below. 

There are no delegates or other references to the datepicker anywhere in the App source (only in the Eureka pod). I've also not put this form into another project to see if it's specifically Eureka, or Eureka not playing nice with another library somewhere (even though no others are loaded into this view controller)

(Side note: removing the 3 additional `form +++ Section()` lines does not make a difference)

```
override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView?.backgroundColor = UIColor.white
        
        var mainSection = Section("Main") { section in
            var header = HeaderFooterView<UIView>(.class)
            header.height = {100}
            header.onSetupView = { view, _ in
                view.backgroundColor = UIColor.White
                let title = UILabel(frame: CGRect(x:10,y: 5, width:self.view.frame.width, height:80))
                title.text = "title"
                view.addSubview(title)
                
                let description = UILabel(frame: CGRect(x:10,y: 70, width:self.view.frame.width, height:20))
                description.numberOfLines = 0
                description.text = "description"
                view.addSubview(description)
            }
            section.header = header
        }
            
        <<< TextRow() { row in
            row.title = "Row 1"
            row.tag = "row1"
            row.add(rule: RuleRequired())
            row.validationOptions = .validatesOnChangeAfterBlurred
        }
        .cellUpdate { cell, row in
            if !row.isValid {
                cell.textLabel?.textColor = .red
            }
        }
        
        <<< TextRow() { row in
            row.title = "Row 2"
            row.tag = "row2"
            row.add(rule: RuleRequired())
            row.validationOptions = .validatesOnChangeAfterBlurred
        }
        .cellUpdate { cell, row in
            if !row.isValid {
                cell.textLabel?.textColor = .red
            }
        }
        
        <<< DateInlineRow() { row in
            row.title = "Date Entry"
            row.tag = "selectdate"
            row.add(rule: RuleRequired())
            row.validationOptions = .validatesOnChangeAfterBlurred
        }
        .cellUpdate { cell, row in
            if !row.isValid {
                cell.textLabel?.textColor = .red
            }
        }
        
        <<< EmailRow() { row in
            row.title = "Row 4"
            row.tag = "row4"
            row.add(rule: RuleRequired())
            row.add(rule: RuleEmail())
            row.validationOptions = .validatesOnChangeAfterBlurred
        }
        .cellUpdate { cell, row in
            if !row.isValid {
                cell.textLabel?.textColor = .red
            }
        }
        
        <<< PhoneRow() { row in
            row.title = "Row 5"
            row.placeholder = "row 5"
            row.tag = "row5"
        }
            
        <<< PickerInputRow<String>() { row in
            row.title = "Row 6"
            row.tag = "row6"
        }
        
        <<< PickerInputRow<String>() { row in
            row.title = "Row 7"
            row.tag = "row7"
        }
        
        <<< TextRow() { row in
            row.title = "Row 8"
            row.tag = "row8"
        }
        
        <<< IntRow() { row in
            row.title = "Row 9"
            row.disabled = true
            row.value = 9999
        }

        <<< TextRow() { row in
            row.title = "Row 10"
            row.placeholder = "(row10)"
            row.tag = "row10"
        }
                
        <<< TextRow() { row in
            row.title = "Row 11"
            row.placeholder = "(row11)"
            row.tag = "row11"
        }
        
        form +++ mainSection
        
        form +++ Section()
        form +++ Section()
        form +++ Section()
        
    }
```

**Comment by mats-claassen** [comment]
I copied your form and run in on the master branch and the DateInlineRow is working as expected. There must be something else breaking it.

**Comment by apcro** [comment]
I'm going to chalk this up to 'I don't know'. I am using a `dateinlinepicker` elsewhere and it works fine, but this form it just refuses to (and this controller has less third party imports than the one that works).

I'm using a `DatePicker` row instead to work around this. Thanks for looking in to this.
