### ISSUE TITLE
Cannot get values from SegmentedRow

### ISSUE THREAD

**Issue by rzubeldia** [xmartlabs/Eureka#185]
I'm trying to get values from a SegmentedRow, but xCode show me the next error: "Cannot convert value of type BaseRow? to specified type SegmentedRow"

let Preg1: SegmentedRow  = form.rowByTag("Q1")

any clue?
Thanks

**Comment by mtnbarreto** [comment]
Hey @rzubeldia 
I have answered something similar here: #18
Regards!
