### ISSUE TITLE
How to make custom PushRow from nibname 

### ISSUE THREAD

**Issue by alquhait** [xmartlabs/Eureka#1850]
Hello guys,
I'm trying to build form with PushRows but I don't wont the title of the row beside the displayValueFor, I want them in multiple line like this:

title                       ==   options to choose
displayValueFor   == | select item     -> |

so I need to customize the row, I did that by this peace of code:
```
 open class _NewPushRow<Cell: CellType>: SelectorRow<Cell> where Cell: BaseCell {
    
    public required init(tag: String?) {
        super.init(tag: tag)
        
       presentationMode = .show(controllerProvider: ControllerProvider.callback { return 
       SelectorViewController<SelectorRow<Cell>> { _ in } }, onDismiss: { vc in
            let _ = vc.navigationController?.popViewController(animated: true) })
      }
    }

    public final class NewPushRow<T: Equatable> : _NewPushRow<PushSelectorCell<T>>, 
    RowType {
        public required init(tag: String?) {
            super.init(tag: tag)
        }
}
```

Bu the problem is I cant alter the row by inserting the nibname with NewPushRow.xib.
So I need help to customize this row

**Comment by alquhait** [comment]
No answer at all?

**Comment by mats-claassen** [comment]
You could try to use the `subtitle` cellStyle by setting `row.cellStyle = .subtitle` in the initializer. If that is not enough, there are many issues as how to create a row with a nib file, and this section in the [README](https://github.com/xmartlabs/Eureka#basic-custom-rows)

**Comment by alquhait** [comment]
> You could try to use the `subtitle` cellStyle by setting `row.cellStyle = .subtitle` in the initializer. If that is not enough, there are many issues as how to create a row with a nib file, and this section in the [README](https://github.com/xmartlabs/Eureka#basic-custom-rows)

You are right, Thank you
