### ISSUE TITLE
Detect which `View` was clicked on a `Cell`

### ISSUE THREAD

**Issue by korantengNanaYaw** [xmartlabs/Eureka#1855]
i have three UIImageView on a single Cell when i click on any of the UIImageView on the cell i want to detect which one was clicked on onCellSelection, without placing a UITapGestureRecognizer on each UIImageview.

               func SocialViewRow(address: SocialMedia)-> ViewRow<SocialMediaViewFile> {
         let viewRow = ViewRow<SocialMediaViewFile>() { (row) in
           row.tag = UUID.init().uuidString
            }
    .cellSetup { (cell, row) in
        //  Construct the view
        let bundle = Bundle.main
        let nib = UINib(nibName: "SocialMediaView", bundle: bundle)

        cell.view = nib.instantiate(withOwner: self, options: nil)[0] as? SocialMediaViewFile
        cell.view?.backgroundColor = cell.backgroundColor
        cell.height =  { 50 }
        print("LINK \(address.facebook?[0] ?? "")")

        cell.view?.iconOne.tag = 90090

        //self.itemDetails.activeURL = address

        let openFace = UITapGestureRecognizer(target: self, action: #selector(QuickItemDetailVC.openFace))
        let openT = UITapGestureRecognizer(target: self, action: #selector(QuickItemDetailVC.openTwit))
        let you = UITapGestureRecognizer(target: self, action: #selector(QuickItemDetailVC.openYouYub))

         cell.view?.iconOne.addGestureRecognizer(openFace)

         cell.view?.iconTwo.addGestureRecognizer(openT)
         cell.view?.iconThree.addGestureRecognizer(you)

        cell.frame.insetBy(dx: 5.0, dy: 5.0)
        cell.selectionStyle = .none

    }.onCellSelection() {cell,row in

     //example   
    //print(iconTwo was clicked)

}

return viewRow`

**Comment by alquhait** [comment]
This is what I did for multiple buttons:
`       
      func createForm() {
        let section = Section("new Form")
        form +++ section
        
        section <<< Buttons("id") { row in
            // do stuff
        }.cellUpdate({ (cell, row) in
            cell.btn1.tag = 1
            cell.btn1.addTarget(self, action: #selector(sendActions), for: .touchUpInside)
            cell.btn2.tag = 2
            cell.btn1.addTarget(self, action: #selector(sendActions), for: .touchUpInside)
        })
    }
    func sendActions(_ sender: UIButton) {
        
        if sender.tag == 1 {
            // do stuff
        }
        if sender.tag == 2 {
            // do stuff
        }
        
    }
`

**Comment by mats-claassen** [comment]
Closing due to lack of activities
