### ISSUE TITLE
Can custom UITableViewCell be reused in Eureka?

### ISSUE THREAD

**Issue by damozhang** [xmartlabs/Eureka#1861]
In my project, I use not only Eureka FormViewController but also native TableViewController.
I have many custom UITableViewCell.

Indeed, I know how to create a custom row in Eureka, and I do it in my project.

Does anyone know how to reuse custom UITableViewCell in Eureka FormViewController?

Thanks.

**Comment by mats-claassen** [comment]
To be used in Eureka, the cell needs to be a subclass of `Cell` which is a subclass of `UITableViewCell`. You could try using a subclass of `Cell` in your UITableViewController.
Another solution could be to create a UIView with the contents of the cell and add that to a `Cell` or `UIITableViewCell`
