### ISSUE TITLE
Is it a good approach if I re-render the form if I update my data on my Data Model ?

### ISSUE THREAD

**Issue by aldoblack** [xmartlabs/Eureka#1864]
So, I am fairly new to iOS and this might be a dumb question.

This is how I show my data from Web Service to Eureka Form:

1. I get the data as JSON from Web Service
2. I paste the JSON to my Data Model.
3. Then I paste my Data Model to my form.

Now, when I make changes to my data model I want that these data to be updated in the form.

My approach is that after I update the data in my Data Model, I remove all rows and then I call the function that renders the form.

Is this the best approach? Do you have any suggestions?

**Comment by funkenstrahlen** [comment]
Hi @aldoblack! Welcome to the iOS Developer Community! It's great you ask these kind of questions to learn how to architect your code.

I understand you ask your question about this repository right on Github. However GitHub Issues should be used to discuss feature requests and bug reports. They are not suitable for these kind of support questions.

Please ask questions like this on Stackoverflow.com. That's the perfect place to find help in this case.

**Comment by mats-claassen** [comment]
Thanks @funkenstrahlen, that is right.
