### ISSUE TITLE
Example app crashes, Native iOS Event Form->Alert

### ISSUE THREAD

**Issue by cool8jay** [xmartlabs/Eureka#1865]
When selecting any Alert item, it crashes.

Mac: 10.14.5
Xcode: 10.2.1
Simulator: iPhone Xr
Date: 2019-06-10

<img width="1552" alt="Screen Shot 2019-06-10 at 11 48 14 PM" src="https://user-images.githubusercontent.com/55504/59207886-89a60100-8bda-11e9-95a8-212980583023.png">

**Comment by mats-claassen** [comment]
This should be fixed with #1851
