### ISSUE TITLE
Custom form

### ISSUE THREAD

**Issue by devLoop1** [xmartlabs/Eureka#1867]
Hello, how can I create a form in which a text window can add a button on the left side, similar to the photo I attached?
The idea is that by entering the text arrow and clicking on the button show the information that I look for in a database and then show the eureka form, it is possible to generate the eureka form after pressing the search button.
I consulted since in the view I can combine the form eureka with textfield and button of Xcode.
<img width="376" alt="Captura de Pantalla 2019-06-13 a la(s) 03 32 39" src="https://user-images.githubusercontent.com/48538624/59412899-79358800-8d8c-11e9-93a4-eec4e45f4668.png">

- Swift 5
- Xcode 10.2.1
- Eureka 5

**Comment by JulianSong** [comment]
This lib is hard to customize. And the code is inflexible. I was trying to use  FormViewController to create my own form. I found it's hard to change the cell background color and text color. Anything I was set has been covered by the default value.  The NavigationAccessoryView is also annoying.

**Comment by mats-claassen** [comment]
This is a question more suited for StackOverflow. It is no issue or feature request.
