### ISSUE TITLE
Spacing between Text and Image on TextRow or LabelRow

### ISSUE THREAD

**Issue by iguron** [xmartlabs/Eureka#1868]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by iguron** [comment]
I see that there is no way to define the width/height of the image to be shown on the textRow or LabelRow. But is there any chance to define the spacing between the text and the image? Or also align the image to the left?

thanks in advance.

**Comment by mats-claassen** [comment]
To avoid the image to be bigger than the row, set `cell.height` to something reasonable. 
To change spacings from the default row you should create a custom nib file and use that with the row you want to use (https://github.com/xmartlabs/Eureka#subclassing-cells-using-the-same-row)
