### ISSUE TITLE
Duplicate row tag in different sections

### ISSUE THREAD

**Issue by ialimz** [xmartlabs/Eureka#1869]
I have many sections that are created dynamically according to servers response.
Response may have nested objects that have same properties with same keys, In eureka, I separate this objects by putting them into different sections.
Logically same keys in different sections should not cause duplicate tags error, but in `BaseRow.swift` due to `rowsByTag` dictionary that flattens all rows and then check duplicate tags, I get error

```
final func wasAddedTo(section: Section) {
        self.section = section
        if let t = tag {
            assert(section.form?.rowsByTag[t] == nil, "Duplicate tag \(t)")
            self.section?.form?.rowsByTag[t] = self
            self.section?.form?.tagToValues[t] = baseValue != nil ? baseValue! : NSNull()
        }
        addToRowObservers()
        evaluateHidden()
        evaluateDisabled()
    }
```

**Comment by mats-claassen** [comment]
The tag should identify the row uniquely in the form, not only the section. This is among other reasons because `form.values` returns a map/dictionary of tag => value, for the whole form.
You could append or prefix a section identifier to each row, for example.
