### ISSUE TITLE
What about adding Swift Package Manager support?

### ISSUE THREAD

**Issue by funkenstrahlen** [xmartlabs/Eureka#1871]
Xcode 11 allows adding swift packages very easily. Have you thought about adding SPM support to Eureka? I could not find any old discussion about this here, therefore I would like to start one!

I personally would love to use Eureka via swift package manager. It does not support assets though. However as far as I can tell this should not be an issue for Eureka.

**Comment by mats-claassen** [comment]
It is good to have this discussion. It might be worth it if several people request it. I do not have an idea of how many projects are using SPM compared to Cocoapods or Carthage.

**Comment by thebluepotato** [comment]
For now, since SPM support in Xcode and for iOS/tvOS/watchOS projects has only been added in Xcode 11 beta 1, there aren't many developers using SPM, but I guess more and more are trying to adopt it since it's easy to manage and keep up-to-date.

So in short: SPM is used way less than Carthage or Cocoapods _for now_, but I think it'll change soon!

**Comment by thebluepotato** [comment]
Based on the Podspec, the main if not only obstacle is the Eureka.bundle file which can't be used with SwiftPM. I've written the `Package.swift` file in approximately 2 minutes, builds and tests perfectly. I just expect it to complain when the chevrons are used. PM available soon for discussion.

**Comment by kostyan5** [comment]
+1 for wanting SPM support and agree with @thebluepotato that very soon SPM will take over Carthage and Cocoapods.

**Comment by dan-hart** [comment]
I agree with @kostyan5, It's only a matter of time, and then SPM will be the dominant dependency manager.

**Comment by Satwa** [comment]
SPM is way easier as it is integrated to Xcode, definitely needs the support for this lib

**Comment by NathanFallet** [comment]
I’m already adding my libs with SPM so it would be great to add support for it. I don’t succeed using Carthage or CocoaPods...

**Comment by txaiwieser** [comment]
Any news on this?

**Comment by txaiwieser** [comment]
I saw that #1877 implements all the basic functionality, its just missing the bundle

**Comment by DanTheColoradan** [comment]
I tried Swift Package Manager today. It looks pretty good and would use if for eureka (instead of Carthage). Did this get resolved?

**Comment by nidegen** [comment]
I'd love to have it too. Couldn't we just draw the chevrons in the `.bundle` instead of using image files?

For me even a version without the `.bundle` would be ok:)

**Comment by macblazer** [comment]
Since it's just the six image files, how about base64 encoding the image data?  Include the string in a source file, and base64 decode the string back into the image at runtime only when it's needed.

**Comment by nidegen** [comment]
totally agree, base64 encoding would be the easiest:)

**Comment by waterskier2007** [comment]
Swift Package Manager should have resource support soon, as there was a recent swift proposal that was accepted to support resources in SPM.

**Comment by funkenstrahlen** [comment]
Awesome if SPM gets native support. Do you have a link to the accepted proposal?

**Comment by waterskier2007** [comment]
Sorry, I was replying through email before. Here is the link to the proposal - https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md

I will find the link to the acceptance post and edit this post.

**Comment by nidegen** [comment]
on second thoughts: We don't know how long it goes until Xcode supports the newest SPM and as the drawing is fairly lightweight, I would still go for the drawing option..

**Comment by flannerykj** [comment]
Any updates on this? Would love to use SPM for Eureka.

**Comment by AndrewBennet** [comment]
I've implemented the drawing option in https://github.com/xmartlabs/Eureka/pull/1976, which removes the bundle, and makes SPM support simple.
