### ISSUE TITLE
Still remains row tag in form after removed it

### ISSUE THREAD

**Issue by hojatdelfan** [xmartlabs/Eureka#1873]
hi
I've read this issue #626 for remove row, after removed row by section it there is still tag.
I have three rows in on section that unique tag is set to any of the rows. Before I add that, I use custome row/cell in eureka as AddressRow.

```
section
  <<< AddressRow() {
      $0.tag = "destination_\(index)"
      $0.value = AddressCellModel(name: "street 1")
       }.cellSetup { cell, row in
       cell.delegate = self
       }.onCellSelection({ [weak self] (cell, row) in
           guard let index = row.indexPath else {return}
           print("index: \(index)")
       })
```
These three rows are created as "destination_0", "destination_1", "destination_2". It is necessary to keep the sequence in row tags. The problem is, I've removed the second row and I'm going to set the row tags again in order, But this time the third row comes in place of the second row and its tag value changes "destination_2" to "destination_1" by below code.
```
section.remove(at: index) // index equal is 1
section.reload()
section.allRows.enumerated().forEach { (offset, element) in
            if let row = element as? AddressRow{
                row.tag = "destination_\(offset)"
            }
        }
```

I'll printed all the form tags again
```
form.allRows.enumerated().forEach { (offset, element) in
            if let row = element as? AddressRow{
                print(row.tag)
            }
        }
        // output: "destination_0" "destination_1"
```

My question is here when a row is removed from the section, why is the tag still inside form?
```
if let row = form.rowBy(tag: "destination_2") as? AddressRow {
            print(row.value) // print addresses
        }
```

if i want to add next destination by "destination_2" tag, occurs crash "Duplicate tag".

**Comment by MosayebG** [comment]
I have this problem too.

**Comment by mats-claassen** [comment]
Changing the tag of a row is not supported. Think of changing the id of an object in the database. For that to work, remove the row from the form. Then, change its tag and re-add it to the form
