### ISSUE TITLE
Eureka Code Signing Issue

### ISSUE THREAD

**Issue by riverbaymark** [xmartlabs/Eureka#1874]
Eureka version Eureka at 5.0.0
Xcode Code version 10.2.1

I am getting the following error when archiving trying to submit my app to the App Store..

Code signing "Eureka.framework" failed.

I have disable bitcode and have used the following run phase script (which has worked in the past but not now for this issue):

# Type a script or drag a script file from your workspace to insert its path.
# skip if we run in debug
if [ "$CONFIGURATION" == "Debug" ]; then
echo "Skip frameworks cleaning in debug version"
exit 0
fi

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

Any help would be greatly appreciated.

Mark

<img width="731" alt="Screen Shot 2019-06-24 at 11 15 17 AM" src="https://user-images.githubusercontent.com/24192428/60031222-52236400-9672-11e9-9344-80c4a5da4f96.png">

**Comment by mats-claassen** [comment]
I have never had issues with code signing Eureka before. Are other frameworks working? 
I doubt this is an eureka issue. It is most likely some configuration problem.

BTW it would be helpful if you format your issue correctly using Markdown.
