### ISSUE TITLE
Math for Slider Row

### ISSUE THREAD

**Issue by mattsap** [xmartlabs/Eureka#1878]
I'm using the slider row (SliderRow.swift) and it seems counterintuitive regarding the  step count, minimum, and maximum. For example, if I put min of 1 and max of 5 and a step of 1, I'd expect that my choices would be 1, 2,3,4, and 5. However, by the formula, we only would get the values 1 and 5. Instead, I need to use the steps = 4, which just seems unintuitive:

            let stepValue = round((slider.value - slider.minimumValue) / (slider.maximumValue - slider.minimumValue) * steps)
            let stepAmount = (slider.maximumValue - slider.minimumValue) / steps
            roundedValue = stepValue * stepAmount + self.slider.minimumValue
Can someone more mathematically inclined take a look? Should the round function be moved to the roundedValue, rather than the stepValue?

The round will either make it the min or max value since this part normalizes between 0 and 1.  (slider.value - slider.minimumValue) / (slider.maximumValue - slider.minimumValue)

**Comment by mats-claassen** [comment]
You should set `row.steps` to the amount of steps you want the slider to have, not to how big each step is.
