### ISSUE TITLE
Custom row displaying cell label with value

### ISSUE THREAD

**Issue by ednofedulo** [xmartlabs/Eureka#1882]
I created a custom row programatically and i cant hide the UITableViewLabel. 
Even with the `textLabel?.text = ""` as the blog post indicates.

![image](https://user-images.githubusercontent.com/8947399/61537027-7887b580-aa0c-11e9-94e5-1c749b7cac54.png)

```
override func setup() {
        super.setup()
        selectionStyle = .none
        textLabel?.text = ""
        height = { return 180 }
    }
```

**Comment by ednofedulo** [comment]
Had to set
```
 detailTextLabel?.text = ""
```

**Comment by lczalh** [comment]
How did you hide it? detailTextLabel?.text = "" 也无法隐藏

**Comment by daoan1412** [comment]
this works well 
```swift
public override func update() {
        super.update()
        detailTextLabel?.text = ""
    }
```
