### ISSUE TITLE
AlertRow style

### ISSUE THREAD

**Issue by lczalh** [xmartlabs/Eureka#1890]
Hi, I hope you can help me solve the following problems
1. How to change the color of the cancel button
2. How to hide the cancel button
3. How to hide headlines

**Comment by lczalh** [comment]
<<< AlertRow<String>("AlertRow") {
                $0.title = "任务类型:"
                $0.cancelTitle = nil
                $0.selectorTitle = nil
                $0.options = ["线上会议", "市场调研", "分享传播", "技术跟台", "推广拜访", "科会招募","流向调查","通用"]
                $0.value = "请选择任务类型"
                }.cellSetup({ (cell, row) in
                    // row.cell.detailTextLabel?.textColor = UIColor.red。更改默认颜色
                    
                    
                })
                .onChange { row in
                    // 输出选择的内容和索引
                    print(row.value ?? "No Value",row.options?.firstIndex(of: row.value!) as Any)
                    
                    row.cell.detailTextLabel?.textColor = UIColor.black
                }.onPresent({ (form, vc) in
                    vc.optionsProviderRow.cancelTitle = nil
                    
                })


vc.optionsProviderRow.cancelTitle = nil This setting cannot be hidden and will still show default cancellation

**Comment by mats-claassen** [comment]
Similar to #1703. You will have to subclass the SelectorAlertController to do this
