### ISSUE TITLE
Can you please make a release with the fix for #1790

### ISSUE THREAD

**Issue by mkoorn** [xmartlabs/Eureka#1892]
#1790 was fixed just after release 5.0.0

I'm using Eureka in a development pod and can only reference Eureka depency from pod specs.

So it would be great if a release 5.0.1 could be created so I can use the swipe actions with background colors.

thanks.

**Comment by mkoorn** [comment]
@mats-claassen or @mtnbarreto any chance of this happening?

**Comment by mats-claassen** [comment]
Yes this will be done soon

**Comment by mkoorn** [comment]
thank you
