### ISSUE TITLE
custom row dynamic height possible?

### ISSUE THREAD

**Issue by mleatherb** [xmartlabs/Eureka#1894]
Is it possible to have a row use `UITableView.automaticDimension`? I've tried using this in `Setup()`, but my content ends up overlapping.

**Comment by tanpengsccd** [comment]
Me too,I use  UITableView.automaticDimension for row, my content ends up overlapping when subviews's height increase. Is there any way to calculate height  for row/cell again ?

**Comment by tanpengsccd** [comment]
fixed with 
```
cell.reload()
```

**Comment by mats-claassen** [comment]
`UITableView.automaticDimension` is the default height for rows

**Comment by fukemy** [comment]
> Me too,I use UITableView.automaticDimension for row, my conten

where did u call reload?
