### ISSUE TITLE
Is it possible to have 2 TableViews in 1 ViewController?

### ISSUE THREAD

**Issue by maley63** [xmartlabs/Eureka#1901]
I would like to have 2 TableViews in 1 ViewController.  Is this possible?
I would like to have in my ViewController
Eureka TableView at top
UIView in middle 
Eureka TableView at the bottom.

Does anyone know if this is possible?

**Comment by deeje** [comment]
this isn't really a question for Eureka… use compositional view controllers: in a parent view controller, embed two child view controllers.
