### ISSUE TITLE
I need PickerInputRow with Custom UI any help please ?

### ISSUE THREAD

**Issue by Ahmed-Elsman** [xmartlabs/Eureka#1902]
I need to handle PickerInputRow but with new Custom UI stuff like this 
<img width="337" alt="Screen Shot 2019-08-31 at 6 11 49 PM" src="https://user-images.githubusercontent.com/8681037/64066501-d5d17200-cc1a-11e9-9294-82c4ecad46c1.png">
any help please ?

**Comment by adozenlines** [comment]
Design the cell layout in a xib, and add the following line to the PickerInputRow init(tag:) to bind it to the new UI
```
cellProvider = CellProvider<PickerInputCell>(nibName: "PickerInputCell", bundle: .main)
```

**Comment by Ahmed-Elsman** [comment]
@adozenlines: Cell inherited from what?

**Comment by Ahmed-Elsman** [comment]
<img width="980" alt="Screen Shot 2019-08-31 at 9 21 08 PM" src="https://user-images.githubusercontent.com/8681037/64068218-4dac9600-cc35-11e9-8be1-60e89c4a71a5.png">
@adozenlines

**Comment by mats-claassen** [comment]
Every cell should inherit from `Cell<Value>` where `Value` is the type of the cells value. It should also conform to `CellType`.
