### ISSUE TITLE
How to customize SelectorRow section header colors?

### ISSUE THREAD

**Issue by amirfl** [xmartlabs/Eureka#1904]
How can I customize the appearance of a form created by a SelectorRow in Eureka? Specifically, the section header background and text colors.

For my own forms, the following did the trick:
```
func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
        if let header = view as? UITableViewHeaderFooterView {
            header.backgroundView?.backgroundColor = UIColor(named: "TableHeaderBackgroundColor")
            header.textLabel?.textColor = UIColor(named: "TableHeaderTextColor")
        }
    }
```
However, I couldn't find a way to apply the same customization to the option forms that are presented to the user after he taps the selector row.

**Comment by mats-claassen** [comment]
In [this part](https://github.com/xmartlabs/Eureka#how-to-customize-selector-and-multipleselector-option-cells) of the Readme you can see how to customize the cells of such a Form. For headers, I think you will have to change `presentationMode` of the row and return a custom `SelectorViewController`.

Have a look at the [Custom Presenter Row](https://github.com/xmartlabs/Eureka#custom-presenter-rows) section (At the end, where presentationMode is set)
