### ISSUE TITLE
iOS 13 Changes breaks Stepper Cell Layout

### ISSUE THREAD

**Issue by Vortec4800** [xmartlabs/Eureka#1910]
I updated Eureka to the xcode11 branch HEAD to get Dark Mode support so I can release my app for iOS 13, but the stepper row layout seems to be broken now. Here is a screenshot so you can see the issue.

I'll look into it and see if I can put together a PR, but I wanted to bring it to your attention first.

![Simulator Screen Shot - iPhone 11 Pro - 2019-09-14 at 18 23 21](https://user-images.githubusercontent.com/396122/64914745-089c5f80-d71d-11e9-926d-32982daffbb4.png)

**Comment by mats-claassen** [comment]
It did not happen to me on Xcode 11 beta 6. Is this something that popped up on a later version? Which Xcode are you using?

**Comment by Vortec4800** [comment]
This is Xcode 11 GM

**Comment by Vortec4800** [comment]
I just updated to Xcode 11 GM seed 2, no change. Also I reverted back to master branch instead of the xcode11 branch and it's still happening (though with the wrong colors of course) so it seems more like a general iOS 13 bug rather than something having to do with the recent changes.

I looked over the constraints in the cell and they appear correct, so I don't know what's happening. Maybe something to do with hooking into the updateConstraints system?

**Comment by MatrixSenpai** [comment]
+1
Workaround: set an initial value, i.e.
```swift
<<< StepperRow("stepRow") { row in
  row.value = 0.0
}
```

Also note that row _must not be_ initially hidden when showing the form

**Comment by Vortec4800** [comment]
Good find, that does fix it. My particular use case is better with the value unset so the user can pick one, but this is better than having the UI be jumbled.

**Comment by MatrixSenpai** [comment]
Agreed. Although, if you're dynamically hiding and showing the field like me, it won't help much :(

**Comment by mats-claassen** [comment]
#1913 should fix this. You can test it from the `fix/stepper_ios13` branch but it should be merged soon

**Comment by MatrixSenpai** [comment]
@mats-claassen awesome, i'll test it out when i get home today
