### ISSUE TITLE
How can I change one Row's cell

### ISSUE THREAD

**Issue by a2184617** [xmartlabs/Eureka#1915]
Dear!
if I want this:
two row  on one row 
<img width="283" alt="WX20190927-145308@2x" src="https://user-images.githubusercontent.com/21099288/65748531-c4ef2000-e136-11e9-9598-0180fb41d064.png">
How can i do ? can you give me for examples ! Thank you !

**Comment by mats-claassen** [comment]
You can use [SplitRow](https://github.com/EurekaCommunity/SplitRow)

**Comment by a2184617** [comment]
thanks!
