### ISSUE TITLE
Override touchesShouldCancel for custom row

### ISSUE THREAD

**Issue by jdanthinne** [xmartlabs/Eureka#1925]
Hi,
I'm trying to use a custom row with a custom range slider (using [RangeSeekSlider](https://github.com/WorldDownTown/RangeSeekSlider)).
Unfortunately, when I try to use this custom UIControl, the tableView continues to receive the drag events and scrolls, making the control very difficult to use.
Eureka using a UITableView, is there a way to override the `touchesShouldCancel` function to disable scrolling the tableView while dragging the control?

**Comment by mats-claassen** [comment]
Eureka has a SliderRow which uses a Slider inside a row and it works quite well. You could see it that is helpful as an example

**Comment by jdanthinne** [comment]
Yes, a UISlider works fine because it is a UIControl and I think the native UITableView handles that out of the box. Unfortunately it doesn't for custom UIViews.
So do you think the override of `touchesShouldCancel` is possible, or do I have to convert the custom range slider to a UIControl subclass?

**Comment by mats-claassen** [comment]
OK, I see. So it is possible but you must set the tableView of the Form to a custom subclass of yours.
The easiest way to do this is if you are using a Storyboard and your `FormViewController` has a UITableView which is linked to the `tableView` outlet. In that case I think it should work if you create a subclass of UITableView which overrides `touchesShouldCancel`, and any other method you need, and set that as the class of the `tableView` in the Storyboard.

If you are not using Storyboard then you will have to create your UITableView subclass in the init of the FormViewController and possibly adjust its frame later in viewDidLoad. Have a look [here](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Core.swift#L455-L468) to see what Eureka does with the tableView

**Comment by jdanthinne** [comment]
Thanks!
