### ISSUE TITLE
DecimalRow without any format?

### ISSUE THREAD

**Issue by eflyjason** [xmartlabs/Eureka#193]
How can I use a `DecimalRow()` without any formatter?

Currently  when I use the following code:

```
<<< DecimalRow(){
    $0.tag = "TAG"
}
```

and it still convert my value `3359.3` to `3,359.60`. How can I just let it output `3359.3`? Thanks!

**Comment by mtnbarreto** [comment]
@eflyjason 

```swift
<<< DecimalRow(){
    $0.formatter = nil
    $0.tag = "TAG"
}
```

Alternatively if you can use a `TextRow` and change the keyboard options:

<<< TextRow() {
    $0.tag = "TAG"
}
.cellSetup { cell, _ in
        cell.textField.autocorrectionType = .Default
        cell.textField.autocapitalizationType = .Sentences
        cell.textField.keyboardType = .Default
}

Notice that TextRow type is String whereas DecimalRow type is Double. 

related to #264 and #214

**Comment by CutFlame** [comment]
I had this same issue and fixed it this way:
```
        row.validationOptions = ValidationOptions.validatesOnDemand
        row.useFormatterOnDidBeginEditing = false
        row.useFormatterDuringInput = false
        row.formatter = nil
```
