### ISSUE TITLE
Is SearchPushRow feature mentioned in#399 included in 5.1 release? 

### ISSUE THREAD

**Issue by flgadams** [xmartlabs/Eureka#1933]
I see mention of a search capability request in #399. Is "SearchPushRow" now included in this release? I could not find an example in the sample project of 5.1. I'm a new Edureka user. Did I overlook it? Thanks

**Comment by mats-claassen** [comment]
No that is not included in the last release. As it is a custom row it probably would also make more sense to release it separately from Eureka as with the other rows in [EurekaCommunity](https://github.com/EurekaCommunity) (which is a set of custom rows that can be installed in addition to Eureka)
