### ISSUE TITLE
[Question] How to change the font color of a form?

### ISSUE THREAD

**Issue by joerho** [xmartlabs/Eureka#1936]
When using dark mode, the fonts are still black. I would like for it to be white in dark mode. I have tried looping through all rows to change the color but baseRows do not have the attribute 'cellUpdate'.

**Comment by mats-claassen** [comment]
Hi, which version of Eureka are you using? Version [5.1.0](https://github.com/xmartlabs/Eureka/releases/tag/5.1.0) supports dark mode

**Comment by joerho** [comment]
I'm not sure which version of Eureka I'm using. I just add "pod 'Eureka'" to my podfile. I am using swift 5 with xcode 11.

**Comment by mats-claassen** [comment]
Your Podfile.lock will tell you which Eureka version you have installed

**Comment by joerho** [comment]
I am currently using Eureka 5.0.0. What do I add to the podfile in order to get 5.1.0?

**Comment by mats-claassen** [comment]
`pod 'Eureka', '~> 5.1.0'`
