### ISSUE TITLE
Display multiple selector row as string but still return object from callback

### ISSUE THREAD

**Issue by kvnh** [xmartlabs/Eureka#1946]
<<< MultipleSelectorRow<Category>(FormTags.categories) { row in
                row.title = FormTitles.categoriesRowTitle
                row.selectorTitle = "Choose Categories"
                row.options = self.viewModel.categoryOptions // Set of categories
                
                row.displayValueFor = { (rowValue: Set<NonConformanceCategory>?) in
                    return rowValue?.map({ $0.label }).sorted().joined(separator: ", ")
                }
            }.onPresent { from, to in
                to.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: from, action: #selector(self.multipleSelectorDone(_:)))
                
            }.cellUpdate({ cell, row in
                if let rowValue = row.value {
                    let categories = Array<Category>(rowValue)
                    print(categories)
                }
            })

The above code displays the selected categories correctly in a comma separated list.
However in the multi select list the rows appear as the Category struct, eg `Category(id:1, label:'category1')` I just want the label String value to appear in the list here. But I still want to return an Array of Category objects (not the label) so I can update the view model.
When I add the CustomStringConvertible protocol to the Category struct and description, it displays correctly in the list, however the Array of Category objects is not returned to cellUpdate, just the labels.
Is there a solution to this?

    struct Category: Hashable {
        //        var description: String {
        //            return label
        //        }
        
        let id: Int64
        let label: String
        
        func matchesSearchQuery(_ query: String) -> Bool {
            return label.lowercased().contains(query.lowercased())
        }
    }

**Comment by renatoamazillo** [comment]
If I understood you correctly, you just want to customize the info that appears in the selector view controller, right? If that is the case, I recommend you to take a look at the Eureka Example Xcode project, more specifically the `["Custom Cell Push Row"  code inside RowsExample.swift](https://github.com/xmartlabs/Eureka/blob/8e5fc2f07e9449b88d49b8ee166cd3c7b66cd5b4/Example/Example/Controllers/RowsExample.swift#L172-L192)`

**Comment by renatosc** [comment]
If I understood you correctly, you just want to customize the info that appears in the selector view controller, right? If that is the case, I recommend you to take a look at the Eureka Example Xcode project, more specifically the "Custom Cell Push Row" code inside [RowsExample.swift](https://github.com/xmartlabs/Eureka/blob/8e5fc2f07e9449b88d49b8ee166cd3c7b66cd5b4/Example/Example/Controllers/RowsExample.swift#L172-L192)

**Comment by kvnh** [comment]
Thank-you. I have set up a custom xib with basic style, however when I try to open the selector view, it gives this error:

    'Could not cast value of type UITableViewCell (0x1e76cc460) to Eureka.ListCheckCell<AuditComplyNative.MyFormViewController.Category>'

The class and identifier have been set as CategoryCell and I have added the following line of code as per the example
    'class CategoryCell: ListCheckCell<Category> {}'

**Comment by kvnh** [comment]
Thank-you. I have set up a custom xib with basic style, however when I try to open the selector view, it gives this error:

    Could not cast value of type UITableViewCell (0x1e76cc460) to Eureka.ListCheckCell<MyApp.MyFormViewController.Category>
The class and identifier have been set as CategoryCell and I have added the following line of code as per the example
    class CategoryCell: ListCheckCell {}

**Comment by kvnh** [comment]
I got it working. I had placed my CategoryCell class within a VC hence the error. Thanks for your help.
