### ISSUE TITLE
Prevent keyboard from hiding when section reloaded

### ISSUE THREAD

**Issue by kvnh** [xmartlabs/Eureka#1947]
I am adding validation to a TextAreaRow so that when there is no text the cell will highlight red and the section title will update. The problem for me however is that when section.reload() is called, it causes the keyboard to disappear. So on the first keystroke after the row has been set an invalid, the keyboard will disappear. Is there a way to prevent this?

                +++ Section(FormTitles.detailsSectionTitle)
            <<< TextAreaRow(FormTags.details) {
                $0.placeholder = FormPlaceholders.detailsRowPlaceholder
                $0.value = self.viewModel.text
                $0.textAreaHeight = .dynamic(initialTextViewHeight: 20)
                $0.add(rule: RuleRequired())
                $0.validationOptions = .validatesOnChange
            }.onChange { row in
                self.viewModel.text = row.value ?? ""
            }.cellUpdate { cell, row in

            }.onRowValidationChanged { cell, row in
                if !row.isValid {
                    row.section?.header?.title = "----------- invalid ---------"
                    cell.backgroundColor = UIColor.red
                    row.section?.reload()
                } else {
                    row.section?.header?.title = "----------- valid ---------"
                    cell.backgroundColor = .white
                    row.section?.reload()
                }
            }

**Comment by renatosc** [comment]
Why don't you give focus back to that textfield after you reloaded the section?

E.g:
```
.onRowValidationChanged { cell, row in
            if !row.isValid {
                row.section?.header?.title = "----------- invalid ---------"
                cell.backgroundColor = UIColor.red
            } else {
                row.section?.header?.title = "----------- valid ---------"
                cell.backgroundColor = .white
            }
            row.section?.reload()
            cell.textField.becomeFirstResponder()
        }
```
