### ISSUE TITLE
passing data back from a custom FormViewController

### ISSUE THREAD

**Issue by primeviltom** [xmartlabs/Eureka#1951]
Currently on xCode 11.0
Eureka Swift 5.1.0

I am familiar with passing data forward and back between view controllers using protocols/delegate methods, but I am having trouble getting a delegate method to fire when the presented view controller (FormViewController) is dismissed. I have no problems sending data to the presented View Controller, just getting the data/object back to the presenting VC.

My VC's look like: https://imgur.com/a/PXkBBl5 . I'm trying to pass some event data (which is an object) back to the New Post VC.

The relevant code for the buttonRow is as follows:
```
$0.rowRight = ButtonRow(){ row in
                    row.title = "Event/Repeating Post"
                    if isEditingMode {
                        //show event detail //TODO
                    }
                    row.tag = "event"
                    row.presentationMode = .segueName(segueName: "addEvent", onDismiss: nil)
                }.cellUpdate { cell, row in
                    cell.textLabel?.textColor = .gray
                } 
```
```
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
         if segue.identifier == "addEvent" {
            let destinationVC = segue.destination as! AddEventController
            destinationVC.delegate = self
        }
    }
```
On the view controller that is being presented, I have the protocol:
```
protocol AddEventDelegate {
    func eventChosen(event: Event)
}
```
and the delegate set:
`var delegate : AddEventDelegate?`

However, when I tap back on the presented VC, the delegate method on the presenting VC never fires...

```
    func eventChosen(event: Event) {
           print("Event chosen") //DOES NOT WORK
       }
```

Can you advise the best way to send object data back from a presented VC, or get the delegate method to execute?

Thank you!

**Comment by mats-claassen** [comment]
Is `prepare(for segue...` being called in the presenting VC? 

An alternative would be to use the `onDismiss` of `presentationMode` which you set to nil. That closure will be passed the presented view controller

**Comment by primeviltom** [comment]
Thanks for the reply! 

I have the relevant part of `prepare(for segue...) ` in my code snippets above, which sets the delegate as self. In my case AddEventController subclasses FormViewController.

The presented VC has some logic going on in it, which initializes and sets an object I want to use back in the presenting VC, which I would normally use a protocol/delegate to handle. 

Can you give me a basic example of how I would use the onDismiss closure to pass data back from the presented VC, if I can't use a delegate method?

**Comment by mats-claassen** [comment]
> I have the relevant part of prepare(for segue...) in my code snippets above, which sets the delegate as self. In my case AddEventController subclasses FormViewController.

I was asking if that code is being executed (i.e. if you put a breakpoint inside the `if`, does it stop there?).
The delegate method should work.

**Comment by primeviltom** [comment]
I've tested with a dummy variable being set in the prepare for block, which works: i.e.
From the presenting VC
```
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "addEvent" {
           let destinationVC = segue.destination as! AddEventController
           destinationVC.delegate = self
           destinationVC.dummy = "Testing!"
           //TODO, if iseditingmode, set event
        }
```
and the presented VC:
```
class AddEventController: FormViewController {
    
    var dummy : String?
    override func viewDidLoad() {
        print("new event")
        
        super.viewDidLoad()
        print("\(String(describing: dummy))")
        setupView()
        buildForm()
    }
```
The console will print a literal, the set dummy var, and also hit a breakpoint if put in:
```
new event
Optional("Testing!")
```
