### ISSUE TITLE
App Extension, accessory disappears

### ISSUE THREAD

**Issue by qwertycommander** [xmartlabs/Eureka#1956]
Hi,

I'm using SuggestionAccessoryRow in an iMessage App Extension. After the app gets put in a dismissed state, and the user uses the form once more, the accessory row doesn't appear anymore.

I have looked all around to find this issue, but I can't find anything about it.

- Environment: Xcode 11, ios 10.3.1, Eureka v 5.1.0

``` swift
<<< SuggestionAccessoryRow<Location>("Enter a Location") {
                $0.filterFunction = { [weak self] text in
                    (self?.locations.filter({ $0.title?.lowercased().contains(text.lowercased()) ?? false }) ?? [])
                }
                $0.placeholder = "Search for a location"
            }
```

**Comment by mats-claassen** [comment]
This issue should be addressed [in its own repo](https://github.com/EurekaCommunity/SuggestionRow/issues/46)
