### ISSUE TITLE
SelectorViewController with optional section header and footer

### ISSUE THREAD

**Issue by yunhao** [xmartlabs/Eureka#1961]
- Eureka 5.1.0

Currently, `SelectorViewController` will assign an empty string `""` to section header and footer even we want to have `nil` value for header and footer. This behavior is different from native `UITableView` APIs. With such behavior, there will always be an extra spacing between two sections.

https://github.com/xmartlabs/Eureka/blob/8e5fc2f07e9449b88d49b8ee166cd3c7b66cd5b4/Source/Rows/Controllers/SelectorViewController.swift#L193-L194

The above two lines of code are confusing.

<img width="622" alt="Screen Shot 2019-12-30 at 21 28 12" src="https://user-images.githubusercontent.com/10205466/71583902-4ba70500-2b4b-11ea-9770-144ca87a0501.png">

**Comment by mats-claassen** [comment]
You could just put all elements into the same section to achieve that, right?

**Comment by yunhao** [comment]
Yes, I can put them into a single section. 

However, it’s the matter of UI design. Sections are used to arrange information and indicate relationships between data. If you look at the Setting app of iOS, you will find Apple using a lot of sections without headers. This is a feature of UITableView but it is ignored by Eureka. More specifically, Eureka prevent developers from doing that. With Eureka, developers can not achieve this feature that is deliberately designed by iOS.

I suggest to remove these two lines of code in order to have a more flexible API. Eureka is for developers instead of customers. Let developers choose how to deal with their section headers and footers.

**Comment by yunhao** [comment]
![image](https://user-images.githubusercontent.com/10205466/71861838-b4394780-3132-11ea-8d17-550eb0d95371.png)

These are some screenshots of Apple's designs.
