### ISSUE TITLE
How does reload work, and can it be used for sorting?

### ISSUE THREAD

**Issue by GoldenJoe** [xmartlabs/Eureka#1964]
Suppose you build a form with a list of objects that require a new form to be pushed:

```
func makeForm(){
arr_employee.sort(by: Employee.sorter)
+++ Section()

<<< ButtonRow(){ row in
   row.title = "Add New Employee"
   row.presentationMode = .show(controllerProvider: ControllerProvider.callback {return Form_Employee(nil, delegate: self)}, onDismiss: { vc in _ = vc.navigationController?.popViewController(animated: true) })
}

+++ Section(){
   $0.tag = "Employees"
}
        
for employee in arr_employee {
   form.last!
   <<< ButtonRow(){ row in
      row.tag = employee.employeeID
      row.title = employee.fullName
      row.presentationMode = .show(controllerProvider: ControllerProvider.callback {return Form_Employee(employee, delegate: self)}, onDismiss: nil)
   }
}
}
```

Let's say you add a new Employee in one of the delegate callbacks, and want to insert it into the form, ordered by fullName. What's the right way to go about this? Currently I am removing and rebuilding the section, but I assume there's a better way.

**Comment by mats-claassen** [comment]
You can use `insert` to insert a row in a section. You will have to find the correct index yourself but you can use all functions that Swift has for arrays on `Section` (like map, filter, first).
