### ISSUE TITLE
CurrencyFormatter without decimals (whole units only)

### ISSUE THREAD

**Issue by primeviltom** [xmartlabs/Eureka#1967]
Hi there, 

I'd like to have a DecimalRow with a CurrencyFormatter that only accepts integers - whole units only with no decimals, whilst retaining the formatter locale etc. 

I'm sure there should be a straightforward method, but I haven't found anything in the documentation that allows me to keep the numberStyle as currency, but also an integer (i.e. numberStyle = .none)
My code for this row looks like this, but so far doesn't have the desired result.
```
                $0.rowRight = DecimalRow(){
                    $0.placeholder = "$"
                    $0.title = "Price"
                    $0.tag = "price"
                    let formatter = CurrencyFormatter()
                    formatter.locale = .current
                    formatter.allowsFloats = false
                    formatter.numberStyle = .currency
                    formatter.alwaysShowsDecimalSeparator = false
                    $0.formatter = formatter
                    $0.useFormatterOnDidBeginEditing = true
                    $0.useFormatterDuringInput = true
```

Thanks!

**Comment by mats-claassen** [comment]
Have you tried with `formatter.maximumFractionDigits = 0`?

**Comment by primeviltom** [comment]
Thats the one! Thanks mate 😀
