### ISSUE TITLE
EXC_BAD_ACCESS with UITableView as FormViewController inside of a UIViewController

### ISSUE THREAD

**Issue by kmann3** [xmartlabs/Eureka#1973]
XCode 11.3 / iOS 13.1
Setup is fairly simple.
I have two buttons in the top left and top right of the UIViewController and a label at the bottom of it.
In the middle I have a UITableView.
I have an IBOutlet set for the table view as a FormViewController. The reference outlet is a View Controller.
The crash happens when I reference it during ViewDidLoad.

```
class ViewController: UIViewController {
  @IBOutlet weak var dataTableView: FormViewController
  override func viewDidLoad() {
    super.viewDidLoad()
    dataTableView.form ++ Section("Section 1") // <-- This is where the Thread 1: EXC_BAD_ACCESS error is thrown
      <<< TextRow() { row in
        row.placeholder = "Name"
      }
  }
}

```

Am I simply being silly here and I need to make the UIViewController a FormViewController (I'm trying to avoid that because I want two buttons and a label in the form)? or is this a bug?
At the moment I'm specifically trying to make this as simple as possible and the code is pretty small, so I can make any reasonable changes.

I pulled the latest code from git following the instructions:
`$ git submodule add https://github.com/xmartlabs/Eureka.git`

**Comment by mats-claassen** [comment]
FormViewController is just a subclass of UIViewController with some extras. You can simply make your controller be a FormViewController, that does not mean its tableView will cover the whole screen. You must connect the UITableView to the `tableView` outlet of `FormViewController`. But then, you can add buttons and whatever you want to that controller.

**Comment by kmann3** [comment]
Ah ok, thanks!
