### ISSUE TITLE
How to change the height of the ActionSheetRow label?

### ISSUE THREAD

**Issue by muuuh** [xmartlabs/Eureka#1977]
Hello,

I'd like to change the height of the ActionSheetRow label (=title)?

`row.cell.textLabel?.numberOfLines = 0`

didn't work.

Btw. is it possible to make the TextRow input field appear below the TextRow label?

Best regards

**Comment by mats-claassen** [comment]
Sorry for the late reply. For your second question, to make the text field appear below the title you must create a custom row.

ActionSheetRow uses `textLabel` of UITableViewCell. It is sometimes cumbersome to modify the layout of that label. Normally if you want to change that kind of stuff you should make a custom row.
