### ISSUE TITLE
Set displayValueFor property value for MultipleSelectorRow

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [xmartlabs/Eureka#1978]
Eureka 5.1.0
Xcode 11.3
iOS 13.3

I have a struct like this.

```swift
struct Specialty {
    let id: Int
    let name: String
}

extension Specialty: Hashable { }

extension Specialty: Equatable { }

func ==(lhs: Specialty, rhs: Specialty) -> Bool {
    return lhs.id == rhs.id
}
```

I want to show a `MultipleSelectorRow` with instances of this struct. And I want the `name` property value to be displayed in the rows.

If I make the struct conform to `CustomStringConvertible` and return the `name` in the `description` property, it works. 

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-21 at 153518](https://user-images.githubusercontent.com/2551877/72795645-0070a580-3c64-11ea-923f-f4d71c3157ce.jpg)

But then when I retrieve the values from the form `form.values()`, I get only those `name` values as strings. I need the entire `Specialty` objects.

So the solution it assigning the value to the `displayValueFor` property of the `MultipleSelectorRow`. But I'm not sure how to implement it.

How do I get the name from a set of objects? Below is my attempt but it's not returning my desired result.

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-21 at 153451](https://user-images.githubusercontent.com/2551877/72795673-05cdf000-3c64-11ea-8e14-a9e23861e7f5.jpg)

```swift
form
    +++ Section()
    <<< MultipleSelectorRow<Specialty>(tag: "SpecialtiesRow")
        .cellSetup { cell, row in
            row.title = "Specialties"
            row.add(rule: RuleRequired())
            row.options = [s1, s2, s3, s4, s5, s6]
            row.displayValueFor = { (specialty: Set<Specialty>?) in
                return specialty?.map { $0.name }.first
            }
        }
        .cellUpdate{ cell, row in
            if !row.isValid { cell.textLabel?.textColor = .red }
        }

    +++ Section()
    <<< ButtonRow()
        .cellSetup { cell, row in
            row.title = "Submit"
        }
        .cellUpdate{ cell, row in
            if !row.isValid { cell.textLabel?.textColor = .red }
        }
        .onCellSelection { [weak self] cell, row in
            if !self!.form.validate().isEmpty { return }
            guard let values = self?.form.values() else { return }
            print(values)
        }
```

[Demo project](https://www.dropbox.com/s/6x3wpkc68igodoi/eurekademo.zip?dl=0)

**Comment by mats-claassen** [comment]
The correct solution is to conform to `CustomStringConvertible` and return `name` in description as you did.

You will not get only the name in the `form.values()` but the whole item. It might look as you only get the name if you print the values to the console. But if you retrieve the value from the dictionary it should be a `Specialty`

**Comment by Isuru-Nanayakkara** [comment]
Oh okay. I was printing it out and that misled me 😬 Thanks.
