### ISSUE TITLE
Compiler warning: Cast from 'BaseMultivaluedSection' to unrelated type 'GenericMultivaluedSection<AddButtonType>' always fails

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [xmartlabs/Eureka#1982]
## Description

When I build my project, I see warning:
`/Pods/Eureka/Source/Core/Section.swift:540:124: Cast from 'BaseMultivaluedSection' to unrelated type 'GenericMultivaluedSection<AddButtonType>' always fails`

## Environment:
* Eureka (5.2.0)
* Xcode Version 11.3.1 (11C504)
* iOS Deployment Target: iOS 11.0

**Comment by mats-claassen** [comment]
Well, the cast does not fail. Seems an issue with how the compiler handles generics.

A tip that might be helpful is adding this line to your Podfile: 

```
inhibit_all_warnings!
```

That will hide all warnings from Pods in Xcode.

**Comment by vg-identance** [comment]
@mats-claassen well it could silenced inline with something like `... (section as Any) as! GenericMultivaluedSection<AddButtonType> ...` at least until you find better way to achieve desired.
