### ISSUE TITLE
Crash with Xcode 11.4 b1

### ISSUE THREAD

**Issue by skrew** [xmartlabs/Eureka#1987]
Hi,

_Eureka version: 5.2.0 via Pod._

There is a crash with Xcode 11.4 b1, seem to be related with `[unowned self]` in the code.

I know it's just a beta, but this bug(?) needs to be watched.

**Comment by mats-claassen** [comment]
See #1988 for a workaround and comments. This seems to be a bug of the compiler, not Eureka. Will watch it

**Comment by phimage** [comment]
@skrew please close, this is a duplicate issue

**Comment by mats-claassen** [comment]
Is this issue still happening in Xcode beta 3 and iOS beta 6?

**Comment by DG0BAB** [comment]
Yes! Just updated to 5.2.0 and it still happens.
