### ISSUE TITLE
Disabled row font color difficult to read

### ISSUE THREAD

**Issue by rtnlsltn** [xmartlabs/Eureka#1991]
I upgraded from 5.0.1 to 5.2.0 and Xcode10 to Xcode11. I immediately noticed that the disabled row font color is much lighter and harder to read than it was before. The differentiation between the disabled and non-disabled rows was clear before, I don't feel this change was necessary. Regardless, I use many disabled rows in my application and need to brighten them to meet any sort of ADA requirements. Is there a fix for this?

**Comment by mats-claassen** [comment]
The default `textLabel` and/or `textField` textColors are set like this in most rows (to support dark mode):

```swift
if #available(iOS 13.0, *) {
    textField.textColor = row.isDisabled ? .tertiaryLabel : .label
} else {
    textField.textColor = row.isDisabled ? .gray : .black
}
```

You can override that in `cellUpdate` or using `defaultCellUpdate` to set it for all rows of a specific type.
