### ISSUE TITLE
Problem building with XCode 10

### ISSUE THREAD

**Issue by alexisbar** [xmartlabs/Eureka#1993]
Hello,

I have some issues when trying to build a project integrating Eureka (v. 5.2.0) on XCode 10.3

<img width="589" alt="Capture d’écran 2020-02-21 à 15 51 57" src="https://user-images.githubusercontent.com/8861304/75044541-19b67d00-54c2-11ea-8e5f-a498e7d94c30.png">

The README states that the repo should be working on XCode 10.2+ but if I understood the problem, some properties are available only on the iOS 13 SDK, which is not available before XCode 11

EDIT: 
By using the release v5.0.1, my project is building. Maybe adding a note on the README could be useful for this 🙂

**Comment by forceunwrap** [comment]
I guess the maintainer of the repo would be happy if you could add it to the README :)

**Comment by mats-claassen** [comment]
You are right. Sorry for that. You should use the last release before Xcode 11/iOS 13 changes which is 5.0.1 as you said
