### ISSUE TITLE
Segmented Row with $0.tag set doesn't use default value

### ISSUE THREAD

**Issue by dote** [xmartlabs/Eureka#1997]
Hi, I have a segmented row that I can't seem to set the default for.

This doesn't work:
<<< SegmentedRow<String>("Test") {
$0.options = ["test","test2"]
$0.value = "test"
$0.tag = "mytag"
....

I can get it to accept the default value by removing the $0.tag as below:
<<< SegmentedRow<String>("Test") {
$0.options = ["test","test2"]
$0.value = "test"
....

I use the tag so I need that to be there, any thoughts on why this doesn't work? Thank you!
Eureka 4.3.1, Xcode 11.3.1, and iOS 12.4

**Comment by iStorry** [comment]
Well, basically `SegmentedRow("TAG")` & `$0.tag = "TAG"` is same you can set one at a time.

**Comment by mats-claassen** [comment]
Exactly! The first parameter for the instantiation of each row is its tag.
