### ISSUE TITLE
Eureka Crash IOS 13.4 beta 4, Xcode 11.4 beta 3

### ISSUE THREAD

**Issue by johnlietzke** [xmartlabs/Eureka#1999]
I am still experience a crash in iOS 13.4 beta 4 using Xcode 11.4 beta 3.  I have isolated the crash to .cellSetup, .cellUpdate, .onCellSelection where { cell, row in } is called in RowType.Swift. 

I commented out the aforementioned and Eureka was able to load and functioned as expected without these essential features.

The issue was closed but has persisted throughout the 13.4 beta and has not been resolved.  I do not believe it is a compiler error in the beta but some modification that results from the transition to Swift 5.2.

**.cellUpdate**

> public var cell: Cell! {
        return _cell ?? {
            let result = cellProvider.makeCell(style: self.cellStyle)
            result.row = self
            result.setup()
            _cell = result
            return _cell
        }()
    }

Console:

> 2020-03-08 09:58:32.892975-0700 Transit[1660:392741] [ProcessSuspension] 0x1215e1650 - ProcessAssertion::processAssertionWasInvalidated()

Trace: **#6**
>Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000180a6a978 in objc_retain ()
#1	0x0000000102555ef8 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:154
#2	0x0000000102556f14 in protocol witness for TypedRowType.cell.getter in conformance Row<A> ()
#3	0x000000010255d084 in closure #1 in RowType<>.cellUpdate(_:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/RowType.swift:216
#4	0x00000001025569fc in Row.updateCell() at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:178
#5	0x00000001024c5938 in FormViewController.tableView(_:cellForRowAt:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Core.swift:969
**_#6	0x00000001024c5b48 in @objc FormViewController.tableView(_:cellForRowAt:) ()_**
#7	0x0000000184f99b14 in -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] ()
#8	0x0000000184f67408 in -[UITableView _updateVisibleCellsNow:] ()
#9	0x0000000184f84458 in -[UITableView layoutSubviews] ()
#10	0x0000000185245264 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#11	0x00000001877c6a04 in -[CALayer layoutSublayers] ()
#12	0x00000001877ccb5c in CA::Layer::layout_if_needed(CA::Transaction*) ()
#13	0x00000001877d76a0 in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#14	0x0000000187720798 in CA::Context::commit_transaction(CA::Transaction*, double) ()
#15	0x000000018774a128 in CA::Transaction::commit() ()
#16	0x0000000184da9908 in _UIApplicationFlushRunLoopCATransactionIfTooLate ()
#17	0x0000000184e44a60 in __handleEventQueueInternal ()
#18	0x0000000184e3d764 in __handleHIDEventFetcherDrain ()
#19	0x0000000180cac1d4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#20	0x0000000180cac12c in __CFRunLoopDoSource0 ()
#21	0x0000000180cab8b4 in __CFRunLoopDoSources0 ()
#22	0x0000000180ca68e4 in __CFRunLoopRun ()
#23	0x0000000180ca62a4 in CFRunLoopRunSpecific ()
#24	0x000000018ad8e38c in GSEventRunModal ()
#25	0x0000000184db0bf4 in UIApplicationMain ()
#26	0x00000001009e0854 in main at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Transit/AppDelegate.swift:10
#27	0x0000000180b2d8f0 in start ()

**.cellSetup**
>@discardableResult
    public func cellSetup(_ callback: @escaping ((_ cell: Cell, _ row: Self) -> Void)) -> Self {
        callbackCellSetup = { [unowned self] (cell: Cell) in  callback(cell, self) }
        return self
    }

Console
> Fatal error: Attempted to read an unowned reference but object 0x28092ad30 was already deallocated2020-03-08 09:56:02.519456-0700 Transit[1654:391269] Fatal error: Attempted to read an unowned reference but object 0x28092ad30 was already deallocated 

Trace: **#6**
>Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000180b22d88 in __pthread_kill ()
#1	0x0000000180a3f74c in pthread_kill$VARIANT$armv81 ()
#2	0x000000018098e934 in abort ()
#3	0x000000018e3be178 in swift::fatalError(unsigned int, char const*, ...) ()
#4	0x000000018e3be2c8 in swift::swift_abortRetainUnowned(void const*) ()
#5	0x000000018e3bfbd4 in swift_unownedRetainStrong ()
**_# 6	0x000000010622d51c in closure #1 in RowType<>.cellSetup(_:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/RowType.swift:227_**
#7	0x000000010622d5f8 in thunk for @escaping @callee_guaranteed (@guaranteed A.Cell) -> () ()
#8	0x0000000106225e64 in thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) ()
#9	0x0000000106225aec in Row._cell.didset at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:148
#10	0x0000000106225cdc in Row._cell.setter ()
#11	0x00000001062260fc in closure #1 in implicit closure #1 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:158
#12	0x0000000106225f48 in Row.cell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:154
#13	0x00000001062261c0 in Row.baseCell.getter at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Row.swift:164
#14	0x000000010618ebc0 in FormViewController.tableView(_:estimatedHeightForRowAt:) at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/Eureka/Source/Core/Core.swift:797
#15	0x000000010618ef64 in @objc FormViewController.tableView(_:estimatedHeightForRowAt:) ()
#16	0x0000000184fa5cf8 in -[UITableView _estimatedHeightForRowAtIndexPath:] ()
#17	0x0000000184fb4918 in __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke ()
#18	0x0000000184fb42f0 in -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] ()
#19	0x0000000184fb5c30 in -[UITableViewRowData _ensureSectionOffsetIsValidForSection:] ()
#20	0x0000000184fb92ec in -[UITableViewRowData rectForFooterInSection:heightCanBeGuessed:] ()
#21	0x0000000184fb94e0 in -[UITableViewRowData heightForTable] ()
#22	0x0000000184f5ed5c in -[UITableView _updateContentSizeSkippingContentOffsetAdjustment:] ()
#23	0x0000000184f87f78 in -[UITableView _rebuildGeometryForcingRowDataUpdate:skipContentOffsetAdjustment:updateImmediatelyIfPossible:] ()
#24	0x0000000184f85d60 in -[UITableView setLayoutMargins:] ()
#25	0x0000000184f85c48 in -[UITableView _setDefaultLayoutMargins:] ()
#26	0x0000000184f85bc0 in -[UITableView didMoveToWindow] ()
#27	0x000000018523c258 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#28	0x00000001851c130c in -[UIScrollView _didMoveFromWindow:toWindow:] ()
#29	0x000000018523bdd0 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#30	0x000000018523034c in __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke ()
#31	0x0000000185230238 in -[UIView(Hierarchy) _postMovedFromSuperview:] ()
#32	0x000000018523e974 in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
#33	0x00000001847c6428 in -[_UIParallaxDimmingView didMoveToWindow] ()
#34	0x000000018523c258 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#35	0x000000018523bdd0 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#36	0x000000018523034c in __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke ()
#37	0x0000000185230238 in -[UIView(Hierarchy) _postMovedFromSuperview:] ()
#38	0x000000018523e974 in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
#39	0x00000001847c1f7c in __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke_2 ()
#40	0x0000000185237d40 in +[UIView(Animation) performWithoutAnimation:] ()
#41	0x00000001847c1918 in __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke ()
#42	0x000000018523d2c8 in +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:forScene:] ()
#43	0x00000001847c138c in -[_UINavigationParallaxTransition animateTransition:] ()
#44	0x00000001847b6930 in ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 ()
#45	0x00000001848c5d90 in +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] ()
#46	0x00000001847b68b0 in ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 ()
#47	0x00000001852379fc in +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] ()
#48	0x00000001847b6718 in _UIViewControllerTransitioningRunCustomTransition ()
#49	0x00000001846eb360 in -[UINavigationController _startCustomTransition:] ()
#50	0x00000001846fea08 in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#51	0x00000001846ffda8 in -[UINavigationController __viewWillLayoutSubviews] ()
#52	0x00000001846e3308 in -[UILayoutContainerView layoutSubviews] ()
#53	0x0000000185245264 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#54	0x00000001877c6a04 in -[CALayer layoutSublayers] ()
#55	0x00000001877ccb5c in CA::Layer::layout_if_needed(CA::Transaction*) ()
#56	0x00000001877d76a0 in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#57	0x0000000187720798 in CA::Context::commit_transaction(CA::Transaction*, double) ()
#58	0x000000018774a128 in CA::Transaction::commit() ()
#59	0x0000000184da9908 in _UIApplicationFlushRunLoopCATransactionIfTooLate ()
#60	0x0000000184e44a60 in __handleEventQueueInternal ()
#61	0x0000000184e3d764 in __handleHIDEventFetcherDrain ()
#62	0x0000000180cac1d4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#63	0x0000000180cac12c in __CFRunLoopDoSource0 ()
#64	0x0000000180cab8b4 in __CFRunLoopDoSources0 ()
#65	0x0000000180ca68e4 in __CFRunLoopRun ()
#66	0x0000000180ca62a4 in CFRunLoopRunSpecific ()
#67	0x000000018ad8e38c in GSEventRunModal ()
#68	0x0000000184db0bf4 in UIApplicationMain ()
#69	0x00000001046e4838 in main at /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Transit/AppDelegate.swift:10
#70	0x0000000180b2d8f0 in start ()

**Comment by mats-claassen** [comment]
Did anyone check if this still happens in iOS 13.4 beta 6?

**Comment by johnlietzke** [comment]
Yes, it continues to happen in Beta 6

**Comment by alldritt** [comment]
The problem continues with 13.4 GM, Xcode 11.3 beta 3.

**Comment by dadixon** [comment]
This is still an issue
