### ISSUE TITLE
Automatically assign first responder when view is displayed

### ISSUE THREAD

**Issue by dwightwatson** [xmartlabs/Eureka#20]
Is it possible to automatically assign the first responder when the form is created/displayed? For example, the first enabled input should open the keyboard and be open to input from the user.

I'm coming across from [XLForm](https://github.com/xmartlabs/XLForm) (which I just found out was also created by you guys, great work!) which has the `assignFirstResponderOnShow` property.

**Comment by mtnbarreto** [comment]
@dwightwatson We will not add this functionality to Eureka.

However you can easily set the first responder by...

```swift
public func viewDidAppear(animated: Bool) {
         super.viewDidAppear(animated)
         let row: BaseRow! = form.rowByTag("yourRowTag") // you can also hold a strong reference to the row
         row.cell.cellBecomeFirstResponder()
}
```

**Comment by dwightwatson** [comment]
Awesome, thanks for that!

Out of curiousity, is there a reason that feature won't come to Eureka?

**Comment by mtnbarreto** [comment]
@dwightwatson 
Is not as used as we initially thought and at the same time is pretty easy to get it work. 
More features means more to maintain ;)

**Comment by alper** [comment]
I guess now it's become `row.cell.textField.becomeFirstResponder()`

**Comment by raudabaugh** [comment]
If you're using a cell that uses something other than a text field as its input, `cellBecomeFirstResponder()` is probably still the way to go. I couldn't get `becomeFirstResponder()` to work for a `DateTimeRow`.

**Comment by romanbarzyczakgelato** [comment]
How to call cellBecomeFirstResponder for DateTimeRow ? 

@raudabaugh any solution?
