### ISSUE TITLE
Any way to use header and footer view from storyboard not from nib's

### ISSUE THREAD

**Issue by shireeshMs** [xmartlabs/Eureka#2001]
I had successfully added footer & header view through nib'S but whenever I am trying to use my footer view through storyboards it crashes on IBOutlets I connected into class through storyboard and giving nil on every outlet of this class .Any Idea how to do it through storyboard iOS 13,xcode 11

**Comment by mats-claassen** [comment]
Make sure the classes of the views in storyboard are correctly set and outlets are connected to those classes and not File Owner (unless that is intended).

You must also correctly tell Eureka how to load that view from the storyboard when you set it as header. Otherwise just use nib files

**Comment by shireeshMs** [comment]
Tell me the little snippet by assuming one view controller from storyboard
I just want to know how to call through storyboard

**Comment by mats-claassen** [comment]
I haven't done it through storyboard so I have no snippet at hand. I normally use nib files. However using Storyboard should work as well.

This kind of help questions are more suited to StackOverflow
