### ISSUE TITLE
Reloading sections the correct way

### ISSUE THREAD

**Issue by forceunwrap** [xmartlabs/Eureka#2003]
Hey there.

We use Eureka in an app which uses MVVM, so the setup of the data source (section/ rows) is set up in the view models. The said data source is not static, e.g. sections might be replaced, once the value of a picker changes.
Once the data source is being updated, we used to use `Form.replaceSubrange` in the respective view controller to just replace all existing sections with the new ones, like: 

```
form.replaceSubrange(0..<self.form.allSections.count, with: sections)
```

This would be fine for us, even if it doesn't perform any diffing or something. I know that we would have to implement diffing our own.
The issue here is, `Form`s implementation of `replaceSubrange(_:with:)` doesn't remove any sections which are currently hidden ([see this line](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Form.swift#L218); because `sections` apparently doesn't include the hidden sections).

That means: once I call `replaceSubrange` while some of the sections are hidden, the hidden ones do not get removed. As a result, there will be more sections in the form, after enabling the switch which is responsible for hiding said sections.

So to the actual questions:
Is is intended to use `sections` in the linked line, which does ignore the hidden sections, or would use `_allSections` make more sense?
Is there a better (or at least another) way to replace all (including hidden) sections which I have overlooked?

Thanks for your time.

**Comment by mats-claassen** [comment]
Why not `form.removeAll()` and then add the new sections?

**Comment by forceunwrap** [comment]
Oh sorry that I didn't elaborate more on this approach.
I tried that one, but then the first section, which is always the same, does get visibly removed and re-added afterwards (as the code tells it), which looks weird.
Using `replaceSubrange(_:with)` looks way nicer, as this does not cause said section to be removed first — because it's only being replaced.

**Comment by mats-claassen** [comment]
OK, I see. I think the decision on what `replaceSubrange` should do with hidden rows is not so easy. Just thinking aloud. Would it make sense to delete the hidden sections in between the sections in the chosen range? I don't think we should take the range on `_allSections` because the range should be based on the indexes of the sections you see in the form. There might also be the case where you might want to delete certain sections but keep the hidden sections in between.

**Comment by forceunwrap** [comment]
Intuitively I expected `replaceSubrange` to replace all the sections, including the hidden ones.
I think `replaceSubrange` should replace all elements of a collection regardless of their properties and for me a hidden section is just a regular section with the property “hidden”.
Also using something like MVVM there should always be one data source which holds all form sections (including the hidden ones), so upon change it should just replace all the sections.

I don’t know if there are any scenarios where you want to keep the hidden ones “implicitly”. If you wanted to keep them, you could still control that via the range you pass to the function, as you should be aware of the indices of the sections which you want to keep.

**Comment by mats-claassen** [comment]
I agree that in the normal case if you want to remove section 2-5 then you also want to remove the sections in between that are hidden.

We can change `replaceSubrange` to replace the hidden sections in that range. However, hidden sections won't be counted in that range. This is consistent with the rest of the framework. The reasoning behind that is that hidden sections or rows are not really in the form (they are not shown). Also this makes the indexes returned in functions like `cellForRow:atIndexPath:` be consistent with those that we use.

This means if you want to replace all sections in a form, you could have to get the indexes you need from `form.sections`

**Comment by forceunwrap** [comment]
Hi @mats-claassen 
Sorry for not checking back for so long. Had some stuff going on.

I've checked `Form` code once more. There's currently no way to remove hidden sections, except for `removeAll()`, which is not what I want - because of the visual issue which I've mentioned. You _can_ access `form.allSections` but it is immutable.

If I do understand your most recent reply correctly, we should not alter the current behavior of `replaceSubrange`, as it is consistent with the rest of the framework - in that it handles hidden sections as not being part of the form.
Do you think it would make sense to override `RangeReplaceableCollection.remove(at:)` instead, in a way so that it removes sections from `_allSections`? Or do you have another idea what could be changed/ implemented in order to remove single _hidden_ sections?

**Comment by mats-claassen** [comment]
I think we could add a `replaceSubrangeOfAllSections` function that is like replaceSubrange but operates on `allSections`. This should cover any use case of removing, inserting and replacing hidden sections. What do you think?

**Comment by forceunwrap** [comment]
Yeah that might do it. It doesn't break existing code and it makes the distinction between the two `replaceSubrange` functions pretty obvious.

I'll provide a PR in the next couple of days. Thank you!
