### ISSUE TITLE
There is a build issue when using it with Carthage and Xcode 11.4

### ISSUE THREAD

**Issue by florinmatinca** [xmartlabs/Eureka#2010]
Hi guys,

I noticed that's an issue when trying to build Eureka with the latest version of Xcode, I suspect that's related to the new Swift 5.3 version.

`Building scheme "Eureka" in Eureka.xcworkspace Build Failed Task failed with exit code 65`

Environment: Eureka 5.2, Xcode 11.4

**Comment by mats-claassen** [comment]
Duplicate of #1988 #1987 #1999 

Will be fixed in 5.2.1 released soon!
