### ISSUE TITLE
Change row title on onChange

### ISSUE THREAD

**Issue by dadixon** [xmartlabs/Eureka#2013]
Eureka: Latest
Xcode: 11.4
iOS: 13.1

I'm using a StepperRow. When the user pressed the stepper, I want the title to change to reflect the change. This use to work but it crashes now and I get no error logs.

`<<< StepperRow("storeDays"){
                if UserDefaults.storeDays > 100 {
                    $0.title = "Keep Indefinitely"
                } else {
                    $0.title = "Keep notes for \(UserDefaults.storeDays) days"
                }
                $0.value = Double(UserDefaults.storeDays)
                $0.cell.stepper.stepValue = 1
                $0.displayValueFor = { value in
                    guard let value = value else { return nil }
                    return "\(Int(value))"
                }
                $0.cell.stepper.minimumValue = 40
                $0.cell.stepper.maximumValue = 101
            }.onChange({ (row) in
                let values = self.form.values()
                let newValue = Int(values["storeDays"] as! Double)
                UserDefaults.set(storeDays: newValue)
                print(UserDefaults.storeDays)
                row.title = "Keep notes for \(UserDefaults.storeDays) days"
                row.updateCell()
            })`

I've also noticed that inside the onChange method, the row.value is always nil

**Comment by dadixon** [comment]
Fixed using this:

`let r = self?.form.rowBy(tag: "storeDays")
                if UserDefaults.storeDays > 100 {
                    r?.title = "Keep Indefinitely"
                } else {
                    r?.title = "Keep notes for \(UserDefaults.storeDays) days"
                }
                r?.updateCell()`

**Comment by mats-claassen** [comment]
Please state the exact version of Eureka when creating issues, instead of "latest"

**Comment by dadixon** [comment]
It fixed after updating the pod
