### ISSUE TITLE
Xcode 11.4

### ISSUE THREAD

**Issue by JakeTorres** [xmartlabs/Eureka#2014]
Xcode 11.4, Eureka 5.0.0, all iOS version

place that build form broken

**Comment by vertuxx** [comment]
Accessing row.value will crush it.

```
form.setValues([
            KEY1: true
            ....
            ])
```

**Log output**
Fatal error: Attempted to read an unowned reference but object 0x2806dbe30 was already deallocated2020-03-27 19:07:15.087144+0900 ExtensionPower[5180:897794] Fatal error: Attempted to read an unowned reference but object 0x2806dbe30 was already deallocated

**Comment by vertuxx** [comment]
Accessing row.value will crush it.

```
form.setValues([
            KEY1: true
            ....
            ])
```

RowType.swift#onChange
```
/**
 Sets a block to be called when the value of this row changes.

 - returns: this row
 */
@discardableResult
public func onChange(_ callback: @escaping (Self) -> Void) -> Self {
    callbackOnChange = { [unowned self] in callback(self) } <--------- signal SIGABRT
    return self
}
```


**Log output**
Fatal error: Attempted to read an unowned reference but object 0x2806dbe30 was already deallocated2020-03-27 19:07:15.087144+0900 MyApp[5180:897794] Fatal error: Attempted to read an unowned reference but object 0x2806dbe30 was already deallocated

**Comment by hannesoid** [comment]
I get this when constructing a section
<img width="1400" alt="Bildschirmfoto 2020-03-27 um 12 16 04" src="https://user-images.githubusercontent.com/1856655/77750812-bff72480-7024-11ea-8e8e-2eaec7db78ad.png">

**Comment by mats-claassen** [comment]
Have you tried Eureka version 5.2.1? There is a workaround to avoid a crash due to a compiler bug. There are multiple issues addressing this #1987 #1988 #1999

**Comment by hannesoid** [comment]
cool, works for me after updating thanks!

**Comment by JakeTorres** [comment]
me too, updating or build with Xcode 11.4 later version
