### ISSUE TITLE
How to add margins to all cells and setup this design?

### ISSUE THREAD

**Issue by rudsberg** [xmartlabs/Eureka#2018]
I have tried everything. I have read googled and googled. I can't get it look like I want to. This is the desired design:

https://gyazo.com/cd39754323e393b9894b077128bb97b8

I can't get the margins on the left and right side working. And how would I add a styling to the entire section like in the picture (other background color)? Thanks for all help.

I have tried the example solutions here but non of them work.
https://github.com/xmartlabs/Eureka/issues/22

I use the latest iOS, Eureka and Xcode versions.

**Comment by mats-claassen** [comment]
Maybe someone from the community has done a design like that and could help.

I would make the tableView the size of the white background and use the tableView's background as white. Then you might need custom cells to add the cell border. Or play with the layout margins. But I haven't done it. Just suggestions

**Comment by mats-claassen** [comment]
Will close this as not an issue
