### ISSUE TITLE
ActiveButtonRow textColor

### ISSUE THREAD

**Issue by jeremiasdsa** [xmartlabs/Eureka#2019]
Hi

I would like to know how to change the text color of an ActiveButtonRow.

             `
               <<< ActiveButtonRow {
                $0.buttonTitle = "Custom Title"
                $0.cell.textLabel?.textColor = .red
                $0.cell.textLabel?.tintColor = .red
                $0.cell.button.titleLabel?.adjustsFontSizeToFitWidth = true
                $0.cell.tintColor = .red
                 ...
              `

I've being trying this with no success.

**Comment by mats-claassen** [comment]
Hi @jeremiasdsa, ActiveButtonRow is not one of Eureka core rows.

However, the issue is that you should not access `cell` in the row initializer. You should use `cellSetup` and `cellUpdate` to modify the cell. For `textLabel.textColor`, change it in `cellUpdate`

**Comment by jeremiasdsa** [comment]
I just figured out how to change it.

`$0.cell.button.setTitleColor(UIColor.red, for: .normal)`
