### ISSUE TITLE
updateCell() not called on iOS 12.4.5

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#2022]
Hi,

today I discovered that on my older iPhone 6 using iOS 12.4.5 updateCell() is not called for some reason. I have PushRows in my form and after choosing an option and going back to the form the value is not shown. After scrolling down and going back the value is visible(seems that updateCell() is not called maybe?)

Eureka: **5.2.1**
Xcode: **11.4**

**Comment by dneykov** [comment]
Calling `row.updateCell()` in `onChange` fixes the problem but that wasn't the case before.

**Comment by mats-claassen** [comment]
I just tested a PushRow in the Examples and it works on Simulator iPhone 11, iOS 13.4. Does it work for you on iOS 13? Or on another iPhone?

**Comment by dneykov** [comment]
Hi @mats-claassen,

yes it is working as expected on iOS 13. I can confirm that the problem appears in the examples as well on iOS 12. The problem is not only appearing on my iPhone but on iPad running iOS 12 as well.

As workaround I added on all my PushRows and MultipleSelectorRows `.onChange` callback.
I tried to fix it in my Pods so I can suggests a solution but did not manage

**Comment by mats-claassen** [comment]
I am wondering if it has to do with this commit https://github.com/xmartlabs/Eureka/commit/2046ebf6a32e8d665942de5eb8a87b9056b462fa.

Could you test if using Eureka 5.1.0 in iOS 12 works? Or reverting the change in `Core.swift` of that commit to see if that fixes it for iOS 12. That would bring is closer to a fix/workaround

**Comment by dneykov** [comment]
@mats-claassen reverting the change in `Core.swift` fix the problem. PushRows work as expected on iOS 12.

**Comment by mats-claassen** [comment]
@dneykov I fixed it in #2029. As per your previous comment it should work for you

**Comment by dneykov** [comment]
@mats-claassen as soon it's publish I will update, test and close this issue.
