### ISSUE TITLE
Example app crashes for all "Multiple Selection" / "Push Selection" row types.

### ISSUE THREAD

**Issue by intere** [xmartlabs/Eureka#2025]
### Relevant Context
- Xcode 11.4 (11E146)
- Eureka 5.2.0 `567d4e1 (HEAD, tag: 5.2.0) Remove bundle from podspec (#1981)`
    - This issue applies to everything 5.0.0 and up as well, probably predates the 5.0.0 baseline as well
- I can 100% reproduce this crash every time
    - I've found the culprit to be `[unowned self] in callback(self.cell, self)` and I'm going to submit a PR for this issue.

In trying to add a PushRow to my own app, I found a crash, so I decided to check out the example app.  I found that the example app is also crashing, so I dove a bit deeper.  I believe I know how to fix this and I'll work on submitting a PR.

### Example demonstration
![EurekaCrash](https://user-images.githubusercontent.com/2284832/80279994-54a18080-86be-11ea-95fc-fdf55bee111f.gif)

### Rows that reproduce this crash:
- `PushRow`
- `SectionedPushRow`
- `LazySectionedPushRow`
- `Custom Cell Push Row`
- `MultipleSelectorRow`
- `SectionedMultipleSelectorRow`
- `LazySectionedMultipleSelectorRow`

**Comment by intere** [comment]
This issue is fixed by [This PR](https://github.com/xmartlabs/Eureka/pull/2026)

**Comment by mats-claassen** [comment]
Have you tried Eureka 5.2.1?

**Comment by intere** [comment]
I had the same issue on the master branch.  No, I did not try 5.2.1.

**Comment by intere** [comment]
I didn't realize that 5.2.1 even existed.  Whoops.  🤦‍♂️

**Comment by intere** [comment]
I'll close my PR, too.
