### ISSUE TITLE
Unable to set detailTextLabel with ButtonRow

### ISSUE THREAD

**Issue by zunjae** [xmartlabs/Eureka#2027]
- Environment: Eureka: 5.2.1, Xcode: 11.4.1 and iOS: 13.4.1 (iPhone 11 pro max)

Issue: I am unable to set a detailTextLabel after it has been created. The detailTextLabel shows "Cool subtitle!" instead even after trying to change it to "bepis"

      <<< ButtonRow(FormTag.Date) {
        $0.title = R.string.localizable.date()
        $0.cellStyle = .subtitle
        $0.cellUpdate { cell, _ in
          cell.detailTextLabel?.textColor = R.color.primaryBackgroundColor()
          cell.detailTextLabel?.text = "Cool subtitle!"
        }

This works fine!

    let dateRow = form.rowBy(tag: FormTag.Date) as! ButtonRow
    dateRow.cell.detailTextLabel!.text = "bepis"
    dateRow.reload() // optional

This doesn't. I'm not seeing anything in my Xcode logs. What am I doing wrong here or is it a library error?

**Comment by zunjae** [comment]
Nevermind I found it

**Comment by fukemy** [comment]
how did u solved this?
