### ISSUE TITLE
SwitchRow to listen to taps and value changes differently

### ISSUE THREAD

**Issue by rommex73** [xmartlabs/Eureka#2028]
Hi there, thanks for your work!

I have an issue with a SwitchRow:

1. My data with the initial value for SwitchRow comes asynchronously, much later than the initialization of the FormViewController, so I initialize the SwitchRow with a default value.

2. I need SwitchRow react only to the tap that changes its value (with an alert window) -- I do it in the .onChange callback.

But currently it shows the alert window also when I set the initial value (when the data comes in), and there was no tap on the switch.

What is the correct way to set the desired behavior, I couldn't find it in the docs, sorry 
Thanks

When submitting issues, please provide the following information to help maintainers to fix the problem faster:
- Environment: Eureka 5.2.1.    Xcode 11.3.1.      iOS 11.

**Comment by mats-claassen** [comment]
You want to show the alert when the user selects the row? In that case you can use `onCellSelection` instead of `onChange`.
