### ISSUE TITLE
ButtonRow on selecting crashes

### ISSUE THREAD

**Issue by Massmaker** [xmartlabs/Eureka#203]
in " didSelect " method of ButtonRow there is no indexPath in implicit upwrapping -  row.indexPath()!

currently fixing it in ".onCellSelection" closure.   ->    " cell.setSelected(false, animated:false)"

**Comment by mtnbarreto** [comment]
@marbetschar Could you please provide your eureka form code so i can reproduce the issue? Also provide Eureka and Xcode version.

**Comment by Massmaker** [comment]
xCode Version 7.2 (7C68)
code : 
    private func setupFinishCancelButtons(section:Section)
    {
        let finishTaskButton = ButtonRow("Finish Task").cellSetup{(cell, row) in
                    cell.textLabel?.font = UIFont.boldSystemFontOfSize(17)
                    cell.tintColor = UIColor.blueColor()
                    row.title = "Finish"
                }.onCellSelection {[weak self] (cell, row) -> () in
                    cell.setSelected(false, animated: false)
                    self?.finishTaskPressed()
                }
        
        let cancelTaskButton = ButtonRow("Cancel Task").cellSetup(){ (cell, row) -> () in
                    cell.tintColor = UIColor.purpleColor()
                    row.title = "Cancel"
                }.onCellSelection(){[weak self] (cell, row) -> () in
                    cell.setSelected(false, animated: false)
                    self?.cancelTaskPressed()
                }
    
        section.removeAll()// in case there is Take button (Take button action)
        section[0] = finishTaskButton
        section[1] = cancelTaskButton
    }
    
    func setupDeleteSection()
    {
        let deleteButtonRow = ButtonRow().cellSetup(){ (cell, row) -> () in
                cell.tintColor = UIColor.redColor()
                row.title = "Delete"
                }.onCellSelection {[weak self] (cell , _) -> () in
                   
                    cell.setSelected(false, animated: false)
                    self?.deleteTaskPressed()
                }

        
        form[3] = Section("Danger Zone") <<<  deleteButtonRow
    }

**Comment by mtnbarreto** [comment]
@Massmaker I couldn't make it crash using the code provided by you.  I'm using master branch version. Could you please check that is still crashing using master branch?

This is my form view controller code....

```swift
class HomeViewController : FormViewController {
    
    
    func setupDeleteSection() {
        let deleteButtonRow = ButtonRow().cellSetup(){ (cell, row) -> () in
            cell.tintColor = UIColor.redColor()
            row.title = "Delete"
            }
        form[2] = Section("Danger Zone") <<<  deleteButtonRow
    }
    
    
    private func setupFinishCancelButtons(section:Section) {
        let finishTaskButton = ButtonRow("Finish Task").cellSetup{(cell, row) in
            cell.textLabel?.font = UIFont.boldSystemFontOfSize(17)
            cell.tintColor = UIColor.blueColor()
            row.title = "Finish"
            }.onCellSelection {(cell, row) -> () in
                //cell.setSelected(false, animated: false) //this is fix
                //self?.finishTaskPressed()
        }
        let cancelTaskButton = ButtonRow("Cancel Task").cellSetup(){ (cell, row) -> () in
            cell.tintColor = UIColor.purpleColor()
            row.title = "Cancel"
            }.onCellSelection(){ (cell, row) -> () in
                //cell.setSelected(false, animated: false) //this is fix
                //self?.cancelTaskPressed()
        }
        section.removeAll()// in case there is Take button (Take button action)
        section[0] = finishTaskButton
        section[1] = cancelTaskButton
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ImageRow.defaultCellUpdate = { cell, row in
           cell.accessoryView?.layer.cornerRadius = 17
           cell.accessoryView?.frame = CGRectMake(0, 0, 34, 34)
        }
        
        form  +++=
            
            Section(footer: "These are 10 ButtonRow rows") {
                $0.header = HeaderFooterView<EurekaLogoView>(HeaderFooterProvider.Class)
            }  
                <<< ButtonRow("Inline rows") { (row: ButtonRow) -> Void in
                    row.title = row.tag
                    row.presentationMode = .SegueName(segueName: "InlineRowsControllerSegue", completionCallback: nil)
                }
                <<< ButtonRow("List Sections") { (row: ButtonRow) -> Void in
                    row.title = row.tag
                    row.presentationMode = .SegueName(segueName: "ListSectionsControllerSegue", completionCallback: nil)
                }
        
        
        let sec = Section()
        setupFinishCancelButtons(sec)
        form +++ sec
        
        setupDeleteSection()
    }
}
```
