### ISSUE TITLE
Changing Decimal Row Automatic Decimal Insertion

### ISSUE THREAD

**Issue by paulyg13** [xmartlabs/Eureka#2031]
I cannot get the decimal row to stop automatically adding the decimal after the first number I type.
`            <<< DecimalRow(k.weight){
                $0.title = "Weight (Kg x 1000)"
                $0.placeholder = "eg. 65"
               $0.add(rule: RuleRequired(msg: "Weight is required"))
                $0.validationOptions = .validatesOnDemand
`

I would like the weight to be in the format of ##.# (ie. 65.0) or so. I have used the formatter to leave only 1 decimal place, but when the user starts typing it automatically inserts the decimal after the first number and a 0. So for example if the user wants to input "65.0", when they type 6, "6.0" appears. If they type 5, it becomes 6.05.

I have tried `                $0.useFormatterDuringInput = false
                $0.useFormatterOnDidBeginEditing = false`, but neither of these work.

Thanks

**Comment by mats-claassen** [comment]
Have you tried something like this: ?

```swift
let f = DecimalFormatter()
$0.formatter = f
f.minimumFractionDigits = 0
f.maximumFractionDigits = 1
$0.useFormatterDuringInput = false
```
