### ISSUE TITLE
Making ValidationRuleHelper rule property public

### ISSUE THREAD

**Issue by YuriSolodkin** [xmartlabs/Eureka#2032]
Would it be possible to make rule property of ValidationRuleHelper public?

     public struct ValidationRuleHelper<T> where T: Equatable {
          let validateFn: ((T?) -> ValidationError?)
          let rule: BaseRuleType
    }

This will allow to get information about existing rules and write code like this:

      var mandatory: Bool {
          return rules.contains { ruleHelper -> Bool in
              ruleHelper.rule.id == "RuleRequired"
          }
      }

**Comment by mats-claassen** [comment]
Yes I think that should be possible
