### ISSUE TITLE
SliderRow not rendering properly

### ISSUE THREAD

**Issue by shakked** [xmartlabs/Eureka#2034]
This is what my slider row looks like. I cannot drag it, I checked the debug frames and also attached that screenshot. Basically, the entire slider is very tiny, not constraining to the full width of the cell.

![Simulator Screen Shot - iPhone 11 - 2020-04-30 at 19 37 15](https://user-images.githubusercontent.com/5383089/80769091-24bd0780-8b1a-11ea-98c1-f9824262007f.png)

![Simulator Screen Shot - iPhone 11 - 2020-04-30 at 19 40 14](https://user-images.githubusercontent.com/5383089/80769186-6c439380-8b1a-11ea-87c8-ecd762d9aa74.png)

Xcode 11.4.1
iOS 13.4.1

This is my code in `viewDidLoad` of `FormViewController` subclass:

 
        let introSection = Section(footer: "Here, you can customize how your hashtags are generated.")
        form.append(introSection)
        
        let hashtagsPerGenerationSection = Section(header: "Hashtags Per Generation", footer: "You can generate up to 30 hashtags each time you use the hashtag generator")
        let hashtagsPerGenerationSliderRow = SliderRow(RowTag.hashtagsPerGeneration) { (sliderRow) in
            sliderRow.cell.slider.minimumValue = 1.0
            sliderRow.cell.slider.maximumValue = 30.0
            sliderRow.steps = 10
            sliderRow.title = "Hashtags"
        }
        hashtagsPerGenerationSection.append(hashtagsPerGenerationSliderRow)
        form.append(hashtagsPerGenerationSection)

**Comment by mats-claassen** [comment]
Hi, sorry for the late reply.

Are you using the latest version of Eureka (5.2.1)?
Are you seeing constraints breaking in the console?

**Comment by StateMachineJunkie** [comment]
Same exact issue using Eureka v5.3.3.
`(lldb) po row.cell.frame
▿ (0.0, 263.0, 540.0, 43.5)
  ▿ origin : (0.0, 263.0)
    - x : 0.0
    - y : 263.0
  ▿ size : (540.0, 43.5)
    - width : 540.0
    - height : 43.5

(lldb) po row.cell.slider.frame
▿ (126.0, 7.0, 4.0, 31.0)
  ▿ origin : (126.0, 7.0)
    - x : 126.0
    - y : 7.0
  ▿ size : (4.0, 31.0)
    - width : 4.0 <--- That's not right.
    - height : 31.0
`

**Comment by r3econ** [comment]
I'm experiencing exactly the same bug. I'm using v5.3.3

**Comment by StateMachineJunkie** [comment]
It has been a while but I seem to recall that all of my sliders were exhibiting this kind of behavior because the input or output type was cast as an `Int` instead of a `Double` or vice-versa. This happened while converting a lot of previously written (by someone else) forms from XLForm to Eureka. Sorry if that is not very helpful.

**Comment by mats-claassen** [comment]
Hi, @cecipirotto has fixed this in #2166. From our testing it is working now. An alternative workaround would be to set an initial value to the SliderRow
