### ISSUE TITLE
How to customise UITableView style ?

### ISSUE THREAD

**Issue by thlbaut** [xmartlabs/Eureka#2036]
Hi !
Is it possible to customise the `UITableView` style with `.insetGrouped` ?
Thanks :)

**Comment by mats-claassen** [comment]
Yes. If you are using storyboards then you can specify the style there. Otherwise you can create the FormViewController using this init:
```swift
public init(style: UITableView.Style)
```

**Comment by thlbaut** [comment]
Thanks :)

**Comment by brhoomjs** [comment]
> Yes. If you are using storyboards then you can specify the style there. Otherwise you can create the FormViewController using this init:
> 
> ```swift
> public init(style: UITableView.Style)
> ```

Where should we add that? in FormViewController?

**Comment by NiuXiaoGuang** [comment]
我是以继承FormViewController的方式来构建项目的，这样如何设置UITableView的Style

**Comment by bcho** [comment]
If you are inheriting the FormViewController, you can try set the tableViewStyle before setupView:

```swift
override func viewDidLoad() {
  tableViewStyle = .insetGrouped

  super.viewDidLoad()
}
```
