### ISSUE TITLE
CountDownRow update delayed in iOS 13.4.1

### ISSUE THREAD

**Issue by bst27** [xmartlabs/Eureka#2037]
As the maintainer of a time tracking app [(Wokiho)](https://www.wokiho.net/) for iOS I experience an issue with the Eureka **CountDownRow** in iOS 13.4.1.

**Environment:**
Eureka (5.2.1) + Xcode 11.4.1 + iOS 13.4.1

**Problem:**
When changing the value of a CountDownRow it is not updated immediately. The update occurs when the value of the row is changed a second time. I have this issue with my iPhone 11 Pro and can reproduce it when running in an xcode simulator. The issue does not exist in iOS 13.3. 

Please note the duration row in the following example where iOS 13.3 (left) works as expected but iOS 13.4.1 (right) does not.

![eureka-ios-13 4 1-bug](https://user-images.githubusercontent.com/6805736/81214533-43b71000-8fd8-11ea-98a7-33c624b3a04d.gif)

**Comment by mats-claassen** [comment]
This issue looks very similar to #571 which happened 4 years ago. In that case, as pointed out in this [StackOverflow post](https://stackoverflow.com/questions/20181980/uidatepicker-bug-uicontroleventvaluechanged-after-hitting-minimum-internal) it was an iOS bug. As it seems to happen on one iOS version and not another with the same version of Eureka, it could be that the same issue resurfaced. Otherwise, there was no code change to CountDownRow recently

**Comment by bst27** [comment]
Thanks @mats-claassen . I can confirm that the adding the following code to be executed during `viewDidLoad()` is a workaround to avoid the bug:

```swift
DispatchQueue.main.async {
	row.cell.datePicker.countDownDuration = TimeInterval()
}
```

Complete example:
```swift
<<< CountDownRow(durationRowTag) { row in
	var dateComponents = DateComponents()
	dateComponents.hour = 0
	dateComponents.minute = 1
	dateComponents.timeZone = TimeZone.current
	
	row.title = "Duration"
	row.value = Calendar.current.date(from: dateComponents)
	
	DispatchQueue.main.async {
		row.cell.datePicker.countDownDuration = TimeInterval()
	}
}
```

**Comment by nazgu1** [comment]
Looks like workaround mentioned above does not work anymore.

What works for me is something like:

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        if let row = form.rowBy(tag: "…") as? CountDownRow {
            let countDownDuration = row.cell.datePicker.countDownDuration
            row.cell.datePicker.countDownDuration = countDownDuration
        }
    }
```
