### ISSUE TITLE
Inline PickerCell can be removed before UIPickerViewDelegate method gets called

### ISSUE THREAD

**Issue by Joony** [xmartlabs/Eureka#204]
In the `PickerCell`, `pickerView:didSelectRow:inComponent:` and `pickerView:titleForRow:forComponent:` can get called after the row has been removed.  The delegate method further calls the `PickerCell` computed property `pickerRow` and fails with a fatal error when trying to access `self.row`.

Create a form with an inline picker (with many options) followed by a text row.  Open the picker row, fling the picker view, and immediately select the text row.  The picker view will be removed before the delegate methods are called.

**Comment by mtnbarreto** [comment]
@Joony  Thanks for reporting the issue. It was already fixed! 
Same as #208
