### ISSUE TITLE
TimeRow format "mm:ss"

### ISSUE THREAD

**Issue by ricardofrias** [xmartlabs/Eureka#2040]
Hi,

Is it possible to change the TimeRow format to "minutes: seconds"?

Best,
Ricardo

**Comment by mats-claassen** [comment]
Hi, that is how you want to show the results? 
In that case you just need to modify the `dateFormatter` of the TimeRow. For example change its `timeStyle` or use a custom format.

**Comment by ricardofrias** [comment]
Hi, 

I tried this, but it only displays the minutes, the seconds, no.

```
<<< TimeRow() {
            $0.title = "Horário"
            $0.noValueDisplayText = "Selecione o horário"
            
            let formatter = DateFormatter()
            formatter.dateFormat = "mm:ss"
            formatter.locale = Locale(identifier: "pt")

            $0.dateFormatter = formatter
            $0.value = formatter.date(from: self.hora.text!)
        } .onChange({ (row) in
            let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "mm:ss"
            self.hora.text = dateFormatter.string(from: row.value!)
        })
```

**Comment by mats-claassen** [comment]
Actually this worked for me:

```swift
    <<< TimeRow() {
        $0.title = "The time is:"
        $0.dateFormatter?.dateFormat = "mm : ss"
    }
```

**Comment by ricardofrias** [comment]
The picker is in the "HH:mm" format, in the form field "mm:ss"

![screen](https://user-images.githubusercontent.com/2522657/82388892-11160a00-9a11-11ea-9168-e7a98beb6fba.jpg)

**Comment by mats-claassen** [comment]
Oh, I see. You want to change the picker? I actually think that is a UIDataPicker limitation. Check [this thread](https://stackoverflow.com/q/29611464/4708657).

You could try using `DoublePickerRow` for example

**Comment by ricardofrias** [comment]
@mats-claassen I used DoublePickerRow and it looks like it worked. 

How do I get the return of the selected pickers?

Thanks!

**Comment by mats-claassen** [comment]
Use the `value` of the row

**Comment by ricardofrias** [comment]
It worked!

The only missing thing is to fill in the time value in DoublePickerInlineRow when the form is loaded. In the TextRow that i included just below, as a test, it was filled out correctly.

![Simulator Screen Shot - iPhone 11 - 2020-05-21 at 22 07 51](https://user-images.githubusercontent.com/2522657/82621068-6c323300-9bb0-11ea-9ff3-feed230817a4.jpg)

**Comment by ricardofrias** [comment]
Done!

$0.value = Tuple(a: min,b: seg)

Thanks!
