### ISSUE TITLE
LocationRow

### ISSUE THREAD

**Issue by ylecuyer** [xmartlabs/Eureka#205]
The LocationRow in the example doesn't seem to work and it's tied to the ios map api.

There is a tiny example of a LocationRow using the GoogleMap API: https://gist.github.com/ylecuyer/78ee6d23601b58f06a06

**Comment by mtnbarreto** [comment]
@ylecuyer Why it doesn't seems to work?

**Comment by mtnbarreto** [comment]
@ylecuyer 
I wanted to let you know that Location row isn't distributed within the main library framework since it requires maps framework to work.
You will need to copy the LocationRow and related files to your project. 

Is this the issue you are experiencing?
