### ISSUE TITLE
Row in SelectableSection is disabled when navigating back to the form

### ISSUE THREAD

**Issue by xavierb1** [xmartlabs/Eureka#2053]
Eureka version 5.2.1
Xcode 11.4
iOS 13.5.1

I have two check box rows in a `.singleSelection(enableDeselection: false)` `SelectableSection` that unintentionally become disabled when navigating away from the screen and then returning to it. I say that because Im not sure what causes the switch. I have tried explicitly setting `$0.disabled = false` when creating the row then again in a `viewWillAppear` function followed by a call to `evaluateDisabled()` but no luck. I found that the prepare function in the `SelectableSection` class as the blocker for the desired behavior. Any thoughts on why the rows are disabled when returning to the form?

```

func prepare(selectableRows rows: [BaseRow]) {
         for row in rows {
            if let row = row as? SelectableRow {
                row.onCellSelection { [weak self] cell, row in
                    guard let s = self, !row.isDisabled else { return } // !row.isDisabled is the blocker
                    switch s.selectionType {
                    case .multipleSelection:
                        row.value = row.value == nil ? row.selectableValue : nil
                    case let .singleSelection(enableDeselection):
                        s.forEach {
                            guard $0.baseValue != nil && $0 != row && $0 is SelectableRow else { return }
                            $0.baseValue = nil
                            $0.updateCell()
                        }
                        // Check if row is not already selected
                        if row.value == nil {
                            row.value = row.selectableValue
                        } else if enableDeselection {
                            row.value = nil
                        }
                    }
                    row.updateCell()
                    s.onSelectSelectableRow?(cell, row)
                }
            }
        }
    }

```

**Comment by mats-claassen** [comment]
Eureka's code does not set the section to disabled. Maybe you should make sure that you are not doing it somewhere else. And make sure that `isDisabled` is actually the reason why the guard statement is false.

**Comment by xavierb1** [comment]
It is not the section but the row itself. To give a little more context, I have a `CheckBoxRow` which is a subclass of `Row` and every time it's interacted with, the row simply updates it's UI between an on and off state. I'm not explicitly setting disabled to true anywhere because there's no case where I would want a checkbox row to be disabled. In an attempt to ensure it isn't, I set `row.disabled = false` in `update()` as well as the places mentioned before. 

Example:
![disabled_row](https://user-images.githubusercontent.com/16827737/85756826-269be500-b6dd-11ea-953c-8d816d03fdec.gif)

Print statements in Eureka code

<img width="835" alt="Screen Shot 2020-06-25 at 12 22 04 PM" src="https://user-images.githubusercontent.com/16827737/85758605-7dee8500-b6de-11ea-8a51-a440c7f55d0d.png">

<img width="705" alt="Screen Shot 2020-06-25 at 12 19 43 PM" src="https://user-images.githubusercontent.com/16827737/85758263-28b27380-b6de-11ea-8143-64d5599312de.png">


When successfully checking a row:
<img width="385" alt="Screen Shot 2020-06-25 at 11 00 57 AM" src="https://user-images.githubusercontent.com/16827737/85745253-8ee5c900-b6d3-11ea-8e54-93b434b62986.png">

Navigating back to the screen and trying to check a row:
<img width="392" alt="Screen Shot 2020-06-25 at 11 04 36 AM" src="https://user-images.githubusercontent.com/16827737/85745457-b63c9600-b6d3-11ea-9c7d-6d306c1da1a0.png">

**Comment by mats-claassen** [comment]
It is weird. I cannot reproduce it. `isDisabled` is an interface to `disabledCache` which is only reset in evaluateDisabled so I don't understand how you can have disabled rows there unless some part of your code does it.

I can't investigate this without a sample project as I cannot reproduce it with a simple push and back.

**Comment by xavierb1** [comment]
Found the bug. Overlooked a line of code on my end. Closing the issue
