### ISSUE TITLE
TextRow textLabel layout problem when the cellStyle is set to subtitle

### ISSUE THREAD

**Issue by brunofrani** [xmartlabs/Eureka#2058]
If the cellStyle of the TextRow is changed to .subtitle and the text label is made multiline the title gets out of the cell frame.
The two changes that I made are: 

$0.cellStyle = .subtitle
$0.cell.textLabel?.numberOfLines = 0

This is a simple project that shows the problem:
 https://github.com/brunofrani/MultilineTextRow

**Comment by mats-claassen** [comment]
I have created a PR with a fix #2069. If you have a chance o try it out let me know what you think.

**Comment by alemar11** [comment]
@mats-claassen works great for me! thanks

**Comment by brunofrani** [comment]
@mats-claassen  it works great, thanks a lot!
