### ISSUE TITLE
Change  image in HeaderFooterView with a <<< ImageRow() .

### ISSUE THREAD

**Issue by dromerobarria** [xmartlabs/Eureka#206]
Any chance to be able to change the image on the HeaderFooterView with a  <<< ImageRow() , just to look like profile view .

Finally it is possible to make the image on the HeaderFooterView  circular , i was trying to do it but nothing happened.

Thanks by the way for this great framework.

**Comment by mtnbarreto** [comment]
I'm not sure if i understood your question.

Rows cannot be used as form section header or footer, at least using `row` eureka abstraction as header view.

As the documentation explains you should provide a header/footer view either by providing a view class or a nib file. https://github.com/xmartlabs/Eureka#section-header-and-footer

Let me know if you were asking something different.
