### ISSUE TITLE
How we can implement the textfield shouldChangeCharactersIn delegate method for TextRow of eureka library ?

### ISSUE THREAD

**Issue by PatilRupaliAress** [xmartlabs/Eureka#2060]
- Environment: Eureka : 1.5.1, Xcode : 11.3 and iOS : 13.3

I don't want to remove the first character from textfield, So for this I have to use the shouldChangeCharactersIn delegate method.

**Comment by mats-claassen** [comment]
Hey @PatilRupaliAress, have a look at [this code](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Common/FieldRow.swift#L454-L456).

You can achieve it by overriding in your FormViewController subclass:

 `open func textInput<T>(_ textInput: UITextInput, shouldChangeCharactersInRange range: NSRange, replacementString string: String, cell: Cell<T>) -> Bool`

**Comment by PatilRupaliAress** [comment]
Works, thank you.
