### ISSUE TITLE
Remove first and last separator

### ISSUE THREAD

**Issue by jobomix** [xmartlabs/Eureka#2065]
I know this question has already been asked but I haven't found a proper way to customise the separator on a per row basis. In this case, I need to remove the top separator on the first row and the bottom separator on the last row but keep all the separators in between

![Screenshot 2020-08-07 at 11 11 00](https://user-images.githubusercontent.com/1127732/89635371-ce8cfc80-d89e-11ea-8cda-d9e2a3d0e528.png)

**Comment by mats-claassen** [comment]
One option is always to create a custom cell for this row and add your own separator line which you can toggle on and off. Might be a bit more involved than using UITableView's separator
