### ISSUE TITLE
Xcode 12 + Carthage

### ISSUE THREAD

**Issue by terryworona** [xmartlabs/Eureka#2066]
Setup:
- Xcode 12.0 beta (12A6159)
- Cartfile: `github "xmartlabs/Eureka" "xcode12"`

Error when I attempt to `import Eureka`:
```
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler:
```

Thoughts? Suggestions?

**Comment by Oni-zerone** [comment]
Hi, we have the same problem with the latest Xcode 12 (beta 5).
Carthage fails: 
`Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Intermediates.noindex/ArchiveIntermediates/Eureka/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Eureka.framework/Eureka /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Products/Release-iphonesimulator/Eureka.framework/Eureka -output /Users/davideceresola/Documents/Git/app_consumer_ios/Carthage/Build/iOS/Eureka.framework/Eureka
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f3/x_pcfm7s76786wl0k0h1sy3w0000gn/T/carthage-xcodebuild.NMDfI8.log`

But from the logs, it results that the build have finished successfully:
`GenerateDSYMFile /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Products/Release-iphonesimulator/Eureka.framework.dSYM /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Products/Release-iphonesimulator/Eureka.framework/Eureka (in target 'Eureka' from project 'Eureka')
    cd /Users/davideceresola/Documents/Git/app_consumer_ios/Carthage/Checkouts/Eureka
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Products/Release-iphonesimulator/Eureka.framework/Eureka -o /Users/davideceresola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Eureka/f5651e328e099393e51b63f1abe78153cbacf90f/Build/Products/Release-iphonesimulator/Eureka.framework.dSYM

** BUILD SUCCEEDED **`

**Comment by Oni-zerone** [comment]
This looks like a problem on carthage: 
https://github.com/Carthage/Carthage/issues/3019

**Comment by mats-claassen** [comment]
As @Oni-zerone mentioned this looks like a Carthage issue with Xcode 12. There seems to be a workaround in the thread linked above
