### ISSUE TITLE
TextAreaRow with imageView icon does not format correctly

### ISSUE THREAD

**Issue by michaelbina** [xmartlabs/Eureka#207]
I had this problem before with SegmentedRow and it was fixed, but it happens now with TextAreaRow.

When you set an imageView icon, the TextArea does not format correctly to account for the width of the image.  See screenshot to see what I mean.

<img width="373" alt="screen shot 2016-01-25 at 2 26 23 am" src="https://cloud.githubusercontent.com/assets/528845/12548435/17a67bfc-c30b-11e5-911d-a1a601bfcc08.png">
<img width="371" alt="screen shot 2016-01-25 at 2 27 16 am" src="https://cloud.githubusercontent.com/assets/528845/12548449/2d01493c-c30b-11e5-953c-94029068cd5f.png">

**Comment by mtnbarreto** [comment]
@michaelbina thanks for reporting it!
