### ISSUE TITLE
Dynamic change textField width in DecimalRow

### ISSUE THREAD

**Issue by tihomirbg** [xmartlabs/Eureka#2070]
Hello, I need help about DecimalRow.

My swift project is without Storyboards so I call FormViewController manually.
I try simple implementation. But DecimalRow has different behavior than example.
In my simple textField is with static width.
![118149017_614548632789658_6126989623859071239_n](https://user-images.githubusercontent.com/7965488/91457010-9456bf80-e88c-11ea-93ef-f201fd31c734.jpg)

but in Eureka Example project this textField is dynamic depends of text input.

![118481530_1728570410652766_4055077931777112953_n](https://user-images.githubusercontent.com/7965488/91457167-bcdeb980-e88c-11ea-9a1b-32958148ec74.jpg)

Any ideas how to make this dynamic?
Thank you

**Comment by tihomirbg** [comment]
This is my init View Controller code

```
import UIKit
//import Eureka
import SnapKit

class ViewController: UIViewController {
    private lazy var containerView: UIView = {
        let view = UIView()
        view.backgroundColor = .green
        return view
    }()

    private let childVC = TestViewController()

    override func viewDidLoad() {
        super.viewDidLoad()

        view.addSubview(containerView)

        self.addChild(childVC)
        containerView.addSubview(childVC.view)
        childVC.didMove(toParent: self)

        containerView.snp.makeConstraints { make in
            make.edges.equalTo(view)
        }

        childVC.view.snp.makeConstraints { make in
            make.edges.equalTo(containerView)
        }
    }
}
```

This is my test FormViewController code
```
import UIKit
import Eureka

class TestViewController : FormViewController {
    override func viewDidLoad() {
        super.viewDidLoad()

        self.tableView.delegate = self
        self.tableView.dataSource = self

        form +++ Section("Number formatters")
            <<< DecimalRow(){
                $0.useFormatterDuringInput = true
                $0.title = "Currency style"
                $0.value = 2015
                let formatter = CurrencyFormatter()
                formatter.locale = .current
                formatter.numberStyle = .currency
                $0.formatter = formatter
                $0.onCellHighlightChanged { cell, row in
                    cell.titleLabel?.backgroundColor = UIColor.green
                    cell.textField.backgroundColor = UIColor.red
                }

            }
......
```
Maybe  @IBOutlet public var tableView: UITableView! is the problem. But how to connect tableView without Interfaice Builder and Storyboard?

**Comment by mats-claassen** [comment]
Hi @tihomirbg I suppose you are using the Eureka examples from master while using the latest released version of Eureka with your `TestViewController`. There is a change on top of the latest release which adds the change you point out above. Try using the master branch version until we make a new release

**Comment by tihomirbg** [comment]
Yes, I confirm that everything is working as expected with master branch.

Waiting for release :)

Thank you very much.
