### ISSUE TITLE
Latest Release (5.3.0) doesn't build on Xcode 11.3.1

### ISSUE THREAD

**Issue by garethlloyd94** [xmartlabs/Eureka#2075]
The latest release does not build on xCode 11.3.1 as it uses `preferredDatePickerStyle`which is only 13.4 and above.

<img width="1016" alt="Screenshot 2020-09-16 at 15 28 31" src="https://user-images.githubusercontent.com/8321013/93354442-e7d97f00-f834-11ea-9e1c-a4d1a61c3d72.png">
<img width="323" alt="Screenshot 2020-09-16 at 15 19 04" src="https://user-images.githubusercontent.com/8321013/93354447-e9a34280-f834-11ea-87d5-64efa3161933.png">

**Comment by mats-claassen** [comment]
Thanks for reporting. The latest release requires Xcode 11.4 or Xcode 12. So currently if you use an older version you should stick to Eureka 5.2.1

**Comment by haohan88** [comment]
Hi, compile error occurs in Xcode 12. => Segmentation fault: 11. Command CompileSwift failed with a nonzero exit code. Tried  both Eureka 5.3.0 and 5.2.1, there error occurs.

How do we work around this? Thanks

**Comment by conrad030** [comment]
> Hi, compile error occurs in Xcode 12. => Segmentation fault: 11. Command CompileSwift failed with a nonzero exit code. Tried both Eureka 5.3.0 and 5.2.1, the error occurs.
> 
> How do we work around this? Thanks

Same issue here ✋

**Comment by mats-claassen** [comment]
I am still trying to download Xcode 12 to test this. Was the `xcode12` branch working for you? Is this something new that was broken after beta 6?

**Comment by conrad030** [comment]
I worked with Xcode 11.7 before, so I can't tell. I downloaded the Xcode 12 GM seed 1 update from the App Store and this error occured.

**Comment by haohan88** [comment]
Hi Matt, was not working with Xcode12 until today.

**Comment by conrad030** [comment]
Found this: https://github.com/xmartlabs/Eureka/issues/2057
@mats-claassen your solution with the branch works for me. Thanks!

**Comment by mats-claassen** [comment]
Hmm, so yes #2057 is a thread about a Swift compiler issue with Xcode 12 which arose with the first beta. That was "fixed" in the `xcode12` branch and has now been released in Eureka 5.3.0.

I just build Eureka successfully from master (which is the same as 5.3.0) on Xcode 12. So using 5.3.0 should be fine with Xcode 12. If you have problems anyway please validate your own code around Eureka (custom rows for example). And please open another issue or post in #2057 if it is an issue with Xcode 12. This thread is about older Xcode versions.

**Comment by haohan88** [comment]
Hi all, thanks for the help. The workaround https://github.com/xmartlabs/Eureka/issues/2057 works.
