### ISSUE TITLE
Crash during collapse of PickerInlineRow

### ISSUE THREAD

**Issue by mbopp** [xmartlabs/Eureka#208]
There seems to be an edge case that throws a "nil found exception" when using the PickerInlineRow.  The error can be replicated using the Picker row by swiping the picker dial (so it bounces, beyond the last option), and then immediately closing the inline picker view row.  

My best guess is that the logic for selecting a value in the picker is running AFTER the inline row has been, at least partially, deallocated.  The specific error seems to be that the `pickerRow` property is nil when grabbing the `pickerView:titleForRow:forComponent`.  

Because the bouncing animation is still happening when the cell is collapsed, when the bouncing stops, the cell no longer has the pickerRow available to draw data from.

Let me know if help is needed replicating the issue.

**Comment by mbopp** [comment]
The exception is prevented if I change the `pickerRow` to an optional in Cells.swift ~#614
`private var pickerRow : _PickerRow<T>? { return row as? _PickerRow<T> }`
Then putting some checks in place in the `UIPickerViewDelegate` callbacks. Like...

```
    public func pickerView(pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int{
        if pickerRow == nil { return 0 }
        return pickerRow!.options.count
    }
    
    public func pickerView(pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String?{
        if pickerRow == nil { return "" }
        return pickerRow!.displayValueFor?(pickerRow!.options[row])
    }
    
    public func pickerView(pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        if pickerRow == nil { return }
        pickerRow!.value = pickerRow!.options[row]
    }
```

Though there may be a more appropriate way of handling the situation.  
One side effect with this solution is that the when the picker is collapsed while still "bouncing" the value does not change to what it ultimately lands on, which isn't ideal, but better than a crash.

**Comment by mtnbarreto** [comment]
@mbopp Thanks for reporting the issue! Should be fixed now!
