### ISSUE TITLE
Compilation Error targeting macCatalyst 13

### ISSUE THREAD

**Issue by mvignau-snap** [xmartlabs/Eureka#2081]
### Setup

- Environment: Eureka 5.3.0 via CocoaPods, macOS 10.15.6, Xcode 12.0. 
- App target iOS 11 and macOS 10.15 (macCatalyst 13)
- Build for mac Intel (no error when building for iOS)

### Compilation Error
```
/[***]/Pods/Eureka/Source/Rows/DateInlineRow.swift:40:57: error: type 'UIDatePickerStyle' has no member 'inline'
            cell.datePicker.preferredDatePickerStyle = .inline
                                                       ~^~~~~~
```

### Solution
I tried modifying `DateInlineRow.swft` line 38-40 from:
```swift
        if #available(iOS 14.0, *) {
            #if swift(>=5.3)
            cell.datePicker.preferredDatePickerStyle = .inline
```
to
```swift
        if #available(iOS 14.0, macOS 11, *) {
            #if swift(>=5.3)
            cell.datePicker.preferredDatePickerStyle = .inline
```

But that did not work, so I excluded macCatalyst all together:
```swift
        if #available(iOS 14.0, *) {
            #if swift(>=5.3) && !targetEnvironment(macCatalyst)
            cell.datePicker.preferredDatePickerStyle = .inline
```

This works for my project, but `preferredDatePickerStyle = .inline` would not be executed if targeting macCatalyst 14

**Comment by mats-claassen** [comment]
#2078 Should fix this issue. It has been merged into master. I want to let the dust settle a bit on iOS 14 to see if there are other things to fix but next week there should be a new release
