### ISSUE TITLE
TextRow default font and textAlign does not work

### ISSUE THREAD

**Issue by MahdiyarTH** [xmartlabs/Eureka#2082]
Hey. I'm using Xcode 11.7, Eureka 5.3.0 and swift 5

i'm setting TextRow default font using code bellow, but it does not affect my UI at all.

```
tableView.semanticContentAttribute = .forceRightToLeft;
        
        TextRow.defaultCellSetup = { cell, row in
            cell.textField.textAlignment = .right;
            cell.textField.semanticContentAttribute = .forceRightToLeft;
            cell.textField.font = Constants.textFieldFont
            cell.textField.backgroundColor = .red
        }
        
        form
            +++ Section(header: "Hello", footer: nil)
            <<< TextRow()
```

the line `cell.textField.backgroundColor = .red` works and my background color changed. but not about my font and textAlign.
`Constants.textFieldFont` is a valid font and is working in other part of my project.
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-20 at 16 29 06](https://user-images.githubusercontent.com/25479661/93710831-b3c8cb80-fb5e-11ea-9e21-92b7b2afd101.png)

**Comment by mats-claassen** [comment]
Hi, sorry for the late response. Try setting those values in `defaultCellUpdate` instead

**Comment by HZChenCheng** [comment]
Why can't defaultCellSetup？
