### ISSUE TITLE
Change DateTimeRow font color in dark mode?

### ISSUE THREAD

**Issue by gdelarosa** [xmartlabs/Eureka#2084]
Currently running Xcode 12, iOS 14, and Eureka 5.3.0. 

While running the app in dark mode, the DateTimeRow does not display the selected data/time in  the black font color. Instead it will display very faintly and is almost invisible to read. 

```
}.cellUpdate { cell, row in
                cell.textLabel?.tintColor = .black
                cell.textLabel?.textColor = .black
                cell.backgroundColor = .white
             }
```
![Screen Shot 2020-09-21 at 2 57 34 PM](https://user-images.githubusercontent.com/9616943/93820775-e0dab400-fc1a-11ea-888b-77e263a33e7c.png)

**Comment by mats-claassen** [comment]
In dark mode the cell's background should be dark, in which case you would see the selected date/time correctly. If you change the default backgroundColor, you should also change the default color of the `detailTextLabel`

**Comment by gdelarosa** [comment]
Solved. Changing the detailTextLabel did the trick. Thank you @mats-claassen!
