### ISSUE TITLE
[question] How to modally present view controller with ButtonRow?

### ISSUE THREAD

**Issue by Ludotrico** [xmartlabs/Eureka#2086]
I have read the readMe thoroughly and looked at the example project. Unfortunately, the buttonRows in the example only showed how to push a view controller using storyboard segue.

How can you modally present or just push a view controller on selection?

            +++ Section("Edit Event")
                <<< ButtonRow() {
                    $0.title = "Media"
                    let provider = ControllerProvider.callback(builder: { return EventMediaVC() })
                    $0.presentationMode = .presentModally(controllerProvider: provider, onDismiss: nil)
                }

Here there is the following error: 

Cannot convert value of type 'ControllerProvider<EventMediaVC>' to expected argument type 'ControllerProvider<UIViewController>'

**Specifically, how can you conform a VC to 'ControllerProvider<UIViewController>'?**

**Comment by mats-claassen** [comment]
Hi @Ludotrico, `ControllerProvider` is an enum. You don't conform to it. It is also generic so if you want to create the controller using a callback as you did you should write something like:

```swift
let provider = ControllerProvider<EventMediaVC>.callback(builder: { return EventMediaVC() })
```

**Comment by Ludotrico** [comment]
@mats-claassen that makes sense, it works now! Thank you
