### ISSUE TITLE
How can I add an Image next to the title of a Switch Row?

### ISSUE THREAD

**Issue by jlstr** [xmartlabs/Eureka#2097]
I would like my SwitchRow to have an Image next to the title like this:

![switch__row](https://user-images.githubusercontent.com/583016/95385024-06222000-08b3-11eb-8f93-2bbe99dd8250.jpg)

Is it possible? I would also need to add a Tap Gesture Recognizer for said image.

Thank you in advance.

**Comment by mats-claassen** [comment]
You will have to create a custom row for that. Have a look at the Readme and the linked blog posts in there for help if needed.

**Comment by jlstr** [comment]
@mats-claassen Thank you for reply. I will see what I can do.

**Comment by jlstr** [comment]
I'm getting an error when I instantiate the custom Row.

`Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ScheduleTestFormViewController 0x7fb78e820730> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key helpImage.'`

`helpImage` is an Outlet (UIImageView) in my Custom TableViewCell. I've gone through the tutorial a number of times now and the result has been the same. Any help with this issue is appreciated.

Thank you.

**Comment by mats-claassen** [comment]
As the error says, UIKit is looking for `helpImage` inside `ScheduleTestFormViewController`. Try reviewing how you created that outlet

**Comment by justdan0227** [comment]
Can you change the row height doing this as well?

**Comment by mats-claassen** [comment]
Hi @justdan0227 to change the height of a cell use:
```swift
.cellSetup { (cell, row) in
    cell.height = { 67 }
}
```
