### ISSUE TITLE
looking to update the section footer text dynamically ..

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#210]
I have a scenario where each row with a textfield has its own section and looking to use the section footer text to be dynamically updated to indicate the number of characters remaining in BLUE as the user types text and also to indicate in RED when the user exceeds the character limit.

In addition, I am trying to make the footer text a smaller font. Looking for suggestion on best way to do this. Currently, it appears that I can set a footer only when the Section is created and it has a standard font size.

Thanks in advance

**Comment by mats-claassen** [comment]
You can set a new footer to the section but you must reload the section before it takes effect on the view.
You cannot change the font of the footer unless you use a custom view for it.

**Comment by rajeshmani27** [comment]
How do I just reload the section 

Thanks

**Comment by mats-claassen** [comment]
If you are using the master version, there is a function `reload` in the Section class. 
If not, wait a bit for it or just:
```
tableView.reloadSections(NSIndexSet(index: index), withRowAnimation: rowAnimation)
```

**Comment by dilizarov** [comment]
Is there a way to accomplish this without the TextField losing its focus when `section.reload()` gets called?
