### ISSUE TITLE
 Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by godlikejoke** [xmartlabs/Eureka#2108]
When I update to the latest version of xcode12.1, 
and I manually import the latest Eureka (master branch 4966703a61df8e17fc74939dfeec4e5c9e94db7c), 

Error when I attempt to import Eureka:
module compiled with swift 5.2.4 cannot be imported by the swift 5.3 compiler... / products / debug iPhone simulator/ Eureka.framework/Modules/Eureka .swiftmodule/x86_ 64-apple-ios- simulator.swiftmodule

**Comment by mats-claassen** [comment]
How are you building it? By manually importing it you mean you add it the source files to your Xcode project? In that case you would be building it with the same Swift compiler, right?

**Comment by godlikejoke** [comment]
yes，i  importing it like this,Eureka was available until I upgraded xocde12.1
![image](https://user-images.githubusercontent.com/11766916/97523735-fe4f2a80-19dd-11eb-9ab0-4219214eb1e2.png)
![image](https://user-images.githubusercontent.com/11766916/97523771-0f983700-19de-11eb-9dd0-78220937ca49.png)

**Comment by mats-claassen** [comment]
Have you tried rebuilding Eureka before building your project? Or a clean and build maybe?

**Comment by godlikejoke** [comment]
thank you very much! I open the Eureka project, clean and build the project, and then manually import Eureka into my project to solve it.  you so cool!
