### ISSUE TITLE
ChecklistRow, initial value

### ISSUE THREAD

**Issue by ebeland** [xmartlabs/Eureka#2115]
Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by ebeland** [comment]
I'm trying to set the initial value of a Selectable Section and cannot find the right way to do so.

form +++ SelectableSection<ListCheckRow<AlbumSortType>>("Sort By", selectionType: .singleSelection(enableDeselection: false))

    form.last!.header = HeaderFooterView<UIView>(HeaderFooterProvider.class)
    form.last!.header?.height = { 0.1 }
        
      for option in self.sortOptions {
            let optionString = option.titleText() + option.secondarySortingText(isAscending: option.isAscending)
            self.form.last! <<< ListCheckRow<AlbumSortType>(optionString) { listRow in
                listRow.title = optionString
                listRow.selectableValue = option
                listRow.value = nil
                if option == self.selectedAlbumSortType {
                    // I tried selecting here it doesn't set the value.
                }
            }
            .onChange({ row in
                self.selectedAlbumSortType = row.selectableValue
            })
        }

I've tried setting it a number of ways and can't find a definitive answer in the docs / Github / Stack. Any clues would be appreciated.

Selecting rows that match my current value has not worked so far.  

I also tried variations on this.

form.setValues(["Sort By": [self.selectedAlbumSortType]])

**Comment by mats-claassen** [comment]
If `listRow.value == listRow.selectableValue` (so, when it is not nil) then it is selected. 
What you can do is:

```swift
listRow.value = option == self.selectedAlbumSortType ? option : nil
```

**Comment by ebeland** [comment]
Thank you that worked.  Never would have guessed that.
