### ISSUE TITLE
Xcode 12.2

### ISSUE THREAD

**Issue by terryworona** [xmartlabs/Eureka#2119]
Any idea when Eureka will be compatible with swift 5.3.1 (via Xcode 12.2)? 

I'm getting this import error with the latest Xcode GM (12.2 `12B45b`):

```
Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler
```

Building off of `master` but no luck.

**Comment by terryworona** [comment]
Release `5.3.2` doesn't seem to resolve this for Xcode. 12.2.

**Comment by mats-claassen** [comment]
Are you using Carthage? If so, have you rebuild the Eureka dependency after updating Xcode? This sounds like your Eureka dependency being built by a previous version of Xcode. If you are not using Carthage try to clean and build Eureka

**Comment by terryworona** [comment]
Ah my mistake! It was built using Xcode `12.1`. Re-built using `12.2` and works now. Thanks for help.
