### ISSUE TITLE
RE: PasswordRow TextField Display ommited by three-pointed reader.

### ISSUE THREAD

**Issue by vertuxx** [xmartlabs/Eureka#2125]
I previously reported an issue where the password field was omitted with "..." in 3.5.0.
This time I checked out 3.5.2 and rechecked to see that the issue wasn't resolved.

Please see the capture.
If the password text becomes long, it will be omitted with "...".
After all, commenting out what I pointed out earlier solved the problem.

`/* if let titleLabel = titleLabel { ... } */`

Hmm. Type "ijklijkli" and it will be omitted.
"ijkl" can be entered up to 2 times, but when "i" is added, "..." is displayed at the end.
The image below is all entered as "ijklijkli".

Please check again.
Thank you.

![EUREKA_5 3 2_IMG_0456](https://user-images.githubusercontent.com/2898039/102202807-1dad0300-3f0b-11eb-8bfb-6b2eb0ddaca2.jpg)

_Originally posted by @vertuxx in https://github.com/xmartlabs/Eureka/issues/2079#issuecomment-745196343_

**Comment by mats-claassen** [comment]
Hi @vertuxx Could you validate that #2129 fixes the issue?

**Comment by vertuxx** [comment]
Hello @mats-claassen 
I've seen the modified code in FieldsRow.swift.
It seems that there is no problem running Example on iPhone.
It looks okay.

Thank you.
