### ISSUE TITLE
How to get height of a table.

### ISSUE THREAD

**Issue by trankimhieu** [xmartlabs/Eureka#213]
Hi everybody.
I put Eureka form inside a container and want to update container height follow form height. How to get form height.

**Comment by mtnbarreto** [comment]
@trankimhieu I have never tried this but it seems not a Eureka domain problem. 
http://stackoverflow.com/questions/6860231/how-to-get-the-size-of-a-uitableviews-content-view

Please post these kind of questions on stackoverflow as contribution guide points out.

Regards
