### ISSUE TITLE
ActionSheetRow - automatically increase height

### ISSUE THREAD

**Issue by chumps52** [xmartlabs/Eureka#2131]
Eureka 5.3.2, iOS 14.3, Xcode 12.3

I'm adding support for Dynamic Type to my app, but the `ActionSheetRow`s don't seem to play ball. [This image shows how they look with the smallest text size, and the largest](https://i.imgur.com/CWcvaJO.png).  
How do I get the cell/row to increase in height to accommodate the text size increase?  

&nbsp;  

At the moment, my `.defaultCellUpdate` is as follows:

        cell.textLabel?.font = UIFont.preferredFont(for: .body, weight: .bold)
        cell.textLabel?.adjustsFontForContentSizeCategory = true
        cell.textLabel?.numberOfLines = 0
        
        cell.detailTextLabel?.font = UIFont.preferredFont(for: .body, weight: .regular)
        cell.detailTextLabel?.adjustsFontForContentSizeCategory = true
        cell.detailTextLabel?.numberOfLines = 0

**Comment by mats-claassen** [comment]
Hi, sorry for the late response. ActionSheetCell is a normal `UITableViewCell` and its height is set to UITableView.automaticDimension unless you change it in your code. In the examples project it works just fine
