### ISSUE TITLE
PickerInputRow onChange method invoking once

### ISSUE THREAD

**Issue by reenaphilip** [xmartlabs/Eureka#2138]
I have a picker input row with custom objects as options. The onChange method has code to reload some of the cells based on the object selected from the picker. When I choose any of the object for the first time, its working as expected. But from second time onwards, the onChange method is not getting invoked. 
Also, in the picker even if I select any object its automatically going back to the first open. 

If I use options as normal Strings, its working. The issues are with custom objects as picker options.

**Comment by mats-claassen** [comment]
Hi @reenaphilip could you specify which version of Eureka and Xcode you are using? And a code sample to reproduce would be nice too

**Comment by reenaphilip** [comment]
> Hi @reenaphilip could you specify which version of Eureka and Xcode you are using? And a code sample to reproduce would be nice too

This the section with picker and other label rows.

           +++ Section("New Shift")
            <<< PickerInputRow<ShiftTypeElement>{
                $0.options = shiftRequestVM.shiftTypesList
                $0.title = "Shift Type"
                $0.add(rule:RuleRequired())
                $0.validationOptions = .validatesOnDemand
                $0.noValueDisplayText = "Select shift"
                //                $0.displayValueFor = {
                //                    return $0?.shiftName
                //                }
                $0.cell.detailTextLabel?.textColor = .black
            }.onChange({ [weak self](row) in
                self?.shiftRequestVM.newShift = row.value!
                if let startRow = self?.form.rowBy(tag: "New Shift Starts") as? LabelRow{
                    startRow.value = row.value?.startTime
                    startRow.updateCell()
                }
                if let endRow = self?.form.rowBy(tag: "New Shift Ends") as? LabelRow{
                    endRow.value = row.value?.endTime
                    endRow.updateCell()
                }
            })
                .cellUpdate({ (cell, row) in
                    if !row.isValid{
                        cell.textLabel?.textColor = .red
                    }
                }).onCellSelection({ [weak self](cell, row) in
                    if (self?.shiftRequestVM.shiftTypesList.isEmpty)!{
                        self?.shiftRequestVM.fetchShiftTypes()
                        row.options = (self?.shiftRequestVM.shiftTypesList)!
                    }
                })
            <<< LabelRow("New Shift Starts"){
                $0.title = "Start Time"
            }
            <<< LabelRow("New Shift Ends"){
                $0.title = "End Time"
            }

The custom object is
   class ShiftDetailsElement: Codable {
    
    let id : Int
    let shiftType : String
    let startTime : String
    let endTime : String
    let empId : Int
    let result : String?
    
    enum CodingKeys : String, CodingKey{
        case id = "ID"
        case shiftType = "ShiftType"
        case startTime = "StartTime"
        case endTime = "EndTime"
        case empId = "EmpID"
        case result = "AuthenticationResult"
    }
    }

and the sample json for getting the custom object is
   {"ID":32,"ShiftType":"Afternoon","StartTime":"11/1/2020 2:00:00 PM","EndTime":"11/1/2020 10:00:00 PM","EmpID":"5","AuthenticationResult":null}

I am using Eureka 5.3.2

**Comment by mats-claassen** [comment]
`ShiftDetailsElement` must be `Equatable` and implemented in a way that each different object in the options list is not equal to any other (otherwise, the framework thinks the value didn't change). Did you implement it that way?

**Comment by reenaphilip** [comment]
> `ShiftDetailsElement` must be `Equatable` and implemented in a way that each different object in the options list is not equal to any other (otherwise, the framework thinks the value didn't change). Did you implement it that way?

Yes. I implemented it as Equatable and CustomStringConvertible. But in Equatable, I was comparing Int properties. When I changed it to the String property it got worked.  
Thanks for reminding that .
