### ISSUE TITLE
PushRow onChange

### ISSUE THREAD

**Issue by havocked** [xmartlabs/Eureka#215]
Hi ! 
Is there a way to listen to an ``onChange`` event for ``PushRow``, like ``AlertRow`` for example ?
Thanks again for your great work !

**Comment by mtnbarreto** [comment]
@havocked 

Yes, All Eureka rows have the "same" callbacks since all must conforms to `RowType`.

Note that PushRow is a generic type....
```swift
                <<< PushRow<Emoji>() {
                        $0.title = "PushRow"
                        $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻]
                        $0.value = 👦🏼
                        $0.selectorTitle = "Choose an Emoji!"
                    }.onChange {
                        print("Value = \($0.value)")
                    }
```

Let me know if this works for you.
