### ISSUE TITLE
Any way to resize height of SegmentedRow (clickable zone, not only the view)

### ISSUE THREAD

**Issue by Rayhko** [xmartlabs/Eureka#2158]
Hello, I am trying to increase the height of the buttons of a SegmentedRow.
I managed to do it with a code similar to this one:

```
<<< SegmentedRow<String>("persist_row"){
    $0.title = "Persist"
    $0.options = ["true", "false"]
}.cellSetup { cell, _ in
    cell.segmentedControl.widthAnchor.constraint(equalToConstant: 200).isActive = true
}
```

However, it only increases the height visually and not the clickable area which remains very small.

Does anyone have an idea for a solution please?

**Comment by Rayhko** [comment]
Finally found a solution, i use constraints with visual format like this : 

```
dynamicConstraints = NSLayoutConstraint.constraints(withVisualFormat: "V:|-[segmentedControl(80)]|", options: .alignAllCenterY, metrics: nil, views: views)
        contentView.addConstraints(dynamicConstraints)
```

**Comment by onuryurtturk** [comment]
@Rayhko can you share more detail? how?

**Comment by onuryurtturk** [comment]
@Rayhko can you share more detail? how?
