### ISSUE TITLE
The regular expression in RuleEmail does not allow some valid special characters

### ISSUE THREAD

**Issue by mstralka** [xmartlabs/Eureka#2159]
- Environment: Eureka 5.3.3
- Xcode 12.4
- iOS 14.4

Eureka's enum `RegExprPattern.EmailAddress` currently looks like this:
~~~
^[_A-Za-z0-9-+]+(\\.[_A-Za-z0-9-+]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z‌​]{2,})$
~~~

According to [Valid Characters for Email Addresses: The Complete List](https://ladedu.com/valid-characters-for-email-addresses-the-complete-list/), the username of an email address may contain apostrophes, question marks, exclamation points, and some other special characters:
![image](https://user-images.githubusercontent.com/439680/120103836-871e7800-c11f-11eb-86fb-fdfeb3f8a5e9.png)

I propose changing the email address regular expression to:
~~~
^[_A-Za-z0-9-+!?#$%'`*/=~^{}|]+(\\.[_A-Za-z0-9-+!?#$%'`*/=~^{}|]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z‌​]{2,})$
~~~

**Comment by mats-claassen** [comment]
Makes sense. Could you create a PR with this change and also updating `ValidationsTests.swift` by either updating `testRuleEmail`, or adding a new test with some simple validations?
