### ISSUE TITLE
Using 'class' keyword for protocol inheritance is deprecated

### ISSUE THREAD

**Issue by dhermanns** [xmartlabs/Eureka#2161]
Hi!

Just a warning - but I think you would like to know it.
My Environment is: Eureka 5.3.3, Latest Xcode and latest iOS version.

I think 'class' should be changed here to AnyObject - as proposed by Xcode.

cu,
Dirk

**Comment by mats-claassen** [comment]
This has been resolved in #2151 but hasn't yet been released.

**Comment by dustinlange** [comment]
Is there an ETA on the next release?
