### ISSUE TITLE
Readme update that shows tags

### ISSUE THREAD

**Issue by justdan0227** [xmartlabs/Eureka#2163]
Am I missing something or does the read me not show how you set a tag for a row?  It shows how you obtain the value for a row by supplying a tag string, however I don't see in the readme where you set those tags.  I'm guessing its just with row.tag = "tag identifier string" ?

**Comment by mats-claassen** [comment]
You can set a tag either as you say or just like this:
```swift
<<< TextRow("my-tag")
```

This is shown in the Readme but not mentioned explicitly

**Comment by justdan0227** [comment]
Ahhhh thanks!
