### ISSUE TITLE
[Eureka.DateCell retain]: message sent to deallocated instance 

### ISSUE THREAD

**Issue by johnjiang** [xmartlabs/Eureka#217]
When I dismiss a view with a datecell, under certain situations I got the following error:

`[Eureka.DateCell retain]: message sent to deallocated instance `

**Comment by mtnbarreto** [comment]
@johnjiang Is this issue still happening using master branch code?

Please follow this guide to contribute: https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md

Regards

**Comment by johnjiang** [comment]
Yes, confirmed that it's still happening using master branch
