### ISSUE TITLE
xCode13 CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

### ISSUE THREAD

**Issue by PierreBrisorgueil** [xmartlabs/Eureka#2178]
Hello, just ran into this with SPM : 

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-13-release-notes

> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
> 
> Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support 

`CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Eureka' from project 'Eureka')
`

**Comment by PierreBrisorgueil** [comment]
hum, strange 🤔

<img width="200" alt="Screenshot 2021-10-06 at 20 50 41" src="https://user-images.githubusercontent.com/6069599/136264963-a52e9355-02b7-440d-bcc2-7aad6d233916.png">

```
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Eureka' from project 'Eureka')
    cd /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/SourcePackages/checkouts/Eureka
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Eureka -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DXcode -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -target arm64-apple-ios9.0 -g -module-cache-path /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -profile-coverage-mapping -profile-generate -embed-bitcode-marker -enable-testing -index-store-path /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Index/DataStore -swift-version 5 -I /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Products/development-iphoneos -I /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Products/development-iphoneos -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/Developer/Library/Frameworks -c -j12 -output-file-map /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/Objects-normal/arm64/Eureka.swiftmodule -Xcc -I/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/swift-overrides.hmap -Xcc -I/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Products/development-iphoneos/include -Xcc -I/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/DerivedSources-normal/arm64 -Xcc -I/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/DerivedSources/arm64 -Xcc -I/Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -emit-objc-header -emit-objc-header-path /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/Build/Intermediates.noindex/Eureka.build/development-iphoneos/Eureka.build/Objects-normal/arm64/Eureka-Swift.h -working-directory /Users/pierrebrisorgueil/Library/Developer/Xcode/DerivedData/waosSwift-blklsvylyurdhqcbfsxcfirghxkd/SourcePackages/checkouts/Eureka

Command CompileSwiftSources failed with a nonzero exit code
```

<img width="176" alt="Screenshot 2021-10-06 at 20 49 41" src="https://user-images.githubusercontent.com/6069599/136264844-9c51c8ae-0d20-4204-9be1-83dcd138142d.png">

<img width="285" alt="Screenshot 2021-10-06 at 20 51 20" src="https://user-images.githubusercontent.com/6069599/136265075-b416cfd6-c2b7-494f-a48c-b0ee9bda1d58.png">

**Comment by mats-claassen** [comment]
So if you select your project and go to `Build Settings` -> Architectures. Which architectures do you have selected? Is it only arm64 and armv7?

**Comment by PierreBrisorgueil** [comment]
Hum I never touched this config, it's probably the default one 

<img width="1077" alt="Screenshot 2021-10-11 at 16 35 57" src="https://user-images.githubusercontent.com/6069599/136841574-d4b2a1b9-cf9d-4b7e-a541-a066b7683c9b.png">

**Comment by ngima** [comment]
I'm also having the same issue on xCode13

**Comment by PierreBrisorgueil** [comment]
Not on my side, task in pause, I will be back on it asap
_interested if you find a oslution_

**Comment by mohdmunaf** [comment]
Quit Xcode -> Go to Applications -> XCode -> rightclick -> Get Info -> Check the checkbox `Open using Rosseta` -> Open Xcode

**Comment by nihp** [comment]
I am getting the error as Executable path not found error.

**Comment by mjayansf** [comment]
Was anyone able to fix this?

**Comment by nihp** [comment]
I have downgraded the Xcode to 13.0 and then try with opening on the 13.2.1 it works

**Comment by nathalia-rus** [comment]
Same problem here. Anyone found a solution / some more clues?

**Comment by cdwaller** [comment]
I found that just going to general settings and unticking "iPad" helped me

**Comment by emirhanbattalbas** [comment]
@mohdmunaf  thank you for your answer

**Comment by krishant-fxbytes** [comment]
I am also facing this issue XCode 12.4 error: Segmentation fault: 11 (in target 'Eureka' from project 'Pods')

**Comment by kietnguyenn** [comment]
i have the same issue on mac m1

**Comment by krishant-fxbytes** [comment]
Problem not solve at time you have any solution this issue related

**Comment by alextkd** [comment]
Just go to the library that fails and select arm6 architecture instead of the default one in Build Settings. It should work
![image](https://user-images.githubusercontent.com/373321/165030762-34660492-9e62-46a8-a398-92b0a870bfa3.png)

**Comment by krishant-fxbytes** [comment]
this solution not working on my side i have already change in build setting
in Architecture as per your suggestion.. but problem not solve

**Comment by alextkd** [comment]
Check every library and 

> 

Did you try to set this architecture for the specified library in your Pods - CardScanner where ActionSheetRow is used? It shows it uses x86 to compile it...

**Comment by mtoninelli** [comment]
it doesn't solve the problem

**Comment by krishant-fxbytes** [comment]
Ok, I'll check it out.

**Comment by grantespo** [comment]
I'm on an M1 mac

After doing this `carthage bootstrap --platform iOS --use-xcframeworks`

I get this error:

> *** Building scheme "RxTest" in Rx.xcworkspace
> *** Building scheme "Moya" in Moya.xcodeproj
> Build Failed
> 	Task failed with exit code 65:
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/lr/x2lngmyn63v95xk121r1vxkm0000gn/T/carthage-xcodebuild.CzzglN.log

** BUILD FAILED **

Then when I check the log, it shows this:

> The following build commands failed:
> 	CompileSwift normal arm64 (in target 'Moya' from project 'Moya')
> 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Moya' from project 'Moya')
> 	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler (in target 'Moya' from project 'Moya')
> 	CompileSwift normal i386 (in target 'Moya' from project 'Moya')
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Moya' from project 'Moya')
> 	CompileSwift normal x86_64 (in target 'Moya' from project 'Moya')
> (6 failures)


Moya team, would be nice if you created a PR to fix this issue or advise a solution. Thanks!

**Comment by truongtq2506** [comment]
Someone needs it. 
In my case, I remove the file. Cause I upgraded RN 64 to 66.4 
Might you miss the file swift you should create? Or you should remove it if don't necessary.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/15075926/171359706-f316a63a-39c9-4efe-b3e6-e5039587afff.png">

**Comment by mlorenze** [comment]
I did a simple new project adding Eureka with SPM (branch master) and couldn't replicate this problem.
I used this setup:

* MacBook Pro M1
* MacOS Monterrey (12.3.1)
* XCode 13.3.1 (13E500a)
* iOS Deployment 15.0

**Comment by FishOfHugToSky** [comment]
![image](https://user-images.githubusercontent.com/21261924/173019217-94c129d8-9ea2-4c39-a650-a724373e08a1.png)
How to solve the problem

**Comment by mats-claassen** [comment]
Hi all, as @mlorenze pointed out we tried to reproduce this in Eureka and couldn't. If someone still has this issue **in Eureka**, then please provide clear steps to reproduce. Will close meanwhile as this is getting a lot of posts which don't seem related to Eureka.

**Comment by aceslick911** [comment]
> In my case, I remove the file. Cause I upgraded RN 64 to 66.4

Thanks for this @truongtq2506 
Had this same issue upgrading to RN69 - some files were left which were ignored.

For anyone having this issue today or in the future, do a git clean or re-clone your project to get rid of any lingering files!

```
git clean -fdx
```

**Comment by kesha-antonov** [comment]
> > In my case, I remove the file. Cause I upgraded RN 64 to 66.4
> 
> Thanks for this @truongtq2506 Had this same issue upgrading to RN69 - some files were left which were ignored.
> 
> For anyone having this issue today or in the future, do a git clean or re-clone your project to get rid of any lingering files!
> 
> ```
> git clean -fdx
> ```

it worked, thanks
