### ISSUE TITLE
Redundant conformance of 'SelectableSection<Row>' to protocol 'Taggable'

### ISSUE THREAD

**Issue by saucym** [xmartlabs/Eureka#2179]
Build to xcframework, report an error when using
use this shell build xcframework
`
#!/bin/bash

NAME=Eureka
ARCH_DIR=$NAME.archives
CONFIGURATION=Release
    
xcodebuild archive \
  -scheme $NAME \
  -project $NAME.xcodeproj \
  -sdk iphoneos \
  -configuration $CONFIGURATION \
  -archivePath "$ARCH_DIR/ios_devices.xcarchive" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  SKIP_INSTALL=NO \
  clean

xcodebuild archive \
  -scheme $NAME \
  -project $NAME.xcodeproj \
  -sdk iphonesimulator \
  -configuration $CONFIGURATION \
  -archivePath "$ARCH_DIR/ios_simulators.xcarchive" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  SKIP_INSTALL=NO \
  clean 

SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)

if [ $CONFIGURATION = Debug ];then 
    echo "CONFIGURATION = Debug"
    xcodebuild -create-xcframework \
    -framework $ARCH_DIR/ios_devices.xcarchive/Products/Library/Frameworks/$NAME.framework \
    -framework $ARCH_DIR/ios_simulators.xcarchive/Products/Library/Frameworks/$NAME.framework \
    -output $NAME.xcframework
else
    echo "CONFIGURATION = $CONFIGURATION"
    xcodebuild -create-xcframework \
    -framework $ARCH_DIR/ios_devices.xcarchive/Products/Library/Frameworks/$NAME.framework \
    -debug-symbols $SHELL_FOLDER/$ARCH_DIR/ios_devices.xcarchive/dSYMs/$NAME.framework.dSYM \
    -framework $ARCH_DIR/ios_simulators.xcarchive/Products/Library/Frameworks/$NAME.framework \
    -debug-symbols $SHELL_FOLDER/$ARCH_DIR/ios_simulators.xcarchive/dSYMs/$NAME.framework.dSYM \
    -output $NAME.xcframework
fi

rm -r $ARCH_DIR
`

**Comment by mats-claassen** [comment]
I am not seeing this warning when building Eureka. Please reopen with additional info adding the respective versions if still an issue
