### ISSUE TITLE
Navigation Bar overlapped by Sections while scrolling

### ISSUE THREAD

**Issue by dlpgithub** [xmartlabs/Eureka#2184]
XCode 13.1
Eureka 5.3.4
iOS 15+

I'm not sure if this error already occurred with iOS 14.
In iOS 15 I noticed that the Navigation Bar is overlapped by the Sections while scrolling.
Can anyone conform this issue?

https://user-images.githubusercontent.com/48456028/139273060-9f0b900d-f3eb-4ba6-8c9e-39ddf243e740.mp4

**Comment by cecipirotto** [comment]
Hi! On iOS 15, you have to configure the navigation bar appearance to opaque. You can see [this answer](https://stackoverflow.com/questions/69111478/ios-15-navigation-bar-transparent).
