### ISSUE TITLE
Build service could not create build operation 

### ISSUE THREAD

**Issue by fukemy** [xmartlabs/Eureka#2187]
Before submitting issues ...

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: 
 + Eureka : lasted.
 + Xcode 130.0
 + IOS 15

![Ảnh chụp Màn hình 2021-11-22 lúc 23 27 38](https://user-images.githubusercontent.com/8202437/142898591-4e9073cf-9ca9-4760-b046-c8d01da715a4.png)

i got this problem and can not build project, can u help? Thanks

**Comment by mats-claassen** [comment]
Hi, can you explain how this is related to Eureka?

**Comment by fukemy** [comment]
i found the problem, your library conflict with QuickTableViewController, i removed this then started using your lib without problem :D
