### ISSUE TITLE
SegmentRow tint color?

### ISSUE THREAD

**Issue by fukemy** [xmartlabs/Eureka#2188]
hi, that question is not about the bug
im trying to find anything that related to segment tint but not working
i have read this issue but he does not give his answer:
https://github.com/xmartlabs/Eureka/issues/1137

can u help? Thanks

**Comment by cecipirotto** [comment]
Hi! you can set the selected tint color on the `cellSetup` callback. 
Code example:
```
<<< SegmentedRow<String>("segments"){
                $0.options = ["Sport", "Music", "Films"]
                $0.value = "Films"
            }.cellSetup({ cell, row in
                 cell.segmentedControl.selectedSegmentTintColor = .blue
            })
```

**Comment by fukemy** [comment]
@cecipirotto love u
