### ISSUE TITLE
Mac Catalyst build errors (Ambiguous use of 'next')

### ISSUE THREAD

**Issue by chumps52** [xmartlabs/Eureka#2190]
Eureka 5.3.4 using Cocoapods. Xcode 13.1. M1 Pro MacBook Pro.

Getting the following when attempting to build using Catalyst - has worked previously, but I now get this error on line 55 of `Cell.swift` (`Ambiguous use of 'next'`).

I _believe_ my last successful build was with 5.3.3 on Xcode 13.0. I've tried downgrading to 5.3.3 but using Xcode 13.1, but it still fails.

Have also tried clearing my build folder + emptying derived data.

<img width="2056" alt="Screenshot 2021-11-23 at 14 01 59" src="https://user-images.githubusercontent.com/22566395/143038084-37222364-1d7b-4981-adcf-b48c6d53345f.png">

**Comment by chumps52** [comment]
Can confirm that Xcode 13.0 builds this fine - but that has the SDK for macOS 11.3 (20E214), rather than 13.1's 12.0 (21A344).

**Comment by mats-claassen** [comment]
Hey @chumps52 can you try whether the PR #2191 fixes the issue?

**Comment by chumps52** [comment]
@mats-claassen Seems to - thank you! :)

**Comment by mtvg** [comment]
Hi @mats-claassen, do you know when is the next release that will contain this PR? Would like to avoid using the master branch if possible. Thanks!

**Comment by mats-claassen** [comment]
Version 5.3.5 released!
