### ISSUE TITLE
evaluateDisabled not working

### ISSUE THREAD

**Issue by fukemy** [xmartlabs/Eureka#2194]
hi, im using lasted Eureka version, and i have some row like this:

```
<<< SwitchRow("All-day") {
            $0.title = Language.get("All day")
            $0.tag = "all_day_row"
            $0.value = scheduleModel.AllDay
            $0.disabled = Condition(booleanLiteral: isViewingMode)
        }.onChange { row in
            guard let value = row.value else { return }
            self.scheduleModel.AllDay = value
        }
```

First time open ViewController, isViewingMode = true, so row disabled, but when change isViewingMode to false, then call evaluateDisabled but it's not working, all rows still disabled.

```
func setupEditMode(){
        isViewingMode = false
        form.allRows.forEach({
            $0.evaluateDisabled()
        })
    }
```

Can you help? Thanks

**Comment by mats-claassen** [comment]
Hi @fukemy. When you set `$0.disabled = Condition(booleanLiteral: isViewingMode)` you are setting disabled to the current value of `isViewingMode` which is `true`. But nothing is observing changes to that variable. If you want to change the disabled state on demand then you should reset the disabled condition to the other literal value, or use a `Condition` which is not literal but a function.
