### ISSUE TITLE
How to set a maximum number of choices in form

### ISSUE THREAD

**Issue by loonloon** [xmartlabs/Eureka#221]
I have try to create a survey form by using Eureka framework. However, how to set a maximum number of choice in form with MultipleSelection option ?

let fruits = ["Apple", "Banana", "Guava", "Others"]

form +++= SelectableSection<ImageCheckRow<String>, String>("fruits_section", selectionType: SelectionType.MultipleSelection) { section in
section.header = HeaderFooterView(title: "What is your favorite fruit ?")
}

for fruit in fruits {
    form.last! <<< ImageCheckRow<String>(fruit) { lrow in
        lrow.title = fruit
        lrow.selectableValue = fruit
    }
}

**Comment by mtnbarreto** [comment]
similar to #222 

You can do it by adding a `onChange` callback to each `ImageCheckRow`:

```swift
            .onChange { row in
                if let _ = row.value {
                    let count = row.section?.filter { $0.baseValue != nil }.count
                    if count > 3 {
                        row.value = nil
                        row.section?.reload()
                    }
                }
            }
```

**Comment by loonloon** [comment]
Hi mtnbarreto, thanks for your reply. The solution worked  as expected
