### ISSUE TITLE
Keyboard is not closing iOS 15.4

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#2212]
After updating to iOS 15.4 keyboard is not closing anymore by pressing `Done` button. Nothing happens, nothing is logged in Xcode. I manage to reproduce it with the Example as well.

1. Tap on `TextRow` for example 
2. Then try to close keyboard by pressing `Done`
3. Nothing happens

 - Device: iPad 6th Generation
 - OS: 15.4
 - Eureka Version 5.3.5
 - Xcode version 13.3

**Comment by mats-claassen** [comment]
Hi, this issue has been fixed in #2213

**Comment by chickendiver** [comment]
Any news on when this will be released?
