### ISSUE TITLE
question of remove insert animation

### ISSUE THREAD

**Issue by lilin87788** [xmartlabs/Eureka#2221]
I don't know how to remove this animation, I used a timer to simulate the network request data。
![now_gif_shuiyin_lower](https://user-images.githubusercontent.com/1483811/170865464-646ec39a-1265-49a2-8bcd-337854d74e8c.gif)
and I override the following delegate method, but it doesn't seem to work for me!!!
![WeChat90fa473c2d0b36d6e45ff36622bc9868](https://user-images.githubusercontent.com/1483811/170865481-6550f17e-97c1-4955-8d67-adea8f4600b7.png)

**Comment by mats-claassen** [comment]
Hi @lilin87788 I will close this as duplicate. If you search the [existing issues](https://github.com/xmartlabs/Eureka/issues?q=is%3Aissue+insert+animation+is%3Aclosed) (mainly the closed ones) you will find several regarding the same problem, for example #575
