### ISSUE TITLE
What is the difference between cellUpdate and cellSetup?

### ISSUE THREAD

**Issue by Maxcucurbit** [xmartlabs/Eureka#2227]
What is the difference between cellUpdate and cellSetup? Why is it invalid to set cell.textLabel.textColor in cellSetup, but it works in cellUpdate.

**Comment by mats-claassen** [comment]
`cellSetup` is run once, after creating the cell. Some attributes like textColor might be reset after that for example to show highlighted status. 

`cellUpdate` is called each time the cell is updated (aka `tableView(cellForRowAt: indexpath)` method)

You can see this in the [README](https://github.com/xmartlabs/Eureka#callbacks-list)
