### ISSUE TITLE
TimePickerRow is undeletable in MultivaluedSection

### ISSUE THREAD

**Issue by Nikitaxub** [xmartlabs/Eureka#2228]
Hi **Eureka Team**!
I need several Time args for my form. I used MultivaluedSection with TimePickerRow in first (because one Time arg should be in all cases) and multivaluedRowToInsertAt.

My code below
```
form
+++ MultivaluedSection(multivaluedOptions: [.Insert, .Delete],
                       header: "Bedtimes",
                       footer: "Add the timing of the medication, if necessary") {
    $0.addButtonProvider = { section in
        return ButtonRow(){
            $0.title = "Add new bedtime"
        }
    }
    $0.multivaluedRowToInsertAt = { index in
        return TimePickerRow() {
            let formatter = DateFormatter()
            formatter.dateFormat = "HH:mm"
            let someDateTime = formatter.date(from: "09:00")
            $0.value = someDateTime
        }
    }
    $0 <<< TimePickerRow() {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm"
        let someDateTime = formatter.date(from: "09:00")
        $0.value = someDateTime
    }
}
```
I can't delete any Row.
<img width="323" alt="Screenshot 2022-09-09 at 11 00 34" src="https://user-images.githubusercontent.com/38690643/189281622-6588abf8-aacd-42f2-9183-6d246a78126c.png">

Next I changed TimePickerRow to e.g TimeRow for first Row:
```
$0.multivaluedRowToInsertAt = { index in
    return TimePickerRow() {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm"
        let someDateTime = formatter.date(from: "09:00")
        $0.value = someDateTime
    }
}
$0 <<< TimeRow() {
    let formatter = DateFormatter()
    formatter.dateFormat = "HH:mm"
    let someDateTime = formatter.date(from: "09:00")
    $0.value = someDateTime
}
```
What I see:
TimeRow is deletable;
<img width="248" alt="Screenshot 2022-09-09 at 11 16 44" src="https://user-images.githubusercontent.com/38690643/189283986-f055c910-0423-47d3-b004-5f47f1ee1341.png">
TimePickerRow is deletable if TimeRow is being prepared for deletion;
<img width="245" alt="Screenshot 2022-09-09 at 11 13 16" src="https://user-images.githubusercontent.com/38690643/189283745-241ebaf3-83c6-419f-a010-d67920ea2afa.png">
TimePickerRow is undeletable again if TimeRow isn't being prepared for deletion (w/o screenshot).

Same thing then first Row is TimePickerRow and TimeRow in multivaluedRowToInsertAt.

 - Device: iPhone 12 mini (or it's simulator)
 - OS: iOS 15.6
 - Eureka Version 5.3.6
 - Xcode version 13.4.1

**Comment by mats-claassen** [comment]
Hi, I copied your first code into one of the examples and the TimePickerRow is deletable, as you can see in the screenshot below. Might there be anything else you are adding in your code that breaks this? 
<img width="386" alt="Screen Shot 2022-09-29 at 08 57 02" src="https://user-images.githubusercontent.com/8573865/193025205-72585a9a-7b76-44e3-b994-f44dede0970c.png">

--------------------
And if I press the (-):

<img width="392" alt="Screen Shot 2022-09-29 at 08 57 23" src="https://user-images.githubusercontent.com/8573865/193025312-fb4c556f-a15f-4e2b-a38b-3e19c4acac46.png">

**Comment by Nikitaxub** [comment]
I don't understand why it didn't work for me for several days in a row. And when I had to go to another country, I checked after your answer and everything is OK)
Thank you.
