### ISSUE TITLE
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib

### ISSUE THREAD

**Issue by ningkexin** [xmartlabs/Eureka#2232]
**Describe the bug**
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib
**Expected behavior**
after add ` libswiftCoreGraphics.tbd`
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib
  Referenced from: /private/var/containers/Bundle/Application/56175BE0-DE65-4E45-91DD-AB23A48C54B8/xxxx.app/Frameworks/CropViewController.framework/CropViewController
  Reason: image not found
(lldb) 

**Screenshots**
<img width="408" alt="image" src="https://user-images.githubusercontent.com/17719524/192923809-f4708936-c356-4bb9-8ad7-a70f438875a3.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/17719524/192923828-5643c7cf-b13f-4874-a7fa-ae3ce204b74f.png">

**Versions (please complete the following information):**
 - Device: iPhone11
 - OS: iOS12.01
 - Eureka Version 2.6.1
 - Xcode version 14.0.1

**Comment by mats-claassen** [comment]
I don't see how this is related to Eureka. Also there is no Eureka version 2.6.1

**Comment by ningkexin** [comment]
@mats-claassen
