### ISSUE TITLE
Scrolling Bug

### ISSUE THREAD

**Issue by AlexEdunov** [xmartlabs/Eureka#224]
Looks like after keyboard disappearing form's scroll view has wrong content size.

Take a look at this video:
https://youtu.be/IR9xmNApPRU

Code:

    override func viewDidLoad() {
            super.viewDidLoad()
            
            form +++ Section(NSLocalizedString("Сменить пароль", comment: ""))
                <<< PasswordRow("current_password") { row in
                    row.title = NSLocalizedString("Текущий пароль", comment: "")
                } <<< PasswordRow("new_password") { row in
                    row.title = NSLocalizedString("Новый пароль", comment: "")
                } <<< PasswordRow("new_password_confirmation") { row in
                    row.title = NSLocalizedString("Новый пароль еще раз", comment: "")
                } <<< ButtonRow("change_password") { row in
                    row.title = NSLocalizedString("Сменить пароль", comment: "")
                    row.cellUpdate({ (cell, row) -> () in
                        cell.textLabel?.textColor = UIColor.hx_colorWithHexString("2176AF")
                    })
            }
        }

**Comment by mats-claassen** [comment]
Hi, seems video is private.

**Comment by AlexEdunov** [comment]
Sorry. I fixed that.

**Comment by mtnbarreto** [comment]
@AlexEdunov Thanks for reporting the issue. Should be fixed now!

**Comment by 99xs** [comment]
Hi there,

There still seems to be an issue. Look at this video too: https://youtu.be/0Y7GNbXe3LM

The code I'm using is this one:

    func createForm() {
        EmailRow.defaultCellUpdate = {cell,row in
            cell.preservesSuperviewLayoutMargins = false
            cell.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
            cell.layoutMargins = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)
        }
        
        PasswordRow.defaultCellUpdate = {cell,row in
            cell.preservesSuperviewLayoutMargins = false
            cell.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)
        }
        
        form +++=
            
            Section("Sign In")
            
            <<< EmailRow("email") {
                $0.title = "Email:"
            }
            
            <<< PasswordRow("password") {
                $0.title = "Password:"
        }
    }

**Comment by mvorisis** [comment]
maybe this will help you #703
