### ISSUE TITLE
Any rule to validate special characters/ numbers in text field in a cell

### ISSUE THREAD

**Issue by Mbhatishere** [xmartlabs/Eureka#2247]
Hi, Is there any rule to validate special characters/ numbers in text field in a cell. I am trying to put validations for a person's name but I don't see any rule which stops him from entering special characters in the field.

Xcode 14.2, iOS 16

**Comment by mlorenze** [comment]
Hi! you can create custom regex rules like you can see in this example:

`<<< TextRow() {
          $0.title = "Contains Lowercase"
          $0.add(rule: RuleRegExp(regExpr: "^.*?[a-z].*?$"))
          $0.validationOptions = .validatesOnChangeAfterBlurred
  }`
  
 You have to create a **RuleRegExpr** instance with the specific _regExpr_ that you need.
