### ISSUE TITLE
Bug in iOS 17 Crash app

### ISSUE THREAD

**Issue by AlexArroyoV** [xmartlabs/Eureka#2251]
When opening the controller that contains the custom rows that we use with eureka, the controller opens but automatically sends a crash in the template but it does not say more info and image of the crash.

**Screenshots**
<img width="806" alt="Captura de pantalla 2023-12-01 a la(s) 18 10 08" src="https://github.com/xmartlabs/Eureka/assets/99345306/04ff75a5-ceec-4f2c-9ad4-c64d446f7ac9">

![sssss](https://github.com/xmartlabs/Eureka/assets/99345306/36f332dc-42a1-4f0e-890a-d4f276412ab1)

**Versions (please complete the following information):**
 "deviceModel" : "iPhone14,2",
  "osVersion" : "17.1.1",
  "locale" : "es-MX",
  "carrier" : null,
  "timezone" : "America/Mexico_City",
  "architecture" : "arm64e",
  "connectionStatus" : "MOBILE_DATA",
  "pairedAppleWatch" : "",
  "appUptimeMillis" : null,

 - Eureka 'Eureka', '~> 5.3.6'
 - Xcode version [14.3.1]

**Comment by santicarmo31** [comment]
@AlexArroyoV are you still facing this issue?
