### ISSUE TITLE
Apple privacy manifest file requirement

### ISSUE THREAD

**Issue by jmedtgit** [xmartlabs/Eureka#2254]
Hi, can you pls add the privacy manifest file to Packages.swift as required by Apple for 3rd party SDKs? https://developer.apple.com/support/third-party-SDK-requirements/

According to this requirement, all 3rd party SDKs need to have the privacy manifest file, otherwise apps that include them will be rejected for app submission starting May 1st, 2024.

Thanks.

**Comment by jmedtgit** [comment]
Hi, can you pls add the privacy manifest file to Packages.swift as required by Apple for 3rd party SDKs? https://developer.apple.com/support/third-party-SDK-requirements/

According to this requirement, all 3rd party SDKs need to have the privacy manifest file, otherwise apps that include them will be rejected for app submission.

Thanks.

**Comment by bCastro1** [comment]
I second this request..  with this new requirement, app submissions will be rejected without it. This May 1 deadline is coming up quick.

**Comment by mlorenze** [comment]
We are working on this issue soon.

**Comment by SaiChinthakuntla** [comment]
+1 to above. Glad you started working.

**Comment by muruganandham** [comment]
Any latest update on this?

**Comment by mlorenze** [comment]
The Manifest was added. Until the release comes out, you can use the master branch.
