### ISSUE TITLE
New release build with privacy manifest

### ISSUE THREAD

**Issue by jmedtgit** [xmartlabs/Eureka#2257]
First, thank you for adding the privacy manifest file per https://github.com/xmartlabs/Eureka/issues/2254

Can we pls have an official release build with privacy manifest file? We are using Swift Package Manager to integrate Eureka SDK.  Our app needs to be submitted for FDA approval, and FDA requires us to use and specify an official release version number for all 3rd party SDK integrated.

Thanks.

**Comment by SaiChinthakuntla** [comment]
Can we please get official release version?
I am working for an medical app and this needs FDA approval too.

**Comment by mlorenze** [comment]
Hi, 5.5.0 is available in SPM.
