### ISSUE TITLE
Multiple check forms in a 'row' (custom row, custom cell)

### ISSUE THREAD

**Issue by sureshjoshi** [xmartlabs/Eureka#23]
I want to have multiple check boxes in the same 'row' or same 'UI control'. I think this is similar to the Weekdays checkbox in the examples, but is there a default control which will sit several checkboxes next to each other?

![multchoice](https://cloud.githubusercontent.com/assets/3823045/10375828/9099955a-6dc8-11e5-97ac-dc6b4d5d7886.png)

**Comment by mtnbarreto** [comment]
@sureshjoshi 
Eureka doesn't provide such multiple checkbox control by default. However you can easily create it by following this guide: https://github.com/xmartlabs/Eureka#how-to-create-custom-rows-and-cells--

Eureka example project could also be helpful, in particular `WeekDayRow` that is created using a xib file.

Let me know if you get stuck at some point.
