### ISSUE TITLE
Each imageRow requires 20-30 MB of memory to use

### ISSUE THREAD

**Issue by btanner** [xmartlabs/Eureka#233]
I am testing with the iPad and iPhone simulator, and my app has _lots_ of images.

I noticed app was at 150 MB of memory usage while testing, only selecting a few photos from the image library in the simulator.

I'm totally a newbie with ios programming, but I imagine there is a way naturally make a small thumbnail for the row graphic and retrieve the "address/ID" of the actual photo in the library when trying to get form contents.

I'll update here if I make any progress on implementing that.

**Comment by mtnbarreto** [comment]
Image row has moved to https://github.com/EurekaCommunity/ImageRow.
