### ISSUE TITLE
Any idea on Google address autocomplete implementation?

### ISSUE THREAD

**Issue by billymwlei** [xmartlabs/Eureka#236]
Any idea in which way to start?
this involved a add-in table view for the possible address and the delegation point back to the vc.

**Comment by weyert** [comment]
@billymwlei Not sure, if you still need but you could consider using my solution. Replace the logic with the appropriate call for Google Places API:

``import UIKit
import Eureka
import CoreLocation
import MapKit

/**
 * ExternalViewPickerCell
 */
public class ExternalViewPickerCell : Cell<CLLocation>, CellType {
    
    public required init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        height = { BaseRow.estimatedRowHeight }
    }
    
    public override func setup() {
        super.setup()
        accessoryType = .DisclosureIndicator
        editingAccessoryType = accessoryType
    }
    
    deinit {
    }
    
    public override func update() {
        super.update()
        selectionStyle = row.isDisabled ? .None : .Default
        detailTextLabel?.text = row.displayValueFor?(row.value)
    }
    
    public override func didSelect() {
        super.didSelect()
        row.deselect()
    }
}

/**
 * _ExternalViewPickerRowProtocol
 */
public protocol _ExternalViewPickerRowProtocol {
    
    typealias ReturningValueType
    
    var onPresentCallback: ((FormViewController)->())? { get set }
    var onCompletionCallback: ((ReturningValueType)->())? { get set }
}

/**
 * _ExternalViewPickerRow
 */
public class _ExternalViewPickerRow: Row<CLLocation, ExternalViewPickerCell>, _ExternalViewPickerRowProtocol {

    public typealias ReturningValueType = CLLocation

    public var onPresentCallback: ((FormViewController)->())?
    public var onCompletionCallback: ((ReturningValueType)->())?
    
    required public init(tag: String?) {
        super.init(tag: tag)
    }
    
    public func onPresent(callback: (FormViewController)->()) -> Self {
        onPresentCallback = callback
        return self
    }
    
    public func onCompletion(callback: (ReturningValueType)->()) -> Self {
        onCompletionCallback = callback
        return self
    }
    
    public override func customDidSelect() {
        super.customDidSelect()
        if !isDisabled {
           self.onPresentCallback?(cell.formViewController()!)
        }
    }
}

/**
 * LocationRow
 */
public final class LocationRow: _ExternalViewPickerRow, RowType {
    
    public var locationName : String?
    
    required public init(tag: String?) {
        super.init(tag: tag)

        self.displayValueFor = { [unowned self] value in
            
            if let locationName = self.locationName {
                return locationName
            }
            
            guard let v = value else {
                return "N/A"
            }

            return self.value!.description
        }
        
        onCompletion { [unowned self] actualValue in
            self.value = actualValue
            self.updateCell()
        }
        
        onPresent { [unowned self] formViewController in
            
            let placePicker = PlacePicker()
            placePicker.selectPlace("") { (selectedPlace) -> () in
                self.locationName = selectedPlace.name
                self.onCompletionCallback?(selectedPlace.location)
            }
        }
    }
}``

**Comment by weyert** [comment]
@mtnbarreto: I attempted to make it a bit more generic but I don't know I can find a way a good way. I would have wanted to `public final class LocationRow: _ExternalViewPickerRow<CLLocation>` instead of the current code but I didn't get that working.

What do you think of it? It's my approach to allow callback based selection of content without being forced to have a UIViewController like with the current `PushSelector`. The above code allows to show the Google Places picker as they have a callback approach like my `PlacePicker`.

**Comment by RafaelRViana** [comment]
I'm also trying to put Google Places Autocomplete into an Eureka row. Did you get it? What is supposed to have in PlacePicker class?

**Comment by weyert** [comment]
Hmm, I suppose you could replace it the class related to the Google Places Autocomplete one? I only have been using the Place Picker component from Google Places. Not the autocomplete one. I guess you could instantiate the view controller and present it?

**Comment by mats-claassen** [comment]
[GooglePlacesRow](https://github.com/EurekaCommunity/GooglePlacesRow) is such an implementation.

**Comment by pouriaalmassi** [comment]
Old thread but I used the following one, with some modifications, which worked well for my particular needs. 

https://github.com/MadGeorge/EurekaAddressAutocompliteRow
