### ISSUE TITLE
Feature Request - Make 2 functions public in Core.Swift

### ISSUE THREAD

**Issue by btanner** [xmartlabs/Eureka#237]
I apologize for polluting the issues list as I work through learning Eureka and iOS/Swift all at once.

Let me tie it together.

I request that in Core.swift, the following 2 functions be made public:
public func createController
public func presentViewController

This seems to be necessary in order for me to create my own version if ImageRow.

With my own ImageRow, I have resolved my issues:
#233 
#228

**Comment by mtnbarreto** [comment]
@btanner done!
Could you please provide your ImageRow code implementation? In particular share your solution for  #233 y #228.

**Comment by btanner** [comment]
The code I posted on #228  works fine as is to clear the photo.

The thumbnail issue for #233  is more tricky.   I haven't found a way to hook into the guts of Eureka to intercept the return value from either picking images from the photo gallery or the camera directly. All I have been able to do is lame stuff like setting a flag when the row is selected "imageMaybeChanged" and then looking for that flag on customUpdateCell and generate a thumbnail.

It's all gross right now though, nothing anyone would want to copy.  I'm saving a full-sized version of the photo to the Documents directory for a later dropbox sync, so it's ok to just store a little thumbnail in the row. However, if someone clicks the picker and doesn't follow through, my imageMaybeChanged flag will be set, which means next time customUpdateCell gets called I have to do stupid tricks to tell if value is a new image, or just a previous thumbnail.

I also need to find a good way to call UIImageWriteToSavedPhotosAlbum, but am not sure how to tell if the image was taken with the camera or selected from the album already.

I don't know much about this part of things, so let me know fi you have any suggestions.

I have done some other stuff with validation, and doing a multi-level hide/show of fields based on a stack of conditions (I have a very powerful "Builder" helper for making complex multi-level forms which hide/how portions depending on what is selected), but it's all very fresh still.

**Comment by btanner** [comment]
@mtnbarreto  Hi. Not sure if you would have received earlier comment. 

So, looks like the image gets picked using ImagePickerController.

As you surely know, the picture comes back in a dictionary:
didFinishPickingMediaWithInfo info: [String : AnyObject]

In the simulator, the dictionary looks as follows when picking one of the built-in images:
[\"UIImagePickerControllerMediaType\": public.image, \"UIImagePickerControllerOriginalImage\": <UIImage: 0x7f9f50fd8af0> size {3000, 2002} orientation 0 scale 1.000000, \"UIImagePickerControllerReferenceURL\": assets-library://asset/asset.JPG?id=ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED&ext=JPG]"

If there was a way to get that info passed or stored to a place where a user could access it, then you could make some pretty nifty imageRows because you could treat Camera different from library, create links to library and show thumbnails, etc.  I don't think there is a way to do that now.

Thoughts?

**Comment by btanner** [comment]
@mtnbarreto 
Ok.  Challenge accepted.  I'm new to Swift and IOS, so maybe this is a stupid way to do it.  I used associated objects in Objective C and a public Extension to UIImage to add a property to UIImage called pickerDict.  It allows you to basically attach the picker information to the UIImage so that it can be retrieved later in the custom row implementation.

Maybe overkill, or bad b/c not pure Swift, but I was downright amazed when my code could read pickerDict out of the row.value.

I have attached a copy of Controllers.swift with the extension. It's all in the last 60 lines of the file.

[Controllers.swift.zip](https://github.com/xmartlabs/Eureka/files/122613/Controllers.swift.zip)

**Comment by btanner** [comment]
I take this all back.  I've learned a lot this week.  Now that I have a handle on how image picking works, I see that I Can just make my own ImagePickerController for my custom ImageRow and do whatever I want.  This gives me a lot more power to control flow and the whole pickerDict thing (which was an interesting exercise) is totally not required.
