### ISSUE TITLE
Cannot reference TextAreaRow

### ISSUE THREAD

**Issue by ageorgios** [xmartlabs/Eureka#24]
form +++ Section("URL")
                <<< TextAreaRow("URL") {
                    $0.tag = "theURL"
                    $0.value = self.entry.url
                    }.onChange{ [weak self] row in
                        //do something
                }

            let urltextrow: TextAreaRow = self.form.rowByTag("theURL")!
            urltextrow.value = url.absoluteString

the value of the TextAreaRow cannot be changed after referencing by  let urltextrow: TextAreaRow = self.form.rowByTag("theURL")!

**Comment by mtnbarreto** [comment]
@ageorgios 
I the table view was already displayed you should invoke 
```swift
urltextrow.updateCell()
```
to update the cell.

Taking a look at the code you posted, it doesn't make sense to initialize a row using `URL` as row tag and then change it to `theURL `.

**Comment by ageorgios** [comment]
thanks for the answer, it needed the updateCell()
as for theURL just a typo
