### ISSUE TITLE
Need way to remove a date with date picker rows

### ISSUE THREAD

**Issue by michaelbina** [xmartlabs/Eureka#252]
Unless I'm missing something, I'm not seeing a way to cancel or remove a date selection after one has been picked from any of the date picker rows.  I essentially need a way to set the value to nil and give a clear way for the user to do this.

Here is what the DateInlineRow looks like now:

<img width="370" alt="screen shot 2016-02-10 at 11 13 11 am" src="https://cloud.githubusercontent.com/assets/528845/12958649/8b7e59d0-cfe7-11e5-980f-7784c996c959.png">

Here is a mock for a possible ui solution but this is by no means the right or best solution so feel free to modify:

<img width="370" alt="screen shot 2016-02-10 at 11 13 11 am" src="https://cloud.githubusercontent.com/assets/528845/12958758/1cf7501a-cfe8-11e5-91ab-069585e575bd.png">

**Comment by btanner** [comment]
+1 for this.
Also for TimeRows

**Comment by mtnbarreto** [comment]
A good solution could be adding a small (red) cross image as a accessory view when the row value is different than nil. @btanner @michaelbina What do you think? 

This is fully feasible with the current feature set provided by Eureka.

**Comment by igordeoliveirasa** [comment]
is there any other solution?

**Comment by iguron** [comment]
Any update or workaround for this?
