### ISSUE TITLE
PushRow with search (performance question)

### ISSUE THREAD

**Issue by Chiliec** [xmartlabs/Eureka#256]
I added searchBar to PushRow and in delegate method do:
```swift
//MARK: - UISearchBarDelegate

public func searchBar(searchBar: UISearchBar, textDidChange searchText: String) {
    for row in form.allRows {
        let visible = searchText.isEmpty || (row.title ?? "").localizedCaseInsensitiveContainsString(searchText)
        row.hidden = Condition(booleanLiteral: !visible)
        row.evaluateHidden()
    }
}
```
but `evaluateHidden()` executes so slow, especially it feels when I have many rows. Please, promt me what I doing wrong.

**Comment by mtnbarreto** [comment]
give this code a try, not sure if it works...

```swift
public func searchBar(searchBar: UISearchBar, textDidChange searchText: String) {
    for row in form.allRows {
        let visible = searchText.isEmpty || (row.title ?? "").localizedCaseInsensitiveContainsString(searchText)
        row.hidden = Condition(booleanLiteral: !visible)
    }
   tableView?.reloadData()
}
```

**Comment by Chiliec** [comment]
It was a first thing what I tried. It doesn't work :(

**Comment by mats-claassen** [comment]
Hey @Chiliec what about this issue? Is it still so slow with the latest version? Have you found a workaround?

**Comment by bithavoc** [comment]
I shared my implementation of a Searchable PushRow [here](http://bithavoc.io/blog/2016/07/04/eureka-search-push-row/), since the controller is implemented from scratch and is not descendant from `FormViewController` is far more performant than recreating the whole form, section and items everytime the user types a query in the search box via `updateSearchResultsForSearchController`.

**Comment by mats-claassen** [comment]
This issue is very similar to #399 .
And I think this is definitely something that should be implemented using a simple UITableView and not using `hidden` variable.

Also maybe [this row](https://github.com/EurekaCommunity/GooglePlacesRow) can help with some ideas for in-place selectors

**Comment by mats-claassen** [comment]
The impolementation provided by @bithavoc is a good example of how to accomplish this.

**Comment by allaire** [comment]
@bithavoc Hey man, thanks for your blog article, but I can't get it to work with the latest Eureka release. Did you keep it updated in your code and wiling to share a gist? Thanks!

**Comment by bithavoc** [comment]
@allaire need to update the blog post, this is for swift 3 https://gist.github.com/bithavoc/f5c9d06f024bfb5d9d3bd9452b94849f

**Comment by allaire** [comment]
@bithavoc Thanks for this! Is it compatible with the latest Eureka version? Looks a bit more "complex", or at least has more lines :)

**Comment by bithavoc** [comment]
@allaire yes is a bit more complex, unlike the first version of Eureka in the latest there is no way to inherit from Table view controller so I had To create one from scratch. But it works, I've been using that exact gist in my app since I migrated to Swift 3... In production.

**Comment by allaire** [comment]
@bithavoc 🤘 Thanks so much for this, will give it a spin. Finding hard to wrap my head around Eureka advanced customization.

**Comment by maxhanglin** [comment]
Guys, if anyone interested, I just modified the gist from @bithavoc to follow the simpler `SearchablePushRow` found in the original post from the author:
http://bithavoc.io/blog/2016/07/04/eureka-search-push-row/

Code:
https://gist.github.com/maxhanglin/032033405a2717a4cdd445bf5190b65f

It can be used as:
```
<<< SearchablePushRow<Contact>("person") { row in
    row.options = contactsList
}
```

Contact, in this example, needs to be:
```
public class Contact: CustomStringConvertible, Equatable, SearchableItem { ... }

**Comment by RalphEBoy1971** [comment]
I am fairly new to using Eureka forms...Does anyone have a working example of this (that they can share) that can show it in action?

**Comment by cbsmith89** [comment]
@maxhanglin seconding @RalphEBoy1971's request.

I'm having dififculty implementing the _SearchablePushRow_ in my Eureka form after having imported your _eureka_swift_3:composable_search_row.swift_ file into my project folder.

Can you please provide a sample of the proper project structure, as well as a sample _FormViewController.swift_ file which incorporates your SearchablePushRow? It would be much appreciated!
