### ISSUE TITLE
detailTextLabel : how to show it?

### ISSUE THREAD

**Issue by andrealufino** [xmartlabs/Eureka#257]
How can I do to show the detailTextLabel of the cell? I can't figure out how to do it

**Comment by mtnbarreto** [comment]
@andrealufino Could you extend or elaborate on what you want to accomplish?

Please make sure you follow the contribution guide providing environment, row type, code example and anything you think could be useful to provide a fast support.
 https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md

**Comment by andrealufino** [comment]
@mtnbarreto You're right, sorry. I'm using the last version of Eureka. I need to show the detail label, the classic detail label under the title label. I don't know how to do it. I was able to show the detail label on the right of the cell. I'm using a CheckRow currently, but I think this is applicable to all rows (almost).

**Comment by mtnbarreto** [comment]
:+1:  Thanks for not taking me wrong! 

This code should work....
```swift
let row = CheckRow() {
                     $0.title = "Your title"
                     $0.value = true
                     $0.cellStyle = UITableViewCellStyle.Subtitle
                }.cellUpdate { cell, _ in
                     cell.detailTextLabel?.text = "Hi There"
                }
```

**Comment by korgx9** [comment]
Doesn't work for PushRow (

```
PushRow<String>.defaultCellSetup = { cell, row in
            row.cellStyle = UITableViewCellStyle.subtitle
            cell.height = { 60 }
}
```

**Comment by mats-claassen** [comment]
Try doing that in the `defaultRowInitializer` instead of `defaultCellSetup`.

**Comment by korgx9** [comment]
Thanks it worked! 👍
