### ISSUE TITLE
PostalAddressRow: Native Country Selector

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#258]
Maybe the PostalAddress Row should support the selection of a country instead of typing it in as String. I'm thinking of a SelectorController displaying a list of translated country names.

And if a country was selected, it will return the ISO countryCode for it.

Thoughts?

**Comment by mats-claassen** [comment]
I am not sure this is in our scope. It seems to me that it is more like a custom row, as you will probably want to have a custom design for the address row as well.

**Comment by marbetschar** [comment]
Oh, ok I can see your concern.

Do you have any idea how we could provide the possibility to use the built in PostalAddressRow but replace the country input field with a selector?

So folks do not have to add a fully customized PostalAddressRow just for country selection?

**Comment by marbetschar** [comment]
@mats-claassen as I'll look into #423 these days, any chance a further enhancement by providing a country selector equally to the native iOS one would make into the official release?

In my opinion this would make the PostalAddressRow even more useful - but maybe this behaviour should be configurable?

![hlfxe](https://cloud.githubusercontent.com/assets/392542/15370821/eea8b818-1d38-11e6-9b1c-70ce06d9e19b.png)

**Comment by rufferto** [comment]
The correct way to do this would be a redesigned PostalAddressRow which used xib files for it's cell layout. The country would be separate PickerRow which would swap in the appropriate layout based on the selection. To support addresses internationally the xib file would be localized. This would eliminate the need for placeholder strings and much of the auto layout layout being managed in code right now. It seems from browsing the code the missing piece is a protocol to map the field order back to the NavigationAccessoryView.

**Comment by mats-claassen** [comment]
PostalAddressRow has been moved to EurekaCommunity and there is [an issue](https://github.com/EurekaCommunity/PostalAddressRow/issues/3) regarding this
