### ISSUE TITLE
Custom Class for PushRow

### ISSUE THREAD

**Issue by mathmatrix828** [xmartlabs/Eureka#26]
PushRow does not seem to have the .action attribute found in XLForm. I'm guessing this is a feature that's in the works?

**Comment by mathmatrix828** [comment]
Using workaround ButtonRow().onCellSelection: { self.presentViewController: }

**Comment by mats-claassen** [comment]
You have to use the `presentationMode` of the row
Have a look here: https://github.com/xmartlabs/Eureka#custom-presenter-row
