### ISSUE TITLE
Are there storyboard elements for Eureka forms?

### ISSUE THREAD

**Issue by bdrelling** [xmartlabs/Eureka#262]
I have been looking into this library and it seems extremely comprehensive. I have the example app on my phone and I've been searching through guides and blogs looking at what it can do.

I am unable to figure out if I can use Eureka outside of `UITableViewController`s, such as if I'm only showing 2-3 fields somewhere in a bigger form, and whether or not I can set a placeholder for where the Eureka form would go as such in the Storyboard, since we have a mix of IB and Programmatic view creation.

If neither are the case, I think this would make for a good issue/feature to be worked on moving forward. (That's why I chose to post here instead of Stack.)

**Comment by mtnbarreto** [comment]
Each Eureka form controller should be or extend `FormViewController` class. 
In case you have a form that doesn't cover the whole screen you can add a child view controller using SB and this child view controller should be your Eureka form controller.

Optionally you can connect `tableView` outlet and set up the layout constraints using storyboard. By doing that you can also change the size of the table view allowing you to add more views on the same view controller in addition to the table view.

Eventually at some point in the future we would allow to create eureka forms not extending from FormViewController and using your own custom view controller. From my understanding this is not a limitation so the only reason we may do it is to improve eureka architecture.

**Comment by mtnbarreto** [comment]
There are no storyboards elements. 
You can only specify the view controller and the UITableView through storyboards. 
Apart of that you can also design any custom row using xib files.

**Comment by alper** [comment]
That FormViewController subclassing requirement does make it hard to use these form elements in different contexts.
