### ISSUE TITLE
Please, avoid big files - daring request :)

### ISSUE THREAD

**Issue by VilemKurz** [xmartlabs/Eureka#268]
First thank you for a great library. I am getting grasp on it, but what I find totally disrupting is those large files, each containing multiple classes. It is very hard (at least for me) to read through them to find some information. Even generated headers do not work on such big files. I propose, for the sake of readability and clarity of the code, to divide the code, file per class. What is the point to have several thousand lines long files, anyway?

**Comment by mikaoj** [comment]
:+1:

**Comment by mats-claassen** [comment]
Hi @VilemKurz, we will do this in the (hopefully) near future.

**Comment by mtnbarreto** [comment]
done!
