### ISSUE TITLE
Global form customization ("theme") setup

### ISSUE THREAD

**Issue by akabab** [xmartlabs/Eureka#269]
Would be great to be able to setup a global style configuration for the form
- global background color
- cells background color
- cells title & detail (+ placeholder) colors
- cell selected background color
- section header background color
- section header title color
- keyboard color
- interactivity color (buttons, links .., active value)

+ eventually font settings

I'm currently making an app with a dark theme

**Comment by mtnbarreto** [comment]
similar to #38
