### ISSUE TITLE
How do I change the height of a SegmentedRow<String>() controller?

### ISSUE THREAD

**Issue by RafaelGadret** [xmartlabs/Eureka#27]
Hello: maybe a silly question, but how do I change the height of a SegmentedRow<String>() controller? I try a lot of things, like:
...
<<< SegmentedRow\<String\>() {
$0.options = ["Cancel Edit", "Skip", "Done"]
let frame = UIScreen.mainScreen().bounds
$0.cell.segmentedControl.frame = CGRectMake(frame.minX + 10, frame.minY + 50,frame.width - 20, frame.height*0.5)
}
...
Can you help me? Thanks!

**Comment by AtharvaVaidya** [comment]
Maybe the reason it isn't working is because the setup method of the segmentedRow supersedes your code. 
Try subclassing SegmentedRow and then overriding the setup function. Set the frame you want in the setup function.

```Swift
public class CustomSegmentedCell: SegmentedCell
{
  override func setup()
  {
    //Code
  }
}
```
Look at the Readme.md for more info on how to make custom rows.
