### ISSUE TITLE
NavigationBar not appearing ?

### ISSUE THREAD

**Issue by ariff20** [xmartlabs/Eureka#272]
Why is the navigation bar not appearing when I select the multipleselectorrow ? There's no way to go back from the options table view

**Comment by mtnbarreto** [comment]
Hi @ariff20 Please follow these guidelines to contribute:  https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md

**Comment by mats-claassen** [comment]
[Here](http://stackoverflow.com/questions/35459392/navigation-bar-not-appearing) is the question with an answer on StackOverflow.
