### ISSUE TITLE
Image Background

### ISSUE THREAD

**Issue by remirobert** [xmartlabs/Eureka#276]
Hello, I wanted to know if it was possible to add an image in background. Or to set the color of the UITableView to clear, to see my UIImageView in background.

Thanks in advance.

**Comment by mats-claassen** [comment]
Sure you can. Just add an imageView behind the tableView on your storyboard and set the tableView's backgroundcolor to `clearColor`.
If you also want the cells of the table to be traslucent then you can do that like this:
```
 override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = super.tableView(tableView, cellForRowAtIndexPath: indexPath)
        cell.backgroundColor = .clearColor()
        return cell
    }
```

**Comment by mtnbarreto** [comment]
I suggest you to also play with table view `backgroundView` apart of setting `.clearColor()` to each cell backgrpundColor property.
