### ISSUE TITLE
ActionSheetRow causes strange behaviour

### ISSUE THREAD

**Issue by timvermeulen** [xmartlabs/Eureka#277]
After using an `ActionSheetRow`, the `rightBarButtonItem` of the `navigationItem` loses its font weight. For example, `UIBarButtonSystemItem.Save` uses a bold system font, but it's not bold anymore after I have used an `ActionSheetRow`.

Also, all heights of my rows shrink slightly after using an `ActionSheetRow`. Just a few pixels each.

My current workaround is to use a `PushRow` instead.

**Comment by mtnbarreto** [comment]
Apparently this is not directly related with Eureka. Eureka does not change any external view font.
I can provide a fast and more efficient support if you provide me with a base code to reproduce the issue quickly.
