### ISSUE TITLE
Issue when Eureka rows come into view

### ISSUE THREAD

**Issue by browndev** [xmartlabs/Eureka#28]
I am experiencing an issue at runtime.
Which is throwing:
`````
Could not cast value of type 'Eureka.BaseRow -> ()' (0x10f2b6030) to 'Eureka.SwitchRow -> ()' (0x10f2b6080).
`````
I have experienced this issue even with forms only containing a single standard section and row.
This is most likely an issue with external setup but if you could give me any pointers it would be a great help.

**Comment by mtnbarreto** [comment]
@browndev Could you please post the code that causes the exception?

**Comment by mtnbarreto** [comment]
I've tested it with 

```swift
        SwitchRow.defaultRowInitializer = { row in
            row.value = false
        }
```

and 

```swift
                <<< SwitchRow() {
                        $0.title = "SwitchRow"
                        $0.value = true
                    }
```

and it works as expected.

**Comment by tnwt7** [comment]
@browndev What is your deployment target version?
I started my new project with 9.1 and found exactly the same error as you. But then changed to 8.0 and everything run fine.
Don't know this is the real reason or not, but it solved my problem.

**Comment by real0x0000** [comment]
@browndev What is your Xcode version?
I am using Xcode 7.1 beta and found the same error with you. But when I changed to Xcode 7 everything run fine.

**Comment by tnwt7** [comment]
Seem like @real0x0000 is right. I am using Xcode 7.0.1. I cannot reproduce these error messages in this version of Xcode.

**Comment by mtnbarreto** [comment]
Apparently a swift 2.1 change on how the function type casting works is causing the exception. I will upload a fix shortly.

**Comment by mtnbarreto** [comment]
Now it should work.
It seems that Swift2.1 compiler no longer allows function type downcasting. 
I had to do some tricks to make it work on 2.1 and don't make changes on Eureka public API.
@browndev @tnwt7 @real0x0000 Thanks for helping me reproduce the issue. 🚀

**Comment by tnwt7** [comment]
Thank you @mtnbarreto !
