### ISSUE TITLE
MapViewController annotationview text

### ISSUE THREAD

**Issue by Tripwire999** [xmartlabs/Eureka#280]
Hi,

I would like to know if it is possible to change the text of the Annotation on the MapViewController. Now it's the default Select. But I would lik to localize it.

Check screenshot below:
http://s9.postimg.org/3wk5zjcdb/Screenie.png

Thx!

**Comment by mtnbarreto** [comment]
@Tripwire999 Eureka doesn't have any annotation in MapViewController. 
Are you trying to implement a custom location selector with Eureka?

**Comment by mtnbarreto** [comment]
if you are still experiencing this issue, let me know..
