### ISSUE TITLE
Split up Core.swift into multiple files

### ISSUE THREAD

**Issue by jkereako** [xmartlabs/Eureka#281]
It is difficult to inspect the code of `Core.swift` because there are over 2,000 lines of undocumented code. That file contains definitions for view controllers, structs and classes.

Ideally, every unit ought to be extracted into its own file and grouped together. The Objective-C version of this library, [XLForm][xlform], does exactly that. It was much easier to look-up the source for a particular feature.

[xlform]: https://github.com/xmartlabs/XLForm/tree/master/XLForm/XL

**Comment by mikaoj** [comment]
#268

**Comment by mtnbarreto** [comment]
done!
