### ISSUE TITLE
PushRow/PopOverSelectorRow do not support cell callbacks

### ISSUE THREAD

**Issue by scottrhoyt** [xmartlabs/Eureka#282]
I've noticed that on `master` `PushRow` and `PopOverSelectorRow` do not seem to support the common cell callbacks (e.g. `cellSetup`, `cellUpdate`). This makes them difficult to use in situations where you want to customize the form UI or write your own validation logic (`onChange`).

**Comment by mats-claassen** [comment]
Hi just tried this in the examples and it worked :neutral_face: 
Also the tests should check that and they pass...
What version of Xcode/iOS are you running?

**Comment by scottrhoyt** [comment]
I am using Xcode 7.2.1 and iOS 9.2.1.

The following code produces a compiler error:
```swift
PushRow<String>("string") {
   $0.title = "Strings"
   $0.options = String.allStrings
   $0.cellSetup { }
   $0.cellUpdate { }
}
```
The error complains about the non-existence of `cellSetup` and `cellUpdate`. I've noticed the same for `onChange`.

**Comment by mats-claassen** [comment]
You are right, thanks for pointing out. Meanwhile, we always use it like this, and it works for `PushRow` as well:
```
<<< PushRow<Emoji>() {
            $0.title = "PushRow"
            $0.options = [💁, 🍐, 👦, 🐗, 🐼, 🐻]
            $0.value = 👦
            $0.selectorTitle = "Choose an Emoji!"
      }.cellSetup { cell, row in
              print("hello")
      }
```

**Comment by mtnbarreto** [comment]
it may be a swift issue. I will close it since there is a workaround to adopt and in my opinion is the proper way to use `cellSetup`, `cellUpdate`.
