### ISSUE TITLE
ButtonRow calls onCellSelection even when disabled

### ISSUE THREAD

**Issue by scottrhoyt** [xmartlabs/Eureka#284]

**Comment by mats-claassen** [comment]
I believe all / most of the rows do this. Not sure this is the best behaviour

**Comment by scottrhoyt** [comment]
Is there a recommended way to detect ButtonRow activation and to disable it?

**Comment by mats-claassen** [comment]
I am not sure what you mean? You should check if the row is disabled at the start of the `onCellSelection`:
```
.onCellSelection { cell, row in
         if !row.isDisabled {
               print("Eureka is awesome!")
         }
}
```

**Comment by scottrhoyt** [comment]
What I mean is that as a user, my expectation of disabling a text field is that I cannot edit it. That is how `UITextField` works and also how `TextRow` works. My expectation of a button is that when I disable it, it won't fire. That is how `UIButton` works, but if the recommended way to detect button activation for `ButtonRow` is to use `onCellSelection` then that is not how `ButtonRow` works.

**Comment by mtnbarreto** [comment]
@scottrhoyt this is the only way we found to get onCellSelect notification regardless of the row disabled value.
Basically `onCellSelection ` means `tableView:didSelectRowAtIndexPath`. If you don't want to execute your `onCellSelection` code when the row is disabled you will have to add a `if` condition as @mats-claassen suggested.

**Comment by DenZuck** [comment]
Have a look at sunbohong's answer in this post https://github.com/xmartlabs/Eureka/issues/559
