### ISSUE TITLE
Feature Request: onVisibilityChanged callback

### ISSUE THREAD

**Issue by btanner** [xmartlabs/Eureka#285]
My validation code explicitly ignores all rows that are hidden because their visibility condition isn't met.

When their condition is met, they appear, and are now suddenly eligible for validation, and contributing to the error count of their group if they fail validation.

I can't think of a good way to determine when a row becomes visible.  Would it be possible to add a callback for this (and enabled/disabled as well for symmetry I guess).

**Comment by rlaferla** [comment]
I think you meant: onVisibility no onVisability which requires a government form.  :-)

**Comment by btanner** [comment]
My workaround for this was to set a timer to run validation on regular intervals.

Turns out that's pretty horrific for battery life, so this feature would be a real benefit.

**Comment by btanner** [comment]
This turned out to be pretty simple now that I understand property setting/getting and closures a bit better than when I started.

Changes:
Baserow gets a new property
```swift
	var callbackOnVisChange: (()->Void)?
```

add a public onVisChange under onChange in Core.swift
```swift
	public func onVisChange(callback: Self -> ()) ->Self{
		callbackOnVisChange = { [unowned self] in callback(self) }
		return self
	}
```

Make a didSet observer to hiddenCache on BaseRow
```swift
	private var hiddenCache : Bool = false{
		didSet{
			callbackOnVisChange?()
		}
	}
```

That's all there is to it!

**Comment by btanner** [comment]
I don't suppose you guys would like to add this in. I was away from my project for a year, and I've come back and updated everything from Swift3.  I have my own validator that counts how many visible fields in a section are pass/failing validation, and I use this callback to update the counts and either put a "checkmark" beside the section or put an X with a count.

I have deleted and re-cloned, branched off 3.1.0 added the callback in again.  I would love to just put Eureka on my PodFile and be a happy man, but I'm stuck with forking and loading upstream changes :)

**Comment by mtnbarreto** [comment]
Eureka provides validation supports since 2.0.0 version. https://github.com/xmartlabs/Eureka#validations 
I would recommend you to implement validations using Eureka api. 

> By default Eureka validations only run on visible rows. 

```swift
extension Form {

    @discardableResult
    public func validate(includeHidden: Bool = false) -> [ValidationError] {
        let rowsToValidate = includeHidden ? allRows : rows
        return rowsToValidate.reduce([ValidationError]()) { res, row in
            var res = res
            res.append(contentsOf: row.validate())
            return res
        }
    }
}
```
