### ISSUE TITLE
Convert form.values to json object

### ISSUE THREAD

**Issue by wstudios** [xmartlabs/Eureka#289]
I am trying to post the form values to a PHP file on a server.
I am using the following but getting errors

let values =  form.values()

let jsonData = try NSJSONSerialization.dataWithJSONObject(values, options: .PrettyPrinted)

Thanks.

**Comment by mtnbarreto** [comment]
@wstudios Could you provide more information about which values are contained in values dictionary and the errors you are getting?

**Comment by wstudios** [comment]
Thanks for the reply. I am using tags with each fields so my form.values print is the following:

> ["expenses": Optional(13.67), "mgmt_msg": Optional(""), "meal_lunch": Optional("")]

The error in swift is the following:
>Argument type '[String: Any?]' does not conform to expected type 'AnyObject'

Thanks for the help.

**Comment by mckayryane** [comment]
@wstudios how did you overcome this? I see you have closed the issue. thanks

**Comment by wstudios** [comment]
I decided to get each value by tag instead and unwrap using the following:

Get all form values that was saved.
`let values : Dictionary! = form.values()`

```
 if let miles = values["miles"]! {
   // place miles in an array and send to server..
}
```
