### ISSUE TITLE
FloatLabelRow onChange event not triggered

### ISSUE THREAD

**Issue by orkunbaba** [xmartlabs/Eureka#29]
.....
<<< FloatLabelRow() {
                $0.title = "My Title"
                }.onChange {  row in
                   print(row.value)             
            }
......
in this code onChange is not triggered. When i use TextRow its triggered. is there any solution for this?

regards

**Comment by mtnbarreto** [comment]
@orkunbaba Thank for reporting the issue!

 `FloatLabelRow ` was added as an example and is not provided by default in Eureka. Anyway the issue is fixed now.
