### ISSUE TITLE
Limit number of characters entered in a TextRow

### ISSUE THREAD

**Issue by bharatkrishna** [xmartlabs/Eureka#293]
I would like to limit the number of characters the user enters in a TextRow. How do I accomplish this?

**Comment by bharatkrishna** [comment]
Could someone point me to documentation if this functionality exists? Thanks.

**Comment by mats-claassen** [comment]
We have not tried it, so this is not documented.
Have a look at [this post](http://stackoverflow.com/questions/433337/set-the-maximum-character-length-of-a-uitextfield)

The `FieldCell` calls this method of the formViewController:
```
public func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
    return formViewController()?.textInput(textField, shouldChangeCharactersInRange:range, replacementString:string, cell: self) ?? true
}
```

**Comment by olcayertas** [comment]
Please look at my answer [here](https://github.com/xmartlabs/Eureka/issues/601#issuecomment-513743463).
