### ISSUE TITLE
Show hidden row when specific multi select option(s) is checked

### ISSUE THREAD

**Issue by wstudios** [xmartlabs/Eureka#294]
I have a field that has multiple selections, below I have another row that gets visible only when a specific item is selected. I am using tags but can't figure out how to get it to work. Thanks.

```swift
           $0.hidden = .Function(["meds_observed"], { form -> Bool in
                                      let row: RowOf<String>! = form.rowByTag("meds_observed")
                                      if row.value != "Waking" 
                                })
```

**Comment by mtnbarreto** [comment]
@wstudios  Could you provide meds_observed row specification?

**Comment by wstudios** [comment]
Thank you for your reply, this is my meds reported row

`            <<< MultipleSelectorRow<String>{
                $0.title = "Meds Reported"
                $0.tag = "meds_reported"
                $0.options = ["No Meds", "Upon Waking", "Breakfast, with food", "Morning, not with meal", "Lunchtime, with food", "Mid-day, not with food", "Dinnertime, with food", "Evening, not with food", "Bedtime"]}`

**Comment by mats-claassen** [comment]
@wstudios If that is a MultipleSelectorRow then the value of it will be a Set<T>, in your case Set<String>. Therefore I believe you cannot cast that row as RowOf<String> nor compare its value to a String.
Why don't you try this:
```
if let value = form.rowByTag("meds_observed").baseValue as? Set<String> { 
     if value.contains("Waking") && value.count == 1 {
          print("Hello World")
    }
}
```

**Comment by wstudios** [comment]
Thanks for your help, works great.
