### ISSUE TITLE
Unable to change the height of cell

### ISSUE THREAD

**Issue by marshallYin** [xmartlabs/Eureka#296]
self.tableView?.rowHeight  doesn't work.
by the way,how to setup the textAlignment and textColor of cell
here is my code
    Section()

        <<< ButtonRow() {
            $0.title = "TextRow"
            }.cellSetup { cell, row in
                cell.imageView?.image = UIImage(named: "1")
                cell.textLabel?.textColor = UIColor.grayColor()
                cell.textLabel?.textAlignment = .Right
    }

but it doesn't work

**Comment by mtnbarreto** [comment]
@marbetschar
You can accomplish it by setting up  `BaseRow.estimatedRowHeight` static property.

**Comment by marshallYin** [comment]
I did it by heightForRowAtIndexPath method .
