### ISSUE TITLE
How to use the ButtonCell

### ISSUE THREAD

**Issue by tomasKa** [xmartlabs/Eureka#30]
There are some samples for other rows but ButtonRow is not well explained in the sample project. Would be super nice to have a bit betted documentation for use cases. E.g how I call an action on a button row.

**Comment by tp** [comment]
I use it like this:


Create the button row:
```swift
    ButtonRow() {
        $0.title = "Tap Me!"
        $0.onCellSelection(self.buttonTapped)
    }
```

And provide a handler in your form class:
```swift
    func buttonTapped(cell: ButtonCellOf<String>, row: ButtonRow) {
        print("tapped!")
    }
```

**Comment by tomasKa** [comment]
Thanks, it works!

**Comment by rlaferla** [comment]
How do you call a segue from a ButtonRow?

**Comment by ins0u** [comment]
For a segue

```
ButtonRow("Rows") {
     $0.presentationMode = .SegueName(segueName: "NameOfSegue", completionCallback: nil)
}
```
