### ISSUE TITLE
Issue: Cell highlighting

### ISSUE THREAD

**Issue by Haggan** [xmartlabs/Eureka#302]
There seems to be cases where the closure for onCellHighlighting is not executed when defined when creating a section. Is this a known problem - anyone else experiencing this? 

Also, the standard highlight doesn't seem to work for PickerInlineRow and some others. Is this as intended?

Not sure if this is a bug or I'm doing something wrong.

**Comment by mtnbarreto** [comment]
@Haggan 
Highlighting works slightly different for Inline rows.  
For inline rows `onExpandInlineRow` callback is in charge of performing the default highlighting as you can see in `PickerInlineRow` implementation.

```swift
public final class PickerInlineRow<T where T: Equatable> : _PickerInlineRow<T>, RowType, InlineRowType{
    
    required public init(tag: String?) {
        super.init(tag: tag)
        onExpandInlineRow { cell, row, _ in
            let color = cell.detailTextLabel?.textColor
            row.onCollapseInlineRow { cell, _, _ in
                cell.detailTextLabel?.textColor = color
            }
            cell.detailTextLabel?.textColor = cell.tintColor
        }
    }
..
}
```


Could you elaborate on `There seems to be cases where the closure for onCellHighlighting is not executed when defined when creating a section. Is this a known problem - anyone else experiencing this?` ? What do you mean by `when defined when creating a section` ?

Regards
