### ISSUE TITLE
App crashes after AlertRow becomes first responder

### ISSUE THREAD

**Issue by Opelor** [xmartlabs/Eureka#306]
This is the sequence of what i'm doing and then the crash:

1. Launch app and view loads Form
2. Enter text in TextRow and hit NEXT on iPad keyboard
3. Enter text in another TextRow and hit NEXT on iPad keyboard

Then it Crashes when the AlertRow is becoming the first responder.

The console error prints: "fatal error: Array index out of range"

The behavior I was expecting was that the AlertView displayed the array of options.

Great Lib! :+1:

**Comment by mtnbarreto** [comment]
@Opelor I couldn't reproduce the issue.

Which Eureka version are you using? Could you post the stack trace?

**Comment by Opelor** [comment]
When I was ready to send the stack trace, I found an error on my code. Now it doesn't crash. 

But the behavior I was expecting was that the AlertRow displayed the array of options.

After pressing next in the keyboard the AlertRow doesn't become the first responder and show the options.

But now I feel it isn't a bug. It's like a missing functionality :+1:

Cheers!
