### ISSUE TITLE
form causing memory leak when inside DetailViewController

### ISSUE THREAD

**Issue by cyrus86** [xmartlabs/Eureka#308]
when adding a form to the detail view of a newly created Master-Detail project (xcode7.x), switching between detailview and masterview a couple of times just keeps piling up memory usage.  
the viewDidLoad is called everytime, though i don't really think this is the problem since that's how the xcode template behaves.  
Is this working as intended or is there a way to dispose of the eureka form when the view disappears?

**Comment by mtnbarreto** [comment]
@cyrus86  Could you upload a project to help me reproduce the issue quickly and provide a fast support?

**Comment by cyrus86** [comment]
https://github.com/cyrus86/memLeak/blob/master/memLeakTest/DetailViewController.swift 
it's a basic master-detail template from xcode with one form inserted into the detail view.  
it adds ~2MB of memory usage every time the detailviewcontroller gets called.  

Also: the warning shows up every time:  
> Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.

**Comment by mtnbarreto** [comment]
@cyrus86 Thanks for sharing the project! I haven't had time to look into it yet but i will do it shortly.

**Comment by cyrus86** [comment]
Sure, let me know if there's something I can help with.  
If you don't see a definitive memory leak while switching back and forth between detail- and masterview, let me know. (But really, the only thing I change from the xcode template is the eureka pod).

**Comment by mtnbarreto** [comment]
@cyrus86 It seems you are using Eureka 1.2 which is not the latest version. Take a look here: https://github.com/cyrus86/memLeak/blob/master/Podfile#L6. it should be 
`pod 'Eureka', '~> 1.4'` or master branch version. 

Using master branch code I'm no longer experiencing the memory leak issue. 

Regards

--------------------------------------------------------------------------------------

I have added [ISSUE_TEMPLATE](https://github.com/xmartlabs/Eureka/blob/master/.github/ISSUE_TEMPLATE.md) and [contributing guide](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md) to avoid this kind of issues. Please follow them before contributing.

**Comment by cyrus86** [comment]
Oh, so sorry for having troubled you with that.  
Not sure how it got to be 1.2. I'll check my actual project tomorrow, but I guess that was it.  
Thanks so much!
