### ISSUE TITLE
Leaving a pickerView while pickerView is scrolling leads to crash

### ISSUE THREAD

**Issue by IncredibleDucky** [xmartlabs/Eureka#309]
Line 614 in Cells.swift crashes due to the force unwrap taking place. 
   ` private var pickerRow : _PickerRow<T> { return row as! _PickerRow<T> }`
row becomes nil if the user is scrolling when the first responder is being resigned resulting in a crash. Can you guys can change this to a normal unwrapping to prevent crashing and just return an empty row if the unwrapping fails?

**Comment by IncredibleDucky** [comment]
An even better idea that just occurred to me is possibly caching the last non-nil selected row and returning that.

**Comment by mtnbarreto** [comment]
@IncredibleDucky Could you provide the Eureka version you are using? I think we already fix this. 

This line was changed to `private var pickerRow : _PickerRow<T>? { return row as? _PickerRow<T> }`

**Comment by mtnbarreto** [comment]
same as #208

**Comment by IncredibleDucky** [comment]
I was using 1.3.1 thank you for responsding. I updated and haven't gotten the crash since. Thank you.
