### ISSUE TITLE
0 after decimal separator (DecimalRow)

### ISSUE THREAD

**Issue by bre7** [xmartlabs/Eureka#319]
Similar to (if not the same as) #69 

Rep:
1. Add `DecimalRow` in VC
2. Type `5`
3. Type `6`
4. Type `,` (or the corresponding decimal separator shown on your screen)
5. Type `8`

Expected: **56,8** (or 56.8 depending on locale)
Result: **56,08** (or 56.08 depending on locale)

Vanilla example, no custom formatter was used. (Locale: UY)

**Comment by mtnbarreto** [comment]
@bre7 Could you please provide your form creation code so i can easily reproduce the issue?

**Comment by bre7** [comment]
Sure, here's the code:
```swift
class AddResultViewController: FormViewController {

        override func viewDidLoad() {
                super.viewDidLoad()
        
                form +++ Section("Agregar nuevo resultado")
                    <<< DecimalRow() {
                        $0.title = "Valor"
                        $0.tag = ResultRowTags.ResultValue.rawValue
                    }
                }
            }

}
```

**Comment by mtnbarreto** [comment]
@bre7 I found the issue, Tomorrow I'm going to push the fix after adding some UI Test coverage for each `formatter` and `useFormatterDuringInput` set up combination.

**Comment by bre7** [comment]
Thanks for the quick fix !
