### ISSUE TITLE
Xcode 7.3 beta 5

### ISSUE THREAD

**Issue by marcosgriselli** [xmartlabs/Eureka#320]
Is there any beta branch that I can pull from to work on this Xcode version?. Current one displays errors from Swift changes. 

<img width="1543" alt="screen shot 2016-03-09 at 10 43 51 am" src="https://cloud.githubusercontent.com/assets/14804033/13637026/d612ed8c-e5e3-11e5-85f7-b39e63bac01d.png">

**Comment by mtnbarreto** [comment]
@marcosgriselli Yes, you can use https://github.com/xmartlabs/Eureka/tree/Xcode7_3 for now.
