### ISSUE TITLE
How to dynamically translate AlertRow cancel button label ?

### ISSUE THREAD

**Issue by berengergermain** [xmartlabs/Eureka#323]
Hello,

is there a way to dynamically set another title to the action row cancel option (or any other one) in an AlertRow ?

Regards.

**Comment by mtnbarreto** [comment]
I made some changes to support it.

I added `public var cancelTitle = NSLocalizedString("Cancel", comment: "")` to  `SelectorAlertController<T: Equatable>` which is the view controller that is presented by ActionRow.

So now we can set the cancel button text setting up onPresent callback:

```swift
                <<< AlertRow<Emoji>() {
                        ...
                    }.onPresent{ _, to in
                        to.view.tintColor = .purpleColor()
                        to.cancelTitle = "My Cancel Button Title"
                    }
```

**Comment by williancoelho** [comment]
Thanks!

**Comment by berengergermain** [comment]
Oh sorry, I missed the notification ! Thank you for the patch ;)

My swift project was canceled but if I have some time, I will try that and give you a feedback.

Regards

**Comment by carlosbdw** [comment]
Still can not change cancel button title by using 

}.onPresent{ _, to in
                        to.cancelTitle = "My Cancel Button Title"
                    }
