### ISSUE TITLE
SliderRow layout problem on iPhone5s/4s

### ISSUE THREAD

**Issue by sash** [xmartlabs/Eureka#324]
Hi guys,

Great job on Eureka! I love it. 

Looks like there is a layout issue with the Slider row on smaller screen sizes. See the screenshot for example:
<img width="322" alt="screen shot 2016-03-09 at 18 38 58" src="https://cloud.githubusercontent.com/assets/45210/13642710/42c2d89c-e626-11e5-9ed4-48cdf61f2d4b.png">

**Comment by brettalcox** [comment]
This is a pretty recent pull request I think. I had the same issue as well. For a hacky workaround, I imported the DeviceKit framework into my project, and edited the SliderRow.swift file. Did an if/else inside the SliderRow.swift class methods for iPhone 4/4S/5/5S/5C, and if the device was <code>==</code> to those devices, set these fields below:

<code>textLabel?.translatesAutoresizingMaskIntoConstraints = true</code>
<code>detailTextLabel?.translatesAutoresizingMaskIntoConstraints = true</code>
<code>let metrics = [
                "hPadding" : 16.0,
                "vPadding" : 0.0,
                "spacing" : 0.0,
            ]</code>

Else, (not any of those devices), then: 

<code>textLabel?.translatesAutoresizingMaskIntoConstraints = false</code>
<code>detailTextLabel?.translatesAutoresizingMaskIntoConstraints = false</code>
<code>let metrics = [
                "hPadding" : 16.0,
                "vPadding" : 12.0,
                "spacing" : 12.0,
            ]</code>

So still looks great on anything newer than those devices....and....sorta good on the older devices. At least makes it usable. 

![simulator screen shot mar 5 2016 11 29 22 pm](https://cloud.githubusercontent.com/assets/7462622/13657020/6a6ca6f6-e631-11e5-8490-f5c94b2e0009.png)

Hopefully we can get a legitimate fix here soon.

**Comment by alibasta** [comment]
Is here any progress on this issue to have a fix in the main branch?

**Comment by mtnbarreto** [comment]
I've tested it using master branch on iphone 4s and 5s and couldn't reproduce the issue. 
@sash @alibasta Are you still experiencing this?

> Xcode 7.3.1, Eureka master branch code.

**Comment by mtnbarreto** [comment]
Please, feel free to reopen this issue if you are still experiencing this issue. A project to reproduce it will help a lot to provide a fast resolution.

**Comment by chidg** [comment]
Hi guys
I was having a similar problem on iPhone 6 and in the simulator, until I looked at the code in the example project and noticed that a `value` attribute was set on the SliderRow. When I set that in my code, the slider text appeared in the correct position. Perhaps it should be mentioned in the docs or raise an error that a value for `value` is needed when initialising a SliderRow.

**Comment by josephbao** [comment]
I'm still getting this. Has this issue been solved?

**Comment by alibasta** [comment]
Thanks @chidg ! That fixed the glitch

**Comment by Fredehagelund92** [comment]
i have this issue to in iphone 6. i've added my code for people to reproduce.

    import UIKit
    import Eureka

    class NewGroupViewController: FormViewController {

        override func viewDidLoad() {
            super.viewDidLoad()

            //Background View
            self.view.backgroundColor = UIColor("#F8F9FF")

            
            
            //Form
            
            
            form = Section("")
                <<< MultipleSelectorRow<String>() {
                    $0.title = "Users"
                    $0.selectorTitle = "Pick users to the group"
                    $0.options = ["One","Two","Three"]
                }
                +++ Section("Søgeindstillinger")
                <<< SliderRow(){
                    $0.title = "Minimum Age"
                    $0.cellStyle = .value1
                    $0.minimumValue = 10
                    $0.maximumValue = 40
                    $0.steps = 30
                    let numberFormatter = NumberFormatter()
                    numberFormatter.numberStyle = .none
                    numberFormatter.minimumFractionDigits = 0
                    $0.cell.formatter = numberFormatter

                }
            
            
        }

        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }
        



    }

**Comment by mats-claassen** [comment]
Thanks @Fredehagelund92 your code exposes the issue, but as @chidg said setting an initial value fixes it.

**Comment by spinach** [comment]
I am still getting this problem. And I'd rather not set initial value because I want form.values()["sliderTag"] to give me nil in order for me to know that the user did not touch the slider. Any way we can fix the layout?

**Comment by pluckq** [comment]
Bump. Still have this issue after hiding/showing others rows on form

**Comment by Ziph0n** [comment]
Same here. Using the Swift3_2 branch

**Comment by akabab** [comment]
@mtnbarreto having this issue too (I'm up to date), isn't it supposed to be open still ?

**Comment by akabab** [comment]
@Ziph0n & @plusckq, went to the source, fixed it for my usage, see PR #1296
