### ISSUE TITLE
How can I make a row disabled without turning the title to  gray?

### ISSUE THREAD

**Issue by marshallYin** [xmartlabs/Eureka#326]
What I want is that user can not tap the row.like this 
![2016-03-10 2 13 28](https://cloud.githubusercontent.com/assets/16058230/13661095/b7ba83b2-e6ca-11e5-93be-86e45b4874ae.png)

but when I set the disabled property of the row,its title will become gray,which I don't want to see.
![2016-03-10 2 13 55](https://cloud.githubusercontent.com/assets/16058230/13661119/db2fb18c-e6ca-11e5-9f4c-7be793414852.png)

How can I fix it?

**Comment by marshallYin** [comment]
override func tableView(tableView: UITableView, willSelectRowAtIndexPath indexPath: NSIndexPath) -> NSIndexPath? {
        if indexPath.section == 0 || indexPath.section == 1 {
            return indexPath
        } else {
            return nil
        }
    }

**Comment by mtnbarreto** [comment]
you should override the disabled color using `cellUpdate` callback.

```swift
row.cellUpdate { cell, row in
        cell.textField.textColor = row.isDisabled ? .yourDisabledTextColor() : .blackColor()
}
```

**Comment by marshallYin** [comment]
I override the tableView(willSelectRowAtIndexPath:) method and return nil to prevent the row from being selected
