### ISSUE TITLE
Button Cell is Not Deselected

### ISSUE THREAD

**Issue by wallance** [xmartlabs/Eureka#33]
I created a simple button with the following code, but when I select the button it is not deselected.  Is this supposed to be handled automatically by the library, or do I have to call a specific method?

```<<< ButtonRow() {
                $0.title = "Sign Up"
    }.onCellSelection{ cell, row in //Custom code}```

In ```onCellSelection``` I tried calling ```cell.unhighlight()```, but that did not have any effect.

**Comment by mtnbarreto** [comment]
@wallance Eureka should've deselected the row automatically.
I'm gonna commit the fix on master branch.
