### ISSUE TITLE
pushrow arrow indicator styling

### ISSUE THREAD

**Issue by cyrus86** [xmartlabs/Eureka#332]
I'm not quite sure what to call it, but the small arrow on the right side of a PushRow has a weird orange shadow. On devices as well as simulator.  

<img width="189" alt="screenshot_3_11_16__08_50" src="https://cloud.githubusercontent.com/assets/2669027/13688797/7d92c968-e767-11e5-8687-6f94e53fae1d.png">

**Comment by mtnbarreto** [comment]
Which Eureka version?

**Comment by mtnbarreto** [comment]
I cannot reproduce the issue? Could you please look for .orangeColor() in your code.
Notice that simulator shows colored layers if you enable some options within Debug menu.
