### ISSUE TITLE
Row Left Margin

### ISSUE THREAD

**Issue by 99xs** [xmartlabs/Eureka#334]
Any way of removing the left margin on rows? I can do it in sections by setting the inset for tableView to 0, but for rows... I can't make it go edge to edge...

Here's an example of what I'm trying to do:

    let rowName = NameRow() {
            $0.title = "First Name:"
            }.cellSetup {cell,row in
                cell.separatorInset = UIEdgeInsetsZero
                cell.layoutMargins = UIEdgeInsetsZero
        }

**Comment by mtnbarreto** [comment]
similar to #22. 

`layoutMargins` property reference:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/#//apple_ref/occ/instp/UIView/layoutMargins
