### ISSUE TITLE
How do I change the textColor for the textLabel in the LabelRow?

### ISSUE THREAD

**Issue by AtharvaVaidya** [xmartlabs/Eureka#34]
I want to change the color of the text of a labelCell. I tried overriding the willDisplayCell function of the tableView, but it didn't work.

**Comment by BryanJBryce** [comment]
+1

**Comment by BryanJBryce** [comment]
+1

**Comment by mtnbarreto** [comment]
You can also change it using the `defaultCellUpdate` class method: 

```swift
        LabelRow.defaultCellUpdate = { cell, row in
            cell. detailTextLabel?.textColor = .redColor()
        }
```

Additional info of these functions: http://blog.xmartlabs.com/2015/09/29/Introducing-Eureka-iOS-form-library-written-in-pure-Swift/#fully-customizable
