### ISSUE TITLE
How to avoid capitalizing the Section Header string and also enable touch on Section Footer string

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#343]
Is there a way to avoid capitalizing the Section Header string similar to how Section Footer.

Also, I am looking to have a text "Forgot password" in the Section footer and wanted to check if there is a way to touch enable the footer text so that I can then invoke a 'Forgot Password" method.

I am using the Eureka 1.4.1
.
Thanks in advance.

**Comment by mats-claassen** [comment]
Hi have you done this without Eureka? (i.e. a simple UITableView section)

The part of the footer can be achieved by adding an an event to the footer view using the onSetupView callback.
If this does not work you might want to create a custom view for the footer

**Comment by rajeshmani27** [comment]
I created an UIButton, added it as an UIView subview and in turn added the subview to the Section footer using the following code..however, I don't see the UIButton show up on the footer.  When I add a UIButton directly to the footer, by setting HeaderFooterProvider<UIButton> I find the UIButton is centered instead of left aligned.

Looking for help on the right way to add UIButton to the footer such that the button is left aligned.

Below code snipped with the UIButton as a subview of UIView.

Section() {section in
                
                //Create an UIButton
                let signupButton = UIButton()
                signupButton.setTitleColor(UIColor.grayColor(), forState: .Normal)
                signupButton.setTitle("Forgot password? Click here", forState: UIControlState.Normal)
                signupButton.addTarget(self, action: #selector(SignupViewController.forgotPasswordClicked), forControlEvents: UIControlEvents.TouchUpInside)
                
                var footer = HeaderFooterView(HeaderFooterProvider<UIView>.Class)
                footer.onSetupView = { view,_,_ in
                    view.frame = CGRectMake(0,0,100,40)
                    view.addSubview(signupButton)
                    
                }
                section.footer = footer
                
            }

**Comment by mtnbarreto** [comment]
@rajeshmani27 By doing that you are adding the button each time the footer is displayed which is not what you want. 

Why don't you create a custom view, let's say "MyFooterView" and set up the footer using it?

```swift
 var footer = HeaderFooterView(HeaderFooterProvider<MyFooterView>.Class)
```

By doing this you will have full control over the view hierarchy and how it looks.

**Comment by mtnbarreto** [comment]
`onSetupView` is intended to set up the header/footer view data or some minimal customization such as text color or alignment but not for change the header/footer view hierarchy.
