### ISSUE TITLE
CreditCard custom row

### ISSUE THREAD

**Issue by demetrio812** [xmartlabs/Eureka#344]
Hello,
that's not really an issue, I've created a custom credit card row here:

https://github.com/demetrio812/EurekaCreditCard

Suggestions and improvements are welcome!

Thanks,
Demetrio

**Comment by mtnbarreto** [comment]
@demetrio812 awesome work!!

I added you to https://github.com/EurekaCommunity. Would you like to transfer the repository to this organization. I can give you the right to do so. 

Regards
