### ISSUE TITLE
Delete image from device after image select?

### ISSUE THREAD

**Issue by wstudios** [xmartlabs/Eureka#346]
I am directly uploading the selected image to a server but need that image deleted after the image has been uploaded.
I am trying to get the image url to delete but it comes as nil.

This is my code

```
 func saveMedImgChanged(row: ImageRow){
   let imgURL = row.imageURL
 }
```

That function is used in the onChange for the image row

 `.onChange(self.saveMedImgChanged)`

I need to get the image asset url so I can prompt the user to delete the image. Thanks for any guidance.

**Comment by mtnbarreto** [comment]
done! now it should work

**Comment by wstudios** [comment]
Thank you very much. How do I get this change? When I run pod update, it keeps the current copy which is version 1.5.0. Thanks

**Comment by mtnbarreto** [comment]
you should use repository master branch base code or a specific commit.
Look at this guide.... https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo
