### ISSUE TITLE
Cannot add photo to ImageRow by "take photo"

### ISSUE THREAD

**Issue by sumitpaul** [xmartlabs/Eureka#347]
Hi Everybody,

I am using the latest version of Eureka, and everything in my form works fine, except for the ImageRow.

When I try to add an image by tapping on "Take Photo" I get this message in the xcode console:

**Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.**

The app doesn't crash, I can still select a photo from the photo library, or saved photos, but I can't actually use the camera. What could be going wrong? I don't get the message where iOS asks if the app can use the camera either.

My ImageRow code looks like this:

```
<<< ImageRow("tagProfilePhoto"){
  $0.title = "Profile Photo"
}
```

**Comment by weyert** [comment]
Noticed a comment on Stackoverflow where it appears to be resolved when executing the image picker code in the main queue, see: http://stackoverflow.com/questions/25884801/ios-8-snapshotting-a-view-that-has-not-been-rendered-results-in-an-empty-snapsho

**Comment by mtnbarreto** [comment]
@sumitpaul Could you provide device model, Eureka, Xcode, ios versions?

**Comment by sumitpaul** [comment]
It was happening on an iphone 5S with iOS 9.2, latest version of Eureka. I tried deleting the app, reinstalling it a bunch of times but that didn't solve the problem. Then I noticed that the uiimagepicker was not asking for permission to use the camera, so I had to go into the settings for the app and turn the camera on. Now it works. But I still do get that message.

**Comment by mtnbarreto** [comment]
@sumitpaul have you finally got rid of this error? Which was the problem?
