### ISSUE TITLE
Issues overriding navigationAccessoryView

### ISSUE THREAD

**Issue by DarrenAndes** [xmartlabs/Eureka#351]
I am trying to override navigationAccessoryView and w/ (Xcode 7.3 and v. 1.5.0) am now having problems as navigationDone is not a public func so the new #selector cannot resolve it.

navigationAccessoryView.doneButton.action = #selector(FormViewController.navigationDone(_:))

// Need this extension to be changed to:

extension FormViewController {
    public func navigationDone(sender: UIBarButtonItem) {

**Comment by mtnbarreto** [comment]
Hi @DarrenAndes,
I made this `FormViewController` methods public: `navigateToDirection(direction: Direction)`

From there should be simple to set up target action to your inputAccessoryView buttons. Take a look at how 
Eureka implements them. Its just one line of code each.

Regards

**Comment by rauanmaemirov** [comment]
@mtnbarreto Has anything changed since that time?
`navigateToDirection` only helps with arrow actions, not doneButton.
