### ISSUE TITLE
Eureka 1.5.0 + Carthage fails for Xcode 7.2.1

### ISSUE THREAD

**Issue by scottrhoyt** [xmartlabs/Eureka#352]
Eureka: 1.5.0 via Carthage
Environment: Xcode 7.2.1 (Swift 2.1)

After running `carthage update` on my project using Eureka, the update failed to build Eureka using Xcode 7.2.1. To verify this build error, I tried a `carthage build --no-skip-current` on the 1.5.0 release and that also failed. 1.5.0 seems to build fine with Xcode 7.3 (Swift 2.2). It appears there is a dependency in the 1.5.0 version on Swift 2.2.

If this is the case, perhaps this is the sort of breaking change that should increment the major version number to be in compliance with semantic versioning. I can imagine many developers not upgrading to Swift 2.2 immediately because of the source code changes needed. They may get caught off guard doing an update via carthage or cocoapods even though they have specified to only update minor version releases.

**Comment by mats-claassen** [comment]
We think this is an evolution of Swift and the compiler in particular, so its not a Eureka breaking change.
Most pods will be experiencing this and we saw that many of them did not increment the major version number. 

 It is not incorrect what you say but it is easy to fix the version you are using to a previous version like 1.4.1

**Comment by mtnbarreto** [comment]
@scottrhoyt We would prefer to use major version number to indicate relevant architecture/design breaking changes. 
Latest stable Eureka version will always be compatible with most recent stable swift/Xcode version and this will happen (at this point) more often than architecture/design breaking changes. 

People have taken both approach (updating major number or middle version number) to manage OSS project versions. For instnce RxSwift took same approach as Eureka. 

You can easily get rid of these issues by fixing the version number to 1.4.x version.
