### ISSUE TITLE
Xcode 7.3 & CocoaPod compilation error

### ISSUE THREAD

**Issue by danialmoghaddam** [xmartlabs/Eureka#353]
Just updated to xcode 7.3 and now getting the  `Command failed due to signal: Segmentation fault: 11` compilation error in `Helper.swift` and `SliderRow.swift`

**Comment by clemkoa** [comment]
This has been fixed in version 1.5. Just update your podfile:
```
  pod 'Eureka', '~> 1.5'
```
Then run `pod install`

**Comment by danialmoghaddam** [comment]
My pod search seemed to be outdated and was showing 1.4.1 as the latest version. 

Changed the pod version to 1.5 and issue is resolved 

Thanks
