### ISSUE TITLE
Hide PickerInlineRow after selected

### ISSUE THREAD

**Issue by wstudios** [xmartlabs/Eureka#354]
i am using the ` <<< PickerInlineRow<String>() {` but need to hide the picker after a user makes a selection.

Thanks

**Comment by izonprize** [comment]
Something like this may work:

$0.hidden = Condition.Predicate(NSPredicate(format: "$RowName != nil"))

**Comment by mtnbarreto** [comment]
@wstudios similar to #97

**Comment by wstudios** [comment]
Thank you, using the .onChange callback referenced also works perfectly.
