### ISSUE TITLE
Row Options Update Question

### ISSUE THREAD

**Issue by izonprize** [xmartlabs/Eureka#355]
I currently have two Action Sheet Rows, A and B, that use two different array of strings as their options source. Row B is disabled until a value from row A is selected. I use the onCellSelection event of row A to create the array of strings for row B. How do I get row B's options to refresh before a user clicks on row B?

In short how do we update a row's options data in the background after the row is already initialized?

**Comment by mats-claassen** [comment]
It is possible to update the options of a row like this for example: 
```
otherRow.onChange { row in
                        if let r = self.form.rowByTag("rowToUpdate") as? AlertRow<Emoji> {
                            r.options = [👦🏼 , 🍐 , 💁🏻 , 🐻]
                            r.updateCell()
                        }
        }
```
You must be able to do it in `onCellSelection` as well
