### ISSUE TITLE
TextAreaRow auto height?

### ISSUE THREAD

**Issue by attilaszaszlateral** [xmartlabs/Eureka#361]
Can I configure a TextAreaRow of an Eureka form to fill the available vertical space?
I will have just a few rows above and toolbar at the bottom.

Eureka: latest master branch, Xcode 7.3, iOS 9.3

btw, documentation says, post questions to stackoverflow.com with tag "eureka-forms", but there is no such tag on SO (and I don't have enough rep to create it). [Question on SO with this issue](http://stackoverflow.com/questions/36310351/eureka-form-textarearow-auto-height).

**Comment by mats-claassen** [comment]
Hi @attilaszaszlateral, have a look at #90 it might help you for now

**Comment by mtnbarreto** [comment]
@attilaszaszlateral Take a look at this merged pull request https://github.com/xmartlabs/Eureka/pull/416, it should be enough to implement your feature. You can set up the row height as well as enable auto size.

Basically we added `textAreaHeight` property to `TextAreaRow`.  `textAreaHeight` type is an enum that can be either Dynamic or Fixed as shown below..

```swift
public enum TextAreaHeight {
    case Fixed(cellHeight: CGFloat)
    case Dynamic(initialTextViewHeight: CGFloat)
}
```
