### ISSUE TITLE
Specific row editing

### ISSUE THREAD

**Issue by su23** [xmartlabs/Eureka#363]
Hi, I would like to 
1) able to edit specific row (in other words transform table into the editing mode)
2) able to customize buttons by sliding row to the left. 
Thus I need to extend `FormViewController` by provideing necessary methods.
All further customisation will be in the inheritors of `FormViewController`.

Can you give me a green light for this modifications?

**Comment by su23** [comment]
please review #371

**Comment by mats-claassen** [comment]
Hey @su23 I think this is rather custom. You can easily do this and customize it in your subclass of `FormViewController` and I believe it is not necessary to add another layer of abstraction here.
Keep in mind to always call super in the methods you override of FormViewController

**Comment by su23** [comment]
Thanks, yes I can do it. But I also was forced to create my own (Multiple)SelectorViewController classes but, probably we can close this ticket.
