### ISSUE TITLE
Lazy options population

### ISSUE THREAD

**Issue by su23** [xmartlabs/Eureka#364]
There are some circumstances when I need a special population of the possible options depending of the data in another rows. Thus, static set in `DataProvider` struct does not satisfy this case.
I can extend this structure by adding 
`public let lazyArrayData: (BaseRowType -> [T])?`
property and corresponding changes in the `SelectorViewController` class. Of course behaviour "'by default' will stay.
Will you give me a green light for this?

**Comment by su23** [comment]
Also I found that pretty the same request is also described in the #355 issue. Sorry for issue duplication.

**Comment by mats-claassen** [comment]
Closing as duplicate to #355
