### ISSUE TITLE
Custom format string for specific option

### ISSUE THREAD

**Issue by su23** [xmartlabs/Eureka#365]
In the DataProvider we can specify the fixed set of T values. But not always I want to see the default string representing of T by calling 
`lrow.title = row.displayValueFor?(option) `
in the SelectorViewController for example.

Sometimes depending on current selected values in another rows I would like to add suffix or prefix or fully customise title for only specific option values.
To achieve this I see by adding 
`public let customFormat: (T -> String)? `
property into DataProvider struct. Of course the behaviour "by default" will stay.
What you think about this?

**Comment by mats-claassen** [comment]
What is the difference between your `customFormat` and overriding `displayValueFor`?
I believe you can do the same.
You should just override `displayValueFor` in your row

**Comment by su23** [comment]
The difference is that by calling `displayValueFor` we can only get string value of that object. But by implementing this clousure we can specify dependency on current application state. Just simple example - I would like to see this list:
```
value 1
value 2 
value 3 (default)
...
value N
```

Where  "default" will be added because this value was selected as default in the application. Thus I want to keep my object as it is, but to override only the string representation when (for example) we show a list of possible values in the popup view.

**Comment by mats-claassen** [comment]
@su23 `displayValueFor` is also a closure so that you can also check for the applications state and return a different string for a default value.
Both closures even have the same type.

**Comment by mtnbarreto** [comment]
@su23 If you need even more flexibility please check out this issue: https://github.com/xmartlabs/Eureka/issues/299, in particular take a look at `selectableRowCellUpdate` property.
