### ISSUE TITLE
Empty space if we didn't specify header title

### ISSUE THREAD

**Issue by su23** [xmartlabs/Eureka#368]
Event in the examples when we open form with no title we see empty space between content and navigation:
![screenshot 2016-04-02 14 11 25](https://cloud.githubusercontent.com/assets/1129964/14226539/3022c2f0-f8dd-11e5-81b9-70d2b1aeaf37.png)

I think we should eliminate this space if header title is not specified because it looks very clumsy. I can achieve this by some modifications in the `FormViewController` class. Will you give me a green light for this?

**Comment by su23** [comment]
Ok, for this issue I already created a pull request: https://github.com/xmartlabs/Eureka/pull/369
Please review my changes

**Comment by mats-claassen** [comment]
Hey @su23 we believe that this should not be the default behaviour. If you want no space between sections then you can use a tableView with style `Plain`. Or you can set custom views as headers giving them the desired height.
For example this helper could help you:
```
extension Section {
    func setEmptyHeaderOfHeight(height: CGFloat, width: CGFloat) {
        self.header = HeaderFooterView<UIView>(HeaderFooterProvider.Callback {
            return UIView(frame: CGRectMake(0, 0, width, height))
        } )
    }
}
```

You could even leave the width out of this method.

**Comment by su23** [comment]
Ok, thanks!
