### ISSUE TITLE
Display an edit version of the form

### ISSUE THREAD

**Issue by wallance** [xmartlabs/Eureka#37]
Is it possible to reuse the same form when you want to allow the user to edit data that was previously submitted?  If so, can a code example be provided of how to create the form with pre-populated field?

**Comment by mtnbarreto** [comment]
Yes, you can use `setValues` method which is declared in `Form` class to set a collection of values to the form.

This is the function implementation: 

```swift
    public func setValues(values: [String: Any]){
        for (key, value) in values{
            let row: BaseRow? = rowByTag(key)
            row?.baseValue = value
        }
    }
```

Each row value type must match with the related dictionary value.
