### ISSUE TITLE
Latest version of Xcode example project not working

### ISSUE THREAD

**Issue by mikerecu** [xmartlabs/Eureka#372]
When i load the example app on my phone i get the below error. However it works in simulator. I am using the latest version of xcode (7.3) and the latest version of ios (ios 9.3.1 & iphone6s). I tried deleting from derived data, cleaning the project but it makes no difference.

dyld: Library not loaded: @rpath/Eureka.framework/Eureka
  Referenced from: /var/containers/Bundle/Application/3BB437F9-AA9B-4226-AC74-5044DDE77869/Example.app/Example
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/3BB437F9-AA9B-4226-AC74-5044DDE77869/Example.app/Frameworks/Eureka.framework/Eureka: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/3BB437F9-AA9B-4226-AC74-5044DDE77869/Example.app/Frameworks/Eureka.framework/Eureka'

**Comment by rcrsv2n** [comment]
Not getting the same issue and I am using Xcode 7.3 and the latest version of iOS. This issue can occur for various unrelated reasons, see here for some possible solutions:
http://stackoverflow.com/questions/32730312/reason-no-suitable-image-found

**Comment by mats-claassen** [comment]
Hi @mikerecu , are you still having this issue?

**Comment by mtnbarreto** [comment]
This issue seems that have nothing to do with Eureka... I will close it for now.
Feel free to re-open it if you tried to solve it and you are still experiencing the issue.
