### ISSUE TITLE
Unsupported architectures when uploading archive

### ISSUE THREAD

**Issue by vikdenic** [xmartlabs/Eureka#373]
I implemented Eureka into my project, and now I get errors when trying to upload to the App Store / TestFlight.
<img width="580" alt="screen shot 2016-04-04 at 8 04 49 pm" src="https://cloud.githubusercontent.com/assets/7085697/14268886/1f1926a6-faa5-11e5-8795-c0ee0ff0271a.png">

These include "Unsupported architectures", "Invalid segment alignment", and "The Binary is invalid.. This binary does not seem to have been built with Apple's linker".

I did not have any of these errors before implemented Eureka. I am running Xcode 7.3

**Comment by vikdenic** [comment]
The problem was that Xcode precompiles the dynamic library for both the simulator (i386) and devices (x86_64). I had to[ implement this run script](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/) to remove the unused architecture.

**Comment by mtnbarreto** [comment]
@vikdenic Are you using Carthage?

**Comment by vikdenic** [comment]
@mtnbarreto Yes, I am using Carthage

**Comment by mtnbarreto** [comment]
@vikdenic  you solution is ok. 
Have you follow this guide https://github.com/Carthage/Carthage/blob/5fd867c4895b4f59d70181dec169a1644f4430e3/README.md#if-youre-building-for-ios? This seems to remove the simulator slices. 

Please also check that ....
In your app target `Build Settings` the `Valid Architectures` values for release does not contains i386 nor x86_64. 

<img width="442" alt="screen shot 2016-05-10 at 5 04 48 pm" src="https://cloud.githubusercontent.com/assets/1746532/15160652/10c61472-16d1-11e6-952e-f9df92c539ff.png">


Also make sure you are using last stable carthage version.

Let me know if this helps to make it work.

**Comment by mtnbarreto** [comment]
Also check out this radar.. http://www.openradar.me/23605715
