### ISSUE TITLE
How to set a constraint between my ios navigation bar and the form?

### ISSUE THREAD

**Issue by ariff20** [xmartlabs/Eureka#375]
I have a navbar in my app that is obscuring the top part of the eureka form.How do I set a vertical constraint to that navbar so that it is displayed correctly?

**Comment by mats-claassen** [comment]
If you are using storyboards then you can just add a tableview to your controller, add the constraints you want and connect the outlet to the FormViewController.
Most probably your navBar is translucent, so setting `translucent = false` would also fix it.
Another option is to manually adding constraints to the tableView, for example in the `viewDidLoad` method of your controller
