### ISSUE TITLE
Passing data between rows

### ISSUE THREAD

**Issue by cfilipov** [xmartlabs/Eureka#377]
Perhaps this is misusing the framework, but I figure it's worth asking. I'm having trouble figuring out the best way to architect custom rows that are based on other row's values. 

**TL;DR: What's an idiomatic strategy for updating one row's contents based on another row's value when both rows value types are different?**

Here's an example of the problem: say I have a custom row that displays a timeline and the user can select a date. This custom row's value type is `NSDate`. Now lets say I have another row in the same form that displays a diagram based on that date and should update its contents based on the selected value of the timeline row. 

This is pretty simple if the diagram row value type is also an `NSDate`. I can just set the value of the other row in the timeline's `onChange` callback. 

However, the diagram view inside the row is pretty generic. The diagram doesn't know anything about dates, it just takes some config object that tells it what/how to display and that config object is created by querying some data source. It should also be noted that a config can be build from various inputs. I might have an identifier or some other model object that I pass in to get the diagram's config instead of a date. So I see a few options for implementing this:

1. The diagram row's value type is the config object, making the row re-usable, but forcing the user of the row to have to transform the date to its config object. In this case I would need to have some logic in `onChange` that takes the row's new value, creates a config, then sets that as the diagram row's value.
2. The diagram row's value type is an `NSDate`, just like the timeline row. This means all the logic for translating the date into a config is done internally in the diagram row. This means I would need separate diagram rows for each different way the diagram could be used. This also puts some app/data access logic in the row itself. The row is less re-usable, but more encapsulated.

One major flaw of option 1 is that calling `updateCell()` on the diagram row does nothing, because all the logic of fetching the data for a date is outside the row's definition. This can be fixed moving the logic out of the timeline's `updateCell` into a function that can be called from the various places that trigger the need to update. But this seems to go against the declarative nature of Eureka and just doesn't feel right.

On the other hand, having the row contain app-specific logic doesn't feel right either, but I'm not sure why or if that even matters.

I can think of a few more ways to accomplish this by defining some protocols etc.. but before I go any further I wanted to see if there was a more idiomatic way of doing this in Eureka that I might have missed.

I am currently doing option 1. You can see the source code [here](https://github.com/cfilipov/MuscleBook/blob/master/MuscleBook/RootViewController.swift). When `CalendarWeekRow` gets a new date, it does some lookup, gets a config object, and sets that on `SideBySideAnatomyViewRow`. The `SideBySideAnatomyViewRow` is used in many places. In fact, there are multiple ways of rendering an anatomy view: Side-by-side or a swipe-able view, each share the config object. If I were to go with option option 2, I would have to create rows for each view+datasource combination.

**Comment by mats-claassen** [comment]
You are correct in pointing out that the rows should be reusable to the greatest possible extent.
I believe option 1 is better for this reason. You should have a centralized / unified place where you process the dates to obtain 'config objects' and then set this as the value of that second row.
Normally after setting the value you will have to call `updateCell` to reflect those changes on the row (at least if the row is on screen)

**Comment by cfilipov** [comment]
Thank you for the reply @mats-claassen. I was hoping there was something more elegant that I was missing. It seems like a lot of manual wiring, but this works. It would be nice to see more non-trivial usages of Eureka to get ideas from. The example app helps a lot, but I don't see a whole lot else even though this is a popular project. Using Eureka has made developing my app much faster, I really appreciate this project!
