### ISSUE TITLE
Scrolling to the bottom of the form

### ISSUE THREAD

**Issue by demetrio812** [xmartlabs/Eureka#378]
Hello,
what's the best way to scroll to the bottom of an Eureka form?

I know I can use self.tableView?.scrollToRowAtIndexPath but I need a NSIndexPath, how do I get the NSIndexPath of the last row in the last section?

Thanks,
Dem

**Comment by mats-claassen** [comment]
This snippet gives you the (optional) indexpath:
```
form.last?.last?.indexPath()
```
You can also use form.count() and form.last?.count()

**Comment by demetrio812** [comment]
Thanks!

Dem
