### ISSUE TITLE
Above separator hided after PickerInlineRow<String> expanded

### ISSUE THREAD

**Issue by andrewSvsg** [xmartlabs/Eureka#382]
**Separator between "Postal" and "State" exist**
![screen shot 2016-04-16 at 5 41 34 pm](https://cloud.githubusercontent.com/assets/16840841/14581647/ae1fa8f8-03fa-11e6-8b33-29419ea55fa4.png)

**Tap on PickerInlineRow<String> and separator become hided**
![screen shot 2016-04-16 at 5 41 40 pm](https://cloud.githubusercontent.com/assets/16840841/14581658/c30fadda-03fa-11e6-82c5-7e05336f489c.png)

**Picker closed**
![screen shot 2016-04-16 at 5 41 48 pm](https://cloud.githubusercontent.com/assets/16840841/14581661/d818619a-03fa-11e6-8ccb-4a1d09f6d351.png)

**Comment by mtnbarreto** [comment]
same as #178
