### ISSUE TITLE
Is it possible to set text alignment to .Left for DateTimeInlineRow?

### ISSUE THREAD

**Issue by andrewSvsg** [xmartlabs/Eureka#383]
I use next settings for  ```NameRow```(SSN, DBA, Company, Tax ID) :
```
    cell.textLabel?.textAlignment = .Left
    cell.detailTextLabel?.textAlignment = .Left
    row.textFieldPercentage = 0.6
```
Birthday is a DateTimeInlineRow
Is it possible to set text alignment and textFieldPercentage like for other cells?
How?

![screen shot 2016-04-16 at 5 46 46 pm](https://cloud.githubusercontent.com/assets/16840841/14581682/5c02493a-03fb-11e6-9688-e1c12cb3449d.png)

**Comment by mats-claassen** [comment]
DateTimeInlineRow is using the default `textLabel` and `detailTextLabel` of UIKit so there is no `textFieldPercentage`.
You can however set the alignment of the labels.
And for the alignment you could try playing with the frames of the labels but I am not sure it will work

**Comment by mtnbarreto** [comment]
To accomplish that you will probably end up creating a custom row. 
I tried to play with alignment and `row.cellStyle` without success :(

Eventually we can make some modification on eureka code to provide more flexibility to easy set up a cell type for a particular, already defined row. 

Regards

**Comment by andrewSvsg** [comment]
All is fine with ```NameRow``` I can set one style for all rows with types from ```NameRow```
cells like ```DateTimeInlineRow``` with own customization rules broke all work (((

**Comment by kohdesmond** [comment]
any fixes on the alignment issues?
