### ISSUE TITLE
How do I add default image to an ImageRow?

### ISSUE THREAD

**Issue by sumitpaul** [xmartlabs/Eureka#386]
I have a function that asynchronously downloads an image from the internet. I want to set my ImageRow cell to this image. How do I do it? This is basically an "edit profile" kind of a form. So i want to show the image that the user currently has their profile image.

I am trying something like this, but it's probably wrong:

getImageFromURL(currentUserPhotoURL!) { (image) in
    print("image downloaded")

    ImageRow("photo").cellUpdate({ (cell, row) in
        cell.accessoryView = UIImageView(image: image)
        cell.accessoryView?.layer.cornerRadius = 17
        cell.accessoryView?.frame = CGRectMake(0, 0, 34, 34)
     })
}

**Comment by mtnbarreto** [comment]
The code below should update the row image. Please let me know if it works for you.
```swift
let imageRow = // your image row reference
imageRow.image = image
imageRow.reload()
```

**Comment by sumitpaul** [comment]
That worked. Thanks!
