### ISSUE TITLE
Modeling cells

### ISSUE THREAD

**Issue by douglasalexandre** [xmartlabs/Eureka#387]
It is possible to model a cell that way?
![captura de tela 2016-04-19 22 26 28](https://cloud.githubusercontent.com/assets/5365616/14660741/465f84d2-067e-11e6-97dd-6293b8c7c8c7.png)

**Comment by mtnbarreto** [comment]
Sure, you can create a custom row that contains both "Nome" and "Apelido" in addition to the user image. The value type of the row could be a struct which has two `String` properties and a `UIImage` property.

For additional information on how to create a custom row take a look at:
https://github.com/xmartlabs/Eureka#how-to-create-custom-rows-and-cells--
https://github.com/EurekaCommunity would also be helpful, it contains custom rows from the community. At the moment it only contains one custom row but i'm encouraging you to add your new custom row there. Let me know if you are interested and i will give you the rights to create/push on the new repo.
