### ISSUE TITLE
eureka compiler segfault w/ latest Xcode 7.3.1 GM Seed

### ISSUE THREAD

**Issue by jaz-ah** [xmartlabs/Eureka#388]
with Xcode: 7.3.1 GM Seed
Eureka: 1.5.0

getting a segfault on the following 3 files:
HeaderFooterView.swift
InlineRowType.swift
Row.swift

basically seeing: 
Command failed due to signal: Segmentation fault: 11

not much other information...  I'm bringing Eureka in through cocoapods and building for an ios9.3 based simulator.

NOTE: this same exact code builds fine w/ Xcode 7.3

**Comment by txaidw** [comment]
Still getting this on the last production Xcode version! Anything I can do?

**Comment by mtnbarreto** [comment]
Please use master branch version for now. We will release a new version shortly...
