### ISSUE TITLE
How to present one form after another in same view controller?

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#389]
Hi everyone,

I would like to present several forms in a view controller. I can get the first form to display fine (form is generated dynamically using API data) in the "viewWillAppear()" method. However, as soon as I go to a different view controller and switch back, the app crashes due to duplicate tags. 

1. How do I clear the existing form within some action method?
2. Is there a way to assign the form a variable? I'm using following syntax but not sure how I can assign a variable to it.

        form
            +++ Section(header: "Some form", footer: "Test") {
                $0.header = HeaderFooterView<TestView>(HeaderFooterProvider.Class)
            }

Thank you in advance!

**Comment by mtnbarreto** [comment]
@plastus 

It seems to me the issue is caused by trying to add rows with the same existing row tags. Each time you get back to your view controller, `viewWillAppear` is invoked and you add again the sections/rows. Each Eureka row tag must be unique. 

If you want to show a new form replacing the existing one, you can set up `form` property. 

```swift
let myForm: Form = .....
formViewController.form = myForm
```
Let me know if this code works for you.

> A FormViewController instance are able to show only one form, you can change it dynamically if needed. 
> If you have more than one view controller to show simultaneously in the same screen, you can add several FormViewControllers into a main parent view controller, each form view controller is a child view controller of main view controller. This is really a rare edge case scenario.

**Comment by plastus** [comment]
Thanks for your response. Ok, so in viewWillAppear() I have the form creation code (tags, type of rows, etc. all obtained from JSON payload that tells iOS what form to generate on screen). 

        let myForm: Form =
            form
                +++ Section(header: "Test", footer: "Footer.") {
                $0.header = HeaderFooterView<TestView>(HeaderFooterProvider.Class)
            }

I try this in viewDidDisappear() for example to try and clear the form and then set a new form info source (different questions). However, when I try the following it tells me that I can't assign it that value.

         self.form = nil

What is the best way to clear the form currently present in a view controller? I basically need to clear the data/UI elements the initial form render has created, in order to put a new form on screen with sometimes over-lapping tags to send to my API. Appreciate your feedback!

**Comment by mtnbarreto** [comment]
this should work...

```swift
self.form = Form()
```

**Comment by mtnbarreto** [comment]
Alternatively you can remove all section from the form..

```swift
self.form.removeAll()
```

**Comment by plastus** [comment]
@mtnbarreto 

Thanks so much! That seems to work in preliminary testing. :)

Off-topic question: Is there an easy way to see all of these methods in Xcode? I know it sometimes predicts class methods, but for example when I was typing "self.form.removeAll()" it didn't show a pop-up list of all the different methods one can use. Just curious if I'm going about coding in Swift the wrong way or if there's a hidden trick to knowing all of the supported methods in a particular class.

**Comment by mtnbarreto** [comment]
If you have ever worked in another IDE you may think as me that Xcode sucks, specially when working with swift, obj-c support and stability is much more better and solid. It's getting better but it has this kind of issues. 

> Notice that `Form` and `Section` conforms to `RangeReplaceableCollectionType` and `MutableCollectionType` so all the methods that belongs to this protocols are available.

Not sure what is going on on your Xcode, my XCode intellisense shows up these methods.
