### ISSUE TITLE
how can i set right to left for arabic content

### ISSUE THREAD

**Issue by trikiano** [xmartlabs/Eureka#398]
in need to set the label in the right and input in the left.
thnx.

**Comment by mtnbarreto** [comment]
It should work, have you tried it ? same as #140

**Comment by trikiano** [comment]
no it not resolved .more help please :(

**Comment by mtnbarreto** [comment]
I have tested it once using Xcode simulator and it worked. 
Could you elaborate more on how are you testing it?

**Comment by trikiano** [comment]
no but i need to change it manually

**Comment by mtnbarreto** [comment]
Follow this guide to test your Right to left interface.....

https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html#//apple_ref/doc/uid/10000171i-CH7-SW1

I have just checked and it works. 

<img width="263" alt="screen shot 2016-04-28 at 7 55 17 pm" src="https://cloud.githubusercontent.com/assets/1746532/14903928/0ceb1852-0d7b-11e6-978d-d6ea7d1c5350.png">
<img width="277" alt="screen shot 2016-04-28 at 7 55 11 pm" src="https://cloud.githubusercontent.com/assets/1746532/14903929/0cebb348-0d7b-11e6-8525-0168145bf1cd.png">

**Comment by hap777** [comment]
If your device language is English but you want to make your form right to left, use affineTransform to mirror the tableView and use it again for labels and values of cells.
here's an example:
self.tableView?.transform = CGAffineTransformMakeScale(-1, 1)  // in viewDidLoad
// cellSetup for  an AlertRow
.cellSetup({ cell , row in
        cell.textLabel?.transform = CGAffineTransformMakeScale(-1, 1)
        cell.detailTextLabel?.transform = CGAffineTransformMakeScale(-1, 1)
                })

Not a good option, but does the work!

**Comment by samfrm** [comment]
@hap777 @trikiano 
Late but use `UIView.appearance().semanticContentAttribute = .forceRightToLeft` ? as Swift 4
