### ISSUE TITLE
Customize row after creation (cellUpdate)

### ISSUE THREAD

**Issue by 3cooper** [xmartlabs/Eureka#4]
I have a field that I would like to highlight after a validation error. From looking at the documentation I'm not sure where I would customize it after the field has already been initialized.  For example, I'd like to change the color of the label when there is an error.

**Comment by mats-claassen** [comment]
There is still no direct means to do validation but you could use the `onChange` callback on the row you want to validate and if there is an error with the new value set to that row then you can change the cell.
Do not forget to call `row.cellUpdate()` after customizing your cell.

**Comment by 3cooper** [comment]
Thanks for the info.  My question was more about the appropriate way to update the row.  Like if I wanted to change the label color, should I drill down to the label with row.cell.label and set it's tint color?  I'm trying to look things up in the code but I'm new to swift and this is the first project I've tried to navigate through.

**Comment by mtnbarreto** [comment]
@3cooper 

From inside `onChange` you can access to the associated cell `row.cell` and change any property. 

If you want to persist your change in the time for this specific row i would recommend to change the cell look and feel from inside `row.updateCell` clousure that will be executed each time the cell is displayed and any invocation to row.cellUpdate() will not override your `cellUpdate` customizations.

To clarify, `cellUpdate` customization clousure is invoked at the end of `row.updateCell` method and `updateCell` method is invoked each time the cell is displayed but you can invoke it (`row,updateCell()`) manually to refresh the cell.

**Comment by 3cooper** [comment]
I don't understand what is happening with the following.  I am calling this code from within viewDidLoad.  When the form appears, the text in the label is Phone Number foo.  But when I debug, I can see that it goes inside the cellUpdate method before showing the form.  If I add a call to updateCell() in viewWillAppear, then the label will say Phone Number bar.  Just trying to understand what is happening.  Why is the code in the cellIUpdate method running when the form is loaded but it doesn't affect the output on the row until updateCell is called.

      form <<< LabelRow(RowTag.PhoneNumber.rawValue) {
        $0.title = "Phone Number"
        $0.value = "foo"
      }.cellUpdate { cell, labelRow in
        labelRow.value = "bar"
      }

**Comment by SpacyRicochet** [comment]
When the form is loaded, the tableview is created and the cells will be displayed. This calls the UITableViewDelegate's `willDisplayCell:` of the FormViewController, which calls for `updateCell`. That's why the cellUpdate block is called after `viewDidLoad`.

As for why you initially see "Phone number foo", _even though_ the cellUpdate has been called once, the cellUpdate method is only called **after** both the row and the cell have finished their normal business. 

The timeline looks something like this.

1. viewDidLoad -> form gets initialised. (`row.value == "foo"`)
2. viewWillAppear -> shows cells, so cellWillDisplay is called -> calls updateCell()
3. updateCell -> sets cell.detailTextLabel.text to row.value -> (`cell.detailTextLabel.text == "foo"`)
4. updateCell -> calls cellUpdate, which changes the row.value, but does **not** update the cell! `row.value == "bar"` and `cell.detailTextLabel.text == "foo"`
5. On the next update, things will be as expected. `row.value == "bar"` and `cell.detailTextLabel.text == "bar"`

Based on this, `cellUpdate` should probably be renamed to `cellDidUpdate`.

**Comment by 3cooper** [comment]
@SpacyRicochet - thanks for the explanation.  So I guess my issue is that in cellUpdate I am changing the label via `row.value` rather than using `cell.detailTextLabel.text`.  Thanks again for the explanation.  I'm trying to find my way through the codebase but having some difficulty tracing through all the layers. Still learning...

**Comment by mtnbarreto** [comment]
@SpacyRicochet Each Eureka row has a associated UITableViewCell.

Whenever a cell is about to appear `willDisplay` is invoked, `willDisplay` invokes row.updateCell() that does this steps:

1. create the cell. 
2. invoke cell.Update() // this set up default cell style and makes use of row properties to set up the cell (for example the detailTextLabel.text using row.value)
3. Invokes the cellUpdate default clousure.
4. invokes cellUpdate clousure of self 

as is shown in the code snippet bellow:

```swift
    override public func updateCell() {
        super.updateCell()
        cell.update()
        customUpdateCell()
        RowDefaults.cellUpdate["\(self.dynamicType)"]?(cell, self)
        callbackCellUpdate?()
        cell.setNeedsLayout()
        cell.setNeedsUpdateConstraints()
    }
```

So to persist the custom style changes even when the cell leaves the visible area you should use 
```
row.cellUpdate { cell, row in 
     ...
}
```
doing that we make sure your code will be invoked at the end of update cycle.

As you might have noticed `row.cellUdpate` does not begin a new update cycle automatically so if you want to see the changes you will have to call `row.updatecell()` after you set up the `row.cellUdpate` clousure.


You can always get the row ( row = form.rowByTag("tag" )) and then access directly the cell property like row.cell.cellProperty = newPropertyValue but probably the update cycle will override it and i do not recommend this approach.

The example project shows several scenarios when we need to make changes on the cells using  cellUpdate clousure and updateCell() method.

@SpacyRicochet Thank  for collaborating in the explanation. 👍 

Regards
