### ISSUE TITLE
cannot use ButtonRow title in condition

### ISSUE THREAD

**Issue by ageorgios** [xmartlabs/Eureka#40]
$0.hidden = .Function(["login"], { form -> Bool in
                    let row: ButtonRow! = form.rowByTag("login")
                    return row.title == "Register"   <- this returns EXC_BAD_INSTRUCTION
                })

When trying the above code, i resulted in EXC_BAD_INSTRUCTION

**Comment by mtnbarreto** [comment]
@ageorgios 
Apparently "login" row was not added yet when the hidden condition is first evaluated. This happens right after the row that has a the hidden property is added to its section.  At this time `form.rowByTag("login")` return nil and `row.title` throws an Exception.

When the dependent row is added, in this case  "login" row, the condition is re-evaluated and form.rowByTag("login") returns it. 

So you should replace the code by:

```swift
 $0.hidden = .Function(["login"], { form -> Bool in
                let: row: ButtonRow? = form.rowByTag("login") 
                return row?.title == "Register"
            })
```
