### ISSUE TITLE
Swipe issue

### ISSUE THREAD

**Issue by YSDC** [xmartlabs/Eureka#402]
I found a bug with the SelectorRow or MultipeSelectorRow.
The user click on a SelectorRow (or MultipeSelectorRow). If, before select an entry, the user swipe right a bit (not enough to come back to the list, but just to see it a bit), and then select items, the selected items list is not updated because the "displayValueFor" has already been called.

I found this bug not only in my app, but also in the example app. I hope it's clear enough, i can upload a video if you want

**Comment by YSDC** [comment]
[errorSwipe.zip](https://github.com/xmartlabs/Eureka/files/244684/errorSwipe.zip)

**Comment by mtnbarreto** [comment]
@YSDC Thanks for reporting it. It should be fixed now.
