### ISSUE TITLE
Way to manually trigger a PushRow segue

### ISSUE THREAD

**Issue by txaidw** [xmartlabs/Eureka#403]
Is there a way to manually trigger a PushRow segue?

I've tried row.select(), row.didSelect().
But when the value is chose on the table it is not selected on the row.

Its possible to do this?

thanks

**Comment by mtnbarreto** [comment]
PushRow is not updated after selecting a value because FormViewController only updates the selected table view cell and since you are pushing it by code the push row cell is not selected. 

As a workaround you can select the cell before pushing the new view controller. Something like this:

```swift
                <<< PushRow<Emoji>() {
                        $0.tag = "Push"
                        $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻]
                        $0.selectorTitle = "Choose an Emoji!"
                    }
                <<< ButtonRow()
                    .onCellSelection({ [weak self] (cell, row) in
                        let pushRow: PushRow<Emoji>  = row.section!.form!.rowByTag("Push")!
                        pushRow.cell.setSelected(true, animated: false) // this is optional, just to make it looks selected
                        self?.tableView?.selectRowAtIndexPath(pushRow.indexPath()!, animated: false, scrollPosition: .None)
                        pushRow.didSelect()
                    })
```

Alternatively you can reload the pushRow (`pushRow.reload()`) when get back to main form view controller. 

Hope it helps!

**Comment by mtnbarreto** [comment]
Look into the code that reloads the selected table view cell from within `FormViewController` `viewWillAppear` method...

```swift
        if let selectedIndexPath = tableView?.indexPathForSelectedRow {
            tableView?.reloadRowsAtIndexPaths([selectedIndexPath], withRowAnimation: .None)
            tableView?.selectRowAtIndexPath(selectedIndexPath, animated: false, scrollPosition: .None)
            tableView?.deselectRowAtIndexPath(selectedIndexPath, animated: true)
        }
```

**Comment by txaidw** [comment]
Thanks for the help! That was not actually my problem, i think i explained poorly.
I had to trigger a push of a PushRow from a button on other cell.
I fixed the problem calling the tableviews methods directly.

```
table.selectRowAtIndexPath(indexPath, animated: true, scrollPosition: UITableViewScrollPosition.None)                        
table.delegate?.tableView?(table, didSelectRowAtIndexPath: indexPath)
```
