### ISSUE TITLE
Smarter table view row deselection

### ISSUE THREAD

**Issue by ZevEisenberg** [xmartlabs/Eureka#405]
Before submitting issues ...

The code in question is here, in `FormViewController` from `Core.swift`. I'm looking at the version on `master` at the time of this writing, which is from commit https://github.com/xmartlabs/Eureka/commit/826d8d9b75b0f3d8890c839360c4f93d7dbb92e8

```swift
public override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    if let selectedIndexPath = tableView?.indexPathForSelectedRow {
        tableView?.reloadRowsAtIndexPaths([selectedIndexPath], withRowAnimation: .None)
        tableView?.selectRowAtIndexPath(selectedIndexPath, animated: false, scrollPosition: .None)
        tableView?.deselectRowAtIndexPath(selectedIndexPath, animated: true)
    }
    NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(FormViewController.keyboardWillShow(_:)), name: UIKeyboardWillShowNotification, object: nil)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(FormViewController.keyboardWillHide(_:)), name: UIKeyboardWillHideNotification, object: nil)
}
```

The problem with this is that if you use an interactive transition to start dismissing the pushed view (so that `self` is reappearing), and then change your mind and cancel the dismissal, the row is still deselected, a subsequent "Back" navigation doesn't show the row deselecting again.

The solution is to use the trick that I outline here: https://gist.github.com/ZevEisenberg/8951478e8c6907bd5e5a

The idea is that you use the transition coordinator to find out if the animation was canceled, and if it was, it reselects the desired rows so that they will still be selected on subsequent dismissal attempts.

**Comment by ZevEisenberg** [comment]
My solution also assumes that you're being dismissed in a navigation controller, which may not be the case always.

**Comment by mtnbarreto** [comment]
@ZevEisenberg Thanks for reporting the issue and provide info to solve it. It seems related with #402. I will look into it and get back to you shortly.

**Comment by mtnbarreto** [comment]
I have not tested in the simulator neither a real device but it seems to me it should work for any transition even custom transitions. Why did you say "My gist also assumes that you're being dismissed in a navigation controller" ?

**Comment by ZevEisenberg** [comment]
@mtnbarreto in the original gist that I linked to, the function takes a navigation controller. When I submitted my PR, I tried using `parentViewController`, and that seemed to work in my nav controller test, but I haven't tried it with modal presentation.
