### ISSUE TITLE
How to change font/color of PushRow values

### ISSUE THREAD

**Issue by stevejcox** [xmartlabs/Eureka#408]
Sorry for the simple question. Just need to know how to access the rows within the view segued to when clicking on the PushRow.

**Comment by mtnbarreto** [comment]
@stevejcox check out this issue #299.

**Comment by stevejcox** [comment]
Thanks man, super helpful - got this to work a treat.

For anyone else coming across this:
.onPresent { from, to in
                    to.selectableRowCellUpdate = { cell, row in
                        print("here")
                        cell.textLabel!.font = ...
                        cell.textLabel!.textColor = ...
                }
            }
