### ISSUE TITLE
Readonly mode as opposed to disabled

### ISSUE THREAD

**Issue by tp** [xmartlabs/Eureka#41]
What do you think of a read-only mode that does not change the appearance to light grey, but does not allow editing either?

The use-case I have in mind is a global "Edit" button, that just enables editing on the form without it changing its appearance.

**Comment by mtnbarreto** [comment]
@tp 
it's not a common scenario. Let's see if someone else ask for it to define if it worth adding it.
Anyway I think you can easily accomplish it by doing:

```swift
        for row in form.rows {
            row.baseCell.userInteractionEnabled = false
        }
```

**Comment by tp** [comment]
Thanks this solves the issue nicely and looks exactly as I would expect from a "read-only" mode. :-)

**Comment by Isuru-Nanayakkara** [comment]
I too would say this is a 'nice to have' feature. I know it's not too dofficult to do the workaround but still it would _look_ clean if I didn't have to call the `baseCell`.

**Comment by davidrft** [comment]
I also think this is a nice to have future. I think this workaround:
`        for row in form.rows {
            row.baseCell.userInteractionEnabled = false
        }`
is not so good because it disables all kinds of interactions with the row, including scrolling, which is a interaction that a readonly mode should be able to handle.

**Comment by radvansky-tomas** [comment]
Not really because if you make row with user interaction == false, then events are not fired, and therefore it cant react to selections...so its not a solution

**Comment by radvansky-tomas** [comment]
So can you extend read-only to fields as well ?

**Comment by gudleyd** [comment]
> Not really because if you make row with user interaction == false, then events are not fired, and therefore it cant react to selections...so its not a solution

Hi, did u solve this problem?

**Comment by radvansky-tomas** [comment]
I've done some PR, wasnt accepted https://github.com/xmartlabs/Eureka/pull/1653

**Comment by itimotin** [comment]
I did in this way
`form +++ Section("DATA")
             <<< TextRow(){
                $0.title = "Code"
                $0.tag = "Code"
                $0.cellSetup { cell, row in
                    cell.textField.isUserInteractionEnabled = false
                }
                }.onCellSelection{cell, row in
                    let iccCodeSectionViewController = CodesTableViewController()
                    self.navigationController?.pushViewController(iccCodeSectionViewController, animated: true)
}
`

for my case I need to move to another view controller, to select multiple values and to return the selected rows back, for start I used MultipleSelectorRow, but I had troubles to display my object in MultipleSelectorViewController. For that I disabled the textfield, and each tap is detected by baseCell and it pushes to CodesTableViewController.
Back I sent data through delegate.

I decided to use this way instead to create my CustomMultipleSelectorRow.
