### ISSUE TITLE
Don't use private/undocumented UIBarButtonSystemItem types

### ISSUE THREAD

**Issue by ZevEisenberg** [xmartlabs/Eureka#411]
From `NavigationAccessoryView`:

```swift
    public var previousButton = UIBarButtonItem(barButtonSystemItem: UIBarButtonSystemItem(rawValue: 105)!, target: nil, action: nil)
    public var nextButton = UIBarButtonItem(barButtonSystemItem: UIBarButtonSystemItem(rawValue: 106)!, target: nil, action: nil)
```

Using undocumented raw values for `UIBarButtonSystemItem` is fragile, and could break in a future iOS update. Rendering or bundling the images in Eureka would be much safer.

**Comment by mtnbarreto** [comment]
@ZevEisenberg I totally agree on this. Do you have time to make the necessary changes?

**Comment by ZevEisenberg** [comment]
Sorry, probably not immediately, but perhaps at some point in the next few weeks. If you can find someone else who can do it, go for it. The easiest would probably be to use the UIKit Artwork Extractor (look on GitHub) to pull out Apple's 1x/2x/3x assets and just use those.

**Comment by VladislavJevremovic** [comment]
I took a humble shot at fixing this as per instructions :) https://github.com/xmartlabs/Eureka/pull/467
