### ISSUE TITLE
why i can't get the form values?

### ISSUE THREAD

**Issue by fuhongbo** [xmartlabs/Eureka#414]
In the example project, i try to get form values, but only get one fields. what's wrong?
![2016-05-09 9 28 42](https://cloud.githubusercontent.com/assets/7901525/15114534/0a89a28a-162d-11e6-8d9f-87e6700c49f3.png)

**Comment by mtnbarreto** [comment]
@fuhongbo Only rows that have a associated tag are added to the values dictionary. 
You can set up a row type either by assigning tag property  `$0.tag = "tagX"` or by passing  the tag as init parameter like `PickerRow<String>("Picker Row")`. 
Row tags must be unique for a particular form.

Hope it helps.
