### ISSUE TITLE
Spaces in TextRow

### ISSUE THREAD

**Issue by bourgeois** [xmartlabs/Eureka#415]
Is it normal that when I enter a space in a TextRow, the cursor jumps to the opposite left ?

Also, when I input multiple spaces in a TextRow, the spaces does not appear until I enter another character.

Thanks!

Environment: XCode 7.3, Eureka 1.5.0

**Comment by mtnbarreto** [comment]
@bourgeois Thanks for reporting the issue. Apparently it's a UIKit issue... 
Why do you you want to start the value with spaces?

**Comment by bourgeois** [comment]
I don't really want this, but I noticed it and thought about reporting the issue so it can be documented.

However, maybe the issue when entering multiple spaces between words is a bigger concern.

**Comment by mtnbarreto** [comment]
@bourgeois if we change the alignment of the text field form right to left this does not happens. Also seems a UIKit issue 😱.

**Comment by mtnbarreto** [comment]
I donlt know which it he correct path to take, for me this are UIKit issues and should not be explained into Eureka readme.

**Comment by bourgeois** [comment]
Got it, actually we can really easily experience the issue with a single `UITextFIeld` application with text aligned to right.

No problem, you can close this issue !
