### ISSUE TITLE
TextArea pre filled information weird behavior

### ISSUE THREAD

**Issue by fnk0** [xmartlabs/Eureka#42]
1st of all thank you so much for this fantastic library!!

I'm experience a strange bug. So for this app I'm developing the user submits data to the server with each picture taken. To speed up future submissions is the app saves the previous user input. Everything works fine except for the TextArea row. Here's a screenshot of the behavior.

Here is how I'm instantiating the row:

```swift
let notesRow = TextAreaRow() {
   $0.placeholder = "Your notes goes here..."
   if let v = self.defaults.valueForKey(Const.D_NOTES) as? String {
       $0.value = v
       self.data.notes = v
   }
}
```

Any ideas how to fix?

![img](https://photos-5.dropbox.com/t/2/AAAVZkK9R4aIlz_1P8wp0HJiq8jbwFKT6QYPvBMbfj-5bw/12/144318787/png/32x32/1/1445277600/0/2/Screenshot%202015-10-19%2011.14.29.png/CMPC6EQgASACIAMgBSAHKAIoBw/LTODHSrxZRnhNz1wAG_DYQW3Sho41R0hZ1Mx6JxiOzE?size=1280x960&size_mode=2)

**Comment by mtnbarreto** [comment]
@fnk0 it seems that the link is broken. 

Probably your issue is the same as this: https://github.com/xmartlabs/Eureka/issues/1. If not let me know.

regards
