### ISSUE TITLE
PostalAddressRow: When a long form is scrolled up/down, values in Address box disappears

### ISSUE THREAD

**Issue by vijeshjain** [xmartlabs/Eureka#423]
Hello @marbetschar ,

I have used PostalAddressRow in one of my forms. While filling all the information in a long form, when user scrolls up/down, values in the Address box disappears. 
And when that form is submitted for passing the whole data to another view controller, values are null for the Address tag.

- Environment: Eureka v1.5.0, Xcode Version 7.3 (7D175) and iOS, Swift v2.0

BTW, I liked all Eureka features, it is really helpful for faster prototype development.
Thanks:)

**Comment by mtnbarreto** [comment]
@marbetschar Could you look into this?

**Comment by marbetschar** [comment]
@vijeshjain  @mtnbarreto 

I'l check this out this weekend.

**Comment by vijeshjain** [comment]
@marbetschar : Sounds good, thanks:)

**Comment by marbetschar** [comment]
Just opened a pull request with a fix for this issue.

Basically the `PostalAddressRow` was designed to allow you to use your own `PostalAddressType` object which stores the postal address information. The builtin `PostalAdress` is a generic `PostalAddressType` and was meant to be set on row initialization:

```
<<< PostalAddressRow(){
  ...
  $0.value = PostalAddress()
}
```

The error occured, if this assignment wasn't made and therefore `$0.value` was `nil`. I've added a fallback for this behaviour, so `PostalAddressRow` uses the builtin`PostalAddress` if no `PostalAddressType` was set before.
