### ISSUE TITLE
Spaces not visible in right-aligned rows when editing text

### ISSUE THREAD

**Issue by heptal** [xmartlabs/Eureka#424]
Now this isn't a issue unique to Eureka, but perhaps there should be a default or an easy way to toggle this behavior for right-aligned text fields? It's definitely off-putting (to me) when typing.

http://stackoverflow.com/questions/19569688/right-aligned-uitextfield-spacebar-does-not-advance-cursor-in-ios-7/22512184#22512184

http://stackoverflow.com/questions/22232884/space-at-end-of-text-not-visible-in-right-aligned-uitextfield

I'm doing this which works for now (in reality should put normal spaces back when finished editing). Is there a better/cleaner way?

``` swift
class MyViewController: FormViewController {
    func replaceNormalSpacesWithNonBreakingSpaces(textField : UITextField) {
        textField.text = textField.text?.stringByReplacingOccurrencesOfString(" ", withString: "\u{00a0}")
    }
    override func viewDidLoad() {
        super.viewDidLoad()

        form +++ Section("MySection")
        <<< TextRow("title") {
             $0.title = "Title"
             $0.placeholder = "Title"          
        }.cellSetup {cell, row in
             cell.textField.addTarget(self, action: #selector(MyViewController.replaceNormalSpacesWithNonBreakingSpaces), forControlEvents: .EditingChanged)
        }
...
```

**Comment by lognaturel** [comment]
I would also very much appreciate a built-in approach for getting this behavior.

**Comment by prine** [comment]
Yep, would also appreciate an built-in solution for that. @heptal Thanks for the workaround!

**Comment by marcosgriselli** [comment]
@heptal nice workaround.

**Comment by hannesoid** [comment]
Thanks guys for this workaround - here's an updated version for Swift3.
Call `EurekaWhitespaceWorkaround.configureTextCells()` to use it.
https://gist.github.com/hannesoid/ed78904e33a362889d2bd38f2f09ec3b

**Comment by CeceXX** [comment]
Hi guys, how am I supposed to use this workaround? I don't see the `defaultCellSetup` closure for my text row. Any hints? Thanks!

@hannesoid 
@heptal

**Comment by mtnbarreto** [comment]
This seems to be a iOS issue so we will not add any workaround in Eureka. Everyone facing the issue can easily add the workaround.

Regards

**Comment by StephanKornerTrihow** [comment]
@lognaturel : can you please show FormHelper class ? Thank you
