### ISSUE TITLE
Use of unresolved identifier "..."

### ISSUE THREAD

**Issue by FateRiddle** [xmartlabs/Eureka#425]
Pod file:
`
platform:ios, ‘9.1’
use_frameworks!

target ‘AnZhuang’ do
source 'https://github.com/CocoaPods/Specs.git'
pod 'Eureka', '~> 1.5'
end
`

Then I copy paste sample code :
`import Eureka

class CustomCellsController : FormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        form +++ Section("Custom cells")
                    <<< WeekDayRow(){
                        $0.value = [.Monday, .Wednesday, .Friday]
                    }
                    <<< TextFloatLabelRow() {
                        $0.title = "Float Label Row, type something to see.."
                    }
    }
}`

Error shown: Use of unresolved identifier "WeekDayRow", use of unresolved identifier "TextFloatLabelRow", why?

**Comment by mtnbarreto** [comment]
`WeekDayRow` and `TextFloatLabelRow` are custom rows included in the library example project. In order to use them you will have to copy past their code into your app.

**Comment by TCOA** [comment]
Could you please be more detailed in "you will have to copy (paste?) their code into your app"?

Both in trying to copy the code into my viewController.swift page (where I wanted to use this) as well as copying the file FloatLabelTextField.swift into the project resulted in the same error (Use of unresolved identifier "TextFloatLabelRow")

Where do we need to put the code to get this working?  These two features are highly desirable for our app, though not sure how to make them work.

Details would be most appreciated (for us that are new to xcode and swift - and especially for a long-time programmer that's been forced to learn it toward the end of his career!).  Thanks!
