### ISSUE TITLE
Public repository for custom rows

### ISSUE THREAD

**Issue by SASDOE** [xmartlabs/Eureka#426]
Some way of allowing users to publish their custom rows would be greatly appreciated. I think many users have implemented their custom rows and believe it would be great to allow them to share these rows easily.

**Comment by mtnbarreto** [comment]
It's not official yet but you can share it under this organization.. https://github.com/EurekaCommunity.

**Comment by mtnbarreto** [comment]
I just invited you to the organization. Please add a exhaustive documentation, example project and tests.
