### ISSUE TITLE
Problem with LocationRow and pinView

### ISSUE THREAD

**Issue by ins0u** [xmartlabs/Eureka#429]
Hello,

I'm testing "LocationRow" and it's work but I have a little problem

I haven't the "pinView" like the example.

![bug](https://cloud.githubusercontent.com/assets/12513250/15323613/2bd3ac80-1c43-11e6-9169-5b3e7e53283d.png)

In MapViewController, there is : 
`v.image = UIImage(named: "map_pin", inBundle: NSBundle(forClass: MapViewController.self), compatibleWithTraitCollection: nil)`

So, i added in the assets, the same "map_pin" (like your example) and it's doesn't work :/
Have you an idea why the pinView doesn't appear ?

Thank you for your help :)

**Comment by ins0u** [comment]
Ok, i'm stupid.
I added in the assets to my project but it was in the assets to Eureka project.
It works now :D

**Comment by engmsaleh** [comment]
I have doubled checked and I couldn't find it anywhere.

**Comment by solohan83** [comment]
if you import any image call map_pin.png into your xCode asset folder, the mark will show up.

The problem is, does not matter what png you import, the mark will always be the same blue circle drop pin.
