### ISSUE TITLE
Section's title and description with NSLocalizedString

### ISSUE THREAD

**Issue by litmisty** [xmartlabs/Eureka#43]
```
Section(NSLocalizedString("Title", comment: "Title"))
```

I want to create section with ```NSLocalizedString``` but it doesn't allow to do it.
The error is below
```Cannot invoke initializer for type 'Section' with an argument list of  type '(String)'```

**Comment by phiberjenz** [comment]
I can't tell exactly why it is like this, but here's my work-around:

<code>let newSection = Section(HeaderFooterView<UIView>(NSLocalizedString("Title", comment: "Title")))</code>

**Comment by litmisty** [comment]
It yields this error
```Ambiguous reference to member 'HeaderFooterView<ViewType>.init'```
I'm using Xcode 7.0.1

**Comment by phiberjenz** [comment]
Yep it does, this is the correct code:

<code>let newSection = Section(HeaderFooterView<UIView>(stringLiteral: NSLocalizedString("Title", comment: "Title")))</code>

Sorry about that.

**Comment by litmisty** [comment]
It works! Thank you. :+1:

**Comment by mtnbarreto** [comment]
@litmisty Thanks for helping out! 👍
Even though this is the way to pass a `NSLocalizedString` as section title constructor parameter I think we will need to add a convenience initializer to `Section` class to make this easier.
