### ISSUE TITLE
PickerInlineRow at bottom expands below table view

### ISSUE THREAD

**Issue by LordAndrei** [xmartlabs/Eureka#430]
I have a standard picker row. It is at the penultimate section. When I expand it, the picker expands down and can't be seen unless the form is scrolled upwards.

I tried:
```
.onExpandInlineRow {...()in
    let indexPath = pickerInlineRow.indexPath()
    if indexPath != nil {
        tableView!.scrollToRowAtIndexPath(indexPath!, atScrollPostion: .Top, animated: true)
    }
}
```
I've also tried .Middle and .Bottom. None of these three work. Bottom actually makes it worse.

Is the onExpandInlineRow happening before the expand?  If so, is this a bug or is there a quick fix?

Thank you.
-Andrei

**Comment by mtnbarreto** [comment]
`onExpandInlineRow ` is invoked before adding the inline row so it's not going to work.

**Comment by chriswill0w** [comment]
why was this closed? what is the solution? I have the same problem
