### ISSUE TITLE
LocationRow and fixed pinView ?

### ISSUE THREAD

**Issue by ins0u** [xmartlabs/Eureka#432]
Hello,

I'm testing "LocationRow" and it's work but I have a (another :p) little problem..

How to make a fixed pinView ?
Which doesn't move when i move the map ?

I retrieves coordinates via json and I would display the pinView on the map (except that when I move the map, the pinView move too and modifies the original data)

Have you an idea ?
Thank you for your help (and sorry for my bad English..) :)

**Comment by mtnbarreto** [comment]
Hey @inket, 
Could you elaborate more on what you want to accomplish?
LocationRow shows a centered pin that represent the location value so the location value is updated whenever the map center changes.

Which gesture do you want to use to update the location value? Drag gesture on the pin? 
I understood that you don't want to update the location when the center of the map changes. Could you confirm?

**Comment by ins0u** [comment]
Hello @mtnbarreto ,

I confirm, i don't want update location value.
It's just to see the location on the map via GPS coordinates (lat/lng)

I think I should create a derivative of LocationRow to adapt the behavior to not update the value, just show the pinView withouh updating value when i move the center.

Thank you for your interest :)

**Comment by mtnbarreto** [comment]
@ins0u You can use `ButtonRowWithPresent` which allows us to present a view controller and it passes the row to the presented view controller. You will have to use the row value to display the pin from your map view controller.


```swift
public final class ButtonRowWithPresent<T: Equatable, VCType: TypedRowControllerType where VCType: UIViewController, VCType.RowValue == T> : _ButtonRowWithPresent<T, VCType>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}

```

`VCType` generic type which is the presented view controller must conforms to `TypedRowControllerType`. Your `VCType` will be something similar to `MapViewController` but should actually add a pin into the map (MapViewController just adds a centered image view to the map without using a map annotation). 

In your case you will have to add the annotation to the map by..

```swift
let anon = Annotation()
anon.coordinate = row.value
mapView.addAnnotation(anon)

//You may also want to provide a view for the annotation
optional public func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView?`.
```


How to work with MKMapView is out of Eureka scope but this should be enough to get this work.

**Comment by ins0u** [comment]
Thank for your help :)

Meanwhile, I did several test and found a solution.
It doesn't use directly Eureka but Maps.
It moves away a little of the subject but I post anyway if other people are interested : 

```
let Latitude = item["valeur","Latitude"].stringValue
let Longitude = item["valeur","Longitude"].stringValue
form.last! 
     <<< LabelRow () {
            $0.title = "My title"
            $0.value = "📍"
      }.onCellSelection({ (cell, row) in   
             openMapForPlace("Pins",latitude: Latitude, longitude: Longitude) 
 })
```

```
func openMapForPlace(name: String, latitude : String, longitude : String) {
        
        let lat1 : NSString = latitude
        let lng1 : NSString = longitude
        
        let latitute:CLLocationDegrees =  lat1.doubleValue
        let longitute:CLLocationDegrees =  lng1.doubleValue
        
        let regionDistance:CLLocationDistance = 10000
        let coordinates = CLLocationCoordinate2DMake(latitute, longitute)
        let regionSpan = MKCoordinateRegionMakeWithDistance(coordinates, regionDistance, regionDistance)
        let options = [
            MKLaunchOptionsMapCenterKey: NSValue(MKCoordinate: regionSpan.center),
            MKLaunchOptionsMapSpanKey: NSValue(MKCoordinateSpan: regionSpan.span)
        ]
        let placemark = MKPlacemark(coordinate: coordinates, addressDictionary: nil)
        let mapItem = MKMapItem(placemark: placemark)
        mapItem.name = "\(name)"
        mapItem.openInMapsWithLaunchOptions(options)
        
    }
```
