### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by piercifani** [xmartlabs/Eureka#437]
Hello all,

First of all, congratulations on this awesome library and it's design using key Swift features. I'm really amazed of how this project is set up and executed.

I want to discuss one key missing feature: form validation. Is there any ETA on when it'll be included? Or it's not in your roadmap right now? 

If it's not in your roadmap right now, I'd like to propose an API design and also start working on it and file a PR when it's ready.

If, however, you already have something on your mind, I'd leave it up to you to implement this important missing functionality.

Let me know what you think!

**Comment by mats-claassen** [comment]
Hi @piercifani Thanks for your comments. We are planning to do this rather sooner than later.

For now people are using external validators. Have a look at #47 

I will close because this is duplicated there.
