### ISSUE TITLE
Edge-to-edge cell separator / margin bug with picker rows

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#438]
When setting up code to allow for edge-to-edge separators, any picker rows (date, generic, etc.) do not conform to the newly set rules.

        tableView!.layoutMargins = UIEdgeInsetsZero
        tableView!.separatorInset = UIEdgeInsetsZero

        TestRow.defaultCellSetup = { cell, row in
            cell.contentView.layoutMargins.left = 0
            cell.layoutMargins = UIEdgeInsetsZero
            cell.datePicker.layoutMargins = UIEdgeInsetsZero
            cell.preservesSuperviewLayoutMargins = false
        }

Example below:

![eureka_margin_bug](https://cloud.githubusercontent.com/assets/18575720/15394343/76f32c1e-1da0-11e6-9cf0-5c5baea88d8e.png)

Edit: Is there any way to preserve actual text margins and ONLY make the separator line edge-to-edge? I've tried every imaginable combination of settings on the tableView and cell itself, but I can't get it to work right.

**Comment by mtnbarreto** [comment]
I have never tried to change the cell margin yet. 
Could you provide me more info about what you want to do, what you expect and what you got. 
Have you implemented `TestRow` ? 
Please point out the issue on image provided.

**Comment by plastus** [comment]
That's "TextRow"...sorry, my mistake when typing up the code.

I'm trying to get this look:

![1-qcz0bkm73uwqwj_cie14sq](https://cloud.githubusercontent.com/assets/18575720/15427157/1332b264-1e61-11e6-8f7f-4d4631311886.png)

What happens when I use the commonly referenced ways of accomplishing this is that not all the rows conform to the zero inset margin. Ideally I would want to retain the actual text margins from left/right as they are by default in Eureka, and ONLY extend the cell separator so that it spans the entire width of the screen.

**Comment by mtnbarreto** [comment]
Try using this code...

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        tableView?.separatorInset = UIEdgeInsetsZero //  Add this line on each FormViewController
        // ... 
     }


// The following code should be executed before loading any form view controller. 
// It will set up layout properties for the whole app. Missing rows/custom rows types should be added. 
// I tested it against Eureka example app and it works like a charm.

      ImageRow.defaultCellUpdate = { cell, row in
           cell.accessoryView?.layer.cornerRadius = 17
           cell.accessoryView?.frame = CGRectMake(0, 0, 34, 34)
        }
 
        TextRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.contentView.preservesSuperviewLayoutMargins = false
            cell.contentView.layoutMargins.left = 50
        }
        
        ButtonRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }
        
        SwitchRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }
        
        DateTimeInlineRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }

        
        DateRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }
        
        DateTimeRow.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }

        PickerInlineRow<NSDate>.defaultCellSetup = { cell, row in
            cell.preservesSuperviewLayoutMargins = false
            cell.layoutMargins.left = 0
            cell.indentationLevel = 5
        }
```

As you may have seen, `indentationLevel` does not work for every cell and sometimes `cell.contentView.layoutMargins.left = 50` should be as `TextRow.defaultCellSetup` shows.  I think this is because `TextRow` cell is not a pure build-in cell, we are making some changes on textLabel, in particular in its constraint.

Let me know if this works.

**Comment by plastus** [comment]
Thanks, I wasn't able to get the Date/Picker rows to allow zero margins with any combination of properties on the cell/contentview, etc. So what I did was approximate what the gap is on the left (~15px) and set all the other cells to use that for the left/right margins. I think it looks better anyway, because it gives it a slight indentation underneath the header/section.

End result is that I have edge-to-edge separators and I maintained the default padding on left/right. :) :+1:

**Comment by plastus** [comment]
I wasn't able to get DateRow/PickerInlineRow to allow zero margins. So what I did was use those two cell types as a baseline for the least amount of left margin that I could do alongside the edge-to-edge cell separators. It turns out to be ~15px. I did 15px left/right margins and I think it looks really good with the screen width separators. :)

**Comment by mats-claassen** [comment]
Headers and footers are managed by UIKit if you use a simple string. If you use custo =m views then you should be able to align it to your rows.

Anyway we have fixed some misalignments since this issue was opened. I will close this issue. If any new issue arises please open a new one.
