### ISSUE TITLE
How to get all row rows from one section ?

### ISSUE THREAD

**Issue by havocked** [xmartlabs/Eureka#44]
Say we got a section "Loans" with multiple rows.

Section 1 tag: Loans
- row Loan 1 value: 10000
- row Loan 2 value: 20000
- row Loan 3 value: 30000

Would it be possible to do that kind of stuff ?

```swift
var section: Section?  = form.sectionByTag("Loans")
//Get all rows / values in this section ?
```

Anyway, Thanks for this great library !

**Comment by mtnbarreto** [comment]
I'm not sure if i understood the question. 

`Section` is a collection of `BaseRow` (row base class) and conforms to `CollectionType` so having a `Section` you can iterate over its row by:

```swift
//let section: Section
for let row in section {
  let value: Any? =  row.baseValue
}
```

or you can get an array containing its rows by:

```Swift
let rows = section.map { $0 }
```

There are much more methods added by the `CollectionType` protocol extension. Look at this post ([Swift Collection Protocols](http://nshipster.com/swift-collection-protocols/)) to know other methods that can be invoked to `Section` or `Form` instances.

**Comment by RowanG1** [comment]
Note that in order for the above functions that mtnbarreto  posted on 21 Oct 2015 to work, the section must be unwrapped.
