### ISSUE TITLE
How do you update formValues automatically when data in one row is changed?

### ISSUE THREAD

**Issue by FateRiddle** [xmartlabs/Eureka#441]
my code is like:

             class HomeViewController : FormViewController {
                override func viewDidLoad() {
               super.viewDidLoad()
              form +++ DateInlineRow() {
              $0.title = "start"
              $0.value = NSDate()
              $0.tag = '"start"
            } 

        <<< DateInlineRow() {
            $0.title = "end"
            $0.value = NSDate()
            $0.tag = '"end"
        }
        <<< PushRow<String>() {
            $0.title = "Type"
            $0.options = ["all", "1", "2", "3", "4"]
            $0.value = "all"
            $0.selectorTitle = "Type："
            $0.tag ="type"
        }
        <<< ButtonRow("Button\(index)") { $0.title = "search: " }
    }
    let formValues = self.form.values()
}

`formValues` returns all the values in table in a dictionary. How do I update that value whenever I pick something in pushRow or scroll the datePick of DateInlineRow?

**Comment by mtnbarreto** [comment]
After making a change on a form value (row value) you should invoke again `form.values()` to get the updated values. 

Eureka creates values dictionary each time `form.values()` is invoked:

```swift
    /**
     Method used to get all the values of all the rows of the form. Only rows with tag are included.
     
     - parameter includeHidden: If the values of hidden rows should be included.
     
     - returns: A dictionary mapping the rows tag to its value. [tag: value]
     */
    public func values(includeHidden includeHidden: Bool = false) -> [String: Any?]{
        if includeHidden {
            return allRows.filter({ $0.tag != nil })
                .reduce([String: Any?]()) {
                    var result = $0
                    result[$1.tag!] = $1.baseValue
                    return result
            }
        }
        return rows.filter({ $0.tag != nil })
            .reduce([String: Any?]()) {
                var result = $0
                result[$1.tag!] = $1.baseValue
                return result
        }
    }
```
