### ISSUE TITLE
TextAreaRow issue

### ISSUE THREAD

**Issue by zhouzq-thu** [xmartlabs/Eureka#442]
There is a problem about TextAreaRow. If a gradient layer is added to the tableview, the TextAreaRow has a white color background. This can be fixed by adding `textView.backgroundColor = UIColor.clearColor()` in the `update()` func.

[before]
![before](https://cloud.githubusercontent.com/assets/9458157/15431321/db18857c-1edb-11e6-852a-a57bfb878e02.jpg)

[after]
![after](https://cloud.githubusercontent.com/assets/9458157/15431323/e086c438-1edb-11e6-82e0-599c80b8820e.jpg)

**Comment by mtnbarreto** [comment]
@zhouzq-thu Thanks for pointing this out. 

Apparently white is the default text view color since we're not setting up this property. You can change the background using wither `cellSetup` or `defaultCellSetup` callbacks since cell update method doesn't override it.


```swift

// change the text view background color of all `TextAreaRow`s
TextAreaRow.defaultCellSetup` = { cell, row in 
            cell. backgroundColor =.clearColor()
}

//or change the color of a particular row 
let textAreaRow: TextAreaRow = ...
textAreaRow.onSetup { cell, row in 
   cell. backgroundColor =.clearColor()
}

```

> For more information about callbacks take a look at https://github.com/xmartlabs/Eureka#customization.
