### ISSUE TITLE
Can't compile the latest version

### ISSUE THREAD

**Issue by MHX792** [xmartlabs/Eureka#443]
Using latest Xcode Version:

![screen shot 2016-05-20 at 18 08 06](https://cloud.githubusercontent.com/assets/12123471/15434184/ff198dac-1eb5-11e6-8197-56b29572e599.png)

**Comment by mtnbarreto** [comment]
Use master branch for now, I'm gonna release a new version shortly.

**Comment by MHX792** [comment]
I think I have done so by using pods? Sorry, I am quite new to github.

**Comment by mtnbarreto** [comment]
Take a look at these reference which explains how to use repository master branch... https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by mtnbarreto** [comment]
Apparently  lastest Eureka release which is 1.5.0 works fine on  Xcode 7.3.1. Could you check which version are you using?

**Comment by MHX792** [comment]
No updates showed up, when I checked the App Store. Probably because I installed an older version from outside the App Store. Nevertheless I still cannot update to Xcode 7.3.1 because I run OS X 10.10. Can you confirm that Eureka 1.5.0 does **not** support Xcode 7.2.1 (the latest for 10.10)?

**Comment by MHX792** [comment]
Update: Reinstalling Xcode 7.2.1 did not solve the issue, but reverting back to Eureka 1.4.1 did.

**Comment by mtnbarreto** [comment]
Eureka 1.5.1 only works on XCode 7.3.1 and up.
