### ISSUE TITLE
modify data source of PushRow

### ISSUE THREAD

**Issue by zhouzq-thu** [xmartlabs/Eureka#444]
Is there a method that we can edit (insert or delete) row in the SelectorViewController, which is presented by a PushRow? Or modify the data source of PushRow in the its popViewController.

**Comment by mats-claassen** [comment]
To do that you need to get hold of the controller that is pushed by the PushRow.
I think the best way is to create a custom `SelectorViewController` and implement its logic there.
You could also get the pushed view controller using the `onPresent` callback
