### ISSUE TITLE
Displaying integer values on SliderRow

### ISSUE THREAD

**Issue by volkanx** [xmartlabs/Eureka#446]
Hi,
I'm trying display the integer values instead of float. I tried the following: 

            $0.onChange { row in
                let isInteger = floor(row.value!) == row.value!
                if (!isInteger) {
                    row.value = floor(row.value!)
                }
                
                let formattedString = String(format: "%.0f", row.value!)
                row.cell.valueLabel.text = formattedString
            }

formattedString displays the values I want but I'm not able to display them on the screen. I can access all other attributes by row.cell. I change change the text colour, for instance, but not the text. I'm guessing I'm setting the text but it gets overwritten shortly.

Is there a way to make the slider show integer values?

Thanks.

**Comment by mtnbarreto** [comment]
Could you please post these kind of questions on stackoverflow as readme points out. 

This is the SliderRow type declaration.... if you set up `steps` to maximumValue - minimumValue you will get it work. 

```swift
public final class SliderRow: Row<Float, SliderCell>, RowType {
    
    public var minimumValue: Float = 0.0
    public var maximumValue: Float = 10.0
    public var steps: UInt = 20
    
    required public init(tag: String?) {
        super.init(tag: tag)
    }
}
```

Let me know if this works.

**Comment by volkanx** [comment]
Asked it on SO: [http://stackoverflow.com/questions/37451191/displaying-integer-values-on-sliderrow](http://stackoverflow.com/questions/37451191/displaying-integer-values-on-sliderrow)

Thanks.

**Comment by volkanx** [comment]
I cloned your repository and put print statements. Looks like I set the value correctly in the onChange handler but valueChanged() gets called afterwards and sets the value again overwriting my value. Is this by design or a bug? 

I solved my issue by just creating an integer version of SliderRow (and StepperRow which has the same issue) as I explained in the StackOverflow post linked above.
