### ISSUE TITLE
Using PushRow when inside a child view

### ISSUE THREAD

**Issue by stevejcox** [xmartlabs/Eureka#447]
I have a Form created within a child view controller, which is all woking nicely - with one exception, push rows.

Any advice on how I can adjust the pushrow so on click it doesn't push an entire new View, but keeps it within the child container?

Thanks in advance

**Comment by volkanx** [comment]
I'm having the same issue with the form inside a container. I couldn't find a solution so had to switch to alertrow

**Comment by mats-claassen** [comment]
You should have a look at the [`presentationMode`](https://github.com/xmartlabs/Eureka/blob/922e28dfba9e69c984b19cc9b7e5d7687bd255c9/Source/Core/Core.swift#L134) property of the selector rows. If no way of presenting your view controller suits you then you can still create your [custom SelectorRow](https://github.com/xmartlabs/Eureka#implementing-a-custom-presenter-row-selectorrow-pushrow-imagerow-etc-).

**Comment by volkanx** [comment]
Thanks @mats-claassen . Actually I don't present a view controller, I just provider the pushrow with a list of names and it displays them. But I guess I'll have to create my own view controller anyway to customize it.

**Comment by mats-claassen** [comment]
Could you find a solution @volkanx ?

**Comment by volkanx** [comment]
@mats-claassen Actually because of time concerns I decided to go with an inline picker which gives me what I need for the time being so I didn't spend much time in resolving that issue.

**Comment by mats-claassen** [comment]
If anyone has this issue, it should be solved by changing the `presentationMode` of the PushRow to do something else than pushing (e.g. like presenting modally).
