### ISSUE TITLE
Eureka crashes app when trying to scroll an empty PickerRow

### ISSUE THREAD

**Issue by bourgeois** [xmartlabs/Eureka#450]
Currently using Eureka 1.5.0 with XCode 7.3.1

I am experiencing crashes when trying to scroll in an empty PickerRow (index out of bounds). 

I see that there is no check to make sure there is actually something in the array before setting it. For some reason the variable `row` is set to 0 in the code below, while there is no element in the array. 

For that reason, the app crashes when trying to scroll empty picker.

    public func pickerView(pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        pickerRow?.value = pickerRow?.options[row]
    }

Why this block gets called when `options` is an empty array ? There is no row to select ?

**Comment by mtnbarreto** [comment]
PickerRow should not be used with an empty options array. I think it doesn't make any sense. 
Why are you using it in this way?

**Comment by bourgeois** [comment]
I'm populating a PickerRow based on an other field input, and one of the cases is that the picker is empty, if it does not applies.

Should I just disable or hide the field in that case, then ?

**Comment by plastus** [comment]
@bourgeois I'm working with an API that may send an empty list that goes into PickerRow. If it's empty, I just set the picker row options to " " which shows as an blank space. Then, if you're submitting the form's values you can check whether the value is equal to that placeholder which would mean the picker wasn't populated with any actual choices.

**Comment by bourgeois** [comment]
That is exactly the problem I am facing. I guess I will do something like that.

Thanks for your input @plastus !

**Comment by bourgeois** [comment]
I forked the repo and added a check in that method @plastus, if you are interested.

https://github.com/coemobile/Eureka/commit/250278b8afc6927706eacbf26647c2c9084ffd61

**Comment by mtnbarreto** [comment]
I think you should hide the picker view when there is no option to show.
