### ISSUE TITLE
Error updating pod version 1.6

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#458]
Hi Guys,

I'm having issues updating pods to 1.6

[!] Unable to satisfy the following requirements:

- `Eureka (~> 1.6)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Eureka (~> 1.6)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

i can install 1.5.0 without specifying version

**Comment by mtnbarreto** [comment]
@kohdesmond, Now it should be fixed. 
I had not pushed the new pod version to pod trunk.

**Comment by kohdesmond** [comment]
@mtnbarreto  thanks mate! is all good now.

by the way, is there anyway to get the frame size of the onExpandInlineRow? all i got is 44 instead of the picker height.
