### ISSUE TITLE
How to create multi columns custom section?

### ISSUE THREAD

**Issue by dakhu** [xmartlabs/Eureka#461]
Hi, I'm trying to create a form similar to edit contact form like the image below which has a preview and edit button on left hand sign and 3 text inputs on the right hand side, but I'm not sure where to start since I couldn't find anything in the doc which set width and alignment of row. Thanks
![2014-05-31-16 53 40-bordermaker](https://cloud.githubusercontent.com/assets/11477001/15592154/574cd67c-2399-11e6-918e-1a64deeafed4.jpg)

**Comment by mtnbarreto** [comment]
The only way to implement these rows is through custom rows. Please take a look at the doc reference (we are currently updating it) and the example project rows.
