### ISSUE TITLE
How to change DateInlineRow picker background and tint color

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#462]
Hi @marbetschar 

as title, it there a way to change DateInlineRow picker background and tint color?

Cheers

Des

**Comment by mtnbarreto** [comment]
You should use `onExpandinlineRow` and change the picker tint and background from here. Inline cell is passed as a clousure parameter. 
We can also change all DatePickerRows using `defaultCellUpdate`.
```swift
DatePickerRow.defaultCellUpdate = { cell, row in
  ..
}
```

**Comment by mtnbarreto** [comment]
If you go for `onExpandInlineRow` approach, take a look at #321 that may help.

**Comment by kohdesmond** [comment]
@mtnbarreto  thanks for the quick reply.

i ended used this:

TimeInlineRow.InlineRow.defaultCellSetup = {cell, row in
            cell.backgroundColor = UIColor.clearColor()
            cell.datePicker.setValue(self.goldColor(), forKey: "textColor")
            let pickerbg = self.createBG(self.kPickerBG)
            cell.datePicker.addSubview(pickerbg)
            cell.datePicker.sendSubviewToBack(pickerbg)
        }

to get this output: https://dl.dropboxusercontent.com/u/418769/Screen%20Shot%202016-05-31%20at%2009.40.22.png

I realised that the memory will increase whenever i open the inline picker. I tried to loop the datepicker subview with tag to prevent additional addSubview if tag found but to no avail.

**Comment by mtnbarreto** [comment]
Where are you setting up `TimeInlineRow.InlineRow.defaultCellSetup`?

**Comment by kohdesmond** [comment]
@mtnbarreto , I called setFormSettings() and createForms() in viewDidLoad()


 func setFormSettings()
    {

 TimeInlineRow.defaultCellSetup = {cell, row in
            cell.height = {self.kCellRowHeight}
            row.minimumDate = NSDate()
            row.maximumDate = NSDate().dateByAddingTimeInterval(60*60*25*60)

            cell.textLabel?.textColor = self.smuSISColor()
            cell.detailTextLabel?.textColor = self.appTextColor()
            cell.tintColor = self.smuSISColor();
            cell.backgroundColor = UIColor.clearColor();
            let bg = self.createBG(self.kCellBGViewHeight)
            cell.addSubview(bg)
            cell.sendSubviewToBack(bg)
        }
        
        TimeInlineRow.InlineRow.defaultCellSetup = {cell, row in
            cell.backgroundColor = UIColor.clearColor()
            cell.datePicker.setValue(self.smuSISColor(), forKey: "textColor")
            
            let pickerbg = self.createBG(self.kPickerBG)
            pickerbg.tag = 99
            cell.datePicker.addSubview(pickerbg)
            cell.datePicker.sendSubviewToBack(pickerbg)
        }
        
        TimeInlineRow.defaultCellUpdate = {cell, row in
            cell.detailTextLabel?.textColor = self.smuSISColor()
            cell.textLabel?.textColor = self.appTextColor()
            cell.selectionStyle = .None
        }
}

 func createForms()
    {
        
        form =
            
            Section()
            { section in setSectionHeader(section, title: "Task Details") }
            
 +++ Section("Task Timing")
            <<< DateInlineRow() {
                $0.title = "Start Date"
                $0.value = NSDate()
                }
            
            <<< TimeInlineRow("Start Time"){
                $0.title = "Start Time"
                $0.noValueDisplayText = "-:--"
                }

            <<< TimeInlineRow(){
                $0.title = "End Time"
                //$0.value = "-:--"
                $0.noValueDisplayText = "-:--"
                $0.hidden = Condition.Function(["Start Time"], { form in
                    if let row : TimeInlineRow = form.rowByTag("Start Time")
                    {
                        return row.value == nil
                    };
                        return true
                    })
                }
}

override func viewDidLoad() {
        super.viewDidLoad()
        tableView?.separatorStyle = .None
        tableView?.backgroundColor = appBackgroundColor()
       // tableView?.sectionHeaderHeight = kHeaderViewHeight + kOffset * 2
        self.title = "New Task"
        
        setFormSettings()
        createForms()
        
        
    }

**Comment by mtnbarreto** [comment]
`defaultCellSetup` implementation should not depend on self since this closure is invoked for all `FormViewController` instances and would be released.

**Comment by kohdesmond** [comment]
@mtnbarreto withoutself, i will get Reference to property 'kPickerBGHeight' in closure requires explicit 'self.' to make capture semantics explicit

`let kPickerBGHeight:CGFloat = 205`

**Comment by minuscorp** [comment]
So I think you have three main choices here:

- You weakly capture `self` in that `defaultCellSetup` closure (that will cause weird things happen to other rows being created when self is being released)

- On `form` creation and configuration time, access to their proper `cellSetup` and such methods to configure one by one each one of your rows.

- Create a separate singleton or `class func` holder to gently gather the necessary information to configure your rows by rewriting the `default...` methods on each your `form` instances.

**Comment by kohdesmond** [comment]
Thanks for your help :)
