### ISSUE TITLE
Scroll to expanded inline row

### ISSUE THREAD

**Issue by Daniesy** [xmartlabs/Eureka#464]
Hey everybody!
I've tried implementing a way to scroll to the expanded inline row but i hit a brick wall: `onExpandInlineRow` is called before the row is inserted, so any code that would make the table scroll to the inline row will fail, because its indexPath is nil. Is there any way to solve this without delaying the scroll code execution? I guess that callbacks after the row insert animation should be added...

Keep up the good work guys! 
Kind regards,
Dan

**Comment by mtnbarreto** [comment]
I think this was fixed in 1.6.0 version. Which version are you using?

**Comment by Daniesy** [comment]
Thanks for the reply. I guess i'm using 1.5.0. This is the version i got from CocoaPods. I'll try to update to 1.6.0 and come back at ya!

**Comment by Daniesy** [comment]
It works great on 1.6.0. Thanks!
