### ISSUE TITLE
Form data validation

### ISSUE THREAD

**Issue by ffittschen** [xmartlabs/Eureka#47]
Hi, is there any way of validating the data of the rows like the validations in `XLForm`?

It would be nice to e.g. only activate a specific `ButtonRow` if the whole form is valid and this depends upon the validations of each row (e.g. row 1,2 and 3 must not be empty)

**Comment by thediary** [comment]
Yes! Please add form validation from XLForm! High priority for my team before we are able to make the switch

**Comment by jpaas** [comment]
Yes please. This is the only reason I haven't switched from XLForm.

**Comment by abbasmousavi** [comment]
+1 for form validation.

**Comment by shanmarkus** [comment]
+ 1

**Comment by bakomchik** [comment]
Hi guys. Thanks for Eureka!
\+ 1!
It would be very cool !

**Comment by ndmeiri** [comment]
👍

**Comment by bryanbartow** [comment]
+ 1

**Comment by waqqas-abdulkareem** [comment]
+1

**Comment by eflyjason** [comment]
+1

**Comment by abelondev** [comment]
+1

**Comment by vertuxx** [comment]
+1!!

**Comment by akabab** [comment]
+2

**Comment by useeless37** [comment]
In the meantime, please follow/contribute to this [SO question](http://stackoverflow.com/questions/35570293/what-is-the-right-way-to-do-validation-in-eureka)

Thanks to you! - from newbie's like me

**Comment by shanmarkus** [comment]
i was using [SwiftValidator](https://github.com/jpotts18/SwiftValidator) for validate text field for each cell.

**Comment by jpaas** [comment]
I've been using [SwiftValidate](https://cocoapods.org/pods/SwiftValidate) in the following way...

set up my validator chain and a property to hold the last calculated valid state:
```swift
  var formValid = false
  var validationIterator: ValidationIterator!

  func configureValidation() {
    validationIterator = ValidationIterator() {
      $0.resultForUnknownKeys = true
      $0.registerChain(ValidatorChain() {
        $0.stopOnException = true
        $0.stopOnFirstError = true
        }
        <~~ ValidatorRequired()
        <~~ ValidatorStrLen() {
          $0.minLength = 2
        }
        , forKeys: [Row.FirstName, Row.LastName]
      )
    }
  }
```
Validate after form initialization and after each row value change. You can also use the formValid state as a row condition:
```swift
      <<< NameRow(Row.LastName) {
        $0.title = "Last name"
        $0.value = lastName
        }.onChange { [weak self] _ in
          self?.validate()
      }

      <<< ButtonRow(Row.Submit) {
        $0.title = "Save"
        $0.disabled = Condition.Function([], { (form) -> Bool in
          return !self.formValid
        })
        $0.onCellSelection { cell, _ in
          self.submitPressed()
        }
      }
```

validate like this:
```swift
  override func validate() {
    formValid = validationIterator.validate(form.values())
    submitRow?.evaluateDisabled()
    navigationItem.rightBarButtonItem?.enabled = formValid
    // Display the error somewhere
  }
  
```

**Comment by Opelor** [comment]
Hi @shanmarkus, can you show an example of how are you using SwiftValidator. Thanks.

**Comment by demetrio812** [comment]
Hello @Opelor I've just committed a first working version of Eureka SwiftValidator TextRow:

[https://github.com/demetrio812/EurekaSwiftValidatorComponents](https://github.com/demetrio812/EurekaSwiftValidatorComponents)

Let me know and feel free to suggest improvements.

Cheers,
Dem

**Comment by Opelor** [comment]
Hi @demetrio812! I've just tested the example and it's a great start!

The first suggestion is to have the ability to customize the validation messages ("This field is required", "Must be a valid email address"..etc.).  The main reason being translation.

Great Contribution!!

**Comment by demetrio812** [comment]
Hello @Opelor ,
that's already supported by SwiftValidator:

```swift
$0.rules = [RequiredRule(message: "My custom message")]
```
You can also create your own rules.

Let's avoid spamming here though, please write any other suggestion on the project page.

Thanks,
Dem

**Comment by txaidw** [comment]
My team is also depending on this Feature to be able to migrate. We were using Validator on normal fields (https://github.com/adamwaite/Validator)

**Comment by violabg** [comment]
any updates on this?

**Comment by mtnbarreto** [comment]
Finally we implemented build-in vaidations feature in Eureka `2.0.0-beta.1` version, Notice that this version only works on swift3.  Take a look at the readme and example project for more info about how to use it.  
Any feedback is welcome. 

Regards

**Comment by ffittschen** [comment]
Awesome, thanks! I'm currently migrating to the `2.0.0-beta.1` and will let you know if I find anything worth to mention

**Comment by mtnbarreto** [comment]
👍 this could be helpful ... https://github.com/xmartlabs/Eureka/blob/master/Documentation/Eureka%202.0%20Migration%20%20Guide.md
