### ISSUE TITLE
exclusive checkRow

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#471]
Hi everyone,
is it possible to make multiple checkRows exclusive so only one can be selected.

Thanks.

**Comment by mats-claassen** [comment]
Yeah, have a look at the Readme [here](https://github.com/xmartlabs/Eureka#list-sections)

**Comment by dneykov** [comment]
Getting error when trying the example:
Use of undeclared type 'ImageCheckRow'

I'm using same example as Readme

**Comment by JordekFluffball** [comment]
The example uses a custom cell (ImageCheckRow) defined in CustomCells.swift that you will need to include if you want to use that example in your project.
