### ISSUE TITLE
Unable to change NameRow textColor

### ISSUE THREAD

**Issue by MatthiasLamoureux** [xmartlabs/Eureka#475]
Hello,

I wish to customize my Eureka form appearance, and I want it dark with white text color. Here's what I do:

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        NameRow.defaultCellSetup = { cell, row in
            cell.tintColor = UIColor.yellowColor()
            cell.backgroundColor = UIColor.blackColor()
            cell.detailTextLabel?.textColor = UIColor.whiteColor()
            cell.textLabel?.textColor = UIColor.whiteColor()
            cell.titleLabel?.textColor = UIColor.whiteColor()
            cell.textField.textColor = UIColor.whiteColor()
        }

        form +++ Section()
            <<< NameRow() {
                $0.title = "Name"
                $0.placeholder = "Type in your name"
                $0.cell.textField.autocorrectionType = .No
                $0.value = "Matthias"
                }
        
        self.tableView?.separatorColor = UIColor.whiteColor()
        self.tableView?.backgroundColor = UIColor.darkGrayColor()
    }

And unfortunately, neither the title label nor the name appears in white. When I select it, the tint changes to yellow, but the text inside the texfield is still black.

Is it a bug, or do I do something wrong?

I'm using Xcode 7.3.1 (7D1014), Eureka 1.6.0 and iOS 9.3

**Comment by MatthiasLamoureux** [comment]
The only way I found to work it around is: 

    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        for row in form.rows {
            row.updateCell()
        }
    }

And I believe this should not be mandatory, should it?

**Comment by mats-claassen** [comment]
Use `cellUpdate` / `defaultCellUpdate`  to set the textColor of the rows.
This is because Eureka changes the textcolor when a row gets highlighted / unhighlighted.

**Comment by MatthiasLamoureux** [comment]
Indeed. Thanks for this information.
