### ISSUE TITLE
How do we add a subtitle text to SwitchRow?

### ISSUE THREAD

**Issue by nkmadala** [xmartlabs/Eureka#476]
I'm trying to provide a hint for a SwitchRow. I tried setting up cell.detailTextLabel?.text but the text is showing up next to switch control. I want the hint to be placed below the title of the SwitchRow with leading edges aligned. How can I achieve this?

**Comment by mats-claassen** [comment]
Have a look at #257.

**Comment by nkmadala** [comment]
Thanks. That worked!! I was missing to set the cell.detailTextLabel on cellupdate.
