### ISSUE TITLE
Collapse/Expand section

### ISSUE THREAD

**Issue by cflorion** [xmartlabs/Eureka#477]
Hi,

I'd like too add to the library the ability to collapse/expand sections. I actually need it for the List Section type, but I think this could be useful for all sections.

My use case is the following: The user has an item to pick in the list, so the list is expanded. When the user selects an item or already has in the past, the list should be collapsed and only showing the selected value.

My question: As you have a clear of of how the library works, would you have any advice on how to best do it ?

Thanks a lot!
Florion

**Comment by mats-claassen** [comment]
I believe the easiest way to do this is by hiding and showing all the rows of a section when the user takes an action.
If you want all sections to support that, make an extension to `Section` that implements the function that handles the action of the user and then call that function from wherever you implement the 'collapse/expand switch', like the section header view.

How to collapse / expand (just suggestion, not tested code):
```
for row in section {
    row.hidden = collapse
    row.evaluateHidden()
}
```
