### ISSUE TITLE
rowByTag("myTag").hidden doesn't work?

### ISSUE THREAD

**Issue by mbalex99** [xmartlabs/Eureka#48]
Here's the bit of code, I'm running this after an async http fetch.  Though I'll just hardcode it for now.

How come the button isn't being hidden?

 ```swift 
if let buttonRow = self.form.rowByTag(self.kDeleteRowTag) {
                buttonRow.hidden = true
                buttonRow.updateCell()
            }
```

**Comment by mbalex99** [comment]
Oh no!
I figured it out.
I needed to put `[unowned self]` in the block running the code. I'm using RxSwift but it shouldn't matter

```swift
.subscribeNext { [unowned self] (canDelete) -> Void in
            if let buttonRow = self.form.rowByTag(self.kDeleteRowTag) {
                buttonRow.disabled = true
                buttonRow.updateCell()
            }
        }```

**Comment by mtnbarreto** [comment]
Hey @mbalex99 , `updateCell` does not evaluate hidden condition, it only updates the tableViewCell according row info. You can invoke `buttonRow.evaluateHidden()` to force the evaluation of hidden condition, it will make the cell visible/invisible if needed.

Regards

**Comment by mbalex99** [comment]
OH wow okay awesome. This worked!

```swift
if let buttonRow = self.form.rowByTag(self.kDeleteRowTag) {
                buttonRow.hidden = true
                buttonRow.evaluateHidden()
            }
```
