### ISSUE TITLE
Storyboard Navigation Bar

### ISSUE THREAD

**Issue by marcsnts** [xmartlabs/Eureka#481]
Originally I had my form made programatically:
http://i.imgur.com/cyAyMZl.png

However, I needed a navigation bar at the top for a better UX so I played around in Storyboard, put the table's outlet to the form view controller and ended up with this:
http://i.imgur.com/UXlNbj6.png
http://i.imgur.com/E3yyUVo.png

My question is: how can I get it to look more elegant like it did originally? After some debugging i've come to the conclusion that the random lines (in the picture with the navigation bar) are because I have hidden rows, however I need these hidden rows one of my features. Is it possible for those lines to disappear while still keeping my rows hidden?

**Comment by James-Coleman** [comment]
If you haven't worked this out already, I think this is a basic XCode question, unrelated to Eureka.
Delete the Nav Bar you've put in manually, select the ViewController and go to Editor > Embed In > Navigation Controller.

**Comment by marcsnts** [comment]
@James-Coleman That made it look a lot cleaner thanks! But still having the issues of the lines from the third image

**Comment by James-Coleman** [comment]
I think there must be something else in your storyboard. Try deleting those controllers, adding a new empty view controller, and embedding it in a nav controller.

**Comment by Ryosuke-Hujisawa** [comment]
Thank you very much for your help.
