### ISSUE TITLE
How to associate DateTimePicker & a selectable string to the same row?

### ISSUE THREAD

**Issue by nkmadala** [xmartlabs/Eureka#482]
Hi, I'm having a requirement where user can select a particular date or select a string ( "immediate" i.e from immediate effect in my form context). How can I add a  DateTimePicker & a string to the alertRow? Please provide some guidance.

Thanks,
Naveen

**Comment by mats-claassen** [comment]
The AlertRow does not support pickers. You would have to create a custom row for this.
I am not even sure UIAlertController does support something like this. Maybe the easiest way is to separate this row in two different rows.
