### ISSUE TITLE
2 levels PushRow 

### ISSUE THREAD

**Issue by zajil** [xmartlabs/Eureka#483]
Hi,
Is there a way to implement 2 level PushRow?

For example I would like to view countries in the first level and whenever you select the country, the second level will presented with cities.

Any idea?
Thanks

**Comment by James-Coleman** [comment]
I'm in the middle of something like this myself.
The PushRow selectorViewController itself is a form, so you could try something like:

`
                <<< PushRow<String>(yourFirstTag) {
                    $0.title = $0.tag
                    $0.options = yourFirstOptions
                    $0.selectorTitle = "Your First Title"
                    $0.value = yourFirstDefaultValue
                    $0.onPresent({ (formViewController, selectorViewController) in
                        selectorViewController.form.first! <<< PushRow<String>(yourSecondTag) {
                            $0.title = $0.tag
                            $0.options = yourSecondOptions
                            $0.selectorTitle = "Your Second Options"
                            $0.value = yourSecondDefaultValue
                        }
                    })
                }
`

**Comment by zajil** [comment]
Thank you, I will give it a try

**Comment by James-Coleman** [comment]
The only issue with the code above is if you have no options set for the first level PushRow. In that case, you might try:


```swift
guard let first = selectorViewController.form.first else { return }
guard let firstSection = first as Section else { return }

for secondLevel in secondLevelData {
        let newRow = ListCheckRow<String>(secondLevel) { newRow in
            newRow.title = newRow.tag
            newRow.selectableValue = newRow.tag

        
        }
        
        var indexToInsertAt = 0
        
        for row in first {
            let listCheckRow = row as! ListCheckRow<String>
            guard let title = listCheckRow.title else { continue }
            if title < text {
                indexToInsertAt += 1
            } else {
                break
            }
        }
        
        
        
        var firstSection = first as Section
        
        firstSection.insert(newRow, atIndex: indexToInsertAt)

                <<< PushRow<String>(yourFirstTag) {
                    $0.title = $0.tag
                    $0.options = yourFirstOptions
                    $0.selectorTitle = "Your First Title"
                    $0.value = yourFirstDefaultValue
                    $0.onPresent({ (formViewController, selectorViewController) in
                        selectorViewController.form.first! <<< PushRow<String>(yourSecondTag) {
                            $0.title = $0.tag
                            $0.options = yourSecondOptions
                            $0.selectorTitle = "Your Second Options"
                            $0.value = yourSecondDefaultValue
                        }
                    })
                }

```

**Comment by mats-claassen** [comment]
@zajil I think we can close this issue, right?
