### ISSUE TITLE
Changing Color of ButtonRow Text

### ISSUE THREAD

**Issue by grsteffens** [xmartlabs/Eureka#486]
How can I change the font color of a buttonrow? I currently have...

```
<<< ButtonRow() {
  $0.title = "Continue"
  $0.baseCell.backgroundColor = Common.colorWithHexString("#336894", alpha: 1.0)
}
```
Is there a $0. I can set so the font of the button is white?

**Comment by singlag1993** [comment]
> How can I change the font color of a buttonrow? I currently have...
> 
> ```
> <<< ButtonRow() {
>   $0.title = "Continue"
>   $0.baseCell.backgroundColor = Common.colorWithHexString("#336894", alpha: 1.0)
> }
> ```
> Is there a $0. I can set so the font of the button is white?

I am able to solve my issue with your piece of code and about the button's title text colour, you can use tintColor property.

// To change the button's background colour.
$0.baseCell.backgroundColor = UIColor.green

// To change button's title text colour.
$0.baseCell.tintColor = UIColor.white
