### ISSUE TITLE
Bug with getting baseValue from SelectableSection

### ISSUE THREAD

**Issue by mirzadelic** [xmartlabs/Eureka#487]
I have this code:
```
        let branch_section = SelectableSection<ImageCheckRow<String>, String>("Lokali", selectionType: .MultipleSelection)
        branch_section.tag = "branch_section"
        for branch in branchList {
            branch_section <<< ImageCheckRow<String>(branch.name){ row in
                row.title = branch.name
                row.baseValue = branch.id
                row.selectableValue = branch.name
                row.value = nil
            }
        }
```
so, `baseValue` is id(Int).

Now, when i use:
```
    @IBAction func saveFilter(sender: AnyObject) {
        let branch_section = self.form.sectionByTag("branch_section") as? SelectableSection<ImageCheckRow<String>, String>
        for branch in branch_section!.selectedRows() {
            print(branch.baseValue)
        }
    }
```

this prints me `name` field, but i need `id`.
I need to get ids of selected choices..
Is this bug?

**Comment by mirzadelic** [comment]
Any help here?

**Comment by mats-claassen** [comment]
@mirzadelic `baseValue` is the same as `value`. In fact `baseValue` is just a untyped wrapper, so you are setting the value to nil yourself. Look here: https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Row.swift#L31-L58

Also, the value of the row will be `selectableValue` if the row is selected, thats why it prints your name. If it is not selected it will be nil.

You might want to subclass that row, using the same cell, just adding a custom attribute to store your id.
Or you could use a struct to set both name and id as value.
