### ISSUE TITLE
AlertRow onPresent tintColor changed back to default blue

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#488]
Hi Guys,

Is there something missing in the example?

```
<<< AlertRow<Emoji>() {
                        $0.title = "AlertRow"
                        $0.selectorTitle = "Who is there?"
                        $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻]
                        $0.value = 👦🏼
                    }.onChange { row in
                        print(row.value)
                    }
                    .onPresent{ _, to in
                        to.view.tintColor = .purpleColor()
                    }
```

the purple cancel will change back to blue when dragged or selected.

**Comment by kohdesmond** [comment]
@marbetschar any news yet?

**Comment by marbetschar** [comment]
@kohdesmond you might want to use `cellSetup` and/or `cellUpdate` for styling purposes. As far as I recap these prevent and/or solve theses issues when cells are refreshed.

Here's a snippet which should point you into the right direction (untested):

```
<<< AlertRow<Emoji>(){
  ...
}.cellSetup{ cell, row in
  ...
}.cellUpdate( cell, row in
 ...
}
```

**Comment by kohdesmond** [comment]
@marbetschar thanks for the speedy reply.

I had already tested your suggestions 

Here are my codes

```
<<< AlertRow<typeArray>(kTaskType) {
            $0.noValueDisplayText = "Please pick a type"
            $0.options = kResponseTypeShowArray
            }
            .cellSetup{ cell, row in
                cell.height = {kCellRowHeight}
                let bg = createBG(kViewHeight)
                cell.backgroundColor = UIColor.clearColor()
                cell.addSubview(bg)
                cell.sendSubviewToBack(bg)
            }
            .cellUpdate{ cell, row in
                cell.textLabel?.text = "Task Type"
                cell.textLabel?.textColor = appTextColor()
                cell.selectionStyle = .None
                cell.detailTextLabel?.textColor = row.value == nil ? appTextColor() : smuSISColor()
                })
            }
            .onPresent{ from, to in
            to.view.tintColor = smuSISColor() //self.appTextColor()
            let subview = to.view.subviews.first! as UIView
            let cv = subview.subviews.first! as UIView
            cv.backgroundColor = appBackgroundColor()
            cv.layer.cornerRadius = 10
            cv.alpha = 1
            cv.layer.borderWidth = 1
            cv.layer.borderColor = appBackgroundColor().CGColor
            }
```

This is how the view looks like on present of the alertview
![screen shot 2016-06-16 at 20 20 20](https://cloud.githubusercontent.com/assets/1192544/16116681/e06934b0-3400-11e6-9274-423d6d53ff0d.png)

As soon as you tap or hold on it, it changes to the default blue.
![screen shot 2016-06-16 at 20 21 14](https://cloud.githubusercontent.com/assets/1192544/16116696/fae0a79c-3400-11e6-85fa-9df62b7ae1ff.png)

if you drag down
![screen shot 2016-06-16 at 20 21 05](https://cloud.githubusercontent.com/assets/1192544/16116717/137b88a8-3401-11e6-837c-ef174599c57d.png)

i need to get the SelectorAlertController reference, so i can update while highlighted and not too sure how can i do it.

**Comment by marbetschar** [comment]
The tintColor you are talking about - is this globally used in the app?

If so, you can get presumably around this by setting the global tintColor correctly:
http://stackoverflow.com/questions/19641476/how-can-i-change-the-global-tint-color-programmatically

Or alternatively using UIAppearance proxies for setting the correct tintColor on element level.

**Comment by kohdesmond** [comment]
@marbetschar, i need to update the SelectorAlertController tint color

**Comment by mats-claassen** [comment]
@kohdesmond The `to` variable you get in `onPresent` is the SelectorAlertController. You can hold a reference to it...

**Comment by mats-claassen** [comment]
@kohdesmond Could you fix this problem?
