### ISSUE TITLE
onPresent() closure is not called when presentationMode = .SegueName

### ISSUE THREAD

**Issue by mrvincenzo** [xmartlabs/Eureka#489]
`onPresent()` closure is not called for `ButtonRowWithPresent` when the row's `presentationMode` is set to `SegueName`

I think that the problem is with `if let controller = presentationMode.createController()`  statement in `ButtonRowWithPresent` which results in `nil` when using `PresentationMode.SegueName` presentation mode.

	public override func customDidSelect() {
		super.customDidSelect()
		if let presentationMode = presentationMode where !isDisabled {
			if let controller = presentationMode.createController(){
				controller.row = self
				onPresentCallback?(cell.formViewController()!, controller)
				presentationMode.presentViewController(controller, row: self, presentingViewController: cell.formViewController()!)
			}
			else{
				presentationMode.presentViewController(nil, row: self, presentingViewController: cell.formViewController()!)
			}
		}
	}

Eureka release 1.5.0, Xcode 7.3.1

**Comment by mats-claassen** [comment]
Hi @mrvincenzo , `onPresent` should be called from `prepareForSegue` as that is the place where the destination view controller can be accessed.

I suspect you might have overriden `prepareForSegue` in your FormViewController and did not call super...?

**Comment by mrvincenzo** [comment]
Nope. I tried both without overriding `prepareForSegue` and with `prepareForSegue` that calls `super. prepareForSegue` before anything else. Same result - .onPresent is not called.

**Comment by mats-claassen** [comment]
@mrvincenzo I have this code and it is working. Swift 3 syntax:
```
<<< ButtonRowWithPresent<InlineRowsController>("Inline rows") { row in
                    row.title = row.tag
                    row.presentationMode = .segueName(segueName: "InlineRowsControllerSegue", completionCallback: nil)
                }.onPresent({ _ in
                    print("Tadaaan...")
                })
```
