### ISSUE TITLE
Change form dynamically at runtime

### ISSUE THREAD

**Issue by ZachJiroun** [xmartlabs/Eureka#49]
Hi, is there any way to change the form dynamically at runtime? This feature was in XLForms.

**Comment by mtnbarreto** [comment]
@ZachJiroun 
What do you mean by change the form dynamically?
Eureka has the same XLForm capabilities in terms of how it updates dynamically the tableView based on its sections and rows.

Cheers

**Comment by ZachJiroun** [comment]
Is there any way to create a new section dynamically? I didn't see a way to do that based off the value of a input field.

**Comment by mtnbarreto** [comment]
You can either insert a new section from onChange callback of the relevant row or assign a condition to the section hidden property, this condition should specify when the section is hidden based on the row value.
