### ISSUE TITLE
what is being called when the done button on first responder is being tapped

### ISSUE THREAD

**Issue by kohdesmond** [xmartlabs/Eureka#490]
Hi @marbetschar, as per my subject title, what function is being called when the done button on first responder is being tapped? i would like to do some validation on the cell when the user dismissed the first responder.

**Comment by marbetschar** [comment]
Hi @kohdesmond 

You might want to use the `onChange` for validation:

```
TextRow()
  .onChange{
    if $0.value != "MyValidation" {
      //do your validation feedback here
    }
  }
```

If this doesn't work out: @mtnbarreto isn't there any `didEndEditing` or `onEndEditing` similar to the `onChange`? How would you bind those events?

**Comment by mats-claassen** [comment]
There is a `textInputDidEndEditing` in FormViewController but it will be called for all rows of that form. 
There is also the `onCellUnHighlight` which gets called when a cell resigns first responder.

Note: If you use `onCellUnHighlight` you must also override `onCellHighlight`. Look at the default implementation of the field rows for more information.
