### ISSUE TITLE
Cannot get disclosureIndicator on ButtonRow

### ISSUE THREAD

**Issue by SASDOE** [xmartlabs/Eureka#491]
I am trying to create a button row to present another `UIViewController`, but because of how I need to instantiate the VC I cannot use `row.presentationMode`.
However when I use this:
```swift
            <<< ButtonRow("I") {
                $0.title = "Image gallery".localized()
                }   .onCellSelection { (cell, row) in
                    // Instatiating and presenting the view controller
                }   .cellSetup { (cell, row) in
                    cell.accessoryType = .DisclosureIndicator
                    row.updateCell()
                }
```
I get a blue button as in issue #3 : ![](https://cloud.githubusercontent.com/assets/1582690/14798557/297228dc-0b30-11e6-9321-100a3ee39ea4.png)

How can I get a button with a disclosure indicator?

**Comment by mats-claassen** [comment]
If you want to use it just like the others you have to add `row.cellStyle = .Vlaue1` in the row initializer.

And you should set the accessoryView in the `cellUpdate`
```
<<< ButtonRow("I") {
                $0.title = "Image gallery"
                $0.cellStyle = .Value1
                }   .onCellSelection { (cell, row) in
                    // Instatiating and presenting the view controller
                }   .cellUpdate { (cell, row) in
                    cell.accessoryType = .DisclosureIndicator
            }
```

![screen shot 2016-06-15 at 12 34 15 pm](https://cloud.githubusercontent.com/assets/8573865/16086329/89c37e38-32f5-11e6-80ed-609c99e094cd.png)
