### ISSUE TITLE
Row selection with Scrolling

### ISSUE THREAD

**Issue by bithavoc** [xmartlabs/Eureka#492]
Is there an specific reason why [`BaseRow.Select()`](https://github.com/xmartlabs/Eureka/blob/893a6216c6ef93bacfa836f969b960ff6897c0dd/Source/Core/BaseRow.swift#L248) `scrollPosition:` is set to `.None`, options like `.Top` are pretty helpful if the cell is not available so it scrolls and selects the row automatically.

I've been using the following extension to overcome this.

``` swift
extension BaseRow {
    func selectScrolling(animated: Bool = false) {
        guard let indexPath = indexPath(), tableView = baseCell?.formViewController()?.tableView ?? (section?.form?.delegate as? FormViewController)?.tableView  else { return }
        tableView.selectRowAtIndexPath(indexPath, animated: animated, scrollPosition: .Top)
    }
}
```

If you want I can submit a PR to make `select` accept an optional scroll position leaving `.None` as default.

**Comment by mats-claassen** [comment]
I cannot think of a reason right now. A pull request would be welcome if you still have the code around. But the pull request should be in Swift 3 syntax and based on `Swift3` branch.
