### ISSUE TITLE
no such module issue with iOS build 9.2

### ISSUE THREAD

**Issue by reomind** [xmartlabs/Eureka#494]
hi
i am trying to do manual installation as well as via cocoa pods but i am getting no such module error in either case

here is what i did for manual steps

- created a project with deployment target 9.2
- copied eureka as sub folder in my project root directory 
- drag and dropped eureka.xprojectcode in navigation panel 
- updated eureka deployment target to 9.2
- added eureka as linked binaries. 

in cocapods i tried installing it with this pod file 
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.2'
use_frameworks!

pod 'Eureka', '~> 1.6'

**Comment by mats-claassen** [comment]
Just tried your steps (without copying Eureka to root folder) and it did just work.

By the way, which version of cocoapods are you using?
You should be using cocoapods 1.0
