### ISSUE TITLE
Invalid Mach-O while uploading to App Store

### ISSUE THREAD

**Issue by mirzadelic** [xmartlabs/Eureka#497]
Got error:

> 
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "*/Frameworks/Eureka.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode) and arm64(bitcode). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

Any solution for this?

**Comment by plastus** [comment]
Set the "enable_bitcode" flag to "NO" under build settings. It looks like you have bitcode disabled for your main project/app but not for the dependent framework (Eureka).

**Comment by mats-claassen** [comment]
@mirzadelic was your problem solved?

**Comment by mirzadelic** [comment]
Yes, it is solved.
