### ISSUE TITLE
Maintaining support for future Swift versions

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#499]
Hi all,

With the latest announcements at WWDC 2016, are there plans to convert Eureka into Swift 3 when the time comes? I installed Xcode 8 beta along with iOS 10 and the conversion from Swift 2.2 to 2.3/3 went poorly. The Eureka code does seem to work nicely though on IOS 10 devices from what I have seen so far.

I'm curious as to the long-term support for this framework and whether there are plans to support the upcoming iteration of Swift.

Thanks in advance!

**Comment by mats-claassen** [comment]
Hi @plastus, we will definitely be converting Eureka to Swift 3 as we do use it extensively in our projects.
But I think this will probably not happen until at least a stable version of Xcode 8 comes out.

Great to know that it seems to work as-is on iOS 10 devices though!

**Comment by plastus** [comment]
That's good to hear! :) I cloned one of my test projects and imported it into Xcode Beta 1. Eureka required a few minor changes to work with Swift 2.3. Works great on iOS 10 when compiled from Swift 2.2 source and 2.3 source code. Just FYI for any others that want to give Xcode 8 a try but are worried about breaking their existing app.

**Comment by banjun** [comment]
For Swift 3 Preview 1 included in Xcode 8 beta 1, there should be swift compiler crashes in some Eureka code.

I have submitted a radar and a bug report for this with turning the problem to a short example code, at WWDC.
https://bugs.swift.org/browse/SR-1813

I think generic and associated types constraints around `TypedRowType` are affected by this swift compiler bug. It's not yet stable for Eureka...

**Comment by mtnbarreto** [comment]
@banjun thanks for reporting the issue!

**Comment by mats-claassen** [comment]
I will close this thread. For any further comments please post them in #517
