### ISSUE TITLE
How to add a clear button to DateTimeInlineRow?

### ISSUE THREAD

**Issue by nkmadala** [xmartlabs/Eureka#502]
How can I provide the option to clear the date for date rows like DateTimeInlineRow?

**Comment by nkmadala** [comment]
Can you please guide me on how to add a button to the DateTimeInlineRow which is visible only when the date picker is visible. I'm asking this because if I add the button to the header it will be visible all the time.

**Comment by plastus** [comment]
Set the section's (which contains the header) hidden property to only show on that condition using a condition function. This will hide the header when the date row is not currently visible.

**Comment by mats-claassen** [comment]
@nkmadala Could you implement this?
