### ISSUE TITLE
Select multiple images in ImageRow

### ISSUE THREAD

**Issue by nkhaitan** [xmartlabs/Eureka#504]
Hello,

Is there a way we can select multiple images at once from the library in ImageRow?

Thanks a lot!

**Comment by rcholic** [comment]
@nkhaitan did you find any solution? I, too, need to have this feature for selecting multiple images in a row. Thanks

**Comment by Leocata14** [comment]
@nkhaitan @rcholic Did either of you find a solution to this? Would be very helpful. I've tried adding extra rows after an image is selected but have issues with removing the photos. 

Multiple image selection would be a life saver

**Comment by sunbohong** [comment]
I also need to have this feature.

I think we will have to implement this by overriding the row we want to use.

**Comment by korgx9** [comment]
If you already implemented it, please share

**Comment by mtnbarreto** [comment]
It would be great if we implement it. 
Anyone want to implement and share this custom row through [EurekaCommunity](https://github.com/eurekaCommunity) organization?

**Comment by almatri** [comment]
I want this feature too, I have an app where the user can select multiple images and upload them together

**Comment by akabab** [comment]
+1!

**Comment by SebastianBO** [comment]
How is this coming along?

**Comment by dneykov** [comment]
Would be really welcome feature.

**Comment by enarida** [comment]
+1

**Comment by farshadjahanmanesh** [comment]
+1
