### ISSUE TITLE
SegmentedRow not appearing when inside childView

### ISSUE THREAD

**Issue by stevejcox** [xmartlabs/Eureka#505]
When loading a form as a child view the SegmentedRow doesn't show the segment. The cell has the correct dimensions, but the segment is not showing up.

**Comment by mats-claassen** [comment]
This is really strange. Why should it not be shown in a child view? Is this happening to other  rows as well?
Have you found the error since?

**Comment by mats-claassen** [comment]
@stevejcox What is the status of this? Are you still experiencing this? What does the view hierarchy inspector say?
