### ISSUE TITLE
Set NSMutableArray as picker row options

### ISSUE THREAD

**Issue by parastagrem** [xmartlabs/Eureka#507]
I am using eureka latest version on Xcode 7.3.1.
I want to assign a NSMutableArray directly to picker row options, I know I was doing this in Objective C version of Eureka i.e. XLForm, but I am getting some error while doing this with eureka.

```
<<< PickerRow<String>("Country*") { row in
                row.title = "Country"
                row.options = countryArray
            
            }
```

Here countryArray is of type NSMutableArray and the error I am getting is 
"Cannot assign value of type NSMutableArray to type [String]"

I don't understand why row.options is of type string.

Am I missing something ?

**Comment by sunbohong** [comment]
let countryArray = NSMutableArray()
                countryArray.addObject("China")
                $0.options = NSArray(array: countryArray)  as! [String]

**Comment by mats-claassen** [comment]
Hi @parastagrem did that work for you?
