### ISSUE TITLE
XCODE 8 beta, converted to Swift Syntax 2.3 getting still 1 issue in HeaderFooterView.swift

### ISSUE THREAD

**Issue by code-K** [xmartlabs/Eureka#508]
Hi there,

Wanted to test the Eureka on the new XCODE 8 beta (iOS 10 SDK). I converted to swift syntax 2.3 and still getting 1 issue here in  HeaderFooterView.swift. Please see attached screenshot.

![bildschirmfoto 2016-06-21 um 9 35 42 am](https://cloud.githubusercontent.com/assets/1224750/16221711/8e23b3b4-3794-11e6-8d51-6d0cbb056c7e.jpg)

It's line 55: 
```return ViewType.`init`(boundsSize:requestHandler:)()```

Can you please point me in the right direction to solve this?

Thanks much and best regards,
Christian

**Comment by plastus** [comment]
I have this in my Xcode 8 project and it works fine:

    return ViewType.init()

**Comment by mats-claassen** [comment]
We are converting Eureka to Swift 2.3 and Swift 3.
Currently branch `swift2.3` has the code for that swift version.
You can fix that error by calling `ViewType()` instead of the rest
