### ISSUE TITLE
Triggering hidden row cell selection programmatically?

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#509]
Is it possible to trigger a cell selection (and resulting segue w/ PushRow for example) using code? I have a form rendered on screen in a child view container and want to select a hidden PushRow programmatically.

    let table = VC.tableView!
    table.selectRowAtIndexPath(index_path, animated: true, scrollPosition: .None)
    table.delegate?.tableView?(table, didSelectRowAtIndexPath: index_path)

The above works when the 'hidden' property for the row is false, but if it's set to true an error crops up.

    fatal error: Section: Index out of bounds:

Thanks in advance!

**Comment by mats-claassen** [comment]
That error pops up because that row is not currently in the tableView nor really in the form.

If you just want to execute the action of that row then get that row with `rowByTag` and call `row.didSelect()`
