### ISSUE TITLE
OptionsRow like HTML's radio control - dispayValueFor

### ISSUE THREAD

**Issue by litmisty** [xmartlabs/Eureka#52]
I want to set the form's values and labels separately.
Now, the value of OptionsRow is set to be the same as the label. So, it's hard to set enum values in the OptionsRow or SegmentRow.

It would be like below. I added ```$0.labels```
Is there some other way to achieve this already?
Please let me know.

```
enum SortTypes : Int {
        case Creation = 0, Update = 1
        static let allValues = [Creation, Update]
        static let allLabels = ["by Creation", "by Update"]
}

SegmentedRow<String>("sortType") {
                $0.options = SortTypes.allValues
                $0.labels = SortTypes.allLabels
            }
```

**Comment by mtnbarreto** [comment]
Each row exposes `displayValueFor` property which the following default value:

```swift
    public var displayValueFor : (T? -> String?)? = {
        if let t = $0 {
            return String(t)
        }
        return nil
    }
```

Being said that, you can change the option description by setting up a new function to this property.
Alternatively you can take advantage of how the default `displayValueFor` is implemented, in particular the invocation to `String(t)` which uses the print value for the type. 

This is an example using the second approach, note the conformance of `CustomStringConvertible`: 

```swift
enum EmojiEnum: String, CustomStringConvertible {
    case Martin =  "Martin"
    case Mathias = "Mathias"
    
    var description: String {
        return self.rawValue + "🚀"
    }
}
```
