### ISSUE TITLE
Bug: Spacing between imageView and textLabel within SwitchRow and ButtonRow cells not consistent

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#522]
![screenshot 2016-06-28 09 46 47](https://cloud.githubusercontent.com/assets/18575720/16417824/629e7b58-3d15-11e6-81cd-e097d7e65498.png)

As shown in the screenshot, when an imageView is defined for both SwitchRow and ButtonRow type rows, the spacing between the textLabel and icon is larger than all other rows. Setting frame origin, width, etc. has no effect.

**Comment by plastus** [comment]
This can be solved by setting the LeadingMargin and CenterY constraints on the text label in.onCellUpdate method and making sure to set "cell.textLabel?.translatesAutoresizingMaskIntoConstraints = false" beforehand.

Looking at the row source code, it looks like neither ButtonRow nor SwitchRow have constraint definitions like the other rows?

**Comment by plastus** [comment]
This is still a bug in 1.7.0 unfortunately.

**Comment by mats-claassen** [comment]
@plastus What do you mean by other rows?
I believe there can be a difference between the rows with constraints and the rows without constraints. The frames of the latter ones are managed by UIKit.

I believe the correct way to fix this is by adjusting the constraints to be equal to UIKits default appearance but I am not sure if we can do this for all the cases (e.g different devices)

**Comment by mats-claassen** [comment]
So I have had a look at this and I found the following:
1) We can change the difference between imageView and textLabel to match that one of default UITableViewCells, but
2) If your images are not all of the same size then you wont get alignment.

This is what it would look like:
![screen shot 2016-07-25 at 5 50 17 pm](https://cloud.githubusercontent.com/assets/8573865/17117008/a07e39e6-5290-11e6-90c5-67bcb99b9baa.png)

**Comment by plastus** [comment]
@mats-claassen Sorry for not updating this thread, the way I solved it was by setting the cell's backgrounView to the contentView with a different background color. Then I had to go to .cellSetup and set-up NSLayoutConstraints for the textLabel relative to the cell's image which I manually add as subviews directly to the cell. I get no flickering, highlight animation works like in a normal cell, etc.
