### ISSUE TITLE
How can I create a inline TextRow?

### ISSUE THREAD

**Issue by tc** [xmartlabs/Eureka#523]
I noticed there are DateInlineRow which expand a hidden cell. 
I want a TextRow when selected will expand a row below with buttons (like Edit Details, Delete)

**Comment by mats-claassen** [comment]
This is not currently supported. And it is a very specific feature.
It might work to manually insert and remove a row after the current TextRow when it becomes or resigns firstResponder. This can be done using the `textInputDidBeginEditing` function of your FormViewController. Note that you will have to check if it is the correct row that is being edited.

If this does not work, you will have to create a custom TextRow subclass (or without subclassing) that implements that functionality.

You can make it an inline row or just create a cell that resizes with constraints and which toggles showing the buttons on and off. 
In any case you will want to use the delegates methods of textField and cell to know when the cell/textfield becomes firstResponder or resigns firstResponder...
