### ISSUE TITLE
LocationRow with Geocoder

### ISSUE THREAD

**Issue by biskit** [xmartlabs/Eureka#524]
using LocationRow from your examples... is it possible to show the actual location (city, administrativeArea) instead of lat/lon in the row?

**Comment by biskit** [comment]
anyone?

**Comment by mats-claassen** [comment]
Could you solve that problem?

**Comment by biskit** [comment]
I have not yet. CLLocation is an async call back and I need to figure out how to return from `displayValueFor` after that returns...

**Comment by mtnbarreto** [comment]
After CLLocation async returns you should save the data somewhere and reload the row by calling `row.reload()`.
`row.reload()` must be invoked from main thread.
