### ISSUE TITLE
How to make multiline label?

### ISSUE THREAD

**Issue by andertsk** [xmartlabs/Eureka#525]
How to insert multiline label with this library? I tried just insert LabelRow but this is only one-line with truncation. Here is full question: [http://stackoverflow.com/questions/38093462/how-to-make-multiline-label-with-eureka](url)

**Comment by JordekFluffball** [comment]
Append this to a row declaration and modify as desired:

.cellSetup{ cell, row in
                cell.height = { 80 }
                cell.textLabel?.numberOfLines = 2
}
