### ISSUE TITLE
Setting the value of row getted with rowByTag dont works

### ISSUE THREAD

**Issue by andertsk** [xmartlabs/Eureka#528]
I use the `self?.form.rowByTag()` function to get the row in callback `.onChange()`, but when i set the value property of the row received by `rowByTag()` for example to nil it doesn't affect the result. The full question can be found here on [stackoverflow](http://stackoverflow.com/questions/38140538/how-to-make-two-mutually-exclusive-segmented-rows-with-eureka)

**Comment by mtnbarreto** [comment]
it was already answered in stackoverflow.

answer quote...

As explained in the guide - section [How to set the form values using a dictionary](https://github.com/xmartlabs/Eureka#how-to-set-the-form-values-using-a-dictionary)

> If the form was already displayed we have to reload the visible rows either by reloading the table view `tableView.reloadData()` or invoking `updateCell()` to each visible row.

so just call weight2Row.updateCell() to have the new values reflect.

updateCell() redraw the cell but don't reload it in the table view, row.reload() does the reload (including the redraw).

Probably in your case `updateCell()` works better.

**Comment by mtnbarreto** [comment]
similar to #355 and many other issues.
