### ISSUE TITLE
FloatLabelTextField formatter

### ISSUE THREAD

**Issue by sagits** [xmartlabs/Eureka#53]
Hi, i would like to use FloatLabelTextField on my projects. I'm trying to add the formatter thats present on DecimalRow but the FloatLabel extends from UITextField direct. 

  How can i implement formatter on FloatLabelTextField? Thanks in advance.

**Comment by mtnbarreto** [comment]
@sagits FloatLabelTextField is not provided natively by Eureka, It's just an example to show how flexible is Eureka and how to create custom rows. Anyway i think it's a cool feature so I implemented it.

Look at the attached pull request for more details.

**Comment by sagits** [comment]
Thank you, its an awesome feature! But i'm having this error:

CustomCells.swift:202:35: Use of undeclared type 'FormatterConformance'

Can you check it please? Thanks in advance

**Comment by mtnbarreto** [comment]
I made this protocol public. This is only available on master branch version for now.

**Comment by sagits** [comment]
Thank you. It worked, but i'm trying to use the CurrencyFormatter provided in example along with useFormatterDuringInput = true in a DecimalFloatLabelRow.
 If i use a default value it starts formatted but when i enter numbers input value wont change, and if i wont use a default value i can type but my text wont get formated as spected. My guess is that this property would format the currency as i type, i'm i wrong? Can you help me please? Thanks in advance.

**Comment by sahithya-carecloud** [comment]
hi
in the floatTextCell how do I put two fields in the single cell?

**Comment by mats-claassen** [comment]
You cannot. You must create a custom row for that
