### ISSUE TITLE
TextAreaRow with counter

### ISSUE THREAD

**Issue by biskit** [xmartlabs/Eureka#530]
is it possible? an option for it, like placeholder? any samples?

**Comment by mats-claassen** [comment]
`Impossible is nothing`... just joking
I do not completely get what you want to implement but I think you are speaking about a specific behaviour that we will not be implementing into Eurekas core.

If you want help implementing this feature you should ideally go for help at StackOverflow...

**Comment by biskit** [comment]
Its not specific at all. It's a counter on TextAreaField and a max value. I was able to implement it myself, though its generic enough for all. I can create pull request...

**Comment by mats-claassen** [comment]
Ah ok so its a character counter?
If somebody else wants it you could create a pull request

**Comment by biskit** [comment]
Yes a character counter one is familiar with.  I have this with pushrow mods (header being empty or not and enableDefaultSelection) in a single pull.

**Comment by mtnbarreto** [comment]
we're not going to add the counter as a core feature. If you want to provide a better TextAreaRow row you can share it through [EurekaCommunity](https://github.com/EurekaCommunity) organization which lists Eureka plugins .
