### ISSUE TITLE
Changing CheckRow value doesn't update the cell?

### ISSUE THREAD

**Issue by AndrewSB** [xmartlabs/Eureka#533]
Environment: Eureka: 1.6.0, Xcode: 7.3.1 and iOS: 9.3

I'm trying to programmatically select and deselect a CheckRow. Currently have this code:

```
            let row = (form.rowByTag(Prefs.Presence.All.rawValue) as! CheckRow)
            print("value was \(row.value)")
            row.value = bool
            print("value is \(row.value)")
            row.cell.update()
```

The value is updating (I call this code multiple times, in a few dispatch_afters for testing), switching from true to false and vice versa, but it seems as if the value doesn't affect the `checkmark : none` set in the CheckRow's `update()`?

I've also tried using `form.allRows.forEach { $0.updateCell() }`, doesn't work either

**Comment by AndrewSB** [comment]
Figured out the issue: It was related to how I was setting up the form. I was doing this:

```
form +++ Section <<< Row someClosure { form.last! <<< Row }

form +++ Section <<< Row someClosure { form.last! <<< Row }
```

I changed that to 
```
var lastSection: Section? = nil

form +++ Section <<< Row someClosure { lastSection = form.last! <<< Row }

lastSection +++ Section <<< Row someClosure { form.last! <<< Row }
```

and it suddenly started working. Not sure why that's the case though, an explanation would be awesome 😄

**Comment by AndrewSB** [comment]
Actually, doing this has actually created another issue, where all the Sections and Rows appended using `lastSection +++ Section` aren't available to `form.rowByTag(:)`, and I'm now crashing due to `NSInvalidArgumentException', reason: 'Can't get value for 'notifications_enabled' in bindings`.

As a workaround, I'm removing the closure for now, but I'd really like to understand the root source of the issue so I can add that pattern back

**Comment by mats-claassen** [comment]
Why are you appending rows inside the initializer of a row? Your form might be inconsistent with that.

**Comment by AndrewSB** [comment]
@mats-claassen my pseudocode was unclear. Here's a more look at what I'm doing:

```
form +++ Section(header: tr(.ProfileSettingsNotificationsTitle), footer: tr(.ProfileSettingsNotificationsHelper))
        
                <<< SwitchRow("notifications_enabled") {
                    $0.title = Prefs.Notifications.Off.l
                    $0.value = self.model.notification == .Off
                }.onCellSelection { _, row in
                    self.model.notification = row.value! ? .All : .Off
                }
        
                [Prefs.Notifications.All, Prefs.Notifications.Devices].map { setting in
                    CheckRow(setting.rawValue) {
                        $0.title = setting.l
                        $0.value = self.model.notification == setting
                        $0.hidden = "$notifications_enabled == false"
                    }.onCellSelection { _, row in
                        let pref = Prefs.Notifications(rawValue: row.tag!)!
                        self.model.notification = row.value! ? pref : .All
                    }
                }.forEach { lastSection = form.last! <<< $0 }
```

**Comment by mats-claassen** [comment]
So your problem is that some of these rows do not appear in rowByTag? 
Your last line should look like:
```
}.forEach { form.last! <<< $0 }
```
I do not know if that will fix your problem but you should try that

**Comment by AndrewSB** [comment]
nope, the rows do appear.

I've realized the issue I had was that I had multiple rows with the same tag. So I was experiencing strange behavior. Should Eureka allow multiple rows to have the same tag? I feel as if tags should be unique. Can I add a PR that asserts tags are unique as you add them to the form?

Really feel like adding that would remove hard-to-find-and-debug errors like the one I just experienced

**Comment by mats-claassen** [comment]
In fact there is an assert when adding rows to a section.
It might not be triggered when the section has not been added to a form yet...

**Comment by AndrewSB** [comment]
@mats-claassen can I share my relevant code with you? I (was) definitely adding multiple rows with the same id string, and they were showing up in the form.

**Comment by mats-claassen** [comment]
Yeah sure.

**Comment by mats-claassen** [comment]
@AndrewSB have you fixed this issue?

**Comment by AndrewSB** [comment]
@mats-claassen this slipped by me! Let me email you the relevant code right now

**Comment by AndrewSB** [comment]
@mats-claassen I can just copy paste it here. Here's how I define my form

```
  form =
            
            Section(header: tr(.ProfileSettingsPresenceTitle), footer: tr(.ProfileSettingsPresenceHelper))
        
            ...
        
                <<< CheckRow(Prefs.Presence.All.rawValue) {
                    $0.title = Prefs.Presence.All.l
                    $0.value = self.model.presence == Prefs.Presence.All
                    $0.hidden = "$presence_enabled == false"
                }.onCellSelection { _, row in
                    let pref = Prefs.Presence(rawValue: row.tag!)!
                    self.model.presence = row.value! ? pref : .All
                }

                <<< CheckRow(Prefs.Presence.Devices.rawValue) {
                    $0.title = Prefs.Presence.Devices.l
                    $0.value = self.model.presence == Prefs.Presence.Devices
                    $0.hidden = "$presence_enabled == false"
                }.onCellSelection { _, row in
                    let pref = Prefs.Presence(rawValue: row.tag!)!
                    self.model.presence = row.value! ? pref : .All
                }
                
                ...
 
                <<< CheckRow(Prefs.Notifications.All.rawValue) {
                    $0.title = Prefs.Notifications.All.l
                    $0.value = self.model.notification == Prefs.Notifications.All
                    $0.hidden = "$notifications_enabled == false"
                }.onCellSelection { _, row in
                    let pref = Prefs.Notifications(rawValue: row.tag!)!
                    self.model.notification = row.value! ? pref : .All
                }
        
                <<< CheckRow(Prefs.Notifications.Devices.rawValue) {
                    $0.title = Prefs.Notifications.Devices.l
                    $0.value = self.model.notification == Prefs.Notifications.Devices
                    $0.hidden = "$notifications_enabled == false"
                }.onCellSelection { _, row in
                    let pref = Prefs.Notifications(rawValue: row.tag!)!
                    self.model.notification = row.value! ? pref : .All
                }

                 ...
        
                <<< ButtonRow(Prefs.Command.Logout.rawValue) {
                    $0.title = Prefs.Command.Logout.l
                    $0.cellStyle = .Value1
                }.cellSetup{ cell, _ in
                    cell.textLabel!.textColor = .blackColor()
                }.onCellSelection(handleButtonAction)
        
```

The enums used here (`Command`, `Notifications`, `Presence`) are defined as so:

```
enum Notifications: String {
        case Off
        case Devices
        case All
}
enum Presence: String {
        case Off
        case Devices
        case All
}
```

So you can see, that `Notifications.All.rawValue` is plainly equal to `Presence.All.rawValue`, both of them resolve to the string `"All"`

If you look at the tags of some of the rows in the definition of the form above, `Prefs.Presence.All.rawValue `, and `Prefs.Notifications.All.rawValue` for example, it's clear that the Row's tags will be the same.

And the code that I have above - with rows which have identical tags in the same form - compiled and ran. So there must be something strange with the assert?

Can you link me to where that assert is? Maybe it only checks for uniqueness within `Section`s and not the entire `Form`?

**Comment by mats-claassen** [comment]
That assert is in [BaseRow.swift](https://github.com/xmartlabs/Eureka/blob/bc14933a040ae2fcc53f059047a375b7d947df93/Source/Core/BaseRow.swift#L162-L172).

That function is called when a row is added to a Form.

**Comment by mtnbarreto** [comment]
@AndrewSB Somehow `func wasAddedTo(section: Section)` is not being called in your case. Could you debug step by step to see the reason so we can help. 
I will close the issue for now.
