### ISSUE TITLE
removing separator

### ISSUE THREAD

**Issue by juliensechaud** [xmartlabs/Eureka#536]
hi
thanks for the great code, awesome work !

I can't manage to just hide separator on a LabelRow (for Example)
I'm in grouped tableview and tried to work with separatorInset,... but can't manage to do it

any ideas please ?

**Comment by mats-claassen** [comment]
Hi @juliensechaud 
No row does manage the separators. This is a thing of UITableView and not directly Eureka related. Please post this questions on StackOverflow (tag: eureka-forms) or search that forums for answers.
 Normally you hide separators changing the `separatorStyle` to `.None` of the tableView of your FormViewController.

**Comment by juliensechaud** [comment]
thanks for the answer but I wanted to hide separators for specific cells
for info I did that  
func hideGroupedSeparator() {
        for view in self.subviews where view != self.contentView {
            if String(view.dynamicType) == "_UITableViewCellSeparatorView" {
                view.removeFromSuperview()
            }
        }
    }

to call in the layoutSubviews of cells' classes

public override func layoutSubviews() {
        super.layoutSubviews()
        self.hideGroupedSeparator()
    }

**Comment by iLandes** [comment]
Hi julien

Can you give more sample code and let see how you do this in Eureka?

**Comment by IronCoderXYZ** [comment]
In case anyone in the future reads this, to hide all separators
in viewdidload
`self.tableView?.separatorStyle = UITableViewCellSeparatorStyle.none`

**Comment by Guillane** [comment]
Hiding a single separator of a UITableViewCell `cell` in **Swift4**:

```
for view in cell.subviews where view != cell.contentView {
  if String(describing: type(of: view)) == "_UITableViewCellSeparatorView" {
    view.removeFromSuperview()
  }
}
cell.layoutSubviews()
```
