### ISSUE TITLE
Cannot change background color of PushRow

### ISSUE THREAD

**Issue by alexvazquez** [xmartlabs/Eureka#537]
Im trying to change the background color of a PushRow but its not working:
```

 }.onPresent{ from, to in
              
                to.view.layoutSubviews()
               
                to.tableView!.backgroundColor = UIColor.lightGrayColor()
          
            }
```
Any clue?

**Comment by mats-claassen** [comment]
Everything can be solved by using your custom `SelectorViewController`. But there might be easier/shorter solutions.

Currently SelectorViewController is just a default implementation for the PushRow. We think that another controller should be used for other implemerntations.

Do you want to change the background of the tableView or of the cells? 
`SelectorViewController` uses `ListCheckRow` so you can use `defaultOnCellUpdate` to change the cells background if you do not use this type of row elsewhere ( or you use it with the same background everywhere).
To customise tableView background color, I have not tried it but keep in mind that `onPresent` is executed before the new view controller is presented. `tableView` might be nil there...

**Comment by alexvazquez** [comment]
Mats thanks a lot for your excelent feedback. Do you know where can I see a example of how to create my own SelectorViewController that has all those implementations? Appreciate it

**Comment by mats-claassen** [comment]
I don't know of an example. But I would start by copying the `_SelectorViewController` from [here](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/Controllers/SelectorViewController.swift#L11) and then change what you need.
You might not even need it to be generic in your case.
The code of this class is really short so it should not be complicated.

**Comment by alexvazquez** [comment]
Thanks a lot Mats, I will play with that and if I can have any question I will come back. Really appreciate so much much your support.

**Comment by alexvazquez** [comment]
Mats I have added a new class "CallCenterTest" based on _SelectorViewController and when I used in my form and build I get and error:

       ```
 form +++
            
            topSection
            
            
            <<< CallCenterTest<String>() {
                $0.title = "Cases"
```
The error is: Generic type "CallCenterTest" specialized with two few parameters (got 1, but expected 2)

Any clue?

**Comment by mats-claassen** [comment]
The error says you need to pass another generic parameter.
_SelectorViewController has two: the value and the row types. Seems you are lacking the second one.
