### ISSUE TITLE
"Disable" Push Row options?

### ISSUE THREAD

**Issue by realenginerd** [xmartlabs/Eureka#538]
I'm trying to create a pushable row that will show all the available items in a list, but not allow any item to be selected. `PushRow` allows me to display of a list of items, but it also allows an item to be selected as the main item. Is there a way to disable this selection? Alternatively, is there another type of row I can use for this purpose?

**Comment by mats-claassen** [comment]
You can do this by changing some default behaviour. You will have to change the `presentationMode` of the PushRow. Currently it is 
```
presentationMode = .Show(controllerProvider: ControllerProvider.Callback { return SelectorViewController<T>(){ _ in } }, completionCallback: { vc in vc.navigationController?.popViewControllerAnimated(true) })
```
You can use your own View Controller instead of `SelectorViewController`. To get started have a look at SelectorViewController's implementation

**Comment by Mike278** [comment]
Hey @realenginerd did you ever come up with a solution to this? I have the same requirement and I'd be interested to see an example.

**Comment by WilliamSundqvist** [comment]
Same issue here! @Mike278  @realenginerd You guys solved it? ;)
