### ISSUE TITLE
Can we support minimumValue & minvalue for number textfield?

### ISSUE THREAD

**Issue by sunbohong** [xmartlabs/Eureka#539]

**Comment by mats-claassen** [comment]
I believe this is part of validation, more than limiting the user input, right?

**Comment by sunbohong** [comment]
@mats-claassen  I have a textfiled for receiving Eyesight input. I need to limit it at 0.1～1.0

**Comment by mats-claassen** [comment]
Well this is currently not implemented.
If you really need it you could implement it and submit a pull request.

**Comment by mtnbarreto** [comment]
We've implemented validations feature in Eureka 2.0.0. 

You should use some of these rules  `RuleGreaterThan, RuleGreaterOrEqualThan, RuleSmallerThan, RuleSmallerOrEqualThan` to provide validation feedback to the user. Check out Example project and Eureka validations' [documentation](https://github.com/xmartlabs/Eureka#validations).
