### ISSUE TITLE
Can we support  show UIPickerView from pop as DateCell?

### ISSUE THREAD

**Issue by sunbohong** [xmartlabs/Eureka#543]

**Comment by mats-claassen** [comment]
Sorry but I do not understand your question. Could you be a bit more explicit?

**Comment by sunbohong** [comment]
https://github.com/xmartlabs/Eureka/blob/0fd33dd55c38dc236bb57aaae5191afda884eefe/Source/Rows/Common/DateFieldRow.swift#L54-L59

I just want show a `UIPickerView`  as UITextField's keyboard view which is pop from bottom.

And **Eureka** has use it in DateFieldRow.

**Comment by mats-claassen** [comment]
Okay I understood you but I think you will have to implement this by overriding the row you want to use.
This is not a core functionality so we will not support it.
