### ISSUE TITLE
Change MultipleSelectorRow value to Array

### ISSUE THREAD

**Issue by mats-claassen** [xmartlabs/Eureka#545]
MultipleSelectorRow value should be an array, not a set, because its values should have an ordering.

**Comment by mats-claassen** [comment]
This could be done in Swift 3 if Arrays can be made Equatable.

**Comment by lognaturel** [comment]
@mats-claassen I'm working on an ordered multiple select row for selecting several tags and have been stuck on exactly this ordering issue. I see that the type parameters for all base classes must conform to `Equatable` but why is that the case? I can't figure out why that constraint is necessary!

**Comment by lognaturel** [comment]
Thought more about this and I see it's needed for `onChange`. In my case, I don't need anything specific to happen on change and I'm not seeing any great options for my needs. Perhaps I could do something weird like keep track of a set of objects which wrap the value I want and an `Int` to represent order. Any ideas would be appreciated.

**Comment by feargswalsh92** [comment]
I want to help add this enhancement, I found this snippet of code on StackOverflow that adds an extension to Array that can give it extra functionality when its' elements are equatable.

`extension Array where Element : Equatable {
    func deletedIndices(byKeeping elementsToKeep: [Element]) -> [Int]
          return self.enumerated().flatMap {
            elementsToKeep.contains($1) ? nil : $0
        }
    }
}` 

However when refactoring the Set to Array<T:Equatable> I get a bunch of errors.
![image](https://cloud.githubusercontent.com/assets/19194339/26516777/8880a61a-4251-11e7-9764-65e62be4ccfc.png)

Any ideas appreciated.

**Comment by feargswalsh92** [comment]
I came across this cocoapod which allows you to define an EquatableArray directly in code.
https://github.com/mikaoj/EquatableArray

**Comment by mtnbarreto** [comment]
After considering this change, we decided to keep current value type. Most of time we are interested in the selected values regardless its order.
