### ISSUE TITLE
SelectorViewController should have option for enableDeselection

### ISSUE THREAD

**Issue by karlvr** [xmartlabs/Eureka#547]
It appears that `SelectorViewController` hard codes a value of `true` for `enableDeselection`. Could that become a property of the row so we can configure it?

**Comment by mats-claassen** [comment]
I think thats a valuable enhancement.
I have a fix in place but I will merge it to the Swift 3 branch.
Do you need this feature now?

**Comment by karlvr** [comment]
Thank you, that’s great. No, I can live without it for the moment—I just changed the default in the code for the moment. Love your work.

**Comment by mats-claassen** [comment]
Merged to `Swift3` branch at #551
