### ISSUE TITLE
The placeholder of TextAreaRow doesn't disappear when I set a delegate to textView

### ISSUE THREAD

**Issue by ghysrc** [xmartlabs/Eureka#549]
```
            +++ Section()
            <<< TextAreaRow("TextArea") {
                $0.tag = "brief"
                $0.placeholder = "some placeholder"
            }.cellSetup({ (cell, row) in
                cell.textView.delegate = self
            })
```
If I didn't set the delegate to textView, it works all right. When I type some words in TextAreaRow, the placeholder disappear.
But I want limit the length of inputs, so I implements the UITextViewDelegate, do my work in textViewDidChange. The placeholder of TextAreaRow never disappear.
![image](https://cloud.githubusercontent.com/assets/4082752/16722353/87d02fe4-4778-11e6-9bbb-595d2213a01e.png)

**Comment by mats-claassen** [comment]
Well this is correct as the cell implements the delegate and a lot of functionality depends on it.
FormViewController has methods that will be called when the delegates of the textView are called.
Not sure which method you want to use but have a look at [the code here](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/TextAreaRow.swift#L128-L200)

**Comment by ghysrc** [comment]
You are absolutely right, what was I thinking...I use the UITextViewTextDidChangeNotification to make it work. Thanks.
