### ISSUE TITLE
Question: How to get the section frame in onSetupView?

### ISSUE THREAD

**Issue by alibasta** [xmartlabs/Eureka#550]
Hi,

thanks for Eureka - it's awesome!!

Im creating a custom section header with the following code:

`

        form +++ Section() {
            var header = HeaderFooterView<ItemDetailHeaderView>(HeaderFooterProvider.NibFile(name: "ItemDetailHeaderView", bundle: nil))
            header.height = { 320 }
            header.onSetupView = { view, _ in
                view.setNeedsDisplay()
                view.setNeedsLayout()
                view.pageControl.numberOfPages = self.imageURLs.count
                
                var itemNumber: CGFloat = 0
                for url in self.imageURLs {
                    let imageNode = ASNetworkImageNode()
                    imageNode.URL = NSURL(string: url)
                    var frame = view.scrollView.bounds
                    frame.origin.x = itemNumber * frame.size.width
                    imageNode.view.frame = frame
                    view.scrollView.addSubview(imageNode.view)
                    itemNumber += 1
                }
                view.scrollView.contentSize = CGSizeMake(itemNumber * view.scrollView.frame.size.width, view.scrollView.frame.size.height)
                view.scrollView.pagingEnabled = true
            }
            $0.header = header
        }`

 Inside the section header is a UIScrollView with a UIPageControl. I need to know the correct frame sizes inside the `onSetupView` to set the correct contentSize of the scroll view and the correct frames of the images. 

What do you recommend?

Best

Alex

**Comment by mats-claassen** [comment]
Hi @alibasta 
First of all, as you are handling with frames you should do this in `viewWillAppear` or later. Normally it is not recommended to do such things in `viewDidLoad`.

And then I would work with the frame width of the tableView or UIScreen's width as width parameter.

**Comment by alibasta** [comment]
Thank you @mats-claassen ! So you recommend manipulating the frame for the scrollview items in `viewWillAppear` (first get the section view and then manipulating the frame) - correct?

**Comment by mats-claassen** [comment]
I would put the code that sets up the section's header  to viewWillAppear or later.
 If you set up your form earlier, you can keep a reference to that section and add the header later.

```
var mySection: Section!
func viewDidLoad() {
      ...
      initializeForm()
}

func viewWillAppear() {
     ...
     mySection.header = ....

}

**Comment by alibasta** [comment]
Thank you @mats-claassen 

I also see the problem using `viewWillAppear`. My problem is that I need to know the correct displayed frame from the header in the `onSetupView` to set the correct frames to the subviews in the header. I only get the frame from the nib - but this is not correct after setting the header height with `      header.height = { 320 }`.

Manipulating the views in `viewDidAppear`works but looks very ugly because the view frames are changing after the cell is visible for the user.

Best

Alex

**Comment by mats-claassen** [comment]
Yeah I know, that has happened to me.
If you know the fixed size of your scrollView and imageViews then you should not trust the frame that comes from the nib but use the correct values. For example if your scrollView has the same width as the tableView or the entire screen then use those widths as they should be correct. 
If that does not work try playing with `setNeedsLayout` and `layoutIfNeeded` although that is not the most clean solution.

**Comment by mats-claassen** [comment]
@alibasta Could you find a solution for this issue?
