### ISSUE TITLE
Eureka with navigation controller problem

### ISSUE THREAD

**Issue by Amefuri** [xmartlabs/Eureka#553]
Hi,

I just try to use example code within my project. and it seem that Eureka form was hided behind my navigation controller pane. 

![eureka form1](https://cloud.githubusercontent.com/assets/1732314/16756633/a4061972-4830-11e6-8a18-08dbdb1ce42e.png)

I expected something like this :

![eureka form2](https://cloud.githubusercontent.com/assets/1732314/16756635/aa56d942-4830-11e6-9e8a-975f835a1aa7.png)

How can I fix this issue?

Thank you,

**Comment by mats-claassen** [comment]
This depends on how you set up the tableView. If you did that by storyboard then see if the constraints are put correctly. 
Otherwise your navigation bar might be translucent or some other issue with your navigation bar.

It is definitely a tableView setup problem, not Eureka related.

**Comment by Amefuri** [comment]
Oh, I didn't know that you can setup Eureka in tableView in storyboard. I thought Eureka was suppose to be code-base only. ? 

But yes you're right. I can fixed this issue by translucent or extend edge property. 
Thank you very much,
