### ISSUE TITLE
Display full size image of ImageRow

### ISSUE THREAD

**Issue by anka** [xmartlabs/Eureka#554]
It would be nice if there is an option to view the image of an ImageRow. So after taking a photo and displaying the small image within the cell there are only options for clearing the image or retake it. Adding another option like "Preview" (or something else) which displays the image in full size as a modal/popover view would be nice.

**Comment by mtnbarreto** [comment]
Seems to me a very edge case scenario, i would recommend you to implement it as a custom row. 
We can share the custom row implementation under https://github.com/eurekaCommunity github organization if you are willing to do so.
