### ISSUE TITLE
presentationMode completionCallback is never called

### ISSUE THREAD

**Issue by alexvazquez** [xmartlabs/Eureka#560]
I have FormViewController where one of my element is a `ButtonRow` and it's `PresentationMode` is SegueName:

```
                    providerRow.presentationMode = .SegueName(segueName: self.isFacility ? "pushToSearchFacility" : "pushToSearchProvider", completionCallback: { vc in
                        
                        vc.navigationController?.popViewControllerAnimated(true)
                        
                    })
```

I have placed a breakpoint where popViewControllerAnimated is called and it never stops there.

How can I fire the completionCallBack in my other UIViewController so this line is reached?

I need this because Im showing some other UIViewControllers in order to select some options and then I have to return, see which row was the the one that originates the push to the view controller so I can set the right value.

Thanks

**Comment by mats-claassen** [comment]
Your `other viewController` should have a `completionCallback` variable just like `SelectorViewController` for example and then call that callback when the user has chosen an option.

**Comment by mats-claassen** [comment]
`SelectorViewController` is an example for this.
