### ISSUE TITLE
How can I add value to a ButtonRow so it looks like PushRow

### ISSUE THREAD

**Issue by alexvazquez** [xmartlabs/Eureka#561]
Im using `ButtonRow` to load some UIViewControllers for searching records on server side.

```
let providerAuthRow = ButtonRow() {
            
            $0.tag = String(serviceAuthIndex) + "_provider"
            $0.title =  String(serviceAuthIndex) + ". Provider"

            $0.presentationMode = .SegueName(segueName: self.isFacility ? "pushToSearchFacility" : "pushToSearchProvider", completionCallback: nil)
            }
```

This is how the Form looks:

![image](https://cloud.githubusercontent.com/assets/347747/16786391/208bdf76-485a-11e6-8e8d-d2cfa19b966c.png)

The if I select a Service (this is a `PushRow`) I have this:

![image](https://cloud.githubusercontent.com/assets/347747/16786408/3969ab68-485a-11e6-984b-003e228f7b85.png)

But for the `ButtonRow` If I set row.value = "Something" I don't see any value to the right of the title.

Any clue how to achieve this?

**Comment by alexvazquez** [comment]
I have just replaced with PushRow and works excellent. Thanks

**Comment by pacification** [comment]
But how it can be implemented with `ButtonRow`?
