### ISSUE TITLE
Custom Row how to attach onChange() event

### ISSUE THREAD

**Issue by alexvazquez** [xmartlabs/Eureka#563]
Im creating a new custom basic row and have a few problems.

This is my XIB design:

![image](https://cloud.githubusercontent.com/assets/347747/16808715/35b3e298-48e3-11e6-8143-1855762bef59.png)

And this is how it looks in the app:

![image](https://cloud.githubusercontent.com/assets/347747/16808811/980308c0-48e3-11e6-9928-e689c6473d30.png)

The code is very simple:

```
public class CustomServiceCell: Cell<Bool>, CellType{
    @IBOutlet weak var btnDelete: UIButton!
    @IBOutlet weak var lblTitle: UILabel!
    
    public override func setup() {
        super.setup()
    }
    
    public override func update() {
        super.update()
    }
}

// The custom Row also has value: Bool, and cell: CustomServiceCell
public final class CustomServiceRow: Row<Bool, CustomServiceCell>, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        // We set the cellProvider to load the .xib corresponding to our cell
        cellProvider = CellProvider<CustomServiceCell>(nibName: "CustomServiceCell")
    }
}

```
What I need is to fire the `onChange()` event when the "Delete" button is pressed so I can do this in my code:

```
 let customRow = CustomServiceRow(){
            
        }.onChange { row in
            // here do the deletion process of whatever
        }
        
        newSection.append(customRow)

```

Any clue? Thanks... Want to take advantage to say that this is the greatest framework I have ever seen for making forms so simple, powerful, and flexible.

Alejandro

**Comment by alexvazquez** [comment]
Solved... just saw that when you set the row.value = something the `onChange()` event is triggered.

**Comment by reenaphilip** [comment]
Where did you add this row.value ? . I want to update a model object when I change the value in custom row textfield. Its not getting updated. How can I achieve it?
