### ISSUE TITLE
When I insert a new section ,the section is strange

### ISSUE THREAD

**Issue by sunbohong** [xmartlabs/Eureka#566]
When I insert a new section,I found two strange thing.

*  The section header title will be upper,I set it as "New Section Optional(1))",but the section header view is "NEW SECTION OPTIONAL(1)".
*  When i add new section one by one,the first section will be slide in from the left one by one.

Xcode 7.3.1  iPhone 6 plus 9.3.2

			.onCellSelection({ (cell, row) in
				let sectionTitle = "New Section ".stringByAppendingString("\(row.indexPath()?.section))")
				let section = Section(sectionTitle)
				print(sectionTitle)
				self.form.insert(section, atIndex: (row.indexPath()?.section)!)
		})

You can download a demo from https://github.com/sunbohong/Eureka/tree/demo

**Comment by mats-claassen** [comment]
Hi @sunbohong ,
1) This is a UIKit behaviour, not Eurekas. Eureka uses the tableView datasource `tableView:titleForHeaderInSection:` method.
2) You want to change the animation of insertion? You can customise that using `insertAnimationForSections` and similar methods in FormViewController

**Comment by sunbohong** [comment]
Hi @mats-claassen  
2)
I found the cause of the problem. 

When i insert new sections,

https://github.com/xmartlabs/Eureka/blob/a762cd7136bf62a983ec62087dcaa9a38a7d3222/Source/Core/Core.swift#L421-L432 

and 

https://github.com/xmartlabs/Eureka/blob/a762cd7136bf62a983ec62087dcaa9a38a7d3222/Source/Core/Core.swift#L761-L765

 will be exec.

They both change tableview's subviews frame,and will lead to confusion animation.

If we remove https://github.com/xmartlabs/Eureka/blob/a762cd7136bf62a983ec62087dcaa9a38a7d3222/Source/Core/Core.swift#L429, the issue will be solved.



 PS.
 
 I'm not sure if you've seen the wrong animation. So please let me tell you how to reproduce step by step.
 
 1. Download and open the demo project. https://github.com/sunbohong/Eureka/tree/demo

 2. Tap "About Button".

 3. Tap "About Button" once again,and you will see the wrong animation.(The third section title view should be slide in from the left; but the second section title view slide in from the left.)

**Comment by mats-claassen** [comment]
OK I have seen it now. I don't think we want to remove the line that reloads the tableView.
I am not sure why the setter of form is being called when inserting a section. This does not happen if you append a section...

**Comment by sunbohong** [comment]
I create a single demo.

When `replaceRange` finishes,the `set` will be called.


	//
	//  ViewController.swift
	//  testRangeReplaceableCollectionType
	//
	//  Created by sunbohong on 16/7/22.
	//  Copyright © 2016年 sunbohong. All rights reserved.
	//
	
	import UIKit
	
	class TestRangeReplaceableCollectionTypeClass {
		required init () {
		}
		var arr = Array<String>()
	}
	
	extension TestRangeReplaceableCollectionTypeClass: Indexable {
	
		var startIndex: Int {
			return 0
		}
	
		var endIndex: Int {
			return arr.count
		}
	
		subscript (position: Int) -> String {
			get {
				return arr[position]
			}
			set {
				arr[position] = newValue
			}
		}
	}
	
	extension TestRangeReplaceableCollectionTypeClass: RangeReplaceableCollectionType {
	
		func replaceRange < C: CollectionType where C.Generator.Element == String > (subRange: Range<Int>, with newElements: C) {
			arr.replaceRange(subRange, with: newElements)
		}
	}
	
	class ViewController: UIViewController {
		var _test: TestRangeReplaceableCollectionTypeClass = { return TestRangeReplaceableCollectionTypeClass() }()
		var test: TestRangeReplaceableCollectionTypeClass {
			get {
				return _test
			}
			set {
				print("set will be called")
			}
		}
		override func viewDidLoad() {
			super.viewDidLoad()
			test.startIndex
			test.insert("sun", atIndex: 0)
		}
	
		override func didReceiveMemoryWarning() {
			super.didReceiveMemoryWarning()
			// Dispose of any resources that can be recreated.
		}
	
	}

**Comment by mtnbarreto** [comment]
@sunbohong I think we can accomplish the same result by doing:

```swift
    public var form : Form {
        get { return _form }
        set {
            guard form !== newValue else { return }
            _form.delegate = nil
            tableView?.endEditing(false)
            _form = newValue
            _form.delegate = self
            if isViewLoaded && tableView?.window != nil {
                tableView?.reloadData()
            }
        }
    }
```

I will make a pull request when i have the chance.
