### ISSUE TITLE
Can't build the framework (Carthage + Xcode 8 b2 / Swift 3)

### ISSUE THREAD

**Issue by alpennec** [xmartlabs/Eureka#567]
Hello,
I am not able to build the Eureka framework using Carthage with Xcode 8 b2 / Swift 3.
I use the "swift3" branch. Find below the error message logged in the terminal.

```
*** Building scheme "Eureka" in Eureka.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Eureka.playground' in workspace '/Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Eureka.xcworkspace'.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Source/Core/Helpers.swift:54:27: error: extraneous argument label 'contentsOf:' in call
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Eureka.playground' in workspace '/Users/Axel/Developer/Skipper-iOS/Carthage/Checkouts/Eureka/Eureka.xcworkspace'.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

<img width="982" alt="screenshot 2016-07-14 19 40 12" src="https://cloud.githubusercontent.com/assets/2082662/16849520/1b50cc2c-49fb-11e6-9552-61e19c217e72.png">

Any idea how to get a correct compilation?
Thanks,
Axel

**Comment by mats-claassen** [comment]
Hi, thanks for reporting. 
When compiling `Source/Helpers.swift` in Xcode you will see that this builds correctly.
Seems that Carthage is using another version of Swift compiler. I do not know how to change this but you must make sure that you are using the compiler from Xcode 8 beta 2.

**Comment by alpennec** [comment]
I don't think the build error is due to the Helpers.swift file. I have the same error with other Swift 3 optimized frameworks (HanekeSwift and SwiftyJSON).

Regarding the compiler, do you think it is linked to the toolchain? https://github.com/Carthage/Carthage/pull/1303

I am using the last available version of Xcode.

**Comment by mats-claassen** [comment]
I am not so familiar with how Carthage works. 
It might be worth a try.

**Comment by alpennec** [comment]
Ok. I'll try to manually install the framework to my project until I can figure out how to make things work using Carthage.

Axel

**Comment by alpennec** [comment]
It is really strange, I tried again with the new Xcode beta version (3), still having the same problem using Carthage. I [opened an issue](https://github.com/Carthage/Carthage/issues/1396) to ask for some help.

**Comment by ikesyo** [comment]
Could you please see https://github.com/Carthage/Carthage/issues/1396#issuecomment-233956060? `Swift3` brach also can't be built.

**Comment by ikesyo** [comment]
Looks like the issue of `Helpers.swift` is related to Debug or Release build. If you add `--configuration Debug` to `carthage` command, the build would success. If you build the target with Release configuration in Xcode, the build would fail too.

**Comment by alpennec** [comment]
@mats-claassen If I download and build the project in the "swift2.3" branch, it works. But not in Release configuration, when I switch in the target Scheme (and Carthage is building the framework also for Release configuration, thus my issue reported above). Maybe this is due to the SWIFT_OPTIMIZATION_LEVEL as suggested by @ikesyo, but the framework should be able to be build with the best optimization level.

The issue is due to the variable predicateVars in Helpers.swift. Any idea how to update this code to make it work with **Fast, Whole Module Optimization [-O -whole module optimization]**.
Do you have any idea why the build fails if we set the maximum optimisation level?

<img width="1355" alt="screenshot 2016-07-23 11 25 57" src="https://cloud.githubusercontent.com/assets/2082662/17077230/a0728bce-50c8-11e6-97f9-193921f9a428.png">

**Comment by mats-claassen** [comment]
Release configuration was fixed in #585 for Swift 3.
I  could also build it with Carthage now although with (quite) some warnings. We will try to fix them later.

**Comment by mats-claassen** [comment]
Swift 2.3 branch also updated. Both should be working without any optimisation switch.
If you can test it that it also works for you that would be great.
Anyway thanks for your feedback and your patience.

**Comment by alpennec** [comment]
@mats-claassen it worked using Carthage in Release configuration 👍 thanks!
