### ISSUE TITLE
How can I change the text color in ButtonRow?

### ISSUE THREAD

**Issue by tc** [xmartlabs/Eureka#569]
I'm trying to do a blue background with white text for a ButtonRow using:

```
            <<< ButtonRow("Login") {
                $0.title = "Login"
                }.onCellSelection({[weak self] row in
                    self!.handleLogin()
                }).cellSetup { cell, row in
                    cell.textLabel?.textColor = UIColor.whiteColor()
                    cell.backgroundColor = UIColor.blueColor()
                }
```
![screen shot 2016-07-16 at 4 42 17 pm](https://cloud.githubusercontent.com/assets/7976/16897848/4cc7cd94-4b74-11e6-85be-057ba403e263.png)
It just stays the tintColor

**Comment by jookes** [comment]
Try to set the textColor in the cellUpdate method like this 

`<<< ButtonRow ("Login") {
                $0.title = "Login"
            }.cellUpdate { cell, row in
                cell.textLabel?.textColor = UIColor.whiteColor()
                cell.backgroundColor = UIColor.blueColor()
            }`

**Comment by tc** [comment]
Great, thanks , using cellUpdate instead of cellSetup works.

**Comment by inf926k** [comment]
It's better to use cell's `tintColor` property here.
```
logoutRow = ButtonRow() { row in
	row.title = "Logout".localized
	row.cell.textLabel?.font = font
	row.cell.tintColor = UIColor(rgb: 0xE25564) 
}
```
