### ISSUE TITLE
CountDownRow

### ISSUE THREAD

**Issue by marcosgriselli** [xmartlabs/Eureka#571]
CountDownRow not displaying values on the first scroll of one field. I need to scroll both Hours and Minutes once (or one of them twice) to get the values on the cell. 

Example shown after selecting the cell and scrolling minutes once: 
![img_5629](https://cloud.githubusercontent.com/assets/14804033/16906295/f32a3e02-4c8b-11e6-8ed5-2581c84eb60a.jpg)

**Comment by mats-claassen** [comment]
This seems to be a bug in UIDatePicker. Have a look at [this SO question](http://stackoverflow.com/questions/20181980/uidatepicker-bug-uicontroleventvaluechanged-after-hitting-minimum-internal).
I do not know if adding a delayed setting of the date is a good solution. Specially if we cannot get a decent value for the delay that will work in all cases.
