### ISSUE TITLE
Textfields Delegates don't work with eureka callbacks

### ISSUE THREAD

**Issue by christianhr** [xmartlabs/Eureka#572]
When I try to use the UITextfield Delegates (by example cell.textfield.delegate = self), the callbacks .onChange, .onCellUnHighlight don't work, sometimes callbacks are not enough so, I need use the UITexfield Delegates

**Comment by mats-claassen** [comment]
Why don;t you use the delegates in FormViewController?
If you look at the cpde of `FieldCell` you will see that it calls delegate methods on FormViewController like `textInputDidBeginEditing`, etc

**Comment by mats-claassen** [comment]
@christianhr Could you use the delegate methods on your FormViewController?
