### ISSUE TITLE
Prompt for camera access when it has been denied

### ISSUE THREAD

**Issue by lognaturel** [xmartlabs/Eureka#573]
When taking a photo from an `ImageRow`, camera access is requested from the user the first time "Take photo" is selected. If the user chooses not to grant camera access, s/he is not prompted again and instead sees the camera interface filled with black. I believe the default behavior in the case where camera access is denied should be to display an alert with a 'Cancel' button and an 'Allow Access' button which jumps to the settings for the current app. If this seems like a reasonable idea (and seems possible), I'd be happy to take a stab at it.

Alternately, do you have suggestions on where to start if I want to do this just for my app?

**Comment by mats-claassen** [comment]
Another option would be just to close the image picker in that case

**Comment by lognaturel** [comment]
@mats-claassen Is this roughly what you're thinking: user taps "Take photo", the camera interface shows up, an alert says something like "You've denied access to the camera, go to settings to fix it" with an OK button, user taps the OK button, the camera interface closes going back to the form?

**Comment by mtnbarreto** [comment]
@lognaturel  I'm not sure but seems to me we need to add AVFoundation to be able to check permissions. Could you check?

**Comment by lognaturel** [comment]
@mtnbarreto Yes, that's the impression that I get as well. Is that a deal breaker?

**Comment by mats-claassen** [comment]
Yes it is. We do not want Eureka to depend on other frameworks.

**Comment by lognaturel** [comment]
@mats-claassen Do you know of any production apps that use Eureka with picture taking capabilities? What do they do to address this? Thanks!

**Comment by mats-claassen** [comment]
No I do not. 
I would try handling that in the end-application by somehow subclassing ImageRow or using a custom one.

**Comment by lognaturel** [comment]
Thanks! I'm not sure when I'll get to this but I'll share what I end up doing.

**Comment by mtnbarreto** [comment]
We should consider all this when implementing ImageRow and share it from EurekaCommunity organization. 

Anyone wants to implement it? We can get started from ImageRow implementation included in the Example project.
