### ISSUE TITLE
Extra distance between secion.

### ISSUE THREAD

**Issue by iBenjamin** [xmartlabs/Eureka#578]
![image](https://cloud.githubusercontent.com/assets/9389813/17017643/c4cf92cc-4f66-11e6-81a1-7ff67a5f36af.png)

After assign section header and height, there is extra height between section, how to avoid it ?

**Comment by mats-claassen** [comment]
I guess you have some issue with either the height of section headers or footers or this is because of the UITableViewStyle you are using.

Also have a look at [this](http://stackoverflow.com/questions/2817308/reducing-the-space-between-sections-of-the-uitableview)

**Comment by iBenjamin** [comment]
thank you!
