### ISSUE TITLE
Font customization bug

### ISSUE THREAD

**Issue by mtpromano** [xmartlabs/Eureka#579]
Hi,

While trying to customize font of rows, I witnessed a strange behavior that seems to be a bug. See GIF at the end.

Code used is:
```
PushRow<String>.defaultCellUpdate = { cell, row in
    cell.textLabel?.font = UIFont.init(name: "Lato-Italic", size: 17.0)!
}
```

What is happening is that first rows are not using the expected font. Then, when scrolling and tableview has to show new/recycled cells, chosen font is finally used.

I tried adding defaultCellSetup too, but this is not helping.

```
PushRow<String>.defaultCellSetup = { cell, row in
            cell.textLabel?.font = UIFont.init(name: "Lato-Italic", size: 17.0)!
}
```

- Environment: 
Eureka (1.7.0)
Xcode Version 7.3.1 (7D1014)
iOS 9.3

![eureka font-bug](https://cloud.githubusercontent.com/assets/16688985/17029708/8d0c719c-4f6c-11e6-9ef9-de93594ff2fe.gif)

**Comment by mats-claassen** [comment]
Hi, I have tried this out but it seemed to work for me. Can you check that you are setting `defaultCellUpdate` before the tableView is loaded?

**Comment by mtpromano** [comment]
Hi,

I set `defaultCellUpdate` just after `super.viewDidLoad()`, like in the Example project.

**Comment by mtpromano** [comment]
Adding `self.tableView?.reloadData()` in `override func viewWillAppear(animated: Bool)` seems to fix it.
