### ISSUE TITLE
Bundle.loadNibNamed now returns an optional • Xcode 8, iOS 10, Swift 2.3

### ISSUE THREAD

**Issue by alpennec** [xmartlabs/Eureka#582]
**Eureka**: 1.5.1 (release 1.7.0).
**Xcode**: 8, beta 3. Swift 2.3.

I can't build the framework, I need to modify the functions
- createView() in HeaderFooterView.swift
- createCell() in Core.swift

to take into account the change in UIKit: Bundle.loadNibNamed now returns an optional. Change can be found here: https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Swift/UIKit.html

<img width="1512" alt="screenshot 2016-07-23 10 59 47" src="https://cloud.githubusercontent.com/assets/2082662/17077193/5e6c775e-50c7-11e6-8be3-46871787576e.png">

**Comment by mats-claassen** [comment]
Hi @alpennec This should be fixed in the latest version of `swift2.3` branch. `Swift3` branch was also updated to Xcode beta 3 syntax
