### ISSUE TITLE
Swift 3 Support - xCode b3

### ISSUE THREAD

**Issue by wm-j-ray** [xmartlabs/Eureka#583]
I've looked thru issues, opened and closed.  Sorry for the inconvenience.

I've used Eureka before and am trying to migrate an existing project to Swift 3. I have tried to install the Swift3 branch using Carthage latest release (0.17.2).  I have also tried to compile as Eureka Swift3 framework.  Neither will build. I am trying to avoid CocoaPods so I have not tried it.

- Carthage: I put the Cartfile in the root of Eureka-Swift3 folder and she blows up looking for workspaces, playgrounds and such.
- xCode8: I tried the workspace approach and the Eureka project in standalone with no luck.

In addition to a bunch of warnings I got a fatal error in Core.  (see attached screen shot)

Question(s):  Is there anyway I can get started on Swift3.  Are there any tricks I could use in build settings, deployment targets and the like?  

Thank you for your help.

Environment: 

    Eureka: Swift3
    Xcode: 8b3
    IOS: 10
    Simulator Target: iPhone SE

![screen shot 2016-07-25 at 10 41 11 am](https://cloud.githubusercontent.com/assets/770852/17105322/c56fe092-5254-11e6-8b03-8da27b559041.png)

**Comment by mats-claassen** [comment]
I am working on this right now. Specially getting Eureka to build in the new Xcode version using Carthage and then removing warnings.
I hope everything will be working soon

**Comment by wm-j-ray** [comment]
Thank you so much for the update.  Really looking forward to it.

**Comment by wm-j-ray** [comment]
So now it's xCode 8b4.  Hopefully there won't be any more swift breakage from now on. 

I looked at this and got Predicate errors. I took a stab at fixing with no success.  Any help or pointers would be appreciated. 

I wasn't sure if you wanted me to open another issue.  

Thanks in advance.

**Comment by mtnbarreto** [comment]
@wm-j-ray 
Swift 3 branch seems to work fine un Xcode8 beta 4 now. If not, let me know.

I will close this issue for now.
