### ISSUE TITLE
DateRow highlight / unhighlight

### ISSUE THREAD

**Issue by chrisortman** [xmartlabs/Eureka#587]
Eureka 1.7.0

I was trying to get consistent behavior of all controls on the form .... color the title blue when editing the row, have grayed out placeholder text when no value and turn text to black when a value is entered.

This proved to be difficult for the DateRow. I wound up accomplishing it by creating my own subclass of _DateRow and changing the initializer onCellHighlight. It seems like it should not be detailTextLabel here but should instead be just textLabel ?

```
 onCellHighlight { cell, row in
            let color = cell.detailTextLabel?.textColor
            row.onCellUnHighlight { cell, _ in
                cell.detailTextLabel?.textColor = color
            }
            cell.detailTextLabel?.textColor = cell.tintColor
        }
```

**Comment by mats-claassen** [comment]
No, this is the intended behaviour. You should be able to change that overriding `onCellHighlight`.
DateRow is different as you have an additional picker and are not editing in the same cell.
iOS does the same as you can see in Calendar app for example.

**Comment by chrisortman** [comment]
Overriding via subclass? Or by specifying a callback when I create the row? `DateRow("").onCellHighlight`

**Comment by mats-claassen** [comment]
Both will work.
If you are using this row more than once it might be better to subclass, as you did. 
But you should also be able to do that with the callbacks.

**Comment by chrisortman** [comment]
Thanks for the help!
