### ISSUE TITLE
Show scrollview (Question)

### ISSUE THREAD

**Issue by v3rmin** [xmartlabs/Eureka#589]
Hi, is it possible to do a pop-up like the one below when you click "region" (not calendar). I didn't find this functionality in the example app.

![simulator](https://media.giphy.com/media/7EauaJGKN7u5W/giphy.gif)

**Comment by mats-claassen** [comment]
That is not in the examples but you can do that using a simple PushRow changing its `presentatioMode` to `.PresentModally`and passing it a view controller that implements your functionality.  If you want to have several rows with this functionality then you might want to [create a custom presenter row](https://github.com/xmartlabs/Eureka#custom-presenter-rows)

Implementing that view controller is your responsibility. It should conform to `TypedRowControllerType ` protocol

**Comment by v3rmin** [comment]
@mats-claassen 👍 Thanks, I will give it a try!

**Comment by v3rmin** [comment]
Is the example code for custom presenter rows outdated? I tried to include the code but got a lot of errors:

**Build Error:**
![eureka_build](http://i.imgur.com/SyV2fQh.png)

**Snippet:**
```swift
import Eureka

public final class CustomPushRow<T: Equatable> : SelectorRow<T, SelectorViewController<T>>, RowType {
  
  public required init(tag: String?) {
    super.init(tag: tag)
    presentationMode = .Show(controllerProvider: ControllerProvider.Callback {
      return SelectorViewController<T>(){ _ in }
      }, completionCallback: { vc in
        vc.navigationController?.popViewControllerAnimated(true)
    })
  }
}
```

**Comment by mats-claassen** [comment]
@v3rmin Yes sorry. This must have been changed in one of the latest updates. 

You have to set `SelectorRow<T, PushSelectorCell<T>, SelectorViewController<T>>` as your superclass. Note the added `PushSelectorCell<T>`. You can use other cells obviously.
