### ISSUE TITLE
Generic Inline picker crash in Example project

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#59]
In the example project, there is a crash (Sigabrt) when selecting values from PickerInlineRow cell and then following up with selecting of an Inline Date Picker from other section. The crash occurs only when one expanded view for inline picker is allowed.

Error details below:
Could not cast value of type '(Eureka.LabelCellOf<NSDate>, Eureka._PickerInlineRow<NSDate>, Eureka.PickerRow<NSDate>) -> ()' (0x1191bf260) to '(Eureka.LabelCellOf<NSDate>, Eureka.PickerInlineRow<NSDate>, Eureka.PickerRow<NSDate>) -> ()' (0x1191bf2b0).

**Comment by mtnbarreto** [comment]
@rajeshmani27 Thanks for reporting it!
