### ISSUE TITLE
Update README to replace PictureRow with ImageRow

### ISSUE THREAD

**Issue by SASDOE** [xmartlabs/Eureka#590]
I would do it myself but because cannot because of the PictureRow image.

**Comment by mats-claassen** [comment]
Hi, thanks for pointing out!
We will fix this soon.

**Comment by SASDOE** [comment]
Might be better to remove the cornerRadius as it is not the default behaviour

**Comment by mtnbarreto** [comment]
We've completely removed ImageRow from default EurekaRow rows.

**Comment by SASDOE** [comment]
Won't that bring breaking changes to anyone using it?

**Comment by mtnbarreto** [comment]
it will, you can get the source code from Eureka example project. It will be provided as custom row under eurekacommunity organization shortly.
