### ISSUE TITLE
Can I consume cell selection event ?

### ISSUE THREAD

**Issue by Amefuri** [xmartlabs/Eureka#593]
Hi,

I want to add some validation that will check if user allowed to press that cell or not. but i'm not sure how I can handle that.

for example:
- if user click on ImageRow
- check if user allow to click this row
- If Yes, process row selection normally
- If No, alert message and do not process with imagePicker

Thank you,

**Comment by mats-claassen** [comment]
You mean you want to disable the cell? Use the `disabled` variable.
If you need help about that check the Readme.

**Comment by Amefuri** [comment]
Hi mats-claassen,

No I did not want to disable a cell. I want it to be enable (clickable) but if condition was not met after user clicked it, I want to show alert box(ex. "you cannot click this button yet") instead of that row action.

**Comment by mats-claassen** [comment]
Well you cannot avoid the event from executing using `onCellSelection`.
For that to happen you would have to subclass every cell to implement that logic in the `didSelect method`.

Another option would be to try and implement that logic in the `presentationMode` of each row. But for example the ImageRow has logic in its `customDidSelect` method so would would probably have to subclass here.

Anyway, `onCellSelection` is called even if cell is set as disabled so you could show an alert box then but you would also have to change the 'disabled appearance' of the cell.

**Comment by Amefuri** [comment]
I see. Thank you for the solution I will try one of those that you suggested.
