### ISSUE TITLE
Update eureka 1.6.0 to 1.7.0 segmented row

### ISSUE THREAD

**Issue by gorbat-o** [xmartlabs/Eureka#594]
hey,

i have just update eureka from 1.6 to 1.7 but now my segmented row doesn't work and i don't understand why,

this is my first code working before on 1.6:
```
        form +++= SegmentedRow<String>("segments") {
            $0.options = ["Passées", "En attente", "Futures"]
            $0.value = currentSection
            } .cellSetup { cell, row in
                cell.height = { 60 }
                cell.layoutMargins = UIEdgeInsetsZero
        }
```

and now, in 1.7 i have got an error like this:
<img width="307" alt="capture d ecran 2016-07-28 a 18 08 58" src="https://cloud.githubusercontent.com/assets/7542553/17220102/5e4bf530-54ee-11e6-8426-1fc82351bfd9.png">

so i try to patch with that:
```
        form
            +++ Section()
            <<< SegmentedRow<String>("segments") {
                $0.options = ["Passées", "En attente", "Futures"]
                $0.value = currentSection
                } .cellSetup { cell, row in
                    cell.height = { 60 }
                    cell.layoutMargins = UIEdgeInsetsZero
        }
```

it's compiling but not working .. :(
thanks for futures helps :)

**Comment by mats-claassen** [comment]
You should use `+++` operator instead of `+++=`.

What do you mean by not working?

**Comment by gorbat-o** [comment]
It's what i've used, but when i execute my app,
they don't show my data

i need to check something else
will keep you updated

**Comment by mats-claassen** [comment]
@gorbat-o  Have you fixed your problem?

**Comment by gorbat-o** [comment]
Nop, i don't find the problem,

i've the same things on 2 projects, and the first crash and not the second :/ sorry

**Comment by Ethenyl** [comment]
Hi,

@gorbat-o can you show us the full code for generating your form ?

Thanks.

**Comment by mtnbarreto** [comment]
@gorbat-o Have you solved it? If not, please share your form view controller code..
