### ISSUE TITLE
Issue with Cocopod installation of Eureka v1.7

### ISSUE THREAD

**Issue by mgyong** [xmartlabs/Eureka#597]
Cocopod version: 1.0.1
Swift version: v2.2

Podfile
********
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Eureka-Example' do
	pod 'Eureka', '~> 1.7'
end

***********
Error
[!] Unable to satisfy the following requirements:

- `Eureka (~> 1.7)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Eureka (~> 1.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by mtnbarreto** [comment]
Someone else having the same issue?
@mgyong  Have you solved it?
