### ISSUE TITLE
Added support for maximum text field lengths

### ISSUE THREAD

**Issue by cmbasnett** [xmartlabs/Eureka#601]
It would be mighty handy to be able to put a hard limit on the amount of characters that can be input on both `TextRow` and `TextAreaRow`.  For example:

    TextAreaRow("comments") {
        // ...
        $0.maxLegth = 60
    }

In the meantime, is there a standard-ish hack to add support for this?

Thanks!

**Comment by cmbasnett** [comment]
Alright, I hacked away at it a bit and came up with [this Gist](https://gist.github.com/cmbasnett/e09fa14d261653aef1809d53d99a13fc).

It's definitely not ideal as it adds a `maxLength` property to anything that extends `Row`, and you must use a custom `FormViewController` class, but it allows for the syntax and behavior I defined in the original post.

**Comment by mtnbarreto** [comment]
Thanks for sharing it!!

**Comment by spifd** [comment]
Hi, no plan to support this? For ex, using rules like RuleMaxLength to enforce the maximum input length.

**Comment by mats-claassen** [comment]
What version did you put in your Podfile? And are you running `pod install` or `pod update`?

**Comment by ykphuah** [comment]
cmbasnett, does the tag needs to be specified for all the rows? not only the rows that I want to set the maxLength?

**Comment by olcayertas** [comment]
I had the similar requirement also I have want to restrict the character set of the row. Instead of extending the `Row` I have defined an other protocol:
```
public protocol InputFilter {
    var allowedCharacterSet: CharacterSet? { get set }
    var maxCharCount: Int { get }
}
```
and than I have defined my own cell and row:

```
open class GSSTextCell: _FieldCell<String>, CellType, InputFilter {

    public var allowedCharacterSet: CharacterSet?
    public var maxCharCount: Int = 1000

    required public init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    open override func setup() {
        super.setup()
        textField.autocorrectionType = .no
        textField.autocapitalizationType = .allCharacters
        textField.keyboardType = .default
    }

    open override func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        let cs = CharacterSet(charactersIn: string)
        // checking empty string for backspace key
        return string == "" || (textField.text?.count)! < maxCharCount && allowedCharacterSet?.isSuperset(of: cs) == true
    }
}
```
```
open class _GSSTextRow: FieldRow<GSSTextCell> {
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}
```
```
public final class CharacterCountAndCharacterSetRestrictedRow: _GSSTextRow, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        cellSetup { cell, row in
            cell.allowedCharacterSet = CharacterSet(charactersIn: "PACFGINSMTVO")
            cell.maxCharCount = 1
        }
    }
}
```
Checking empty string is required to able to use backspace key. This way I do not have to override textField functions on controller level.

**Comment by mndgs** [comment]
You can achieve functionality like this using custom Formatter, 

This should get you started

    class StringMaxLengthFormatter: Formatter {
 
    let maxLength: Int
    /* ... */  
        override func string(for obj: Any?) -> String? {
            if let string = obj as? String {
                return String(string.prefix(maxLength))
            }
            return nil
        }
    
        override func getObjectValue(_ obj: AutoreleasingUnsafeMutablePointer<AnyObject?>?, for string: String, errorDescription error: AutoreleasingUnsafeMutablePointer<NSString?>?) -> Bool {
        
            if let obj = obj {
                obj.pointee = self.string(for: string) as AnyObject?
            }
        
            return true
        }
    }

Usage:

    <<< TextRow {
                $0.useFormatterDuringInput = true
                $0.formatter = StringMaxLengthFormatter(maxLength: 10)
    }
