### ISSUE TITLE
Cell subviews with the same width as cell stop 60pt short of the right edge

### ISSUE THREAD

**Issue by iwarrior74** [xmartlabs/Eureka#608]
![simulator screen shot 12 aug 2016 04 39 08](https://cloud.githubusercontent.com/assets/17153393/17612161/b9f67a78-6046-11e6-9289-3353ede54fe4.png)

I'm trying to create a new custom row and am running into some issues while positioning subviews within the cell. There seems to be a 60pt gap to the right. As the code below shows, the frame printed out for imgView is the same as the frame for the cell, however stops 60pt short from the edge. 

I'm not sure if this is something simple that I've overlooked. The code I'm using is from the ImageRow class, I've just made changes to the init function.

```
public required init(tag: String?) {
        sourceTypes = .All
        super.init(tag: tag)
        presentationMode = .PresentModally(controllerProvider: ControllerProvider.Callback { return ImagePickerController() }, completionCallback: { [weak self] vc in
            self?.select()
            vc.dismissViewControllerAnimated(true, completion: nil)
            })
        self.displayValueFor = nil
        
        
        let imgView = UIImageView(frame: CGRectMake(0, 0, cell.bounds.width, cell.bounds.height))
        imgView.backgroundColor = .redColor()
        cell.addSubview(imgView)
        
        cell.backgroundColor = .brownColor()
        
        print(imgView.bounds)
        print(cell.bounds)
        
    }

```
Here is the console output:
```
(0.0, 0.0, 320.0, 44.0)
(0.0, 0.0, 320.0, 44.0)
```

I've also noticed that setting the row height using `cell.height = { 100 }` does not update the bounds of the cell. Is there any way that I can do this?

**Comment by mtnbarreto** [comment]
At init time probably the cell bound is not calculated properly because the layout is pending to run.  

Which is the device? 
Have you tried passing hardcoded values here? let imgView = UIImageView(frame: CGRectMake(0, 0, cell.bounds.width, cell.bounds.height))

**Comment by mtnbarreto** [comment]
Have you checked which is the view on the upper right corner. Seems the accessory view....

**Comment by iwarrior74** [comment]
The device is iPhone 6. `print(cell.subviews)` returns this:
```
[<UITableViewCellContentView: 0x7f9780d2e1a0; frame = (0 0; 320 44); 
gestureRecognizers = <NSArray: 0x7f9780d85330>; 
layer = <CALayer: 0x7f9780d8b430>>, 
<UIImageView: 0x7f9780c50870; 
frame = (0 0; 380 44); 
userInteractionEnabled = NO; 
layer = <CALayer: 0x7f9780cdde00>>]
```

I've tried passing in hardcoded values to `let imgView = UIImageView(frame: CGRectMake(0, 0, cell.bounds.width, cell.bounds.height))`. If I pass in a width of 320, it stays the same. However, if I pass in a width of 380, it runs to the edge. I don't understand how the width would be 380...

On the cell bound question - is there any way to update or get the correct bounds for the cell?

**Comment by mats-claassen** [comment]
This issue is related to when you are setting the frame of your subview. In iPhone 6, 6 Plus and 7 the screen width is 375. In smaller devices its 320.
This width is adjusted somewhere after the instantiation of your cell that is why it will not work in the `init` method. 

Even in the setup method the cell might not have the correct layout so that you should probably add the subView in the `setup` method and then wait for `layoutSubviews` or more preferably `update` to correctly set the frame of the subView.

**Comment by mtnbarreto** [comment]
you can either set up the width hardcoded depending on the screen size of device type, set up it after cell layout is done, set up `autoresizingMask` mask to stretch imageView whenever it superview increases its size.
