### ISSUE TITLE
Without storyboard on sugeue，what should I do

### ISSUE THREAD

**Issue by huangboju** [xmartlabs/Eureka#609]

**Comment by mtnbarreto** [comment]
@huangboju  Can you elaborate more on the question so i can help?

**Comment by huangboju** [comment]
AController -> BController 

$0.presentationMode = .SegueName(segueName: "BController", 
completionCallback: nil) 

Only this way？

**Comment by mats-claassen** [comment]
You have two ways of using a segue:
```
case SegueName(segueName: String, completionCallback: (UIViewController->())?)
case SegueClass(segueClass: UIStoryboardSegue.Type, completionCallback: (UIViewController->())?)
```

You can use whichever suits you best. Are you having a problem with this?

**Comment by huangboju** [comment]
Thanks,  I have resolved. Like this
<img width="456" alt="2016-08-30 11 52 57" src="https://cloud.githubusercontent.com/assets/14818224/18075545/554051ec-6ea8-11e6-9ac1-fb46b835dfda.png">

This is my code:
//
//  Copyright © 2016年 xiAo_Ju. All rights reserved.
//

import Eureka

// MARK: SegueCell

public class SegueCellOf<T: Equatable>: Cell<T>, CellType {
    
    required public init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }
    
    public override func update() {
        super.update()
        selectionStyle = row.isDisabled ? .None : .Default
        accessoryType = .None
        editingAccessoryType = accessoryType
        textLabel?.textAlignment = .Center
        textLabel?.textColor = tintColor
        var red: CGFloat = 0, green: CGFloat = 0, blue: CGFloat = 0, alpha: CGFloat = 0
        tintColor.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        textLabel?.textColor  = UIColor(red: red, green: green, blue: blue, alpha: row.isDisabled ? 0.3 : 1.0)
    }
    
    public override func didSelect() {
        super.didSelect()
        row.deselect()
    }
}


//MARK: SegueRow

public class _SegueRowOf<T: Equatable> : Row<T, SegueCellOf<T>> {
    public var controller: UIViewController.Type?
    
    required public init(tag: String?) {
        super.init(tag: tag)
        displayValueFor = nil
        cellStyle = .Default
    }
    
    public override func customDidSelect() {
        super.customDidSelect()
        if !isDisabled {
            if let controller = controller {
                let dest = controller.init()
                cell.formViewController()?.pushTo(dest, tag: self.tag)
            }
        }
    }
    
    public override func customUpdateCell() {
        super.customUpdateCell()
        let leftAligmnment = controller != nil
        cell.textLabel?.textAlignment = leftAligmnment ? .Left : .Center
        cell.accessoryType = !leftAligmnment || isDisabled ? .None : .DisclosureIndicator
        cell.editingAccessoryType = cell.accessoryType
        if !leftAligmnment {
            var red: CGFloat = 0, green: CGFloat = 0, blue: CGFloat = 0, alpha: CGFloat = 0
            cell.tintColor.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
            cell.textLabel?.textColor  = UIColor(red: red, green: green, blue: blue, alpha:isDisabled ? 0.3 : 1.0)
        } else {
            cell.textLabel?.textColor = nil
        }
    }
}

/// A generic row with a button. The action of this button can be anything but normally will push a new view controller
public final class SegueRowOf<T: Equatable> : _SegueRowOf<T>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}

/// A row with a button and String value. The action of this button can be anything but normally will push a new view controller
public typealias SegueRow = SegueRowOf<String>
