### ISSUE TITLE
DecimalRow has cannot use backspace to delete the number

### ISSUE THREAD

**Issue by DesmondPang** [xmartlabs/Eureka#61]
DecimalRow has cannot use backspace to delete the number. It seems a problem of the dot separating integer and decimal parts

**Comment by DesmondPang** [comment]
Sorry, the problem only exist when use DecimalRow  with NSNumberFormatterStyle.CurrencyStyle formatter

**Comment by mtnbarreto** [comment]
@DesmondPang okay
