### ISSUE TITLE
PickerInlineRow does not have Default Cell Setup, RowInitializer, Update, OnCellHighlight, and OnCellUnhighlight.

### ISSUE THREAD

**Issue by p-sun** [xmartlabs/Eureka#610]
Most other rows, including DateInlineRow have these 5 functions to set the defaults. Thank you!

iOS 9.3. Xcode 7.3.1. Eureka 1.7.0.

**Comment by mtnbarreto** [comment]
Notice that `PickerInlineRow` is a generic type. 

For instance, the right way to set the defaultCellUpdate to PickerInlineRow is:
```swift
PickerInlineRow<String>.defaultCellUpdate = { ....  }
```

you should do that as many times as different generic types you use in your app.
