### ISSUE TITLE
FormDelegate adopt NSObjectProtocol

### ISSUE THREAD

**Issue by dangthaison91** [xmartlabs/Eureka#614]
Hi, thanks for awesome library. Eureka help me clean my code so much.

I'm using Eureka with RxSwift - a FRP Framework and trying to wrap some properties to Observable. RxSwift provide a DelegateProxy to bridge from Delegate to Reactive. So i have to create EurekaDelegateProxy class then implement functions in FormDelegate like that:

```Swift
class FormDelegateProxy<T: Equatable>: DelegateProxy, DelegateProxyType, FormDelegate {
    
    let sectionsHaveBeenAddedSubject = PublishSubject<T?>()
    
    static func currentDelegateFor(object: AnyObject) -> AnyObject? {
        guard let rowOf = object as? RowOf<T> else { return nil }
        guard let form = rowOf.section?.form else { return nil }
        return form.delegate
    }
    
    static func setCurrentDelegate(delegate: AnyObject?, toObject object: AnyObject) {
        guard let rowOf = object as? RowOf<T> else { return }
        guard let form = rowOf.section?.form else { return }
        form.delegate = delegate as? FormDelegate
    }
    
    func sectionsHaveBeenAdded(sections: [Section], atIndexes: NSIndexSet) {
        //self._forwardToDelegate?.sectionsHaveBeenAdded(sections, atIndexes: atIndexes)
        sectionsHaveBeenAddedSubject.onNext(...)
    }
```

I should call  `forwardToDelegate` to ensure that other features that depend on this delegate will not be affected. But FormDelegate was not adopted `NSObjectProtocol`. So no forwardToDelegate.

**Comment by mats-claassen** [comment]
HI @dangthaison91 , is that the only needed change? Did you try by modifying FormDelegate locally if it works?

It would be interesting to support such use cases. I do not think we will support RxSwift natively but at least give the opportunity to implement a Reactive layer above Eureka.

**Comment by dangthaison91** [comment]
Hi @mats-claassen: We just wanted to wrap `cell.value` to `cell.rx_value` so thought to create Delegate Proxy. But never mind, we recognize that we can override `value` in `didSet`. It's simpler and easier.
Thanks for yours supporting. :D
