### ISSUE TITLE
In DecimalRow, can't edit decimal value in locale where comma is used as decimal mark

### ISSUE THREAD

**Issue by lognaturel** [xmartlabs/Eureka#617]
To reproduce: change phone/simulator language to a language which uses commas rather than periods as the decimal mark (French, for example). Run a project with a form that includes a `DecimalRow`. Enter 5,6 in that `DecimalRow`. Tap 'ok' and it is properly displayed as '5,6.' Tap the row to edit it and the value is displayed as '5.6' with a period rather than a comma. Replace the 6 with a 0 to get '5.0.' Tap 'ok' and the value will still be '5,6.'

It looks like the period shows up as the decimal mark when the field is edited because `useFormatterDuringInput` is set to `false` in `FormatteableRow`. I've tried setting it to `true` when I add the row to the form but that doesn't work. For example, if I try to type `2,55`, as soon as I type `2`, it is replaced by `2,00` and I end up with `2,55,00` and I need to manually delete the extra 0s. I tried setting `maximumFractionDigits` to 2 and not setting `minimumFractionDigits` but then I can't enter in a decimal at all.

How can I make editing a value in a locale where commas are used as the decimal mark equivalent to editing the same value in a locale where periods are used? I would like to be able to tap an empty row and enter in a value with a decimal and then tap the cell to edit it with a comma still being shown but no 0s added.

**Comment by mats-claassen** [comment]
Have you had a look at #264? Seems the same issue.

**Comment by lognaturel** [comment]
Thanks, @mats-claassen, it does sound like the issue described was the same.

To get the behavior I expected, I ended up simply needing to discover `useFormatterOnDidBeginEditing` and set it to `true` when creating the row so that the decimal mark in the field matches the one on the keyboard. I also set `maximumFractionDigits` to 2 and did not set `minimumFractionDigits`.

How about adding a note to the docs stating that if `useFormatterOnDidBeginEditing` set to `false` for a `DecimalRow`, it won't work in locales that don't use the period as a decimal mark. Or perhaps the default should be `true`? Having it be `false` means that any user of a `DecimalRow` in a locale not using a period as a decimal mark is getting unexpected behavior by default. Is there a reason someone would want it `false`?

Let me know if you think there's a change that's worth making either to code or documentation. That's something I should be able to get to quickly!

**Comment by mats-claassen** [comment]
I think the documentation needs a bit of restructuration and there are definitely things missing.
If you want to write something about the DecimalRow, great.

As to the default value of `useFormatterOnDidBeginEditing`, it is nil by default so that the value of `useFormatterDuringInput` will be used. I believe this is for backward comnpatibility but it should definitely be documented.
