### ISSUE TITLE
How to add two textRow at the same line

### ISSUE THREAD

**Issue by baim40** [xmartlabs/Eureka#618]
I've been looking for several time in documentation, issues, and people blog, but i could not find solution how to create two textRow at the same line. I suspect that i need to create a custom row to do it, but i have no idea how make it. can anyone help me? thanks a lot.

**Comment by lognaturel** [comment]
You can take a look at `PostalAddressRow` for some inspiration. You could even start from there and take out everything but postal code and city.

Be careful if you want to use a formatter for one or both of the `UITextField`s, I believe there is an issue at [line 584](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/PostalAddressRow.swift#L584) that will prevent it from working as intended.

**Comment by baim40** [comment]
thanks a lot lognaturel, I am looking at PostalAddressRow.swift right know. Hopefully i can reproduce the row like postal code and city using the same method. By the way is there any other simple way to do it?

**Comment by Ethenyl** [comment]
Hello there,

Check the [Custom rows](https://github.com/xmartlabs/Eureka#custom-rows) section for more details on how to do this.

Hope it will help!
