### ISSUE TITLE
Removing Separator between rows

### ISSUE THREAD

**Issue by caieylau** [xmartlabs/Eureka#619]
Hi! Is there a way we can remove separator between the fields? For normal UITableViewController I would do

self.tableView.separatorStyle = UITableViewCellSeparatorStyle.None

Is there an equivalent of that for the FormViewController?

Thanks!

**Comment by mtnbarreto** [comment]
@caieylau  Have you tried using the same code.. `self.tableView.separatorStyle = UITableViewCellSeparatorStyle.None` ?

**Comment by caieylau** [comment]
OMG i feel dumb for not even trying that first.

**Comment by mtnbarreto** [comment]
👍
