### ISSUE TITLE
Bad access crash when assigning placeholder or value on TextRow

### ISSUE THREAD

**Issue by sureshjoshi** [xmartlabs/Eureka#623]
This is an very strange issue because I can't believe no one else has it, so I'm now confused as to what might be happening.

            <<< TextRow("macAddress") {
                $0.title = $0.tag
                $0.placeholder = "1234"
            }

This crashes, every single time, on the $0.placeholder line with an exec_bad_access - ditto if I assign a $0.value... 

This happened when cocoapods updated my repo from 1.6.0 to 1.7.0 and suddenly my app no longer works. I've tried the usual suspects of clearing the build cache, clearing pod cache, re-installing, etc... But nothing.

**Comment by mtnbarreto** [comment]
where do you assign `$0.value` ?

**Comment by mtnbarreto** [comment]
could you please send the stack trace and send as much information as possible so we can help.

**Comment by sureshjoshi** [comment]
I assign .value at runtime, or sometimes I'll assign it when I setup my form - same problem either way. I'll reply with a stack in a few days when I can load the new version again.

**Comment by mtnbarreto** [comment]
If you are still experiencing the issue, please send the stack trace and reopen the issue.
