### ISSUE TITLE
Adding a custom callback to an inline row

### ISSUE THREAD

**Issue by phiberjenz** [xmartlabs/Eureka#624]
I'm trying hard to grasp how the callbacks system works (ie. onChange, cellUpdate etc.) but my combined lack of understanding of the inner workings of the framework and Swift makes it unclear to me.

What I'm trying to accomplish is this:
I have a custom inline row with it's corresponding row to be expanded/collapsed. Everything works fine, but I have a button in the (possibly) expanded row which is going to perform something that is highly dependant upon variables in the form view controller itself.

It seems to me that in this case, instead of adding a bunch of variables that is set on the inline row and then trickles down to the expandable row, the best way of doing this would be to add a new callback that could be set when creating the row. Please correct me if I'm wrong.

Is there a need to setup new protocols for this? Looking at the InlineRowType protocol, the only callbacks that are defined there are onCollapseInlineRow and onExpandInlineRow. These callbacks are set on the showing row (the one that is always visible). But I want to set a callback on the expandable row (the one which is not always shown). How would I accomplish this?

I think that it's possible considering that onChange callback for the showing row is called when the value changes in the expandable row. Is this because of the changed value from the expandable row is propagated "upwards" to the showing row and triggers the showing rows callback?

I know that this might be a bad description of the problem, but any help would be appreciated!

Regard,
Jens

**Comment by mtnbarreto** [comment]
Why not use `onExpandInlineRow` to set up the button target and action ? 
By doing that you can implement the `ontap` button gesture handler directly in the form view controller. 

You can also set up a function in the expandable row from `onExpandInlineRow` but you will  be in charge of setting up it and also call it whenever the button is tapped. `onExpandInlineRow` passes the string typed cell and row as a parameter so if you declare a property you will be able to set up it directly  (no need to cast). 

> Having a cell you can get the form view controller by invoking `formViewController()` `BaseCell` method.

> All row callbacks (that have nothing to do with inline rows) are saved in `BaseRow` type. This is because we wanted to make custom row creation easy and also be able to invoke them from base types. Just by conforming `RowType` protocol we get all generic callback without the need to declare extra properties.
By contrast, as you have already noticed, `InlineRowType` makes you declare a stored property to hold onExpand onCollapse callbacks. 

Let me know if this helps...
