### ISSUE TITLE
I want to remove a row, which api should I use?

### ISSUE THREAD

**Issue by huangboju** [xmartlabs/Eureka#626]

**Comment by marcsnts** [comment]
form.allRows returns all the rows, if you know the index you can call form.allRows.removeAtIndex

**Comment by huangboju** [comment]
<img width="1001" alt="2016-08-24 8 04 56" src="https://cloud.githubusercontent.com/assets/14818224/17914048/7fa58e7e-69d1-11e6-93f6-f2371ce0a56e.png">

**Comment by mats-claassen** [comment]
You can access the section of the row and then remove the row from that section.

**Comment by mtnbarreto** [comment]
`section.removeAtIndex(rowIndex)` 
`section.removeFirst()`
`section.removeLast()`
//or
`section.remove(:at)` in swift 3

`section[index] = nil` may work too.

having a row is pretty simple to get its index. We can always get its section and the form by...

`row.section?.form`

`section.indexOf(row)`
`section.index(of:)` in swift 3.



and get its index is pretty simple as well. 

> Both `Form` and `Section` types conform to [MutableCollection](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_MutableCollectionType_Protocol/index.html#//apple_ref/swift/intf/s:Ps21MutableCollectionType) protocol. 

Hope it helps.

**Comment by huangboju** [comment]
This is my code and UI, if i do this 'form[0].removeLast()', all row will hidden
<img width="972" alt="2016-08-25 8 30 01" src="https://cloud.githubusercontent.com/assets/14818224/17952549/366fc21a-6a9e-11e6-83d4-8c564bfc32bc.png">
<img width="1022" alt="2016-08-25 8 29 44" src="https://cloud.githubusercontent.com/assets/14818224/17952570/6c758098-6a9e-11e6-8004-7ddbf1a428a1.png">

**Comment by mtnbarreto** [comment]
try with this..

```swift
var section = form[0]
section.removeLast()
```

**Comment by mats-claassen** [comment]
@huangboju Could you solve this?

**Comment by huangboju** [comment]
Yeah, solved
