### ISSUE TITLE
Location row value not updating

### ISSUE THREAD

**Issue by marcsnts** [xmartlabs/Eureka#627]
So I copied and pasted the Location Row implementation into my project and then added the row to my form, however when I select a location (press done in the map view) the row value does not update. The .onChange of the LocationRow does not get called.

**Comment by mtnbarreto** [comment]
Hi @marcsnts ! Have you debugged the code to see if tap gesture handler is called when done button is pressed?

https://github.com/xmartlabs/Eureka/blob/ccaf437578e43737dc9a23988ba37fd3a6b2c236/Example/Example/CustomCells.swift#L574

**Comment by marcsnts** [comment]
Yes @mtnbarreto the tappeDone function does get called

**Comment by mtnbarreto** [comment]
then, seems to me you are overridden the location value somewhere. 
Are you setting location value from your view controller?

**Comment by marcsnts** [comment]
I just have the default <<< LocationRow("location") in my viewDidLoad function, value is not being set anywhere from my end

**Comment by mtnbarreto** [comment]
could you please upload a project so i can take a look.

**Comment by marcsnts** [comment]
`public final class LocationRow : SelectorRow<CLLocation, PushSelectorCell<CLLocation>, MapViewController>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        presentationMode = .Show(controllerProvider: ControllerProvider.Callback { return MapViewController(){ _ in } }, completionCallback: { vc in vc.navigationController?.popViewControllerAnimated(true) })
        displayValueFor = {
            guard let location = $0 else { return "" }
            let fmt = NSNumberFormatter()
            fmt.maximumFractionDigits = 4
            fmt.minimumFractionDigits = 4
            let latitude = fmt.stringFromNumber(location.coordinate.latitude)!
            let longitude = fmt.stringFromNumber(location.coordinate.longitude)!
            return  "\(latitude), \(longitude)"
        }
    }
}

public class MapViewController : UIViewController, TypedRowControllerType, MKMapViewDelegate {
    
    public var row: RowOf<CLLocation>!
    public var completionCallback : ((UIViewController) -> ())?
    
    lazy var mapView : MKMapView = { [unowned self] in
        let v = MKMapView(frame: self.view.bounds)
        v.autoresizingMask = UIViewAutoresizing.FlexibleWidth.union(UIViewAutoresizing.FlexibleHeight)
        return v
        }()
    
    lazy var pinView: UIImageView = { [unowned self] in
        let v = UIImageView(frame: CGRectMake(0, 0, 50, 50))
        v.image = UIImage(named: "map_pin", inBundle: NSBundle(forClass: MapViewController.self), compatibleWithTraitCollection: nil)
        v.image = v.image?.imageWithRenderingMode(.AlwaysTemplate)
        //v.tintColor = self.view.tintColor
        v.backgroundColor = .clearColor()
        v.clipsToBounds = true
        v.contentMode = .ScaleAspectFit
        v.userInteractionEnabled = false
        return v
        }()
    
    let width: CGFloat = 10.0
    let height: CGFloat = 5.0
    
    lazy var ellipse: UIBezierPath = { [unowned self] in
        let ellipse = UIBezierPath(ovalInRect: CGRectMake(0 , 0, self.width, self.height))
        return ellipse
        }()
    
    
    lazy var ellipsisLayer: CAShapeLayer = { [unowned self] in
        let layer = CAShapeLayer()
        layer.bounds = CGRectMake(0, 0, self.width, self.height)
        layer.path = self.ellipse.CGPath
        layer.fillColor = UIColor.grayColor().CGColor
        layer.fillRule = kCAFillRuleNonZero
        layer.lineCap = kCALineCapButt
        layer.lineDashPattern = nil
        layer.lineDashPhase = 0.0
        layer.lineJoin = kCALineJoinMiter
        layer.lineWidth = 1.0
        layer.miterLimit = 10.0
        layer.strokeColor = UIColor.grayColor().CGColor
        return layer
        }()
    
    
    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
        super.init(nibName: nil, bundle: nil)
    }
    
    convenience public init(_ callback: (UIViewController) -> ()){
        self.init(nibName: nil, bundle: nil)
        completionCallback = callback
    }
    
    public override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(mapView)
        
        mapView.delegate = self
        mapView.addSubview(pinView)
        mapView.layer.insertSublayer(ellipsisLayer, below: pinView.layer)
        
        let button = UIBarButtonItem(barButtonSystemItem: UIBarButtonSystemItem.Done, target: self, action: #selector(MapViewController.tappedDone(_:)))
        button.title = "Done"
        button.tintColor = Colors.NeutunPurple.color
        navigationItem.rightBarButtonItem = button
        
        if let value = row.value {
            let region = MKCoordinateRegionMakeWithDistance(value.coordinate, 400, 400)
            mapView.setRegion(region, animated: true)
        }
        else{
            mapView.showsUserLocation = true
        }
        updateTitle()
        
    }
    
    public override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        let center = mapView.convertCoordinate(mapView.centerCoordinate, toPointToView: pinView)
        pinView.center = CGPointMake(center.x, center.y - (CGRectGetHeight(pinView.bounds)/2))
        ellipsisLayer.position = center
    }
    
    
    func tappedDone(sender: UIBarButtonItem){
        let target = mapView.convertPoint(ellipsisLayer.position, toCoordinateFromView: mapView)
        row.value? = CLLocation(latitude: target.latitude, longitude: target.longitude)
        completionCallback?(self)
    }
    
    func updateTitle(){
        let fmt = NSNumberFormatter()
        fmt.maximumFractionDigits = 4
        fmt.minimumFractionDigits = 4
        let latitude = fmt.stringFromNumber(mapView.centerCoordinate.latitude)!
        let longitude = fmt.stringFromNumber(mapView.centerCoordinate.longitude)!
        title = "\(latitude), \(longitude)"
    }
    
    public func mapView(mapView: MKMapView, regionWillChangeAnimated animated: Bool) {
        ellipsisLayer.transform = CATransform3DMakeScale(0.5, 0.5, 1)
        UIView.animateWithDuration(0.2, animations: { [weak self] in
            self?.pinView.center = CGPointMake(self!.pinView.center.x, self!.pinView.center.y - 10)
            })
    }
    
    public func mapView(mapView: MKMapView, regionDidChangeAnimated animated: Bool) {
        ellipsisLayer.transform = CATransform3DIdentity
        UIView.animateWithDuration(0.2, animations: { [weak self] in
            self?.pinView.center = CGPointMake(self!.pinView.center.x, self!.pinView.center.y + 10)
            })
        updateTitle()
    }
}
`

**Comment by iainsmith** [comment]
@marcsnts are you setting a CLLocation value on the row as in the example project?

**Comment by marcsnts** [comment]
Fixed my problem, the problem was that the UI wasn't being updated so I  had to call tableView.reloadData()

**Comment by mtnbarreto** [comment]
This code https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Core.swift#L484 should have updated the row. 
Somehow viewWillAppear is not invoked or the location row is not selected.

**Comment by marcsnts** [comment]
I used this locationManager to set the default value to the user's current location, without the onChange reload it doesn't update.
```
override func viewDidLoad() {
 <<< LocationRow("location") {
            $0.title = "Location"

        }.onChange { [weak self] row in
            self!.tableView!.reloadData()
        }
}
    func locationManager(manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        
        if userLocationSet == false {
            if let userLoc = locations.last {
                let locationRow:LocationRow = form.rowByTag("location")!
                locationRow.value = userLoc
                self.form.rowByTag("location")!.reload()
                self.tableView!.reloadData()
                
                userLocationSet = true
            }
        }
        
    }
```

**Comment by mtnbarreto** [comment]
whenever location manager changes the location row value you must update it programatically (it's not made automatically). 

`self.form.rowByTag("location")?.reload()` should be enough. 

maybe declaring a constant to hold the location row and then using it from locationManager method. Make sure location manager runs in main thread.

**Comment by mtnbarreto** [comment]
`self!.tableView!.reloadData() -> `self?.tableView?.reloadData()` seems better
