### ISSUE TITLE
Masks for Phone Rows

### ISSUE THREAD

**Issue by leandrodestro** [xmartlabs/Eureka#628]
It might be a silly question, but I've found no example on how to create a mask for my numeric inputs for such things like phone numbers, etc.

I've created a CustomRow and added it to my form to solve my problem, but I think that this should be something more easily achievable (there must be a mask definition somewhere).

Am I wrong?

PS: Your framework is just GREAT and is helping me a lot. You've done a great job on it.

**Comment by mtnbarreto** [comment]
A custom row is the way to go here. 
Probably your new custom row uses an external helper such as https://github.com/Serheo/SHSPhoneComponent. 

We have a custom row catalog here: https://github.com/eurekacommunity which intends to provide these complex eureka rows. If you want to share it let me know and i add you to the organization.

**Comment by mtnbarreto** [comment]
I added this row to our EurekaCommunity roadmap.
