### ISSUE TITLE
Click on label in a field ?

### ISSUE THREAD

**Issue by ins0u** [xmartlabs/Eureka#632]
Hello,

I have a little problem..
It's possible to **click on label** in a field, without triggering the change and pass in a custom function (for tooltips) ?

**Comment by mats-claassen** [comment]
Hi,
Is it possible, yes. 
Is it already implemented, no.
Could you do that using an existing row, maybe. (You can definitely create your custom row for this)

You could try adding tap gesture recognizers to your cell in `cellSetup` and then handle it in your controller, but I would create a custom row for this. For which type of row do you want to implement this? You could override that row and add the functionality or just create it from scratch.

**Comment by ins0u** [comment]
> For which type of row do you want to implement this?

For any type of row (LabelRow, PushRow, MultipleSelectorRow, TextRow, SwitchRow, TimeRow, DateRow, etc etc)

> You could try adding tap gesture recognizers to your cell in cellSetup and then handle it in your controller

Do you have a simple example to do this ?

**Comment by mats-claassen** [comment]
No I have no example for this. And I have never done it like that, but it should work
I would create custom rows but you would have to do it for every type of row... which is not so nice.

**Comment by mtnbarreto** [comment]
@ins0u  Was you able to accomplish it?

**Comment by ins0u** [comment]
No, not yet, I have not found enough specific example: /
Can you help me ?
