### ISSUE TITLE
@IBOutlet for the table view is missing in storyboard when using Carthage

### ISSUE THREAD

**Issue by alpennec** [xmartlabs/Eureka#633]
Hello,

I am using Eureka in my Swift 2.3 project (Xcode 8, beta 6).
I added a UITableViewController to my Storyboard, and chose the right class for the.
Even if I add a UIViewController + UITableView inside (with auto layout constraint), I can't specify the tableView (not visible in the outlets).

This results in 2 problems:
- Cells seems to be reused. When I scroll down or up, the cells disappear (like if they were not retained).
- The title for a section header is added multiple times to the table view.

What I did to fix that is to manually embed the framework to my project, so I was able to access the @IBOutlet tableView from the storyboard.

Do you have any idea how to make the @IBOutlet accessible using Carthage?

Thanks,
Axel

**Comment by mtnbarreto** [comment]
Seems to me a Xcode problem with dynamic frameworks. 

As a workaround you can add the same outlet to the view controller that extends FormViewController, connect the outlet and then delete the outlet added by you. 

As a result you will have the storyboard xml updated. 

Let me know if this works.

**Comment by mtnbarreto** [comment]
same as #295

**Comment by alpennec** [comment]
I copied and pasted a view controller from the Eureka example project and updated the view controller class to put mine instead. It worked (i.e. kept the IBOutlet link). Thanks for the help.

**Comment by mtnbarreto** [comment]
cool! you're welcome! 🍻
