### ISSUE TITLE
How to remove entire section

### ISSUE THREAD

**Issue by moyoteg** [xmartlabs/Eureka#634]
I am trying to make it so I can add or remove players which means I need to add and remove sections.

<img width="708" alt="screen shot 2016-08-31 at 4 06 54 pm" src="https://cloud.githubusercontent.com/assets/574112/18148245/b0624b32-6f95-11e6-8bc3-e9bb4e0d6370.png">

**Comment by moyoteg** [comment]
I found the solution =D

### Like this:

`{ (cell, row) in						
		if let section = row.section {		
self.form.removeAtIndex(section.index!)
						}
						row.reload() // or row.updateCell()	
					}`

**Comment by mats-claassen** [comment]
Take care because `section.index` could be nil if the section is hidden. You should not force unwrap that.
