### ISSUE TITLE
textField.selectAll not working properly with onCellSelection/onCellHighlight

### ISSUE THREAD

**Issue by zinyakov** [xmartlabs/Eureka#641]
Hi. I'm trying to implement all text field's text selection with the method `cell.textField.selectAll(nil)` at the time of cell highlight or cell selection. However, `onCellSelection` callback fires only when I select a blank space around text field and within the row (e.g. row label space). Then, trying to call with `onCellHighlight` also has no luck - textfield selection blinks a few seconds and then disappears (I think, after this callback ends).
So, how can I correctly implement all text selection within the Eureka row's textfield after it's selection? Without customising the toolbar like [this](https://github.com/xmartlabs/Eureka/issues/103)

**Comment by mats-claassen** [comment]
`onCellHighlight` seems to work in all cases except when the text of the textfield is tapped and then the cursor does just get positioned. A possible workaround might be to override `func textInputDidBeginEditing<T>(textInput: UITextInput, cell: Cell<T>)` in your FormViewController and check if it is dthe desired cell and then selectAll from there

**Comment by zinyakov** [comment]
Thank you for your advice. It worked nicely on simple rows like IntRow, however, rows with formatters just blink for a second and then the selection disappears. Also, there's a glitch with the right selection mark - it's thinner than the left one.
<img width="37" alt="screen shot 2016-09-23 at 19 16 01" src="https://cloud.githubusercontent.com/assets/15367331/18793174/3cb562b6-81c2-11e6-8c59-d706cf395466.png">

**Comment by mtnbarreto** [comment]
Have you tried using 

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
       cell.textField.selectAll(nil)
}
```

instead of sync...

```swift
cell.textField.selectAll(nil)
```

**Comment by mtnbarreto** [comment]
I just tested it and it works even when the field row has a formatter.

```swift
<<< TextRow() {
                        $0.title = "TextRow"
                        $0.placeholder = "Placeholder"
                    }
                    .onCellHighlightChanged({ (cell, row) in
                        if row.isHighlighted {
                                cell.textField.selectAll(nil)
                        }
                    })
                
                <<< DecimalRow() {
                        $0.title = "DecimalRow"
                        $0.value = 5
                        $0.formatter = DecimalFormatter()
                        $0.useFormatterDuringInput = true
                        //$0.useFormatterOnDidBeginEditing = true
                    }.cellSetup { cell, _  in
                        cell.textField.keyboardType = .numberPad
                    }
                    .onCellHighlightChanged({ (cell, row) in
                        if row.isHighlighted {
                            cell.textField.selectAll(nil)
                        }
                    })
```

The animation looks better if you delay the selection (`DispatchQueue.main.asyncAfter(deadline: .now() + 0.3)`) but it even work when you select the text as the example above shows. 

I'm using Xcode 8, Swift 3, iphone 7 simulator, Eureka v2.0.0-beta.1
