### ISSUE TITLE
Permissions Issues for Overriding and Inherit

### ISSUE THREAD

**Issue by adrianodiasx93** [xmartlabs/Eureka#643]
I am customizing the `ButtonRow`, and when I tried to override the method `prepareForSegue` from the class `BaseRow` and the methods ` customDidSelect` and `customUpdateCell` from the class `Row` I faced the following error _"Overriding non-open instance method outside of its defining module"_. My way around was replacing the access control of these methods from `public` to `open`, which is [now](https://swifting.io/blog/2016/08/17/22-swift-3-access-control-beta-6/) the access level that allows classes to be subclassed and methods overridden.

I'd like to avoid modifying such core classes. Could you guys please change these methods to open, or maybe did you intend these to be public? 

Thanks in advance!

**Comment by mats-claassen** [comment]
Sure we will review all the access levels.
