### ISSUE TITLE
Example project - Cannot scroll to see the whole view 

### ISSUE THREAD

**Issue by juliensch** [xmartlabs/Eureka#644]
Hi, 

Downloaded the example project, however I cannot scroll down to see the whole view. 

Is there something to change to make happen? 

Thanks,

Julien

**Comment by mats-claassen** [comment]
I cannot reproduce this...
Are you sure this is not a Simulator issue?

**Comment by juliensch** [comment]
Indeed, it was a simulator issue. Thanks for pointing that out. 

I still have a few questions. Would be great if you could help me out: 

When using the count down picker is it possible to: 
1. have the option to choose the number of seconds? 
2. change how the time is displayed in the row? I'd like to display something like : 00:00:00 


As you can see in the screenshot below, in the Exercice section, the rows are separated by a gray line but this line is not appearing in the Workout information section. How can I make it appear in this section ? 

![simulator screen shot 11 sept 2016 10 49 53](https://cloud.githubusercontent.com/assets/19761122/18416205/9205f956-780d-11e6-9593-ba11535e8243.png)

Thanks, 

Julien

**Comment by mats-claassen** [comment]
`UIDatePicker` has a `datePickerMode` which allows certain modes (UIDatePickerMode). You have to choose from them or implement your custom picker.

To change how time is displayed you should change `displayValueFor`. Have a look at its current implementation to get some ideas. (https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/DateInlineRow.swift#L74-L84)

**Comment by mats-claassen** [comment]
Also maybe have a look at #606
