### ISSUE TITLE
Custom Row Crashing

### ISSUE THREAD

**Issue by marcsnts** [xmartlabs/Eureka#648]
So I have a custom row for phone numbers and the .xib contains a label for the title and a textfield for the phone number. My app crashes when a segue occurs when the TEXTFIELD of the custom row is the most recent thing that's been touched.  Not really sure how to go about debugging/fixing this.

Here is a report from crashlytics.

1	UIKit	
-[UIResponder _clearOverrideNextResponder] + 156
2
UIKit	
-[UIView(Hierarchy) removeFromSuperview] + 184
3	UIKit	
-[UITableViewCell removeFromSuperview] + 220
4	UIKit	
-[UIView dealloc] + 952
5	UIKit	
-[UIScrollView dealloc] + 796
6	UIKit	
-[UITableViewWrapperView dealloc] + 128
7	libobjc.A.dylib	
(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 508
8	CoreFoundation	
_CFAutoreleasePoolPop + 28
9	CoreFoundation	
__CFRunLoopRun + 1636
10	CoreFoundation	
CFRunLoopRunSpecific + 384
11	GraphicsServices	
GSEventRunModal + 180
12
UIKit	
UIApplicationMain + 204

**Comment by hardikdevios** [comment]
Don't think this issue is related to This lib please try debugging more using proper breakpoint and use deep step alternative you can try exceptionbreakpoint also.

**Comment by mtnbarreto** [comment]
@marcsnts Could you please share more info about the issue, i would really appreciate if you can share your custom row code. Please make sure to follow our contribution guidelines too.
