### ISSUE TITLE
Top menu buttons

### ISSUE THREAD

**Issue by yurevich1** [xmartlabs/Eureka#650]
Please, provide some information how to setup buttons in top navigation menu.

**Comment by mats-claassen** [comment]
You mean the `navigationBar`? That is not related to Eureka and you should ask that elsewhere.

**Comment by yurevich1** [comment]
Yes. I think this is rather complicated to understand lifecycle of Eureka items and interaction. I think this is good idea to update the manual to describe this.

**Comment by mats-claassen** [comment]
A FormViewController is a subclass of UIViewController. So you can simply modify its `navigationBar` the same way as with every other controller (given that if it is embedded in a navigation controller). Is it that what you want? This has nothing to do with Eureka's lifecycle. Eureka does just use a UITableView, the rest is your responsibility.

**Comment by mtnbarreto** [comment]
You can  set up it as you typically do it using any other view controller embedded in a navigation view controller. You are responsible for embedding the FormViewController in a UINavigationController. Then as @mats-claassen said, you can set up the navigationItems to the navigationBar.

**Comment by yurevich1** [comment]
Thanks, @mats-claassen . I wound implement UISearchBar with callback. I have the other question about this task. Imo, this library is complicated for an external programmer (with comparison to the other cocoapod libraries). A lot of abstractions, generics and inheritant subclasses. Nevertheless, this is wonder lib which gives wonder results.
This issue should be closed.
