### ISSUE TITLE
if PushRow selects the same option "row.value" == nil and selected option is "empty"

### ISSUE THREAD

**Issue by moyoteg** [xmartlabs/Eureka#651]
if PushRow selects the same option "row.value" == nil and selected option is "empty"

is this the desired functionality?

Wouldn't it make sense to leave the selected value? =)

<img width="1061" alt="screen shot 2016-09-12 at 11 55 20 am" src="https://cloud.githubusercontent.com/assets/574112/18446537/f7cbd904-78df-11e6-9813-b158936a59ec.png">

**Comment by plastus** [comment]
The user needs the ability to cancel a selection and leave the row value empty. Otherwise, if a user even did one selection there would be no way for them to go back and deselect to leave the value equal to nil.

**Comment by mats-claassen** [comment]
In the `Swift3` branch which should be the next release there is a functionality to specify if an user should be able to deselect a value.

Duplicated by #261.
