### ISSUE TITLE
rowByTag gives nil by retrieving string from PickerInlineRow!

### ISSUE THREAD

**Issue by sebasdeweert** [xmartlabs/Eureka#652]
When I have the following code to show a PickerInlineRow:

```
PickerInlineRow<String>("PickerInlineRowDate") { (row : PickerInlineRow<String>) -> Void in
                
                let dates: NSArray = downloadManager.UserGetAppointment.allKeys as! [String]
                
                let sortedArray = dates.sortedArrayUsingComparator { (d1, d2) -> NSComparisonResult in
                    return (d1 as! String).compare(d2 as! String)
                }
                
                for date in sortedArray {
                
                    let dateFormatter = NSDateFormatter()
                    dateFormatter.dateFormat = "yyyy-MM-dd" //2016-08-05
                    dateFormatter.timeZone = NSTimeZone(name: "UTC")
                    dateFormatter.locale = NSLocale(localeIdentifier: "nl_NL")
                    
                    let date = dateFormatter.dateFromString(date as! String)
                    
                    dateFormatter.dateFormat = "d MMMM yyyy"
                    dateFormatter.timeZone = NSTimeZone(name: "UTC")
                    let timeStamp = dateFormatter.stringFromDate(date!)
                    
                    row.options.append(timeStamp)
                
                }
                
                row.title = "Datum"
                
                row.displayValueFor = { (rowValue: String?) in
                    return rowValue
                }
                
                row.value = row.options[0]
                
            }


```

Now I want to retrieve the `row.value` from above `PickerInlineRowDate` so I use this code:
            
```
<<< PickerInlineRow<String>("PickerInlineRowTime") { (row : PickerInlineRow<String>) -> Void in
                
                if let row: PickerInlineRow<String>! = self.form.rowByTag("PickerInlineRowDate") {
                    
                    print(row.value)
                }

}
```

But when I print the `row.value` I get a `unexpectedly found nil while unwrapping an Optional value`. 

Also when I try: `print(self.form.rowByTag("PickerInlineRowDate"))` I get `nil`.

What am I doing wrong? This is such a simple question, but I can't get to figure it out... 

`print(form.values())` gives me: 

`["PickerInlineRowDate": Optional("24 oktober 2016"), "PickerInlineRowTime": Optional("Test")]` 

So it's stored right?

**Comment by mats-claassen** [comment]
I believe this might happen because the initializer of the row (the block you put after `<<< PickerInlineRow<String>("PickerInlineRowTime")`) is executed immediately from the rows init method. This means that the row has not been added to the form yet. As I do not see your code I do not know if the other row may also not be in the form yet.

What is what you want to do?

**Comment by sebasdeweert** [comment]
True, I found out that the `self.form.rowByTag("PickerInlineRowDate")` can only be retrieved by the .onChange code. It's fixed now! 👍
