### ISSUE TITLE
iTunes Connect rejects builds because NSPhotoLibraryUsageDescription is required

### ISSUE THREAD

**Issue by robbiet480** [xmartlabs/Eureka#655]
I just submitted a build to iTunes Connect that was rejected. The email I received stated:

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.`

I looked through all my source including Pods. The only project that has any mention of PhotoLibrary is Eureka in the ImageRow. What would the long term fix be? For now I just removed the ImageRow.

**Comment by mats-claassen** [comment]
Could reproduce in the Examples project with iOS 10. Thanks for reporting. 

I also realized that adding this key to Eureka's `Info.plist` does **not** fix the issue. Adding it to the proper app's Info.plist works. 

For now one workaround is to remove ImageRow or to just add this key with a description string to your app's `Info.plist`. As this might be bothersome if the app is not really using the ImageRow maybe we should remove the ImageRow from Eureka's core and add it as a custom row to [EurekaCommunity](https://github.com/EurekaCommunity).

**Comment by yannickl** [comment]
@mats-claassen  or may be you should package it as a submodule (Cocoapods).

If people need it they just have to add the specific module, otherwise nothing will be added to the target project:

```
pod 'Eureka/Image', '~> 3'
```

**Comment by robbiet480** [comment]
I'm good for either solution but my preference would be to remove the ImageRow and put it into EurekaCommunity.

**Comment by mats-claassen** [comment]
Yes we will add it to EurekaCommunity. 

Or, it would be welcome if somebody else wants to do this...

**Comment by mtnbarreto** [comment]
ImageRow has been deleted from Eureka core.
