### ISSUE TITLE
Does not work on Xcode 8 / Swift 3

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/Eureka#656]
Xcode 8 
Swift 3 

I am trying to use this framework on a new project. I installed it with cocoapods but it does not work after I convert the syntax to Swift 3. 

Any ideas on how can I deal with this? or are you guys updating the framework to support Swift 3? 

Thanks.

**Comment by cloke** [comment]
It looks like there is a swift 3 branch.

**Comment by richardblakeneywilliams** [comment]
I've tried the Swift3 banch as well, can't get that to work either.

**Comment by richardblakeneywilliams** [comment]
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'

Tried this in my podfile and Xcode 8 still tries to convert syntax to 3

**Comment by mats-claassen** [comment]
Swift 3 branch should be working on Xcode 8 GM. We have still not tried it on Xcode 8. Thanks for reporting.

**Comment by mats-claassen** [comment]
It seems that there is no change needed from Xcode 8 GM to Xcode 8 so that Swift 3 branch should work. In my case if I add the Eureka pod and tap convert to Swift 3 then it works and does not update anything.

Obviously we do not want to "convert" each time we update our pod.
I am not sure where the issue lies as opening Eureka with Xcode 8 does not prompt to convert so it might also have to do with Cocoapods.

**Comment by mats-claassen** [comment]
Installing Eureka with Carthage works seamlessly (if the correct Xcode version is selected in the terminal). So that I guess this has to do with Cocoapods.

For now Eureka works when tapping "convert" after updating the pod. It might also work with setting `Use Legacy Swift Language Version` build setting to `No`.

**Comment by JorgeAGomez** [comment]
It doesn't work for me on any way :(. When click "convert", it tries to make a bunch of changes.

**Comment by richardblakeneywilliams** [comment]
@JorgeAGomez Dude you need to point your Eureka pod to the Swift3 banch. 

Do it like this: 
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'

**Comment by JorgeAGomez** [comment]
@richardblakeneywilliams Thanks man! its working now! 👍

**Comment by mtnbarreto** [comment]
Using Swift 3 branch is at your own risk. We are still making changes on it.
We will add a migration guide, document validations feature and make the final release soon.

**Comment by jasonnam** [comment]
Will the Swift3 branch be merged into master?

**Comment by mats-claassen** [comment]
Yes it will.

**Comment by svedm** [comment]
When I trying to migrate my project to swift3 with eureka pod(Swift3 branch) I get this error:

> Module file was created by a newer version of the compiler: /Users/VeNOm/Library/Developer/Xcode/DerivedData/proj_name/Build/Intermediates/SwiftMigration/proj_name/Products/Debug-iphonesimulator/Eureka/Eureka.framework/Modules/Eureka.swiftmodule/x86_64.swiftmodule

Any ideas how to solve it?

**Comment by cloke** [comment]
I had the same issue using cocoa pods and the following seemed to fix it:

1. Upgraded to the latest version of cocoa pods and verified that I was actually using the latest version. I ended up having to remove all installed gems and adding them back.

2. Remove the POD entry, pod install, added back the entry, and pod install again.

Of course if you aren't using cocoa pods then this might be useless info.

**Comment by svedm** [comment]
@cloke, thx for answer! I tried all, but it doesn't help. 
Sure, I use latest pods(1.1.0.rc.2)

**Comment by mats-claassen** [comment]
@svedm Did you Clean and Build and/ or delete the `DerivedData` folder?

**Comment by kocherovets** [comment]
convert all public members to open in swift 3 branch please, my old code works with it hardly

**Comment by juliensch** [comment]
@mats-claassen, is there a moment when we can expect Eureka to be fully compatible with swift3/xcode 8? 

thanks

**Comment by alibasta** [comment]
Same here @JorgeAGomez @richardblakeneywilliams : After using `pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'
` I did a `pod deintegrate` than a `pod install` and after that Xcode asked for the Swift 3 convert. After doing the convert I see also a lot of changes (public classes to open classes for example). I'm using Xcode Version 8.0 (8A218a)

**Comment by svedm** [comment]
@mats-claassen It's strange but creating new swift3 project with eureka helped me. Thx!
Also what about changing access level of some methods from `public` to `open`? E.g. I cannot override [`keyboardWillShow` method](https://github.com/xmartlabs/Eureka/blob/Swift3/Source/Core/Core.swift#L823) for now because it is public, but I think it should be open.

**Comment by christianhr** [comment]
I add this line to my pod file `pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'` and the form loads good, but when I put the focus on a TextFloat field, the app crash, please see the last line on the log screen

<img width="998" alt="screen shot 2016-09-26 at 4 36 13 pm" src="https://cloud.githubusercontent.com/assets/20073816/18852981/9e6d85e0-8408-11e6-9ca0-3a2469d4124a.png">

**Comment by mtnbarreto** [comment]
TextFloat field? IS this a custom row?

**Comment by christianhr** [comment]
I mean "TextFloatLabelRow"

**Comment by christianhr** [comment]
Hi again, I found the problem, check the next image on line 434, the navigationAccessoryView variable was nil:

`open var navigationAccessoryView : NavigationAccessoryView!`

I had to instantiate it
`open var navigationAccessoryView : NavigationAccessoryView! = NavigationAccessoryView()`

the problem was in Core.swift class, from Eureka

<img width="763" alt="screen shot 2016-09-27 at 7 39 40 am" src="https://cloud.githubusercontent.com/assets/20073816/18873640/0a6b7c2a-8486-11e6-8701-8492c9ba14d2.png">

**Comment by cooler333** [comment]
*  **AlignAllBaseline**
    ```swift
NSLayoutFormatOptions.AlignAllBaseline
    ```

    AlignAllBaseline is unavailable in Swift: Use 'allignAllFirstBaseline/allignAllLastBaseline' instead
*  **loadNibNamed**
    ```swift
return (bundle ?? NSBundle(forClass: ViewType.self)).loadNibNamed(nibName, owner: nil, options: nil)[0] as! ViewType
    ```

    Value of optional type [AnyObject]? not unwrapped; did you mean to use '!' or '?'?

    ```swift
return (bundle ?? NSBundle(forClass: ViewType.self)).loadNibNamed(nibName, owner: nil, options: nil)![0] as! ViewType
    ```

**Comment by cooler333** [comment]
'Use Legacy Swift Language Version' -> YES by default.

    Eureka.xcconfig: SWIFT_VERSION = 2.3;

But it must be 3.0

**Comment by mtnbarreto** [comment]
@cooler333 what do you mean with your comment?

**Comment by Amindv1** [comment]
I'm using Xcode 8 and am having an issue where I'm getting around ~167 errors saying certain lines are incorrect ( I think the eureka file is written in Swift 2.3 and its syntax checking is correcting to Swift 3.0). This is what my podfile looks like:

```
pod 'MagicalRecord'
pod 'MFSideMenu'
pod 'UIDevice-Hardware'
pod 'Flurry-iOS-SDK'
pod 'AKNumericFormatter'
pod 'JSBadgeView'
pod 'RETableViewManager'
pod 'RNBlurModalView'
pod 'APLKeyboardControls'
pod 'MBProgressHUD'
pod 'RBStoryboardLink'
pod 'DTCoreText'
pod 'AFNetworking'
pod 'MTMigration'
pod 'Harpy'
pod 'SDWebImage'
pod 'ELCImagePickerController'
pod 'UAAppReviewManager'
pod 'DZNEmptyDataSet'
pod 'Fabric'
pod 'Crashlytics'
pod 'DeepLinkKit'
pod 'PullToRefreshCoreText', :git => 'https://github.com/garfbargle/PullToRefreshCoreText'
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

```
I tried changing it from 
pod 'Eureka', '~> 1.5'

to 

pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'

to try and get it to work. After changing my pod file I ran pod install. I'm on cocoapods version cocoapods-1.0.1. Is there something I'm missing? I also have Use Legacy Swift Language Version set to NO.

**Comment by mtnbarreto** [comment]
The only test I made was creating a new swift 3 project from scratch. Also travis are building and testing swift 3 code. 

If you are using cocoapods as dependency manager make sure you are successfully fetching the right code. 

`pod 'Eureka', '~> 2.0.0-beta.1'`

**Comment by Amindv1** [comment]
I believe I am, when I run pod install it tells me im using 'Using Eureka (2.0.0-beta.1)'. I also tried changing it from pointing to the branch to the line you provided but I still have the same errors. Any other suggestions?

**Comment by mtnbarreto** [comment]
just in case, I deleted Swift3 branch to avoid any confusion. 

Check if a new project works as expected if not upload a project having the issue so i can take a look.

**Comment by mtnbarreto** [comment]
2.0.0-beta.1 is fully written in swift 3. Take a look at the source files that cocoapods fetches and compare with master branch.

**Comment by Amindv1** [comment]
Yea it seems that I just messed up, after pointing to the branch the issues came from the actual project files not eureka. Thanks!

**Comment by GerdC** [comment]
2.0.0-beta.1 is fully Swift 3 compliant.

*but* there must be some configuration information inside the pod that makes Xcode 8 using an earlier swift version. XCode 8 proposes converting to Swift 3. If I agree, Xcode detects that there is no sourcecode to change. After finishing this process, Xcode 8 uses Swift 3 for Eureka 2.0.0-beta.1.

I've done the three times now. Happens each times I 'pod update'.

**Comment by supdann** [comment]
I just wanted to say that the cocoapods installation as it is explained in the readme did not work for me.

Instead I used:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'YourAPPName' do
   pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
end
```

This worked.

**Comment by Amindv1** [comment]
@supdann 

You can do: 

pod 'Eureka', '~> 2.0.0-beta.1'

but you're right the readme isn't right for swift 3.0

**Comment by RaduGrama** [comment]
Can anyone actually get Eureka to compile with Swift 3? Using a Pod like the one recommended in the readme file in a brand new empty project:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'eurekatest' do
	pod 'Eureka', '~> 2.0.0-beta.1'
end
```

First it asks to convert to Swift 2.3 or Swift 3 (should it ask for that?) and then after clicking Convert to Swift 3 it generates 1,978 compile errors:

![image](https://cloud.githubusercontent.com/assets/88959/19363212/9a04c656-9157-11e6-8226-68834b66b02d.png)

This is a new project, should I just use Swift 2.3 until this gets fixed?

**Comment by mtnbarreto** [comment]
Somehow Xcode asks to convert Eureka to swift3 when integrated via cocoapods. From my understanding either Eureka last beta release or master branch are already written in swift 3 so we should skip the Xcode migration. 
I will take a look at xcode settings/podspec spec to see what's going on when i have time.

**Comment by supdann** [comment]
@Amindv1 , @RaduGrama , @mtnbarreto 

I still wonder how do you even get this to work:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TestApp' do
    pod 'Eureka', '~> 2.0.0-beta.1'
end

```
Every time I call pod install I get the following error:
![bildschirmfoto 2016-10-14 um 10 32 26](https://cloud.githubusercontent.com/assets/9986994/19380944/d42f702c-91f9-11e6-9a2b-3f095310fe0b.png)

But if I edit the Podfile like this, it seems to work fine:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0' 
use_frameworks!

target 'APIER' do
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
end
````
![bildschirmfoto 2016-10-14 um 10 38 51](https://cloud.githubusercontent.com/assets/9986994/19381111/7786e0c0-91fa-11e6-9939-9a88fe56a00a.png)
And I don't need to let Xcode convert the Code of Eureka to Swift 3, because it's already written in Swift 3. Everything fine. 
I also checked the CocoaPods/Specs/Eureka, and found this:
![bildschirmfoto 2016-10-14 um 10 44 25](https://cloud.githubusercontent.com/assets/9986994/19381290/40c6e390-91fb-11e6-8ba8-cd909d050d5e.png)

I don't see a 2.0.0-beta.1 version there. Can this be the reason why the Pod installation failed by just using  **pod 'Eureka', '~> 2.0.0-beta.1'**?

**Comment by sunbohong** [comment]
@supdann 2.0.0-beta.1 version has been published in  https://github.com/CocoaPods/Specs/blob/704194e8634b27e69b5f585a8cc9e6c70e69c551/Specs/Eureka/2.0.0-beta.1/Eureka.podspec.json

**Comment by mtnbarreto** [comment]
Which cocoapods version are you using? 
mine is `1.1.0.rc.3` and it works properly. 

related with #714

**Comment by JorgeAGomez** [comment]
I have the same problem. I need to convert the code to Swift3 every time I `pod install` . Even though it does not make any changes it still asks me to convert it every time.

**Comment by mtnbarreto** [comment]
Which is your cocoapods version ?
Seems to me you should use release candidate version 

> pod --version

**Comment by JorgeAGomez** [comment]
I am running pod version 1.0.1

**Comment by supdann** [comment]
@mtnbarreto 

I updated cocoapods from 1.1.0.rc.2 to 1.1.0.rc.3, and can't install yet using pod **'Eureka', '~> 2.0.0-beta.1'**, I m still getting the same error as in my previous comment (The one with the red text):
```
[!] Unable to satisfy the following requirements:
- `Eureka (~> 2.0.0-beta.1)` required by `Podfile`
...
```
I uninstalled the other cocoapods versions just to be sure. Any other idea about what I should check?

**Comment by chlebta** [comment]
@christianhr I got the same issue as you did you find what's causing that ??

@mtnbarreto

**Comment by mtnbarreto** [comment]
@supdann @chlebta Somehow you don't have eureka spec repo, 
try this: https://guides.cocoapods.org/terminal/commands.html#pod_repo_update

**Comment by Amindv1** [comment]
Yea cocoapods no longer runs 'pod repo update' when you do 'pod install' so it would make sense that you don't have the right eureka spec repo. Try running 'pod repo update' and then 'pod install' and see if that fixes your problem.

**Comment by chlebta** [comment]
Always same issue I thinks it's related to subclassing can you check my sample project 
https://github.com/xmartlabs/Eureka/issues/718

**Comment by JorgeAGomez** [comment]
It works now. I updated cocoapods version to 1.1.0.rc.3 and also runned `pod repo update` and `pod install` and now everything works as expected. Thanks!

**Comment by supdann** [comment]
@mtnbarreto 
You were right, it seems like the problem was that I had to update the spec repo.
Now it works properly. The steps I followed to make it work were:

Install Cocoapods 1.1.0.rc.3
```
sudo gem install cocoapods --pre

```
Update the spec repo (This step took quite a while)
```
pod repo update

```
And finally install whatever is inside in your Podfile
```
pod install
```

**Comment by mtnbarreto** [comment]
Readme was updated with the specific version of cocoapods that should be used to install eureka.
I think we can close this issue for now.
