### ISSUE TITLE
Add image source to an ImageRow

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [xmartlabs/Eureka#659]
Hello,

First of all, I really love Eureka! The product suits its name.

But I have a question:
Is it possible to add a image source to an ImageRow? Now I can choose from '.Camera', '.PhotoLibrary' and '.SavedPhotosAlbum', but I would like to add another option 'App backgrounds' which should show an image picker for a couple of images that my app contains in the assets folder.

The goal is to add a background to my app through Eureka, but with the option to choose from some preloaded backgrounds.

How can I achieve this?

**Comment by mats-claassen** [comment]
I think you should create a custom row for this that subclasses `_ImageRow`
You should then override `customDidSelect` and add your implementation there. You can reuse a lot of code from `_ImageRow's` customDidSelect. I agree that the ImageRow could be easier to extend but currently this would be the best way.

You will obviously have to provide a UIImagePicker that displays your assets images. I am not sure about how to implement that.

**Comment by mtnbarreto** [comment]
Now that we've removed ImageRow from Eureka rows provided by default I recommend you to create a custom row considering this feature. 
Regards

**Comment by mtnbarreto** [comment]
https://github.com/EurekaCommunity is a good place to share it with the community, I can add you to the organization if you are willing to create it.
