### ISSUE TITLE
Update to swift 2.3

### ISSUE THREAD

**Issue by jc-paris** [xmartlabs/Eureka#661]
Hi,

In order to build with Xcode 8 I converted my code to swift 2.3.

But when I'm building the project I got several errors. Because of force unwraps not done for UINib loading or used of AlignAllBaseline instead of AlignAllLastBaseline.

I'm using the last pre release of cocoapods (1.1.0) with the latest version of Eureka available.

How could I solve my issue without changing your code ?

Thanks

**Comment by mats-claassen** [comment]
Hi @jc-paris, there is a branch `swift2.3`. Did you try with that one? We have not released that branch for now so you should point to that branch directly.

**Comment by mtnbarreto** [comment]
We will update master branch to Swift3 shortly. From now we will only add new features to swift 3 version.

**Comment by isabella-rhyu** [comment]
I had a very similar issue in Xcode 8. I am using the `swift2.3` branch but the Eureka framework in my project is still giving several errors, especially with optionals and saying that 'AlignAllBaseline' is not available in Swift. Like @jc-paris I don't want to change your code, any advice?
Thank you

**Comment by mats-claassen** [comment]
Are you using Cocoapods? If so you should be using the latest pre-release. 
If not then I don't know where the issue may be.

**Comment by isabella-rhyu** [comment]
I'm not using Cocoapods, the errors seem to be intermittent, which is strange. I cleaned my project and built it successfully last night but after re-opening it this afternoon they had come back and persisted after another clean.

**Comment by mats-claassen** [comment]
I did just create a project from scratch using Cocoapods and Eureka from `swift2.3` and it worked (I had to set `Use Legacy Swift Language Version ` to YES in the build settings of Eureka target).
So if you have correctly st that setting it should work. Did you try deleting the build folder in `DerivedData`? (or `Option` + `Product -> Clean Build Folder`)

**Comment by isabella-rhyu** [comment]
That worked!
Thank you!
