### ISSUE TITLE
PushRow with duplicate values

### ISSUE THREAD

**Issue by sderuiter** [xmartlabs/Eureka#662]
Hi,

trying out Eureka for my next app. I've setup my form, containing a PushRow that selects customer names. The customer record contains id and name, however the PushRow is filled with an Array of only the names. 

Now, Eureka gives me the possibility to retrieve the selected value using form.values. However, what if two customers have the same name? Can we somehow get the selected index path.row value? Or is there a better way to make sure I have info on the correctly selected customer?

**Comment by mats-claassen** [comment]
PushRow is generic so that you can define it as `PushRow<Customer>` if Customer is Equatable. Then the values will be customers and you have the id and name and whatever else.

To make the PushRow show the names of the customers as the options you should set `displayValueFor` accordingly.

**Comment by sderuiter** [comment]
Thanks. I've now my my Customer struct Equatable. Still need some help on getting this right, though.
I currently have:
`<<< PushRow<Contact>("payToContact") {
                $0.options = Contacts
                $0.displayValueFor = {
                    return $0!.name
                }
            }`

However, this does not work. Contacts is an array of Contact struct. What's the correct code for showing names as options and returning a selected customer struct?

**Comment by mtnbarreto** [comment]
👍
