### ISSUE TITLE
Q: is there a way to "display" text with underlying values

### ISSUE THREAD

**Issue by exalted** [xmartlabs/Eureka#668]
I wonder if is there a way to "display" a `PushRow<UInt>`(meaning user selected value would be an `Uint`, but user visible `options` would be `String`s.

For instance, picker-UI might "visualize": `["Foo", "Bar", "Baz"]` with underlying values `[1, 2, 3]`, and when the user picks `"Foo"`, we would have a way to know it's value is `1`.

**Comment by mtnbarreto** [comment]
have you seen this: #662, #645?

**Comment by exalted** [comment]
Yea, I figured about `displayValueFor` later on. Thanks!
