### ISSUE TITLE
Eureka Form inside a container view

### ISSUE THREAD

**Issue by richardblakeneywilliams** [xmartlabs/Eureka#669]
Has anyone done this? When I try put one into a container view it doesn't even show up.

**Comment by plastus** [comment]
I use Eureka inside container views without issue. Make sure the constraints on your container view are set-up properly within the parent view controller.

**Comment by mbustamanteo** [comment]
I have done this. Make sure the constraints are setup and the embedded view controller is actually set to your own FormViewController

**Comment by mtnbarreto** [comment]
Seems it works properly inside a containerView. Will close the issue for now.

**Comment by valeriozhang** [comment]
Any one can give example code?

**Comment by pouriaalmassi** [comment]
@valeriozhang  https://github.com/pouriaalmassi/EurekaContainer
