### ISSUE TITLE
Repeating rows

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#672]
Hi,
I'm wondering if it's possible to make something like repeater. For example I have a form where I would like to give my users opportunity to attach as many photos as they want and submit the form. Can anyone give me an idea?
Thanks.

**Comment by mspasov** [comment]
Make a section with a single image picker cell. Once you pick a value, add a new cell.
If you have maximum number of slots predefined (and are not many), you could create all the cells, but keep them hidden, until the previous cells value != nil.

**Comment by dneykov** [comment]
Really simple and easy solution.
Thanks.
