### ISSUE TITLE
Any way to center the section footer?

### ISSUE THREAD

**Issue by dromerobarria** [xmartlabs/Eureka#677]
it is posible to center the text of footer or header of a section?

+++ Section(header:"", footer: "center text")

**Comment by mtnbarreto** [comment]
You need to set up a custom view as section footer as the readme points out here: https://github.com/xmartlabs/Eureka#section-header-and-footer

**Comment by jonathanellis** [comment]
Here's a code snippet to achieve this:

```
+++ Section { section in

    var footer = HeaderFooterView(HeaderFooterProvider<UITableViewHeaderFooterView>.class)

    footer.onSetupView = { view, _ in
        view.textLabel?.text = "This text will be centered"
        view.textLabel?.textAlignment = .center
    }
    section.footer = footer
}
```
