### ISSUE TITLE
negative numbers for DecimalRow

### ISSUE THREAD

**Issue by yurevich1** [xmartlabs/Eureka#679]
How can I setup DecimalRow in oreder to input negative values?

That is, I can type something like 10.44 but not -9.329

**Comment by lognaturel** [comment]
I believe the only thing that keeps you from entering a negative number is that the keyboard that's used by the row doesn't include a minus sign. You can check out [this Stackoverflow thread](http://stackoverflow.com/questions/28101460/how-to-add-a-minus-sign-to-the-decimalpad-ios-keyboard) to see some suggestions on how to create a custom keyboard that includes one. Alternately, you could consider adding the minus to the `inputAccessoryView`.

**Comment by mtnbarreto** [comment]
@lognaturel 👍
