### ISSUE TITLE
CountDownRow prints Date as Optional

### ISSUE THREAD

**Issue by mgmart** [xmartlabs/Eureka#683]
After moving my app to Swift3 I encountered the issue with CountDownRow. Other row types seem not to be affected. 

<img width="188" alt="glass_und_iphone_7_ _ios_10_0__14a345_" src="https://cloud.githubusercontent.com/assets/3919652/18850406/acd6be7e-8437-11e6-842f-f03e3c614a61.png">

The corresponding code is here:

       +++ Section("Planning")
        <<< CountDownRow() {
          $0.disabled = disabled ? true : false
          $0.title = "Planned Pause:"
          $0.tag = "pause"
          $0.minuteInterval = 5
          $0.value = Date(timeIntervalSinceReferenceDate: control.pause.amount - 3600)

**Comment by mtnbarreto** [comment]
It's weird since example app works as expected. Anyway now I forced unwrapping

**Comment by mgmart** [comment]
That's indeed weird. Can confirm that the fix works for me also. Thanks!
