### ISSUE TITLE
IntRow format

### ISSUE THREAD

**Issue by akabab** [xmartlabs/Eureka#684]
Hi,

I'd like to format a IntRow so when user type in a value it is displayed with "/8" appended to it:
```
7 -> 7/8
0 -> 0/8
12 -> 12/8
```
the value should still be 7, 0 & 12, only cell should be displayed with "/8" suffix.
Maybe it should be achieved when cell is deselected, so when it has focus it only display the integer value and when released it format it as wanted.

Hope I got understood,

thank you

**Comment by akabab** [comment]
On your Example target, formatters are not working correctly:
- Spell Out style: if I type any new value (eg. 120) it will display an empty cell, but if I type in "one" it will display "one" then when I take focus again it will be filled with integer value "1"..
- other formatters (Energy & Mass): it is not possible to modify the value.... it will keep displaying the formatted version of the initial value.. 

I'm trying to make my custom formatter for my purpose
```
IntRow() {
     $0.title = "Engine #X"
     $0.placeholder = ".../8"
     $0.value = 0
     $0.formatter = EighthsFormatter()
}

class FractionFormatter: NSNumberFormatter, FormatterProtocol {
      override func stringForObjectValue(obj: AnyObject) -> String? {
        if obj.isKindOfClass(NSNumber.self) {
          return String(obj) + "/8"
        }
        return nil
      }

      override func getObjectValue(obj: AutoreleasingUnsafeMutablePointer<AnyObject?>, forString string: String, errorDescription error: AutoreleasingUnsafeMutablePointer<NSString?>) -> Bool {
        return false
      }

      func getNewPosition(forPosition position: UITextPosition, inTextInput textInput: UITextInput, oldValue: String?, newValue: String?) -> UITextPosition {
        return textInput.positionFromPosition(position, offset:((newValue?.characters.count ?? 0) - (oldValue?.characters.count ?? 0))) ?? position
      }
  }
```
it is working but I have the same problem of updating the value.. 

![eureka_customformatter](https://cloud.githubusercontent.com/assets/6205705/18882361/3685bf74-84df-11e6-8b74-7f6cdaecd5b3.gif)

now if I add $0.useFormatterDuringInput = true

![eureka_customformatter2](https://cloud.githubusercontent.com/assets/6205705/18882532/dd349840-84df-11e6-8a5f-a6bb1da13acd.gif)

... how to make this right ?

**Comment by akabab** [comment]
I did achieve something with
```
IntRow() {
     $0.title = "Engine #X"
     $0.placeholder = ".../8"
     $0.value = 0
     $0.formatter = NumberSuffixFormatter(suffix: "/8")
}

class NumberSuffixFormatter: NSFormatter, FormatterProtocol {
    var suffix: String!

    init(suffix: String = "") {
      self.suffix = suffix
      super.init()
    }
    
    required init?(coder aDecoder: NSCoder) {
      fatalError("init(coder:) has not been implemented")
    }

    override func stringForObjectValue(obj: AnyObject) -> String? {
      return String(obj) + self.suffix
    }

    override func getObjectValue(obj: AutoreleasingUnsafeMutablePointer<AnyObject?>, forString string: String, errorDescription error: AutoreleasingUnsafeMutablePointer<NSString?>) -> Bool {

      let str = string.componentsSeparatedByCharactersInSet(NSCharacterSet.decimalDigitCharacterSet().invertedSet).joinWithSeparator("")
      obj.memory = Int(str)

      return true
    }

    func getNewPosition(forPosition position: UITextPosition, inTextInput textInput: UITextInput, oldValue: String?, newValue: String?) -> UITextPosition {
      return textInput.positionFromPosition(position, offset:((newValue?.characters.count ?? 0) - (oldValue?.characters.count ?? 0))) ?? position
    }
  }
```

**Comment by mtnbarreto** [comment]
@akabab have you made it work?

**Comment by mtnbarreto** [comment]
`getNewPosition` method is only called when `useFormatterDuringInput ` is true as Readme points out.

**Comment by akabab** [comment]
yes, now I'm trying to understand how to implement `getNewPosition` with `useFormatterDuringInput=true`, current implementation is making weird stuff, I'd like to be able to edit the value but not the "/8" suffix

**Comment by mtnbarreto** [comment]
okay, so I will close the issue for now...

Open another one if you need help with `getNewPosition`, not sure if you can do it by using it.
