### ISSUE TITLE
Custom presented row not able to return values to the presenter row 

### ISSUE THREAD

**Issue by mohan-shyam** [xmartlabs/Eureka#685]
I'm using Eureka (Swift 2.3 branch) and have created a Custom row to present `mediaPicker`.

Additional information at [http://stackoverflow.com/questions/39448586/how-to-present-a-viewcontroller-using-a-row-in-eureka-forms](url)

This was based on modifying the `LocationRow` available to my requirements.

The problem is I'm not able to set the value using row.value nor return a string which can be displayed while the previous row is presented.

Here is what I use,

    // MusicRow
    public final class MusicRow : SelectorRow<MPMediaItemCollection, PushSelectorCell<MPMediaItemCollection>, AddMusicViewController>, RowType {
        public required init(tag: String?) {
            super.init(tag: tag)
            presentationMode = .Show(controllerProvider: ControllerProvider.Callback { return AddMusicViewController(){ _ in } }, completionCallback: { vc in vc.navigationController?.popViewControllerAnimated(true) })
            displayValueFor = {
                guard let musicTitle = $0 else { return "" }
                let representativeItem = musicTitle.representativeItem
                print("representativeItem = \(representativeItem)")
               let representativeItemTitle = representativeItem?.title
               return  "\(representativeItemTitle)"
            }
        }
    }

    // MusicViewController
    public class AddMusicViewController : UIViewController, TypedRowControllerType, MPMediaPickerControllerDelegate {
    
    public var row: RowOf<MPMediaItemCollection>!
    public var completionCallback : ((UIViewController) -> ())?
    
    private lazy var musicPicker : MPMediaPickerController = { [unowned self] in
        let mediaPicker = MPMediaPickerController.self(mediaTypes:.Music)
        return mediaPicker
    }()
    
    private var musicArray = [MPMediaItem]()

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
        super.init(nibName: nil, bundle: nil)
    }
    
    convenience public init(_ callback: (UIViewController) -> ()){
        self.init(nibName: nil, bundle: nil)
        completionCallback = callback
    }
    
    public override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(musicPicker.view)
        
        musicPicker.delegate = self
        musicPicker.allowsPickingMultipleItems = true
        
        // Remove "Back" button for AddMusicViewController
        self.navigationItem.leftBarButtonItem = UIBarButtonItem(title: "", style: .Plain, target: nil, action: nil)
    }
    
    // After selection, store the data into a temporary variable
    public func mediaPicker(mediaPicker: MPMediaPickerController, didPickMediaItems mediaItemCollection: MPMediaItemCollection) {
        musicTemp = mediaItemCollection
        if musicTemp == nil {
            noMusic = true
        } else {
            noMusic = false
            row.value? = musicTemp!
            print("row.value = \(row.value)")
        }
        completionCallback?(self)
    }
    
    // Cancel mediaPickerController
    public func mediaPickerDidCancel(mediaPicker: MPMediaPickerController){
        // Dismiss the picker if the user canceled
        noMusic = true
        completionCallback?(self)
    }
    }

**Comment by mtnbarreto** [comment]
use `row.value = musicTemp!` instead of `row.value? = musicTemp!`. 

Could you please try scrolling out MusicRow and make it visible again after selection a music from the picker. Seems to me it is a issue related with the row refresh.

**Comment by mohan-shyam** [comment]
Thanks very much @mtnbarreto . I knew it was a very trivial issue, and the solution was even trivial. Sorry for taking your time, which is due to my inexperience. Taking baby steps in iOS dev! +1
