### ISSUE TITLE
Swift 2.3 official release

### ISSUE THREAD

**Issue by gragera** [xmartlabs/Eureka#687]
Hi,

Any chance to get an official release for Swift 2.3 rather than relaying in a branch in our Podfiles?

Thanks!

**Comment by mtnbarreto** [comment]
Hey @gragera , we have no plans to add official support to swift 2.3, actually we will continue eureka support only for swift 3. 

Is there any special reason you want a official release?

**Comment by shawnce** [comment]
We would like to have a Swift 2.3 official release. We have the need to move to Xcode 8 but stay on Swift 2.3 while we 1) wait for other external dependencies become ready for for Swift 3, and 2) likely waiting until Swift 3.0.x/3.x given some issues we are tripping across in Swift 3.

**Comment by gragera** [comment]
My reasons are the same as @shawnce's :)

**Comment by banjun** [comment]
from pod developer point of view...
`pod spec lint` can be passed with published version of dependencies (there is no support for branch dependency specifier for podspec).
so we want to use a published Eureka pod from swift-2.3 branch for updating our pods depending on Eureka for Swift 2.3.

**Comment by shawnce** [comment]
Any update on this? Also what is the current expectation for Swift 3 support leaving beta status?

**Comment by banjun** [comment]
after migrating several projects to Swift 2.3 & 3, i think bumping to Swift 3 directly are not always difficult as to Swift 2.3.
actually many published pods are not compatible to Swift 2.3, without some modifications.
so I, personally for now, no longer need Swift 2.3 ver..

now Xcode 8.2 is announced as the last Xcode supporting Swift 2.3.

**Comment by mtnbarreto** [comment]
As @banjun said, Xcode will no longer support swift 2.3 so there is no need to spend time making an official release. I expect everyone is migrated by then.

@shawnce We will release an official swift 3 release shortly. Will be pretty much similar to master current branch code.
