### ISSUE TITLE
Unwanted 0 after comma for DecimalRow

### ISSUE THREAD

**Issue by prbaron** [xmartlabs/Eureka#69]
Hello,

Each time I want to enter a decimal value into a DecimalRow (example 3,63), I have to do the following steps

  1. Type `3`
  2. Type `,`
  3. Press `Cancel` (because a 0 is added after the comma)
  4. Type `63`

How can I get rid of the step 3 ?

Best regards

**Comment by prbaron** [comment]
My phone was in French so we do not have `.` for decimal but `,` (13,50€). I changed my local to english and had the `.` button. When I enter 13.50, everything works.

So I guess the problem is because of the comma.

**Comment by bre7** [comment]
Bump. Is it just me or this bug still active ?

Rep:
1. Add DecimalRow in VC
2. Type `5`
3. Type `6`
4. Type `,` (or the corresponding decimal separator shown on your screen)
5. Type `8`

Expected: 56,8 (or 56.8 depending on locale)
Result: 56,08 (or 56.08 depending on locale)

No custom formatter was used. Just vanilla example. (Locale: UY)
