### ISSUE TITLE
Eureka validations with swift 2.3

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#692]
Is it possible to use Eureka built-in validations with swift 2.3?

**Comment by mtnbarreto** [comment]
Not, it's only available on swift3. Regards

**Comment by dneykov** [comment]
Okay thanks.
I have to consider migrate my app to swift 3.

**Comment by mtnbarreto** [comment]
@rafaelmaroxa has implemented it, here the pull request  #710. It's already merged on swift2.3 branch.
