### ISSUE TITLE
Error when compiling CustomRow with Swift 3.0

### ISSUE THREAD

**Issue by txaiwieser** [xmartlabs/Eureka#693]
- Environment: Xcode 8, and have tried the "2.0.0 Beta 1" and the latest commit from "master".

I have couple custom Rows that inherit from _FieldRow. and I'm getting a compiler error:

```
Undefined symbols for architecture i386:
  "direct field offset for Eureka._FieldCell.(textField.storage in _3A88909586E8B5678F695AC90DD64A31) : __ObjC.UITextField?", referenced from:
      Eureka._FieldCell.textField.setter : __ObjC.UITextField in IntAsStringRow.o
      Eureka._FieldCell.(textField.materializeForSet : __ObjC.UITextField).(closure #1) in IntAsStringRow.o
      Eureka._FieldCell.textField.setter : __ObjC.UITextField in IntCurrencyRow.o
      Eureka._FieldCell.(textField.materializeForSet : __ObjC.UITextField).(closure #1) in IntCurrencyRow.o
      Eureka._FieldCell.textField.setter : __ObjC.UITextField in IntAsStringRow.o
      Eureka._FieldCell.(textField.materializeForSet : __ObjC.UITextField).(closure #1) in IntAsStringRow.o
      Eureka._FieldCell.textField.setter : __ObjC.UITextField in IntCurrencyRow.o
      Eureka._FieldCell.(textField.materializeForSet : __ObjC.UITextField).(closure #1) in IntCurrencyRow.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any Ideas on how I can fix this?

Thanks!

**Comment by txaiwieser** [comment]
Just made more tests and its happening when inheriting from any Cell, I tried with
class CustomCell: TextCell

**Comment by kuquert** [comment]
Same here, any ideas?

**Comment by mtnbarreto** [comment]
Custom row code is an external library or are just source file that belong to your iOS project?
Could you please share it code or upload a project so i can look into it.

**Comment by txaiwieser** [comment]
I made a sample project reproducing the error, its very straight foward, just one class with direct or indirect inheritance from _FieldCell.
https://dl.dropboxusercontent.com/u/4986807/CustomRowTest.zip

**Comment by mtnbarreto** [comment]
Could you please check now using master branch?

**Comment by mtnbarreto** [comment]
@txaiwieser @kuquert

**Comment by txaiwieser** [comment]
Yes, its now working as expected! Its a very weird but..
I saw how you've fixes, any idea why it doesn't work when using lazy vars? The problem was related to properties storage right?

**Comment by peymankh** [comment]
@mtnbarreto The same thing seems to be happening for UITextView as well.

**Comment by mtnbarreto** [comment]
@pedrovereza @txaiwieser @kuquert Are you guys using carthage to integrate Eureka? 
Looks like the issue only happens when using Carthage. Could you confirm?

**Comment by pedrovereza** [comment]
I think you meant to mention @peymankh 😅

**Comment by peymankh** [comment]
@mtnbarreto @pedrovereza Hey, yes.

**Comment by txaiwieser** [comment]
Yes, I'm using Carthage too
