### ISSUE TITLE
2.0.0.3 beta fails to install on platform 9.0

### ISSUE THREAD

**Issue by adek05** [xmartlabs/Eureka#695]
https://github.com/CocoaPods/Specs/blob/master/Specs/Eureka/2.0.0-beta.1/Eureka.podspec.json#L17

Documentation suggests using 9.0 when installing this pod, while the new release is not marked as compatible with this platform.

**Comment by mtnbarreto** [comment]
@adek05  Could you please send the issue you are experiencing?
