### ISSUE TITLE
Are DecimalRows with a formatter supposed to lose its value after editing?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#697]
Sorry for not being able to write a good title...

I have a decimal row in my form. I set its formatter to a `NumberFormatter` that only shows 2 decimal places:

            <<< DecimalRow(someTag) {
                row in
                // setting general stuff here...
                let formatter = NumberFormatter()
                formatter.maxiumFractionDigits = 2
                row.value = 1.234567
                row.formatter = formatter
        }

When I ran the app and saw the form, I saw that the value is indeed formatted correctly (1.23). Then I tapped on the row to try to edit it, it now shows me the true value (1.234567), which is nice. I did nothing to the value and tapped on "Done" on the keyboard. The value shown is now back to 1.23 again.

Here's the weird thing. I expected the true value to be shown when I tapped on the row _again_, right? But it wasn't! It shows the formatted value 1.23! It seems like the original 1.234567 is lost!

Is this intentional?

**Comment by mtnbarreto** [comment]
I think that when you leave the input field Eureka takes the string and tries to convert it to a value using your formatter. This makes you lost precision since your formatter has maxiumFractionDigits = 2. 
I'm not completely sure  but seems to me this is what is going on.

**Comment by mtnbarreto** [comment]
also displayed value string has only 2 significant digits that makes impossible to get the original value.
