### ISSUE TITLE
TableView margin

### ISSUE THREAD

**Issue by sagits** [xmartlabs/Eureka#698]
Hi, im adding a margin to my tableView (the default Eureka tableView) using this approach:

```
self.tableView!.contentInset = UIEdgeInsetsMake(0, 20, 20, 0);
```

The left margin works, but the right not. No matter the number i use on the right margin (0, 20, 80) the tableView always show this way (it looks like the cell wont resize):

![image](https://cloud.githubusercontent.com/assets/6174566/19053069/ab3a9664-898f-11e6-93ad-1ba1e642a606.png)

Can you help me please?

**Comment by mtnbarreto** [comment]
there are many issues related with table view and table view cells margin. Please take a look at them.

**Comment by mtnbarreto** [comment]
@sagits  Do you know how to accomplish that without using Eureka?
