### ISSUE TITLE
missing PickerRow

### ISSUE THREAD

**Issue by douglasd3** [xmartlabs/Eureka#70]
I'm using Eureka with CocoaPods and the PickerRow class is missing from Rows.swift. I'm running the 1.1.0 version.

Error: Use of unresolved identifier 'PickerRow'

**Comment by justinmakaila** [comment]
+1. Digging around the source, I see that it's there, but it's not in the Carthage build for whatever reason...

I'm guessing it has to do with tagging releases.

@mtnbarreto Do you have any ideas?

**Comment by justinmakaila** [comment]
For the record, this is due to tags. The release that Carthage and CocoaPods download is v1.1.0, which is behind master (obviously) and does not contain PickerRow. Quick fix:
```
$ git tag v1.1.1
$ git push origin master --tag
```

**Comment by mtnbarreto** [comment]
I have just released a new version. 
Regards
