### ISSUE TITLE
Reload section of form not working

### ISSUE THREAD

**Issue by meismyles** [xmartlabs/Eureka#700]
What is the correct way to reload a section of a form, or even just the whole form itself.

I have one section of a form that has a text field I can use to create entries in an array, and then populate another section of the form with these entries.

No matter what I try though I can't seem to reload the list section. What is the correct way of doing this?

I have tried `form.sectionBy(tag: NAME).reload()`, `tableView?.reloadData()` and a few others, but what should be the correct way of doing this?

**Comment by mtnbarreto** [comment]
Could you please share your form code??

Have you read this: https://github.com/xmartlabs/Eureka#how-to-update-a-section-headerfooter ?

If you add a new section to a displayed form or add rows to a displayed section these changes should be reflected automatically which means you don't need to do anything else.

**Comment by meismyles** [comment]
@mtnbarreto Yep I have read that thanks. Here is the form code:

```
form
+++ Section("Add Category")
    <<< NameRow("NameRow"){ row in
        row.title = "Name"
        row.placeholder = "Enter Category Here"
        row.add(rule: RuleRequired())
        row.add(rule: RuleClosure { _ in
            let productCategoryTitles = self.productCategories.map { $0.title }
            for title in productCategoryTitles {
                if title == row.value! {
                    return ValidationError(msg: "Category already exists!")
                }
            }
            return nil
        })
        row.validationOptions = .validatesOnChange
    }
    .onChange { row in
        (self.form.rowBy(tag: "AddCategoryButton") as? ButtonRow)?.hidden = Condition(booleanLiteral: row.value?.isEmpty ?? true)
        (self.form.rowBy(tag: "AddCategoryButton") as? ButtonRow)?.evaluateHidden()
    }
    <<< ButtonRow("AddCategoryButton"){ row in
        row.title = "Add Category"
        row.hidden = Condition(booleanLiteral: true)
    }
    .onCellSelection { cell, row in
        self.addProductCategory(title: (self.form.rowBy(tag: "NameRow") as! NameRow).value!)
    }
+++ Section("Current Categories")
    if self.productCategories.isEmpty {
        form.last! <<< LabelRow(){ row in
            row.title = "No Categories"
        }
    }
    else {
        for option in self.productCategories {
            form.last! <<< LabelRow(option.title!){ row in
                row.title = option.title
            }
        }
    }
```

So in the first section I call `self.addProductCategory(...)`, this subsequently updates `self.productCategories`, I then was hoping calling `tableView.reloadData()` or getting the second section and calling `section.reload()` would force it to run through the loop again and create any added `LabelRow()`.

Am I missing something here?

**Comment by mtnbarreto** [comment]
I think this is well explained in the doc and example project. 

Seems to me the code you posted was added to  form view controller's `viewDidLoad` method.

You should add a new row whenever `AddCategoryButton` button is tapped....


```swift
 .onCellSelection { cell, row in
       let lastSection = form.last!
       let: nameRow: NameRow =  self.form.rowBy(tag: "NameRow")
       let labelRow =  LabelRow(){ row in
            row.title = nameRow.value
        }
       lastSection <<<  labelRow
    }
```

That code will add a new row to the last section, so you have only to update the dsl array, either by adding rows to a section or a section to the form. Once the form is on screen the only way to make changes on it is by making modification on dsl structure which means add remove replace rows or sections. 

Hope it helps.
