### ISSUE TITLE
Custom section header with hiding function 

### ISSUE THREAD

**Issue by chlebta** [xmartlabs/Eureka#701]
Hello,
I'm trying to create custom header section with a button to hide this section, here's my code : 

`HeaderView`
```
    var trigerAction: (()->Void)!
    @IBAction func didClickDeleteButton(sender: AnyObject) {
        if trigerAction != nil {
            trigerAction()
        }
    }
```

`formViewController`
```
        +++ Section(){ section in
                var header = HeaderFooterView<PurchaseOrderDetailCustomHeaderView>(HeaderFooterProvider.NibFile(name: "PurchaseOrderDetailCustomHeaderView", bundle: nil))
                header.onSetupView = { view, section in
                    view.sectionId = 1
                    view.trigerAction =  { () -> Void in
                            section.hidden = true
                        }
                }
                section.header = header
                section.hidden = .Function(["stepper"], { form -> Bool in
                    let stepperRow = self.form.rowByTag("stepper") as? StepperRow
                    return stepperRow!.value > 0 ? false : true
                })
            }
```

When I click on the button my `trigerAction void` is called but the section is not hidden, so any help or idea ?

- Environment: Eureka (1.7) , Xcode(7.3.1) and iOS (9).

**Comment by mtnbarreto** [comment]
I think you should call section's `evaluateHidden()` method to make the section visible if it is hidden.

```swift
view.trigerAction =  { () -> Void in
                            section.hidden = true
                            section.evaluateHidden()
                        }
```

Moreover, after the form appeared, whenever you change section hidden property you should invoke `evaluateHidden()` .

@chlebta let me know if that does the trick.

**Comment by chlebta** [comment]
@mtnbarreto 
cool it work :)

**Comment by chlebta** [comment]
Please, I've another question is it possible to create dynamically another section.
for example when user tap + button it create new section with some fields
