### ISSUE TITLE
defaultOnCellHighlightChanged event not being called

### ISSUE THREAD

**Issue by chrisortman** [xmartlabs/Eureka#704]
Running Eureka 2.0.0.beta-1, iOS

I have some events bound to the `defaultOnCellHighlightChanged` callback that since upgrading are no longer being called. 

```swift
func validateStringRow(_ cell : Cell<String>, row : RowOf<String>) {
            if let rules = validationRules[row.tag!] {
                let result = self.validate([row.tag! : rules])
                invokeCallbackWithNonRequiredErrors(result, row: row)
            }
}
 ZipCodeRow.defaultOnCellHighlightChanged = validateStringRow
```

I had previous rolled my own validation if that helps...I know there's built-in's now, but had hoped to defer adopting them as I'm close to releasing this app.

**Comment by mtnbarreto** [comment]
it was an issue, thanks for reporting it!!

**Comment by chrisortman** [comment]
Thanks! It looks like the function is getting called now. How can I tell if I am being called because of a highlight or unhighlight? 

I expected to check row.isHighlighted but that doesn't seem to change before the callback is invoked?
