### ISSUE TITLE
How to use common UITableViewCell with Eureka cells

### ISSUE THREAD

**Issue by Cokile** [xmartlabs/Eureka#707]
I want to use a common `UITableViewCell`(named `myCell`) whose `accessoryType` is `.DisclosureIndicator` with several Eureka cells. When I tap `myCell`, it will push a `UIViewController`. 

My first thought is use `PushRow`, but I don't know how to make `PushRow` to push a custom `UIViewController`.

**Comment by mtnbarreto** [comment]
Have you read https://github.com/xmartlabs/Eureka#custom-rows?

**Comment by Cokile** [comment]
@mtnbarreto Thanks!
