### ISSUE TITLE
How to change TextAreaRow placeholder's size?

### ISSUE THREAD

**Issue by Cokile** [xmartlabs/Eureka#708]
I want to change the font size of `TextAreaRow`, so I use the code below: 

```Swift
descRow = TextAreaRow() { row in
      row.placeholder = "Please enter something"
    }.cellSetup({ (cell, row) in
      cell.height = {151}
    }).cellUpdate({ (cell, row) in
      cell.textView.font = UIFont.pf(UIFontWeightRegular, size: 15)
    })
```

However, it only change the font size of the `textView` and leave the placeholder with the default size.

**Comment by mtnbarreto** [comment]
I think that you can do it by setting up `placeholderLabel` cell's property from `cellSetup` or `cellUpdate` callback.

**Comment by Cokile** [comment]
Thanks!
