### ISSUE TITLE
TextRow can have wrong value due to autocorrect

### ISSUE THREAD

**Issue by graemesi** [xmartlabs/Eureka#71]
When using a TextRow, sometimes the autocorrected text is shown to the user, but the non-autocorrected text is present in the form.values() dictionary.

1. In a text row type some nonsense text such as 'asdd'. The autocorrect system on iOS will highlight the text with a light blue color. 
2. Don't press return to accept the autocorrect suggestion. Instead tap Done to dismiss the keyboard.
3. The autocorrected text (e.g. "Add") is put in the textfield
4. If you examine the form.values() dictionary you'll see that the non-autocorrected text 'asdd' is the value for the TextRow.

**Comment by teonator** [comment]
The atutocorrect bug still happened on Eureka 5.0.0 (iOS 12.3.1). Is there a fix?
