### ISSUE TITLE
PushRow selection not updating after return

### ISSUE THREAD

**Issue by csimmonsbluebook** [xmartlabs/Eureka#711]
When presenting a FormViewController modally, that is embedded inside a Navigation Controller, I am having a problem with PushRow. I select the PushRow, then select an option, the view goes back to the original page, but the selection does not update the PushRow value and the PushRow remains grayed out like it is still selected. This is shown in the gif below. Any ideas how to fix this issue?

![pushrowproblem](https://cloud.githubusercontent.com/assets/19786779/19190018/07137a88-8c69-11e6-9f71-0cffefa3da50.gif)

Eureka: 2.0.0-beta.1
Xcode: 8.0
iOS: Deployment Target 9.0

**Comment by mohan-shyam** [comment]
Have you set row.value?

```
.cellUpdate { cell, row in
                    row.value = "Whatever you've selected"
            }
```

**Comment by csimmonsbluebook** [comment]
The row value is typically updated automatically when selecting a PushRow's value. I'm not quite sure how I solved the problem, but I removed a few segue connections and the navigation controller. Then re-embedded the view in a navigation controller and made the connections again and it seems to be working for now.
