### ISSUE TITLE
ImageRow crash

### ISSUE THREAD

**Issue by kocherovets** [xmartlabs/Eureka#712]
Hi! After moved ImageRow from example project my project crashes on Take Photo button. Debugger does not show why. Example project works fine. I have used ImageRow previously in my project with Eureka and did not change my code.

**Comment by mtnbarreto** [comment]
try using this: https://github.com/EurekaCommunity/ImageRow

**Comment by kocherovets** [comment]
It does not work too. I will debug and write result here

**Comment by floscom** [comment]
Add this in your info.plist

**Key:** Privacy - Photo Library Usage Description
**Value:** Allow photos

This should fix the problem!

**Comment by mtnbarreto** [comment]
@kocherovets Could you get around of it using @floscom suggestion?

**Comment by kocherovets** [comment]
Thanks
