### ISSUE TITLE
Failed to install with instruction for version 2.0/Swift3 coccoapod

### ISSUE THREAD

**Issue by mamcx** [xmartlabs/Eureka#713]
I follow the instrucctions for install Eureka with swift 3:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
def myPods
    pod 'Eureka', '~> 2.0'
end

target 'basura' do
    myPods
end

```
I get this error:
```

[!] Unable to satisfy the following requirements:

- `Eureka (~> 2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Eureka (~> 2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

If I use directly the master branch, it install but not compile in Swift 3. I get this:

> error: The following binaries use incompatible versions of Swift:
> ...../Developer/Xcode/DerivedData/basura-hfgwjonfvjlxoufnbgnpillymopi/Build/Products/Debug-iphonesimulator/basura.app/Frameworks/Eureka.framework/Eureka
>..../Developer/Xcode/DerivedData/basura-hfgwjonfvjlxoufnbgnpillymopi/Build/Products/Debug-iphonesimulator/basura.app/basura

This is in new, blank project without modifications

Xcode:Version 8.0 (8A218a)
Pod: 1.1.0.rc.2

**Comment by csimmonsbluebook** [comment]
@mamcx I was getting the same error.

After running 'pod repo update' to make sure that wasn't the problem I used:

pod 'Eureka', '~> 2.0.0-beta.1'

**Comment by mamcx** [comment]
That fix the first issue, but still get the binary is incompatible. I get this additional warning:

> ld: warning: ignoring file.../Developer/Xcode/DerivedData/basura-hfgwjonfvjlxoufnbgnpillymopi/Build/Products/Debug-iphonesimulator/Eureka.framework/Eureka, file was built for i386 which is not the architecture being linked (x86_64): ...../DerivedData/basura-hfgwjonfvjlxoufnbgnpillymopi/Build/Products/Debug-iphonesimulator/Eureka.framework/Eureka

It compile for device.

**Comment by mtnbarreto** [comment]
Seems that it has to do with the project configuration or the cache. We've been using it through cocoapods and it works perfectly.

**Comment by mamcx** [comment]
You are rigth. i recreate manually the project and do the conversion to swift 3 without the wizard. It work now.
