### ISSUE TITLE
SWIFT 3 configuration

### ISSUE THREAD

**Issue by GerdC** [xmartlabs/Eureka#714]
Each time I 'pod update' to 2.0.0-beta.1, XCode 8 forces me to update my project to Swift 3.

To examine what happens, I did the following

1. pod update to 2.0.0-beta.1
2. Commit everything to git using SourceTree
3. Let XCode 8 do the update to Swift 3
4. Look in SourceTree what is changed by the update.

I find that the update inserts the line
				SWIFT_VERSION = 3.0;
several times into the file 
.../Pods/Pods.xcodeproj

Context:
			baseConfigurationReference = F5D28069C7FB1AC5E9AF95B580CA7254 /* Eureka.xcconfig */;
			buildSettings = {
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				CURRENT_PROJECT_VERSION = 1;
				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
				DEFINES_MODULE = YES;
				DYLIB_COMPATIBILITY_VERSION = 1;
				DYLIB_CURRENT_VERSION = 1;
				DYLIB_INSTALL_NAME_BASE = "@rpath";
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_PREFIX_HEADER = "Target Support Files/Eureka/Eureka-prefix.pch";
				INFOPLIST_FILE = "Target Support Files/Eureka/Info.plist";
				INSTALL_PATH = "$(LOCAL_LIBRARY_DIR)/Frameworks";
				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
				MODULEMAP_FILE = "Target Support Files/Eureka/Eureka.modulemap";
				MTL_ENABLE_DEBUG_INFO = NO;
				PRODUCT_NAME = Eureka;
				SDKROOT = iphoneos;
				SKIP_INSTALL = YES;
				SWIFT_VERSION = 3.0;
				TARGETED_DEVICE_FAMILY = "1,2";
				VERSIONING_SYSTEM = "apple-generic";
				VERSION_INFO_PREFIX = "";
			};
			name = Release;

I'm not a cocoapods expert, but I think this comes from the file Eureka.xcconfig.
So maybe the file Eureka.xcconfig should contain something like
                 SWIFT_VERSION = 3.0;

What do you think?

**Comment by ZuYuanZhou** [comment]
I can't compile for swift 3 either. Any other settings?

**Comment by caieylau** [comment]
I can't do it either.

**Comment by caieylau** [comment]
I deleted the derived data folder and it worked after that. Go to Xcode -> Preference -> Location -> Derived Data Folder and delete it. Remove the pod -> Pod install -> Add it back in -> Pod install again! This worked for me. Worth a try!

**Comment by GerdC** [comment]
My workaround works too: updating to Swift 3 as XCode suggests.

The point of this issue: Workarounds shouldn't be necessary.

**Comment by mtnbarreto** [comment]
@GerdC Seems to me that configuration (SWIFT_VERSION = 3.0) is already there (in eureka framework).

Check your cocoapods version please. You should use the newest one.

I just checked cocoapods integration in a project created from scratch using Xcode 8 and it works perfectly.

**Comment by mtnbarreto** [comment]
According cocoapods release notes to get this property set up  ("[Installer] Set the SWIFT_VERSION for CocoaPods generated targets") you should have used cocoapods 1.1.0.beta.1 and above. 

you can install pre release versions by `gem install cocoapods --pre`

**Comment by GerdC** [comment]
Yes, `gem install cocoapods --pre` fixes the problem.
