### ISSUE TITLE
Fetch CoreData and display results as options in a PushRow

### ISSUE THREAD

**Issue by mohan-shyam** [xmartlabs/Eureka#717]
How to fetch from CoreData and display the results as options in a PushRow?

I have two entities defined with a relationship between them as well. The second entity has a one to many relationship with the first one. I intend to use the results from second entity, as the values for the first one.

Any suggestions are welcome.. Thanks in advance.

**Comment by mohan-shyam** [comment]
I would like to add more information to my question...

Cell Setup:

```
+++ Section()
            <<< PushRow<String>() {
                $0.tag = "AudioDeviceTag"
                $0.title = "Audio Device"
                $0.options = audioDeviceList.map { $0.name! }
        }
```

Where audioDeviceList is `[AudioDevice]`

And, I try to get the values from the form,

```
if let audioDeviceInput = (formInput["AudioDeviceTag"])! {
            audioDeviceTemp = (audioDeviceInput as? AudioDevice)!
            print("audioDeviceTemp = \(audioDeviceTemp)")
        }
```

Below is the error!!!

`Could not cast value of type '__NSCFString' (0x3857b6a8) to 'TestApp.AudioDevice' (0x10cb68).`

**Comment by mats-claassen** [comment]
I believe the error comes because you are setting the name of the `AudioDevice` as option and therefore as value and then you try to cast that String to AudioDevice which won't work.

**Comment by mohan-shyam** [comment]
Thanks for looking into this @mats-claassen . Yes, that is the reason for the error. But, how would you suggest a similar implementation? 

An array of custom type which is an NSManagedObject subclass, has to be the `options` for a `PushRow`?? I'm a big fan of Eureka, and have it in my app, quite extensively. But, there are situations like these, where I'm clueless!! :/

Additional Info about `AudioDevice`,

```
extension AudioDevice {

    @nonobjc public override class func fetchRequest() -> NSFetchRequest {
        return NSFetchRequest(entityName: "AudioDevice");
    }

    @NSManaged public var name: String?
    @NSManaged public var type: String?
    @NSManaged public var uid: String?
    @NSManaged public var addDate: NSDate?
    @NSManaged public var rules: NSSet?

}

```

**Comment by mohan-shyam** [comment]
Tried implementing a custom row, by tweaking an existing view controller. But, in `cellForRowAtIndexPath`, `cell` value is turning out to be `nil`.

```
public override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell
    {
        print("Entered")
        if let cell:UITableViewCell? = self.tableView.dequeueReusableCellWithIdentifier("AudioDeviceCell") {
            print("Entered, again")
            let audioDevice = fetchAudioDeviceController.objectAtIndexPath(indexPath) as! AudioDevice
            print("Again")
            print("Cell = \(cell)")
            cell!.textLabel?.text = audioDevice.name
            
            return cell!
        }
    }
```

Console : 

```
Entered
Entered, again
Again
Cell = nil
fatal error: unexpectedly found nil while unwrapping an Optional value
```

And, this viewController is working perfectly when used in a separate scenario..

**Comment by mohan-shyam** [comment]
All I need is for a way to implement an array of custom type (`AudioDevice`) as the options and, when the user selects an option, it should be picked up. But, only an attribute(`AudioDevice.name`) of this custom type should be visible for selection.

Tried implementing it through a custom presenter row in vain. Unable to do it via PushRow. :(

**Comment by mats-claassen** [comment]
You can use `row.displayValueFor` which is a block that takes the value and returns the String which will be displayed

**Comment by mtnbarreto** [comment]
For more complex Selector rows customization use `selectableRowCellUpdate` as discussed in #299 .

**Comment by mtnbarreto** [comment]
@mohan-shyam Have you solved your issue?

**Comment by mohan-shyam** [comment]
Not yet, @mtnbarreto .. Will close it myself once I'm able to sort this out. Please bear with me (very slow learner :-/ )

**Comment by mohan-shyam** [comment]
Okay, I've finally managed to have it display the way I want. But it crashes when I try to select an option..!!!

```
public override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        if let audioDevice = fetchedResultsController?.objectAtIndexPath(indexPath) as? AudioDevice {
            print("audioDevice = \(audioDevice)")
            audioDevice.managedObjectContext?.performBlockAndWait{
                self.row.value = audioDevice
            }
            completionCallback?(self)
        }
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
    }
```

Console output:

```
audioDevice = <TestApp.AudioDevice: 0x15eb8cc0> (entity: AudioDevice; id: 0x15eb7ea0 <x-coredata://9C4AE241-AABF-494F-94C4-A40EF74A47BE/AudioDevice/p2> ; data: {
    addDate = "2016-10-17 04:32:34 +0000";
    name = Headphones;
    rules = "<relationship fault: 0x15eb76e0 'rules'>";
    type = Headphones;
    uid = "Wired Headphones";
})
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
```

A screenshot as well,

<img width="805" alt="screen shot 2016-10-17 at 11 54 49" src="https://cloud.githubusercontent.com/assets/14356135/19427285/a5939072-9460-11e6-9e4d-da35e5a7982b.png">

Not sure why it's ending up as `nil`!?

**Comment by mohan-shyam** [comment]
@mats-claassen , @mtnbarreto , I have managed to get this done. Thanks very much for your support. Kudos, to you both.. 

Refrained from using a custom row, as it was too complicated and resulted in the issues above. Settled on using `displayValueFor` as @mats-claassen suggested. 

Looks like I spent a lot of time figuring out nothing!! :-/
