### ISSUE TITLE
TextRow & TextFloatLabelRow issue 

### ISSUE THREAD

**Issue by chlebta** [xmartlabs/Eureka#718]
Hello,
When I click on `TextRow or TextFloatLabelRow` field I get this error 
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```
Even if I use `$0.value = "a value"` the app still crash when I click en textField row 

- Environment: Eureka 2.0.0 beta 1 ; Xcode 8 ;  and iOS 9 and 10
![screen shot 2016-10-11 at 12 12 16](https://cloud.githubusercontent.com/assets/1204608/19266926/257ee7c8-8fac-11e6-9030-4cc0f5a44edb.png)

**Comment by mtnbarreto** [comment]
Stack trace please...
Which was the dependency manager used to integrate the library?

**Comment by chlebta** [comment]
Cocoapods 
  pod 'Eureka', '~> 2.0.0-beta.1'

**Comment by mtnbarreto** [comment]
it's weird since the example project also contains these rows i couldn't make it crash.

**Comment by mtnbarreto** [comment]
I just created a cocoapods project from scrach and seems to work fine. 

This is my podfile...

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

```
target 'SimpleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleApp
  pod 'Eureka', '~> 2.0.0-beta.1'
end
```

**Comment by mtnbarreto** [comment]
@chlebta  Could you please upload a project having the issue so i can take a look...?

**Comment by chlebta** [comment]
@mtnbarreto Even me, I can't repreduce the issue on sample project, also I can't push my project to public. 

I've delete all pods and re-install but always same issue with textRows.
<img width="1280" alt="screen shot 2016-10-17 at 09 48 52" src="https://cloud.githubusercontent.com/assets/1204608/19429241/eb3337e8-944e-11e6-88a8-308d135747e9.png">

**Comment by chlebta** [comment]
I've reproduced the issue : 
[sample.zip](https://github.com/xmartlabs/Eureka/files/532698/sample.zip)

**Comment by chlebta** [comment]
After debugging I think it's subclassing issue, because if my class `ViewController` inherit directly from `formViewController` then it works fine but if inherit `MasterViewController` then it bugs

**Comment by mtnbarreto** [comment]
When overriding `viewWillAppear` from `MasterViewController` you must call super implementation. 
Seems you forgot to call it.

```swift
//
//  MasterViewController.swift
//  sample
//
//  Created by Ahmed K on 17/10/16.
//  Copyright © 2016 Prium. All rights reserved.
//

import UIKit
import Eureka

class MasterViewController: FormViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        print("didLoad MasterViewController")
        
        self.initForm()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated) // <<< ---ADD THIS LINE
        //
        self.tableView?.tableFooterView = UIView()
        
    }
    
    public func initForm() {
        LabelRow.defaultCellUpdate = { cell, row in cell.textLabel?.font = UIFont(name: "Helvetica", size: 15)! ; cell.height = { 50 }  }
        ButtonRow.defaultCellUpdate = { cell, row in cell.textLabel?.font = UIFont(name: "Helvetica", size: 15)!}
        print("initForm MasterviewController")
    }
}
````
