### ISSUE TITLE
MultipleSelectorRow & "noValueDisplayText" for empty value

### ISSUE THREAD

**Issue by elsurudo** [xmartlabs/Eureka#720]
Right now, this text is only shown if the `value` is nil. IMO, it should also show if the value is empty (`count == 0`). Thoughts?

Or in case this is the way it is for a reason I hadn't thought of, what is the easiest way to implement the functionality I am looking for? Essentially, displaying some "prompt" text when the selection is empty.

**Comment by elsurudo** [comment]
I ended up solving this by placing the following in the `cellUpdate` callback:

```
if row.value == nil || row.value!.count == 0 {
    cell.detailTextLabel!.text = row.noValueDisplayText
}
```

**Comment by mtnbarreto** [comment]
good solution..
