### ISSUE TITLE
ImageRow How to get image data?

### ISSUE THREAD

**Issue by Rosenkreuz** [xmartlabs/Eureka#721]
I wanna upload to Firebase Strage from photo library picture.

```
<<< ImageRow() {
                $0.title = "Image Row 2"
                $0.sourceTypes = .PhotoLibrary
                $0.clearAction = .no
                }
                .cellUpdate { cell, row in
                    cell.accessoryView?.layer.cornerRadius = 17
                    cell.accessoryView?.frame = CGRect(x: 0, y: 0, width: 34, height: 34)
            }
```

**Comment by mats-claassen** [comment]
You want to get the image the user chose? `row.value` should be your answer

**Comment by Rosenkreuz** [comment]
Thx! 
Then i got the error.

> cannot convert value of type '[UIImage]?' to expected argument type 'Data'

```
.onChange() { row in
    let image = row.value
    var data = NSData()
    data = UIImageJPEGRepresentation(image!, 0.8)
    ...
}
```

**Comment by Rosenkreuz** [comment]
make sense?
```
 data = UIImageJPEGRepresentation(image!, 0.8)! as NSData
```

**Comment by mtnbarreto** [comment]
row.value type is `UIImage?` and not NSData

**Comment by bitbibit** [comment]
Any clue on how to do this? Firebase requires an NSString Url version of the image - 
How to convert ImageRow.Value to Url?

**Comment by tsuz** [comment]
> How to convert ImageRow.Value to Url?

Yuo can get it via `ImageRow.imageURL`
