### ISSUE TITLE
PushRow, title going over value text

### ISSUE THREAD

**Issue by marcelogfsouza** [xmartlabs/Eureka#722]
Hi, I am using Xcode 7.3.1 with a device with iOS 9.2.1 and Eureka 1.7.0.
The issue that I am having is that I am using a push row and the information of the title and the value are coming from the backend, but the text is too big for the field so the title is going over the detail text. Maybe there is an constraint issue between those two labels.

Thanks

![img_0046](https://cloud.githubusercontent.com/assets/12305962/19362379/88f9468c-9154-11e6-87bf-d6b5e4e2337e.PNG)

**Comment by mtnbarreto** [comment]
It might be a constraint issue but it should be reported to UIKit apple guys since we are using the default table view cell to display PushRow cell.

As a workaround i recommend you to set up a shorter title by cutting it off or try adding additional constraints to get what you want.

> Almost sure you will run into the same issue even if you don't use Eureka.

**Comment by marcelogfsouza** [comment]
Thanks for the information. I didn't know it was the default table view cell from Apple.
