### ISSUE TITLE
Form inside a View instead ViewController

### ISSUE THREAD

**Issue by christianhr** [xmartlabs/Eureka#723]
I wonder if I can add my form within a UIView instead of a ViewController, I need some graphics on the top, just before of the Form

**Comment by pwicks86** [comment]
Just make a UITableView where you want your form to be and then hook it up to the tableView IBOutlet in FormViewController.

**Comment by mats-claassen** [comment]
Exactly, your tableView does not have to occupy the whole screen.

**Comment by mcka** [comment]
@pwicks86 @christianhr any code sample. how to hook it up? 
I tried something and it builds but crashes. thanks

````
import UIKit
import Eureka

class ViewController: UIViewController {

    @IBOutlet weak var tableFormView: FormViewController!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        tableFormView.form = Section()
            <<< TextRow(){ row in
                row.title = "Text Row"
                row.placeholder = "Enter text here"
            }
            +++ Section()
    }
}

**Comment by eliteproxy7** [comment]
I get an error on this when i try with Swift 3

<img width="594" alt="screen shot 2017-01-27 at 12 53 25 pm" src="https://cloud.githubusercontent.com/assets/5486268/22381309/1a0e3f46-e48f-11e6-83a3-03c6a3ddaf8d.png">

**Comment by pouriaalmassi** [comment]
@mats-claassen How exactly is this done? I've tried following the above recommendation but I've hit a wall. In IB there is no outlet called `tableView` in the Connections inspector. 

![screenshot 2017-01-31 17 25 52](https://cloud.githubusercontent.com/assets/1231767/22454520/7dfe6ea6-e7da-11e6-9721-aaf773014985.png)

The second attempt I made was to override the `tableView` property but again I hit a wall. Two compilation errors: 

`Overriding non-open var outside of its defining module` and `Cannot override with a stored property 'tableView'`.

![screenshot 2017-01-31 17 25 09](https://cloud.githubusercontent.com/assets/1231767/22454549/b6d27006-e7da-11e6-87a2-7d7f9cd5c8c5.png)

The third attempt I made was to programmatically set constraints on `tableView` which does work but is a bit of an inconvenience. 

```
override func viewDidLoad() {
        super.viewDidLoad()

      tableView?.translatesAutoresizingMaskIntoConstraints = false
        view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[tableView][footerButton]|", options: [], metrics: nil, views: ["tableView" : self.tableView!, "footerButton" : footerButton]))
        view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[tableView]|", options: [], metrics: nil, views: ["tableView" : self.tableView!]))
        view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[footerButton]|", options: [], metrics: nil, views: ["footerButton" : footerButton]))

...
```

**Comment by developerdalelaw** [comment]
@pouriaalmassi Did you install Eureka by Carthage? I had that issue as well. It seems to be an bug between Carthage and XCode and I applied the hackaround described in this issue:
#295

**Comment by pouriaalmassi** [comment]
@developerdalelaw I am using Carthage to install Eureka. Will file a bug if there isn't one already. Thanks for the tip!

**Comment by rjjohnpatrickcruz** [comment]
Hi Reopening this one, I'm using cocoa pods and trying to use a uiview instead of the uiviewcontroller, any suggestion on how I can achieve this? I'm using latest pod version, swift 3  Hoping for your kind response. Thanks.

**Comment by nikarc** [comment]
@rjjohnpatrickcruz Here's what worked for me:

I believe you have to use a `UITableView`, not a `UIView`.

1. Add your UITableView to the view in your storyboard. Make sure the table view is styled as `grouped` rather than `plain`
2. Drag from the `tableView` circle in the Outlets panel in the Connections Inspector. This outlet is provided by Eureka's `FormViewController` so there is no need to override it or create a new `@IBOutlet` for the table view
![drag](https://cloud.githubusercontent.com/assets/3580396/25457471/76d2a216-2aa4-11e7-8847-5910a04a07e2.jpg)
3. Continue with your code as normal. The `form` variable now references your `UITableView`:

```Swift
    override func viewDidLoad() {
        super.viewDidLoad()
        
        form +++ Section() { section in
            section <<< TextRow() {// etc...
        }
    }
```

**Comment by stami** [comment]
Thanks, @nikarc !

Old thread but I think this could be a part of documentation... :) Or maybe I should've known it as common iOS knowledge but I hadn't encountered this situation before where the outlet is defined in the inherited parent class.

**Comment by ltrojanowski** [comment]
@stami I agree, this should be part of the documentation.

**Comment by Coners** [comment]
this is the process to add borders:

<img width="505" alt="Screen Shot 2019-04-17 at 11 39 13" src="https://user-images.githubusercontent.com/49714898/56282356-e15a4b80-6106-11e9-91e2-e95c713f7490.png">
<img width="1056" alt="Screen Shot 2019-04-17 at 11 39 39" src="https://user-images.githubusercontent.com/49714898/56282357-e15a4b80-6106-11e9-9051-c1da9888486e.png">
<img width="611" alt="Screen Shot 2019-04-17 at 11 39 59" src="https://user-images.githubusercontent.com/49714898/56282358-e15a4b80-6106-11e9-8b49-b368bfa7c3df.png">
<img width="576" alt="Screen Shot 2019-04-17 at 11 40 27" src="https://user-images.githubusercontent.com/49714898/56282359-e15a4b80-6106-11e9-8ae2-758d69bdda40.png">
<img width="1002" alt="Screen Shot 2019-04-17 at 11 40 46" src="https://user-images.githubusercontent.com/49714898/56282360-e1f2e200-6106-11e9-98ab-91cbc4bcc027.png">

**Comment by Coners** [comment]
I hope this helps someone - I appreciate this isn't exactly what the question was about but I had to put this somewhere it has taken me two days to figure this out.. there is very little online other than people asking asn other people not telling them exactly what to do
