### ISSUE TITLE
Disable cell highlight in Eureka 2.0 ?

### ISSUE THREAD

**Issue by Amefuri** [xmartlabs/Eureka#724]
Previously I do it like this

```
.onCellHighlight { _, _  in }
.onCellUnHighlight { _, _ in }
```
        
but with a replacement of .onCellHighlightChanged . I have no idea to achieve that.
I did try 

`.onCellHighlightChanged({ (_, _) in })`

but It seem to not work like I thought.

**Comment by mats-claassen** [comment]
`onCellHighlightChanged` is called where in earlier versions both the other two callbacks were called. To know if the row is highlighted or not you should use `row.isHighlighted`

**Comment by Amefuri** [comment]
Actually, I didn't want to know when the row is highlighted, instead I want to disable/remove the default blue highlighted.

.onCellHighlight { _, _  in }
.onCellUnHighlight { _, _ in }

does the job since it override the default behaviour I assumed.

**Comment by Amefuri** [comment]
ok I end up with setup cell tintColor with the same color as titleTextColor. not sure if this is the right way to do it but it work for me.

```
.cellSetup { cell, row in
cell.tintColor = cell.titleLabel?.textColor
}
```

**Comment by tianxiewuhua** [comment]
> ok I end up with setup cell tintColor with the same color as titleTextColor. not sure if this is the right way to do it but it work for me.
> 
> ```
> .cellSetup { cell, row in
> cell.tintColor = cell.titleLabel?.textColor
> }
> ```

But if I use attributedText, this way is not working
