### ISSUE TITLE
Modifying PushRow options cell textLabel

### ISSUE THREAD

**Issue by csimmonsbluebook** [xmartlabs/Eureka#726]
Is there a way to change the PushRow option rows to have word wrap instead of cutting off the text by applying ... to the end?

Is there some option where you can modify the numberOfLines for the cells after the PushRow is shown?

You can see an example of this in the 4th row here:
![img_0527](https://cloud.githubusercontent.com/assets/19786779/19391640/8c45e406-91fb-11e6-8988-ef8929245b5e.PNG)

Eureka: 2.0.0-beta.1
Xcode: 8.0
iOS: Deployment Target 9.0

**Comment by mtnbarreto** [comment]
similar to #299

**Comment by mtnbarreto** [comment]
Take a look at these issues https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue%20selectableRowCellUpdate%20

**Comment by csimmonsbluebook** [comment]
@mtnbarreto Sorry for the duplicate. Didn't see those issues. Fixed my problem. Thanks!
