### ISSUE TITLE
disabled/hidden

### ISSUE THREAD

**Issue by sderuiter** [xmartlabs/Eureka#727]
Hi, using Eureka Branch 2.3 on Xcode 8.

I think I have a pretty common pattern, but unsure if I'm tackling in the right way. 
I have a listview table view controller, showing items. The controller has an ADD button. Clicking the button segues to an Eureka FormViewController. Clicking on a row in the list view table view controller also segues to the same Eureka FormViewController. Based on whether it's a new item, or viewing an existing item, I either pre-populate data into the form, or show an empty form. 

Now, the FormViewController is embedded in an navigationController, and my right navigation button is either Save (if a new item), or Edit (if an existing item). 
In FormViewController.viewDidLoad, I'm setting up the form, and disable all controls if its is an existing item.

(Form snippet)
```
<<< DecimalRow("amount"){
$0.title = "Amount"
$0.disabled = Condition(booleanLiteral: disabledForm)
$0.evaluateDisabled()

$0.placeholder = "EUR..."
if  existingBillID != nil {
    $0.value = Bills(existingBillID).amount
} else {
   }
```

The Edit navigation Button calls the function EditBill.
```
func editBill() {
      disabledForm = false
        if  disabledForm {
            self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Edit, target: self, action: #selector(BillViewController.editBill))
        } else {
            self.navigationItem.rightBarButtonItem = saveButton
        }
        self.tableView!.reloadData
}
```

Now my goal here is, when tapping the Edit button, the form will reload and all rows will be enabled again. However, nothing happens, rows will remain disabled. What am I doing wrong here?

**Comment by mtnbarreto** [comment]
You must get the row and set `disabled` property again, this time using `false`. 

There is no any binding between the variable and the condition you should update `disabled` value, invoke `evaluateDisabled()` and then reload the row, section or the entire form.

**Comment by mtnbarreto** [comment]
related issues: #48 , #177, #307. Take a look at the example project and read all related issues to get more info. https://github.com/xmartlabs/Eureka/issues?q=label%3A%22Hiding+%26+Disabling+Rows%22+is%3Aclosed
