### ISSUE TITLE
Invalid TextRow rule behavior

### ISSUE THREAD

**Issue by rdadkins** [xmartlabs/Eureka#729]
There is currently an issue with `validate()` on TextRows. Suppose that you have two Rules for a TextRow; one is `RuleRequired` and the other is `RuleMaxLength` on a `TextRow`. The problem arises when you decide to validate a row that has 0 characters in it. The errors returned include `RuleRequired` which would be expected with a TextRow of 0 length. However, `RuleMaxLength` is also returned as an error although 0 is not greater than the max length set for any length. This can be achieved by the following:

```
let row = TextRow()
row.add(rule: RuleRequired())
row.add(rule: RuleMaxLength(maxLength: 50))
// add to section and add section to form
...
print(self.form.validate())
```

The values printed will include both errors stating that a field is required and that the max characters rule has been violated (although there are 0 characters).

Shouldn't the RuleMaxLength be thrown only if there are more characters supplied in the row?

**Comment by rdadkins** [comment]
This appears to be `RuleMaxLength` guard check in `isValid`. If there is an empty String passed to isValid, it treats it as nil and thus returns the error. I have a temporary fix that looks like the following:

```
func isValid(value: String?) -> ValidationError? {
  if let value = value {
    return value.characters.count <= max ? validationError : nil // assuming max is an Int and not UInt
  }
  return nil
}
```

or with guard:

```
func isValid(value: String?) -> ValidationError? {
  guard let value = value else { return nil }
  return value.characters.count <= max ? validationError : nil // assuming max is an Int and not UInt
}
```

**Comment by mtnbarreto** [comment]
Could you please make a pull request with the fix?
