### ISSUE TITLE
`defaultCellSetup` not called when row has `disabled` property

### ISSUE THREAD

**Issue by ldiqual** [xmartlabs/Eureka#732]
I'm encountering an issue where assigning to `disabled` prevents the `defaultCellSetup` of that cell type to be called:

![image](https://cloud.githubusercontent.com/assets/941453/19415349/e61ac442-9322-11e6-8b0d-b55c1a115346.png)

Notice how the `Middle Name` cell is not styled properly. Removing the assignment to `disabled` fixes the issue.

### Code

```
NameRow.defaultCellSetup = { cell, row in
    // customization
}

let mainSection = Section()

let middleNameRow = NameRow(tag: nil)
middleNameRow.title = "Middle name"
middleNameRow.disabled = Condition.function(["noMiddleName"]) { form -> Bool in
    return (form.rowBy(tag: "noMiddleName") as? SwitchRow)?.value ?? false
}
mainSection.append(middleNameRow)

let noMiddleNameRow = SwitchRow(tag: "noMiddleName")
noMiddleNameRow.title = "I don't have a middle name"
mainSection.append(noMiddleNameRow)

form.append(mainSection)
```

### Environment

 - Cocoapods 1.1.0-rc3
 - Eureka 2.0.0-beta.1
 - iOS 10.0.1
 - Xcode 8

**Comment by mats-claassen** [comment]
@ldiqual The issue must lay somewhere else as I copied your code and it is styled correctly. Also setting the disabled property does not affect if `defaultCellSetup` is called or not.

**Comment by ldiqual** [comment]
@mats-claassen Found the issue with my code, I was setting  `NameRow.defaultCellSetup` *after* creating the form, which works for all rows but the ones that have a `disabled` attribute. My guess is that as soon as `disabled` is assigned, the corresponding row is set up, instead of waiting for a layout cycle of some sort.

In short, to fix this: assign `defaultCellSetup` first, then create the sections/rows.

Closing this, sorry for the trouble.
