### ISSUE TITLE
How to get Section offset in form and scroll to it?

### ISSUE THREAD

**Issue by Laptopmini** [xmartlabs/Eureka#736]
Eureka: 1.7 (Swift 2 Branch)
XCode: 7.3.1 (Swift 2.2)
iOS Target: 9.0

**I would like to open one of my form and scroll down to a particular section automaticly.**

My idea was to set the title of the desired section in one of the class's variable before presenting it:
`var sendToSection: String?`

Then in my view controller:
```
    override func viewWillLayoutSubviews() {
        if let name = sendToSection, section = form.sectionByTag(name) {
            sendToSection = nil
            // offset scrollview to section offset
        }
    }
```

However, I quickly realized that `Section` does not offer a `frame` variable. Nor do I know how to access the `UIScrollView` set up by the form.

How can I get the `Y location` of a Section and modify the form's `UIScrollView`'s `contentOffset`?

**Comment by mtnbarreto** [comment]
`FormViewController` has a `tableView` outlet that is the `UIScrollView` you are talking about. 

You will have to get the section index and then scroll to its correspond table view section or section first row. 

Something like this....

```swift
        let section = form.sectionBy(tag: "yourTag") // or form[4]
        let sectionIndex = section?.index
        var rect = tableView?.rect(forSection: sectionIndex!)
        // optional, change the rect height if it is taller than table view height
        rect?.size.height = tableView!.frame.size.height
        //
        tableView?.scrollRectToVisible(rect!, animated: true)
```

**Comment by mtnbarreto** [comment]
Here is how we can scroll to a particular row, it may be helpful too: 
 https://github.com/xmartlabs/Eureka/blob/master/Source/Core/Core.swift#L843

**Comment by Laptopmini** [comment]
Thanks for help @mtnbarreto. Much appreciated.
