### ISSUE TITLE
Validation Message

### ISSUE THREAD

**Issue by AyusSalleh** [xmartlabs/Eureka#738]
I got 2 question 

1. How can i create error message for required field. Example : row.title = state. so the error message will be "State is required". The error message for required field is change respectively follow its field title.

2. How can i change error message for certain field after click some action. Example: click submit, there error is wrong password. So the error message below the field is "Wrong Password"

Thank you

**Comment by Laptopmini** [comment]
Your question is too broad. What do you mean create an error message?

Print it out?
Present a UIAlert?
Present it in a custom view?

**Comment by mtnbarreto** [comment]
Are you asking for this: #733?

**Comment by mtnbarreto** [comment]
validationMessage has nothing to do with how we show the errors. The validation error display should be done by the developer based on Eureka notifications to onRowValidationChanged callback as Example project shows. 

#733 was merged into master so now we can pass the validation message as last rule init parameter.


The only way to update a rule message is by assigning a id to the rule and then remove it using its id and add another rule setting up the new validations message to it. 
Anyway this is not that common, at least i think so..
