### ISSUE TITLE
Use carthage installation error

### ISSUE THREAD

**Issue by huangboju** [xmartlabs/Eureka#742]
<img width="440" alt="2016-10-19 4 15 53" src="https://cloud.githubusercontent.com/assets/14818224/19510810/57944110-9617-11e6-9a5f-79739fbe9d82.png">

<img width="695" alt="2016-10-19 4 16 27" src="https://cloud.githubusercontent.com/assets/14818224/19510831/6aae9638-9617-11e6-828f-0c25175b8196.png">

**Comment by mats-claassen** [comment]
Seems to work with `github "xmartlabs/Eureka" ~> 2.0.0`. 
It is as if Carthage does not support hyphens in the version string

**Comment by sivakspt** [comment]
github "xmartlabs/Eureka" ~> 2.0.0.1 

Use the above and it will work.
