### ISSUE TITLE
combo `Validator` is very well.

### ISSUE THREAD

**Issue by roshanman** [xmartlabs/Eureka#743]
[Validator]https://github.com/adamwaite/Validator
Validator is a user input validation library written in Swift.

**Comment by mtnbarreto** [comment]
@roshanman The issue propose is unclear for me.  Do you want to consider this library as validation library? 

We have implemented a build-in [validations feature](https://github.com/xmartlabs/Eureka#validations). We can eventually add more validations similar to these that https://github.com/adamwaite/Validator has.
