### ISSUE TITLE
Section doesn't conform to 2 protocols

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#744]
I updated my code to Swift 3 and 2 errors appear:

> Section.swift:206:1: Type 'Section' does not conform to protocol 'MutableIndexable'
> Section.swift:206:1: Type 'Section' does not conform to protocol 'IndexableBase'

How do I fix them? I tried cleaning and rebuilding but the errors stay there.

**Comment by mtnbarreto** [comment]
Seems you are still using eureka 1.x version. Please make sure you integrated the right version. 

If yo need additional help i would like to see Swift version, cocoapods/carthage version and how you integrated Eureka in your project.

**Comment by Sweeper777** [comment]
I am just doing

    pod 'Eureka'

In my pod file, is that wrong?

**Comment by Sweeper777** [comment]
Cocoapod version is 1.1.0.beta.1 and as I said I am using swift 3

**Comment by mtnbarreto** [comment]
Eureka 2.0.0 is still in beta so to install it you should follow [readme instructions](https://github.com/xmartlabs/Eureka#installation).
