### ISSUE TITLE
Errors with customs rows after upgrading to Swift 3

### ISSUE THREAD

**Issue by CrislerAnytimes** [xmartlabs/Eureka#745]
Hi, I did some custom rows in Eureka and it was working fine in xcode 7 and the old version of Eureka.  I Upgraded Eureka and xcode to the latest version and I got these error after upgrading and I don't know how to fix it or what I'm doing wrong since it was working before.

Type 'ProfileHeaderRow' does not conform to `Taggable`
Type `ProfileHeaderRow` does not conform to `BaseRowType`
Type 'ProfileHeaderRow' does not conform to 'Typed Row Type'
Generic Type 'Row' specialized with too many type parameters ( got 2, but expected 1)

this is how my class look like roughly

```swift
final class ProfileHeaderRow: Row<ProfileModel, ProfileHeaderCell>, RowType {
    required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<ProfileHeaderCell>(nibName: "ProfileHeaderCell")
    }
}

final class ProfileHeaderCell: Cell<ProfileModel>, CellType {
  ....  
}
```

Any ideas on where I got it wrong?

**Comment by mtnbarreto** [comment]
@CrislerAnytimes you are right, we have done some changes on how to specify custom rows...

This migration guide should be helpful to performs necessary changes. https://github.com/xmartlabs/Eureka/blob/master/Documentation/Eureka%202.0%20Migration%20%20Guide.md
