### ISSUE TITLE
Validation customized message

### ISSUE THREAD

**Issue by skrosoft** [xmartlabs/Eureka#746]
Hello,

I'm looking to use Spanish message in validation.

With some Rules I am able to customize the message:

>         var min6char = RuleMinLength(minLength: 6);
>         min6char.validationError = ValidationError(msg: "Debe contener al menos 6 caracteres.")

But with RuleRequired() it is imposible

![image](https://cloud.githubusercontent.com/assets/4645565/19578449/1085e770-96f2-11e6-8c41-b302e51065a3.png)

Could someone help me?

**Comment by mtnbarreto** [comment]
RuleRequired is a generic struct I think, so the right way to initialize it is...

```swift
let r = RuleRequired<String>()
r. validationError = (msg: "spanish text")
```

Normally when you add the required rule to a row you use `add(rule:)` method and the generic type is automatically inferred so you don't need to specify it. 

Take into account that the msg can be set up passing it as last init parameter (only available in master branch code).

**Comment by skrosoft** [comment]
It works! thank you. In my version, the init() function didnt had a "msg" parameter.
I had to remove the pod from the Podfile, launch install and add it back;

Vincent
