### ISSUE TITLE
A new rule - Row equals to Row

### ISSUE THREAD

**Issue by skrosoft** [xmartlabs/Eureka#747]
Hello,

It could be usefull a validator that allow us to compare 2 row values, example with the field Password and PasswordConfirm, both field must have the same value to make data valid.

`$0.add(rule: RuleEqualsToRow(msg:"Password doesnt match.", tag:"password"))`

Vincent

**Comment by mtnbarreto** [comment]
@skrosoft  Makes total sense, Could you implement it and make a pull request?

**Comment by skrosoft** [comment]
#750 here it is the pull request. @mtnbarreto please let me know if it seems good for you.
