### ISSUE TITLE
imageView for SegmentedRow has no width value

### ISSUE THREAD

**Issue by michaelbina** [xmartlabs/Eureka#75]
When I set the imageView image for a NameRow, it shows up as expected like so:

<img width="371" alt="screen shot 2015-11-05 at 1 12 35 pm" src="https://cloud.githubusercontent.com/assets/528845/10981884/206b80a6-83bf-11e5-9b60-d6882eda3171.png">

```
            <<< NameRow(GENDER_TAG) {
                $0.title = "Gender"
                if self.isEditMode() {
                    $0.value = self.animalObject?.objectForKey(self.GENDER_TAG) as? String
                }
                }.cellSetup { cell, row in
                    cell.imageView?.image = UIImage(named: "form_gender")
            }
```

When I change it to a SegmentedRow, it looks like this:

<img width="370" alt="screen shot 2015-11-05 at 1 18 05 pm" src="https://cloud.githubusercontent.com/assets/528845/10982002/bd58c658-83bf-11e5-8412-d3c5c5712bae.png">

```
            <<< SegmentedRow<String>(GENDER_TAG) {
                $0.title = "Gender"
                $0.options = ["Male", "Female"]
                if self.isEditMode() {
                    $0.value = self.animalObject?.objectForKey(self.GENDER_TAG) as? String
                }
                }.cellSetup { cell, row in
                    cell.imageView?.image = UIImage(named: "form_gender")
            }
```

Any advice on how to fix it would be greatly appreciated.

**Comment by mtnbarreto** [comment]
At the moment `SegmentedCell` doesn't take into account the imageView to set up its constraints :(. 
We should do something like `_FieldCell` `updateConstraints()` method to update the constrains depending on whether the imageView is used or not.   https://github.com/xmartlabs/Eureka/blob/master/Source/Cells.swift#L874 may help. 

Note in this code that we added KVO to the  imageView `image` property to be notified when it changes and update the constraints accordingly.

I really appreciate if you have time to fix the issue and make a pull request.

**Comment by michaelbina** [comment]
I will take a stab at this when i get a chance.  Thanks for the pointers

**Comment by estebansotoara** [comment]
Hi @mtnbarreto 
I saw this issue open and wanted to give a hand, I added some lines to check the ```imageView``` in ```updateConstraints()``` and included the cases in the example

I have a fork with the changes (https://github.com/estebansotoara/Eureka/tree/imageViewForSegmentedRow), you can check it out and if you like it I can make a PR

**Comment by dernster** [comment]
@estebansotoara that fork seems to be good! We would also need to update the constraints automatically when the imageView.image property changes (as it is done with the textLabel). To accomplish that, add an observer to the imageView for the key "image" and update the "observeValueForKeyPath" overridden function accordingly (similar as in _FieldCell).

What do you think?

**Comment by estebansotoara** [comment]
@dernster sure, I'll take a look a this on the next days and let you know

**Comment by estebansotoara** [comment]
@dernster the change is up

**Comment by dernster** [comment]
@estebansotoara the changes are ok now! Just rebase your branch to be fast-forward from the Eureka master and then make a pull request!

**Comment by estebansotoara** [comment]
@dernster just to be sure I understand correctly and don't screw up anything, I have to rebase the topic branch into my fork master (have to update master as there is some new commits) and then make the pull request from master

**Comment by michaelbina** [comment]
* nudge* sounds like there's a fix out there.  Would love to see this get merged soon...

**Comment by mtnbarreto** [comment]
@dernster we suggest the rebase to have a cleaner git history. Take a look at this reference https://www.atlassian.com/git/tutorials/merging-vs-rebasing that explains the benefits of git rebase over git merge. 

Considering a particular state of eureka master branch i would expect only one commit per feature.  
One way to do that is rebasing interactively your branch with master(update your local master with xmartlabs remote first).

**Comment by estebansotoara** [comment]
@mtnbarreto I just made the PR #115 thanks for the help

**Comment by mtnbarreto** [comment]
Cool! Thanks @estebansotoara !

**Comment by estebansotoara** [comment]
No problem, I'm glad I could help
