### ISSUE TITLE
Rows Not scrolling above keyboard when becomes first responder.

### ISSUE THREAD

**Issue by dhiraj-tagrem** [xmartlabs/Eureka#751]
Xcode 7.3.1
Deployment Target: iOS 8
Eureka Pod Version: 1.6.0
Swift Version 2.3

I am using Eureka in one of my app but the problem being is that when any text row becomes first responder, its not scrolling above keyboard and still lay below keyboard which makes that field and non visible and thats why difficult to make input. Also when tableview is scrolled up to pull that row in visible are, keyboard gets dismissed. Can you help whats been wrong.

**Comment by mtnbarreto** [comment]
Probably you forget to call `viewWillAppear`, `viewDidLoad` super implementation when overriding it. 
I really appreciate if you report these issues attaching the relevant code.
