### ISSUE TITLE
Pod 1.7 / Swift 2.3

### ISSUE THREAD

**Issue by yesez5** [xmartlabs/Eureka#753]
Hi, I just updated Eureka through Pods to the version 1.7 for getting compatibility with Swift 2.3. But currently, Pods downloads the version 1.6 which is not compatible with Swift 2.3. So I had to specify my pod in this way:

`pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'swift2.3'`

Is this a bug or I am doing something wrong?
Thanks guys for your amazing work.

**Comment by mats-claassen** [comment]
There is no Swift 2.3 release. The only way of using it is as you mentioned with branch `swift2.3`.
