### ISSUE TITLE
FormViewController.keyboardWillShow() not scrolling to offscreen row

### ISSUE THREAD

**Issue by davros1970** [xmartlabs/Eureka#755]
In method, FormViewController.keyboardWillShow(), my TextRow is not being scrolled to when the TextRow becomes the first responder.

This block of code is not executed, indexPath() returns nil. cell is not nil. It has a reference to the proper responder TextCell.

`
            if let selectedRow = table.indexPath(for: cell) {
                table.scrollToRow(at: selectedRow, at: .none, animated: false)
            }
`

My cell is scrolled off the bottom of the screen. I believe the proper correction would be

`
if let selectedRow = table.indexPathForRow(at: cell.center) {
    table.scrollToRow(at: selectedRow, at: .none, animated: false)
}
`

I was trying to make my TextRow be the first responder in the initializer. Everything seems to work properly for TextRows that are on-screen when the form first appears.

`
<<< TextRow() { row in // initializer
    row.title = myTag
    row.tag = row.title
    row.cell.textField.becomeFirstResponder()
}
`

The hack workaround I found was to make my cell become first responder again in the viewDidAppear(). viewWillAppear() did not work.

`
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    guard let myRow = form.rowBy(tag: myTag) as? TextRow else {
        return
    }
    myRow.cell.textField.becomeFirstResponder()      
}
`

- Environment: 2.0.0-beta.1, Xcode: Version 8.0 (8A218a), iOS 10

**Comment by davros1970** [comment]
I tried to override FormViewController.keyboardWillShow() and use my suggested fix "table.indexPathForRow(at: cell.center)" but that did not fix my issue.

**Comment by mtnbarreto** [comment]
For offscreen rows you should use UIKit methods like this...

```swift
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tableView?.scrollToRow(at: <rowIndexPath>, at: .none, animated: false)
    }
```

> It does not make sense to make the first responder something that is not actually in the tree view.

**Comment by davros1970** [comment]
Sorry, but your answer did not work for me. Only in viewDidAppear will such a solution work.

**Comment by mtnbarreto** [comment]
you are right,  I should have written `viewDidAppear`. :)

**Comment by davros1970** [comment]
OK. Is that an iOS API limitation or a Eureka limitation? I guess my simplistic question is 'How do I tell Eureka which row is the first responder when setting up my form?' Is what I'm doing the expected way of doing this? I need the keyboard open to a specific TextRow when the ViewController comes to life.

**Comment by mtnbarreto** [comment]
I would not say that is a Eureka limitation...

The expected way to do so is by using UIKit helpers as you are doing now. 

If you need the first responder on a specific field, first make the row visible (without animation) then assign the first responder. 

Eureka does a lot of stuff and seems to me that exposing these kind of helpers makes the things harder to understand and also to maintain the project.
Typically when using the Eureka API we don't care about view controller life cycle and when the cells are visible or not, Eureka just provides a way to specify data entry fields in a high level abstraction and also handle itself to update the UI whenever these data structure changes.

**Comment by davros1970** [comment]
Ok. Thx for the quick feedback! Much appreciated!
