### ISSUE TITLE
Retrieving ValidationErrors when row is not valid.

### ISSUE THREAD

**Issue by mliudev** [xmartlabs/Eureka#756]
Hi,

I'm currently using Eureka 2.0.0-beta.1 with Swift 3 and XCode 8. I'm researching using the new validations feature to replace what we have implemented with the Validator library. One of the required functionality to implement the switch is the ability to retrieve the error messages associated with invalid rows.

According to the Eureka docs I can check whether is a row is valid or invalid but I don't see a way to access the error messages associated with broken rules. Is there currently a way to do this?

Mike

**Comment by mtnbarreto** [comment]
@mliudev  I've updated the readme with the information you are looking for.
