### ISSUE TITLE
I am trying to add an ImageRow  using Eureka, why do I keep  getting use of  unresolved identifier ImageRow Error, what am I not doing correctly?

### ISSUE THREAD

**Issue by benji4720148** [xmartlabs/Eureka#759]
![screen shot 2016-10-24 at 9 30 30 pm](https://cloud.githubusercontent.com/assets/10980373/19669919/2ccc2c0e-9a31-11e6-8b32-28b5c7fa8abd.png)

**Comment by mats-claassen** [comment]
`ImageRow` has been removed from Eureka in the latest version. This is because it requires specific entries in the Info.plist of your project.
You can add it from [EurekaCommunity/ImageRow](https://github.com/EurekaCommunity/ImageRow) as a separate Pod. (`pod 'ImageRow', '~> 1.0' `)

**Comment by chefren** [comment]
@mats-claassen is it possible to add it as a Pod? I tried, but it conflicts with the Eureka pod version 3.0.0 as it requires `~> 2.0.0-beta.1`
