### ISSUE TITLE
Unable to hide row whose value is changed

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#76]
I am looking to hide a specific row (say row1) once its value is changed to a non-nil and simultaneously un-hide another row (say row2). 

When I changed the value of row1, I set
.onChange({ (row) -> () in
          row.hidden = true
        })

However, the row1 doesn't get hidden.

Looking for suggestions on how to get this to work.

Thanks in advance.

**Comment by jkennington** [comment]
Call `.evaluateHidden()`. The `true` is turned into a condition but not evaluated when you set it. You can force it to evaluate with that function, though.

**Comment by mtnbarreto** [comment]
@jkennington  :+1:
