### ISSUE TITLE
two button row in one row

### ISSUE THREAD

**Issue by rayastar** [xmartlabs/Eureka#760]
how insert two button row in one row?
is it custom row?

**Comment by mtnbarreto** [comment]
You will have to create a custom row. 

I would recommend you to take a look at [custom rows](https://github.com/xmartlabs/Eureka#custom-rows) documentation and issues tagged with `custom row` [label](https://github.com/xmartlabs/Eureka/issues?q=label%3A%22custom+row%22+is%3Aclosed). 

These blog posts may also help:
https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/
https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/
