### ISSUE TITLE
PushRow multiline title

### ISSUE THREAD

**Issue by akabab** [xmartlabs/Eureka#762]
Trying to get the PushRow main row to be multiline based on title value intrinsic size (dynamic height)

with this piece of code..
```
<<< PushRow<String>("tag") {
  $0.title = "7 : complètement épuisé, incapable de travailler efficacement"
  $0.selectorTitle = "Fatigue Level"
  // $0.cell.textLabel?.numberOfLines = 0
  $0.cell.detailTextLabel?.numberOfLines = 0
}
```
..I'm getting this kind of result
<img width="428" alt="screen shot 2016-10-26 at 21 56 02" src="https://cloud.githubusercontent.com/assets/6205705/19742816/052a5cc4-9bc7-11e6-807d-e7d4844724f3.png">

not what I expected ;)

any idea?

**Comment by mtnbarreto** [comment]
We are just using UIKit default `UITableViewCell`. Seems that its contraints set up does not support multilines in textLabel nor detailTextLabel.

I would recommend to set up cell.height = { fixedHeight } for these cases.

**Comment by akabab** [comment]
ain't a solution but thanks anyway :)

**Comment by tiritea** [comment]
> We are just using UIKit default UITableViewCell. _Seems that its contraints set up does not support multilines in textLabel nor detailTextLabel._

Yup. Maybe have a look at this as a possible fix, if you want to go to the trouble of working around Apple's bug that is..: https://stackoverflow.com/questions/36587126/autolayout-ignores-multi-line-detailtextlabel-when-calculating-uitableviewcell-h
