### ISSUE TITLE
Create multiple field in same row.

### ISSUE THREAD

**Issue by AyusSalleh** [xmartlabs/Eureka#767]
Anyone know is there possible to create multiple textfield in same row using eureka?
<img width="396" alt="screen shot 2016-10-31 at 9 42 35 am" src="https://cloud.githubusercontent.com/assets/20343677/19841970/6ba32ece-9f4e-11e6-9528-8925969b9439.png">

**Comment by mats-claassen** [comment]
You can create this. Have a look at our blog posts about how to create custom rows ([Part1](https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/) and [Part2](https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/)) if you need help getting started.
There is also a similar row in [EurekaCommunity](https://github.com/EurekaCommunity/CreditCardRow)
