### ISSUE TITLE
How to format model for displaying in picker view controller for MultipleSelectorRow

### ISSUE THREAD

**Issue by dev4dev** [xmartlabs/Eureka#770]
I'm using MultipleSelectorRow as follow

```swift
<<< MultipleSelectorRow<Language>("languages") { row in
				row.title = "Language"
				row.options = Language.all()
				row.selectorTitle = "Language"
				row.displayValueFor = { (rowValue: Set<Language>?) in
					return rowValue?.map({ $0.title }).sorted().joined(separator: ", ")
				}
			}
```

```
struct Language: Equatable {
	let code: String
	let title: String
}
```

In form everything is ok
<img width="374" alt="screenshot 2016-11-02 09 20 57" src="https://cloud.githubusercontent.com/assets/722407/19919796/b875ceec-a0dd-11e6-8548-079e6984154f.png">

But in picker controller there is a mess
<img width="374" alt="screenshot 2016-11-02 09 21 47" src="https://cloud.githubusercontent.com/assets/722407/19919817/cdac8bfc-a0dd-11e6-9c63-9516e3cf7ae1.png">

Could I format it somehow?

**Comment by dev4dev** [comment]
https://github.com/dev4dev/Eureka/commit/be50fcb21d3536d55734666d20633703659f1ea7

**Comment by mats-claassen** [comment]
Yeah, just make `Language` conform to `CustomStringConvertible`

**Comment by dev4dev** [comment]
@mats-claassen That's not a solution, then it will return `title` in `form.values()` but I need whole object to get `code` value from it

**Comment by dev4dev** [comment]
@mats-claassen omg, my another epic fail...I tried to do that, and I saw only titles in console, I thought it returns only titles but not objects...now I just realized that it used `description` to represent those objects in console... :facepalm:
