### ISSUE TITLE
How to launch an action on pressing Done?

### ISSUE THREAD

**Issue by joaomarceloods** [xmartlabs/Eureka#779]
I need to call a function when the user finishes filling the form and presses Ok (on the keyboard toolbar) on the last field. I need help figuring out how to do this.

The last row is a DateRow, I tried setting the `target` and `action` of the toolbar and it works sometimes, others it doesn't -- first time yes, but if I go back to another row and back to the last, no.
```swift
    let birthdayRow = DateRow()

    override func viewDidLoad() {
        super.viewDidLoad()     
   
        form +++ Section() <<< birthdayRow

        let toolbar = (birthdayRow.cell.datePicker.inputAccessoryView as! UIToolbar)
        let okButton = toolbar.items!.last!
        okButton.target = self
        okButton.action = #selector(save)
    }
    
    func doSomething() {
        //...
    }
```
- Eureka 2.0.0-beta.1 (CocoaPods)
- Swift 3.0.1
- Xcode 8.1 (8B62)
- iOS 10.1.1 (14B100)
- iPad (device)

**Comment by edasque** [comment]
Would love to know that too

**Comment by AkdM** [comment]
I've just figured out this myself. You will need to use the `onCellHighlightChanged` callback with `row.isHightlighted` property.

Example:
``` swift
<<< TextRow() {
$0.title = "Something"
}.onCellHighlightChanged { cell, row in
  if !row.isHighlighted {
    // Do things here
  }
}
```

Hope I've helped!

**Comment by NorakGithub** [comment]
Seem like the `row.isHighLighted` is always return `true` when the textfield is not focus anymore. Are there any way to get the action when user tapped on return button?

**Comment by mats-claassen** [comment]
This is now possible by overriding `func inputAccessoryView(for row: BaseRow) -> UIView?` like this:

```swift
override func inputAccessoryView(for row: BaseRow) -> UIView? {
    let iaView = super.inputAccessoryView(for: row)
    guard let iaNavigationView = iaView as? NavigationAccessoryView else {
        return iaView
    }
    iaNavigationView.doneButton.action = #selector(NavigationAccessoryController.tapped)
    return iaNavigationView
}
```
