### ISSUE TITLE
How can I use Eureka forms in a view controller that is not a subclass of `FormViewController`

### ISSUE THREAD

**Issue by abbasmousavi** [xmartlabs/Eureka#78]
How can I use Eureka forms in a view controller that is not a subclass of `FormViewController`

**Comment by mtnbarreto** [comment]
You must extend from `FormViewController`. `FormViewController ` is nothing else than a extension of `UIViewController` that adds some behaviour to display the form properly so this should not be a problem. 

Regards

**Comment by abbasmousavi** [comment]
@mtnbarreto Is it possible to implement FormViewController as a protocol with default behavior that extend UIViewController so that view controllers that are not subclasses of FormViewController can conform to it?

Consider this use case. I want all view controllers in my app have some base behavior and only some of this controllers will contain forms. If FormViewController was a protocol it was possible to use subclasses of a base view controller for all controllers and controllers with forms in them conform to the protocol.

The other possible approach is the approach used by FXForms, see https://github.com/nicklockwood/FXForms#displaying-a-form-advanced
(You can inherit from FXFormViewController or use a plain UIViewController and assign it a form controller and a tableview)

**Comment by justinmakaila** [comment]
@abbasmousavi Couldn't you achieve the same thing by building your common behavior into a protocol, and creating a `SpecializedFormViewController` and a `SpecializedViewController`?

You could even avoid duplications with protocol extensions
