### ISSUE TITLE
Maybe someone can help - deleting a row?

### ISSUE THREAD

**Issue by werneroi** [xmartlabs/Eureka#780]
Hi, I hope it is ok to post here, as i didnt find an answer anywhere else
Is there a way to delete a row from a form?

any help will be appreciated!
Thank you world.

**Comment by mats-claassen** [comment]
A `Section` is just a collection of rows, you can see it as an array. So you have functions like `remove(at: Index)`, `removeLast()` and `removeFirst()`.

To get the section for a specific row you can use `form.rowByTag("yourTag")?.section`.

**Comment by renatoamazillo** [comment]
Just for future readers, `form.rowByTag("yourTag")` have been replaced by `form.rowBy(tag: "yourTag")`, so to access the section of a specific row you can use:
`form.rowBy(tag: "yourTag")?.section`

**Comment by renatosc** [comment]
For future readers: `form.rowByTag("yourTag")` have been replaced with `form.rowBy(tag: "yourTag")`, so to access a section of a specific row you can use:

`form.rowBy(tag: "yourTag")?.section`
