### ISSUE TITLE
Q: ButtonRow configuration

### ISSUE THREAD

**Issue by szuniverse** [xmartlabs/Eureka#781]
Hi

How to configure a ButtonRow cell to open a safari link?
And the alignment should be left.

thanks

**Comment by cesaredecal** [comment]
In case anyone was wondering:

            <<< ButtonRow() { row in
                row.title = "Share"
                row.cell.imageView?.image = #imageLiteral(resourceName: "shareSquare")
                row.cell.accessoryView = UIImageView(image: #imageLiteral(resourceName: "arrow"))

                row.cell.height = { return self.cellHeight }
                }.cellUpdate({ (cell, _) in
                    cell.textLabel?.textAlignment = .left
                }).onCellSelection({ (cell, row) in
                    self.openSafari() // add code to open safari here or create a new function
                })
