### ISSUE TITLE
Setting a separator inset affects layoutMargin 

### ISSUE THREAD

**Issue by AndrewSB** [xmartlabs/Eureka#782]
I noticed this when trying to align the separator inset of a cell that already had an indentation level.

Basically, If I set a `separatorInset` on the cell, it does indeed move the cell's inset to the specified value, but it also modifies the cell's `layoutMargins`. 

For example, if I set the "All" row's cell's seperatorInset to 44, this is what happens
<img width="521" alt="screen shot 2016-11-09 at 3 28 15 pm" src="https://cloud.githubusercontent.com/assets/3814772/20160626/3ef26632-a69d-11e6-90dc-018a3d9fcbe7.png">

The expected behavior would be to have the line insetted to the right, but to have the text staying aligned with the row above and below "All"

Is there somewhere in Eureka where the cell's `seperatorInset` affects the `layoutMargins`?

**Comment by mats-claassen** [comment]
No. I think this is a behaviour of UIKit. Did you try doing the same in a normal UITableView?

**Comment by AndrewSB** [comment]
I don't think it is, the reason I was surprised that `Eureka` did it this way was because I'm using `separatorInset` (through a storyboard) on a UITableView and it didn't change the `layoutMargins`

I can post a sample project if you're having trouble reproing UIKit's behavior!

**Comment by santiagofm** [comment]
Hey!
This is the default behavior when using the *default* `UITableViewCell`s `textLabel` and changing the cells `separatorInset`.
Cheers
