### ISSUE TITLE
Can't create row with tag

### ISSUE THREAD

**Issue by andertsk** [xmartlabs/Eureka#784]
When i trying to create the for example LabelRow or SwitchRow with tag i get the following error:

> 16:31: Extra argument 'tag' in call
![2016-11-10 14 28 25](https://cloud.githubusercontent.com/assets/705208/20168001/e1db7ed8-a751-11e6-8438-ec0b6e3fab14.png)

Eureka version: 2.0.0-beta.1
Xcode version: 8, iOS 9

**Comment by plastus** [comment]
You don't need the "tag:" declaration. Either initialize the row like as:

    <<< LabelRow("some_tag")

or override it's tag by:

    $0.tag = "your_tag"

**Comment by igordeoliveirasa** [comment]
I created this class: 
`final class PersonInfoMasterRow: Row<PersonInfoMasterCell>, RowType {
    required init(tag: String?) {
        super.init(tag: tag)
        self.cellProvider = CellProvider<PersonInfoMasterCell>(nibName: "PersonInfoMasterCell")
    }
}
`

However I've been facing with this error, when I try to use, like: 
`<<< ButtonRow() {
                    $0.title = "Informar"
                }
                .onCellSelection { cell, row in
                    self.performSegue(withIdentifier: "presentSinglePersonSelection", sender: nil)
                }
            
            <<< PersonInfoMasterRow("leader") {
                $0.hidden = $0.value == nil
            }
`

**Comment by samritchie** [comment]
This is the bane of my existence, every time I touch the forms code in my app I get this error and it takes me forever to remember what causes it.

Future me: There’s something wrong inside the `initializer` closure but Swift doesn’t want to tell you what it is.
