### ISSUE TITLE
Can't add RuleMinLength rule into TextRow

### ISSUE THREAD

**Issue by Shiuyin** [xmartlabs/Eureka#785]
Hi,

much like https://github.com/xmartlabs/Eureka/issues/764 i have the same problem, except for TextRow. With the following code

```
form.last! <<< TextRow(String(field.id)) {
                    $0.title = field.question
                    $0.validationOptions = .validatesOnChange
                    if field.mandatory == true {
                        $0.add(rule: RuleRequired())
                    }
                    $0.add(rule: RuleMinLength(minLength: field.minLength))
                    $0.add(rule: RuleMaxLength(maxLength: field.maxLength))
                }
```

I still get the error "Incorrect argument label in call (have 'rule:', expected 'ruleSet:')", for the $0.add().

The RuleRequired() 2 lines above works though...

**Comment by mats-claassen** [comment]
Is `field.minLength` a UInt?

**Comment by Shiuyin** [comment]
It's a positive Integer, and defined as "dynamic var minLength: Int". I am using Swift Realm and "Field" is a Realm Object from my database that stores minLength and maxLength as Int's. So it should be easily possible to just plug them in one by one as a new "rule: ", which somehow fails as described.

If you need any more information, please tell me. (I have close to 0 experience in Swift, this is my 1st ios App).

Thanks.

**Comment by Shiuyin** [comment]
This can be closed. I found the problem myself. Thanks for sending me on the right direction with your UInt question.

For all having the same problem: The Rule's init is as follows:

 public init(minLength: UInt, msg: String? = nil){
        let ruleMsg = msg ?? "Field value must have at least \(minLength) characters"
        min = minLength
        validationError = ValidationError(msg: ruleMsg)
    }

So passing in an instance of type Int won't work because it expects an UInt. 

The current Swift compiler / XCode is however bugged and gave me a complete nonsense error message, thus sending me on the wrong track.

Thanks for your help.
