### ISSUE TITLE
Subclasses Cell<T> don't show up in xib inspector.

### ISSUE THREAD

**Issue by bennichols** [xmartlabs/Eureka#787]
Eureka 2.3 branch, Xcode 8.1, iOS 10:

I'm trying to make a custom cell from a xib and subclassing Cell<T>. However, the new class doesn't show up in the inspector when I try to assign it in the xib. If I change the class to inherit from BaseCell, it shows up as expected. I also tried getting rid of the generic and subclassing Cell<String> but that didn't work either.

**Comment by mtnbarreto** [comment]
This is a Interface Builder limitation that does not work with generic types.
As a workaround change custom cell superclass to BaseCell, connect the outlets and put back custom cell superclass to Cell<T>.
