### ISSUE TITLE
placeholderLabel frame doesn't changes

### ISSUE THREAD

**Issue by andertsk** [xmartlabs/Eureka#789]
When i set the new insets of `textView` of `TextAreaRow` the frame of `placeholderLabel` doesn't changes automatically.
```swift
TextAreaRow.defaultCellUpdate = { cell, _ in
    cell.textView.backgroundColor = AppSettings.AppColors.paleOrangeColor
    cell.textView.textContainerInset = UIEdgeInsetsMake(10, 10, 10, 10)
    cell.backgroundColor = .clear
}
```
So when i start typing in textView it becomes a bit ugly.
![screen shot 2016-11-14 at 1 21 53 pm](https://cloud.githubusercontent.com/assets/705208/20256646/5bf720aa-aa77-11e6-80c7-711c0fae5490.png)

**Comment by santiagofm** [comment]
Hey @andertsk ! Did you find a workaround for this ?
The placeholder's frame doesn't change because `UItextView`s don't have placeholders so this `placeholderLabel` is custom and not bound to the `textView`s frame or contentInsets.
Cheers

**Comment by m-revetria** [comment]
Closing this due to lack of response
