### ISSUE TITLE
Somebody can explain to me how from PushRow go to my view controller? 

### ISSUE THREAD

**Issue by rayastar** [xmartlabs/Eureka#790]
Hello everybody. i create PushRow:

            <<< PushRow<String>("category1") {
                $0.title = "Категория"
                ...
                $0.value = "test"            
            }
I want go to my view controller. How i can do it? I just do not understand what to do
thank you for your help

**Comment by mats-claassen** [comment]
You must use the `presentationMode` variable. You can have a look at the examples or do something like this:
```
    row.presentationMode = .show(controllerProvider: ControllerProvider.callback {
        return MyViewController<T>(){ _ in }
    }, completionCallback: { vc in
        vc.navigationController?.popViewController(animated: true)
    })
```
changing what you need.

**Comment by rayastar** [comment]
Thank you! i found example!!!! example with Map
