### ISSUE TITLE
Cell style does not work for some specific rows

### ISSUE THREAD

**Issue by abdulKarim002** [xmartlabs/Eureka#791]
This is the code i have used for changing cell text label and details text label in name row and email row and it doest not work,but works from other rows like - DateInlineRow, URLRow
![img_1836](https://cloud.githubusercontent.com/assets/13949425/20301040/cc547674-ab47-11e6-836c-238b39640553.png)

Xcode version - 8.1
Swift - 3.0
Eureka - 2.0.0-beta.1

        NameRow.defaultCellSetup = { cell, row in
            cell.textLabel?.textColor =  UIColor.red
            cell.detailTextLabel?.textColor = UIColor.red
            //cell.backgroundColor = UIColor.clear
        }
        
        EmailRow.defaultCellSetup = { cell, row in
            cell.textLabel?.textColor =  UIColor.red
            cell.detailTextLabel?.textColor = UIColor.red
            //cell.backgroundColor = UIColor.clear
        }

        DateInlineRow.defaultCellSetup = { cell, row in
            cell.textLabel?.textColor =  UIColor.red
            cell.detailTextLabel?.textColor = UIColor.red
            //cell.backgroundColor = UIColor.clear
        }

**Comment by mats-claassen** [comment]
You should be doing that using `defaultCellUpdate` and not `defaultCellSetup`. 
cellSetup is called just after the cell is initialized but Eureka does update the color of the label in its cellUpdate method to show that it is highlighted. Therefore the text colors of the default labels should always be set in the `cellUpdate` or `defaultCellUpdate`.

**Comment by abdulKarim002** [comment]
Thank you , it worked,..
