### ISSUE TITLE
Did IntRow work with percent formatter ?

### ISSUE THREAD

**Issue by Amefuri** [xmartlabs/Eureka#796]
I'm trying to do percent row by pass NSFormatter .PercentStyle to IntRow like this 

```swift
section <<< IntRow() {
            $0.title = "Test Percent Row"
            let formatter = NSNumberFormatter()
            formatter.numberStyle = .PercentStyle
            $0.formatter = formatter
}
```

but value is disappear after I tapped done.

Thank you,

**Comment by mtnbarreto** [comment]
same as #768

**Comment by mtnbarreto** [comment]
Eureka has a issue when formatter is only used to display the value (not during editing) and is not able to convert back the string value to typed value.

BTW the right way to use percent formatter is ..
```swift

<<< IntRow() {
                    $0.title = "Test Percent Row"
                    let formatter = NumberFormatter()
                    formatter.numberStyle = .percent
                    formatter.multiplier = 1
                    $0.formatter = formatter
                }
```

> notice I added `formatter.multiplier = 1`

**Comment by Amefuri** [comment]
It's working now Thanks!
