### ISSUE TITLE
How to obtain Eureka row knowing only UITableView indexPath number?

### ISSUE THREAD

**Issue by plastus** [xmartlabs/Eureka#797]
I am trying to implement swipe actions within Eureka cells and running into an issue. I know I have access to the currently swiped row's indexPath, but how can I obtain the actual Eureka row itself based on this so that I can access its properties (including string tag)?

    func tableView(tableView: UITableView, editActionsForRowAtIndexPath indexPath: NSIndexPath) -> [UITableViewRowAction]? {
        var actions = [UITableViewRowAction]()
        let action = UITableViewRowAction(style: .Normal, title: "Delete") { (action, indexPath) -> Void in
            self.tableView!.setEditing(false, animated: true)
            //placeholder for action
        }
        action.backgroundColor = UIColor(red:0.75, green:0.22, blue:0.17, alpha:1.0)
        actions.append(action)
        let action2 = UITableViewRowAction(style: .Normal, title: "Edit") { (action, indexPath) -> Void in
            self.tableView!.setEditing(false, animated: true)
            //placeholder for action
         }
         action2.backgroundColor = .orangeColor()
         actions.append(action2)
        return actions
    }

Would appreciate any hints or suggestions. Thanks!

**Comment by mtnbarreto** [comment]
from your controller functions you can index 
```swift
if let row = form[indexPath.section][indexPath.row] {
...
}
```

**Comment by plastus** [comment]
@mtnbarreto Awesome, thanks! Greatly appreciated. :)
