### ISSUE TITLE
ActionSheetRow + RuleRequired() & titleLabel

### ISSUE THREAD

**Issue by emadd** [xmartlabs/Eureka#798]
Would like my required ActionSheetRow to appear red when validation fails but the cell does not expose a titleLabel to change the color, only textLabel and that doesn't appear to work.

```
<<< ActionSheetRow<QProfileType>() { row in
                    row.title = "Profile Type"
                    row.selectorTitle = "Pick a Profile Type"
                    row.options = QProfileType.list()
                    row.add(rule: RuleRequired())
                    row.displayValueFor = {
                        val in
                        return val?.label()
                    }
                }.cellUpdate { cell, row in
                    if !row.isValid {
                        cell.textLabel?.textColor = .red
                    }
                }
```

**Comment by mats-claassen** [comment]
Currently the row is validated when the value changes (if `validationOptions` contains `validatesOnChange`) or when the cell resigns first responder which does not happen for selector rows. That is why it won't turn red. I you validate the row on demand calling `row.validate()` then it should turn red the next time it updates.

You could do that when the user wants to submit the form

**Comment by mtnbarreto** [comment]
you can either set `.validatesOnChange` to `validationOptions` property or validates on demand by calling row.validate().

> `validatesOnBlur` doesn't works on such kind of rows that don't become first responder. 

Regards

**Comment by Dithers** [comment]
I was able to change the validation text style by inserting a new label into the cells subview. hope this helps someone else as frustrated as I was

```
             if !row.isValid {
                for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
                    let labelRow = LabelRow() {
                    let errorLabel = UILabel()
                        errorLabel.text = validationMsg
                        errorLabel.frame = CGRect(x:0, y:0, width:$0.cell.frame.width, height:30)
                        errorLabel.textColor = UIColor.red
                        errorLabel.textAlignment = .left
                        $0.cell.addSubview(errorLabel)
                    }
                    row.section?.insert(labelRow, at: row.indexPath!.row + index + 1)
                }
            }
```
