### ISSUE TITLE
Show values for MultipleSelectorRow when disabled

### ISSUE THREAD

**Issue by Bart1909** [xmartlabs/Eureka#799]
Hey guys,

i'm very new to swift and ios-programming and using Eureka for showing some information. The form is disabled at first and will only be enabled if your user-role is a specific one and you press a button for editing.

I have a MultipleSelectorRow in my form and preselect some values. If the MultipleSelectorRow is disabled I can not click on them and see the whole list. 

Is it possible to show the list but disable, that the user can select values?

Best wishes from germany

Tobi

**Comment by mtnbarreto** [comment]
Hi @Bart1909,  

You can disable user interactions of presented selector controller instead of disabling the row.

```swift
                <<< MultipleSelectorRow<Emoji>() {
                        $0.title = "MultipleSelectorRow"
                        $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻]
                        $0.value = [👦🏼, 🍐, 🐗]
                    }
                    .onPresent { from, to in
                        
                        to.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: from, action: #selector(RowsExampleViewController.multipleSelectorDone(_:)))
                        let _ = to.view
                        to.tableView?.isUserInteractionEnabled = false   // <-------------
                    }
```

You might also want to change how the cell looks like when read only, please read Eureka documentation and related issues like #299.

**Comment by Bart1909** [comment]
Hi @mtnbarreto,

thanks for the hint!

But if I use isUSerInteractionEnabled then I'm unable to scroll.
But with the hint, I found, that using 
`to.tableView?.allowsSelection = true`
does exactly that, what I want. I can scroll the tableView and won't be able to select anything.

Thanks a lot!

Best wishes

Tobi

**Comment by mtnbarreto** [comment]
👍 good catch! thanks for sharing the hint!
