### ISSUE TITLE
how to change Section height

### ISSUE THREAD

**Issue by lkqin** [xmartlabs/Eureka#80]
how to change Section height

**Comment by mats-claassen** [comment]
A section consists of a header, rows and a footer. Each cell has a height variable so you can set the height of each row.
If you are setting the header and footer with strings you can also set the height for that header or footer in the initializer like this:
```
Section("FieldRow examples") {
        $0.header?.height = { 100 }
}
```
You can also set the header or footer like this if you have a custom view:
```
var header = HeaderFooterView<MyHeaderNibFile>(.NibFile(name: "MyHeaderNibFile", bundle: nil))        
header.onSetupView = { view, _, _ in
     // customize header
 }

header.height = { 100 }
section.header = header
```

**Comment by iBenjamin** [comment]
if you want to make a section header height to 0, you can use to following code.

```objc
$0.header = HeaderFooterView<UIView>(HeaderFooterProvider.Class)
$0.header?.height = { CGFloat.min }
```
