### ISSUE TITLE
LabelRow textAlignment center not working

### ISSUE THREAD

**Issue by Tripwire999** [xmartlabs/Eureka#801]
Environment:
- Eureka version 2.0.0 beta 1
- Xcode version 8.0 (8A218a)
- iOS 10 (14A345)

Hi, 

I can't seem to set the alignment of a LabelRow to center. I'm using the following code:
```swift
<<< LabelRow("TEST") {
        $0.title = "Test label"
        $0.cellUpdate { cell, row in
          cell.textLabel?.textAlignment = .center
          cell.textLabel?.textColor = .white
          cell.backgroundColor = UIColor(red: 255/255, green: 65/255, blue: 65/255, alpha: 1.0)
        }
    }
```

I've read on StackOverflow that this should work but nothing is happening on the label. I've checked the frame of the label and it's the size of the text. I've tried to set the cell frame and textLabel frame to something different but that's also not working.

**Comment by mtnbarreto** [comment]
Hi @Tripwire999 , you should change the table view cell style to get this layout as code below shows...

```swift
                <<< LabelRow () {
                        $0.title = "LabelRow"
                        $0.cellStyle = .default
                    }
                    .cellUpdate({ (cell, row) in
                        cell.textLabel?.textAlignment = .center
                    })
```

Regards

**Comment by Tripwire999** [comment]
Hi,

Sorry for the late reply but it's still not working for me. I've changed some code here is a sample of what i'm using now which is not working:
```
    let endDateTimeError: LabelRow = LabelRow()
    endDateTimeError.tag = "endDateTimeErrorRow"
    endDateTimeError.title = "Eindtijd kan niet voor begintijd liggen"
    endDateTimeError.cell.backgroundColor = timeErrorBackgroundColor
    endDateTimeError.cellStyle = .default
    endDateTimeError.cellUpdate { cell, row in
      cell.textLabel?.textAlignment = .center
      cell.textLabel?.textColor = timeErrorTextColor
    }
    endDateTimeError.hidden = .function([""], { form -> Bool in
      return employee.endTime! > employee.startTime!
    })
    section <<< endDateTimeError
```

**Comment by mats-claassen** [comment]
@marioGusmao I think that won't work with the default `cellStyle`. I also don't know what exactly you want to accomplish. Please search in other issues and StackOverFlow for help
