### ISSUE TITLE
TimeInlineRow Doesn't Call .OnRowValidationChanged

### ISSUE THREAD

**Issue by s1rc** [xmartlabs/Eureka#803]
Using UX callback example provided in the 'Eureka Example' project the following will validate as false and show the error message. Changing the value of the TimeInlineRow does validate as true, but the error message row is not removed.

```swift
TimeInlineRow() {
    $0.title = "Question"
    $0.add(rule: RuleRequired())
}.onRowValidationChanged { cell, row in
    let rowIndex = row.indexPath!.row
    while row.section!.count > rowIndex + 1 && row.section?[rowIndex  + 1] is LabelRow {
        row.section?.remove(at: rowIndex + 1)
    }
    if !row.isValid {
        for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
            let labelRow = LabelRow() {
                $0.title = validationMsg
                $0.cell.contentView.backgroundColor = UIColor.red
                $0.cell.height = { 30 }
            }
            row.section?.insert(labelRow, at: row.indexPath!.row + index + 1)
        }
    }
}
```

**Comment by mtnbarreto** [comment]
It's been called but you have some issues on that code.

First, Eureka does not evaluate the rules at the beginning, I mean when the form is displayed. 
Then, this is a Inline row so you should not add the label row between the `TimeInlineRow ` and its associated inline row, in particular if `TimeInlineRow` is expanded. 
You must set up `$0.validationOptions = .validatesOnChange` because inline rows never become first responder so they never blur the field.  By default `.validatesOnBlur` is the `validationOptions` value.
Finally, after selecting a date value it's impossible to make it fails, at least through the UI. In the code bellow i'm using `ClosureRule` to randomly switch between true/false. 

```swift
<<< TimeInlineRow(){
                $0.title = "TimeInlineRow"
                $0.validationOptions = .validatesOnBlur
                $0.add(rule: RuleClosure() {value in return arc4random_uniform(2) == 0 ? ValidationError(msg: "Validation Error") : nil })
            }.onRowValidationChanged { cell, row in
                let rowIndex = row.indexPath!.row
                let shiftCount = row.isCollapsed ? 1 : 2
                while row.section!.count > rowIndex + shiftCount && row.section?[rowIndex  + shiftCount] is LabelRow {
                    row.section?.remove(at: rowIndex + shiftCount)
                }
                if !row.isValid {
                    for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
                        let labelRow = LabelRow() {
                            $0.title = validationMsg
                            $0.cell.contentView.backgroundColor = UIColor.red
                            $0.cell.height = { 30 }
                        }
                        row.section?.insert(labelRow, at: row.indexPath!.row + index + shiftCount)
                    }
                }
            }
```

> I added `isCollapsed`, `isExpanded` helpers that will be merged with master. 

Ideally you should add this code using `defaultOnRowValidationChanged` like the code bellow shows

```swift
TimeInlineRow.defaultOnRowValidationChanged { cell, row in
       let rowIndex = row.indexPath!.row
                let shiftCount = row.isCollapsed ? 1 : 2
                while row.section!.count > rowIndex + shiftCount && row.section?[rowIndex  + shiftCount] is LabelRow {
                    row.section?.remove(at: rowIndex + shiftCount)
                }
                if !row.isValid {
                    for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
                        let labelRow = LabelRow() {
                            $0.title = validationMsg
                            $0.cell.contentView.backgroundColor = UIColor.red
                            $0.cell.height = { 30 }
                        }
                        row.section?.insert(labelRow, at: row.indexPath!.row + index + shiftCount)
                    }
                }              
}
```

By doing that in that way you have to configure it only once instead of adding this code on every `TimeInlineRow` of your app. 

Hope it helps you!

**Comment by Skyb0rg** [comment]
Its not working anymore with the above code :

now you should use:

`TimeInlineRow.defaultOnRowValidationChanged { cell, row in
       let rowIndex = row.indexPath!.row
                let shiftCount = row.isCollapsed ? 1 : 2
                while row.section!.count > rowIndex + shiftCount && row.section?[rowIndex  + shiftCount] is LabelRow {
                    row.section?.remove(at: rowIndex + shiftCount)
                }
                if !row.isValid {
                    for (index, validationMsg) in row.validationErrors.map({ $0.msg }).enumerated() {
                        let labelRow = LabelRow() {
                            $0.title = validationMsg
                            $0.cell.contentView.backgroundColor = UIColor.red
                            $0.cell.height = { 30 }
                        }
                        row.section?.insert(labelRow, at: rowIndex + index + shiftCount)
                    }
                }              
}`

to avoid: 
Simultaneous accesses to 0x7fac17789bf8, but modification requires exclusive access.
Previous access (a modification) started at Eureka`BaseRow.section.modify + 111 (0x104940d3f).
Current access (a read) started at:

replace
row.indexPath!.row

at 
row.section?.insert(...
with 
rowIndex

hope this helps somebody.
