### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by Tripwire999** [xmartlabs/Eureka#804]
**Environment:**
- Xcode 8.1
- iOS version: 10.1
- Eureka version 2.0.0 beta 1

Hi,

When compiling my eureka forms in Xcode 8.1 I get the error in the title of this issue. This happens to a lot of forms in my app. When I comment everything out in my populateForm my app is compiling fine.
**Error message**

1.	While type-checking 'populateForm' at /Users/Sebastiaan/Documents/Xcode projects/Spills/Spills/ViewControllers/CleaningSubsequentWorkFormViewController.swift:26:12
2.	While type-checking expression at [/Users/Sebastiaan/Documents/Xcode projects/Spills/Spills/ViewControllers/CleaningSubsequentWorkFormViewController.swift:27:5 - line:54:10] RangeText="form +++ Section("VERVOLGWERKZAAMHEDEN")
      <<< SegmentedRow<String>("extra_oil") {
        $0.title = "Vervanging geplaatste oil boom"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.replaceOilBoom > -1 ? $0.options[self.currentCalamity.replaceOilBoom] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
      }.onChange({ row in
        self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.replaceOilBoom))")
      })
      <<< SegmentedRow<String>("extra_sample") {
        $0.title = "Bodem bemonstering"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.soilSampling > -1 ? $0.options[self.currentCalamity.soilSampling] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
        }.onChange({ row in
          self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.soilSampling))")
        })
      <<< SegmentedRow<String>("extra_soil") {
        $0.title = "Bodem sanering"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.soilRemediation > -1 ? $0.options[self.currentCalamity.soilRemediation] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
        }.onChange({ row in
          self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.soilRemediation))")
        })"

**Form code**
```swift
form +++ Section("VERVOLGWERKZAAMHEDEN")
      <<< SegmentedRow<String>("extra_oil") {
        $0.title = "Vervanging geplaatste oil boom"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.replaceOilBoom > -1 ? $0.options[self.currentCalamity.replaceOilBoom] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
      }.onChange({ row in
        self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.replaceOilBoom))")
      })
      <<< SegmentedRow<String>("extra_sample") {
        $0.title = "Bodem bemonstering"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.soilSampling > -1 ? $0.options[self.currentCalamity.soilSampling] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
        }.onChange({ row in
          self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.soilSampling))")
        })
  <<< SegmentedRow<String>("extra_soil") {
        $0.title = "Bodem sanering"
        $0.options = [kNo, kYes]
        $0.value = self.currentCalamity.soilRemediation > -1 ? $0.options[self.currentCalamity.soilRemediation] : nil
        }.cellSetup { cell, row in
          cell.setControlWidth(width: 200)
        }.onChange({ row in
          self.updateCurrentCalamity(value: row.options.index(of:row.value!), forKey: "\(#keyPath(Calamity.soilRemediation))")
        })

   form +++ Section("EXTRA WERKZAAMHEDEN")
      <<< TextAreaRow("extra_remark") {
        $0.value = self.currentCalamity.extraNotes
        }.onChange({ row in
          self.updateCurrentCalamity(value: row.value, forKey: "\(#keyPath(Calamity.extraNotes))", nilAllowed: true)
        })
```

**Comment by Tripwire999** [comment]
Sorry about the code formatting, somehow the formatting tools on GIT never work for me -_-

**Comment by mtnbarreto** [comment]
Hi @Tripwire999 , there may be something customized by you that makes the compilation fail. I just ran the example project and looks like everything works as expected. 

Could you provide more information in order to reproduce the issue so i can give further assistance?? Would be great If you can share an app reproducing the issue.
