### ISSUE TITLE
Arabic Support and RTL

### ISSUE THREAD

**Issue by tarek903** [xmartlabs/Eureka#807]
Hi,
 first of all i'd like to thank you guys for this great library i really appreciate what you are doing here

as for the problem of Arabic support , when i edit the schema and choose Arabic language, layouts doesn't change but when i choose right to left pseudo language it does . can't figure out the problem here thanks in advance

**Comment by mtnbarreto** [comment]
@tarek903 
What do you mean by "layout change"? Could you share an screenshot pointing out the issue?

**Comment by ybeapps** [comment]
+1 I want this feature too
to be fully localized we have to support Right-To-Left Languages, such as Arabic and Hebrew

Need to check SemanticContentAttribute and apply reverse in layout if needed

**Comment by ybeapps** [comment]
I have a workaround but it's partially working.

in my FormViewController viewDidLoad I add the following line:
```
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        tableView?.semanticContentAttribute = .forceRightToLeft
```

The layout does reverses.. but it's not looking good as the standard Left-To-Right.

Look at the result in the attached picture
![simulator screen shot 15 2017 17 47 46](https://cloud.githubusercontent.com/assets/5706986/26063406/a62896c8-3996-11e7-82c7-b3074fefda0f.png)

**Comment by ybeapps** [comment]
The best solution is that all the subviews of the FormViewController implementations will inherit the "SemanticContentAttribute" from the view controllers view
This suppose to fix all issues
