### ISSUE TITLE
Picker Keyboard

### ISSUE THREAD

**Issue by SpencerC** [xmartlabs/Eureka#808]
Hi,
The inline picker controls are cool, but I was wondering if there was an easy way to display the picker in the keyboard area with the prev/next controls like Safari does:
![img_3684](https://cloud.githubusercontent.com/assets/817672/20655831/3bc197f2-b4db-11e6-907b-2c7d5bb7a611.PNG)

If there isn't, and I were to implement an approach, would it be a good candidate for a pull request?

**Comment by mtnbarreto** [comment]
We don't have such picker view row variation yet. We would love to have it so Feel free to make a pull request. 
Maybe PickerInputRow is a good candidate name for the row. What do you think?
