### ISSUE TITLE
Custom Row fails to update its subviews on updateCell()

### ISSUE THREAD

**Issue by Laptopmini** [xmartlabs/Eureka#810]
Eureka: 1.7 (Swift 2 Branch)
XCode: 7.3.1 (Swift 2.2)
iOS Target: 9.0

I have a form which lets you access a Color Picker and I am trying to make a custom row to represent the user's selection when coming back to the form. After multiple attempts using Custom Presenter Rows, without any success, I decided to just use a normal row and its `onCellSelection` method to present the new controller. 

The Color Picker presented uses the Form as a delegate so that when the User makes a selection, the delegate method in the Form is called and I can update the corresponding row that presented it. 

Here is the code I have for my custom row:

```swift
public class ColorPickerEurekaFormCell: Cell<Bool>, CellType {
    
    @IBOutlet var title: UILabel!  // Default Value: "Color"
    @IBOutlet var colorIndicator: UIView!
    
    public override func setup() {
        super.setup()
        colorIndicator.backgroundColor = .clearColor()
        colorIndicator.layer.cornerRadius = 10
        colorIndicator.layer.borderWidth = 1
        colorIndicator.layer.borderColor = UIColor.lightGrayColor().CGColor
    }
    
    func changeTitle(title: String) {
        self.title.text = title
        row.updateCell()
    }
    
    func changeColorIndicator(color: UIColor) {
        self.colorIndicator.backgroundColor = color
        row.updateCell()
    }
}


public final class ColorPickerEurekaFormRow: Row<Bool, ColorPickerEurekaFormCell>, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<ColorPickerEurekaFormCell>(nibName: "ColorPickerEurekaFormCell")
    }
}
```

As you can see, the row's layout is defined in a `.xib` with 2 outlets: the title and color indicator (a UIView with rounded corners on the right hand side of the row).

When my delegate method from my Color Picker is called and returns a UIColor, I call `.changeColorIndicator(color)` with it. However I can't get the `colorIndicator` UIView to update its color for the life of me. 

In `changeColorIndicator()`, if I do:
```swift
self.backgroundColor = .greenColor()
self.row.updateCell()
```
The background color of the cell changes to green, which means its updating the cell itself fine, but it can't seem to redraw/update the UIView I defined in my `.xib`. I also tried calling `.setNeedsDisplay` on the `colorIndicator`, but nothing changed either.

Do you guys have any idea how to get the cell to redraw a subview? Or why this subview isn't updating?

**Comment by Laptopmini** [comment]
Follow-up question:
How can I prevent the row from using its initialize state when highlighted?

As seen above, in the `setup()` of the cell, I set the `colorIndicator.backgroundColor = .clearColor()`.

Now, if I add the following method to `ColorPickerEurekaFormRow: Row<Bool, ColorPickerEurekaFormCell>, RowType`:
```
func changeColorIndicator(color: UIColor) {
        cell.changeColorIndicator(color)
    }
```

So that I can do the following when the Row is initialized:
```
ColorPickerEurekaFormRow(DEVICE_COLOR_TAG) { row in
                if let initialDeviceColor = self.initialDeviceColor {
                    row.changeColorIndicator(initialDeviceColor)
                }
}
```

where:
```
private var initialDeviceColor: UIColor?
```

Then the Row appears when an initial Color (all good). However, when the Cell is highlighted, the `colorIndicator` revers back to its original color, `.clearColor()`.

I tried looking into overridding `Cell`'s `highlightCell()` method, but I could not figure where its telling it to use the original configuration from `setup()`, or even where its keeping track of these original settings. 
Any advice?

PS: Sorry for the blocks of texts, I just try to make sure I'm as detailed as possible.

**Comment by mtnbarreto** [comment]
`cell.update()` is doing nothing since you are not overriding that method. 

Ideally your row, cell should hold a "color" (UIColor) instead of a Bool. Why does it hold a bool if the user is selecting a color?

then update method should set the `colorIndicator` background  color. If the cell keeps selected  when the user leaves the form to select the color, when get back to the cell Eureka automatically updates it otherwise you have to update the cell manually as you have been doing. 

 If after following this you still don't make it work, please share a Eureka repository containing your custom row so i can take a look at it.

**Comment by Laptopmini** [comment]
@mtnbarreto Sorry for the late response. I had to put this on hold while I switch over to Swift 3.

While I was migrating, I updated my code to reflect the advice you gave me above, but the problem still remains. Here is the following code I have for my Row/Cell at the moment:
```
open class ColorPickerEurekaFormCell: Cell<UIColor>, CellType {
    fileprivate let defaultColorIndicatorBorderWidth: CGFloat = 1
    
    @IBOutlet var title: UILabel!
    @IBOutlet var colorIndicator: UIView!
    
    open override func setup() {
        super.setup()
        colorIndicator.backgroundColor = .clear
        colorIndicator.layer.cornerRadius = 10
        colorIndicator.layer.borderWidth = defaultColorIndicatorBorderWidth
        colorIndicator.layer.borderColor = UIColor.lightGray.cgColor
    }
    
    open override func update() {
        super.update()
        if let value = row.value {
            colorIndicator.backgroundColor = value
            if value == .clear {
                colorIndicator.layer.borderWidth = defaultColorIndicatorBorderWidth
            } else {
                colorIndicator.layer.borderWidth = 0
            }
        }
    }
}


public final class ColorPickerEurekaFormRow: Row<ColorPickerEurekaFormCell>, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<ColorPickerEurekaFormCell>(nibName: "ColorPickerEurekaFormCell")
    }
    
    func changeColorIndicator(_ color: UIColor?) {
        value = color ?? .clear
        cell.update()
    }
}
```

The row itself is initialized as such:
```
ColorPickerEurekaFormRow(DEVICE_COLOR_TAG) { row in
    if let initialDeviceColor = self.initialDeviceColor {
        row.value = initialDeviceColor
    }
}.onCellSelection({ (cell, row) in
    self.presentColorPickerController()
})
```

When `presentColorPickerController()` is called, I present my `ColorPickerViewController` which uses the form as a delegate. When the user confirms his choice, the view is pop'd off and the delegate method `colorPickerDidChooseColor()` is called. This method then calls `row.changeColorIndicator(color)` where `color` is the `UIColor` chosen by the user and `row` is obviously our instance of `ColorPickerEurekaFormRow`. 

Let me know if I can provide any more information.

**Comment by Laptopmini** [comment]
@mtnbarreto You can remove the awaiting response tag.

**Comment by mtnbarreto** [comment]
`changeColorIndicator ` is being invoked? have you debugged it? 

I need a project containing the row to provide additional support. It may be several things and with the information provided is hard to realize what is happening.

**Comment by m-revetria** [comment]
Closing this due to lack of response. 

@Laptopmini if this is still happening in the latest version of Eureka and you can provide an example project with the row please consider reopening this issue.

Regards

**Comment by Laptopmini** [comment]
This issue does NOT occur in the latest version of Eureka.
