### ISSUE TITLE
Way to create background for sections

### ISSUE THREAD

**Issue by jordancamara** [xmartlabs/Eureka#815]
Is there a way to create a background view or container for each section? Seems like this would be a pretty common use case. Any ideas?

**Comment by mtnbarreto** [comment]
For every row of the section you should set up cell background view and also it contentView's color to clear.

```swift
<<< DecimalRow().cellSetup { cell, row  in
                                    cell.backgroundView = YourView()
                                    cell.contentView.backgroundColor = .clearColor
                               }
```
