### ISSUE TITLE
StepperRow does not display displayValueFor properly

### ISSUE THREAD

**Issue by alldritt** [xmartlabs/Eureka#817]
Hello,

I'm using Electra pod 'Eureka', '~> 2.0.0-beta.1', Xcode 8.1, iOS 10.1 (iPhone/iPad)

I'm having a problem where when I use displayValueFor to format my stepper values (milliseconds) the resulting display is incorrect:

![img_0041](https://cloud.githubusercontent.com/assets/1425137/20807626/8f18b44a-b7b4-11e6-950e-18e0496df683.png)

The code I'm using to construct these stepper rows looks like this:

```
                <<< StepperRow {
                    $0.title = "Fixaction"
                    $0.displayValueFor = {
                        return "\(Int($0 ?? 0)) ms"
                    }
                    $0.value = Double(self.options.fixationPeriod)
                }
                .onChange {
                    self.options.fixationPeriod = Int($0.value ?? 0)
                }

```

Can someone explain what I'm doing wrong?  

Thanks in advance

**Comment by mtnbarreto** [comment]
You are properly setting up the row but there is an issue. I will fix it now.
