### ISSUE TITLE
accessoryButtonTappedForRowWith 

### ISSUE THREAD

**Issue by johnmci** [xmartlabs/Eureka#820]
I noticed you don't have a delegate exposed for accessoryButtonTappedForRowWith

open func tableView(_ tableView: UITableView, accessoryButtonTappedForRowWith indexPath: IndexPath) 

in the extension FormViewController : UITableViewDelegate

We needed that because we wanted to know if the row was selected, or if the accessory button was tapped. We won't do a pull request yet because we are not sure exactly how you would like to expose the tap to the row or cell.

**Comment by mtnbarreto** [comment]
Hi @johnmci , you can implement this delegate method directly from your FormViewController extension as the code below shows...


```swift
@objc(tableView:accessoryButtonTappedForRowWithIndexPath:) func tableView(_ tableView: UITableView, accessoryButtonTappedForRowWith indexPath: IndexPath) {
        print("Hi")
}
```

you will have to change the accessory type of the row by setting up accessoryType to detailDisclosureButton...

```swift
.cellUpdate { cell, row in
        cell.accessoryType = .detailDisclosureButton // or .detailButton
}
```

According to apple [doc](https://developer.apple.com/reference/uikit/uitableviewdelegate/1614996-tableview?language=objc) the method is only called when accessory type is .detailButton or .detailDisclosureButton

> The delegate usually responds to the tap on the disclosure button (the accessory view) by displaying a new view related to the selected row. This method is not called when an accessory view is set for the row at indexPath.

**Comment by mtnbarreto** [comment]
LMK if that solution works for you..

**Comment by johnmci** [comment]
Ok, we can do that, if it ever goes into the base class then we'll get flagged about having to do an override and decide how to proceed then
