### ISSUE TITLE
ButtonRow gets pushed under the Navigation bar

### ISSUE THREAD

**Issue by Shiuyin** [xmartlabs/Eureka#822]
I have a simple VC that look like that: 

```
class MyVC: FormViewController, UIPickerViewDelegate {
}
```

This VC is embeded into a Navigation Controller, that i created using XCode's "embed in..." feature.

Right at the start of it, i am creating a section and add a new ButtonRow() like that:

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        form +++ Section()
        form.last! <<< ButtonRow() {
            $0.title = "Add..."
        }.onCellSelection { _, _ in
            print("TEST: clicked add button")
        }
    }
```

This however results in the following messed up layout:
![screenshot](https://cloud.githubusercontent.com/assets/7461737/20862488/51a26bac-b9ac-11e6-9f48-00694a46ab38.png)

The ButtonRow is nearly not visible and pushed under the navigation bar. I can't click the ButtonRow. And yes, the screenshot is completely scrolled up to the top.

What is happening here and how can i fix that?

Thanks :)

EDIT: Strange. I had a UIPickerView added to the VC in my storyboard (placed it directly on the view). This seems to have messed up the ButtonRow() disappearing under the Navigation Bar. I fixed it by adding self.tableView?.addSubview(myPicker)

1. Why did it mess up the row rendering in the first place?
2. Why does it now work properly with adding the addSubview() right after initialization?
3. Why is an addSubview() needed in order to make the UIPickerView visible? It wasn't visible to me before that.

**Comment by spinloop** [comment]
I am experiencing this as well...

![image](https://cloud.githubusercontent.com/assets/7525850/20893897/6fd6549a-bae1-11e6-8f3f-85638ba50f08.png)

**Comment by mtnbarreto** [comment]
Are you connecting `tableView` FormViewController IBOutlet?

**Comment by mtnbarreto** [comment]
Seems similar to #116

**Comment by spinloop** [comment]
@mtnbarreto thank you! i was converting a form i did manually to using the library and hadn't yet removed those connections. much appreciated.

**Comment by mtnbarreto** [comment]
You welcome! You should connect the storyboard `tableview` with the `tableView` FormViewController IBOutlet.
