### ISSUE TITLE
Simple color changing question

### ISSUE THREAD

**Issue by leandrodestro** [xmartlabs/Eureka#838]
Is it still possible to change the colors of the "navigation arrows" (< and >) and "'Done' button" that appears right above the keyboard?

![img_1444](https://cloud.githubusercontent.com/assets/7717621/21108526/92fb577c-c07c-11e6-850a-83da983a1166.PNG)

I'm quite sure that I could do it by setting a global color with:

`UIView.appearance().tintColor = color_themeColor`

However I don't think that this still works (after I updated to the Swift 3 version).

Thanks.

**Comment by yuchenglin** [comment]
@leandrodestro Did you find the solution? Thanks

**Comment by yuchenglin** [comment]
@leandrodestro 
Thanks your reply. 
This does change my check color(option selector) but the buttons above keyboard are still default blue. I added that line in `AppDelegate`. Did I miss something?
