### ISSUE TITLE
Eureka Prompt for converting to swift 3 everytime a new pod is added to pod file

### ISSUE THREAD

**Issue by pprevalon** [xmartlabs/Eureka#839]
Everytime I add a new pod and update pod file i get conversion error in eureka to convert to swift 3.0. When convert Eureka to 3.0 no error issues is converted. how can this be fixed

**Comment by santiagofm** [comment]
Are you experiencing this issue with newer versions of the library ?
Cheers

**Comment by pprevalon** [comment]
No
