### ISSUE TITLE
Add image to segmented control

### ISSUE THREAD

**Issue by eemilko** [xmartlabs/Eureka#840]
It seems that it is possible to have the user choose between images in the segmented control (not text). However when I try to add this: 

```swift
<<< SegmentedRow<UIImage>(){
          $0.title = "SegmentedRow"
          $0.options = [UIImage(named: "dog")!, UIImage(named: "dog")!]
}
```

I just get a string <UIImage: 0x153...>,{40, 40} and not the actual image displayed.
The same thing happened when I tried to use an inline row:

```swift
<<< PickerInlineRow<UIImage>("Icon") { (row : PickerInlineRow<UIImage>) -> Void in
          row.title = row.tag
          row.options = [UIImage(named: "dog")!, UIImage(named: "dog")!]
          row.value = row.options[0]
}
```
How can I let the user choose between a list of predefined images?

Thanks.

**Comment by george-hsin-somobilehealth** [comment]
But UIImage is still not supported with PickerInlineRow
