### ISSUE TITLE
Exception with an @IBOutlet table

### ISSUE THREAD

**Issue by mojidabckuu** [xmartlabs/Eureka#845]
Faced with an issue when I have a form for the controller as an `IBOutlet` and form creation code starts with
```swift
form +++ Section() <<< ...
```
The it gives an animation when screen appears
If my form creation is written like
```swift
form = Section() <<< ... +++ Section()
```
Then it gives a crash for
```swift
open override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        let selectedIndexPaths = tableView?.indexPathsForSelectedRows ?? []
        tableView?.reloadRows(at: selectedIndexPaths, with: .none)
```
Am I doing something wrong for initialization? When form is not an `IBOutlet` then it is fine. 

```swift
// I added extra if for 
if let selectedIndexPaths = tableView?.indexPathsForSelectedRows, !selectedIndexPaths.isEmpty {
            tableView?.reloadRows(at: selectedIndexPaths, with: .none)
// Other part of code
}
```
For now it works for me

**Comment by mtnbarreto** [comment]
It works fine for me. 

Could you share an example to reproduce it?

**Comment by m-revetria** [comment]
Closing this due to lack of response
