### ISSUE TITLE
Keyboard Toolbar color

### ISSUE THREAD

**Issue by mellob** [xmartlabs/Eureka#851]
The Keyboard toolbar text color is white when entering data for textRow. Does anyone know how to change the color. Also with the Keyboard toolbar is it possible to get the field placeholder values for each text field along with the arrows (<>)

Melvin

**Comment by starr0stealer** [comment]
@mellob 

To customize the color of the navigation tool bar make sure you are subclassing `FormViewController` then you have access to the property `navigationAccessoryView`. Note you could also handle this via `*.appearance().*` called during `AppDelegate` to globally apply. You can access `UIToolbar`, `UIBarButtonItem` or `NavigationAccessoryView` depending on your needs. I handle global App themes that way.

ie

```swift
        navigationAccessoryView.tintColor = UIColor(...)
        navigationAccessoryView.barTintColor = UIColor(...)
        navigationAccessoryView.sizeToFit() // sometimes this is needed to trigger a UI update

     // Called during AppDelegate

        NavigationAccessoryView.appearance().tintColor = UIColor(...)
        NavigationAccessoryView.appearance().barTintColor = UIColor(...)
```

If your reference to `placeholder values` is about adding them to the navigation toolbar, you would have to completely replace `navigationAccessoryView` of `FormViewController` with your own subclass adding this functionality.  You would need to "wire" it up in your subclass of `FormViewController`, though it may be tricky.

**Comment by txaiwieser** [comment]
I was trying to use the appearance proxy to change the tintColor of the NavigationAccessoryView, but unfortunately the FormViewController forces the tintColor to be the view.tintColor (witch I don't want) 

``` swift
open class FormViewController : UIViewController, FormViewControllerProtocol {
    open override func viewDidLoad() {
        super.viewDidLoad()
        navigationAccessoryView = NavigationAccessoryView(frame: CGRect(x: 0, y: 0, width: view.frame.width, height: 44.0))
        navigationAccessoryView.tintColor = view.tintColor <-- THIS LINE
        navigationAccessoryView.autoresizingMask = .flexibleWidth
        }
    }
```

I removed this forced set in my fork, if you guys think it will work in other cases I can make the PR
