### ISSUE TITLE
When Using with Material the view does not show

### ISSUE THREAD

**Issue by winniepooh001** [xmartlabs/Eureka#856]
Hi,

Thank you for the wonderful form. A problem I'm having is that when I have the form as a child view controller of another view controller (to provide common header and footer using Material by cosmic mind). The view just won't show. I think it is because the form it self does not have a view?

I'm not sure how to resolve this. I just want to know if form does not working as a child view?

Thank you

**Comment by winniepooh001** [comment]
Please close.. I figured out what I did wrong. Sorry

**Comment by mtnbarreto** [comment]
okay. 

> Eureka forms work as child view controllers, i have already tested it.
