### ISSUE TITLE
Is this design possible with Eureka?

### ISSUE THREAD

**Issue by SaifAlDilaimi** [xmartlabs/Eureka#858]
I have the following design and I would really like to use Eureka for it but I have few issues:

1. how can I add a TableHeaderView to the Form (The part with the user image on top)
2. how can I design the cell to look like the ones in my design? As far as I this is not possible without subclassing right?

**Image**
![entry_missed_info](https://cloud.githubusercontent.com/assets/3785570/21508011/8ef8ff46-cc7d-11e6-9545-3fb7c1a1799b.png)

All the textfields should also have a placeholder, is this possible?

**Comment by sxua** [comment]
Yes

**Comment by starr0stealer** [comment]
@SaifAlDilaimi 

For the image header you could do something similar to how it was done in the Example app, using a `Nib`.

https://github.com/xmartlabs/Eureka/blob/master/Example/Example/ViewController.swift#L353

For the images at the start of each cell, you could also do similar to what is in the Example app, using `cellSetup`.

https://github.com/xmartlabs/Eureka/blob/master/Example/Example/ViewController.swift#L184

```swift
.cellSetup { cell, row in
    cell.imageView?.image = UIImage(named: "...")
}
```

**Comment by SaifAlDilaimi** [comment]
perfect, thx!
