### ISSUE TITLE
Xcode runs hot when using many setValues parameters

### ISSUE THREAD

**Issue by sidetrax** [xmartlabs/Eureka#86]
Dear Xmartlabs-Team,
when using your framework I encounter the trouble that with many setValue parameters my mac's fans start to go crazy.
Using about 10-12 (mixed rows, others are commented out) works even though Xcode takes pretty long to compile the swift files. Starting with about 13 Rows the compiling takes awfully long and my mac runs hot. With every row it seems the time to compile rises exponentially. I have most of them disabled to spare my mac of the strain and I guess it would take a couple of hours to compile.

I tried different variations to find out whether this is caused by a certain parameter but it turns out I can use any combination with the above problem.

I use the setValues like so:

<code>form.setValues(["companyName": companyName,"isHomeCompany": isHomeCompany,"companyCircuit": companyCircuit,"companyStreet": companyStreet,"companyZIPCode": companyZIPCode,"companyCity": companyCity,"companyCountry": companyCountry,"companyPhone": companyPhone,"openHour": openHour,"closeHour": closeHour,"contactName": contactName,"contactHomePhone": contactHomePhone,"contactCellPhone": contactCellPhone,"contactEmail": contactEmail,"conatct2Name": conatct2Name,"conatct2HomePhone": conatct2HomePhone,"conatct2CellPhone": conatct2CellPhone,"conatct2Email": conatct2Email*/])</code>

**Comment by mats-claassen** [comment]
I did try the `setValues` func in the 'Rows' example by setting more than 10 rows and did not see any change. Where are you calling this function? And can you give us a bit more context of your form? Are you setting Strings or other objects as values?

**Comment by sidetrax** [comment]
Thank you for your reply.
I uploaded a TestViewController.swift file as txt-file.
In the storyboard I'm using a plain ViewController with a tableView in it, like you did in your example project.
Please let me know if I am somehow using it incorrectly or if it compiles without problems in your development environment.

[TestViewController.txt](https://github.com/xmartlabs/Eureka/files/33471/TestViewController.txt)

**Comment by connersimmons** [comment]
@sidetrax @mats-claassen I am having the same issue.

**Comment by mats-claassen** [comment]
It seems this is on the Swift side rather than Eureka. The slow part seems to be the part where you create a Dictionary [String: Any?]. To work around this I did the following and it works fine:
```
let arr : [String: String?] = ["companyName": companyName,"companyCircuit": companyCircuit,"companyStreet": companyStreet,"companyZIPCode": companyZIPCode,"companyCity": companyCity,"companyCountry": companyCountry,"companyPhone": companyPhone,"midweekMeetingWeekday": midweekMeetingWeekday,"publicMeetingWeekday": publicMeetingWeekday,"contactName": contactName,"contactHomePhone": contactHomePhone,"contactCellPhone": contactCellPhone,"contactEmail": contactEmail,"contact2Name": contact2Name,"contact2HomePhone": contact2HomePhone,"contact2CellPhone": contact2CellPhone,"contact2Email": contact2Email]
        
var anyArr = [String: Any?]()
arr.map({ (key, value) in
     anyArr[key] = value
})
form.setValues(anyArr)
```
While this works, you can just set one type at a time like this, which is not really useful.
I recommend creating the dictionary as follows:
```
var arr = [String: Any?]()
arr["companyName"] = companyName
arr["companyCircuit"] = companyCircuit
...
arr["contact2CellPhone"] = contact2CellPhone
```

**Comment by sidetrax** [comment]
I just tried the second one. Works perfectly! Thanks a lot!
For me the issue has been solved. ;-)

**Comment by connersimmons** [comment]
This second option also works for me. Thanks for getting back to us!
