### ISSUE TITLE
Is there a way to use a ButtonRow() .onCellSelection() to add dynamically the previous row based on user input?

### ISSUE THREAD

**Issue by bmoshirian** [xmartlabs/Eureka#861]
I am trying to work out how to dynamically add x number of rows to the bottom of a section based on how many times the user presses ButtonRow(). These rows are the same as the ones loaded by default. I have searched high and low, but to little success.

e.g.
```
Section()
<<<NameRow("Add Individual Name") 
<<< ButtonRow("Add Another Name"){
        (sudo code:) .onCellSelection{
              (ADD ROW FROM ABOVE)
        }
}

```
The Output would be:
John Smith
Add another Name

and it becomes
John Smith
Tim Smith
Jane Smith
George Smith
Add another Name

etc.

This functionality would be great to add to the Eureka project for those working with groups of people.

Currently using:
Xcode 8
Swift 3
Eureka 2.00 - beta -1

**Comment by starr0stealer** [comment]
@bmoshirian 

This is possible with Eureka, in order to do so you will need to assign the `Section` to a _variable_. Then assign the `ButtonRow` to its own `Section`. Once you have the `Section` as a variable, you can build the `form` as you normally would.

ie.

```swift
    func initializeForm() {
        let updatableSection = Section()

        form
            +++ updatableSection
                <<< TextRow() { /* title, etc */ }
            +++ Section()
                <<< ButtonRow() { /* title, etc */ }
                .onCellSelection { row in
                    updatableSection
                        <<< TextRow() { /* title, etc */ }
                }
    }
```

**Comment by bmoshirian** [comment]
Thank you @starr0stealer
