### ISSUE TITLE
Unable to eliminate the spacing above the section header

### ISSUE THREAD

**Issue by rahimizad** [xmartlabs/Eureka#863]
Still unable to eliminate the grey space above the section just below the navigation bar... How can I eliminate that space all together?

            Section() { section in
                section.header?.height = { 0 }
                section.footer?.height = { 0 }
                section.tag = "duration_s"
            }
![simulator screen shot jan 2 2017 8 42 52 am](https://cloud.githubusercontent.com/assets/777742/21593000/98ba6328-d0c7-11e6-97af-ea25a4cf19b4.png)

**Comment by rahimizad** [comment]
Solved by:

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Eliminate the redundance space above the first section
        automaticallyAdjustsScrollViewInsets = false
        tableView?.contentInset = UIEdgeInsetsMake(33, 0, 0, 0)

**Comment by Tibb** [comment]
@rahimizad thanks! But it's probably:
`tableView?.contentInset = UIEdgeInsetsMake(-33, 0, 0, 0)`

Your code adds more space with the 33 value ;)

**Comment by mtnbarreto** [comment]
The trick to change the section height https://github.com/xmartlabs/Eureka/issues/80#issuecomment-226708469
