### ISSUE TITLE
section header setup

### ISSUE THREAD

**Issue by yurevich1** [xmartlabs/Eureka#864]
What is the best approach to setup section header? I just want to set the font as bold (or italic).

**Comment by starr0stealer** [comment]
@yurevich1 

Check out the `Custom View` section in the main Read Me

https://github.com/xmartlabs/Eureka#custom-view

Without building the `Header` yourself I don't think you will get access to is during internal construction. That would be for good reasons, for example if you increase the size (bold could do this), the height needed would need to be recalculated.

Building the view with `Callback` seems like the quickest route to take, though using `Nib` "easier" for some.
