### ISSUE TITLE
How to refresh entire form after calling validate()?

### ISSUE THREAD

**Issue by emadd** [xmartlabs/Eureka#867]
I'd like to force the form to show which fields are failing (I guess this would need to trigger the cellUpdate method) validation after I've called form.validate().  Is this possible?

**Comment by emadd** [comment]
Nevermind

**Comment by pouriaalmassi** [comment]
@emadd  what was your solution?

**Comment by emadd** [comment]
@pouriaalmassi I can't remember exactly, but I think I ended up showing the first error encountered in an Alert

```
form.validate()
for row in form.rows{
    row.updateCell()
}
for row in form.rows{
    if(row.validationErrors.count > 0){
        let msg: String =  row.title! + " " + row.validationErrors[0].msg.lowercased()
        showError(error: QError.Validation(msg: msg))
    }
}
```
