### ISSUE TITLE
disable selectable row -> row is still selectable

### ISSUE THREAD

**Issue by dazeili** [xmartlabs/Eureka#872]
Is this a bug or is there a way to make a cell not selectable. The row is greyed out and gets no animation on selection, but the selectable value is assigned, and the checkmark gets toggled.

**Comment by mtnbarreto** [comment]
Could you share your form, selectableRow code so i can look into the issue?

**Comment by dazeili** [comment]
It was my mistake. Everything works fine ;).
But I said that in the answer.

LG

**Comment by infiniteNIL** [comment]
I'm having problems with this. What were you doing wrong?
