### ISSUE TITLE
Custom PushRow multiline text

### ISSUE THREAD

**Issue by msilva** [xmartlabs/Eureka#876]
I'm having trouble understanding how to do this from the documentation.  Is there a way to use the PushRow so that it presents a list of selections in the presenting controller (as it currently does), but to customize the text in each row, for multi label.  

Imagine we have the name of the selection on line 1 or a row, and a more detailed description on line 2, etc.  

I don't see how to do this.  Thanks!

**Comment by ilyapuchka** [comment]
You'll need to create a subclass of `_SelectorViewController` with your custom row type as generic parameter and create a subclass of `SelectorRow` with this controller as its generic parameter. Types hierarchy should be basically the same as for `PushRow` just with your custom selector controller in place.
