### ISSUE TITLE
UITableViewController dependency makes Eureka inflexible

### ISSUE THREAD

**Issue by alper** [xmartlabs/Eureka#877]
I'm playing around with Eureka a bit and it is an impressive library.

One thing that is making it inflexible to use is that it depends fairly rigidly on a UITableViewController (or similar). This is a component that is not recommended to be used anyway.

Since the only thing we are talking about is a list of controls, these should be usable and renderable anywhere. Some contenders of hosts for this could be UIScrollView or UICollectionView but maybe there are more?

**Comment by starr0stealer** [comment]
Eureka doesn't use `UITableViewController`, the `FormViewController` will automatically add a `UITableView` if one doesn't exist.

Eureka is built around `UITableViewCell`, making it confirm to a `UICollectionView` would add duplication to the entire framework. Being in a table it already is basically a "Scroll View".

The design choice around using Tables and Cells is following the de facto standard of how Forms are built for iOS.

I find Eureka to be quite flexible, I am still amazed by the things I have built with very little customization to the core framework. Then the Nib support just opens the doors even further, imo.

**Comment by mats-claassen** [comment]
Exactly Eureka does not depend on `UITableViewController`, just UITableView
