### ISSUE TITLE
How to set PushRow requires?

### ISSUE THREAD

**Issue by Rosenkreuz** [xmartlabs/Eureka#880]
I wanna set requir.

```
<<< PushRow<String>() {
            $0.title = "Title"
            $0.options = ["aaa", "bbb"]
            $0.value = "aaa"
}
```

**Comment by fictorial** [comment]
https://github.com/xmartlabs/Eureka/issues/261#issuecomment-255439929

**Comment by fedeojeda95** [comment]
Hi @Rosenkreuz,

Eureka now support validations for the row. You could either go with something similar to the previous comment, but I strongly recommend you check out the validation rules. The required rule is provided out of the box by Eureka!

For further information about this, please check the README and the example project, especifically the `ValidationsController`.

Hope it helps! Regards,
