### ISSUE TITLE
ButtonRow style

### ISSUE THREAD

**Issue by codeboost** [xmartlabs/Eureka#881]
Is it possible to change the style of the ButtonRow cell  ?
I'd like it to have .Value1 style and a disclosure indicator.

I've managed to have the disclosure indicator show up, by setting the ```cell.accessoryType``` in ```cellUpdate```, but how do I change the cell's style ?
``` 
row.cellSetup { (cell, row) in
   row.cellStyle = .Value1
}
```
This does *something* to the cell (text is centered and color is changed), but it doesn't change the cell style. Is that possible ?

I'm using Eureka Swift 2.3

**Comment by codeboost** [comment]
I've figured it out. The style *was* being set, but I was trying to change the detail text by setting ```row.value```, which doesn't seem to work. 

Now I just use ```cell.detailTextLabel.text = "my text"``` and it looks good.

**Comment by eliburke** [comment]
Probably as a result of changes to the underlying implementation, I now have to set the cell style in the initializer; changing it in cellSetup or cellUpdate does not work. If you want your ButtonRow to have a disclosure indicator, you can set that as well (not necessary for ButtonRowWithPresent)

            let row = ButtonRow("doit") { formRow in
                formRow.title = "Do It!"
                formRow.cellStyle = .value1
                formRow.cellUpdate { cell, cellRow in
                    cell.textLabel?.text = "left_side_label"
                    cell.detailTextLabel?.text = "right_side_label"
                    cell.accessoryType = .disclosureIndicator
                }

            let row = ButtonRowWithPresent<CustomViewController> { formRow in
                formRow.title = "Custom"
                formRow.cellStyle = .value1
                formRow.cellUpdate { cell, cellRow in
                    cell.textLabel?.text = "left_side_label"
                    cell.detailTextLabel?.text = "right_side_label"
                }
