### ISSUE TITLE
How to populate the form Values from Firebase database ?

### ISSUE THREAD

**Issue by sriteja25** [xmartlabs/Eureka#885]
I am using Eureka to create forms in my project, thanks for the great read me.

I have sucesfully saved the form values into my database. Now i am looking to populate the for values with the saved values from the firebase database. How can i achieve this ?

**Comment by cohenadair** [comment]
You'll have to observe a Fireabase Database reference child, and set your form values in the callback. See the [Read and Write Data on iOS](https://firebase.google.com/docs/database/ios/read-and-write#read_data_once) Firebase guide.

**Comment by mtnbarreto** [comment]
@sriteja25 have you get around this?

**Comment by sriteja25** [comment]
Sorry, as  we had to customise the text fields and other UIElements , so to gain control I built my own form from scratch, no longer using Eureka now.

**Comment by liaujianjie** [comment]
Hi I'm not sure if anyone is still interested in this. I'm half-done with writing an adapter to convert between Eureka-friendly values and FirebaseDatabase-friendly values. Is there any way I can identify the `Row`'s type from a `Row`?

**Comment by liaujianjie** [comment]
This works for me: https://gist.github.com/liaujianjie/9b46a95f0b6341953ad1d34e228725a1

**Comment by m-revetria** [comment]
@liaujianjie thanks for sharing your code! We'll take in mind for future reference.

I'm closing this issue.

**Comment by Hardikpans** [comment]
@sriteja25  can you tell me how did you saved value in the database?
