### ISSUE TITLE
validatesOnChangeAfterBlurred issue

### ISSUE THREAD

**Issue by jsonfellin** [xmartlabs/Eureka#886]
This is a small bug. I believe line 579 in the Core file needs to change from:

`if cell.row.validationOptions.contains(.validatesOnBlur) ||  cell.row.validationOptions.contains(.validatesOnChangeAfterBlurred) {`

to

`if cell.row.validationOptions.contains(.validatesOnBlur) ||  (cell.row.wasChanged && cell.row.validationOptions.contains(.validatesOnChangeAfterBlurred)) {`

Thanks again for the great library.

**Comment by mtnbarreto** [comment]
@jsonfellin you are right, do you want to fix it?

**Comment by jsonfellin** [comment]
Sure, I’ll submit a PR shortly.

**Comment by jsonfellin** [comment]
Any tips on submitting? It looks like I don’t have access to push a new branch.

**Comment by mats-claassen** [comment]
You should fork the repo, create a branch there and submit a pull request from that branch
