### ISSUE TITLE
TextAreaRow adds an enter when pressing next on keyboard coming from another row

### ISSUE THREAD

**Issue by Tripwire999** [xmartlabs/Eureka#887]
Eureka version: v2.0.0-beta.1
Xcode version: 8.2.1
iOS version: iOS 10.2

Consider the following code:
```swift
<<< TextRow() {
        $0.title = "Location"
        $0.value = self.locationDescription
        $0.placeholder = "Short description of location"
        }.onChange { row in
          self.locationDescription = row.value
      }
      <<< TextAreaRow("general_overview_location_remark") {
        $0.title = ""
        $0.value = self.locationRemarks
        $0.placeholder = "Tap to add a remark"
        }.onChange({ row in
          self.locationRemarks = row.value
        })
```

When typing a location description in the TextRow and pressing next on the keyboard it will automatically switch to the TextAreaRow this works perfectly fine. When TextAreaRow gets the focus it adds an Enter to the TextAreaRow before even writing a character with the keyboard so that the cursor isn't on line 1 but on line 2. The characters I enter with the keyboard are then on line 2 instead of line 1. 

Is this is a bug or default behavior?

**Comment by mtnbarreto** [comment]
the extra enter seems to be an issue.
