### ISSUE TITLE
FloatlabelRow + Action Sheet 

### ISSUE THREAD

**Issue by AyusSalleh** [xmartlabs/Eureka#888]
I try to make text field that user able to select options from action sheet picker, but when i click the text field it show normal keyboard. Anyone have example on way to do this?

here is my code:
```
 <<< TextFloatLabelRow() {
                $0.title = "Float Label Row, type something to see.."
                $0.options = []
                for i in 1...10{
                    $0.options.append("option \(i)")
                }
                $0.value = $0.options.first
            }
```

**Comment by James-Coleman** [comment]
If you want the FloatLabelRow appearance of small title above large value, try starting with an ActionSheetRow, changing the style to UITableViewCellStyle.subtitle, and customising the text size of the different labels.

**Comment by mtnbarreto** [comment]
@AyusSalleh I suggest you to take a look at issues labeled with [custom row](https://github.com/xmartlabs/Eureka/labels/custom%20row). Also look at https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/ and https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/ that explain how toi create custom rows. 

Actually, we can say that all Eureka rows are custom row, there are no difference among build-in rows and custom ones.
