### ISSUE TITLE
Error when compiling CustomRow containing UITextField with Swift 3.0

### ISSUE THREAD

**Issue by effzehn** [xmartlabs/Eureka#889]
Equivalent to #693 but here it's the FieldCell that causes problems. I am using Carthage / Xcode 8 with the 2.0.0-beta release.

The issue in FieldsCell seems remedied and I was able to use a manually built framework bundle. However, with Carthage using 2.0.0-beta release this issue pops up again.

**Comment by douglas-srs** [comment]
I have the same issue, manually compiling fixes this.

**Comment by m-revetria** [comment]
This should be working fine with the latest version, if not please open a new ticket.

Cheers
