### ISSUE TITLE
TextAreaRow placeholder unexpected cursor position when aligned to center

### ISSUE THREAD

**Issue by migue1s** [xmartlabs/Eureka#89]
The cursor is in an unexpected position when centering the placeholder (the center instead of in front). This is a visual bug and does not affect the functionality per se.

As a concrete example:
```swift
      <<< TextAreaRow("something") {
        $0.cell.textView.textAlignment = NSTextAlignment.Center
        $0.cell.placeholderLabel.textAlignment = NSTextAlignment.Center
        $0.cellUpdate({ (cell, row) -> () in
          cell.placeholderLabel.textColor = UIColor.lightGrayColor()
          cell.placeholderLabel.text = "Hello world"
        })
```

**Comment by mtnbarreto** [comment]
@migue1s  According the code you shared, `$0.cell.textView.textAlignment = NSTextAlignment.Center` makes the cursor appears in the center. If you comment the line out it appears at the left keeping the placeholder in the center.

Do you expect something different?

Regards
