### ISSUE TITLE
Segmented auto updates cell and doesn't call custom update code

### ISSUE THREAD

**Issue by iLandes** [xmartlabs/Eureka#890]
Swift 3.0, 2.0.0-beta.1

Segmented row never call  row.updateCell().

For the moment I change the valueChanged() func in SegmentedRow.swift file. It's look Ok :]

```
 func valueChanged() {
        row.value =  (row as! SegmentedRow<T>).options[segmentedControl.selectedSegmentIndex]
        row.updateCell() 
    }
```

The same kind of issue is refer for stepper row : https://github.com/xmartlabs/Eureka/issues/865

**Comment by mtnbarreto** [comment]
@iLandes 
There is no need to call updateCell there since this method is called by the library when the user tap on a segmented option. 

Why do you say updateCell is missing? Can you show me an example where you need that line of code to make it work ?

**Comment by m-revetria** [comment]
Closing this due to lack of response
