### ISSUE TITLE
Configuring the keyboard: properties gone ??

### ISSUE THREAD

**Issue by Tibb** [xmartlabs/Eureka#891]
Eureka version: 2.0.0-beta1
Xcode version: 8.2.1

Apparently, the properties you detailed in your README about the keyboard are not in the library.
`rowKeyboardSpacing`
`animateScroll`

 Here is the Core source code of the pod version:

```
open class FormViewController : UIViewController, FormViewControllerProtocol {
    
    @IBOutlet public var tableView: UITableView?
    
    private lazy var _form : Form = { [weak self] in
        let form = Form()
        form.delegate = self
        return form
        }()
    
    public var form : Form {
        get { return _form }
        set {
            _form.delegate = nil
            tableView?.endEditing(false)
            _form = newValue
            _form.delegate = self
            if isViewLoaded && tableView?.window != nil {
                tableView?.reloadData()
            }
        }
    }
    
    /// Accessory view that is responsible for the navigation between rows
    open var navigationAccessoryView : NavigationAccessoryView!
    
    /// Defines the behaviour of the navigation between rows
    public var navigationOptions : RowNavigationOptions?
    private var tableViewStyle: UITableViewStyle = .grouped
```

Weird thing: the downloaded example project isn't the same, as those properties are present.

**Comment by Tibb** [comment]
Same issue for the `RuleEqualsToRow` : not present in the latest pod version.
Here is the pod content:
![capture d ecran 2017-02-14 a 16 43 21](https://cloud.githubusercontent.com/assets/4620037/22936284/4ef0d724-f2d5-11e6-851e-e969f2966812.png)

Any help would be appreciated.. I'm not the only facing this issue apparently

**Comment by Tibb** [comment]
Same problem for the customizable ValidationError message (from [PR733](https://github.com/xmartlabs/Eureka/pull/733))
This PR isn't included in the latest POD version.

**Comment by mtnbarreto** [comment]
@Tibb please make sure that cocoapods is fetching the right Eureka version https://github.com/xmartlabs/Eureka/releases/tag/2.0.1

Are you following readme installation guide?

**Comment by DavidLari** [comment]
I was having the same problems with the beta version. Looks like 2.0.1 fixes the rowKeyboardSpacing and the animateScroll issues. Thanks!

**Comment by Tibb** [comment]
@mtnbarreto I just updated my pod: works like a charm now!
As I mentioned when I opened this issue, it was related to the 2.0.0-beta1 at the time.

Thanks for the 2.0.1 update
