### ISSUE TITLE
Ghosted 2nd section name

### ISSUE THREAD

**Issue by edasque** [xmartlabs/Eureka#894]
Eureka 2.0b1, Xcode 8.2.1, iOS 10.2

Any idea why the code in the most basic sample produces a weird ghosted 2nd section name at the bottom?

You can see it here (with my slightly modified code but I saw it with the basic example), on simulator and physical device:
<img width="389" alt="glass_and_iphone_7_ _ios_10_2__14c89_" src="https://cloud.githubusercontent.com/assets/219187/22232132/9247359e-e1b5-11e6-9c29-5a97368edd75.png">

```swift
class SettingsFormViewController: FormViewController {
  
  override func viewDidLoad() {
    super.viewDidLoad()
    form = Section("NZBGet")
      <<< URLRow { row in
        row.title = "Hostname"
        row.tag = "host"
        row.placeholder = "nzbget.smith.com"
      }
      <<< SwitchRow { row in
        row.title = "SSL"
        row.tag = "bSSL"

      }
      <<< TextRow { row in
        row.title = "Login"
        row.tag = "login"
        row.placeholder = "bob"
      }
      <<< TextRow { row in
        row.title = "Password"
        row.placeholder = "1234"
        row.tag = "password"
      }
      <<< IntRow { row in
        row.title = "Port"
        row.placeholder = "6789"
        row.tag = "port"
      }
      +++ Section("NZBGeek")
      <<< TextRow { row in
        row.title = "API Key"
        row.placeholder = "Your API key goes here"
    }
  }

}
```

**Comment by mtnbarreto** [comment]
You may have added a tableView to a VC using InterfaceBuilder but forgot to connect the outlet. Can you check?

**Comment by edasque** [comment]
That was exactly it, how did you know!?!?
