### ISSUE TITLE
 Missing argument label 'rawValue:' in call

### ISSUE THREAD

**Issue by Rosenkreuz** [xmartlabs/Eureka#898]
Why?

```swift
override func viewDidLoad() {
        super.viewDidLoad()
        form = Section("Section1") <----- Missing argument label 'rawValue:' in call
            <<< TextRow(){ row in
                row.title = "Text Row"
                row.placeholder = "Enter text here"
            }
            <<< PhoneRow(){
                $0.title = "Phone Row"
                $0.placeholder = "And numbers here"
            }
            +++ Section("Section2")
            <<< DateRow(){
                $0.title = "Date Row"
                $0.value = Date(timeIntervalSinceReferenceDate: 0)
        }
    }
```

**Comment by mtnbarreto** [comment]
It should work. I'm tested it agains master branch version and it works fine. 
Which are your Xcode Swift versions?

**Comment by Rosenkreuz** [comment]
Xcode Version 8.2.1(8C1002)
Swift3

When i did to convert swift syntax then happened this.

**Comment by mtnbarreto** [comment]
Not sure what happened but last Eureka version is already compatible with swift 3 and it was written in swift 3 syntax. 

Have you solved it?

**Comment by Rosenkreuz** [comment]
Not soved yet.
I'm now using XLForm.

**Comment by mtnbarreto** [comment]
well, you don't need to migrate Eureka if your code is already in swift 3. In fact Eureka code should never be migrated, you should choose the right version compatible with your poject swift version.

**Comment by Rosenkreuz** [comment]
New Project->pod init->pod install-> open project
then this alert
![2017-01-31 17 20 11](https://cloud.githubusercontent.com/assets/688536/22457281/227ed728-e7da-11e6-8bfb-3e18e540622c.png)

**Comment by eliteproxy7** [comment]
i keep getting this error 

i am using
 pod 'Eureka', '~> 2.0.0-beta.1'


I have Xcode Version 8.1 (8B62)
with swift 3
