### ISSUE TITLE
Would love to see a currency field / row added. (Formatters)

### ISSUE THREAD

**Issue by btripp** [xmartlabs/Eureka#9]

**Comment by mtnbarreto** [comment]
@btripp
What do you mean by currency field?
We have added support for `NSFormatter`s, look at the example project which contains a field that shows a currency value. 
Eureka gives the ability to set up any custom formatter to a field cell or create a completely new row type.

**Comment by thiagoross** [comment]
That would be nice. 

I think I know what he is talking about. I made a component to format a NSNumber given a currencyCode, for example.

What would be great is a field where you set a value (NSNumber), and a currencyCode (BRL, USD, etc..) and it formats the number for you like R$ 1.234,00 or US$ 1,234.00. A price field.

If you want to take a look at my component:
https://github.com/thiagoross/TRCurrencyTextField

**Comment by mtnbarreto** [comment]
TextField rows provided by default have a formatter property that can be used to set up any formatter.

for instance:

```swift
DecimalRow(){
        $0.useFormatterDuringInput = true
        $0.title = "Currency style"
        $0.value = 2015
        let formatter = CurrencyFormatter()
        formatter.locale = NSLocale.currentLocale()
        formatter.numberStyle = NSNumberFormatterStyle.CurrencyStyle
        $0.formatter = formatter
}
```

I think that setting up the formatter is enough and there is no need to use a different row. 
Anyway If you want to provide a default formatter customization you can extend from 
`public class FieldRow<T: Any, Cell: CellType where Cell: BaseCell, Cell: TextFieldCell, Cell.Value == T>` and accordingly configure the formatter by overriding the init.
