### ISSUE TITLE
LabelRow detailTextLabel text truncated

### ISSUE THREAD

**Issue by violetwee** [xmartlabs/Eureka#900]
Hi, I'm using the LabelRow to display calculation results. I'm having trouble when the textLabel text is long (or when I set the font size larger in Settings -> Accessibility) and it forces the detailTextLabel to truncate. 

For example:
Annual Interest 3..

I would like the detailTextLabel to show the exact value (no truncation) and the textLabel to wrap to the next line if needed. How can I do that?

I have tried setting the following:
    cell.textLabel?.adjustsFontSizeToFitWidth = true
    cell.textLabel?.numberOfLines = 0
but it's not working.

I have also tried setting cell.detailTextLabel?.adjustsFontSizeToFitWidth = true as well. It shows the exact value but the font size gets really small. Hope someone can help.

**Comment by mtnbarreto** [comment]
I think this issue is pretty similar to #762

**Comment by mtnbarreto** [comment]
let me know if the proposed suggestion in #762 works for you.

**Comment by m-revetria** [comment]
Closing this due to lack of response
