### ISSUE TITLE
Issues after upgrade Xcode 8.3/iOS10.2

### ISSUE THREAD

**Issue by mellob** [xmartlabs/Eureka#902]
Hi All,
wondering if someone could help.

I upgraded my Xcode version to 8.3 beta to support devices running iOS 10.2.

I have getting errors such as 
1. Type 'Form' does not conform to protocol 'MutableCollection'
2. Type 'Form' does not conform to protocol '_MutableIndexable'
3. Type 'Form' does not conform to protocol 'RangeReplaceableCollection'

Melvin

**Comment by mtnbarreto** [comment]
Shortly we will have a new branch containing migration to swift 3.1. Check #904 out.

**Comment by m-revetria** [comment]
Closing this, the support for Swift 3.1 is already released
