### ISSUE TITLE
DecimalRow text colour?

### ISSUE THREAD

**Issue by calebmanley** [xmartlabs/Eureka#906]
Hi,

I am unable to change the colour of the text written in the DecimalRow field?
Is this something I am overlooking or is this not possible?

**Comment by mtnbarreto** [comment]
Hi @calebmanley , this likely to be similar to #137. Basically you should use `cellUpdate` row's callback.

**Comment by calebmanley** [comment]
![screen shot 2017-01-31 at 6 03 36 pm](https://cloud.githubusercontent.com/assets/2014573/22455303/a5a799fa-e7df-11e6-8eec-2245ac9d71f7.png)

Thanks for the reply @mtnbarreto 
Turns out my generic function used to set the colour can't access the DecimalRow text field as I am using the generic Row class.
Disappointing that I've had to set it all separately again.
Any idea on how this could be done better?
