### ISSUE TITLE
I can't change keyboard language in NameRow()

### ISSUE THREAD

**Issue by MarcSky** [xmartlabs/Eureka#919]
Hello!
Thanx for best form builder.
I from Russia and i have problem with changing language in keyboard. They only English, but i need Russian.
When i use uitextfield without Eureka, i can change keyboard language. What is it?
Thanx!

**Comment by huayu0723** [comment]
I had the same problem and I'll try to work on this.

**Comment by huayu0723** [comment]
Hi, @MarcSky 

Actually it's not an issue. Just use TextRow() instead, and it should resolve your problem.

**Comment by mtnbarreto** [comment]
@MarcSky have you solved this?

**Comment by MarcSky** [comment]
@mtnbarreto Yes

**Comment by AndrewBennet** [comment]
Is there a way to have both the word-capitalisation of `NameRow` and the keyboard language button availability of `TextRow`?

**Comment by AndrewBennet** [comment]
In case anyone else comes across this: the capitalisation of a `TextRow` can be set as follows:
```
let row = TextRow() {
    $0.cell.textField.autocapitalizationType = .words
}
```
