### ISSUE TITLE
Formatting section background color

### ISSUE THREAD

**Issue by yurevich1** [xmartlabs/Eureka#920]
Hi!

I've found that only this code could help to setup background color in proper way:

```swift
 var header = HeaderFooterView<UITableViewHeaderFooterView>(.class)
                                 footer.onSetupView = {view, _ in
                                     view.backgroundView = UIView(frame: view.bounds)
                                     view.backgroundView?.backgroundColor = C.sectionColor
                                 }
                                 section.header = header
 
 var footer = HeaderFooterView<UITableViewHeaderFooterView>(.class)
                                 footer.onSetupView = {view, _ in
                                     view.backgroundView = UIView(frame: view.bounds)
                                     view.backgroundView?.backgroundColor = C.sectionColor
                                 }
                                 section.footer = footer
```

Please, update the manual in the main ReadMe file. In ReadMe example only changes the background of UILabel that can only wrap the text. It doesn't fit the parent view.

**Comment by mtnbarreto** [comment]
Could you point out which is the section you want to be updated....?

**Comment by yurevich1** [comment]
Section Header and Footer > Custom View

**Comment by mtnbarreto** [comment]
Could you please make the required changes as a pull request?


I just tested our code an=d seems it works accordingly..

<img width="890" alt="screen shot 2017-02-10 at 5 17 17 pm" src="https://cloud.githubusercontent.com/assets/1746532/22844210/c450f8a4-efbb-11e6-96b1-4d402f847cdb.png">

**Comment by m-revetria** [comment]
Closing this due to lack of response

**Comment by chanonly123** [comment]
tableView.backgroundColor = .purple, changes section background color.
