### ISSUE TITLE
How to set popover arrow direction?

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [xmartlabs/Eureka#922]
Hi,

First of all, thanks for the great framework.

Is there any way to set the popover arrow direction?

I need to set direction of popover downwards. Please help me thanks.

**Comment by mtnbarreto** [comment]
Hi @ThiyagarajanShivSankaran ,

you should set up `permittedArrowDirections` property as shown below.

```swift
                    ActionSheetRow<String>() { 
                         .... 
                     }
                    .onPresent { from, to in
                        to.popoverPresentationController?.permittedArrowDirections = .up 
                    }
```

**Comment by ThiyagarajanShivSankaran** [comment]
Thank you @mtnbarreto.
