### ISSUE TITLE
How to edit cellAccessory tintColor in ListCheckCell inside PushRow

### ISSUE THREAD

**Issue by kirakik** [xmartlabs/Eureka#923]
Hello,

I've been trying to find a way to edit the tintColor of ListCheckCell without needing to fork the repo, but so far I've come up short. Has anyone ever managed to do so or have an idea on how to go about this?

```
Eureka Version: 1.7.0 (swift 2 branch)
Xcode 7.3
iOS 9.0
```

I would really appreciate any pointers!

**Comment by mtnbarreto** [comment]
Hi @kirakik , try using `onPresent` callback like this:

```swift
                    PushRow() {
                        ....
                        ...
                    }
                    .onPresent{ from, to in                        
                        to.selectableRowCellUpdate = { cell, _ in cell.tintColor = .yellow }
                    }
```
