### ISSUE TITLE
Disabled ListCheckRows still Selectable

### ISSUE THREAD

**Issue by infiniteNIL** [xmartlabs/Eureka#924]
Before submitting issues ...

We are using Eureka 2.0.0-beta1 with Xcode 8.2 and Swift 3

Here's some sample code:
```swift
        let section = SelectableSection<ListCheckRow<AdditionalSearchCriteria>>("Additional Search Criteria",
                                                                                selectionType: .singleSelection(enableDeselection: false))
        
        let options: [AdditionalSearchCriteria] = [.conforming, .nonConforming, .portfolio]
        for option in options {
            let row = ListCheckRow<AdditionalSearchCriteria> { row in
                row.title = option.rawValue
                row.selectableValue = option
                row.value = nil
                
                row.disabled = true                
                row.cellSetup { cell, row in
                    BaseCell.caliberDefaultCellSetup(cell: cell, row: row)
                }
                row.cellUpdate { cell, row in
                    BaseCell.caliberDefaultCellUpdate(cell: cell, row: row)
                }
            }
            
            section.append(row)
        }
```

When the rows in this section get disabled when the loan type field changes, you can still tap on the rows and the checkmark changes to the one you tapped on. 

I would expect that it would not respond to any taps when disabled.

**Comment by fedeojeda95** [comment]
Hi @infiniteNIL,

This is actually a small issue. If you check in the protocol `SelectableSectionType` in the source code (the `SelectableSection` conforms this protocol) theres a function called prepare which set the `onCellSelection` of the row. It's in this method that the logic for updating the selected value is executed.

There's a guard that checks that `self` is not nil. In that guard, the condition `!row.isDisabled` should be added. So, the guard would be `guard let s = self, !row.isDisabled else { return }`.

I'll add this as a issue and we'll fix it as soon as we can. 

Hope it helps! Feel free to ask any further question if you still have trouble with this.

Regards,

**Comment by JesseNoBata** [comment]
Still seeing this bug as well.
