### ISSUE TITLE
I can't add RuleGreaterThan rule into IntRow

### ISSUE THREAD

**Issue by ch4vi** [xmartlabs/Eureka#925]
I'm using carthage build from master branch, and when trying to add this rule to the row, it shows follow error

> Incorrect argument label in call (have 'rule:', expected 'ruleSet:')

```swift
<<< IntRow() {
          $0.tag = "userAge"
          $0.add(rule: RuleGreaterThan(min: UInt(18)))
          $0.add(rule: RuleRequired())
}
```
Using Xcode 8.2

**Comment by mtnbarreto** [comment]
`RuleGreaterThan` generic type is Int and not UInt so the right way to set up it is ...

```swift
$0.add(rule: RuleGreaterThan(min: Int(18)))
```

Notice I'm using Int instead of UInt.
