### ISSUE TITLE
Background and tint color of section, don't work

### ISSUE THREAD

**Issue by kwstasna** [xmartlabs/Eureka#926]
Hello.

I'm trying to change the background color and the text color of the section with the code below.

```
        form +++ Section(){ section in
            section.header = {
                var header = HeaderFooterView<UIView>(.callback({
                    let view = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 50))
                    view.backgroundColor = .black
                    view.tintColor = .white
                    return view
                }))
                header.title = "test"
                header.height = { 50 }
                return header
                }()
            }
```

Although instead of changing them, it makes them dissapear

**Comment by mtnbarreto** [comment]
The view you are using as `HeaderFooterView` must contain a UILabel to set up the title. Then you should use `onSetupView` to set up the title from section information..

```swift
var header = HeaderFooterView<YourHeaderType>(.....)
header.onSetupView = { view: YourHeaderType, _ in 
     view.yourlabel = "section title"
}
```

`HeaderFooterView` generic type should be replaced by your header view type, do not use UIView as your example shows.

**Comment by kwstasna** [comment]
Ah ok i got it now! 
Made a view and a label inside and worked!
