### ISSUE TITLE
The selection of PickerInlineRow will decide the next values

### ISSUE THREAD

**Issue by kwstasna** [xmartlabs/Eureka#927]
Hello again.
I'm trying to figure out how can i take the value of a PickerInlineRow when the user select a cell?

What i would like to do is, to have 2 PickerInlineRow

the first one will be the Country and the second will be the Capital
For example
```swift
            <<< PickerInlineRow<String>("countrytag") {
                $0.title = "Country"
                $0.options = ["Germany", "Austria"]
            }

            <<< PickerInlineRow<String>() {
                $0.title = "Capital"
               if country.value == "Germany" {  //ideal for me
                $0.options = ["Berlin"]
               } else {
                 $0.options = ["Vienna"]
               }
                
            }
```
So i saw the function .didSelect but i can't tell how to use it.
In the example there is no .didSelect function called.
Is there any way to figure it out?
Thanks a lot again!!! :smile:

**Comment by kwstasna** [comment]
So I came up with a noobie solution for now...
I've set up a variable called 

`var country: Int!`

and inside the form
```

            <<< PickerInlineRow<String>("countrytag") {
                $0.title = "Country"
                $0.options = ["Germany", "Austria"]
                
                }.onChange { row in
                    if row.value == "Germany" {
                        self.country= 1
                    } else {
                        self.country= 0
                    }
            }
            <<< PickerInlineRow<String>("loctag") {
                $0.title = "Town"
                }.onCellSelection { cell, row in
                    if self.country == 1 {
                        print("its one")
                        row.options = ["Berlin"]
                        row.reload()
                    } else {
                        print("its not one")
                        row.options = ["Vienna"]
                        row.reload()
                    }
            }
```

But there is an issue. When i select Germany in country, and then i go to Town, the options are 0.
If i press again the row of Town, then i get the value Berlin.
If i chose now Austria in Country and then i try to see Vienna in Town, i will first see Berlin and if i close it again and open it then i will see Austria. Its like the row is not being update.
Any idea why?

**Comment by santiagofm** [comment]
hey @kwstasna !
I think you could just change the `options` of the second picker from the `onChanged` block from the first picker. Haven't tested but i assume something like this should work:
```swift
<<< PickerInlineRow<String>("countrytag") {
    $0.title = "Country"
    $0.options = ["Germany", "Austria"]
}.onChange { row in
    guard let country = row.value else { return }
    
    if let townsRow = form.rowBy(tag: "loctag") as? PickerInlineRow<String> { 
        townsRow.value = nil
        townsRow.options = towns(for: country)
        townsRow.reload() // not sure if needed
    }
}

<<< PickerInlineRow<String>("loctag") {
    $0.title = "Town"
}

func towns(for country: String) -> [String] {
    if country == "Germany" {
        return ["Berlin"]
    } else {
        return ["Vienna"]
    }
}

```

Hope it helps!
Cheers

**Comment by m-revetria** [comment]
Looks like the problem can be solved with the latest comment.

Closing this due to lack of response.
