### ISSUE TITLE
When i tap on my TextRow or NameRow my view is reloaded

### ISSUE THREAD

**Issue by MarcSky** [xmartlabs/Eureka#928]
I have a very strange problem, I can not decide, for example, when I click on my NameRow or TextRow my view is reloaded, and all data you have entered is erased! Maybe it's because I use let valuesDictionary = form.values (includeHidden: true) to obtain the data from the form. Very strange error (

```swift
<<< TextRow("username") { row in
    row.title = "Name"
    if let name = KeychainTaxi.getUserUsername() {
        row.value = name
    } else {
        row.placeholder = "Your name"
    }
}
```

**Comment by santiagofm** [comment]
Hey @MarcSky, could you post the full code so we can see what's going on ? The code you posted is ok.
Cheers

**Comment by m-revetria** [comment]
Closing this due to lack of response
