### ISSUE TITLE
Capitalization: NameFloatLabelCelI

### ISSUE THREAD

**Issue by igordeoliveirasa** [xmartlabs/Eureka#930]
The custom: NameFloatLabelCell is not capitalizing words.

**Comment by igordeoliveirasa** [comment]
It's because you guys have been configured textField.keyboardType as .namePhonePad instead of .asciiCapable. Since I have no time to push now, please commit somebody! thanks.

**Comment by mtnbarreto** [comment]
thanks for contributing!
