### ISSUE TITLE
Segmentation fault: 11 eureka

### ISSUE THREAD

**Issue by eliteproxy7** [xmartlabs/Eureka#938]
I am using

pod 'Eureka', '~> 2.0.0-beta.1'

here is my code 

```swift   
    override func viewDidLoad() {
        super.viewDidLoad()
        
        var dataBaseRef: FIRDatabaseReference! { return FIRDatabase.database().reference()
        }      
        let userRef = dataBaseRef.child("users/\(FIRAuth.auth()!.currentUser!.uid)")
        
        userRef.observe(.value, with: { (snapshot) in
            let user = User(snapshot: snapshot)
            let userName = user.username
            let userEmail = user.email
            let gender = user.gender
            let phone = user.phone
            let birthday = user.birthday

            let locationUpdateTime = user.locationUpdateTimer
 
            let useridis = user.uid!
          
            self.form =
                Section(){ section in
                    section.header = {
                        var header = HeaderFooterView<UIView>(.callback({
                            let view = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 65))
                            view.backgroundColor = .red
                            return view
                        }))
                        header.height = { 65 }
                        return header
                    }()
                }
                +++ Section("General")
             
                <<< TextRow(){ row in
                    row.title = "Username"
                    row.placeholder = "Enter text here"
                    row.value = userName
                    self.updateUsername = row.value!
                    
                    }.onChange { row in
                        
                        if row.value != nil {
                            print("Object is NOT nil")
                            self.updateUsername = row.value!
                        }else{
                            
                            print("Object is nil")
                            self.updateUsername = userName!
                        }

                }
                
                
                <<< TextRow(){ row in
                    row.title = "Contact Email"
                    row.placeholder = "Enter text here"
                    row.value = userEmail
                    self.updateEmail = row.value!
                }

                +++ Section("Personal")
                
                <<< ActionSheetRow<String>() {
                    $0.title = "Gender"
                    $0.selectorTitle = "Pick your gender"
                    $0.options = ["Male","Female","Love"]
                    
                    if gender != nil {
                        $0.value = gender
                        self.updateGender = $0.value!
                    }
                    }.onChange {
                        self.updateGender = $0.value!
                }
                
              
                <<< PhoneRow(){
                    $0.title = "Phone"
                    $0.placeholder = "And number here"
                    $0.value = phone
                    
                    self.updatePhone = $0.value!
                    }.onChange { row in
                        
                        if row.value != nil {
                            print("Object is NOT nil")
                            self.updatePhone = row.value!
                            
                        }else{
                            
                            print("Object is nil")
                            self.updatePhone = phone!
                        }                       
                }
                <<< DateRow(){
                    $0.title = "Birthdate"                    
                    let localeStr = "us"
                     if birthday != nil {   
                        print("birthday is",birthday!)
                        let strTime = birthday!
                        let formatter = DateFormatter()
                        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss Z"
                        formatter.locale = NSLocale(localeIdentifier: "us") as Locale!
                        formatter.timeZone = NSTimeZone(abbreviation: "GMT+0:00") as TimeZone!
                        let dateAssing = formatter.date(from: strTime)!                        
                        $0.value = dateAssing
                        self.updateBirthday = String(describing: $0.value!)
                    }

                }.onChange { row in
                   let newDate = row.value!                
                    print("newdate = ",newDate) //Convert String to Date
                    self.updateBirthday = String(describing: newDate)
                    print("changed ",self.updateBirthday)
                    
                }
                     
                +++ Section("Settings")
                <<< ActionSheetRow<String>() {
                    $0.title = "Location Update Timer"
                    $0.selectorTitle = "Select how often to update your location"
                    $0.options = ["30 minutes","1 Hour","1 Hour 30 Minutes"]
                    
                    if locationUpdateTime != nil {
                        $0.value = locationUpdateTime
                        self.updateTime = $0.value!
                    }
                    
                    }.onChange {
                        self.updateTime = $0.value!
                }
                
                
                +++ Section("")
                <<< ButtonRow ("Update") { $0.title = "Update" }.cellUpdate { cell, row in cell.textLabel?.textColor = UIColor.white
                    cell.backgroundColor = UIColor(red:0.15, green:0.65, blue:0.76, alpha:1.0)
                    }.onCellSelection { [weak self] (cell, row) in
                        let userRef = dataBaseRef.child("users/\(FIRAuth.auth()!.currentUser!.uid)")
                        let data  = ["username": self!.updateUsername, "email": self!.updateEmail, "phone": self!.updatePhone, "gender": self!.updateGender, "birthday": self!.updateBirthday, "updateTime": self!.updateTime] as [String : Any]
                        userRef.updateChildValues(data)
                        let alertController = UIAlertController(title: "Update Completed", message: "Updates succesfully saved", preferredStyle: .alert)
                        alertController.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: nil))
                        self?.present(alertController, animated: true, completion: nil)
            }
    
        }) { (error) in
            print(error.localizedDescription)
        }
        
        
    }
```

When i run this on its own it works fine 

when i include 

JSQMessagesViewController

i get this error on the settings page

`
Showing Recent Errors Only
Check dependencies

ProcessProductPackaging "" /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR.app.xcent
    cd "/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR 6"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    

Entitlements:

{
    "application-identifier" = "J4LKJ4LJ53.com.APPNAME.APPIS.version.1";
    "aps-environment" = development;
}

    builtin-productPackagingUtility -entitlements -format xml -o /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR.app.xcent

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/Script-4DB36C33DB2067084174251E.sh
    cd "/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR 6"
    /bin/sh -c /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/Script-4DB36C33DB2067084174251E.sh

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd "/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR 6"
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name APPNAMR -Onone -DDEBUG -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -target x86_64-apple-ios10.0 -g -module-cache-path /Users/venmkhm/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -enable-testing -I /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/ALCameraViewController -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/Alamofire -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/AlamofireImage -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/Eureka -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/GPUImage -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/JSQMessagesViewController -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/JSQSystemSoundPlayer -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/Material -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/PickerView -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/Pulsator -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/SlideMenuControllerSwift -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/SwiftMessages -F /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/TPKeyboardAvoiding -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseAnalytics/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseAuth/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseCore/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseCrash/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseDatabase/Frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseInstanceID/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseMessaging/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/FirebaseStorage/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/GoogleMaps/Base/Frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/GoogleMaps/Maps/Frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/GooglePlaces/Frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Framework -F /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6 -c -j8 /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Model/Constraints.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/AppDelegate.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/SettingsViewControllerOut.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ChatLoginViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/HomeControllerViews/MenuControllerOptionsCell.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/MenuViewController/MenuViewControllerExtension.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Model/LoadingIndicator.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Model/UIViewController+DelayCall.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ActiveListController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/webDynamic.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ChannelListViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/ChatCell/ToChatCellCell.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/User.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/preferencesViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/MenuViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/PulseAnimation/LFTPulseAnimation.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/AuthService.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/MeasurementHelper.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/SwiftMessageCardView.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ProfileViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/SettingsViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/ChatCell/FromChatCell.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ForgotPasswordViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/Channel.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/areaDetails.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Model/UIView+Shadow+Radius.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/HomeViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Constants.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ActiveListController/ActiveListControllerExtensionfile.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ChatViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/LogInViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/UIImage+Gif.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/AppState.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/ViewControllers/SliderViewController.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/HomeControllerViews/WhereIsUserCell.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/Views/ActiveListCell/ActiveListCell.swift /Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/APPNAMR/CreateChannelCell.swift -output-file-map /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/Objects-normal/x86_64/APPNAMR-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/Objects-normal/x86_64/APPNAMR.swiftmodule -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR-generated-files.hmap -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR-own-target-headers.hmap -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/APPNAMR-project-headers.hmap -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Firebase/Core/Sources -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/Firebase -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseAnalytics -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseAuth -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseCore -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseCrash -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseDatabase -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseInstanceID -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseMessaging -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/FirebaseStorage -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/GoogleInterchangeUtilities -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/GoogleMaps -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/GooglePlaces -Xcc -I/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6/Pods/Headers/Public/GoogleSymbolUtilities -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/DerivedSources/x86_64 -Xcc -I/Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/venmkhm/Library/Developer/Xcode/DerivedData/APPNAMR-ccvmengswwmqiycbkscsjvokbxtr/Build/Intermediates/APPNAMR.build/Debug-iphonesimulator/APPNAMR.build/Objects-normal/x86_64/APPNAMR-Swift.h -Xcc -working-directory/Users/venmkhm/Desktop/MOVE/Firebase/Working/APPNAMR\ 6

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

Activity Log Complete    2/20/17, 7:22 PM
`

**Comment by santiagofm** [comment]
Hey @eliteproxy7, it seems to be an issue with `JSQMessagesViewController` rather than `Eureka`.
Feel free to open a new issue if you think otherwise please.
