### ISSUE TITLE
enable autocapitalization for name rows

### ISSUE THREAD

**Issue by jatraiz** [xmartlabs/Eureka#94]
First off, great library so far! We're really enjoying using it.

We ran into an issue where name rows were not auto capitalizing no matter what we did. It turns out that when you set the keyboard type to .NamePhonePad all auto capitalization is disabled. This also has the side effect of making it impossible to put any punctuation in the name rows. 

In our current project we've changed the default keyboard for the textfield in the name row to be ~~.Alphabet~~ ,ASCIICapable instead and all is well.

Just wanted to make sure this was your intention.

**Comment by mtnbarreto** [comment]
@jatraiz Thanks!

Regarding the keyboardType issue we have already fixed it changing the keyboard type to `ASCIICapable`: https://github.com/xmartlabs/Eureka/commit/2848cd8ce102ec209a0c10859e2e1a9d85303730

Regards
