### ISSUE TITLE
Localization on Validate fields

### ISSUE THREAD

**Issue by ridvank** [xmartlabs/Eureka#940]
Is there any localization on validate fields? So far I checked the source but could not see any localization.

**Comment by ijaureguialzo** [comment]
Hi, I was wondering the same. 

You can create the rule with a message and then localize the string as usual:

```swift
$0.add(rule: RuleRequired(msg:"You should really write something here..."))
```

Hope it helps.

**Comment by ridvank** [comment]
Yes, I used the same way to create localization. Thanks for your response 👍
