### ISSUE TITLE
xCode 8.3 Beta 3

### ISSUE THREAD

**Issue by mikecbone** [xmartlabs/Eureka#943]
Eureka doesn't build on the latest beta version of xCode.

Does anyone know a fix, or a forked version that works?

**Comment by dannysood** [comment]
Any update on this? Deciding on whether to use Eureka and seems like a blocker.

**Comment by jondwillis** [comment]
@mikecbone @dannysood Quick and dirty hack if you need it working now. https://github.com/xmartlabs/Eureka/pull/957

**Comment by dannysood** [comment]
Thanks @jondwillis

**Comment by vincent-peng** [comment]
Thanks @jondwillis , save our day.
Hope the PR will get review and merge soon.
