### ISSUE TITLE
ActionSheet: Display Value and Real Value

### ISSUE THREAD

**Issue by midgard** [xmartlabs/Eureka#944]
Hi,

I have a code block like this:

```swift
    <<< ActionSheetRow<String>("permission") {
        $0.title = "Viewable for";
        $0.selectorTitle = "Viewable for";
        $0.options = ["Public", "Only My Friends", "Just Me"];
        $0.value = "Public";
    }
```

But I need a real value for this options. Because I want to save 0 for "Public" or 1 for "Only My Friends"

How do I handle this?

Thanks!

**Comment by SIDGEY** [comment]
you can use :

value to int and display string like :
```
 $0.displayValueFor = { (rowValue:) in    
     return  you String;
}
```

**Comment by midgard** [comment]
@mtnbarreto can you help me?

**Comment by mtnbarreto** [comment]
Hey @midgard ! You should set up `displayValueFor` row property which allows us to provides the value description that eureka shows. You will likely have to change  ActionSheetRow<String> to ActionSheetRow<Int> or an Enum generic type of your choice. 

For more information take a look at #662, #645. 

> We're going to document the property shortly.
