### ISSUE TITLE
is It possible for supporting customise height for section and row ?

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#946]

**Comment by SIDGEY** [comment]
You can customize like: 

```
 let section = Section(){ section in
            header.height = {100}
       }
 section.header?.height = {100};
section.reload()

```

**Comment by iOSUser110** [comment]
but what if we are using custom section means from bin file..can we support multiline label in section ...and no of lines will be depend on the text coming from server- (dynamic nature) ?

**Comment by santiagofm** [comment]
hey @iOSUser110 ! Have you found a way to achieve this ?
Cheers

**Comment by m-revetria** [comment]
I'm closing this due to lack of response

**Comment by Laptopmini** [comment]
Not sure if helps, but for TextAreaRows, you can easily use a dynamic height.

```
row.textAreaHeight = TextAreaHeight.dynamic(initialTextViewHeight: NSString(string: (row.value ?? row.placeholder) ?? "").size(attributes: row.cell.textView.typingAttributes).height)
```

**Comment by ranhsd** [comment]
Hi, If this is still relevant. You can do something like this: 

```
        form
            +++ Section(){section in
                
                var header = HeaderFooterView<WelcomeFormSectionView>(.class)
                header.onSetupView = {view, section in
                    view.backgroundColor = .clear
                    view.subtitleLabel.text = "with\nmultiplelines\nmulti-line"
                    view.contentView.setNeedsLayout()
                    view.contentView.layoutIfNeeded()
                    let size = view.contentView.systemLayoutSizeFitting(UILayoutFittingCompressedSize)
                    section.header?.height = { size.height }
                }
                
                section.header = header

        }
```
Please use auto layout and make sure all constraints are in place and it will work.

Ran.

**Comment by alper** [comment]
@ranhsd I tried doing this but for me it does not work if I have a header with a custom NIB that needs to expand past its original bounds because of more content. Also my `view` does not have a `contentView`.

**Comment by kyleturner** [comment]
@ranhsd Thanks for this snippet, it worked well for our cases!

@alper If your view doesn't have a `contentView`,  it likely means you have a generic `UIView` subclass and not a subclass of `UITableViewCell` or similar derivative. 

Therefore, you can replace `view.contentView` with your view under consideration, or `view` directly, to update appropriate properties.
