### ISSUE TITLE
TextColor and Background colors - Change Header text color.

### ISSUE THREAD

**Issue by lastmboy** [xmartlabs/Eureka#95]
I've been customizing the color settings, as I have a situation where I have a darker, gradient background. I wanted the tableview to be ClearColor, and the text colors to be different colors, which wasn't a problem. However, the HeaderView text color is always a dark grey, which doesn't show up very well on darker backgrounds. However, I have had no success trying to determine where to get at the text color on the header to customize it. Can you provide an example or at least point me in the right direction regarding where I could override the header cell text color? Thanks.
![2015-11-19_13-31-28](https://cloud.githubusercontent.com/assets/6284736/11281795/db60ae6a-8ec1-11e5-9d93-bd9a53f159da.png)

**Comment by mtnbarreto** [comment]
@lastmboy look at this http://stackoverflow.com/a/27261038/2763561 if you only want to change the default header color.

If this doesn't works you can set up a whole new header section by following this reference https://github.com/xmartlabs/Eureka#section-header-and-footer

**Comment by lastmboy** [comment]
Great! Thanks for the info.
