### ISSUE TITLE
Appending Card to Section which is not a BaseType row. 

### ISSUE THREAD

**Issue by sundeepios** [xmartlabs/Eureka#951]
I am using both material UI and Eureka in our app.

And i am trying to append a card to section which is not a basetype row.

Is there any component that equals to card, so that we can append to section.

**Comment by santiagofm** [comment]
Hey @sundeepios ! 
I think you should be able to achieve what you want by implementing a custom row for the form, please take a look at the [readme](https://github.com/xmartlabs/Eureka#custom-rows).
