### ISSUE TITLE
Picker Row does not allow selection of first item when value is initially nil

### ISSUE THREAD

**Issue by rendion** [xmartlabs/Eureka#961]
When row.value is initially nil, the only way to select the first value is to scroll off the first value and then back to it.  The possible workarounds are putting a "Select" value as the first value, selecting the first value when the user selects the picker, or defaulting the value.

**Comment by hprobotic** [comment]
I working on this. In temporary, you should define new custom pickerView with xib file. on top, add 1 button let user press done.
Handle custom logic to get first value on that

**Comment by imaximix** [comment]
I worked around it by using onCellSelection.
```
row.onCellSelection() { result in
                if result.1.value == nil {
                    result.1.value = result.1.options.first
                }
            }
```

**Comment by m-revetria** [comment]
Looks like you found a solution 😄 . Closing this issue

Cheers
