### ISSUE TITLE
Hide date- and picker views after selection

### ISSUE THREAD

**Issue by corbrink** [xmartlabs/Eureka#97]
I'm using quite a few inline picker views but when selection is made you need to tap the cell to hide the view.
Is there a way to hide the picker views when a user selection was made similar to UIpickerview's pickerView.hidden = true after DidSelect?

**Comment by mats-claassen** [comment]
Hi, you can call `collapseInlineRow` from the onChange() callback of your row.
```
<<< DateTimeInlineRow("Title")
                .onChange { [weak self] row in
                    row.collapseInlineRow()
                }
```

**Comment by corbrink** [comment]
Just what I needed. Thank you for the great form!
