### ISSUE TITLE
Podspec 2.0 not working when trying to install

### ISSUE THREAD

**Issue by thedavejay** [xmartlabs/Eureka#970]
Hi,

I am a fan of Eureka!

When I tried to install it using pod install 'pod 'Eureka', '~> 2.0'
--------------------------------------------------------------

> [!] Unable to satisfy the following requirements:
> 
> - `Eureka (~> 2.0)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `Eureka (~> 2.0)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.

--------------------------------------------------------------

removing the version from the pod file it only detects 1.7. I have for now installed it by pointing to the git repo itself:

> pod 'Eureka', :tag => 'master', :git => 'https://github.com/xmartlabs/Eureka.git'

It then shows the current version to be 2.0.1:

> Installing Eureka 2.0.1 (was 1.7.0)

Seems like the pod specs need to be updated ?

Thanks,

**Comment by Laptopmini** [comment]
```
pod search Eureka
```

```
...
Versions: ..., 2.0.0-beta.1, ...
...
```

**Comment by Flightfire** [comment]
I am also having trouble. I can get version 2.0.0-beta.1 installed, but the Podspec and ReadMe say it should be version 3.0. Would really appreciate version 3 so I can integrate MultiValueSections into my app. Thanks.

**Comment by Alexsandr** [comment]
I also had this problem. I managed to install version 3. Here is my pod file

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Project' do
  
  use_frameworks!
  pod 'Eureka', :tag => 'master', :git => 'https://github.com/xmartlabs/Eureka.git'
  
end
```

I used [CocoaPods App](https://cocoapods.org/app)

Eureka 3 is in the branch of the master, for her there is no branch '~> 3.0'

**Comment by Sweeper777** [comment]
I am facing this problem too! I tried both `'~> 3.0.0'` and `'~> 3.0'` and both did not work.

**Comment by Danm72** [comment]
Same deal

**Comment by ifabiosantos** [comment]
Same here. 

`pod search Eureka` returns Eureka (2.0.1).

**Comment by mradzinski** [comment]
Same here, 3.0 doesn't exist. ```pod search Eureka``` after a ```pod repo update``` returns Eureka (2.0.1)

**Comment by ArtSabintsev** [comment]
Bumping this issue as well.

**Comment by Sweeper777** [comment]
@ArtSabintsev I used that but this error appeared:

```
[!] Error installing Eureka
[!] /usr/bin/git clone git@github.com:xmartlabs/Eureka /var/folders/3t/ckrspdms2y13_tn_rhr6rnq80000gn/T/d20170415-876-38pi2s --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/3t/ckrspdms2y13_tn_rhr6rnq80000gn/T/d20170415-876-38pi2s'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by ArtSabintsev** [comment]
You might want to try https://github.com/xmartlabs/Eureka

**Comment by ArtSabintsev** [comment]
also BUMP, as this issue needs to be fixed ASAP.

**Comment by m-revetria** [comment]
Eureka 3.0.0 has been released to Cocoapods, so now you can install it by declaring 

```
pod 'Eureka', '~> 3.0.0'
```

Thanks!

**Comment by ArtSabintsev** [comment]
Thank you!
