### ISSUE TITLE
Crash When Presenting PushRow SelectorViewController After Resigning First Responder

### ISSUE THREAD

**Issue by infiniteNIL** [xmartlabs/Eureka#971]
We are experiencing a crash when we are editing an IntRow and we tap on a PushRow. The crash is occurring when Eureka tries to present the PushRow's selector view controller, after resigning the first responder, because its cannot find the row's formViewController. A force unwrap of the result of formViewController() causes the crash.

Here's the stack trace:

![screen shot 2017-03-22 at 10 57 11 am](https://cloud.githubusercontent.com/assets/352414/24210492/edf3c568-0eee-11e7-8e9b-16e187cdaaa2.png)

And here's the code:

![screen shot 2017-03-22 at 10 57 22 am](https://cloud.githubusercontent.com/assets/352414/24210501/f66aa554-0eee-11e7-965c-03cc1bb2bee5.png)

The crash doesn't seem to occur if you dismiss the keyboard first, or scroll the form before tapping on the push row.

The crash is not specific to a particular push row. It crashes with other push rows as well, so I don't think it is related to how we are creating particular rows.

We are running on Xcode 8.2.1 with the iOS 10.2 simulator, Eureka v2.0.1

**Comment by santiagofm** [comment]
Hey @infiniteNIL !
Can't seem to reproduce the issue, would you mind sharing a sample project ? Is the `PushRow` custom ?
Cheers

**Comment by infiniteNIL** [comment]
Sorry, this awhile ago and we figured out that we were really abusing the forms and this was our fault. I would close this as it wasn't a bug in Eureka.
