### ISSUE TITLE
can i add a custom view into cell?

### ISSUE THREAD

**Issue by abellee** [xmartlabs/Eureka#972]
Eureka: 2.0.1
Xcode: 8.0
iOS: 8.1

I don't like the left margin of the cell separator.
but I can not clear it. 
so I wanna just add a custom view into the cell, I should set the height to 1.

**Comment by Laptopmini** [comment]
Read the documentation

**Comment by santiagofm** [comment]
Hey @abellee !
You didn't specify which rows you are using, but with most built-in rows you can specify a custom nib to use and you could add your separator there:
```swift
<<< TextRow() {
    $0.cellProvider = CellProvider<TextCell>(nibName: "NewCustomCell", bundle: .main)
    $0.title = "TextRow"
}
```
Cheers
