### ISSUE TITLE
memory leaks when I call `self` in `onChange`

### ISSUE THREAD

**Issue by abellee** [xmartlabs/Eureka#974]
Eureka: 2.0.1
Xcode: 8.2.1
iOS: 8.1

2017-03-25 19:32:23.952 xx[23700:40182275] Memory Leak: (
    "xx.VerifyCodeViewController",
    UIView,
    UITableView,
    UITableViewWrapperView,
    "Eureka.TextCell"
)
2017-03-25 19:32:23.953 xx[23700:40182275] Possibly Memory Leak.
In case that Eureka.TextCell should not be dealloced, override -willDealloc in Eureka.TextCell by returning NO.
View-ViewController stack: (
    "xx.VerifyCodeViewController",
    UIView,
    UITableView,
    UITableViewWrapperView,
    "Eureka.TextCell"
)

I tried to comment all codes maybe cause leaking, but still show me the memory leak after I input something into the `TextCell` and pop my `ViewController`.

**Comment by Laptopmini** [comment]
Make sure you use a weak reference to self to avoid memory leaks.

**Comment by abellee** [comment]
@Laptopmini ya I tried to add everywhere that possible to make leaking but still not work

**Comment by abellee** [comment]
@Laptopmini even though I have delete all my codes just leave the cells

**Comment by Laptopmini** [comment]
I'll jump the gun for the maintainers of this library and recommend you create an example project which reproduces this memory leak and share it here.

**Comment by Bashta** [comment]
Having the same issue! Even after using `[unowned self]` i do get leaks.

**Comment by alexsanderkhitev** [comment]
Hi @Bashta  Have you solved this problem? I also ran into the problem of memory leak.

**Comment by Bashta** [comment]
@alexsanderkhitev No. Even stripping the project down to the simplest demo produces a leak. dropped Eureka altogether since i dont have enough time to investigate where the leak occurs.

**Comment by alexsanderkhitev** [comment]
@Bashta thanks for response

**Comment by m-revetria** [comment]
Hi @abellee, thanks for letting us know about the issue.

We are going deeper into it in order to solve any memory-related issue. I'd like to know how are you getting those leaks log.

**Comment by mats-claassen** [comment]
@abellee I think #1000 and #1001 fix this issue.
