### ISSUE TITLE
How to change image size in ButtonRow

### ISSUE THREAD

**Issue by ainurb** [xmartlabs/Eureka#975]

**Comment by ainurb** [comment]
@mats-claassen @mtnbarreto @rlaferla

**Comment by Laptopmini** [comment]
Mentioning usernames will only frustrate the maintainers of the library, even more so when you clearly just deleted the Issue Instructions without reading them. 

Be patient, you're not the only one asking for help.

**Comment by ainurb** [comment]
Got it, I was in a hurry and hadn't read instructions, this is true. Already solved it, so closing issue.
