### ISSUE TITLE
Set value of fields dynamically

### ISSUE THREAD

**Issue by lenkaiser** [xmartlabs/Eureka#976]
Hi,

I want to set my the values of my fields dynamically based on the input I get from an API call.
So for this I get the answers from the server, parse it to objects and I'm trying to set the value.
However this is impossible because the rowBy(tag:) method returns a BaseRow<Optional> so I don't know what type the row is. And a BaseRow doesn't have the parameter value.

Is there a known method that allows me to check what field type it is and set the value?

```swift
ItemProducer.itemGetFormAnswers(withArguments: arguments) { (success, responseData, error) in
    MBProgressHUD.hide(for: self.view, animated: true)
    switch(success) {
    case .responseTrue:
        
        for dataObject in responseData?["data"] as! [[AnyHashable:Any]] {
            let answerObject = Answer.parseJSON(dataObject)
            if (answerObject != nil) {
                self.answers[(answerObject?.questionID)!] = answerObject
                
                //Add answer
                if let row = self.form.rowBy(tag: String(describing: answerObject?.questionID)) {
                    let date = Date.init(timeIntervalSince1970: Double((answerObject?.answer)!)!)
                    row.value = date
                    row.reload()
                }
            }
        }
        break
    default:
        print("failed to get the answers")
        break
    }
}
```

**Comment by Laptopmini** [comment]
I think you can use `.self`.

```
class A {}

class B: A {}

let x: A? = B()

if let x = x {
    print(x.self) // PRINTS: "B\n"
}
```

**Comment by lenkaiser** [comment]
Thank you for the advice, I finally went with your ledger idea. I knew that was an option but I hoped that Eureka had a more advanced option. For people interested in the execution of the idea I did the following.

```
//Loop through all the questions
for question in self.arrQuestions {
    switch(question.detailType) {
    case .checkBox:
        if let answerObject = self.answers[question.questionID] {
            let row = self.form.rowBy(tag: String(describing: answerObject.questionID)) as! CheckRow
            row.value = Bool(answerObject.answer)
            row.reload()
        }
        break
    case .dateTime:
        if let answerObject = self.answers[question.questionID] {
            let row = self.form.rowBy(tag: String(describing: answerObject.questionID)) as! DateTimeRow
            let date = Date.init(timeIntervalSince1970: Double((answerObject.answer)!)!)
            row.value = date
            row.reload()
        }
        break
        ...... etc......
```

If you have any more ideas to make this more solution more elegant please let me know as I'm still learning swift! Thank you for the advice sir!

**Comment by m-revetria** [comment]
Hi @lenkaiser, I think you can follow one of next approaches:

1. Use the `baseValue` property from `BaseRow`, so in the first code example you shown just change `row.value = date` with `row.baseValue = date`
2. Use `form.setValues`, if the tags you are using matches with the keys in a dictionary then you can do `form.setValues(dataObject)`
3. Cast the row to the appropriate type:

   ```
   //Add answer
   if let row = self.form.rowBy(tag: String(describing: answerObject?.questionID)) as? DateRow {
     let date = Date.init(timeIntervalSince1970: Double((answerObject?.answer)!)!)
     row.value = date
     row.reload()
   }
   ```

Cheers

**Comment by m-revetria** [comment]
Closing this due to lack of response
