### ISSUE TITLE
README issue - row catalog content indent incorrect?

### ISSUE THREAD

**Issue by dhmspector** [xmartlabs/Eureka#978]
Looks like  the Row Catalog section has the bit that shows the screen shots/images indented 1 one level too far and markdown is not rendering it correctly:

<img width="979" alt="eureka-readme-issue" src="https://cloud.githubusercontent.com/assets/21057/24583266/3f99ea02-16f9-11e7-8332-6083be78b8d4.png">

**Comment by Laptopmini** [comment]
I think github's release of a new flavored markdown is the reason for this.

**Comment by othomas1984** [comment]
I've just fixed this in https://github.com/xmartlabs/Eureka/pull/990
