### ISSUE TITLE
 Unbalanced calls to begin/end appearance transitions for ViewController

### ISSUE THREAD

**Issue by rokoroku** [xmartlabs/Eureka#98]
When using PushRow / MultipleSelectorRow, it sometimes causes Unbalanced calls to begin/end appearance transitions warning, and the cell doesn't update, just staying highlighted like below screenshot.

![img_0332](https://cloud.githubusercontent.com/assets/5208632/11324977/5b295b00-9184-11e5-9415-524d740e4946.jpg)

**Comment by mtnbarreto** [comment]
@rokoroku Could you please upload an example to reproduce the issue?

**Comment by gardengrocer** [comment]
@rokoroku how did you change the color of a SwitchRow? Thanks

**Comment by rokoroku** [comment]
@mtnbarreto I couldn't found what exactly causes that issue yet.
I think it may not be an Eureka-global issue, however, for your help, I nested FormViewController inside UITabBarController inside UInavigationController and I'm using UIViewController.showViewController method in my custom segue.

@gardengrocer I use BaseCell.appearance().backgroundColor property.

**Comment by gardengrocer** [comment]
@rokoroku I'm sorry, I meant text color, not background color. did you use BaseCell.appearance() for that, too? Thanks

**Comment by rokoroku** [comment]
@gardengrocer I use SwitchRow.defaultCellUpdate = { cell, row in
      cell.textLabel?.textColor = UIColor.whiteColor()
}

**Comment by gardengrocer** [comment]
@rokoroku Thank you.

**Comment by mtnbarreto** [comment]
@rokoroku I will close the issue since i couldn't reproduce the issue. I'm willing to reopen it if you share code to reproduce it.

Regards
