### ISSUE TITLE
Is / should there be a way to manually trigger evaluation of Conditions()

### ISSUE THREAD

**Issue by eliburke** [xmartlabs/Eureka#983]
I want to show a text field that offers a selection of suggested string values inline. It took me a while to get it working, and it is a little bit hacky. I'm curious if there is a better way. 

The primary "Server" field has an onCellHighlightChanged block that sets a boolean _hideServerList_ to true or false, indicating whether suggestions should be shown. Next in the form I have a set of LabelRows with a hidden Condition that looks at the _hideServerList_ bool, and the value of the "Server" field to determine if each row should show or hide. 

The hacky part is that there is no way to force the form to evaluate Conditions() other than by changing the respective form value. When the user selects the "Server" field I would like to set the boolean value and show all possible options. None of the update or reload methods seemed to work, so I ultimately had to do this:
```swift
            formRow.onCellHighlightChanged({ (cell, cellRow) in
                if cellRow.isHighlighted {
                    self.hideServerList = false
                } else {
                    self.hideServerList = true
                }
                let realValue = cellRow.value
                cellRow.value = "foobar" // hack to trigger _value.didSet in Row.swift
                cellRow.value = realValue
            })
```

Here's a gif showing what I did
![selection](https://cloud.githubusercontent.com/assets/2371768/24616165/533785a4-185e-11e7-9c5d-b746b55a4b38.gif)

**Comment by mats-claassen** [comment]
So, automatic evaluation is only executed on value changes of a row. In other cases you have to trigger this.
You can use the `evaluateHidden` function of a row to force it to evaluate if it should be hidden. So if you store your LabelRow's in an array you can loop over it and call `evaluateHidden` on each of them
