### ISSUE TITLE
The cell after the scroll is highlighted again.

### ISSUE THREAD

**Issue by alexsanderkhitev** [xmartlabs/Eureka#987]
Hello! I have a problem with the last cell in the table, for example I click on it, it is highlighted, in the cell itself I use this code so that after clicking it, it was not selected since I show another controller. The problem is that with the scrolling of the table, when the given cell is not in the field of vision, and then we see it again, it is highlighted. I tried several different options and set a breakpoint, but that does not help.  Because of what it can be? How to fix it?

My code in cell

```
  override func didSelect() {
        super.didSelect()
        isSelected = false
        presentProfileAboutMeVC()
    }
```

**Comment by mtnbarreto** [comment]
Hi @alexsanderkhitev Which is the cell that is causing the issue?

**Comment by alexsanderkhitev** [comment]
Hi @mtnbarreto This was my custom cell, inherited by the standard `Cell <CardDetailCellModel>, CellType`, but the project changed the requirements and this cell, it was no longer needed and I deleted it. With the remaining cells, this behavior was not observed. If this problem occurs the next time, I will share the cell code with you.

By the way, will you make a new release of Eureka?
