### ISSUE TITLE
can you provide the support for floating label in the form ?

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#988]
I love this library. I used it everywhere and now for some screens need to implement floating label ,  dont want to remove this library support ?
Is there any solution for floating textfield label with Eureka

**Comment by eliburke** [comment]
It's available in the example project. Just grab a copy of:
./Example/Helpers/FloatLabelTextField.swift
and all of the *FloatLabelRow" classes in ./Example/CustomCells.swift (approx lines 138 to 506) and add them directly to your project.

**Comment by mtnbarreto** [comment]
@iOSUser110 Could you successfully integrate FloatLabelTextField into your project?
We will release it under [EurekaCommunity](https://github.com/EurekaCommunity) github account, which also has other eureka custom rows.

**Comment by iOSUser110** [comment]
I added the code mentioned by @eliburke ,but getting issue as Type '_FloatLabelCell<T>' does not conform to protocol 'TextFieldCell'

**Comment by iOSUser110** [comment]
and is it possible in this library to support beatification of FloatLabelTextfield as in library SkyFloatingLabelTextField. 
also they have very nice feature of invalid values. if those can be availble with Eureka library

**Comment by eliburke** [comment]
@iOSUser110 I find that XCode + Swift can be finicky about identifying compile problems consistently, but generally you should be able to figure out what it wants. For example, I commented out the textField property, and got your error and it spells it out:
<img width="1301" alt="screen shot 2017-04-19 at 8 12 37 am" src="https://cloud.githubusercontent.com/assets/2371768/25179562/7256899a-24d8-11e7-9a7c-36786df4cccb.png">
If you can't get the tooltip to appear, the Build Errors tab (triangle with exclamation point) also lists errors.

Whatever it is complaining about is probably a typo or cut-and-paste mistake.

**Comment by santiagofm** [comment]
https://github.com/EurekaCommunity/FloatLabelRow
