### ISSUE TITLE
How to customize ImageRow to display image from a xib 

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#993]
I am looking to customize the ImageRow to take advantage of the ImagePickerController that comes with it and unable to figure out how to do it. I have 2 image customization scenarios

1) Display a profile image at the center of the cell

Here's what I tried:
I created a xib that has that has imageview in the center of the tableviewcell . Then I  sub-classed cell and added to ImageRow per the suggestion at below link. https://github.com/xmartlabs/Eureka#subclassing-cells-using-the-same-row

```swift
<<< ImageRow() {
    $0.cellProvider = CellProvider<ProfilePhotoCell>(nibName: "ProfilePhoto", bundle:Bundle.main)
}
```

However, I get an error.

2) I want to check if it is possible to extend an ImageRow by having a collection view within the imageRow that contains one cell per image added from image source (camera/photo library) and a default "+" imageview collectionview cell that when clicked presents the ImagePickerController. This is for ability to show multiple pictures added horizontally and be able to clear an added picture by tap on an existing picture. Similarly, ability to delete pictures by tapping on a given picture.

Any pseudocode on how to achieve the above scenario would be helpful.

Thanks in advance

**Comment by 48clyde** [comment]
Hi rajeshmani27,

I wanted to customize the cell as well, and ended up modifying _ImageRow to split it into a Row and a Cell. I think it is a bit back-to-front, the cell holds the value and not the row which I think is wrong.

However, it works for now.


The new ImageCell
```
open class ImageCell: BaseCell, CellType {
    public typealias Value = UIImage
    public var row: RowOf<UIImage>!
    @IBOutlet weak var viewImage : UIImageView?
}
```

The modified _ImageRow with the new header and the call to CellProvider in the init.

```
//MARK: Row
open class _ImageRow<Cell: CellType>: SelectorRow<ImageCell, ImagePickerController>  where Cell: BaseCell, Cell: TypedCellType, Cell.Value == UIImage {

    open var sourceTypes: ImageRowSourceTypes
    open internal(set) var assetURL: URL?
    open var clearAction = ImageClearAction.yes(style: .destructive)
    private var _sourceType: UIImagePickerControllerSourceType = .camera
    
    public required init(tag: String?) {
        sourceTypes = .All
        super.init(tag: tag)
        cellProvider = CellProvider<ImageCell>(nibName: "ImageCell")
        
        presentationMode = .presentModally(controllerProvider: ControllerProvider.callback { return ImagePickerController() }, onDismiss: { [weak self] vc in
            self?.select()
            vc.dismiss(animated: true)
        })
        self.displayValueFor = nil
        
    }
```

**Comment by santiagofm** [comment]
Hey @rajeshmani27 !
First of all which `ImageRow` are you using ? The one in the Example project or [ImageRow](https://github.com/EurekaCommunity/ImageRow) ?

The problem with scenario 1 is that the image that is picked gets set as the `accessoryView` of your cell which is at the right of the cell and you can't it's position.
As for scenario 2, it's pretty complex on it's own and i don't see any advantages on extending the `ImageRow`, instead i would recommend you to implement a custom row taking ideas from it.

If you have any issues doing this please feel free to post and share code so we can discuss and help you!
Cheers

**Comment by rajeshmani27** [comment]
I am using the ImageRow from the Eureka Community. I got it work by overriding _ImageRow class as follows:
final class CustomImageRow : _ImageRow<ProfilePhotoCell>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<ProfilePhotoCell>(nibName: "ProfilePhoto")
    }
    
    open override func customUpdateCell() {
        
        super.customUpdateCell()
        cell.accessoryType = .none
        cell.accessoryView = nil
        
        if let image = self.value {
            
            let imageView = cell.profilePhotoImageView
            imageView?.contentMode = .scaleToFill
            imageView?.image = image
            
            //Rounded image
            imageView?.setRadius(70)
            
        }
        else{
            let imageView = cell.profilePhotoImageView
            imageView?.contentMode = .scaleToFill
            imageView?.image = #imageLiteral(resourceName: "createProfileUserLogo")
            
            //Rounded image
            imageView?.setRadius(0)
        }

        
    }
}

I am yet to implement scenario2 and wanted to check if the following approach would work
1) Add collectionView with a single "Add" cell to a custom Nib, link the nib to a custom Photos cell, row and set the cell to conform to [UIImage] array data type that stores a list of photos for the cell
2) Add logic in cellUpdate that when an element is added to photos array additional collectionview cell is added 
3) Detect tap on the cell called "Add" and present an UIImagePickerController and upon controller dismiss after photo addition, update the photos array variable
4) Detect tap on existing photocell and call "Zoom" method that shows the zoomed photo with "Delete" option. When deleted, the photos array is updated. Add logic in cellUpdate to remove the collectionviewcell

**Comment by mtnbarreto** [comment]
If you face issues extending ImageRow, you can opt by crating a custom row from scratch taking ImageRow source code as example.
