### ISSUE TITLE
Make String conform to HeaderFooterViewRepresentable

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/Eureka#994]
I want to do this:

        form +++ TextAreaRow("some tag") {
            row in
            row.section?.header = "Hello"
        }

But there is a compiler error around "some tag", saying that there is an extra argument. I think this is because Swift can't understand that it can convert the string literal to a `HeaderFooterView`, which is compatible with the required type `HeaderFooterViewRepresentable`. It would be better if `String` itself conformed to `HeaderFooterViewRepresentable`

**Comment by m-revetria** [comment]
Hi @Sweeper777, thanks for the report.

Actually you cannot create a `HeaderFooterViewRepresentable` directly with a string literal. There is a mistake in the documentation where it says so.

As the generic class `HeaderFooterView` conforms to `ExpressibleByStringLiteral` you are able to create an instance of it from a string really simple. You can do something like below:

```swift
section.header = HeaderFooterView<UIView>(stringLiteral: "Header title here")
// or
let header: HeaderFooterView<UIView> = "Header title here"
section.header = header
```

We are not currently planning to make `String` conform to `HeaderFooterViewRepresentable` in the Eureka's project. You can make it in a simple way like it's shown below:

```swift
extension String: HeaderFooterViewRepresentable {

    public var title: String? {
        get {
            return self
        }
        set(newValue) { }
    }

    public var height: (() -> CGFloat)? {
        get { return nil }
        set { }
    }

    public func viewForSection(_ section: Section, type: HeaderFooterType) -> UIView? {
        return nil
    }

}
```

Another approach would be adding a computed property to Section through an extension:


```swift
extension Section {

    var headerString: String? {
        get { return header?.title }
        set {
            let header = HeaderFooterView<UIView>.init(title: newValue)
            self.header = header
        }
    }

}
```

Regards

**Comment by Sweeper777** [comment]
Ok, thanks for the info!
