### ISSUE TITLE
How do I obtain value of selected row when using SelectableSection?

### ISSUE THREAD

**Issue by rlam3** [xmartlabs/Eureka#997]
The following function method was called in viewDidLoad.

The form loads correctly but I would like to obtain the language option selected to be updated on my app. 

How do I obtain the value for which a checkmark is on? This is only a single check row. Not multiple rows.

Also I have a save bar button item on the top right making it more user friendly. How do I obtain the right value within the updateLanguage statement? 

Thanks!

```swift
    func configureForm() -> Void {
        
        form +++
            SelectableSection<ListCheckRow<String>>("What is your prefered language?", selectionType: .singleSelection(enableDeselection: false))
        
        for option in languages {
            form.last! <<< ListCheckRow<String>(option){ listRow in
                
                let displayName = Localize.displayNameForLanguage(option)

                listRow.title = displayName
                listRow.selectableValue = option
                listRow.value = nil
            }
        }
        
    }
```

**Comment by mtnbarreto** [comment]
Depending on the selectable section type you can use one of these 2 methods exposed by SelectableSection class.

```swift
func selectedRow() -> SelectableRow?
func selectedRows() -> [SelectableRow]
```

Then, you should access `value` property to get the selected value of the row.

so the proper code is

```swift
selectableSection.selectedRow()?.value
// or
selectableSection.selectedRows()?.map { $0.value }
```

> Eureka readme points this out here: https://github.com/xmartlabs/Eureka#getting-the-selected-rows

-----------------------------------------------------------

Could you elaborate more on `Also I have a save bar button item on the top right making it more user friendly. How do I obtain the right value within the updateLanguage statement?`? I didn't understand it.

**Comment by rlam3** [comment]
@mtnbarreto How do I obtain the selectableSection? this isn't quite clear in the documentation. An gist of this would be much appreciated. Thanks! 

When I mean update language statement. 

I mean...
How am I able to determine where to put the check mark within the for loop of option in languages.
Because this is a single select row. I need to set a default check mark and make it update to the correct value.

**Comment by eliburke** [comment]
I think what @rlam3 is asking is-- how can you set a default value for the SelectableSection<>

I know that for some use cases, it is sufficient to call selectedRow() and handle a nil value. But for others, we want to show the default setting to the user so they know what the resulting behavior will be.

I could not find a built-in way to set the initial / default / current selection, but I was able to do it in a "hacky" way by tagging each row and calling didSelect() after the form was loaded:

    var selectableSection: SelectableSection<ListCheckRow<String>>!
    override func viewDidLoad() {
        super.viewDidLoad()
        selectableSection = SelectableSection<ListCheckRow<String>>("Section Header:", selectionType: .singleSelection(enableDeselection: false))
        for str in ["one", "two", "three"] {
            let row = ListCheckRow<String> { listRow in
                listRow.tag = str
                listRow.title = str
                listRow.selectableValue = str
                listRow.value = nil
            }
            channelNotifications <<< row
        }
        selectableSection.onSelectSelectableRow = { (cell, cellRow) in
            print("cell.value = \(cellRow.value)")
        }
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if let row: ListCheckRow<String> = selectableSection.rowBy(tag: "one") {
            row.didSelect()
        }
    }

**Comment by eliburke** [comment]
Ok, color me embarrassed. This is how you set a default value:
````
            form.setValues(["one" : "one"])
````
This is covered in the FAQ: 
https://github.com/xmartlabs/Eureka#how-to-set-the-form-values-using-a-dictionary
