### ISSUE TITLE
How do I take custom actions when a row is removed from a multivalued section?

### ISSUE THREAD

**Issue by jfjdud120** [xmartlabs/Eureka#998]
Eureka: 3.0.0
Xcode: 8.3

Hi.

For example, I want to get a reference to a row and print the title of it when it is removed from a multivalued section by swiping and tapping "delete" button.

In earlier version, I overrode `tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath)` and could do what I wanted.

But, in Eureka 3.0.0, I can't override it, because it is not 'open'.

If I can't override it, there must be some mechanism for doing what I want(e.g. delegate or callback, etc.), I guess.

I found a method `rowsHaveBeenRemoved(_ rows: [BaseRow], at indexes: [IndexPath])`, but Xcode says 'Declarations from extensions cannot be overridden yet.'

How can I do that?

**Comment by mtnbarreto** [comment]
Let's make the method open for now. I think it doesn't worth adding a new callback just to get multivalued section notifications.

**Comment by Laptopmini** [comment]
Bump.

**Comment by macrigiuseppe** [comment]
was this resolved?

**Comment by mtnbarreto** [comment]
For a solution take a look at #1136

**Comment by stonkeep** [comment]
See on https://stackoverflow.com/questions/48916511/why-cant-delete-row-in-eureka-demo
